!     THIS IS THE FIRST FILE OF ASTO-RELEATED ROUTINES
!
SUBROUTINE P33_1(b,a,e)
   use iso_fortran_env, only: real64
!     EQUATION 1, PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES THE SEMI-MINOR AXIS OF AN ELLIPSE FROM SEMI-MAJOR
!     AXIS AND THE ECCENTRICITY
   real(real64) A,B,E,B2
   B=DSQRT((A**2)*(1.0D0-(E**2)))
   RETURN
END
!
!
SUBROUTINE P33_2_1(R,W,O)
   use iso_fortran_env, only: real64
!     EQUATION 2-1, PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES SUBSIDIARY QUANTITIES
!     W=ARGUMENT OF PERIHELION,O=LONGITUDE OF ASCENDING NODE,R=RESULT
!     W AND O ASSUME ANGLES IN RADIANS
   real(real64) R,W,O
   R=DSIN(W)*DSIN(O)
   RETURN
END
!
!
SUBROUTINE P33_2_2(R,W,O)
   use iso_fortran_env, only: real64
!     EQUATION 2-2, PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES SUBSIDIARY QUANTITIES
!     W=ARGUMENT OF PERIHELION,O=LONGITUDE OF ASCENDING NODE,R=RESULT
!     W AND O ASSUME ANGLES IN RADIANS
   real(real64) R,W,O
   R=DSIN(W)*DCOS(O)
   RETURN
END
!
!
SUBROUTINE P33_2_3(R,W,I)
   use iso_fortran_env, only: real64
!     EQUATION 2-3, PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES SUBSIDIARY QUANTITIES
!     W=ARGUMENT OF PERIHELION,I=ANGLE OF INCLINATION
!     W AND I ASSUME ANGLES IN RADIANS
   real(real64) R,W,I
   R=DSIN(W)*DSIN(I)
   RETURN
END
!
!
SUBROUTINE P33_2_4(R,W,O)
   use iso_fortran_env, only: real64
!     EQUATION 2-4, PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES SUBSIDIARY QUANTITIES
!     W=ARGUMENT OF PERIHELION,O=LONGITUDE OF ASCENDING NODE,R=RESULT
!     W AND O ASSUME ANGLES IN RADIANS
   real(real64) R,W,O
   R=DCOS(W)*DSIN(O)
   RETURN
END
!
!
!
SUBROUTINE P33_2_5(R,W,O)
   use iso_fortran_env, only: real64
!     EQUATION 2-5, PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES SUBSIDIARY QUANTITIES
!     W=ARGUMENT OF PERIHELION,O=LONGITUDE OF ASCENDING NODE,R=RESULT
!     W AND O ASSUME ANGLES IN RADIANS
   real(real64) R,W,O
   R=DCOS(W)*DCOS(O)
   RETURN
END
!
!
SUBROUTINE P33_2_6(R,W,I)
   use iso_fortran_env, only: real64
!     EQUATION 2-6, PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES SUBSIDIARY QUANTITIES
!     W=ARGUMENT OF PERIHELION,I=ANGLE OF INCLINATION
!     W AND I ASSUME ANGLES IN RADIANS
   real(real64) R,W,I
   R=DCOS(W)*DSIN(I)
   RETURN
END
!
!
SUBROUTINE P33_2_7(R,W,O,I)
   use iso_fortran_env, only: real64
!     EQUATION 2-7, PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES SUBSIDIARY QUANTITIES
!     W=ARGUMENT OF PERIHELION,I=ANGLE OF INCLINATION,O=LONGITUDE OF ASCENDING NODE
!     W,O AND I ASSUME ANGLES IN RADIANS
   real(real64) R,W,I,O
   R=((DCOS(W)*DCOS(O))*DCOS(I))-(DSIN(W)*DSIN(O))
   RETURN
END
!
!
SUBROUTINE P33_2_8(R,W,O,I)
   use iso_fortran_env, only: real64
!     EQUATION 2-8, PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES SUBSIDIARY QUANTITIES
!     W=ARGUMENT OF PERIHELION,I=ANGLE OF INCLINATION,O=LONGITUDE OF ASCENDING NODE
!     W,O AND I ASSUME ANGLES IN RADIANS
   real(real64) R,W,I,O
   R=((DSIN(W)*DCOS(O))*DCOS(I))+(DCOS(W)*DSIN(O))
   RETURN
END
!
!
SUBROUTINE P33_PX(R,W,O,I)
   use iso_fortran_env, only: real64
!     EQUATION 3-PX,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES PX AS R
!     W=ARGUMENT OF PERIHELION,I=ANGLE OF INCLINATION,O=LONGITUDE OF ASCENDING NODE
!     W,O AND I ASSUME ANGLES IN RADIANS
   real(real64) R,W,I,O
   R=(DCOS(W)*DCOS(O))-((DSIN(W)*DSIN(O))*DCOS(I))
   RETURN
END
!
!
SUBROUTINE P33_PY(R,W,O,I,E)
   use iso_fortran_env, only: real64
!     EQUATION 3-PY,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES PY AS R
!     W=ARGUMENT OF PERIHELION,I=ANGLE OF INCLINATION,O=LONGITUDE OF ASCENDING NODE
!     E=ANGLE OF THE OBLIQUITY OF THE ECLIPTIC
!     W,O AND I ASSUME ANGLES IN RADIANS
   real(real64) R,W,I,O,T8,T3,E
   T8=((DSIN(W)*DCOS(O))*DCOS(I))+(DCOS(W)*DSIN(O))
   T3=DSIN(W)*DSIN(I)
   R=(T8*DCOS(E))-(T3*DSIN(E))
   RETURN
END
!
!
SUBROUTINE P33_PZ(R,W,O,I,E)
   use iso_fortran_env, only: real64
!     EQUATION 3-PZ,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES PZ AS R
!     W=ARGUMENT OF PERIHELION,I=ANGLE OF INCLINATION,O=LONGITUDE OF ASCENDING NODE
!     E=ANGLE OF THE OBLIQUITY OF THE ECLIPTIC
!     W,O AND I ASSUME ANGLES IN RADIANS
   real(real64) R,W,I,O,T8,T3,E
   T8=((DSIN(W)*DCOS(O))*DCOS(I))+(DCOS(W)*DSIN(O))
   T3=DSIN(W)*DSIN(I)
   R=(T3*DCOS(E))+(T8*DSIN(E))
   RETURN
END
!
!
SUBROUTINE P33_QX(R,W,O,I,E)
   use iso_fortran_env, only: real64
!     EQUATION 3-QX,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES QX AS R
!     W=ARGUMENT OF PERIHELION,I=ANGLE OF INCLINATION,O=LONGITUDE OF ASCENDING NODE
!     E=ANGLE OF THE OBLIQUITY OF THE ECLIPTIC
!     W,O AND I ASSUME ANGLES IN RADIANS
   real(real64) R,W,I,O,T2,T4,E
   T2=DSIN(W)*DCOS(O)
   T4=DCOS(W)*DSIN(O)
   R=-T2-(T4*DCOS(I))
   RETURN
END
!
!
SUBROUTINE P33_QY(R,W,O,I,E)
   use iso_fortran_env, only: real64
!     EQUATION 3-QY,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES QY AS R
!     W=ARGUMENT OF PERIHELION,I=ANGLE OF INCLINATION,O=LONGITUDE OF ASCENDING NODE
!     E=ANGLE OF THE OBLIQUITY OF THE ECLIPTIC
!     W,O AND I ASSUME ANGLES IN RADIANS
   real(real64) R,W,I,O,T6,T7,E
   T6=DCOS(W)*DSIN(I)
   T7=((DCOS(W)*DCOS(O))*DCOS(I))-(DSIN(W)*DSIN(O))
   R=(T7*DCOS(E))-(T6*DSIN(E))
   RETURN
END
!
!
SUBROUTINE P33_QZ(R,W,O,I,E)
   use iso_fortran_env, only: real64
!     EQUATION 3-QZ,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES QZ AS R
!     W=ARGUMENT OF PERIHELION,I=ANGLE OF INCLINATION,O=LONGITUDE OF ASCENDING NODE
!     E=ANGLE OF THE OBLIQUITY OF THE ECLIPTIC
!     W,O AND I ASSUME ANGLES IN RADIANS
   real(real64) R,W,I,O,T6,T7,E
   T6=DCOS(W)*DSIN(I)
   T7=((DCOS(W)*DCOS(O))*DCOS(I))-(DSIN(W)*DSIN(O))
   R=(T6*DCOS(E))+(T7*DSIN(E))
   RETURN
END
!
!
SUBROUTINE P33_AX(R,A,PX)
   use iso_fortran_env, only: real64
!     EQUATION 4-AX,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES AX AS R
!     A=SEMI-MAJOR AXIS, AND PX
   real(real64) A,PX
   R=A*PX
   RETURN
END
!
!
SUBROUTINE P33_AY(R,A,PY)
   use iso_fortran_env, only: real64
!     EQUATION 4-AY,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES AY AS R
!     A=SEMI-MAJOR AXIS, AND PY
   real(real64) A,PY
   R=A*PY
   RETURN
END
!
!
SUBROUTINE P33_AZ(R,A,PZ)
   use iso_fortran_env, only: real64
!     EQUATION 4-AZ,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES AZ AS R
!     A=SEMI-MAJOR AXIS, AND PZ
   real(real64) A,PZ
   R=A*PZ
   RETURN
END
!
!
SUBROUTINE P33_BX(R,A,QX)
   use iso_fortran_env, only: real64
!     EQUATION 4-BX,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES BX AS R
!     A=SEMI-MAJOR AXIS AND QX
   real(real64) A,QX
   R=A*QX
   RETURN
END
!
!
SUBROUTINE P33_BY(R,A,QY)
   use iso_fortran_env, only: real64
!     EQUATION 4-BY,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES BY AS R
!     A=SEMI-MAJOR AXIS AND QY
   real(real64) A,QY
   R=A*QY
   RETURN
END
!
!
SUBROUTINE P33_BZ(R,A,QZ)
   use iso_fortran_env, only: real64
!     EQUATION 4-BZ,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES BZ AS R
!     A=SEMI-MAJOR AXIS AND QZ
   real(real64) A,QZ
   R=A*QZ
   RETURN
END
!
!
SUBROUTINE P33_M(R,N,SMALLT,BIGT)
   use iso_fortran_env, only: real64
!     EQUATION 6,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES M, THE MEAN ANOMOLY AS R
!     BIGT IS THE TIME OF PEIHELION PASSAGE, N=MEAN MOTION,SMALLT = TIME
   real(real64) N,SMALLT,BIGT,R
   R=N*(SMALLT-BIGT)
   RETURN
END
!
!
SUBROUTINE P33_R(R,A,E,LARGEE)
   use iso_fortran_env, only: real64
!     EQUATION 7,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES r-DISTANCE TO THE SUN AS R
!     A=SEMI-MAJOR AXIS, E=ECCENTRICITY,LARGEE=ECCENTRIC ANOMOLY
   real(real64) R,A,E,LARGEE
   R=A*(1.0D0-(E*DCOS(LARGEE)))
   RETURN
END
!
!
SUBROUTINE P33_X(R,AX,E,LARGEE,BX)
   use iso_fortran_env, only: real64
!     EQUATION 8,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES X-HELIOCENTRIC COORDINATE AS R
!     E=ECCENTRICITY,LARGEE=ECCENTRIC ANOMOLY
!     AX AND BX FROM ABOVE ROUTINES
   real(real64) R,A,E,LARGEE,AX,BX
   R=(AX*(DCOS(LARGEE)-E))+(BX*DSIN(LARGEE))
   RETURN
END
!
SUBROUTINE P33_Y(R,AY,E,LARGEE,BY)
   use iso_fortran_env, only: real64
!     EQUATION 8,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES Y-HELIOCENTRIC COORDINATE AS R
!     E=ECCENTRICITY,LARGEE=ECCENTRIC ANOMOLY
!     AY AND BY FROM ABOVE ROUTINES
   real(real64) R,A,E,LARGEE,AY,BY
   R=(AY*(DCOS(LARGEE)-E))+(BY*DSIN(LARGEE))
   RETURN
END
!
SUBROUTINE P33_Z(R,AZ,E,LARGEE,BZ)
   use iso_fortran_env, only: real64
!     EQUATION 8,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES Z-HELIOCENTRIC COORDINATE AS R
!     E=ECCENTRICITY,LARGEE=ECCENTRIC ANOMOLY
!     AZ AND BZ FROM ABOVE ROUTINES
   real(real64) R,A,E,LARGEE,AZ,BZ
   R=(AZ*(DCOS(LARGEE)-E))+(BZ*DSIN(LARGEE))
   RETURN
END
!
!
SUBROUTINE P33_R2(R,X,Y,Z)
   use iso_fortran_env, only: real64
!     EQUATION 9,PAGE 33, ORBITS FOR AMATEURS WITH A MICROCOMPUTER
!     THIS ROUTINE COMPUTES R SQUARED AS A CHECK
   real(real64) R,X,Y,Z
   R=(X**2)+(Y**2)+(Z**2)
   RETURN
END
!
!
!
