!
!       DIFFERENTIAL RAY TRACES
!
! SUB FRFDIF.FOR
SUBROUTINE FRFDIF
!
!     FULL RAY AIMING PRE 2/10/2006, KEPT AS A BACKUP
!
   use DATLEN
   use DATMAI
   use mod_surface
   use mod_system, only: sys_scx, sys_scy, sys_ray_aiming
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       DIFFERENTIAL RAY WITH RESPECT TO A CHANGE IN RAY HEIGHT AT
!       SURFACE 0.
!       DIFFERENTIAL RAY TRACE. THIS IS A SET OF
!       CLOSE RAYS TO THE RAY WHICH
!       ARE TRACED
!       FROM THE ORIGINAL OBJECT
!       POINT PLUS SOME DELTA AT NEWOBJECT TOWARD THE
!       CHIEF RAY LOCATION AT SURFACE NEWREF
!
   INTEGER I,KKK
!
   real(real64) DDELX,DDELY,TARX,TARY,YANG,XANG &
   &,D11,D12,D21,D22,DET,MF1,MF2,SHIFTX,SHIFTY,HIT,&
   &MAG,LSTART,MSTART,NSTART,XPARTX,YPARTX,XPARTY,YPARTY &
   &,LOLD,MOLD,NOLD,XC1,YC1,ZC1,XL,XM,XN,YL,YM,YN &
   &,ZPARTX,ZPARTY
!
   real(real64) SIG,X,XHT,YHT,ZHT,XSCYFAC,YSCYFAC &
   &,Y,Z,L,M,N,X1ONE,Y1ONE,&
   &X1LAST,Y1LAST,RXONE,RYONE,RXLAST,RYLAST
!
   LOGICAL DELFAIL
!
!
   SREFDIFEXT=.TRUE.
!     PROPER INITIALIZE PROCEEDURE 3/3/96
   R_X=0.0D0
   R_Y=0.0D0
   R_Z=0.0D0
   XOLD=0.0D0
   YOLD=0.0D0
   ZOLD=0.0D0
   LOLD=0.0D0
   MOLD=0.0D0
   NOLD=0.0D0
!
!       NOTE: CHIEF RAY IS ALWAYS AIMED TO THE VERTEX OR LOCAL
!       ORIGIN OF THE REFERENCE SURFACE OR TO THE "CENTER"
!       OF THE CLEAR APERTURE ON THE REFERENCE SURFACE IF THERE IS
!       A CLEAR APERTURE DEFINED. THIS ALLOWS SHIFTING THE AIMPONIT
!       BY DECENTERING THE CLEAR APERTURE!

!       THE REF OBJECT HEIGHTS ARE:
!       (AT THE OBJECT SURFACE)
   XHT=REFRY(1,NEWOBJ)
   YHT=REFRY(2,NEWOBJ)
   ZHT=REFRY(3,NEWOBJ)
!
!       THE FOLLOWING ARE INITIAL VALUES FOR VARIABLES USED IN
!       AIMING THE REFERENCE RAY AT THE CENTER OF THE REFERENCE
!       SURFACE.
!
!       SET INITIAL VALUES FOR X1ONE, Y1ONE, X1LAST AND Y1LAST
!
   X1ONE=-99999.9D0
   Y1ONE=-99999.9D0
   X1LAST=-99999.9D0
   Y1LAST=-99999.9D0
!
!       SET INITIAL VALUES FOR RXONE, RYONE, RXLAST AND RYLAST
   RXONE=-99999.9D0
   RYONE=-99999.9D0
   RXLAST=-99999.9D0
   RYLAST=-99999.9D0
!
   FOB0=0
   DDELX=0.001D0
   DDELY=0.001D0
!
!       FIRST XZ PLANE
   IF(XHT.NE.0.0D0)&
   &SIG=XHT/DABS(XHT)
   IF(XHT.EQ.0.0D0)&
   &SIG=1.0D0
!     WE NEED AN ANGLE WHICH HAS ITS TANGENT EQUAL TO IS RADIAN MEASURE
!     TO 10 DIGITS THIS IS TRUE AT 1 ARC SEC
!
   XSCYFAC=DABS(0.000004848D0*surf_thickness(NEWOBJ))
!
   SHIFTX=XSCYFAC*SIG
   IF(sys_scx().GE.0.0D0) SHIFTX=DABS(SHIFTX)
   IF(sys_scx().LT.0.0D0) SHIFTX=-DABS(SHIFTX)
!
   XSTRT=REFRY(1,(NEWOBJ))+(SHIFTX)
   RFDELX=SHIFTX
   YSTRT=REFRY(2,NEWOBJ)
   ZSTRT=REFRY(3,NEWOBJ)
!
!       THESE ARE THE INITIAL AIMING COORDINATES IN THE NEWOBJ+1 SURFACE
!       IN THE LOCAL COORDINATE SYSTEM OF SURFACE NEWOBJ+1
!       THESE COORDINATES NEED TO BE TRANSLATED INTO THE LOCAL
!       COORDINATE SYSTEM OF SURFACE NEWOBJ BEFORE THE STARTING
!       DIRECTION COSINES CAN BE CALCULATED USING BAKONE.FOR
!
   X1AIM=REFRY(1,(NEWOBJ+1))
   Y1AIM=REFRY(2,(NEWOBJ+1))
   Z1AIM=REFRY(3,(NEWOBJ+1))
   XC=X1AIM
   YC=Y1AIM
   ZC=Z1AIM
   IF(XC.LT.0.0D0) DDELX=DABS(DDELX)
   IF(YC.LT.0.0D0) DDELY=DABS(DDELY)
   IF(XC.GE.0.0D0) DDELX=-DABS(DDELX)
   IF(YC.GE.0.0D0) DDELY=-DABS(DDELY)
   XAIMOL=XC
   YAIMOL=YC
   ZAIMOL=ZC
   R_TX=X1AIM
   R_TY=Y1AIM
   R_TZ=Z1AIM
   CALL BAKONE
   X1AIM=R_TX
   Y1AIM=R_TY
   Z1AIM=R_TZ
!
!
!       INITIAL DIRECTION COSINES ARE
   MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
   &+((ZSTRT-Z1AIM)**2))
   LSTART=(X1AIM-XSTRT)/MAG
   MSTART=(Y1AIM-YSTRT)/MAG
   NSTART=(Z1AIM-ZSTRT)/MAG
   NINTY=.FALSE.
   IF(NSTART.LT.0.0D0) NINTY=.TRUE.
   IF(NINTY) RVSTART=.TRUE.
   IF(NSTART.EQ.0.0D0) THEN
      YANG=PII/2.0D0
      XANG=PII/2.0D0
   ELSE
      IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         YANG=0.0D0
      ELSE
         YANG=DATAN2(MSTART,NSTART)
      END IF
      IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         XANG=0.0D0
      ELSE
         XANG=DATAN2(LSTART,NSTART)
      END IF
   END IF
   X=XSTRT
   Y=YSTRT
   Z=ZSTRT
   L=LSTART
   M=MSTART
   N=NSTART
!
   KKK=0
!       DDELX AND DDELY ARE THE INITIAL INCREMENTORS FOR THE
!       DERIVATIVE CALCULATION IN NEWTON-RAPHSON SEARCH FOR
!       CHIEF RAY AIMING.
!
9  CONTINUE
   IF(surf_thickness(NEWOBJ).LT.0.0D0) REVSTR=.TRUE.
   IF(surf_thickness(NEWOBJ).GE.0.0D0) REVSTR=.FALSE.
   RV=.FALSE.
!
!       KKK COUNTS THE NUMBER OF TRIES TO GET A GOOD REFERENCE
!       SURFACE ZERO POINT INTERSECTION
   KKK=KKK+1
   REFEXT=.TRUE.
   STOPP=0
!        PROCEED
!
   IF(KKK.NE.1) THEN
!
      MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
      &+((ZSTRT-Z1AIM)**2))
      LSTART=(X1AIM-XSTRT)/MAG
      MSTART=(Y1AIM-YSTRT)/MAG
      NSTART=(Z1AIM-ZSTRT)/MAG
      NINTY=.FALSE.
      IF(NSTART.LT.0.0D0) NINTY=.TRUE.
      IF(NINTY) RVSTART=.TRUE.
      IF(NSTART.EQ.0.0D0) THEN
         YANG=PII/2.0D0
         XANG=PII/2.0D0
      ELSE
         IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            YANG=0.0D0
         ELSE
            YANG=DATAN2(MSTART,NSTART)
         END IF
         IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            XANG=0.0D0
         ELSE
            XANG=DATAN2(LSTART,NSTART)
         END IF
      END IF
      X=XSTRT
      Y=YSTRT
      Z=ZSTRT
      L=LSTART
      M=MSTART
      N=NSTART
!       KKK=1
   END IF
   LOLD=LSTART
   MOLD=MSTART
   NOLD=NSTART
   RFDIFF(1,NEWOBJ)=X
   RFDIFF(2,NEWOBJ)=Y
   RFDIFF(3,NEWOBJ)=Z
   RFDIFF(4,NEWOBJ)=L
   RFDIFF(5,NEWOBJ)=M
   RFDIFF(6,NEWOBJ)=N
   RFDIFF(13,NEWOBJ)=LOLD
   RFDIFF(14,NEWOBJ)=MOLD
   RFDIFF(15,NEWOBJ)=NOLD
   DO 10 I=NEWOBJ+1,NEWIMG

      CALL TRNSF2_ARGS(I, X, Y, Z, L, M, N)
      STOPP=0
      REFEXT=.TRUE.
      R_X=X
      R_Y=Y
      R_Z=Z
      R_L=L
      R_M=M
      R_N=N
      R_I=I
      LOLD=L
      MOLD=M
      NOLD=N
      R_XAIM=XAIMOL
      R_YAIM=YAIMOL
      R_ZAIM=ZAIMOL
      IF(REFRY(24,R_I-1).GT.0.0D0) POSRAY=.TRUE.
      IF(REFRY(24,R_I-1).LT.0.0D0) POSRAY=.FALSE.
      CALL HITSUR
      X=R_X
      Y=R_Y
      Z=R_Z
      L=R_L
      M=R_M
      N=R_N
      IF(STOPP.EQ.1) THEN
         IF(MSG) THEN
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            CALL RAY_FAILURE(I)
            OUTLYNE=&
            &'WHILE TRACING THE XZ-PLANE CHIEF DIFFERENTIAL RAY'
            CALL SHOWIT(1)
         END IF
         STOPP=1
         SREFDIFEXT=.FALSE.
         RETURN
      ELSE
         STOPP=0
         REFEXT=.TRUE.
      END IF
!       CHECK THE RAY HEIGHT AT
!       NEWREF AND ADJUST THE YAIMOL AND XAIMOL AT SURFACE
!       NEWOBJ+1 SO THAT THE RAY HEIGHT AT NEWREF IS WITHIN
!       .001 AIMTOL . MAXIMUN NUMBER OF ITERRATIONS IS
!       100.
!
      IF(I.EQ.NEWREF) THEN
!       CALCULATE TARX AND TARY
!     AIM POINT IS SAME AS THAT OF THE ORIGINAL REFRAY JUST TRACED
!
         TARY=REFRY(2,NEWREF)
         TARX=REFRY(1,NEWREF)
!
         IF((0.001D0*AIMTOL).LE.1.0D-10) HIT=1.0D-10
         IF((0.001D0*AIMTOL).GT.1.0D-10) HIT=0.001D0*AIMTOL
         IF(KKK.GT.2 &
         &.OR.sys_ray_aiming().EQ.0.0D0) THEN
!       AIM IS GOOD ENOUGH, PROCEED
            GO TO 100
!       AIM NOT GOOD ENOUGH, IMPROVE GUESS
         END IF
!
!       SET X1LAST TO X1ONE AND Y1LAST TO Y1ONE
         X1ONE=X1LAST
         Y1ONE=Y1LAST
!       SET XAIMOL AND YAIMOL TO X1LAST AND Y1LAST
         X1LAST=XAIMOL
         Y1LAST=YAIMOL
!       SET RXONE AND RYONE TO RXLAST AND RYLAST
         RXONE=RXLAST
         RYONE=RYLAST
!       SET RXLAST AND RYLAST TO X AND Y
         RXLAST=X
         RYLAST=Y
!       X AND Y ARE THE CURRENT RAY COORDINATES AT THE
!       REFERENCE SURFACE.
!
!       GUESS CASE 1, REPRESENTS THE FIRST REFINEMENT
!       OF THE AIMING POINT.
!       THIS OCCURS IF KKK=1
         IF(KKK.EQ.1) THEN
!       THIS IS CASE 1
!       IN THIS CASE WE SET THE SURFACE 1 AIMING POINTS
!       EQUAL TO THE OLD AIM POINTS PLUS A SMALL DELTA
!       IN ORDER TO CALCULATE DERIVATIVES.
!
            X1AIM=XAIMOL+DDELX
            Y1AIM=YAIMOL+DDELY
            Z1AIM=ZAIMOL
            XC=X1AIM
            YC=Y1AIM
            ZC=Z1AIM
            XC1=XC
            YC1=YC
            ZC1=ZC
            IF(surf_curvature(1).NE.0.0D0)&
            &CALL GETZEE1
            X1AIM=XC
            Y1AIM=YC
            Z1AIM=ZC
!
!       CALCULATE NEW SET OF VALUES FOR DERIVATIVES
!
            XAIMOL=XC1
            YAIMOL=YC1
            ZAIMOL=ZC1
            R_TX=X1AIM
            R_TY=Y1AIM
            R_TZ=Z1AIM
            CALL BAKONE
            X1AIM=R_TX
            Y1AIM=R_TY
            Z1AIM=R_TZ
!       NOW THE COORDINATES ARE IN THE NEWOBJ COORD SYSTEM
            GO TO 9
!       THIS IS NOT THE FIRST REFINEMENT, KKK NOT = 1
         END IF
!
         CALL RAYDERIV(X1LAST,Y1LAST,X1ONE,Y1ONE &
         &,RXONE,RYONE,RXLAST,RYLAST,D11,D12,D21,D22)
!
!       MF1=TARX-RXLAST, MF2=TARY-RYLAST
!
!       TARX AND TARY ARE THE COORDINATES OF THE CENTER
!       OF THE DECENTERED CLEAR APERTURE ON THE REFERENCE
!       SURFACE IF THERE IS A CLEAR APERTURE DEFINED AND IT
!       IS DECENTERED. IF THESE CONDITIONS DO NOT EXIST,
!       TARY AND TARX ARE BOTH IDENTICALLY 0.0D0.
!
!
         MF1=TARX-RXLAST
         MF2=TARY-RYLAST
         DELFAIL=.FALSE.
         CALL NEWDEL(MF1,MF2,D11,D12,D21,D22,DELFAIL)
         IF(DELFAIL) THEN
            RETURN
         ELSE
            GO TO 9
         END IF
!       NOT AT THE REFERENCE SURFACE, NO RAY AIMING NEEDED
      END IF
!
100   CONTINUE
!
!       THE COORDINATES OF THE DIFFERENTIAL RAY AT NEWIMG ARE:
!                       X,Y,Z WITH DIRECTION COSINES
!                       L,M,N
!       NOW RENAME THEM TO:
      RFDIFF(1,I)=X
      RFDIFF(2,I)=Y
      RFDIFF(3,I)=Z
      RFDIFF(4,I)=L
      RFDIFF(5,I)=M
      RFDIFF(6,I)=N
      RFDIFF(13,I)=LOLD
      RFDIFF(14,I)=MOLD
      RFDIFF(15,I)=NOLD
10 CONTINUE
!
   DDELX=0.001D0
   DDELY=0.001D0
!       SECOND YZ PLANE
!
   X1ONE=-99999.9D0
   Y1ONE=-99999.9D0
   X1LAST=-99999.9D0
   Y1LAST=-99999.9D0
!
!       SET INITIAL VALUES FOR RXONE, RYONE, RXLAST AND RYLAST
   RXONE=-99999.9D0
   RYONE=-99999.9D0
   RXLAST=-99999.9D0
   RYLAST=-99999.9D0
!
   IF(YHT.NE.0.0D0) SIG=YHT/DABS(YHT)
   IF(YHT.EQ.0.0D0) SIG=1.0D0
!     WE NEED AN ANGLE WHICH HAS ITS TANGENT EQUAL TO IS RADIAN MEASURE
!     TO 10 DIGITS THIS IS TRUE AT 1 ARC SEC
!
   YSCYFAC=DABS(0.000004848D0*surf_thickness(NEWOBJ))
!
   SHIFTY=YSCYFAC*SIG
   IF(sys_scy().GE.0.0D0) SHIFTY=DABS(SHIFTY)
   IF(sys_scy().LT.0.0D0) SHIFTY=-DABS(SHIFTY)
!
   YSTRT=REFRY(2,(NEWOBJ))+(SHIFTY)
   RFDELY=SHIFTY
   XSTRT=REFRY(1,NEWOBJ)
   ZSTRT=REFRY(3,NEWOBJ)
   X1AIM=REFRY(1,(NEWOBJ+1))
   Y1AIM=REFRY(2,(NEWOBJ+1))
   Z1AIM=REFRY(3,(NEWOBJ+1))
   XC=X1AIM
   YC=Y1AIM
   ZC=Z1AIM
   IF(XC.LT.0.0D0) DDELX=DABS(DDELX)
   IF(YC.LT.0.0D0) DDELY=DABS(DDELY)
   IF(XC.GE.0.0D0) DDELX=-DABS(DDELX)
   IF(YC.GE.0.0D0) DDELY=-DABS(DDELY)
   XAIMOL=XC
   YAIMOL=YC
   ZAIMOL=ZC
   R_TX=X1AIM
   R_TY=Y1AIM
   R_TZ=Z1AIM
   CALL BAKONE
   X1AIM=R_TX
   Y1AIM=R_TY
   Z1AIM=R_TZ
!
!    INITIAL DIRECTION COSINES ARE
   MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
   &+((ZSTRT-Z1AIM)**2))
   LSTART=(X1AIM-XSTRT)/MAG
   MSTART=(Y1AIM-YSTRT)/MAG
   NSTART=(Z1AIM-ZSTRT)/MAG
   NINTY=.FALSE.
   IF(NSTART.LT.0.0D0) NINTY=.TRUE.
   IF(NINTY) RVSTART=.TRUE.
   IF(NSTART.EQ.0.0D0) THEN
      YANG=PII/2.0D0
      XANG=PII/2.0D0
   ELSE
      IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         YANG=0.0D0
      ELSE
         YANG=DATAN2(MSTART,NSTART)
      END IF
      IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         XANG=0.0D0
      ELSE
         XANG=DATAN2(LSTART,NSTART)
      END IF
   END IF
   X=XSTRT
   Y=YSTRT
   Z=ZSTRT
   L=LSTART
   M=MSTART
   N=NSTART
   KKK=0
!       DDELX AND DDELY ARE THE INITIAL INCREMENTORS FOR THE
!       DERIVATIVE CALCULATION IN NEWTON-RAPHSON SEARCH FOR
!       CHIEF RAY AIMING.
!
19 CONTINUE
   IF(surf_thickness(NEWOBJ).LT.0.0D0) REVSTR=.TRUE.
   IF(surf_thickness(NEWOBJ).GE.0.0D0) REVSTR=.FALSE.
   RV=.FALSE.
!
!       KKK COUNTS THE NUMBER OF TRIES TO GET A GOOD REFERENCE
!       SURFACE ZERO POINT INTERSECTION
   KKK=KKK+1
   STOPP=0
   REFEXT=.TRUE.
!        PROCEED
!
   IF(KKK.NE.1) THEN
!    INITIAL DIRECTION COSINES ARE
      MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
      &+((ZSTRT-Z1AIM)**2))
      LSTART=(X1AIM-XSTRT)/MAG
      MSTART=(Y1AIM-YSTRT)/MAG
      NSTART=(Z1AIM-ZSTRT)/MAG
      NINTY=.FALSE.
      IF(NSTART.LT.0.0D0) NINTY=.TRUE.
      IF(NINTY) RVSTART=.TRUE.
      IF(NSTART.EQ.0.0D0) THEN
         YANG=PII/2.0D0
         XANG=PII/2.0D0
      ELSE
         IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            YANG=0.0D0
         ELSE
            YANG=DATAN2(MSTART,NSTART)
         END IF
         IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            XANG=0.0D0
         ELSE
            XANG=DATAN2(LSTART,NSTART)
         END IF
      END IF
      X=XSTRT
      Y=YSTRT
      Z=ZSTRT
      L=LSTART
      M=MSTART
      N=NSTART
!       KKK=1
   END IF
   LOLD=LSTART
   MOLD=MSTART
   NOLD=NSTART
   RFDIFF(7,NEWOBJ)=X
   RFDIFF(8,NEWOBJ)=Y
   RFDIFF(9,NEWOBJ)=Z
   RFDIFF(10,NEWOBJ)=L
   RFDIFF(11,NEWOBJ)=M
   RFDIFF(12,NEWOBJ)=N
   RFDIFF(16,NEWOBJ)=LOLD
   RFDIFF(17,NEWOBJ)=MOLD
   RFDIFF(18,NEWOBJ)=NOLD
   DO 20 I=NEWOBJ+1,NEWIMG

      CALL TRNSF2_ARGS(I, X, Y, Z, L, M, N)
      STOPP=0
      REFEXT=.TRUE.
!
      R_X=X
      R_Y=Y
      R_Z=Z
      R_L=L
      R_M=M
      R_N=N
      R_I=I
      LOLD=L
      MOLD=M
      NOLD=N
      R_XAIM=XAIMOL
      R_YAIM=YAIMOL
      R_ZAIM=ZAIMOL
      IF(REFRY(24,R_I-1).GT.0.0D0) POSRAY=.TRUE.
      IF(REFRY(24,R_I-1).LT.0.0D0) POSRAY=.FALSE.
      CALL HITSUR
      X=R_X
      Y=R_Y
      Z=R_Z
      L=R_L
      M=R_M
      N=R_N
      IF(STOPP.EQ.1) THEN
         IF(MSG) THEN
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            CALL RAY_FAILURE(I)
            OUTLYNE=&
            &'WHILE TRACING THE YZ-PLANE CHIEF DIFFERENTIAL RAY'
            CALL SHOWIT(1)
         END IF
         STOPP=1
         SREFDIFEXT=.FALSE.
         RETURN
      ELSE
         STOPP=0
         REFEXT=.TRUE.
      END IF
!       CHECK THE RAY HEIGHT AT
!       NEWREF AND ADJUST THE YAIMOL AND XAIMOL AT SURFACE
!       NEWOBJ+1 SO THAT THE RAY HEIGHT AT NEWREF IS WITHIN
!       .001 AIMTOL. MAXIMUN NUMBER OF ITERRATIONS IS
!       100.
!
      IF(I.EQ.NEWREF) THEN
!       CALCULATE TARX AND TARY
         IF(surf_clap_type(I) >= 1.AND.surf_clap_type(I) <= 6.AND.&
         &surf_array_parity(I) == 0) THEN
!       REF SURF HAS CLAP ON IT
!       SET TARGET TO CENTER OF DECENTERED CLAP, surf_clap_dim(I, 3),
!       AND surf_clap_dim(I, 4) ARE CLAP DECENTRATIONS
!       HERE IS WERE THE TARGET FOR RAY AIMING IS SET FOR THE
!       CHIEF RAY. A SIMILAR BY MORE COMPLEX SETTING IS REQUIRED
!       FOR NON-CHIEF RAYS IN THE SUBROUTINE RAYTRA.FOR
            TARY=surf_clap_dim(I, 3)
            TARX=surf_clap_dim(I, 4)
         ELSE
!       NO CLAP OF REF SURF.
            TARX=0.0D0
            TARY=0.0D0
         END IF
!
         IF((0.001D0*AIMTOL).LE.1.0D-10) HIT=1.0D-10
         IF((0.001D0*AIMTOL).GT.1.0D-10) HIT=0.001D0*AIMTOL
         IF(KKK.GT.2 &
         &.OR.sys_ray_aiming().EQ.0.0D0) THEN
!       AIM IS GOOD ENOUGH, PROCEED
            GO TO 1200
!       AIM NOT GOOD ENOUGH, IMPROVE GUESS
         END IF
!
!       SET X1LAST TO X1ONE AND Y1LAST TO Y1ONE
         X1ONE=X1LAST
         Y1ONE=Y1LAST
!       SET XAIMOL AND YAIMOL TO X1LAST AND Y1LAST
         X1LAST=XAIMOL
         Y1LAST=YAIMOL
!       SET RXONE AND RYONE TO RXLAST AND RYLAST
         RXONE=RXLAST
         RYONE=RYLAST
!       SET RXLAST AND RYLAST TO X AND Y
         RXLAST=X
         RYLAST=Y
!       X AND Y ARE THE CURRENT RAY COORDINATES AT THE
!       REFERENCE SURFACE.
!
!       GUESS CASE 1, REPRESENTS THE FIRST REFINEMENT
!       OF THE AIMING POINT.
!       THIS OCCURS IF KKK=1
         IF(KKK.EQ.1) THEN
!       THIS IS CASE 1
!       IN THIS CASE WE SET THE SURFACE 1 AIMING POINTS
!       EQUAL TO THE OLD AIM POINTS PLUS A SMALL DDELTA
!       IN ORDER TO CALCULATE DERIVATIVES.
!
            X1AIM=XAIMOL+DDELX
            Y1AIM=YAIMOL+DDELY
            Z1AIM=ZAIMOL
            XC=X1AIM
            YC=Y1AIM
            ZC=Z1AIM
            XC1=XC
            YC1=YC
            ZC1=ZC
            IF(surf_curvature(1).NE.0.0D0)&
            &CALL GETZEE1
            X1AIM=XC
            Y1AIM=YC
            Z1AIM=ZC
!
!       CALCULATE NEW SET OF VALUES FOR DERIVATIVES
!
            XAIMOL=XC1
            YAIMOL=YC1
            ZAIMOL=ZC1
            R_TX=X1AIM
            R_TY=Y1AIM
            R_TZ=Z1AIM
            CALL BAKONE
            X1AIM=R_TX
            Y1AIM=R_TY
            Z1AIM=R_TZ
!       NOW THE COORDINATES ARE IN THE NEWOBJ COORD SYSTEM
            GO TO 19
!       THIS IS NOT THE FIRST REFINEMENT, KKK NOT = 1
         END IF
!
         CALL RAYDERIV(X1LAST,Y1LAST,X1ONE,Y1ONE &
         &,RXONE,RYONE,RXLAST,RYLAST,D11,D12,D21,D22)
!
!       MF1=TARX-RXLAST, MF2=TARY-RYLAST
!
!       TARX AND TARY ARE THE COORDINATES OF THE CENTER
!       OF THE DECENTERED CLEAR APERTURE ON THE REFERENCE
!       SURFACE IF THERE IS A CLEAR APERTURE DEFINED AND IT
!       IS DECENTERED. IF THESE CONDITIONS DO NOT EXIST,
!       TARY AND TARX ARE BOTH IDENTICALLY 0.0D0.
!
!
         MF1=TARX-RXLAST
         MF2=TARY-RYLAST
         DELFAIL=.FALSE.
         CALL NEWDEL(MF1,MF2,D11,D12,D21,D22,DELFAIL)
         IF(DELFAIL) THEN
            RETURN
         ELSE
            GO TO 19
         END IF
!       NOT AT THE REFERENCE SURFACE, NO RAY AIMING NEEDED
      END IF
!
1200  CONTINUE
!
!       THE COORDINATES OF THE DIFFERENTIAL RAY AT NEWIMG ARE:
!                       X,Y,Z WITH DIRECTION COSINES
!                       L,M,N
      RFDIFF(7,I)=X
      RFDIFF(8,I)=Y
      RFDIFF(9,I)=Z
      RFDIFF(10,I)=L
      RFDIFF(11,I)=M
      RFDIFF(12,I)=N
      RFDIFF(16,I)=LOLD
      RFDIFF(17,I)=MOLD
      RFDIFF(18,I)=NOLD
!
!       STORE THESES DIFFERENTIALS
!
20 CONTINUE
   DO I=NEWOBJ,NEWIMG
      XPARTX=RFDIFF(1,I)-REFRY(1,I)
      YPARTX=RFDIFF(2,I)-REFRY(2,I)
      ZPARTX=RFDIFF(3,I)-REFRY(3,I)
      IF(XPARTX.EQ.0.0D0.AND.YPARTX.EQ.0.0D0.AND.I.NE.0)&
      &POLANGX(I)=-POLANGX(I-1)
      IF(XPARTX.EQ.0.0D0.AND.YPARTX.GT.0.0D0) POLANGX(I)=PII/2.0D0
      IF(XPARTX.EQ.0.0D0.AND.YPARTX.LT.0.0D0) POLANGX(I)=-PII/2.0D0
!
      IF(YPARTX.EQ.0.0D0.AND.XPARTX.GT.0.0D0) POLANGX(I)=0.0D0
      IF(YPARTX.EQ.0.0D0.AND.XPARTX.LT.0.0D0) POLANGX(I)=PII
      IF(XPARTX.NE.0.0D0.AND.YPARTX.NE.0.0D0)&
      &POLANGX(I)=DATAN2(XPARTX,YPARTX)
      XPARTY=RFDIFF(7,I)-REFRY(1,I)
      YPARTY=RFDIFF(8,I)-REFRY(2,I)
      ZPARTY=RFDIFF(9,I)-REFRY(3,I)
      IF(XPARTY.EQ.0.0D0.AND.YPARTY.EQ.0.0D0.AND.I.NE.0)&
      &POLANGY(I)=-POLANGY(I-1)
      IF(XPARTY.EQ.0.0D0.AND.YPARTY.GT.0.0D0) POLANGY(I)=PII/2.0D0
      IF(XPARTY.EQ.0.0D0.AND.YPARTY.LT.0.0D0) POLANGY(I)=-PII/2.0D0
!
      IF(YPARTY.EQ.0.0D0.AND.XPARTY.GT.0.0D0) POLANGY(I)=0.0D0
      IF(YPARTY.EQ.0.0D0.AND.XPARTY.LT.0.0D0) POLANGY(I)=PII
      IF(XPARTY.NE.0.0D0.AND.YPARTY.NE.0.0D0)&
      &POLANGY(I)=DATAN2(XPARTY,YPARTY)
      IF(SHIFTX.LT.0.0D0) THEN
         IF(POLANGX(I).EQ.0.0D0) THEN
            POLANGX(I)=PII
         ELSE
            IF(POLANGX(I).EQ.PII) THEN
               POLANGX(I)=0.0D0
            ELSE
               IF(POLANGX(I).NE.0.0D0.AND.POLANGX(I).NE.PII) THEN
                  POLANGX(I)=-POLANGX(I)
               END IF
            END IF
         END IF
      END IF
      IF(SHIFTY.LT.0.0D0) THEN
         IF(POLANGY(I).EQ.0.0D0) THEN
            POLANGY(I)=PII
         ELSE
            IF(POLANGY(I).EQ.PII) THEN
               POLANGY(I)=0.0D0
            ELSE
               IF(POLANGY(I).NE.0.0D0.AND.POLANGY(I).NE.PII) THEN
                  POLANGY(I)=-POLANGY(I)
               END IF
            END IF
         END IF
      END IF
      MAG=DSQRT((XPARTX**2)+(YPARTX**2)+(ZPARTX**2))
      IF(MAG.NE.0.0D0) THEN
         RXL(I)=XPARTX/MAG
         RXM(I)=YPARTX/MAG
         RXN(I)=ZPARTX/MAG
      ELSE
         RXL(I)=1.0D0
         RXM(I)=0.0D0
         RXN(I)=0.0D0
      END IF
      MAG=DSQRT((XPARTY**2)+(YPARTY**2)+(ZPARTY**2))
      IF(MAG.NE.0.0D0) THEN
         RYL(I)=XPARTY/MAG
         RYM(I)=YPARTY/MAG
         RYN(I)=ZPARTY/MAG
      ELSE
         RYL(I)=0.0D0
         RYM(I)=1.0D0
         RYN(I)=0.0D0
      END IF
   END DO
   RETURN
END
!       DIFFERENTIAL RAY TRACING
! SUB DIFRAY.FOR
SUBROUTINE DIFRAY
!
!     FULL RAY AIMING PRE 2/10/2006, KEPT AS A BACKUP
!
   use DATLEN
   use DATMAI
   use mod_surface
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       DIFFERENTIAL RAY WITH RESPECT TO A CHANGE IN RAY HEIGHT AT
!       THE REFERENCE SURFACE.
!       THIS IS A SET OF
!       CLOSE RAYS TO THE RAY TRACED WITH THE RAY COMMAND WHICH
!       ARE TRACED WITH AIMING TO THE REFERENCE SURFACE WITH A SMALL
!       SHIFT IN AIM POINT IN X AND Y AND TRACED
!       FROM THE ORIGINAL OBJECT POINT
!
!       THE FOLLOWING DEFINE AND PASS THE DIFFERENTIAL RAY TRACE
!       WITH RESPECT TO AN AIMING CHANGE AT SURFACE NEWREF
!
   INTEGER I,KKK
!
   real(real64) DDELX,DDELY,TARX,TARY,YANG,XANG,HIT,&
   &D11,D12,D21,D22,DET,MF1,MF2,RSHIFTX,RSHIFTY,SYS12,SYS13 &
   &,MAG,LSTART,MSTART,NSTART,LOLD,MOLD,NOLD &
   &,XC1,YC1,ZC1
!
   COMMON/SHIFTY/RSHIFTX,RSHIFTY
!
   real(real64) SIG,X,&
   &Y,Z,L,M,N,X1ONE,Y1ONE,XL,XM,XN,YL,YM,YN,&
   &X1LAST,Y1LAST,RXONE,RYONE,RXLAST,RYLAST
!
   LOGICAL DELFAIL
!
!
   SRAYDIFEXT=.TRUE.
!
   DDELX=0.001D0
   DDELY=0.001D0
!
!     PROPER INITIALIZE PROCEEDURE 3/3/96
   R_X=0.0D0
   R_Y=0.0D0
   R_Z=0.0D0
   XOLD=0.0D0
   YOLD=0.0D0
   ZOLD=0.0D0
   LOLD=0.0D0
   MOLD=0.0D0
   NOLD=0.0D0
!
!     SET REF AP HT
!
   IF(surf_clap_type(NEWREF) >= 1.AND.&
   &surf_clap_type(NEWREF) <= 6.AND.&
   &surf_array_parity(NEWREF) == 0) THEN
!
!       CLAP IS ON REFERENCE SURFACE
!
!       CIRCULAR CLAP
!
      IF(surf_clap_type(NEWREF) == 1.AND.&
      &surf_array_parity(NEWREF) == 0) THEN
         IF(surf_clap_dim(NEWREF, 1).LE.surf_clap_dim(NEWREF, 2)) THEN
            SYS12=surf_clap_dim(NEWREF, 1)
            SYS13=surf_clap_dim(NEWREF, 1)
         ELSE
            SYS12=surf_clap_dim(NEWREF, 2)
            SYS13=surf_clap_dim(NEWREF, 2)
         END IF
!       NOT CIRCULAR CLAP
      END IF
!        RECT CLAP
!
      IF(surf_clap_type(NEWREF) == 2.AND.&
      &surf_array_parity(NEWREF) == 0) THEN
         SYS12=surf_clap_dim(NEWREF, 1)
         SYS13=surf_clap_dim(NEWREF, 2)
!       NOT RECT CLAP
      END IF
!        ELIP CLAP
!
      IF(surf_clap_type(NEWREF) == 3.AND.&
      &surf_array_parity(NEWREF) == 0) THEN
         SYS12=surf_clap_dim(NEWREF, 1)
         SYS13=surf_clap_dim(NEWREF, 2)
!       NOT ELIP CLAP
      END IF
!        RCTK CLAP
!
      IF(surf_clap_type(NEWREF) == 4.AND.&
      &surf_array_parity(NEWREF) == 0) THEN
         SYS12=surf_clap_dim(NEWREF, 1)
         SYS13=surf_clap_dim(NEWREF, 2)
!       NOT RCTK CLAP
      END IF
!        POLY CLAP
!
      IF(surf_clap_type(NEWREF) == 5.AND.&
      &surf_array_parity(NEWREF) == 0) THEN
         SYS12=surf_clap_dim(NEWREF, 1)
         SYS13=surf_clap_dim(NEWREF, 1)
!       NOT POLY CLAP
      END IF
!        IPOLY CLAP
!
      IF(surf_clap_type(NEWREF) == 6.AND.&
      &surf_array_parity(NEWREF) == 0) THEN
         SYS12=surf_clap_dim(NEWREF, 5)
         SYS13=surf_clap_dim(NEWREF, 5)
!       NOT IPOLY CLAP
      END IF
!
   ELSE
!       NO CLAP ON REF SURF.
      SYS13=PXTRAX(1,NEWREF)
      SYS12=PXTRAY(1,NEWREF)
   END IF
!
!       SET INITIAL VALUES FOR X1ONE, Y1ONE, X1LAST AND Y1LAST
!
   X1ONE=-99999.9D0
   Y1ONE=-99999.9D0
   X1LAST=-99999.9D0
   Y1LAST=-99999.9D0
!
!       SET INITIAL VALUES FOR RXONE, RYONE, RXLAST AND RYLAST
   RXONE=-99999.9D0
   RYONE=-99999.9D0
   RXLAST=-99999.9D0
   RYLAST=-99999.9D0
!
   FOB0=0
!
!       FIRST XZ PLANE
   SIG=SYS13/DABS(SYS13)
   RSHIFTX=DIFTOL*DBLE(INT(SIG))
!
   XSTRT=RAYRAY(1,NEWOBJ)
   RSHIFTX=DABS(RSHIFTX)
   DELX=DABS(RSHIFTX)
   IF(W2.LT.0.0D0) DELX=-DELX
   YSTRT=RAYRAY(2,NEWOBJ)
   ZSTRT=RAYRAY(3,NEWOBJ)
!       THE INITIAL AIMING POINT IN NEWOBJ+1 IN NEWOBJ+1 COORDINATES IS:
   X1AIM=RAYRAY(1,(NEWOBJ+1))+RSHIFTX
   Y1AIM=RAYRAY(2,(NEWOBJ+1))
   Z1AIM=RAYRAY(3,(NEWOBJ+1))
   XC=X1AIM
   YC=Y1AIM
   ZC=Z1AIM
   IF(XC.LT.0.0D0) DDELX=DABS(DDELX)
   IF(YC.LT.0.0D0) DDELY=DABS(DDELY)
   IF(XC.GE.0.0D0) DDELX=-DABS(DDELX)
   IF(YC.GE.0.0D0) DDELY=-DABS(DDELY)
   XAIMOL=XC
   YAIMOL=YC
   ZAIMOL=ZC
!
!       CONVERT TO COORD SYS OF NEWOBJ
   R_TX=X1AIM
   R_TY=Y1AIM
   R_TZ=Z1AIM
   CALL BAKONE
   X1AIM=R_TX
   Y1AIM=R_TY
   Z1AIM=R_TZ
!       THESE ARE NOW IN COORD SYS OF SURFACE NEWOBJ
!
!       INITIAL DIRECTION COSINES ARE:
   MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
   &+((ZSTRT-Z1AIM)**2))
   LSTART=(X1AIM-XSTRT)/MAG
   MSTART=(Y1AIM-YSTRT)/MAG
   NSTART=(Z1AIM-ZSTRT)/MAG
   NINTY=.FALSE.
   IF(NSTART.LT.0.0D0) NINTY=.TRUE.
   IF(NINTY) RVSTART=.TRUE.
   IF(NSTART.EQ.0.0D0) THEN
      YANG=PII/2.0D0
      XANG=PII/2.0D0
   ELSE
      IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         YANG=0.0D0
      ELSE
         YANG=DATAN2(MSTART,NSTART)
      END IF
      IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         XANG=0.0D0
      ELSE
         XANG=DATAN2(LSTART,NSTART)
      END IF
   END IF
   X=XSTRT
   Y=YSTRT
   Z=ZSTRT
   L=LSTART
   M=MSTART
   N=NSTART

!
   KKK=0
!       DDELX AND DDELY ARE THE INITIAL INCREMENTORS FOR THE
!       DERIVATIVE CALCULATION IN NEWTON-RAPHSON SEARCH FOR
!       CHIEF RAY AIMING.
!
9  CONTINUE
   IF(surf_thickness(NEWOBJ).LT.0.0D0) REVSTR=.TRUE.
   IF(surf_thickness(NEWOBJ).GE.0.0D0) REVSTR=.FALSE.
   RV=.FALSE.
!
!       KKK COUNTS THE NUMBER OF TRIES TO GET A GOOD REFERENCE
!       SURFACE INTERSECTION
   KKK=KKK+1
   REFEXT=.TRUE.
   FAIL=.FALSE.
   STOPP=0
!        PROCEED
!
   IF(KKK.NE.1) THEN
      MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
      &+((ZSTRT-Z1AIM)**2))
      LSTART=(X1AIM-XSTRT)/MAG
      MSTART=(Y1AIM-YSTRT)/MAG
      NSTART=(Z1AIM-ZSTRT)/MAG
      NINTY=.FALSE.
      IF(NSTART.LT.0.0D0) NINTY=.TRUE.
      IF(NINTY) RVSTART=.TRUE.
      IF(NSTART.EQ.0.0D0) THEN
         YANG=PII/2.0D0
         XANG=PII/2.0D0
      ELSE
         IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            YANG=0.0D0
         ELSE
            YANG=DATAN2(MSTART,NSTART)
         END IF
         IF(DABS(LSTART).LE.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            XANG=0.0D0
         ELSE
            XANG=DATAN2(LSTART,NSTART)
         END IF
      END IF
      X=XSTRT
      Y=YSTRT
      Z=ZSTRT
      L=LSTART
      M=MSTART
      N=NSTART
!       KKK=1
   END IF
   LOLD=LSTART
   MOLD=MSTART
   NOLD=NSTART
   DIFF(1,NEWOBJ)=X
   DIFF(2,NEWOBJ)=Y
   DIFF(3,NEWOBJ)=Z
   DIFF(4,NEWOBJ)=L
   DIFF(5,NEWOBJ)=M
   DIFF(6,NEWOBJ)=N
   DIFF(13,NEWOBJ)=LOLD
   DIFF(14,NEWOBJ)=MOLD
   DIFF(15,NEWOBJ)=NOLD
   DO 10 I=NEWOBJ+1,NEWIMG

      CALL TRNSF2_ARGS(I, X, Y, Z, L, M, N)
      STOPP=0
      RAYEXT=.TRUE.
      FAIL=.FALSE.
      R_X=X
      R_Y=Y
      R_Z=Z
      R_L=L
      R_M=M
      R_N=N
      LOLD=L
      MOLD=M
      NOLD=N
      R_I=I
      R_XAIM=XAIMOL
      R_YAIM=YAIMOL
      R_ZAIM=ZAIMOL
      IF(RAYRAY(24,R_I-1).GT.0.0D0) POSRAY=.TRUE.
      IF(RAYRAY(24,R_I-1).LT.0.0D0) POSRAY=.FALSE.
      CALL HITSUR
      X=R_X
      Y=R_Y
      Z=R_Z
      L=R_L
      M=R_M
      N=R_N
      IF(STOPP.EQ.1) THEN
         IF(MSG) THEN
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            CALL RAY_FAILURE(I)
            OUTLYNE=&
            &'WHILE TRACING THE XZ-PLANE MARGINAL DIFFERENTIAL RAY'
            CALL SHOWIT(1)
         END IF
         STOPP=1
         SRAYDIFEXT=.FALSE.
         RETURN
      ELSE
         STOPP=0
         RAYEXT=.TRUE.
         FAIL=.FALSE.
      END IF
!
!       CHECK THE RAY HEIGHT AT
!       NEWREF AND ADJUST THE YAIMOL AND XAIMOL AT SURFACE
!       NEWOBJ+1 SO THAT THE RAY HEIGHT AT NEWREF IS WITHIN
!       .001 AIMTOL. MAXIMUN NUMBER OF ITERRATIONS IS 100
!
      IF(I.EQ.NEWREF) THEN
!       CALCULATE TARX AND TARY
         IF(RAYRAY(1,NEWREF).LE.0.0D0) TARX=RAYRAY(1,NEWREF)+RSHIFTX
         IF(RAYRAY(1,NEWREF).GT.0.0D0) TARX=RAYRAY(1,NEWREF)-RSHIFTX
         TARY=RAYRAY(2,NEWREF)
!
         IF((0.001D0*AIMTOL).LE.1.0D-10) HIT=1.0D-10
         IF((0.001D0*AIMTOL).GT.1.0D-10) HIT=0.001D0*AIMTOL
         IF(KKK.GT.2 &
         &) THEN
!       AIM IS GOOD ENOUGH, PROCEED
            GO TO 100
!       AIM NOT GOOD ENOUGH, IMPROVE GUESS
         END IF
!
!       SET X1LAST TO X1ONE AND Y1LAST TO Y1ONE
         X1ONE=X1LAST
         Y1ONE=Y1LAST
!       SET XAIMOL AND YAIMOL TO X1LAST AND Y1LAST
         X1LAST=XAIMOL
         Y1LAST=YAIMOL
!       SET RXONE AND RYONE TO RXLAST AND RYLAST
         RXONE=RXLAST
         RYONE=RYLAST
!       SET RXLAST AND RYLAST TO X AND Y
         RXLAST=X
         RYLAST=Y
!       X AND Y ARE THE CURRENT RAY COORDINATES AT THE
!       REFERENCE SURFACE.
!
!       GUESS CASE 1, REPRESENTS THE FIRST REFINEMENT
!       OF THE AIMING POINT.
!       THIS OCCURS IF KKK=1
         IF(KKK.EQ.1) THEN
!       THIS IS CASE 1
!       IN THIS CASE WE SET THE SURFACE 1 AIMING POINTS
!       EQUAL TO THE OLD AIM POINTS PLUS A SMALL DELTA
!       IN ORDER TO CALCULATE DERIVATIVES.
!
            X1AIM=XAIMOL+DDELX
            Y1AIM=YAIMOL+DDELY
            Z1AIM=ZAIMOL
            XC=X1AIM
            YC=Y1AIM
            ZC=Z1AIM
            XC1=XC
            YC1=YC
            ZC1=ZC
            IF(surf_curvature(1).NE.0.0D0)&
            &CALL GETZEE1
            X1AIM=XC
            Y1AIM=YC
            Z1AIM=ZC
!
!       CALCULATE NEW SET OF VALUES FOR DERIVATIVES
!
            XAIMOL=XC1
            YAIMOL=YC1
            ZAIMOL=ZC1
            R_TX=X1AIM
            R_TY=Y1AIM
            R_TZ=Z1AIM
            CALL BAKONE
            X1AIM=R_TX
            Y1AIM=R_TY
            Z1AIM=R_TZ
!       NOW THE COORDINATES ARE IN THE NEWOBJ COORD SYSTEM
            GO TO 9
!       THIS IS NOT THE FIRST REFINEMENT, KKK NOT = 1
         END IF
!
         CALL RAYDERIV(X1LAST,Y1LAST,X1ONE,Y1ONE &
         &,RXONE,RYONE,RXLAST,RYLAST,D11,D12,D21,D22)
!
!       MF1=TARX-RXLAST, MF2=TARY-RYLAST
!
!       TARX AND TARY ARE THE COORDINATES OF THE CENTER
!       OF THE DECENTERED CLEAR APERTURE ON THE REFERENCE
!       SURFACE IF THERE IS A CLEAR APERTURE DEFINED AND IT
!       IS DECENTERED. IF THESE CONDITIONS DO NOT EXIST,
!       TARY AND TARX ARE BOTH IDENTICALLY 0.0D0.
!
!
         MF1=TARX-RXLAST
         MF2=TARY-RYLAST
         DELFAIL=.FALSE.
         CALL NEWDEL(MF1,MF2,D11,D12,D21,D22,DELFAIL)
         IF(DELFAIL) THEN
            RETURN
         ELSE
            GO TO 9
         END IF
!       NOT AT THE REFERENCE SURFACE, NO RAY AIMING NEEDED
      END IF
!
100   CONTINUE
!
!       THE COORDINATES OF THE DIFFERENTIAL RAY AT SURFACE I ARE:
!                       X,Y,Z WITH DIRECTION COSINES
!                       L,M,N
!       NOW RENAME THEM TO:
      DIFF(1,I)=X
      DIFF(2,I)=Y
      DIFF(3,I)=Z
      DIFF(4,I)=L
      DIFF(5,I)=M
      DIFF(6,I)=N
      DIFF(13,I)=LOLD
      DIFF(14,I)=MOLD
      DIFF(15,I)=NOLD
10 CONTINUE
!
   DDELX=0.001D0
   DDELY=0.001D0
!       NEXT THE YZ PLANE
   X1ONE=-99999.9D0
   Y1ONE=-99999.9D0
   X1LAST=-99999.9D0
   Y1LAST=-99999.9D0
!
!       SET INITIAL VALUES FOR RXONE, RYONE, RXLAST AND RYLAST
   RXONE=-99999.9D0
   RYONE=-99999.9D0
   RXLAST=-99999.9D0
   RYLAST=-99999.9D0
   SIG=SYS12/DABS(SYS12)
   RSHIFTY=DIFTOL*DBLE(INT(SIG))
!
   YSTRT=RAYRAY(2,(NEWOBJ))
   DELY=DABS(RSHIFTY)
   IF(W1.LT.0.0D0) DELY=-DELY
   XSTRT=RAYRAY(1,NEWOBJ)
   ZSTRT=RAYRAY(3,NEWOBJ)
   X1AIM=RAYRAY(1,(NEWOBJ+1))
   Y1AIM=RAYRAY(2,(NEWOBJ+1))+RSHIFTY
   Z1AIM=RAYRAY(3,(NEWOBJ+1))
   XC=X1AIM
   YC=Y1AIM
   ZC=Z1AIM
   IF(XC.LT.0.0D0) DDELX=-DABS(DDELX)
   IF(YC.LT.0.0D0) DDELY=-DABS(DDELY)
   XAIMOL=XC
   YAIMOL=YC
   ZAIMOL=ZC
   R_TX=X1AIM
   R_TY=Y1AIM
   R_TZ=Z1AIM
   CALL BAKONE
   X1AIM=R_TX
   Y1AIM=R_TY
   Z1AIM=R_TZ
!
!    INITIAL DIRECTION COSINES ARE
   MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
   &+((ZSTRT-Z1AIM)**2))
   LSTART=(X1AIM-XSTRT)/MAG
   MSTART=(Y1AIM-YSTRT)/MAG
   NSTART=(Z1AIM-ZSTRT)/MAG
   NINTY=.FALSE.
   IF(NSTART.LT.0.0D0) NINTY=.TRUE.
   IF(NINTY) RVSTART=.TRUE.
   IF(NSTART.EQ.0.0D0) THEN
      YANG=PII/2.0D0
      XANG=PII/2.0D0
   ELSE
      IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         YANG=0.0D0
      ELSE
         YANG=DATAN2(MSTART,NSTART)
      END IF
      IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         XANG=0.0D0
      ELSE
         XANG=DATAN2(LSTART,NSTART)
      END IF
   END IF
   X=XSTRT
   Y=YSTRT
   Z=ZSTRT
   L=LSTART
   M=MSTART
   N=NSTART
   KKK=0
!       DDELX AND DDELY ARE THE INITIAL INCREMENTORS FOR THE
!       DERIVATIVE CALCULATION IN NEWTON-RAPHSON SEARCH FOR
!       CHIEF RAY AIMING.
!
19 CONTINUE
   IF(surf_thickness(NEWOBJ).LT.0.0D0) REVSTR=.TRUE.
   IF(surf_thickness(NEWOBJ).GE.0.0D0) REVSTR=.FALSE.
   RV=.FALSE.
!
!       KKK COUNTS THE NUMBER OF TRIES TO GET A GOOD REFERENCE
!       SURFACE ZERO POINT INTERSECTION
   KKK=KKK+1
   STOPP=0
   RAYEXT=.TRUE.
   FAIL=.FALSE.
!        PROCEED
!
   IF(KKK.NE.1) THEN
!    INITIAL DIRECTION COSINES ARE
      MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
      &+((ZSTRT-Z1AIM)**2))
      LSTART=(X1AIM-XSTRT)/MAG
      MSTART=(Y1AIM-YSTRT)/MAG
      NSTART=(Z1AIM-ZSTRT)/MAG
      NINTY=.FALSE.
      IF(NSTART.LT.0.0D0) NINTY=.TRUE.
      IF(NINTY) RVSTART=.TRUE.
      IF(NSTART.EQ.0.0D0) THEN
         YANG=PII/2.0D0
         XANG=PII/2.0D0
      ELSE
         IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            YANG=0.0D0
         ELSE
            YANG=DATAN2(MSTART,NSTART)
         END IF
         IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            XANG=0.0D0
         ELSE
            XANG=DATAN2(LSTART,NSTART)
         END IF
      END IF
      X=XSTRT
      Y=YSTRT
      Z=ZSTRT
      L=LSTART
      M=MSTART
      N=NSTART
!       KKK=1
   END IF
   LOLD=LSTART
   MOLD=MSTART
   NOLD=NSTART
   DIFF(7,NEWOBJ)=X
   DIFF(8,NEWOBJ)=Y
   DIFF(9,NEWOBJ)=Z
   DIFF(10,NEWOBJ)=L
   DIFF(11,NEWOBJ)=M
   DIFF(12,NEWOBJ)=N
   DIFF(16,NEWOBJ)=LOLD
   DIFF(17,NEWOBJ)=MOLD
   DIFF(18,NEWOBJ)=NOLD
   DO 20 I=NEWOBJ+1,NEWIMG

      CALL TRNSF2_ARGS(I, X, Y, Z, L, M, N)
      STOPP=0
      RAYEXT=.TRUE.
      FAIL=.FALSE.
!
      R_X=X
      R_Y=Y
      R_Z=Z
      R_L=L
      R_M=M
      R_N=N
      LOLD=L
      MOLD=M
      NOLD=N
      R_I=I
      R_XAIM=XAIMOL
      R_YAIM=YAIMOL
      R_ZAIM=ZAIMOL
      IF(RAYRAY(24,R_I-1).GT.0.0D0) POSRAY=.TRUE.
      IF(RAYRAY(24,R_I-1).LT.0.0D0) POSRAY=.FALSE.
      CALL HITSUR
      X=R_X
      Y=R_Y
      Z=R_Z
      L=R_L
      M=R_M
      N=R_N
      IF(STOPP.EQ.1) THEN
         IF(MSG) THEN
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            CALL RAY_FAILURE(I)
            OUTLYNE=&
            &'WHILE TRACING THE YZ-PLANE MARGINAL DIFFERENTIAL RAY'
            CALL SHOWIT(1)
         END IF
         STOPP=1
         SRAYDIFEXT=.FALSE.
         RETURN
      ELSE
         STOPP=0
         RAYEXT=.TRUE.
         FAIL=.FALSE.
      END IF
!       CHECK THE RAY HEIGHT AT
!       NEWREF AND ADJUST THE YAIMOL AND XAIMOL AT SURFACE
!       NEWOBJ+1 SO THAT THE RAY HEIGHT AT NEWREF IS WITHIN
!       .001 AIMTOL. MAXIMUN NUMBER OF ITERRATIONS IS 100
!
      IF(I.EQ.NEWREF) THEN
!       CALCULATE TARX AND TARY
         IF(RAYRAY(2,NEWREF).LE.0.0D0) TARY=RAYRAY(2,NEWREF)+RSHIFTY
         IF(RAYRAY(2,NEWREF).GT.0.0D0) TARY=RAYRAY(2,NEWREF)-RSHIFTY
         TARX=RAYRAY(1,NEWREF)
!
         IF((0.001D0*AIMTOL).LE.1.0D-10) HIT=1.0D-10
         IF((0.001D0*AIMTOL).GT.1.0D-10) HIT=0.001D0*AIMTOL
         IF(KKK.GT.2 &
         &) THEN
!       AIM IS GOOD ENOUGH, PROCEED
            GO TO 1200
!       AIM NOT GOOD ENOUGH, IMPROVE GUESS
         END IF
!
!       SET X1LAST TO X1ONE AND Y1LAST TO Y1ONE
         X1ONE=X1LAST
         Y1ONE=Y1LAST
!       SET XAIMOL AND YAIMOL TO X1LAST AND Y1LAST
         X1LAST=XAIMOL
         Y1LAST=YAIMOL
!       SET RXONE AND RYONE TO RXLAST AND RYLAST
         RXONE=RXLAST
         RYONE=RYLAST
!       SET RXLAST AND RYLAST TO X AND Y
         RXLAST=X
         RYLAST=Y
!       X AND Y ARE THE CURRENT RAY COORDINATES AT THE
!       REFERENCE SURFACE.
!
!       GUESS CASE 1, REPRESENTS THE FIRST REFINEMENT
!       OF THE AIMING POINT.
!       THIS OCCURS IF KKK=1
         IF(KKK.EQ.1) THEN
!       THIS IS CASE 1
!       IN THIS CASE WE SET THE SURFACE 1 AIMING POINTS
!       EQUAL TO THE OLD AIM POINTS PLUS A SMALL DDELTA
!       IN ORDER TO CALCULATE DERIVATIVES.
!
            X1AIM=XAIMOL+DDELX
            Y1AIM=YAIMOL+DDELY
            Z1AIM=ZAIMOL
            XC=X1AIM
            YC=Y1AIM
            ZC=Z1AIM
            XC1=XC
            YC1=YC
            ZC1=ZC
            IF(surf_curvature(1).NE.0.0D0)&
            &CALL GETZEE1
            X1AIM=XC
            Y1AIM=YC
            Z1AIM=ZC
!
!       CALCULATE NEW SET OF VALUES FOR DERIVATIVES
!
            XAIMOL=XC1
            YAIMOL=YC1
            ZAIMOL=ZC1
            R_TX=X1AIM
            R_TY=Y1AIM
            R_TZ=Z1AIM
            CALL BAKONE
            X1AIM=R_TX
            Y1AIM=R_TY
            Z1AIM=R_TZ
!       NOW THE COORDINATES ARE IN THE NEWOBJ COORD SYSTEM
            GO TO 19
!       THIS IS NOT THE FIRST REFINEMENT, KKK NOT = 1
         END IF
!
         CALL RAYDERIV(X1LAST,Y1LAST,X1ONE,Y1ONE &
         &,RXONE,RYONE,RXLAST,RYLAST,D11,D12,D21,D22)
!
!       MF1=TARX-RXLAST, MF2=TARY-RYLAST
!
!       TARX AND TARY ARE THE COORDINATES OF THE CENTER
!       OF THE DECENTERED CLEAR APERTURE ON THE REFERENCE
!       SURFACE IF THERE IS A CLEAR APERTURE DEFINED AND IT
!       IS DECENTERED. IF THESE CONDITIONS DO NOT EXIST,
!       TARY AND TARX ARE BOTH IDENTICALLY 0.0D0.
!
!
         MF1=TARX-RXLAST
         MF2=TARY-RYLAST
         DELFAIL=.FALSE.
         CALL NEWDEL(MF1,MF2,D11,D12,D21,D22,DELFAIL)
         IF(DELFAIL) THEN
            RETURN
         ELSE
            GO TO 19
         END IF
!       NOT AT THE REFERENCE SURFACE, NO RAY AIMING NEEDED
      END IF
!
1200  CONTINUE
!
!       THE COORDINATES OF THE DIFFERENTIAL RAY AT SURFACE I ARE:
!                       X,Y,Z WITH DIRECTION COSINES
!                       L,M,N
      DIFF(7,I)=X
      DIFF(8,I)=Y
      DIFF(9,I)=Z
      DIFF(10,I)=L
      DIFF(11,I)=M
      DIFF(12,I)=N
      DIFF(16,I)=LOLD
      DIFF(17,I)=MOLD
      DIFF(18,I)=NOLD
!
!       STORE THESES DIFFERENTIALS
!
20 CONTINUE
   RETURN
END
!
! SUB FOBDIF.FOR
SUBROUTINE FOBDIF
!
   use DATLEN
   use DATMAI
   use mod_surface
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       DIFFERENTIAL TRACE FOR CHIEF RAY. THIS IS A SET OF
!       CLOSE RAYS TO THE CHIEF RAY WHICH
!       ARE TRACED WITHOUT ADDITIONAL RAY AIMING FROM THE ORIGINAL OBJECT
!       POINT AT NEWOBJECT TOWARD THE ORIGINAL COORDINATE PLUS SOME
!       SMALL DELTA ON SURFACE NEWOBJECT+1.
!
!       THIS IS USED FOR THE FOB OPTION WHICH SHOWS THE X AND Y
!       FOCII ALONG A CLOSE RAY TRACE ABOUT THE CHIEF RAY
!
   INTEGER I,FFS,FFT
!
   real(real64) D11,D12,D21,D22,HIT,&
   &DET,DDELX,DDELY,SHIFTY,SHIFTX,LSTART,&
   &MSTART,NSTART,YANG,XANG,TARY,TARX,MF1,MF2 &
   &,MAG,LOLD,MOLD,NOLD,XC1,YC1,ZC1,XL,XM,XN,YL,YM,YN
!
   INTEGER KKK
!
   real(real64) FT,FS,X,X1ONE,Y1ONE,X1LAST,Y1LAST,&
   &Y,Z,L,M,N,RXONE,RYONE,&
   &RXLAST,RYLAST
!
   real(real64) SYS12,SYS13,&
   &A11,A12,A21,A22,JK_AA,JK_BB,FS1,FS2,FT1,FT2,S,T
!
   COMMON/FBDIFF/FS,FT,FFS,FFT
!
   LOGICAL DELFAIL
!
!
   SREFDIFEXT=.TRUE.
!
   DDELX=0.001D0
   DDELY=0.001D0
!
!     PROPER INITIALIZE PROCEEDURE 3/3/96
   R_X=0.0D0
   R_Y=0.0D0
   R_Z=0.0D0
   XOLD=0.0D0
   YOLD=0.0D0
   ZOLD=0.0D0
   LOLD=0.0D0
   MOLD=0.0D0
   NOLD=0.0D0
!
   IF(surf_clap_type(NEWREF) >= 1.AND.&
   &surf_clap_type(NEWREF) <= 6.AND.&
   &surf_array_parity(NEWREF) == 0) THEN
!
!       CLAP IS ON REFERENCE SURFACE
!
!       CIRCULAR CLAP
!
      IF(surf_clap_type(NEWREF) == 1 &
      &.AND.surf_array_parity(NEWREF) == 0) THEN
         IF(surf_clap_dim(NEWREF, 1).LE.surf_clap_dim(NEWREF, 2)) THEN
            SYS12=surf_clap_dim(NEWREF, 1)
            SYS13=surf_clap_dim(NEWREF, 1)
         ELSE
            SYS12=surf_clap_dim(NEWREF, 2)
            SYS13=surf_clap_dim(NEWREF, 2)
         END IF
!       NOT CIRCULAR CLAP
      END IF
!        RECT CLAP
!
      IF(surf_clap_type(NEWREF) == 2 &
      &.AND.surf_array_parity(NEWREF) == 0) THEN
         SYS12=surf_clap_dim(NEWREF, 1)
         SYS13=surf_clap_dim(NEWREF, 2)
!       NOT RECT CLAP
      END IF
!        ELIP CLAP
!
      IF(surf_clap_type(NEWREF) == 3 &
      &.AND.surf_array_parity(NEWREF) == 0) THEN
         SYS12=surf_clap_dim(NEWREF, 1)
         SYS13=surf_clap_dim(NEWREF, 2)
!       NOT ELIP CLAP
      END IF
!        RCTK CLAP
!
      IF(surf_clap_type(NEWREF) == 4 &
      &.AND.surf_array_parity(NEWREF) == 0) THEN
         SYS12=surf_clap_dim(NEWREF, 1)
         SYS13=surf_clap_dim(NEWREF, 2)
!       NOT RCTK CLAP
      END IF
!        POLY CLAP
!
      IF(surf_clap_type(NEWREF) == 5 &
      &.AND.surf_array_parity(NEWREF) == 0) THEN
         SYS12=surf_clap_dim(NEWREF, 1)
         SYS13=surf_clap_dim(NEWREF, 1)
!       NOT POLY CLAP
      END IF
!        IPOLY CLAP
!
      IF(surf_clap_type(NEWREF) == 6 &
      &.AND.surf_array_parity(NEWREF) == 0) THEN
         SYS12=surf_clap_dim(NEWREF, 5)
         SYS13=surf_clap_dim(NEWREF, 5)
!       NOT IPOLY CLAP
      END IF
!
   ELSE
!       NO CLAP ON REF SURF.
      SYS13=PXTRAX(1,NEWREF)
      SYS12=PXTRAY(1,NEWREF)
   END IF
!
   FOB0=0
   FT=0.0D0
   FS=0.0D0
   FFT=0
   FFS=0
   IF(.NOT.LDIF) THEN
      OUTLYNE=&
      &'DIFFERENTIAL RAYTRACE IS "OFF"'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'ALL DIFFERENTIAL RAY DATA IS ZERO'
      CALL SHOWIT(1)
      STOPP=1
      SREFDIFEXT=.FALSE.
      RETURN
!       LDIF TRUE, PROCEED
   END IF
!
!       SET INITIAL VALUES FOR X1ONE, Y1ONE, X1LAST AND Y1LAST
!
   X1ONE=-99999.9D0
   Y1ONE=-99999.9D0
   X1LAST=-99999.9D0
   Y1LAST=-99999.9D0
!
!       SET INITIAL VALUES FOR RXONE, RYONE, RXLAST AND RYLAST
   RXONE=-99999.9D0
   RYONE=-99999.9D0
   RXLAST=-99999.9D0
   RYLAST=-99999.9D0
!
!       FIRST XZ PLANE
   SHIFTX=DABS(DIFTOL)
!        SHIFTX=DABS(DIFTOL*DABS(SYS13))
!
   XSTRT=RAYRAY(1,NEWOBJ)
   YSTRT=RAYRAY(2,NEWOBJ)
   ZSTRT=RAYRAY(3,NEWOBJ)
!       THE INITIAL AIMING POINT IN NEWOBJ+1 IN NEWOBJ+1 COORDINATES IS:
   X1AIM=RAYRAY(1,(NEWOBJ+1))
   Y1AIM=RAYRAY(2,(NEWOBJ+1))
   Z1AIM=RAYRAY(3,(NEWOBJ+1))
   XC=X1AIM
   YC=Y1AIM
   ZC=Z1AIM
   IF(XC.LT.0.0D0) DDELX=DABS(DDELX)
   IF(YC.LT.0.0D0) DDELY=DABS(DDELY)
   IF(XC.GE.0.0D0) DDELX=-DABS(DDELX)
   IF(YC.GE.0.0D0) DDELY=-DABS(DDELY)
   XAIMOL=XC
   YAIMOL=YC
   ZAIMOL=ZC
!
!       CONVERT TO COORD SYS OF NEWOBJ
   R_TX=X1AIM
   R_TY=Y1AIM
   R_TZ=Z1AIM
   CALL BAKONE
   X1AIM=R_TX
   Y1AIM=R_TY
   Z1AIM=R_TZ
!       THESE ARE NOW IN COORD SYS OF SURFACE NEWOBJ
!
!       INITIAL DIRECTION COSINES ARE:
   LSTART=RAYRAY(4,NEWOBJ)
   MSTART=RAYRAY(5,NEWOBJ)
   NSTART=RAYRAY(6,NEWOBJ)
   NINTY=.FALSE.
   IF(NSTART.LT.0.0D0) NINTY=.TRUE.
   IF(NINTY) RVSTART=.TRUE.
   IF(NSTART.EQ.0.0D0) THEN
      YANG=PII/2.0D0
      XANG=PII/2.0D0
   ELSE
      IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         YANG=0.0D0
      ELSE
         YANG=DATAN2(MSTART,NSTART)
      END IF
      IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         XANG=0.0D0
      ELSE
         XANG=DATAN2(LSTART,NSTART)
      END IF
   END IF
   X=XSTRT
   Y=YSTRT
   Z=ZSTRT
   L=LSTART
   M=MSTART
   N=NSTART
!
   KKK=0
!       DDELX AND DDELY ARE THE INITIAL INCREMENTORS FOR THE
!       DERIVATIVE CALCULATION IN NEWTON-RAPHSON SEARCH FOR
!       CHIEF RAY AIMING.
!
9  CONTINUE
   IF(surf_thickness(NEWOBJ).LT.0.0D0) REVSTR=.TRUE.
   IF(surf_thickness(NEWOBJ).GE.0.0D0) REVSTR=.FALSE.
   RV=.FALSE.
!
!       KKK COUNTS THE NUMBER OF TRIES TO GET A GOOD REFERENCE
!       SURFACE INTERSECTION
   KKK=KKK+1
!       IF KKK EXCEEDS 100 TRIES, PRINT RAY ITERRATION ERROR
!       AND STOP SEARCHING.
   IF(KKK.GT.NRAITR) THEN
      OUTLYNE='WARNING:'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'MARGINAL DIFFERENTIAL RAY (XZ-PLANE) FAILURE:'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'RAY FAILED TO CONVERGE TO RAY-AIM POINT'
      CALL SHOWIT(1)
      STOPP=1
      SREFDIFEXT=.FALSE.
      RETURN
   ELSE
      RAYEXT=.TRUE.
      FAIL=.FALSE.
      STOPP=0
!        PROCEED
   END IF
!
   IF(KKK.NE.1) THEN
      MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
      &+((ZSTRT-Z1AIM)**2))
      LSTART=(X1AIM-XSTRT)/MAG
      MSTART=(Y1AIM-YSTRT)/MAG
      NSTART=(Z1AIM-ZSTRT)/MAG
      NINTY=.FALSE.
      IF(NSTART.LT.0.0D0) NINTY=.TRUE.
      IF(NINTY) RVSTART=.TRUE.
      IF(NSTART.EQ.0.0D0) THEN
         YANG=PII/2.0D0
         XANG=PII/2.0D0
      ELSE
         IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            YANG=0.0D0
         ELSE
            YANG=DATAN2(MSTART,NSTART)
         END IF
         IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            XANG=0.0D0
         ELSE
            XANG=DATAN2(LSTART,NSTART)
         END IF
      END IF
      X=XSTRT
      Y=YSTRT
      Z=ZSTRT
      L=LSTART
      M=MSTART
      N=NSTART
!       KKK=1
   END IF
   DO 10 I=NEWOBJ+1,NEWIMG

      CALL TRNSF2_ARGS(I, X, Y, Z, L, M, N)
      STOPP=0
      RAYEXT=.TRUE.
      FAIL=.FALSE.
      R_X=X
      R_Y=Y
      R_Z=Z
      R_L=L
      R_M=M
      R_N=N
      R_I=I
      LOLD=L
      MOLD=M
      NOLD=N
      R_XAIM=XAIMOL
      R_YAIM=YAIMOL
      R_ZAIM=ZAIMOL
      IF(REFRY(24,R_I-1).GT.0.0D0) POSRAY=.TRUE.
      IF(REFRY(24,R_I-1).LT.0.0D0) POSRAY=.FALSE.
      CALL HITSUR
      X=R_X
      Y=R_Y
      Z=R_Z
      L=R_L
      M=R_M
      N=R_N
      IF(STOPP.EQ.1) THEN
         IF(MSG) THEN
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            CALL RAY_FAILURE(I)
            OUTLYNE=&
            &'WHILE TRACING THE XZ-PLANE MARGINAL DIFFERENTIAL RAY'
            CALL SHOWIT(1)
         END IF
         STOPP=1
         SREFDIFEXT=.FALSE.
         RETURN
      ELSE
         STOPP=0
         RAYEXT=.TRUE.
         FAIL=.FALSE.
      END IF
!       CHECK THE RAY HEIGHT AT
!       NEWREF AND ADJUST THE YAIMOL AND XAIMOL AT SURFACE
!       NEWOBJ+1 SO THAT THE RAY HEIGHT AT NEWREF IS WITHIN
!       .001 AIMTOL. MAXIMUN NUMBER OF ITERRATIONS IS 100
!
      IF(I.EQ.NEWREF) THEN
!       CALCULATE TARX AND TARY
         IF(RAYRAY(1,NEWREF).LT.0.0D0) TARX=RAYRAY(1,NEWREF)+SHIFTX
         IF(RAYRAY(1,NEWREF).GE.0.0D0) TARX=RAYRAY(1,NEWREF)-SHIFTX
         TARY=RAYRAY(2,NEWREF)
!
         IF((0.001D0*AIMTOL).LE.1.0D-10) HIT=1.0D-10
         IF((0.001D0*AIMTOL).GT.1.0D-10) HIT=0.001D0*AIMTOL
         IF(DSQRT(((TARX-X)**2)+((TARY-Y)**2)).LE.(HIT).AND.KKK.GT.1 &
         &) THEN
!       AIM IS GOOD ENOUGH, PROCEED
            GO TO 100
!       AIM NOT GOOD ENOUGH, IMPROVE GUESS
         END IF
!
!       SET X1LAST TO X1ONE AND Y1LAST TO Y1ONE
         X1ONE=X1LAST
         Y1ONE=Y1LAST
!       SET XAIMOL AND YAIMOL TO X1LAST AND Y1LAST
         X1LAST=XAIMOL
         Y1LAST=YAIMOL
!       SET RXONE AND RYONE TO RXLAST AND RYLAST
         RXONE=RXLAST
         RYONE=RYLAST
!       SET RXLAST AND RYLAST TO X AND Y
         RXLAST=X
         RYLAST=Y
!       X AND Y ARE THE CURRENT RAY COORDINATES AT THE
!       REFERENCE SURFACE.
!
!       GUESS CASE 1, REPRESENTS THE FIRST REFINEMENT
!       OF THE AIMING POINT.
!       THIS OCCURS IF KKK=1
         IF(KKK.EQ.1) THEN
!       THIS IS CASE 1
!       IN THIS CASE WE SET THE SURFACE 1 AIMING POINTS
!       EQUAL TO THE OLD AIM POINTS PLUS A SMALL DELTA
!       IN ORDER TO CALCULATE DERIVATIVES.
!
            X1AIM=XAIMOL+DDELX
            Y1AIM=YAIMOL+DDELY
            Z1AIM=ZAIMOL
            XC=X1AIM
            YC=Y1AIM
            ZC=Z1AIM
            XC1=XC
            YC1=YC
            ZC1=ZC
            IF(surf_curvature(1).NE.0.0D0)&
            &CALL GETZEE1
            X1AIM=XC
            Y1AIM=YC
            Z1AIM=ZC
!
!       CALCULATE NEW SET OF VALUES FOR DERIVATIVES
!
            XAIMOL=XC1
            YAIMOL=YC1
            ZAIMOL=ZC1
            R_TX=X1AIM
            R_TY=Y1AIM
            R_TZ=Z1AIM
            CALL BAKONE
            X1AIM=R_TX
            Y1AIM=R_TY
            Z1AIM=R_TZ
!       NOW THE COORDINATES ARE IN THE NEWOBJ COORD SYSTEM
            GO TO 9
!       THIS IS NOT THE FIRST REFINEMENT, KKK NOT = 1
         END IF
!
         CALL RAYDERIV(X1LAST,Y1LAST,X1ONE,Y1ONE &
         &,RXONE,RYONE,RXLAST,RYLAST,D11,D12,D21,D22)
!       MF1=TARX-RXLAST, MF2=TARY-RYLAST
!
!       TARX AND TARY ARE THE COORDINATES OF THE CENTER
!       OF THE DECENTERED CLEAR APERTURE ON THE REFERENCE
!       SURFACE IF THERE IS A CLEAR APERTURE DEFINED AND IT
!       IS DECENTERED. IF THESE CONDITIONS DO NOT EXIST,
!       TARY AND TARX ARE BOTH IDENTICALLY 0.0D0.
!
!
         MF1=TARX-RXLAST
         MF2=TARY-RYLAST
         DELFAIL=.FALSE.
         CALL NEWDEL(MF1,MF2,D11,D12,D21,D22,DELFAIL)
         IF(DELFAIL) THEN
            RETURN
         ELSE
            GO TO 9
         END IF
!       NOT AT THE REFERENCE SURFACE, NO RAY AIMING NEEDED
      END IF
!
100   CONTINUE
10 CONTINUE
!       THE COORDINATES OF THE DIFFERENTIAL RAY AT NEWIMG ARE:
!                       X,Y,Z WITH DIRECTION COSINES
!                       L,M,N
!       THE COORDINATES OF THE REFERENCE RAY ARE:
!       REFRY(1,NEWIMG),REFRAY(2,NEWIMG),REFRY(3,NEWIMG)
!       WITH DIRECTION COSINES
!       REFRY(4,NEWING),REFRY(5,NEWIMG),REFRY(6,NEWIMG)
!       THESE COORDINATES AND DIRECTION COSINES ARE IN THE
!       LOCAL COORDINATE SYSTEM OF (NEWIMG).
!       THE Z COORDINATE OF THE INTERSECTION OF THESE TWO
!       RAYS WILL BE THE VALUE FS.
   A11=L-M
   A12=-(REFRY(4,NEWIMG)-REFRY(5,NEWIMG))
   A21=M-N
   A22=-(REFRY(5,NEWIMG)-REFRY(6,NEWIMG))
   JK_AA=((REFRY(1,NEWIMG)-X)-(REFRY(2,NEWIMG)-Y))
   JK_BB=((REFRY(2,NEWIMG)-Y)-(REFRY(3,NEWIMG)-Z))
   DET=(A11*A22)-(A12*A21)
   IF(DABS(DET).LE.1.0D-6) DET=0.0D0
   IF(DET.EQ.0.0D0) THEN
      FS=0.0D0
      FT=0.0D0
      FFS=0
      FFT=0
!       NO SOLUTION EXISTS
      SREFDIFEXT=.FALSE.
      RETURN
   ELSE
!       A SOLUTION EXISTS
      FFS=1
      S=((A11*JK_BB)-(A21*JK_AA))/DET
      T=(JK_AA-(A12*S))/A11
      FS1=Z+(N*T)
      FS2=REFRY(3,NEWIMG)+(REFRY(6,NEWIMG)*S)
!       CALCULATE FS
      FS=(FS1+FS2)/2.0D0
   END IF
!
   DDELX=0.001D0
   DDELY=0.001D0
!       NEXT THE YZ PLANE
   SHIFTY=DABS(DIFTOL)
!        SHIFTY=DABS(DIFTOL*DABS(SYS12))
!
   YSTRT=RAYRAY(2,(NEWOBJ))
   XSTRT=RAYRAY(1,NEWOBJ)
   ZSTRT=RAYRAY(3,NEWOBJ)
   X1AIM=RAYRAY(1,(NEWOBJ+1))
   Y1AIM=RAYRAY(2,(NEWOBJ+1))
   Z1AIM=RAYRAY(3,(NEWOBJ+1))
   IF(XC.LT.0.0D0) DDELX=-DABS(DDELX)
   IF(YC.LT.0.0D0) DDELY=-DABS(DDELY)
   XAIMOL=XC
   YAIMOL=YC
   ZAIMOL=ZC
   R_TX=X1AIM
   R_TY=Y1AIM
   R_TZ=Z1AIM
   CALL BAKONE
   X1AIM=R_TX
   Y1AIM=R_TY
   Z1AIM=R_TZ
!
!    INITIAL DIRECTION COSINES ARE
   LSTART=RAYRAY(4,NEWOBJ)
   MSTART=RAYRAY(5,NEWOBJ)
   NSTART=RAYRAY(6,NEWOBJ)
   NINTY=.FALSE.
   IF(NSTART.LT.0.0D0) NINTY=.TRUE.
   IF(NINTY) RVSTART=.TRUE.
   IF(NSTART.EQ.0.0D0) THEN
      YANG=PII/2.0D0
      XANG=PII/2.0D0
   ELSE
      IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         YANG=0.0D0
      ELSE
         YANG=DATAN2(MSTART,NSTART)
      END IF
      IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
         XANG=0.0D0
      ELSE
         XANG=DATAN2(LSTART,NSTART)
      END IF
   END IF
   X=XSTRT
   Y=YSTRT
   Z=ZSTRT
   L=LSTART
   M=MSTART
   N=NSTART
   KKK=0
!       DDELX AND DDELY ARE THE INITIAL INCREMENTORS FOR THE
!       DERIVATIVE CALCULATION IN NEWTON-RAPHSON SEARCH FOR
!       CHIEF RAY AIMING.
!
19 CONTINUE
   IF(surf_thickness(NEWOBJ).LT.0.0D0) REVSTR=.TRUE.
   IF(surf_thickness(NEWOBJ).GE.0.0D0) REVSTR=.FALSE.
   RV=.FALSE.
!
!       KKK COUNTS THE NUMBER OF TRIES TO GET A GOOD REFERENCE
!       SURFACE ZERO POINT INTERSECTION
   KKK=KKK+1
!       IF KKK EXCEEDS 100 TRIES, PRINT RAY ITERRATION ERROR
!       AND STOP SEARCHING.
   IF(KKK.GT.NRAITR) THEN
      OUTLYNE='WARNING:'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'MARGINAL DIFFERENTIAL RAY (YZ-PLANE) FAILURE:'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'RAY FAILED TO CONVERGE TO RAY-AIM POINT'
      CALL SHOWIT(1)
      STOPP=1
      SREFDIFEXT=.FALSE.
      RETURN
   ELSE
      STOPP=0
      RAYEXT=.TRUE.
      FAIL=.FALSE.
!        PROCEED
   END IF
!
   IF(KKK.NE.1) THEN
!    INITIAL DIRECTION COSINES ARE
      MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
      &+((ZSTRT-Z1AIM)**2))
      LSTART=(X1AIM-XSTRT)/MAG
      MSTART=(Y1AIM-YSTRT)/MAG
      NSTART=(Z1AIM-ZSTRT)/MAG
      NINTY=.FALSE.
      IF(NSTART.LT.0.0D0) NINTY=.TRUE.
      IF(NINTY) RVSTART=.TRUE.
      IF(NSTART.EQ.0.0D0) THEN
         YANG=PII/2.0D0
         XANG=PII/2.0D0
      ELSE
         IF(DABS(MSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            YANG=0.0D0
         ELSE
            YANG=DATAN2(MSTART,NSTART)
         END IF
         IF(DABS(LSTART).EQ.0.0D0.AND.DABS(NSTART).EQ.0.0D0) THEN
            XANG=0.0D0
         ELSE
            XANG=DATAN2(LSTART,NSTART)
         END IF
      END IF
      X=XSTRT
      Y=YSTRT
      Z=ZSTRT
      L=LSTART
      M=MSTART
      N=NSTART
!       KKK=1
   END IF
   DO 20 I=NEWOBJ+1,NEWIMG

      CALL TRNSF2_ARGS(I, X, Y, Z, L, M, N)
      STOPP=0
      RAYEXT=.TRUE.
      FAIL=.FALSE.
!
      R_X=X
      R_Y=Y
      R_Z=Z
      R_L=L
      R_M=M
      R_N=N
      R_I=I
      LOLD=L
      MOLD=M
      NOLD=N
      R_XAIM=XAIMOL
      R_YAIM=YAIMOL
      R_ZAIM=ZAIMOL
      IF(REFRY(24,R_I-1).GT.0.0D0) POSRAY=.TRUE.
      IF(REFRY(24,R_I-1).LT.0.0D0) POSRAY=.FALSE.
      CALL HITSUR
      X=R_X
      Y=R_Y
      Z=R_Z
      L=R_L
      M=R_M
      N=R_N
      IF(STOPP.EQ.1) THEN
         IF(MSG) THEN
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            CALL RAY_FAILURE(I)
            OUTLYNE=&
            &'WHILE TRACING THE YZ-PLANE MARGINAL DIFFERENTIAL RAY'
            CALL SHOWIT(1)
         END IF
         STOPP=1
         SREFDIFEXT=.FALSE.
         RETURN
      ELSE
         STOPP=0
         RAYEXT=.TRUE.
         FAIL=.FALSE.
      END IF
!       CHECK THE RAY HEIGHT AT
!       NEWREF AND ADJUST THE YAIMOL AND XAIMOL AT SURFACE
!       NEWOBJ+1 SO THAT THE RAY HEIGHT AT NEWREF IS WITHIN
!       .001 AIMTOL. MAXIMUN NUMBER OF ITERRATIONS IS  100
!
      IF(I.EQ.NEWREF) THEN
!       CALCULATE TARX AND TARY
         IF(RAYRAY(2,NEWREF).LT.0.0D0)TARY=RAYRAY(2,NEWREF)+SHIFTY
         IF(RAYRAY(2,NEWREF).GE.0.0D0)TARY=RAYRAY(2,NEWREF)-SHIFTY
         TARX=RAYRAY(1,NEWREF)
!
         IF((0.001D0*AIMTOL).LE.1.0D-10) HIT=1.0D-10
         IF((0.001D0*AIMTOL).GT.1.0D-10) HIT=0.001D0*AIMTOL
         IF(DSQRT(((TARX-X)**2)+((TARY-Y)**2)).LE.(HIT).AND.KKK.GT.1 &
         &) THEN
!       AIM IS GOOD ENOUGH, PROCEED
            GO TO 1200
!       AIM NOT GOOD ENOUGH, IMPROVE GUESS
         END IF
!
!       SET X1LAST TO X1ONE AND Y1LAST TO Y1ONE
         X1ONE=X1LAST
         Y1ONE=Y1LAST
!       SET XAIMOL AND YAIMOL TO X1LAST AND Y1LAST
         X1LAST=XAIMOL
         Y1LAST=YAIMOL
!       SET RXONE AND RYONE TO RXLAST AND RYLAST
         RXONE=RXLAST
         RYONE=RYLAST
!       SET RXLAST AND RYLAST TO X AND Y
         RXLAST=X
         RYLAST=Y
!       X AND Y ARE THE CURRENT RAY COORDINATES AT THE
!       REFERENCE SURFACE.
!
!       GUESS CASE 1, REPRESENTS THE FIRST REFINEMENT
!       OF THE AIMING POINT.
!       THIS OCCURS IF KKK=1
         IF(KKK.EQ.1) THEN
!       THIS IS CASE 1
!       IN THIS CASE WE SET THE SURFACE 1 AIMING POINTS
!       EQUAL TO THE OLD AIM POINTS PLUS A SMALL DDELTA
!       IN ORDER TO CALCULATE DERIVATIVES.
!
            X1AIM=XAIMOL+DDELX
            Y1AIM=YAIMOL+DDELY
            Z1AIM=ZAIMOL
            XC=X1AIM
            YC=Y1AIM
            ZC=Z1AIM
            XC1=XC
            YC1=YC
            ZC1=ZC
            IF(surf_curvature(1).NE.0.0D0)&
            &CALL GETZEE1
            X1AIM=XC
            Y1AIM=YC
            Z1AIM=ZC
!
!       CALCULATE NEW SET OF VALUES FOR DERIVATIVES
            XAIMOL=XC1
            YAIMOL=YC1
            ZAIMOL=ZC1
            R_TX=X1AIM
            R_TY=Y1AIM
            R_TZ=Z1AIM
            CALL BAKONE
            X1AIM=R_TX
            Y1AIM=R_TY
            Z1AIM=R_TZ
!       NOW THE COORDINATES ARE IN THE NEWOBJ COORD SYSTEM
!
            GO TO 19
!       THIS IS NOT THE FIRST REFINEMENT, KKK NOT = 1
         END IF
!
         CALL RAYDERIV(X1LAST,Y1LAST,X1ONE,Y1ONE &
         &,RXONE,RYONE,RXLAST,RYLAST,D11,D12,D21,D22)
!
!       MF1=TARX-RXLAST, MF2=TARY-RYLAST
!
!       TARX AND TARY ARE THE COORDINATES OF THE CENTER
!       OF THE DECENTERED CLEAR APERTURE ON THE REFERENCE
!       SURFACE IF THERE IS A CLEAR APERTURE DEFINED AND IT
!       IS DECENTERED. IF THESE CONDITIONS DO NOT EXIST,
!       TARY AND TARX ARE BOTH IDENTICALLY 0.0D0.
!
!
         MF1=TARX-RXLAST
         MF2=TARY-RYLAST
         DELFAIL=.FALSE.
         CALL NEWDEL(MF1,MF2,D11,D12,D21,D22,DELFAIL)
         IF(DELFAIL) THEN
            RETURN
         ELSE
            GO TO 19
         END IF
!       NOT AT THE REFERENCE SURFACE, NO RAY AIMING NEEDED
      END IF
!
1200  CONTINUE
20 CONTINUE
!
!       THE COORDINATES OF THE DIFFERENTIAL RAY AT NEWIMG ARE:
!                       X,Y,Z WITH DIRECTION COSINES
!                       L,M,N
!       THE COORDINATES OF THE REFERENCE RAY ARE:
!       REFRY(1,NEWIMG),REFRY(2,NEWIMG),REFRY(3,NEWIMG)
!       WITH DIRECTION COSINES
!       REFRY(4,NEWING),REFRY(5,NEWIMG),REFRY(6,NEWIMG)
!       THESE COORDINATES AND DIRECTION COSINES ARE IN THE
!       LOCAL COORDINATE SYSTEM OF (NEWIMG).
!       THE Z COORDINATE OF THE INTERSECTION OF THESE TWO
!       RAYS WILL BE THE VALUE FT.
   A11=L-M
   A12=-(REFRY(4,NEWIMG)-REFRY(5,NEWIMG))
   A21=M-N
   A22=-(REFRY(5,NEWIMG)-REFRY(6,NEWIMG))
   JK_AA=((REFRY(1,NEWIMG)-X)-(REFRY(2,NEWIMG)-Y))
   JK_BB=((REFRY(2,NEWIMG)-Y)-(REFRY(3,NEWIMG)-Z))
   DET=(A11*A22)-(A12*A21)
   IF(DABS(DET).LE.1.0D-6) DET=0.0D0
   IF(DET.EQ.0.0D0) THEN
      FS=0.0D0
      FT=0.0D0
      FFS=0
      FFT=0
!       NO SOLUTION EXISTS
      SREFDIFEXT=.FALSE.
      RETURN
   ELSE
!       A SOLUTION EXISTS
      FFT=1
      S=((A11*JK_BB)-(A21*JK_AA))/DET
      T=(JK_AA-(A12*S))/A11
      FT1=Z+(N*T)
      FT2=REFRY(3,NEWIMG)+(REFRY(6,NEWIMG)*S)
!       CALCULATE FT
      FT=(FT1+FT2)/2.0D0
   END IF
!
   RETURN
END
