MODULE globals
   use zoa_logger
   use iso_fortran_env, only: real64

   PUBLIC
   integer, parameter :: long = selected_real_kind(15, 307)
   character(len=10) :: zoaVersion
   character(len=256) :: basePath
   type(zoaLogger) :: logger
   character(len=140)  :: rawCommands(20)
   character(len=140)  :: currentCommand

   logical :: TEST_MODE = .FALSE.
   logical :: HEADLESS_MODE = .FALSE.
   logical :: RELEASE_MODE = .FALSE.

   ! Thickness value stored when user enters "Infinity" (e.g. for object-at-infinity)
   real(kind=long), parameter :: INFINITY_DISTANCE = 1.0e13_long
   ! Display threshold: show "Infinity" in the lens editor for |thickness| above this
   real(kind=long), parameter :: INFINITY_DISPLAY_THRESHOLD = 1.0e10_long
!
!     PROCESS ONE OR 20 COMMANDS
!
   LOGICAL MULTICOM
   INTEGER NUMCOM
!
!     NEUTRAL PLOT ARRAY STUFF
!
   CHARACTER*42 NEUTARRAY
   DIMENSION NEUTARRAY(:)
   ALLOCATABLE :: NEUTARRAY
!
!     RADIAL ENERGY DISTRIBUTION (REPLACES REDDAT.DAT)
!
   real(real64) REDDAT1,REDDAT2,REDDAT3
   DIMENSION REDDAT1(:),REDDAT2(:),REDDAT3(:)
   ALLOCATABLE :: REDDAT1,REDDAT2,REDDAT3
!
!
!     DIFFRACTION ENERGY DISTRIBUTION (REPLACES SPDPSF.DAT)
!
   real(real64) SPDPSF1,SPDPSF2,SPDPSF3
   DIMENSION SPDPSF1(:),SPDPSF2(:),SPDPSF3(:)
   ALLOCATABLE :: SPDPSF1,SPDPSF2,SPDPSF3
!
!     DIFFRACTION ENERGY DISTRIBUTION (REPLACES PSF.DAT IN RED CALCS)
!
   INTEGER IPSF1,IPSF2,IPSF3
   DIMENSION IPSF1(:),IPSF2(:),IPSF3(:)
   ALLOCATABLE :: IPSF1,IPSF2,IPSF3
!
!     BIG CAPFN SPOT DIAGRAM
   real(real64) DSPOTT
   real(real64) DSPOTT1
   real(real64) DSPOTT2
   real(real64) DSPOTT3
   real(real64) DSPOTT4
   real(real64) DSPOTT5
   real(real64) DSPOTT6
   real(real64) DSPOTT7
   real(real64) DSPOTT8
   real(real64) DSPOTT9
   real(real64) DSPOTT10
   DIMENSION DSPOTT(:,:)
   DIMENSION DSPOTT1(:,:)
   DIMENSION DSPOTT2(:,:)
   DIMENSION DSPOTT3(:,:)
   DIMENSION DSPOTT4(:,:)
   DIMENSION DSPOTT5(:,:)
   DIMENSION DSPOTT6(:,:)
   DIMENSION DSPOTT7(:,:)
   DIMENSION DSPOTT8(:,:)
   DIMENSION DSPOTT9(:,:)
   DIMENSION DSPOTT10(:,:)
   ALLOCATABLE :: DSPOTT
   ALLOCATABLE :: DSPOTT1
   ALLOCATABLE :: DSPOTT2
   ALLOCATABLE :: DSPOTT3
   ALLOCATABLE :: DSPOTT4
   ALLOCATABLE :: DSPOTT5
   ALLOCATABLE :: DSPOTT6
   ALLOCATABLE :: DSPOTT7
   ALLOCATABLE :: DSPOTT8
   ALLOCATABLE :: DSPOTT9
   ALLOCATABLE :: DSPOTT10
!
!       FULL IMAGING ARRAYS
!
!       OBJECT
!
   real(real64) IOBJECTX,IOBJECTY,IOBJECTV,IOBJECTX2,IOBJECTY2
!
   DIMENSION IOBJECTX2(:,:),IOBJECTY2(:,:),OBJTEMP(:,:,:)
   DIMENSION IOBJECTX(:,:),IOBJECTY(:,:),IOBJECTV(:,:,:)
   ALLOCATABLE :: IOBJECTX,IOBJECTY,IOBJECTV
   ALLOCATABLE :: IOBJECTX2,IOBJECTY2,OBJTEMP
!
!       OBJECTX HOLDS X COORDINATE OF ITH ROW, JTH COLUMN AS real(real64)
!       OBJECTY HOLDS Y COORDINATE OF ITH ROW, JTH COLUMN ASreal(real64)
!       OBJECTV HOLDS VALUE OF ITH ROW, JTH COLUMN, KTH WAVELENGTH AS real(real64)
!
   INTEGER IOBJECTYPE
!
!       ICOLOR1,ICOLOR2,ICOLOR3
   INTEGER ICOLOR1,ICOLOR2,ICOLOR3,NCRAYS
!       NUMCOLORS
   INTEGER NUMCOLORS,IMAGETYPE
!
!       IMAGE
!
   real(real64) IIMAGEX,IIMAGEY,IIMAGEV,XR,YR,ZR,IDELX,IDELY,ODELX,ODELY
   real(real64) IIMAGEX2,IIMAGEY2,IMGTEMP
   real(real64) VR
   INTEGER OBJNX,OBJNY
   INTEGER IMGNX,IMGNY
!
   DIMENSION IIMAGEX(:,:),IIMAGEY(:,:),IIMAGEV(:,:,:,:),&
   &IMGTEMP(:,:,:,:)
   ALLOCATABLE :: IIMAGEX,IIMAGEY,IIMAGEV,IMGTEMP
   DIMENSION IIMAGEX2(:,:),IIMAGEY2(:,:)
   ALLOCATABLE :: IIMAGEX2,IIMAGEY2
!
!       IMAGEX HOLDS X COORDINATE OF ITH ROW, JTH COLUMN AS real(real64)
!       IMAGEY HOLDS Y COORDINATE OF ITH ROW, JTH COLUMN, AS real(real64)
!       IMAGEV HOLDS VALUE OF ITH ROW, JTH COLUMN, KTH WAVELENGTH real(real64)
!
   LOGICAL OXODD,OYODD,IXODD,IYODD
!
   CHARACTER*80 BMPREADR
!
   real(real64) PSFWV(1:10),GRIIMG
   INTEGER NNPSF,MMMIMG,PGRIMG

   real(real64) FIMG
   DIMENSION FIMG(:,:)
   ALLOCATABLE :: FIMG
!
   INTEGER XCENTOFF,YCENTOFF
!
   real(real64) OBJLEVEL
!
!       11/12/2002
!       ZERNIKE REPRESENTATION OF PHASE IN A SYSTEM
!       AS DETERMINED FROM A RAY TRACE REFERENCED TO THE LAST CHIEF RAY AND THE
!       GUT CHIEF RAY
!       FIRST DIMENSION IS ZERN COUNTER
!       1-37 ARE ZERNIKE TERMS, 38 IS REFERENCE RADIUS
!       39,40,41,42,43,44,46 ARE CLAP DATA
!       47,48,49,50,51,52,53 ARE COBS DATA
!       SECOND DIMENSION IS WAVELENGTH NUMBER
!       THIRD DIMENSION IS THE SURFACE NUMBER
!       FOURTH DIMENSION IS 1 FOR GUT RAY, 2 FOR LAST CHIEF RAY
   real(real64) ZERNSURF
   DIMENSION ZERNSURF(:,:,:,:)
   ALLOCATABLE :: ZERNSURF
!
!       FOE
   LOGICAL PUPIL_EXIST,CAPFN_EXIST,DOMAINS,DOMAINF,AIB,RTHETA
   real(real64) FOEGRID1
   DIMENSION FOEGRID1(:,:,:,:)
   ALLOCATABLE :: FOEGRID1
!       DIM 1 IS X INDEX
!       DIM 2 IS Y INDEX
!       DIM 3 IS WAVELENGTH NUMBER
!       DIM 4 IS 1 OR 2 FOR REAL OR IMAGINARY PART
   real(real64) GRIDSX,GRIDSY,NGRIDSX,NGRIDSY
!       GRID SPACINGS AND NUMBERS OF CELLS IN SPATIAL DOMAIN
   real(real64) GRIDFX,GRIDFY,NGRIDFX,NGRIDFY
!       GRID SPACINGS AND NUMBERS OF CELLS IN FREQUENCY DOMAIN
   INTEGER FOEMODE
!       FOEMODE IS 1=FOCAL, 2=UFOCAL, 3-AFOCAL, 4-UAFOCAL
!
!       DEFINITIONS TO SUPPORT EITHER NSS OR GRADIENT INDEX RAY TRACING
!       MAX NUMBER OF MULTI RAYS SET BY "MRAYS" USING PM COMMAND
!       MULTIRAY DATA IS STORED INDEXED TO THE ENTRANCE PORT SURFACE NUMBER
   real(real64) MULTIRAY_DATA
   DIMENSION MULTIRAY_DATA(:,:,:)
   ALLOCATABLE :: MULTIRAY_DATA
!
   real(real64) MULTIREF_DATA
   DIMENSION MULTIREF_DATA(:,:,:)
   ALLOCATABLE :: MULTIREF_DATA
!
   real(real64) MULTI_DATA
   DIMENSION MULTI_DATA(:,:,:)
   ALLOCATABLE :: MULTI_DATA
!
   real(real64) GLOBAL_MULTIREF_DATA
   DIMENSION GLOBAL_MULTIREF_DATA(:,:,:)
   ALLOCATABLE :: GLOBAL_MULTIREF_DATA
!
   real(real64) GLOBAL_MULTIRAY_DATA
   DIMENSION GLOBAL_MULTIRAY_DATA(:,:,:)
   ALLOCATABLE :: GLOBAL_MULTIRAY_DATA
!
   INTEGER NUMHITS
   DIMENSION NUMHITS(:)
   ALLOCATABLE :: NUMHITS
!
!       PLOTTING
   INTEGER P1ARAY
   DIMENSION P1ARAY(:,:,:)
   ALLOCATABLE :: P1ARAY
!
   LOGICAL FOBRUN
!
   real(real64) OPLCOR
!
!       GRIDS SPECIAL SURFACE UNLOADED FLAG
   LOGICAL GRIDSUNLOADED19(0:499)
   LOGICAL GRIDSUNLOADED20(0:499)
   LOGICAL GRIDSUNLOADED22(0:499)
!
!       FRAME DRAWING FLAG
   LOGICAL FRAME
!
!
!       SEQUENTIAL RAY HISTORY ARRAY
   real(real64) RHIST
   DIMENSION RHIST(:,:,:)
!       DIMENSION 1 GOES FROM 1 TO 86 TO HOLD THE 50 RAY PARAMETERS AND THE 36
!       POSSIBLE DIFFERENTIAL RAY DATA FROM DIFF AND RFDIFF
!       DIMENSION 2 IS A SEQUENTIAL COUNT OF THE RAYS STORED
!       DIMENSION 3 IS THE SURFACE NUMBER FROM 0 TO MAXSUR
!       RAY HISTORIES ARE STORRED FOR EVERY RAY TRACED TO THE SURFACE NUMBER
!       DESIGNATED BY THE "RHIST" COMMANDS FIRST NUMERIC WORD.
!       IF RHIST'S QUALIFIER WORD IS "YES" OR "ON", RAY DATA IS SAVED
!       AFTER EVERY CALL TO SUBROUTINE RAYTRA
   ALLOCATABLE :: RHIST
!       RAY_HIT_FLAG IS ONLY TRUE WHEN RAY HISTORIES ARE TO BE GATHERED
!       AND IS SET BY THE RHIST COMMAND
!       RAY_HIST_NUM IS THE NUMBER OF THE CURRENT RAY BEING ADDED
!       HIST1 IS TRUE IF THE 1:50 REGULAR RAY DATA HAS ALREADY BEEN SAVED
!       HIST2 IS TRUE IF CHIEF DIFFERENTIAL RAY DATA HAS BEEN SAVED
!       HIST3 IS TRUE WHEN REGULAR DIFFERENTIAL RAY DATA HAS BEEN SAVED.
   INTEGER RAY_HIST_NUM,RHIST_MAXRAYS
   LOGICAL RAY_HIST_FLAG
   LOGICAL SHORTHIST,LONGHIST
!       MTRACE STUFF
   real(real64) RW1,RW2,RW3,RW4,RW5,FW1,FW2,FW3,FW4,FW5
   real(real64) SCENE_ARRAY
   DIMENSION SCENE_ARRAY(:,:)
   ALLOCATABLE :: SCENE_ARRAY
!       FIRST INDEX IS 1:3 TO HANDLE AN RGB SCENE BUT ONLY 1 IS USED
!       FOR THE SD PROBLEM
!       INDEX 2 GOES FROM 1 TO FOBNUMBER WHERE THE SEQUENTIAL FOBNUMBER
!       STARTS IN THE FOB -,- CORNER OF THE SCENE AND ROW AT A TIME LEFT TO RIGHT
!       AND THEN UP TO END AT FOB +,+
   LOGICAL MRAYSSET,MFOBSSET
   INTEGER RDF1,RDF2,RDF3,RDF4,RDF5,RCACOCH,FOBNUMBER
!       MULTI-RAY INTENSITY CALCULATION
   real(real64) TEMPHIST,TEMPINTEN,INTEN_ARRAY,INTENLENGTH_ARRAY
   real(real64) INTENPIXDIM
   real(real64) INTEN_XARRAY,INTEN_YARRAY
   DIMENSION TEMPHIST(:,:,:),TEMPINTEN(:,:),INTEN_ARRAY(:,:,:)
   DIMENSION INTEN_XARRAY(:,:),INTEN_YARRAY(:,:)
   ALLOCATABLE :: TEMPHIST,TEMPINTEN,INTEN_ARRAY
   ALLOCATABLE :: INTEN_XARRAY,INTEN_YARRAY
   INTEGER INTENNUM_PIXELS,MAX_INTEN_NUM,INTSURF,INTN,INTDIM
   LOGICAL INTENEXIST
   real(real64) INTTOT,INTOT2,RTOT,IRTOT
!
!       MTRACEI GRID VARIABLES
   real(real64) IGRID,IXARRAY,IYARRAY
   INTEGER IARRAY_DIM
   DIMENSION IGRID(:,:,:),IXARRAY(:,:),IYARRAY(:,:)
   ALLOCATABLE :: IGRID,IXARRAY,IYARRAY
!       IGRID(IX,IY,ICODE)
!       ICODE=1 IF 0, GRID CELL DOES NOT COUNT AS IT IS OUTSIDE THE ASSOCIATED CLAP
!                  1, GRID CELL COUNTS
!       ICODE=2 HOLDS IRRADIANCE VALUE
!       ICODE=3 HOLDS THE INTENSITY VALUE
!       ALLOCATABLE :: IGRID,IXARRAY,IYARRAY
!       END MULTI-RAY INTENSITY VARIABLES
!
   INTEGER WIFONT,WISIZE
!
!     GLOBAL ARRAY DARR USED WITH ITER POWL
   real(real64) DARR
   DIMENSION DARR(:,:)
   ALLOCATABLE :: DARR
!
!     DIFFERENTIAL RAY TRACE TRACKER FOR RAYERROR
   LOGICAL DIFRAYTRACE
!
END MODULE globals
