! SUB MISSREF.FOR

SUBROUTINE MISSREF(X,Y)
!
   use DATLEN
   use DATMAI
   IMPLICIT NONE
!
   EXTERNAL INSID1,INSID2
!
!       THIS CHECKS IF X AND Y IS INSIDE THE CLAP ON THE REFERENCE SURFACE
!
   INTEGER I,CAFLG,N,III,CACOCA
!
   REAL*8 X,Y,Z,ANGLE,JK1,JK2,JK3,&
   &XR,YR,LS,RS,XRD,YRD,X1,X2,X3,X4,Y1,Y2,Y3,Y4,&
   &X5,X6,X7,X8,Y5,Y6,Y7,Y8,XC1,XC2,XC3,XC4,YC1,YC2,&
   &YC3,YC4,RAD2,MAXSID,CS1,CS2,CS3,CS4,A15,A22
!
   LOGICAL INS,INSID1,INSID2
!
   LOGICAL NOCOBSPSF
   COMMON/PSFCOBS/NOCOBSPSF
!
   INTEGER CAERAS,COERAS
!
   COMMON/CACO/CAERAS,COERAS,LS
!
!     VARIABLES FOR SPOT TRACING
!
   LOGICAL TCLPRF,SPDTRA
!
   COMMON/SPRA1/SPDTRA
   I=NEWREF
   LS=0
!
!       I IS THE REF SURFACE NUMBER
!
!
   IF(ALENS(9,I).EQ.0.0D0) THEN
!
!       NO CLAPS OR COBS, JUST RETURN
      RETURN
!       THERE ARE CLAPS AND COBS, PROCEED CHECKING
   END IF
!
   IF(ALENS(9,I).NE.0.0D0) THEN
      CAFLG=INT(ALENS(9,I))
!       CLAP EXISTS
!******************************************************************
!
!       CAFLG=1 CIRCULAR CLAP, DOES IT STOP THE RAY
      IF(CAFLG.EQ.1) THEN
!
         LS=0.0D0
!       CIRCULAR CLAP EQUATION IS:
!
!       (X)**2 + (Y)**2 = R**2
!
!       SUB X AND Y IN THE LEFT SIDE. IF THE LEFT SIDE IS
!       GREATER THAN THE RIGHT SIDE, THE RAY IS BLOCKED
!       ELSE IT IS NOT BLOCKED.
!
!       IF NON-ZERO CLAP DECENTRATIONS EXISTS, THEY MUST BE CONSIDERED
!       IN CLAP CHECKING. WE CONVERT THE RAY COORDINATES X AND Y
!       TO XR AND YR IN THE COORDINATE SYSTEM OF THE DECENTERED
!       CLEAR APERTURE. REMEMBER.

         XR=X-ALENS(13,I)-JK1
         YR=Y-ALENS(12,I)-JK2
!
         LS=DSQRT((XR**2)+(YR**2))
!
         IF(DABS(ALENS(10,I)).LE.DABS(ALENS(11,I))) THEN
            RS=DSQRT(ALENS(10,I)**2)+AIMTOL
         ELSE
            RS=DSQRT(ALENS(11,I)**2)+AIMTOL
         END IF
         IF(REAL(LS).GT.REAL(RS)) THEN
            LS=10.0D0
         ELSE
            LS=0.0D0
         END IF
!
         IF(LS.EQ.10.0D0) THEN
!       RAY IS BLOCKED BY CLAP ON SURFACE I
            REFMISS=.TRUE.
            RETURN
         END IF
      END IF
!       CAFLG NOT 1
   END IF
!
!
!       CAFLG=2 RECTANGULAR CLAP, DOES IT STOP THE RAY
   IF(CAFLG.EQ.2) THEN
!
      LS=0.0D0
!
!       IN THE COORDINATE SYSTEM OF THE RECTANGLE, THE CORNER
!       COORDINATES ARE:
      X1=-ALENS(11,I)-AIMTOL
      Y1=ALENS(10,I)+AIMTOL
      X2=-ALENS(11,I)-AIMTOL
      Y2=-ALENS(10,I)-AIMTOL
      X3=ALENS(11,I)+AIMTOL
      Y3=-ALENS(10,I)-AIMTOL
      X4=ALENS(11,I)+AIMTOL
      Y4=ALENS(10,I)+AIMTOL
!
      XRD=X
      YRD=Y
!
!       IF NON-ZERO CLAP DECENTRATIONS EXISTS, THEY MUST BE CONSIDERED
!       IN CLAP CHECKING. WE CONVERT THE RAY COORDINATES X AND Y
!       TO XRD AND YRD IN THE COORDINATE SYSTEM OF THE DECENTERED
!       CLEAR APERTURE. REMEMBER.

      XRD=XRD-ALENS(13,I)-JK1
      YRD=YRD-ALENS(12,I)-JK2
!
!       IF A NON-ZERO CLAP TILT EXISTS, IT MUST BE CONSIDERED
!       IN CLAP CHECKING. WE CONVERT THE RAY COORDINATES XRD AND YRD
!       TO XR AND YR IN THE COORDINATE SYSTEM OF THE ROTATED
!       CLEAR APERTURE. REMEMBER. GAMMA ROTATION OF A CLAP OR
!       COBS HAS THE SAME SIGN AS IN A SURFACE ROTATION
!     (THE ROTATION IS ALWAYS ABOUT THE LOCAL Z-AXIS OF THE SURFACE VERTEX)

      A15=(ALENS(15,I)+JK3)*PII/180.0D0
      XR=(XRD*DCOS(A15))+(YRD*DSIN(A15))
      YR=(YRD*DCOS(A15))-(XRD*DSIN(A15))
!       ARE THE POINTS XR AND YR ON THE RECTANGLE OR OUTSIDE
!       IF YES, SET LS=10.0D0
!       IF NO SET LS=0.0D0
      XT(1)=X1
      YT(1)=Y1
      XT(2)=X2
      YT(2)=Y2
      XT(3)=X3
      YT(3)=Y3
      XT(4)=X4
      YT(4)=Y4
      NP=4
      X0=XR
      Y0=YR
      INS=INSID1()
      IF(INS) THEN
!       RAY NOT BLOCKED
         LS=0.0D0
      ELSE
!       RAY BLOCKED
         LS=10.0D0
      END IF
!
      IF(LS.EQ.10.0D0) THEN
!       RAY IS BLOCKED BY CLAP ON SURFACE I
         REFMISS=.TRUE.
         RETURN
      END IF
!       CAFLG NOT 2
   END IF
!
!       CAFLG=3 ELLIPTICAL CLAP, DOES IT STOP THE RAY
   IF(CAFLG.EQ.3) THEN
!
      LS=0.0D0
!       ELLIPTICAL CLAP EQUATION IS:
!
!       (X)**2/A**2  + (Y)**2/B**2 = 1
!
!       SUB X AND Y IN THE LEFT SIDE. IF THE LEFT SIDE IS
!       GREATER THAN 1.0D0, THE RAY IS BLOCKED
!       ELSE IT IS NOT BLOCKED.
!
      XRD=X
      YRD=Y
!
!       IF NON-ZERO CLAP DECENTRATIONS EXISTS, THEY MUST BE CONSIDERED
!       IN CLAP CHECKING. WE CONVERT THE RAY COORDINATES X AND Y
!       TO XRD AND YRD IN THE COORDINATE SYSTEM OF THE DECENTERED
!       CLEAR APERTURE. REMEMBER.

      XRD=XRD-ALENS(13,I)-JK1
      YRD=YRD-ALENS(12,I)-JK2
!
!       IF A NON-ZERO CLAP TILT EXISTS, IT MUST BE CONSIDERED
!       IN CLAP CHECKING. WE CONVERT THE RAY COORDINATES XRD AND YRD
!       TO XR AND YR IN THE COORDINATE SYSTEM OF THE ROTATED
!       CLEAR APERTURE. REMEMBER. GAMMA ROTATION OF A CLAP OR
!       COBS HAS THE SAME SIGN AS IN A SURFACE ROTATION

      A15=ALENS(15,I)*PII/180.0D0
      A15=(ALENS(15,I)+JK3)*PII/180.0D0
      XR=(XRD*DCOS(A15))+(YRD*DSIN(A15))
      YR=(YRD*DCOS(A15))-(XRD*DSIN(A15))
      LS=((XR**2)/(ALENS(11,I)**2))+&
      &((YR**2)/(ALENS(10,I)**2))
!
      IF(REAL(LS).GT.(1.0+(AIMTOL**2))) THEN
!       RAY BLOCKED
         LS=10.0D0
      ELSE
!       NOT BLOCKED
         LS=0.0D0
      END IF
!
      IF(LS.EQ.10.0D0) THEN
         REFMISS=.TRUE.
         RETURN
      END IF
!       CAFLG NOT 3
   END IF
!
!
!       CAFLG=4 RACETRACK CLAP, DOES IT STOP THE RAY
   IF(CAFLG.EQ.4) THEN
!
      LS=0.0D0
!
!       IF THE RADIUS OF THE CORNERS IS LESS THAN THE LARGER
!       OF THE TWO SIDE DIMENSIONS, AN 8 SIDED POLYGON NEEDS TO BE
!       CHECKED AS WELL AS THE FOUR CIRCLES. IF NOT, THE BASE RECTANGE
!       AND THE FOUR CIRCLES NEED TO BE CHECKED.
!
      IF(ALENS(10,I).LE.ALENS(11,I)) THEN
!       ALENS(11,I) = MAXSID
         MAXSID=ALENS(11,I)
      ELSE
         MAXSID=ALENS(10,I)
      END IF
      IF(ALENS(14,I).LT.MAXSID) THEN
!       SETUP THE 8 SIDED BOX
         N=8
         X1=-ALENS(11,I)+ALENS(14,I)-AIMTOL
         Y1=ALENS(10,I)+AIMTOL
         X2=-ALENS(11,I)-AIMTOL
         Y2=ALENS(10,I)-ALENS(14,I)+AIMTOL
         X3=-ALENS(11,I)-AIMTOL
         Y3=-ALENS(10,I)+ALENS(14,I)-AIMTOL
         X4=-ALENS(11,I)+ALENS(14,I)-AIMTOL
         Y4=-ALENS(10,I)-AIMTOL
         X5=ALENS(11,I)-ALENS(14,I)+AIMTOL
         Y5=-ALENS(10,I)-AIMTOL
         X6=ALENS(11,I)+AIMTOL
         Y6=-ALENS(10,I)+ALENS(14,I)-AIMTOL
         X7=ALENS(11,I)+AIMTOL
         Y7=ALENS(10,I)-ALENS(14,I)+AIMTOL
         X8=ALENS(11,I)-ALENS(14,I)+AIMTOL
         Y8=ALENS(10,I)+AIMTOL
!
!
      ELSE
!       SET UP THE FOUR SIDED BOX
         N=4
         X1=-ALENS(11,I)-AIMTOL
         Y1=ALENS(10,I)+AIMTOL
         X2=-ALENS(11,I)-AIMTOL
         Y2=-ALENS(10,I)-AIMTOL
         X3=ALENS(11,I)+AIMTOL
         Y3=-ALENS(10,I)-AIMTOL
         X4=ALENS(11,I)+AIMTOL
         Y4=ALENS(10,I)+AIMTOL
      END IF
!
      XRD=X
      YRD=Y
!
!       IF NON-ZERO CLAP DECENTRATIONS EXISTS, THEY MUST BE CONSIDERED
!       IN CLAP CHECKING. WE CONVERT THE RAY COORDINATES X AND Y
!       TO XRD AND YRD IN THE COORDINATE SYSTEM OF THE DECENTERED
!       CLEAR APERTURE. REMEMBER.

      XRD=XRD-ALENS(13,I)-JK1
      YRD=YRD-ALENS(12,I)-JK2
!
!       IF A NON-ZERO CLAP TILT EXISTS, IT MUST BE CONSIDERED
!       IN CLAP CHECKING. WE CONVERT THE RAY COORDINATES XRD AND YRD
!       TO XR AND YR IN THE COORDINATE SYSTEM OF THE ROTATED
!       CLEAR APERTURE. REMEMBER. GAMMA ROTATION OF A CLAP OR
!       COBS HAS THE SAME SIGN AS IN A SURFACE ROTATION

      A15=ALENS(15,I)*PII/180.0D0
      A15=(ALENS(15,I)+JK3)*PII/180.0D0
      XR=(XRD*DCOS(A15))+(YRD*DSIN(A15))
      YR=(YRD*DCOS(A15))-(XRD*DSIN(A15))
!       ARE THE POINTS XR AND YR ON THE POLYGON OR OUTSIDE
!       IF YES, SET LS=10.0D0
!       IF NO SET LS=0.0D0
      IF(N.EQ.4) THEN
         XT(1)=X1
         YT(1)=Y1
         XT(2)=X2
         YT(2)=Y2
         XT(3)=X3
         YT(3)=Y3
         XT(4)=X4
         YT(4)=Y4
      ELSE
         XT(1)=X1
         YT(1)=Y1
         XT(2)=X2
         YT(2)=Y2
         XT(3)=X3
         YT(3)=Y3
         XT(4)=X4
         YT(4)=Y4
         XT(5)=X5
         YT(5)=Y5
         XT(6)=X6
         YT(6)=Y6
         XT(7)=X7
         YT(7)=Y7
         XT(8)=X8
         YT(8)=Y8
      END IF
      NP=N
      X0=XR
      Y0=YR
      INS=INSID1()
      IF(INS) THEN
!       RAY NOT BLOCKED
         LS=0.0D0
      ELSE
!       RAY BLOCKED
         LS=10.0D0
      END IF
! NOW IS THE POINT INSIDE ANY OF THE FOUR CIRCLES
!       CENTER OF THE FIRST CIRCLE IS AT
      XC1=-ALENS(11,I)+ALENS(14,I)
      YC1= ALENS(10,I)-ALENS(14,I)
      CS1=DSQRT(((XR-XC1)**2)+((YR-YC1)**2))
!       CENTER OF THE SECOND CIRCLE IS AT
      XC2= -ALENS(11,I)+ALENS(14,I)
      YC2= -ALENS(10,I)+ALENS(14,I)
      CS2=DSQRT(((XR-XC2)**2)+((YR-YC2)**2))
!       CENTER OF THE THIRD CIRCLE IS AT
      XC3= ALENS(11,I)-ALENS(14,I)
      YC3=-ALENS(10,I)+ALENS(14,I)
      CS3=DSQRT(((XR-XC3)**2)+((YR-YC3)**2))
!       CENTER OF THE FIRST CIRCLE IS AT
      XC4=ALENS(11,I)-ALENS(14,I)
      YC4=ALENS(10,I)-ALENS(14,I)
      CS4=DSQRT(((XR-XC4)**2)+((YR-YC4)**2))
!
      RAD2=DSQRT(ALENS(14,I)**2)+AIMTOL
!

      IF(.NOT.INS.AND.REAL(CS1).GT.REAL(RAD2)&
      &.AND.REAL(CS2).GT.REAL(RAD2).AND.&
      &REAL(CS3).GT.REAL(RAD2).AND.REAL(CS4).GT.REAL(RAD2)) THEN
!       RAY IS BLOCKED BY ONE OF THE CIRCLES AND THE BOX
         LS=10.0D0
      ELSE
!     RAY PASSES THROUGH A CIRCLE
         LS=0.0D0
      END IF
!
      IF(LS.EQ.10.0D0) THEN
!       RAY IS BLOCKED BY CLAP ON SURFACE I
         REFMISS=.TRUE.
         RETURN
      END IF
!       CAFLG NOT 4
   END IF
!
!       CAFLG=5 POLY CLAP, DOES IT STOP THE RAY
   IF(CAFLG.EQ.5) THEN
      LS=0.0D0
!
!       IN THE COORDINATE SYSTEM OF THE POLYGON, THE CORNER
!       NUMBER OF POINTS IS ALENS(11,I), CENTER TO CORNER DISTANCE
!       IS ALENS(10,II). POINTS GO COUNTER CLOCKWISE LOOKING
!       TOWARD THE +Z DIRECTION
!       COORDINATES ARE:
      ANGLE=0.0D0
      DO III=1,INT(ALENS(11,I))
         XT(III)=ALENS(10,I)*DCOS(ANGLE+(PII/2.0D0))
         YT(III)=ALENS(10,I)*DSIN(ANGLE+(PII/2.0D0))
         ANGLE=ANGLE+((TWOPII)/ALENS(11,I))
      END DO
      XRD=X
      YRD=Y
!
!       IF NON-ZERO CLAP ERASE DECENTRATIONS EXISTS, THEY MUST BE CONSIDERED
!       IN CLAP ERASE CHECKING. WE CONVERT THE RAY COORDINATES X AND Y
!       TO XRD AND YRD IN THE COORDINATE SYSTEM OF THE DECENTERED
!       CLEAR APERTURE ERASE. REMEMBER.
!
      XRD=XRD-ALENS(13,I)-JK1
      YRD=YRD-ALENS(12,I)-JK2
!
!       IF A NON-ZERO CLAP ERASE TILT EXISTS, IT MUST BE CONSIDERED
!       IN CLAP ERASE CHECKING. WE CONVERT THE RAY COORDINATES XRD AND YRD
!       TO XR AND YR IN THE COORDINATE SYSTEM OF THE ROTATED
!       CLEAR APERTURE ERASE. REMEMBER.

      A15=ALENS(15,I)*PII/180.0D0
      A15=(ALENS(15,I)+JK3)*PII/180.0D0
      XR=(XRD*DCOS(A15))+(YRD*DSIN(A15))
      YR=(YRD*DCOS(A15))-(XRD*DSIN(A15))
!
!       ARE THE POINTS XR AND YR ON THE RECTANGLE OR OUTSIDE
      X0=XR
      Y0=YR
      NP=INT(ALENS(11,I))
      INS=INSID1()
      IF(INS) THEN
!       RAY NOT BLOCKED
         LS=0.0D0
      ELSE
!       RAY BLOCKED
         LS=10.0D0
      END IF
!
      IF(LS.EQ.10.0D0) THEN
!       RAY IS BLOCKED BY CLAP ON SURFACE I
         REFMISS=.TRUE.
         RETURN
      END IF
!       CAFLG NOT 5
   END IF
!
!       CAFLG=6 IPOLY CLAP, DOES IT STOP THE RAY
   IF(CAFLG.EQ.6) THEN
      LS=0.0D0
!
!       POINTS GO COUNTER CLOCKWISE LOOKING
!       TOWARD THE +Z DIRECTION
!       COORDINATES ARE:
      ANGLE=0.0D0
      DO III=1,INT(ALENS(11,I))
         XT(III)=IPOLYX(III,I,1)
         YT(III)=IPOLYY(III,I,1)
      END DO
      XRD=X
      YRD=Y
!
!       IF NON-ZERO CLAP ERASE DECENTRATIONS EXISTS, THEY MUST BE CONSIDERED
!       IN CLAP ERASE CHECKING. WE CONVERT THE RAY COORDINATES X AND Y
!       TO XRD AND YRD IN THE COORDINATE SYSTEM OF THE DECENTERED
!       CLEAR APERTURE ERASE. REMEMBER.
!
      XRD=XRD-ALENS(13,I)-JK1
      YRD=YRD-ALENS(12,I)-JK2
!
!       IF A NON-ZERO CLAP ERASE TILT EXISTS, IT MUST BE CONSIDERED
!       IN CLAP ERASE CHECKING. WE CONVERT THE RAY COORDINATES XRD AND YRD
!       TO XR AND YR IN THE COORDINATE SYSTEM OF THE ROTATED
!       CLEAR APERTURE ERASE. REMEMBER.

      A15=ALENS(15,I)*PII/180.0D0
      A15=(ALENS(15,I)+JK3)*PII/180.0D0
      XR=(XRD*DCOS(A15))+(YRD*DSIN(A15))
      YR=(YRD*DCOS(A15))-(XRD*DSIN(A15))
!
!       ARE THE POINTS XR AND YR ON THE RECTANGLE OR OUTSIDE
      X0=XR
      Y0=YR
      NP=INT(ALENS(11,I))
      INS=INSID1()
      IF(INS) THEN
!       RAY NOT BLOCKED
         LS=0.0D0
      ELSE
!       RAY BLOCKED
         LS=10.0D0
      END IF
!
      IF(LS.EQ.10.0D0) THEN
!       RAY IS BLOCKED BY CLAP ON SURFACE I
         REFMISS=.TRUE.
         RETURN
      END IF
!       CAFLG NOT 6
   END IF
!
   RETURN
END
