!       FIFTEENTH FILE FOR LENS DATABASE MANAGER FILES

! SUB LNSEOS.FOR
SUBROUTINE LNSEOS
   USE GLOBALS
   use zoa_ui_callbacks, only: notify_replot, notify_refresh_status
!
!     CALLS LNSEOS1. THIS IS HERE TO SUPPORT AUTOFUNC
!
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
   LOGICAL SAV2,RES2,EXIS49
!
   INTEGER I,J,OF5,OF6,ALLOERR
   COMMON/OLDFVAL/OF5,OF6
!
   OF5=F5
   OF6=F6

   OUTLYNE = "LNSEOS ROUTINE STARTING! "
   CALL SHOWIT(19)

!
   IF(CFLDCNT.EQ.0) THEN
!       SET UP THREE FIELD OF VIEW POSITIONS AT 0.7 AND 1.0
      CFLDCNT=3
      CFLDS(1,1)=0.0D0
      CFLDS(1,2)=0.0D0
      CFLDS(1,3)=0.0D0
      CFLDS(2,1)=0.0D0
      CFLDS(2,2)=0.7D0
      CFLDS(2,3)=1.0D0
   END IF
!     RESTORE DECENTERS TO CONVER PIVOTS
   IF(SYSTEM(20).GT.DBLE(MAXSUR)) SYSTEM(20)=DBLE(MAXSUR)
   I=INT(SYSTEM(20))
   ALENS(29,1:I) = 0.0D0
   ALENS(30,1:I) = ALENS(114,1:I)
   ALENS(31,1:I) = ALENS(115,1:I)
   ALENS(69,1:I) = ALENS(116,1:I)
   ALENS(26,1:I) = ALENS(118,1:I)
   ALENS(27,1:I) = ALENS(119,1:I)
   ALENS(28,1:I) = ALENS(120,1:I)
   DO I=0,INT(SYSTEM(20))
      IF(surf_decenter_x(I).NE.0.0D0.OR.surf_decenter_y(I).NE.0.0D0.OR.surf_decenter_z(I).NE.0.0D0) call set_surf_decenter_flag(I, 1)
   END DO
!
   IF(INT(SYSTEM(91)).EQ.0) F57=0
!
   IF(F57.EQ.0) THEN
!       ALLOCATE THE MULTIHIT ARRAYS AND P1ARAY
      DEALLOCATE(GLOBAL_MULTIRAY_DATA,GLOBAL_MULTIREF_DATA,MULTIRAY_DATA,MULTIREF_DATA,MULTI_DATA,P1ARAY,STAT=ALLOERR)
      IF(.NOT.ALLOCATED(MULTIRAY_DATA)) THEN
         IF(SYSTEM(102).EQ.1.0D0) THEN
!       AN NSS TUBE SURFACE IS PRESENT, ALLOCATE MEMORY
            DEALLOCATE(GLOBAL_MULTIRAY_DATA,GLOBAL_MULTIREF_DATA,MULTIRAY_DATA,MULTIREF_DATA,MULTI_DATA,P1ARAY,STAT=ALLOERR)
            ALLOCATE(GLOBAL_MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS),GLOBAL_MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS),MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS),MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS),MULTI_DATA(1:50,0:MAXSUR,1:MRAYS),P1ARAY(0:360,1:3,1:MRAYS),STAT=ALLOERR)
            GLOBAL_MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
            GLOBAL_MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
            MULTI_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
            MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
            MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
         ELSE
            DEALLOCATE(P1ARAY,STAT=ALLOERR)
            ALLOCATE(P1ARAY(0:360,1:3,1:MRAYS),STAT=ALLOERR)
         END IF
      END IF
      CALL LNSEOS1
      OUTLYNE = "LNSEOS1 CALL FINISHED 81"
      CALL SHOWIT(19)
      IF(OF5.EQ.1) THEN
!     SET PARAXIAL FLAGS TO FALSE
         CALL PRTRB
         OUTLYNE = "DONE WITH PRTRB"
         CALL SHOWIT(19)
         OUTLYNE = "ABOUT TO CALL PRTRC"
         CALL SHOWIT(19)
         CALL PRTRC
         OUTLYNE = "DONE WITH PRTRC"
         CALL SHOWIT(19)
         CALL PRTRD
         OUTLYNE = "DONE WITH PRTRD"
         CALL SHOWIT(19)
      END IF
      ! JN:  Added this to force replot after lens update
      ! TODO:  There are multiple returns in this sub
      ! Not sure If I should do this in all exits
      call notify_replot()
      call notify_refresh_status()
      RETURN
   END IF
   IF(F57.EQ.1) THEN
      F57=0
!       ALLOCATE THE MULTIHIT ARRAYS AND P1ARAY
      DEALLOCATE(GLOBAL_MULTIRAY_DATA,GLOBAL_MULTIREF_DATA,MULTIRAY_DATA,MULTIREF_DATA,MULTI_DATA,P1ARAY,STAT=ALLOERR)
      IF(.NOT.ALLOCATED(MULTIRAY_DATA)) THEN
         IF(SYSTEM(102).EQ.1.0D0) THEN
!       AN NSS TUBE SURFACE IS PRESENT, ALLOCATE MEMORY
            DEALLOCATE(GLOBAL_MULTIRAY_DATA,GLOBAL_MULTIREF_DATA,MULTIRAY_DATA,MULTIREF_DATA,P1ARAY,MULTI_DATA,STAT=ALLOERR)
            ALLOCATE(GLOBAL_MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS),GLOBAL_MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS),MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS),MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS),MULTI_DATA(1:50,0:MAXSUR,1:MRAYS),P1ARAY(0:360,1:3,1:MRAYS),STAT=ALLOERR)
            GLOBAL_MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
            GLOBAL_MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
            MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
            MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
            MULTI_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
         ELSE
            DEALLOCATE(P1ARAY,STAT=ALLOERR)
            ALLOCATE(P1ARAY(0:360,1:3,1:MRAYS),STAT=ALLOERR)
         END IF
      END IF
      CALL LNSEOS1
      OUTLYNE = "LNSEOS1 CALL FINISHED 120"
      CALL SHOWIT(19)
      IF(OF5.EQ.1) THEN
!     SET PARAXIAL FLAGS TO FALSE
         CALL PRTRB
         CALL PRTRC
         CALL PRTRD
      END IF
      F57=1
      F1=0
      F6=1
      F22=1
      LNSTYP=2
   END IF
!
   IF(F6.EQ.1) THEN
      IF(F57.EQ.1) THEN
         F57=0
!       ALLOCATE THE MULTIHIT ARRAYS AND P1ARAY
         DEALLOCATE(GLOBAL_MULTIRAY_DATA,GLOBAL_MULTIREF_DATA,MULTIRAY_DATA,MULTIREF_DATA,MULTI_DATA,P1ARAY,STAT=ALLOERR)
         IF(.NOT.ALLOCATED(MULTIRAY_DATA)) THEN
            IF(SYSTEM(102).EQ.1.0D0) THEN
!       AN NSS TUBE SURFACE IS PRESENT, ALLOCATE MEMORY
               DEALLOCATE(GLOBAL_MULTIRAY_DATA,GLOBAL_MULTIREF_DATA,MULTIRAY_DATA,MULTIREF_DATA,P1ARAY,MULTI_DATA,STAT=ALLOERR)
               ALLOCATE(GLOBAL_MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS),GLOBAL_MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS),MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS),MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS),MULTI_DATA(1:50,0:MAXSUR,1:MRAYS),P1ARAY(0:360,1:3,1:MRAYS),STAT=ALLOERR)
               GLOBAL_MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
               GLOBAL_MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
               MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
               MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
               MULTI_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
            ELSE
               DEALLOCATE(P1ARAY,STAT=ALLOERR)
               ALLOCATE(P1ARAY(0:360,1:3,1:MRAYS),STAT=ALLOERR)
            END IF
         END IF
         CALL LNSEOS1
         OUTLYNE = "LNSEOS1 CALL FINISHED 165"
         CALL SHOWIT(19)
!       REFRESH 357 ABERRATIONS
         IF(OF5.EQ.1) THEN
!     SET PARAXIAL FLAGS TO FALSE
            CALL PRTRB
            CALL PRTRC
            CALL PRTRD
         END IF
!     AUTOFUNC (binary macro merit functions) removed
         OUTLYNE='AUTOFUNC REQUIRES BINARY MACRO FUNCTIONS (FUN01-FUN10)'
         CALL SHOWIT(1)
         OUTLYNE='BINARY MACRO SYSTEM REMOVED - AUTOFUNC NOT SUPPORTED'
         CALL SHOWIT(1)
         CALL MACFAL
         GO TO 5000
         F1=0
         F6=1
         F22=1
         LNSTYP=2
!       ALLOCATE THE MULTIHIT ARRAYS AND P1ARAY
         DEALLOCATE(GLOBAL_MULTIRAY_DATA,GLOBAL_MULTIREF_DATA,MULTIRAY_DATA,MULTIREF_DATA,MULTI_DATA,P1ARAY,STAT=ALLOERR)
!       DO WE NEED TO ALLOCATE THE MULTIHIT ARRAYS
         IF(.NOT.ALLOCATED(MULTIRAY_DATA)) THEN
            IF(SYSTEM(102).EQ.1.0D0) THEN
!       AN NSS TUBE SURFACE IS PRESENT, ALLOCATE MEMORY
               DEALLOCATE(GLOBAL_MULTIRAY_DATA,GLOBAL_MULTIREF_DATA,MULTIRAY_DATA,MULTIREF_DATA,MULTI_DATA,P1ARAY,STAT=ALLOERR)
               ALLOCATE(GLOBAL_MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS),GLOBAL_MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS),MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS),MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS),MULTI_DATA(1:50,0:MAXSUR,1:MRAYS),P1ARAY(0:360,1:3,1:MRAYS),STAT=ALLOERR)
               GLOBAL_MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
               GLOBAL_MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
               MULTIRAY_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
               MULTIREF_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
               MULTI_DATA(1:50,0:MAXSUR,1:MRAYS)=0.0D0
            ELSE
               DEALLOCATE(P1ARAY,STAT=ALLOERR)
               ALLOCATE(P1ARAY(0:360,1:3,1:MRAYS),STAT=ALLOERR)
            END IF
         END IF
         CALL LNSEOS1
         OUTLYNE = "LNSEOS1 CALL FINISHED 510"
         CALL SHOWIT(19)
         IF(OF5.EQ.1) THEN
!     SET PARAXIAL FLAGS TO FALSE
            CALL PRTRB
            CALL PRTRC
            CALL PRTRD
         END IF
         F57=1
      END IF
   END IF
5000 CONTINUE
   call LogTermFOR("After LNNSEOS1 I presume?")
   RETURN
END
SUBROUTINE TILT_RETURN(ERCODE,TRYES)
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
   INTEGER I,J
   LOGICAL ERCODE,TRYES
!     TEST FOR NESTED TILT RETS
   DO I=0,INT(SYSTEM(20))
      IF(surf_tilt_flag(I) == 6) THEN
         TRYES=.TRUE.
!     FOUND A TILT RET ON SURFACE I
!     THAT TILT RET MUST NOT REFER TO A SURFACE WITH A TILT RET ON IT
         J=INT(surf_ret_surf_num(I))
         IF(surf_tilt_flag(J) == 6) THEN
!     TILT RET REFERS TO A SURFACE WHICH HAS A TILT RET ON IT, DROP THE
!     TILT RETURN
            ALENS(25:28,I)=0.0D0
            ALENS(118:120,I)=0.0D0
            call set_surf_ret_surf_num(I, 0)
            ALENS(77:80,I)=0.0D0
            call set_surf_pivot_flag(I, 0)
            ALENS(90:95,I)=0.0D0
            ERCODE=.TRUE.
            WRITE(OUTLYNE,*)'"TILT RET" ON SURFACE ',I
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'REFERS TO SURFACE ',J,' WHICH ITSELF HAS'
            CALL SHOWIT(1)
            OUTLYNE='A "TILT RET" ASSIGNED TO IT'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'THE "TILT RET" ON SURFACE ',I,' IS BEING DELETED'
            CALL SHOWIT(1)
         END IF
      ELSE
!     NO TILT RET ON SURFACE I
      END IF
   END DO
   DO I=0,INT(SYSTEM(20))
      IF(surf_tilt_flag(I) == 6) THEN
!     TILT RET
         DO J=0,I
            IF(surf_tilt_flag(J) == 2.OR.surf_tilt_flag(J) == 3) THEN
!     PREVIOUS TILT AUTO FOUND
!     DELETE THE TILT RET ON I
               ALENS(25:28,I)=0.0D0
               ALENS(118:120,I)=0.0D0
               call set_surf_ret_surf_num(I, 0)
               ALENS(77:80,I)=0.0D0
               call set_surf_pivot_flag(I, 0)
               ALENS(90:95,I)=0.0D0
               ERCODE=.TRUE.
               WRITE(OUTLYNE,*)'"TILT RET" ON SURFACE ',I
               CALL SHOWIT(1)
               WRITE(OUTLYNE,*)'IS PRECEEDED BY A "TILT AUTO(M)" ON SURFACE',J
               CALL SHOWIT(1)
               WRITE(OUTLYNE,*)'THE "TILT RET" ON SURFACE ',I,' IS BEING DELETED'
               CALL SHOWIT(1)
            ELSE
!     TO PREV TILT AUTO FOUND
            END IF
         END DO
      ELSE
!     NO TILT RET
      END IF
   END DO
   DO I=0,INT(SYSTEM(20))
      IF(surf_tilt_flag(I) == 6) THEN
!     TILT RET
         IF(INT(surf_ret_surf_num(I)).GE.I) THEN
            ERCODE=.TRUE.
            WRITE(OUTLYNE,*)'"TILT RET" ON SURFACE ',I
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'REFERS TO A FOLLOWING SURFACE'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'THE "TILT RET" ON SURFACE ',I,' IS BEING DELETED'
            CALL SHOWIT(1)
         ELSE
!     REFERS TO EARLIER SURFACE
         END IF
      ELSE
!     NO TILT RET
      END IF
   END DO
   RETURN
END
! SUB LNSEOS1.FOR
SUBROUTINE LNSEOS1
   use global_widgets
   use kdp_data_types, only: check_clear_apertures
   use paraxial_ray_trace_test, only: PRTRA_NEW
   USE GLOBALS

!     NOTE ON 11/04/96 THIS ROUTINE ONLY HAS ONE SUCCESSFUL RETURN
!     AND IT IS AT THE BOTTOM OF THE ROUTINE
!
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE LNSEOS. THIS IS THE SUBROUTINE WHICH
!       HANDLES THE COMMAND EOS WHEN ISSUED FROM THE NEW LENS INPUT
!       OR LENS UPDATE MODE.
!
   LOGICAL REDOLNSEOS,JKOFF,BADGLS,ERCODE,TRYES,LPASS1
   REAL*8 RD,INDEX,VNUM
!
   COMMON/GLSBAD/BADGLS

!
   INTEGER KIL,IST,LST,ITYPEP,CFI,CFJ,CFF12,IPASS1,IPASS2 ,KKKK,I,II,III,SLVMRK,ITT,IFF,TESTIT,J,K,ZZTOP, JJ
!
   COMMON/DPIKER/CFI,CFJ,CFF12
!
   COMMON/PTYPER/ITYPEP
!
   REAL*8 YCLAP,XCLAP,XTERM,YTERM,A1,A2,JK_TEMP
!
   LOGICAL NOSTOP,NOREF,SKIP
!


   OUTLYNE = "LNSEOS1 Routine Starting!"
   CALL SHOWIT(19)
!       IF F28 OR F31 ARE 1, WE ARE IN OPTIM OR TOLER
!       AND SOME THINGS GET SKIPPED
   SKIP=.FALSE.
   IF(F28.EQ.1.OR.F31.EQ.1.OR.LNSTYP.NE.1) SKIP=.TRUE.
!
   SELECT CASE (SKIP)
    CASE (.TRUE.)
!       FIX SECOND NUMERIC WORD IN SCY/SCX/SCY FANG/SCX FANG
!       AND ASTOP ASSIGNMENT
      NOSTOP=.TRUE.
      NOREF=.TRUE.
      IF(INT(SYSTEM(25)).GE.0.AND.INT(SYSTEM(25)).LE.INT(SYSTEM(20)))NOREF=.FALSE.
      IF(INT(SYSTEM(26)).GE.0.AND.INT(SYSTEM(26)).LE.INT(SYSTEM(20)))NOSTOP=.FALSE.
!       IF NO REF SURF AND NO STOP, MAKE REF SURF = SURFACE 1
      IF(NOREF.AND.NOSTOP) THEN
         SYSTEM(25)=1.0D0
      END IF
!       IF NO REF SURF BUT THERE IS A STOP, MAKE REF SURF = STOP SURF
      IF(.NOT.NOSTOP.AND.NOREF) THEN
         SYSTEM(25)=SYSTEM(26)
      END IF
      IF(.NOT.NOSTOP) THEN
!       THERE IS A STOP SURFACE, ZERO OUT SECOND NUMERIC WORDS OF
!       SCY,SCX,SCY FANG AND SCX FANG
         SYSTEM(15)=0.0D0
         SYSTEM(17)=0.0D0
         SYSTEM(22)=0.0D0
         SYSTEM(24)=0.0D0
      END IF
!
   END SELECT
!
   REDOLNSEOS=.FALSE.



!       999 IS A RE-ENTRY POINT
999 CONTINUE
   SELECT CASE (SKIP)
    CASE (.TRUE.)
!       CHECK FOR OBJECT THICKNESS ZERO
      IF(DABS(surf_thickness(0)).EQ.0.0D0) THEN
         OUTLYNE='WARNING: OBJECT THICKNESS IS ZERO'
         CALL SHOWIT(1)
         OUTLYNE='IS CHANGED TO 1.0D20'
         CALL SHOWIT(1)
         call set_surf_thickness(0, 1.0D20)
      END IF
!       CHECK FOR OBJECT THICKNESS LESS THAN SAY OR SAX
      IF(DABS(surf_thickness(0)).LT.0.01D0) THEN
         OUTLYNE='WARNING: OBJECT THICKNESS IS LESS THAN 0.01 LENS UNITS.'
         CALL SHOWIT(1)
         OUTLYNE='INCREASE THE OBJECT THICKNESS IN ORDER TO AVOID OPD'
         CALL SHOWIT(1)
         OUTLYNE='INACCURACIES'
         CALL SHOWIT(1)
      END IF
!       CHECK FOR SURFACE THICKNESS MAG GREATER THAN 1E200
!     OR LESS THAN 1.0D-20
!       THIS HELPS OVERFLOWING ON MACHINES.
      DO KIL=0,INT(SYSTEM(20))
         IF(surf_thickness(KIL).GT.1.0D200)call set_surf_thickness(KIL, 1.0D200)
         IF(surf_thickness(KIL).LT.-1.0D200)call set_surf_thickness(KIL, -1.0D200)
         IF(DABS(surf_thickness(KIL)).LT.1.0D-20)call set_surf_thickness(KIL, 0.0D0)
      END DO
!       RESET NEWOBJ,NEWREF AND NEWIMG
      CALL RESSUR
      !OUTLYNE = "JUST FINISHED RESSUR"
      !CALL SHOWIT(19)
!
      IF(SYSTEM(18).EQ.1.0D0) SYSTEM(19)=1.0D0
      IF(SYSTEM(18).EQ.0.0D0) SYSTEM(19)=0.0D0
!
!       SET REFEXT TO FALSE AND NULL TO TRUE
      IF(RAYCLEAR) THEN
         FOBYES=.FALSE.
         NULL=.TRUE.
         FAIL=.TRUE.
         RAYEXT=.FALSE.
         POLEXT=.FALSE.
         REFEXT=.FALSE.
         SPDEXT=.FALSE.
         GSPDEXT=.FALSE.
         CPFNEXT=.FALSE.
         CALL DELPSF
         OUTLYNE = "JUST FINISHED DELPSF"
         CALL SHOWIT(19)
      END IF
   END SELECT
   II=INT(SYSTEM(20))
   ALENS(109,1:II)=0.0D0
   IF(F5.EQ.1) THEN
!       LENS INPUT, UNLOAD THE GRID FILES
      ALENS(88,1:II)=0.0D0
      IPASS1=1
      IPASS2=0
      LPASS1=.FALSE.
      GRIDSUNLOADED19(0:MAXSUR)=.TRUE.
      GRIDSUNLOADED20(0:MAXSUR)=.TRUE.
      GRIDSUNLOADED22(0:MAXSUR)=.TRUE.
      CALL GRIDS(1,0,LPASS1)
      OUTLYNE = "JUST FINISHED GRIDS"
      CALL SHOWIT(19)
   END IF
!
!     RESOLVE FICT GLASS TYPE IN OPTIM AND TOLER

   IF(LNSTYP.EQ.2.OR.LNSTYP.EQ.3) THEN
!       NOW RESOLVE THE CALCULATION OF REFRACTIVE INDICES VIA
!       GLASS CATALOG SEARCHES
!
!     FIX LEADING COLON IN GLASS NAME
      DO I=0,INT(SYSTEM(20))
         IF(GLANAM(I,2)(1:1).EQ.':') GLANAM(I,2)(1:13)=GLANAM(I,2)(2:13)
         IF(GLANMP(I,2)(1:1).EQ.':') GLANMP(I,2)(1:13)=GLANMP(I,2)(2:13)
      END DO
      call logger%logText('About to call GLSRES 780')
      CALL GLSRES
      OUTLYNE = "JUST FINISHED GLSRES"
      CALL SHOWIT(19)
   END IF
!
   IF(LNSTYP.EQ.1) THEN
!
!       AS VARIOUS FEATURES ARE ADDED TO THE LENS SUBFILE, THINGS
!       SUCH AS THE PARAXIAL SOLVES OR THE PIKUPS, THEY WILL
!       REQUIRE RESOLUTION PRIOR TO A RETURN TO THE CMD LEVEL.
!
!       NOW RESOLVE THE CALCULATION OF REFRACTIVE INDICES VIA
!       GLASS CATALOG SEARCHES IF F22=1. DONE FOR THE CURRENT
!       CONFIGURATION ONLY.
!
!       PROCEED TO CHECK CATALOGS
!
!     FIX LEADING COLON IN GLASS NAME
      DO I=0,INT(SYSTEM(20))
         IF(GLANAM(I,2)(1:1).EQ.':') GLANAM(I,2)(1:13)=GLANAM(I,2)(2:13)
         IF(GLANMP(I,2)(1:1).EQ.':') GLANMP(I,2)(1:13)=GLANMP(I,2)(2:13)
      END DO
!
      BADGLS=.FALSE.
      IF(F22.EQ.1) THEN
         !call logger%logText('About to call GLSRES 806')
         CALL GLSRES
         OUTLYNE = "JUST FINISHED GLSRES"
         CALL SHOWIT(19)
         IF(BADGLS) THEN
            OUTLYNE = "BADGLS IS TRUE"
            CALL SHOWIT(19)
!     DO THE MESSAGE
            OUTLYNE='WARNING: CURRENT LENS HAS GLASS INPUT ERRORS'
            CALL SHOWIT(1)
            OUTLYNE= 'LENS PRESCRIPTION SHOULD BE CHECKED'
            CALL SHOWIT(1)
         END IF
!       NO CATALOG SEARCH IS REQUIRED
      END IF
!
!
!       NOW AT LENS INPUT LEVEL, THE LAST SURFACE ENTERED INCREMENTED THE
!       SURFACE COUNT. TO CORRECT THIS, ONLY AT F5=1, DECREASE THE SURFACE COUNT
!       BY 1.0 AND ONLY IF THERE ARE NO SOLVES OR THICKNESS
!     PIKUPS ON THIS LAST SURFACE
      IF(F5.EQ.1) THEN
!     IS THERE A THICKNESS SOLVE OR PIKUP ON SURF INT(SYSTEM(20))-1?
         IF(surf_pickup_count(INT(SYSTEM(20))-1).NE.0.0D0.OR.surf_solve_flag(INT(SYSTEM(20))-1).NE.0.0D0.OR.surf_thickness(INT(SYSTEM(20))).NE.0.0D0) THEN
!     HAS SOLVES OR PIKUPS OR THICKNESS ON I-1, DON'T REDUCE THE COUNT
         ELSE
!     NO SOLVES, PIKUPS OR THICKNESS ON I-1, DELETE THE SURFACE I
            SYSTEM(20)=SYSTEM(20)-1.0D0
         END IF
      END IF
!
      NEWIMG=SYSTEM(20)
      IF(SYSTEM(20).LT.0.0D0) SYSTEM(20)=0.0D0
      NEWIMG=SYSTEM(20)
      IF(F5.EQ.1.AND.SYSTEM(20).EQ.0.0D0) THEN
         OUTLYNE='LENS SYSTEM HAS NO SURFACES'
         CALL SHOWIT(1)
         OUTLYNE='RETURNED TO CMD LEVEL'
         CALL SHOWIT(1)
         F1=1
         F5=0
         F22=0
         SYSTEM(25)=0.0D0
         NEWREF=SYSTEM(25)
         OUTLYNE = "ABOUT TO CALL MACFAL "
         CALL SHOWIT(19)
         CALL MACFAL
         RETURN
      END IF
      IF(F6.EQ.1.AND.SYSTEM(20).EQ.0.0D0) THEN
         OUTLYNE='LENS SYSTEM HAS NO SURFACES'
         CALL SHOWIT(1)
         OUTLYNE='RETURNED TO CMD LEVEL'
         CALL SHOWIT(1)
         F1=1
         F6=0
         F22=0
         SYSTEM(25)=0.0D0
         NEWREF=SYSTEM(25)
         OUTLYNE = "ABOUT TO CALL MACFAL "
         CALL SHOWIT(19)
         CALL MACFAL
         RETURN
      END IF
!***************************************************************
!       ON MAY 11 1990 IT WAS DISCOVERED THAT IF THE RAYTRACE
!       TRACED INTO THE LAST SURFACE (NEWIMG). IF THE INDEX OF
!       NEWIMG WAS NOT = TO NEWIMG-1, THE DIRECTION COSINES WERE
!       CHANGED. THIS WAS FIXED INSIDE HITSUR.FOR AND THE
!       APPROPRIATE PARAXIAL TRACES. THE REFRACIVE INDEX
!       OF SURFACE NEWIMG IS NOW NOT USED IN ANY CALCULATION OF
!       PARAXIAL OR REAL RAY TRACING. FOR NEATNESS, THE NAME OF THE
!       GLASS TYPE OF SURFACE SYSTEM(20) IS SET TO "IMAGE SURFACE"
!       AND THE INDEX OF REFRACTION IS SET = TO SURFACE SYSTEM(20)-1
      call set_surf_refractive_index(INT(SYSTEM(20)), 1, surf_refractive_index(INT(SYSTEM(20))-1, 1))
      call set_surf_refractive_index(INT(SYSTEM(20)), 2, surf_refractive_index(INT(SYSTEM(20))-1, 2))
      call set_surf_refractive_index(INT(SYSTEM(20)), 3, surf_refractive_index(INT(SYSTEM(20))-1, 3))
      call set_surf_refractive_index(INT(SYSTEM(20)), 4, surf_refractive_index(INT(SYSTEM(20))-1, 4))
      call set_surf_refractive_index(INT(SYSTEM(20)), 5, surf_refractive_index(INT(SYSTEM(20))-1, 5))
      call set_surf_refractive_index(INT(SYSTEM(20)), 6, surf_refractive_index(INT(SYSTEM(20))-1, 6))
      call set_surf_refractive_index(INT(SYSTEM(20)), 7, surf_refractive_index(INT(SYSTEM(20))-1, 7))
      call set_surf_refractive_index(INT(SYSTEM(20)), 8, surf_refractive_index(INT(SYSTEM(20))-1, 8))
      call set_surf_refractive_index(INT(SYSTEM(20)), 9, surf_refractive_index(INT(SYSTEM(20))-1, 9))
      call set_surf_refractive_index(INT(SYSTEM(20)), 10, surf_refractive_index(INT(SYSTEM(20))-1, 10))
      GLANAM(INT(SYSTEM(20)),1)=' '
      GLANAM(INT(SYSTEM(20)),2)='LAST SURFACE'
   ELSE
!       LNSTYP NOT 1
   END IF
!
   IF(LNSTYP.EQ.1) THEN
!
!***************************************************************
!
!       DOES SAX GET THE VALUE OF SAY?
      IF(SYSTEM(49).NE.1.0D0.AND.SYSTEM(49).NE.3.0D0) THEN
!               YES IT DOES
         SYSTEM(13)=SYSTEM(12)
!               DON'T RESET SAX EQUAL TO SAY
      END IF
      IF(SYSTEM(13).EQ.0.0D0.AND.SYSTEM(12).NE.0.0D0) THEN
!               YES IT DOES
         SYSTEM(13)=SYSTEM(12)
!               DON'T RESET SAX EQUAL TO SAY
      END IF
!     NOW CALCULATE SAY AND SAX FROM NAO OR FNO IF NECESSARY
!
      IF(SYSTEM(64).EQ.1.0D0) THEN
         IF(INT(SYSTEM(11)).GE.1.AND.INT(SYSTEM(11)).LE.5) THEN
            YTERM=(SYSTEM(65))/(ALENS(45+INT(SYSTEM(11)),0))
         END IF
         IF(INT(SYSTEM(11)).GE.6.AND.INT(SYSTEM(11)).LE.10) THEN
            YTERM=(SYSTEM(65))/(ALENS(65+INT(SYSTEM(11)),0))
         END IF
         IF(DABS(YTERM).GT.1.0D0) THEN
            OUTLYNE='NEW "NAOY" VALUE WAS NOT REALISTIC'
            CALL SHOWIT(1)
            OUTLYNE= '"NAOY" SETTING TURNED OFF'
            CALL SHOWIT(1)
            YTERM=1.0D0
            SYSTEM(12)=surf_thickness(0)*DTAN(DASIN(YTERM))
            SYSTEM(64)=0.0D0
         ELSE
            SYSTEM(12)=surf_thickness(0)*DTAN(DASIN(YTERM))
         END IF
      END IF
      IF(SYSTEM(64).EQ.2.0D0) THEN
         IF(INT(SYSTEM(11)).GE.1.AND.INT(SYSTEM(11)).LE.5) THEN
            XTERM=(SYSTEM(66))/(ALENS(45+INT(SYSTEM(11)),0))
         END IF
         IF(INT(SYSTEM(11)).GE.6.AND.INT(SYSTEM(11)).LE.10) THEN
            XTERM=(SYSTEM(66))/(ALENS(65+INT(SYSTEM(11)),0))
         END IF
         IF(DABS(XTERM).GT.1.0D0) THEN
            OUTLYNE='NEW "NAOX" VALUE WAS NOT REALISTIC'
            CALL SHOWIT(1)
            OUTLYNE= '"NAOX" SETTING TURNED OFF'
            CALL SHOWIT(1)
            XTERM=1.0D0
            SYSTEM(13)=surf_thickness(0)*DTAN(DASIN(XTERM))
            SYSTEM(64)=0.0D0
         ELSE
            SYSTEM(13)=surf_thickness(0)*DTAN(DASIN(XTERM))
         END IF
      END IF
      IF(SYSTEM(64).EQ.3.0D0) THEN
         IF(INT(SYSTEM(11)).GE.1.AND.INT(SYSTEM(11)).LE.5) THEN
            YTERM=(SYSTEM(65))/(ALENS(45+INT(SYSTEM(11)),0))
            XTERM=(SYSTEM(66))/(ALENS(45+INT(SYSTEM(11)),0))
         END IF
         IF(INT(SYSTEM(11)).GE.6.AND.INT(SYSTEM(11)).LE.10) THEN
            YTERM=(SYSTEM(65))/(ALENS(65+INT(SYSTEM(11)),0))
            XTERM=(SYSTEM(66))/(ALENS(65+INT(SYSTEM(11)),0))
         END IF
         IF(DABS(YTERM).GT.1.0D0) THEN
            OUTLYNE='NEW "NAOY" VALUE WAS NOT REALISTIC'
            CALL SHOWIT(1)
            OUTLYNE= '"NAOY" SETTING TURNED OFF'
            CALL SHOWIT(1)
            YTERM=1.0D0
            SYSTEM(12)=surf_thickness(0)*DTAN(DASIN(YTERM))
            SYSTEM(64)=0.0D0
         ELSE
            SYSTEM(12)=surf_thickness(0)*DTAN(DASIN(YTERM))
         END IF
         IF(DABS(XTERM).GT.1.0D0) THEN
            OUTLYNE='NEW "NAOX" VALUE WAS NOT REALISTIC'
            CALL SHOWIT(1)
            OUTLYNE= '"NAOX" SETTING TURNED OFF'
            CALL SHOWIT(1)
            XTERM=1.0D0
            SYSTEM(13)=surf_thickness(0)*DTAN(DASIN(XTERM))
            SYSTEM(64)=0.0D0
         ELSE
            SYSTEM(13)=surf_thickness(0)*DTAN(DASIN(XTERM))
         END IF
      END IF

      IF(SYSTEM(67).EQ.1.0D0) THEN
         SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
      END IF
      IF(SYSTEM(67).EQ.2.0D0) THEN
         SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
      END IF
      IF(SYSTEM(67).EQ.3.0D0) THEN
         SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
         SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
      END IF
!
      IF(SYSTEM(49).NE.2.0D0.AND.SYSTEM(49).NE.3.0D0) THEN
!     SCX NOT ENTERED EXPLICITLY
         IF(SYSTEM(18).EQ.1.0D0) SYSTEM(19)=1.0D0
         IF(SYSTEM(18).EQ.0.0D0) SYSTEM(19)=0.0D0
!       NO FIX IS NECESARRY
      END IF
!
      IF(DABS(surf_thickness(NEWOBJ)).GE.1.0D10.AND.SYSTEM(60).EQ.0.0D0 .AND.SYSTEM(61).EQ.0.0D0) THEN
!     OBJECT AT INFINITY, NO SCY (FANG) OR SCX (FANG) COMMANDS ISSED
!     SET SCY FANG AND SCX FANG TO 1.0 DEGREES
         SYSTEM(14)=0.0D0
         SYSTEM(15)=0.0D0
         SYSTEM(16)=0.0D0
         SYSTEM(17)=0.0D0
         SYSTEM(21)=1.0D0
         SYSTEM(22)=0.0D0
         SYSTEM(23)=1.0D0
         SYSTEM(24)=0.0D0
         SYSTEM(18)=1.0D0
         SYSTEM(19)=1.0D0
         SYSTEM(51)=0.0D0
         SYSTEM(52)=0.0D0
         SYSTEM(53)=1.0D0
         SYSTEM(54)=1.0D0
      END IF
      IF(DABS(surf_thickness(NEWOBJ)).LT.1.0D10.AND.SYSTEM(60).EQ.0.0D0 .AND.SYSTEM(61).EQ.0.0D0) THEN
!     OBJECT NEAR, NO SCY (FANG) OR SCX (FANG) COMMANDS ISSED
!     SET SCY AND SCX TO 1.0 LENS UNIT
         SYSTEM(14)=1.0D0
         SYSTEM(15)=0.0D0
         SYSTEM(16)=1.0D0
         SYSTEM(17)=0.0D0
         SYSTEM(21)=0.0D0
         SYSTEM(22)=0.0D0
         SYSTEM(23)=0.0D0
         SYSTEM(24)=0.0D0
         SYSTEM(18)=0.0D0
         SYSTEM(19)=0.0D0
         SYSTEM(51)=1.0D0
         SYSTEM(52)=1.0D0
         SYSTEM(53)=0.0D0
         SYSTEM(54)=0.0D0
      END IF
!
      IF(SYSTEM(18).EQ.0.0D0) THEN
!       CALCULATE SCY FANG FROM SCY BUT SINCE THE DENOMINATOR IN
!       THE CALCULATION IS THE OBJECT THICKNESS, IF IT IS ZERO,
!       SKIP THE CALCULATION AND SET SCY FANG TO 1.0. PRINT
!       A WARNING MESSAGE AS WELL.
!
         I=0
         IF(surf_thickness(0).EQ.0.0D0) THEN
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            OUTLYNE=' OBJECT THICKNESS ZERO. SCY FANG SET TO 1.0'
            CALL SHOWIT(1)
            OUTLYNE=' OBJECT THICKNESS RESET TO 1.0D20'
            CALL SHOWIT(1)
            SYSTEM(21)=1.0D0
            call set_surf_thickness(0, 1.0D20)
         ELSE
!     OBJECT THICKNESS NOT ZERO
!       PROCEED WITH SCY FANG CALCULATION
!
            IF(SYSTEM(26).NE.-99.0D0) THEN
               IF(DABS(SYSTEM(14)).LE.1.0D-15.AND.DABS(surf_thickness(0)).LE.1.0D-15) THEN
                  JK_TEMP=0.0D0
               ELSE
                  JK_TEMP=DATAN2(SYSTEM(14),surf_thickness(0))
               END IF
               SYSTEM(21)=JK_TEMP

               IF(surf_thickness(0).GT.0.0D0) THEN
                  IF(SYSTEM(14).GT.0.0D0) SYSTEM(21)=-DABS(SYSTEM(21))
                  IF(SYSTEM(14).LT.0.0D0) SYSTEM(21)=DABS(SYSTEM(21))
                  IF(SYSTEM(14).EQ.0.0D0) SYSTEM(21)=0.0D0
               END IF
               IF(surf_thickness(0).LT.0.0D0) THEN
                  IF(SYSTEM(14).GT.0.0D0) SYSTEM(21)=DABS(SYSTEM(21))
                  IF(SYSTEM(14).LT.0.0D0) SYSTEM(21)=-DABS(SYSTEM(21))
                  IF(SYSTEM(14).EQ.0.0D0) SYSTEM(21)=0.0D0
               END IF
            END IF
!
            IF(SYSTEM(26).EQ.-99.0D0) THEN
               IF(DABS(SYSTEM(14)-SYSTEM(15)).LE.1.0D-15.AND.DABS(surf_thickness(0)).LE.1.0D-15) THEN
                  JK_TEMP=0.0D0
               ELSE
                  JK_TEMP=DATAN2((SYSTEM(14)-SYSTEM(15)),surf_thickness(0))
               END IF
               SYSTEM(21)=JK_TEMP
               IF(surf_thickness(0).GT.0.0D0) THEN
                  IF((SYSTEM(14)-SYSTEM(15)).GT.0.0D0) SYSTEM(21)=-DABS(SYSTEM(21))
                  IF((SYSTEM(14)-SYSTEM(15)).LT.0.0D0) SYSTEM(21)=DABS(SYSTEM(21))
                  IF((SYSTEM(14)-SYSTEM(15)).EQ.0.0D0) SYSTEM(21)=0.0D0
               END IF
               IF(surf_thickness(0).LT.0.0D0) THEN
                  IF((SYSTEM(14)-SYSTEM(15)).GT.0.0D0) SYSTEM(21)=DABS(SYSTEM(21))
                  IF((SYSTEM(14)-SYSTEM(15)).LT.0.0D0) SYSTEM(21)=-DABS(SYSTEM(21))
                  IF((SYSTEM(14)-SYSTEM(15)).EQ.0.0D0) SYSTEM(21)=0.0D0
               END IF
            END IF
! SYSTEM(18)=0 AND OBJECT THICKNESS NOT ZERO
            SYSTEM(21)=(180.0D0/PII)*SYSTEM(21)
!     END OF LOOP FOR OBJECT THICKNESS TEST
         END IF
      ELSE
!       SYSTEM(18) NOT EQUAL TO 0.0
      END IF
!C
      IF(SYSTEM(19).EQ.0.0D0) THEN
!       CALCULATE SCX FANG FROM SCX BUT SINCE THE DENOMINATOR IN
!       THE CALCULATION IS THE OBJECT THICKNESS, IF IT IS ZERO,
!       SKIP THE CALCULATION AND SET SCX FANG TO 1.0. PRINT
!       A WARNING MESSAGE AS WELL.
!
!       SHOULD SCX EQUAL SCY?
         IF(SYSTEM(49).NE.2.0D0.AND.SYSTEM(49).NE.3.0D0) THEN
!       YES IT SHOULD
            SYSTEM(16)=SYSTEM(14)
            SYSTEM(17)=SYSTEM(15)
!       NO, DON'T SET SCX = SCY
         END IF
!
         I=0
         IF(surf_thickness(0).EQ.0.0D0) THEN
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            OUTLYNE=' OBJECT THICKNESS ZERO. SCX FANG SET TO 1.0'
            CALL SHOWIT(1)
            OUTLYNE=' OBJECT THICKNESS RESET TO 1.0D20'
            CALL SHOWIT(1)
            SYSTEM(23)=1.0D0
            call set_surf_thickness(0, 1.0D20)
         ELSE
!       PROCEED WITH SCX FANG CALCULATION
!
            IF(SYSTEM(26).NE.-99.0D0)THEN
               IF(DABS(SYSTEM(16)).LE.1.0D-15.AND.DABS(surf_thickness(0)).LE.1.0D-15) THEN
                  JK_TEMP=0.0D0
               ELSE
                  JK_TEMP=DATAN2(SYSTEM(16),surf_thickness(0))
               END IF
               SYSTEM(23)=JK_TEMP
               IF(surf_thickness(0).GT.0.0D0) THEN
                  IF(SYSTEM(16).GT.0.0D0) SYSTEM(23)=-DABS(SYSTEM(23))
                  IF(SYSTEM(16).LT.0.0D0) SYSTEM(23)=DABS(SYSTEM(23))
                  IF(SYSTEM(16).EQ.0.0D0) SYSTEM(23)=0.0D0
               END IF
               IF(surf_thickness(0).LT.0.0D0) THEN
                  IF(SYSTEM(16).GT.0.0D0) SYSTEM(23)=DABS(SYSTEM(23))
                  IF(SYSTEM(16).LT.0.0D0) SYSTEM(23)=-DABS(SYSTEM(23))
                  IF(SYSTEM(16).EQ.0.0D0) SYSTEM(23)=0.0D0
               END IF
            END IF
            IF(SYSTEM(26).EQ.-99.0D0)THEN
               IF(DABS(SYSTEM(16)-SYSTEM(17)).LE.1.0D-15.AND.DABS(surf_thickness(0)).LE.1.0D-15) THEN
                  JK_TEMP=0.0D0
               ELSE
                  JK_TEMP=DATAN2((SYSTEM(16)-SYSTEM(17)),surf_thickness(0))
               END IF
               SYSTEM(23)=JK_TEMP
               IF(surf_thickness(0).GT.0.0D0) THEN
                  IF((SYSTEM(16)-SYSTEM(17)).GT.0.0D0) SYSTEM(23)=-DABS(SYSTEM(23))
                  IF((SYSTEM(16)-SYSTEM(17)).LT.0.0D0) SYSTEM(23)=DABS(SYSTEM(23))
                  IF((SYSTEM(16)-SYSTEM(17)).EQ.0.0D0) SYSTEM(23)=0.0D0
               END IF
               IF(surf_thickness(0).LT.0.0D0) THEN
                  IF((SYSTEM(16)-SYSTEM(17)).GT.0.0D0) SYSTEM(23)=DABS(SYSTEM(23))
                  IF((SYSTEM(16)-SYSTEM(17)).LT.0.0D0) SYSTEM(23)=-DABS(SYSTEM(23))
                  IF((SYSTEM(16)-SYSTEM(17)).EQ.0.0D0) SYSTEM(23)=0.0D0
               END IF
            END IF
            SYSTEM(23)=(180.0D0/PII)*SYSTEM(23)
         END IF
      ELSE
!       SYSTEM(19) NOT EQUAL TO 0.0
      END IF
!
      IF(SYSTEM(18).EQ.1.0D0) THEN
!
!*****************************************************************
!
!       CALCULATE SCY FROM SCY FANG IF REQUIRED
!
         I=0
         SYSTEM(14)=-surf_thickness(0)*DTAN((PII/180.0D0)*SYSTEM(21))
         IF(SYSTEM(26).EQ.-99.0D0) SYSTEM(14)=SYSTEM(14)+SYSTEM(15)
      END IF
!
!******************************************************************
!
      IF(SYSTEM(19).EQ.1.0D0) THEN
!
!       CALCULATE SCX FROM SCX FANG IF REQUIRED
!
!       SHOULD SCX FANG EQUAL SCY FANG?
         IF(SYSTEM(49).NE.2.0D0.AND.SYSTEM(49).NE.3.0D0) THEN
!       YES IT SHOULD
            SYSTEM(23)=SYSTEM(21)
            SYSTEM(24)=SYSTEM(22)
!       NO, DON'T SET SCX FANG = SCY FANG
         END IF

         I=0
         SYSTEM(16)=-surf_thickness(0)*DTAN((PII/180.0D0)*SYSTEM(23))
         IF(SYSTEM(26).EQ.-99.0D0) SYSTEM(16)=SYSTEM(16)+SYSTEM(17)
      END IF
   ELSE
!     LNSTYP NOT 1
   END IF
!
!
!       SET FLAGS FOR A RETURN TO CMD LEVEL
!
   IF(F5.EQ.1) THEN
      TFSURF=INT(SYSTEM(20))
      TFTMIN=-0.005D0
      TFTMAX=0.005D0
      TFDELT=0.001D0
      TFDIRECTION= 2
   END IF

   IF(F5.EQ.1) F5=0
   IF(F6.EQ.1) F6=0
   F1=1
   F22=0
!       NOW FLAGS ARE SET TO CMD LEVEL
!
   IF(LNSTYP.EQ.1) THEN
!
!
!********************************************************************
!********************************************************************
!
!       CHECK THAT THERE ARE NO SOLVE RECORDS WHICH OCCUR BEFORE THE
!       APERTURE STOP SURFACE. SOLVES INFRONT OF THE APERTURE
!       STOP SURFACE ARE NOT ALLOWED. THE ASTOP SURFACE IS THE
!       SURFACE FOR WHICH PARAXIAL CHIEF RAYS ARE AIMED. IN THE
!       ABSENCE OF AN APERTURE STOP DEFINITION, SURFACE
!       1 IS THE AIMING SURFACE AND NO SOLVES MAY COME BEFORE SURFACE
!       1.
!**********************************************************************
!
      SLVMRK=INT(SYSTEM(26))-1
!       IF NO ASTOP DEFINED, SLVMRK WILL BE LESS THAN ZERO
!       SET IT TO 1
      IF(SLVMRK.LT.0) SLVMRK=1
      DO 56 I=0,SLVMRK-1
!       ARE THERE SOLVES?
!
         IF(surf_solve_flag(I).NE.0.0D0) THEN
!       FOUND A SOLVE INFRONT OF THE ASTOP SURFACE, REMOVE IT
!       AND PRINT MESSAGE IN SOME CASES
!     NO CHIEF RAY SOLVES IN FRONT OF STOP INCLUDING APY AND APX SOLVES
!     THEN RESOLVE THE VALUE OF surf_solve_flag(I)

!     CHIEF RAY SOLVES OF ANY TYPE ARE NOT ALLOWED IN FRONT OF THE STOP
            IF(SOLVE(6,I).EQ.2.0D0) THEN
               WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PCY-SOLVE DELETED'
               CALL SHOWIT(1)
               SOLVE(6,I)=0.0D0
            END IF
            IF(SOLVE(4,I).EQ.5.0D0) THEN
               WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PCX-SOLVE DELETED'
               CALL SHOWIT(1)
               SOLVE(4,I)=0.0D0
            END IF
            IF(SOLVE(8,I).EQ.4.0D0) THEN
               WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - APCY-SOLVE DELETED'
               CALL SHOWIT(1)
               SOLVE(8,I)=0.0D0
            END IF
            IF(SOLVE(2,I).EQ.11.0D0) THEN
               WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - APCX-SOLVE DELETED'
               CALL SHOWIT(1)
               SOLVE(2,I)=0.0D0
            END IF
            IF(SOLVE(8,I).EQ.5.0D0) THEN
               WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PICY-SOLVE DELETED'
               CALL SHOWIT(1)
               SOLVE(8,I)=0.0D0
            END IF
            IF(SOLVE(2,I).EQ.12.0D0) THEN
               WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PICX-SOLVE DELETED'
               CALL SHOWIT(1)
               SOLVE(2,I)=0.0D0
            END IF
            IF(SOLVE(8,I).EQ.6.0D0) THEN
               WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PUCY-SOLVE DELETED'
               CALL SHOWIT(1)
               SOLVE(8,I)=0.0D0
            END IF
            IF(SOLVE(2,I).EQ.13.0D0) THEN
               WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PUCX-SOLVE DELETED'
               CALL SHOWIT(1)
               SOLVE(2,I)=0.0D0
            END IF
!     IF SAY FLOAT IS IN OPERATION, NO MARGINAL RAY SOLVES ARE ALLOWED
!     IN FRONT OF THE STOP
            IF(SYSTEM(83).EQ.1.0D0) THEN
!     SAY FLOAT IN EFFECT
               IF(SOLVE(6,I).EQ.1.0D0) THEN
                  WRITE(OUTLYNE,*)'SAY FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PY-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(6,I)=0.0D0
               END IF
               IF(SOLVE(6,I).EQ.3.0D0) THEN
                  WRITE(OUTLYNE,*)'SAY FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SAY FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - CAY-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(6,I)=0.0D0
               END IF
               IF(SOLVE(8,I).EQ.1.0D0) THEN
                  WRITE(OUTLYNE,*)'SAY FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - APY-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(8,I)=0.0D0
               END IF
               IF(SOLVE(8,I).EQ.2.0D0) THEN
                  WRITE(OUTLYNE,*)'SAY FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PIY-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(8,I)=0.0D0
               END IF
               IF(SOLVE(8,I).EQ.3.0D0) THEN
                  WRITE(OUTLYNE,*)'SAY FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PUY-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(8,I)=0.0D0
               END IF
               IF(SOLVE(8,I).EQ.7.0D0) THEN
                  WRITE(OUTLYNE,*)'SAY FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - COCY-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(8,I)=0.0D0
               END IF
            ELSE
!     NOT SAY FLOAT
            END IF
!     IF SAX FLOAT IS IN OPERATION, NO MARGINAL RAY SOLVES ARE ALLOWED
!     IN FRONT OF THE STOP
            IF(SYSTEM(84).EQ.1.0D0) THEN
!     SAX FLOAT IN EFFECT
               IF(SOLVE(4,I).EQ.4.0D0) THEN
                  WRITE(OUTLYNE,*)'SAX FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PX-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(4,I)=0.0D0
               END IF
               IF(SOLVE(4,I).EQ.6.0D0) THEN
                  WRITE(OUTLYNE,*)'SAX FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - CAX-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(6,I)=0.0D0
               END IF
               IF(SOLVE(2,I).EQ.8.0D0) THEN
                  WRITE(OUTLYNE,*)'SAX FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - APX-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(2,I)=0.0D0
               END IF
               IF(SOLVE(2,I).EQ.9.0D0) THEN
                  WRITE(OUTLYNE,*)'SAX FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PIX-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(2,I)=0.0D0
               END IF
               IF(SOLVE(2,I).EQ.10.0D0) THEN
                  WRITE(OUTLYNE,*)'SAX FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - PUX-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(2,I)=0.0D0
               END IF
               IF(SOLVE(2,I).EQ.14.0D0) THEN
                  WRITE(OUTLYNE,*)'SAX FLOAT IS IN EFFECT'
                  CALL SHOWIT(1)
                  WRITE(OUTLYNE,*)'SURFACE',SURF,' :SURFACE PRECEEDS ASTOP SURFACE - COCX-SOLVE DELETED'
                  CALL SHOWIT(1)
                  SOLVE(2,I)=0.0D0
               END IF
            ELSE
!     NOT SAX FLOAT
            END IF
!       CALCULATE THE CORRECT VALUE OF surf_solve_flag(SURF)
!
            call set_surf_solve_flag(SURF, 0.0D0)
            IF(SOLVE(6,SURF).GT.0.0D0) call set_surf_solve_flag(SURF, surf_solve_flag(SURF)+1.0D0)
            IF(SOLVE(4,SURF).GT.0.0D0) call set_surf_solve_flag(SURF, surf_solve_flag(SURF)+0.1D0)
            IF(SOLVE(8,SURF).GT.0.0D0) call set_surf_solve_flag(SURF, surf_solve_flag(SURF)+2.0D0)
            IF(SOLVE(2,SURF).GT.0.0D0) call set_surf_solve_flag(SURF, surf_solve_flag(SURF)+0.2D0)
!
            IF(surf_solve_flag(I).EQ.0.0D0) THEN
               WRITE(OUTLYNE,*)'SURFACE',SURF,'NO SOLVES REMAIN ON SURFACE'
               CALL SHOWIT(1)
               call set_surf_solve_flag(I, 0.0D0)
!       TESTED SURFACE DOES NOT HAVE SOLVE, PROCEED
            END IF
         END IF
56    CONTINUE
!
!       SOLVE/ASTOP INCONSISTENCIES REMOVED
!
!
!********************************************************************
!     THIS WAS MOVED HERE AFTER PIKUPS TO MAKE REFL WORK WITH
!     PIKUP GLASS
!
!       THE NEXT ITEM TO REQUIRE RESOLUTION IS THE PSUDO-PIKUP
!       OF THE REFRACTIVE INDICES FOR REFLECTIVE SURFACES.
!       A REFLECTIVE SURFACE ALWAYS REFLECTS BACK INTO THE
!       MEDIA IT IS EMERSED IN AND THUS IF SURFACE I+1
!       IS DEFINED AS "REFL" THEN ITS REFRACTIVE INDICES
!       WILL ALWAYS BE EQUAL IN MAGNITUDE BUT OPPOSITE IN
!       ALGEBRAIC SIGN TO THE REFRACTIVE INDICES OF SUFACE
!       I. AT THIS POINT THE LENS IS SEARCHED FROM SURFACE 0
!       TO THE (IMAGE SURFACE NUMBER )
!       (SURFACE NUMBER = INT(SYSTEM(20))-1).
!       IF A SURFACE IS FOUND TO HAVE A GLANAM(SURF,1)='REFL'
!       THEN FOR THAT SURFACE THE INDICES STORED IN
!       surf_refractive_index(SURF, 1) THROUGH surf_refractive_index(SURF, 5) ARE SET EQUAL TO BUT
!     (AND 71 TO 75 FOR WAVELENGTHS 6 TO 10)
!       OPPOSITE IN SIGN TO THE CORRESPONDING VALUES ON SURFACE
!       (SURF-1). THEN A RETURN TO THE CMD LEVEL IS PERFORMED.
!       RESOLUTION OF REFRACTIVE INDICES IN PRESENTS OF
!       REFLECTIONS

!       ON 8/8/89 IT WAS DISCOVERED THAT IF A SYSTEM HAD
!       ORIGINALLY HAD REFLECTIVE SURFACES AND SOME OR ALL WERE
!       CHANGED TO NONE REFLECTIVE, THE NEGATIVE INDICES
!       AFTER THAT REFLECTIVE SURFACE WERE NOT CORRECTLY MADE
!       POSITIVE. BY RE-SETTING ALL INDICES POSITIVE, THE SUBROUTINE
!       LNSEOS COULD THEN GIVE THE CORRECT SIGNS TO ALL REFRACTIVE
!       INDICES.
      K=INT(SYSTEM(20))
      ALENS(46:50,1:K)=DABS(ALENS(46:50,1:K))
      ALENS(71:75,1:K)=DABS(ALENS(71:75,1:K))
!
      F21=0
      DO 10 I=1,INT(SYSTEM(20))
         IF(GLANAM(I,2).EQ.'REFL'.OR.GLANAM(I,2).EQ.'REFLTIRO') THEN
            IF(F21.EQ.1.OR.F21.EQ.0) THEN
               F21=-1
               ALENS(46:50,I)=ALENS(46:50,(I-1))
               ALENS(71:75,I)=ALENS(71:75,(I-1))
            ELSE
               IF(F21.EQ.-1)THEN
                  F21=1
                  ALENS(46:50,I)=ALENS(46:50,(I-1))
                  ALENS(71:75,I)=ALENS(71:75,(I-1))
               END IF
            END IF
         END IF
         IF(F21.EQ.0) GO TO 10
         IF(F21.EQ.-1) THEN
            IF(surf_refractive_index(I, 1).GT.0.0D0) call set_surf_refractive_index(I, 1, -surf_refractive_index(I, 1))
            IF(surf_refractive_index(I, 2).GT.0.0D0) call set_surf_refractive_index(I, 2, -surf_refractive_index(I, 2))
            IF(surf_refractive_index(I, 3).GT.0.0D0) call set_surf_refractive_index(I, 3, -surf_refractive_index(I, 3))
            IF(surf_refractive_index(I, 4).GT.0.0D0) call set_surf_refractive_index(I, 4, -surf_refractive_index(I, 4))
            IF(surf_refractive_index(I, 5).GT.0.0D0) call set_surf_refractive_index(I, 5, -surf_refractive_index(I, 5))
            IF(surf_refractive_index(I, 6).GT.0.0D0) call set_surf_refractive_index(I, 6, -surf_refractive_index(I, 6))
            IF(surf_refractive_index(I, 7).GT.0.0D0) call set_surf_refractive_index(I, 7, -surf_refractive_index(I, 7))
            IF(surf_refractive_index(I, 8).GT.0.0D0) call set_surf_refractive_index(I, 8, -surf_refractive_index(I, 8))
            IF(surf_refractive_index(I, 9).GT.0.0D0) call set_surf_refractive_index(I, 9, -surf_refractive_index(I, 9))
            IF(surf_refractive_index(I, 10).GT.0.0D0) call set_surf_refractive_index(I, 10, -surf_refractive_index(I, 10))
         END IF
         IF(F21.EQ.1) THEN
            IF(surf_refractive_index(I, 1).LT.0.0D0) call set_surf_refractive_index(I, 1, DABS(surf_refractive_index(I, 1)))
            IF(surf_refractive_index(I, 2).LT.0.0D0) call set_surf_refractive_index(I, 2, DABS(surf_refractive_index(I, 2)))
            IF(surf_refractive_index(I, 3).LT.0.0D0) call set_surf_refractive_index(I, 3, DABS(surf_refractive_index(I, 3)))
            IF(surf_refractive_index(I, 4).LT.0.0D0) call set_surf_refractive_index(I, 4, DABS(surf_refractive_index(I, 4)))
            IF(surf_refractive_index(I, 5).LT.0.0D0) call set_surf_refractive_index(I, 5, DABS(surf_refractive_index(I, 5)))
            IF(surf_refractive_index(I, 6).LT.0.0D0) call set_surf_refractive_index(I, 6, DABS(surf_refractive_index(I, 6)))
            IF(surf_refractive_index(I, 7).LT.0.0D0) call set_surf_refractive_index(I, 7, DABS(surf_refractive_index(I, 7)))
            IF(surf_refractive_index(I, 8).LT.0.0D0) call set_surf_refractive_index(I, 8, DABS(surf_refractive_index(I, 8)))
            IF(surf_refractive_index(I, 9).LT.0.0D0) call set_surf_refractive_index(I, 9, DABS(surf_refractive_index(I, 9)))
            IF(surf_refractive_index(I, 10).LT.0.0D0) call set_surf_refractive_index(I, 10, DABS(surf_refractive_index(I, 10)))
         END IF
10    CONTINUE
!
!********************************************************************
!
!       NOW CHECK FOR THE PRESENCE OF COCY OR COCX SOLVES WHICH
!       REFERENCE A SURFACE NUMBER LARGER (FARTHER DOWN THE LENS)
!       THAN ITS OWN NUMBER. IF FOUND, CHECK THAT THERE ARE NO INTERVINING
!       PAXAXIAL THICKNESS SOLVES. IF ANY ARE FOUND, REMOVE THE
!       COCY OF COCX SOLVE AND PRINT A WARNING MESSAGE.
!
      DO 803 I=1,INT(SYSTEM(20))
         IF(SOLVE(8,I).EQ.7.0D0.OR.SOLVE(2,I).EQ.14.0D0) THEN
!       FOUND A COCY OR COCX SOLVE
!       DOES IT REFER TO A FOLLOWING SURFACE?
            IF(SOLVE(9,I).GT.I.OR.SOLVE(1,I).GT.I) THEN
!       YES IT DOES,PROCEED WITH PROCESSING
!       ARE THERE THICKNESS SOLVES BETWEEN THE COCY/COCX SOLVE
!       AND THE REFERENCED SURFACE?
               ITT=I
               IF(SOLVE(8,I).EQ.7.0D0) IFF=INT(SOLVE(9,I))-1.0D0
               IF(SOLVE(2,I).EQ.14.0D0) IFF=INT(SOLVE(1,I))-1.0D0
               TESTIT=0
               DO 804 J=ITT,IFF
                  IF(SOLVE(6,J).NE.0.0D0.OR.SOLVE(4,J).NE.0.0D0) THEN
                     TESTIT=TESTIT+1
!       NO THICKNESS SOLVE FOUND,CONTINUE
                  END IF
804            CONTINUE
!       IF TESTIT NOT ZERO, THEN THERE WAS AN INTERVINING
!       THICKNESS SOLVE. IN THIS CASE THE COCY OR COCX SOLVE MUST GO.
               IF(TESTIT.NE.0) THEN
!       REMOVE THE SOLVE AND PRINT AN ERROR MESSAGE
                  IF(SOLVE(8,I).EQ.7.0D0) THEN
                     OUTLYNE='(COCY) SOLVE CONFLICTS WITH A FOLLOWING THICKNESS SOLVE'
                     CALL SHOWIT(1)
                     OUTLYNE='(COCY) SOLVE DELETED'
                     CALL SHOWIT(1)
                     SOLVE(8,I)=0.0D0
                     SOLVE(9,I)=0.0D0
                     call set_surf_solve_flag(I, surf_solve_flag(I)-2.0D0)
!       NOT A COCY SOLVE,PROCEED
                  END IF
                  IF(SOLVE(2,I).EQ.14.0D0) THEN
                     OUTLYNE='(COCX) SOLVE CONFLICTS WITH A FOLLOWING THICKNESS SOLVE'
                     CALL SHOWIT(1)
                     OUTLYNE='(COCX) SOLVE DELETED'
                     CALL SHOWIT(1)
                     SOLVE(2,I)=0.0D0
                     SOLVE(1,I)=0.0D0
                     call set_surf_solve_flag(I, surf_solve_flag(I)-2.0D0)
!       NOT A COCX SOLVE,PROCEED
                  END IF
!       TESTIT IS ZERO, NO SOLVE TO REMOVE, PROCEED
               END IF
!       NO TO DOES NOT,CONTINUE
            END IF
!       NO COCY OR COCX SOLVE FOUND, CONTINUE
         END IF
803   CONTINUE
   ELSE
!     NOT LNSTYP=1
   END IF
!
!       NOW CHECK FOR FNBY AND FNBX HOLDS AND CHECK THE MODE.
!       IF NOT FOCAL OR UFOCAL, PRINT MESSAGE THAT HOLD WAS IGNORED.
!       CHECK FOR FNBY OR FNBX HOLD
   IF(SYSTEM(44).EQ.-1.0D0.AND.SYSTEM(83).EQ.0.0D0.AND.SYSTEM(84).EQ.0.0D0) THEN
!               THERE IS AN F NUMBER HOLD (YZ PLANE)
!       CHECK LENS MODE, MUST BE FOCAL OR UFOCAL
      IF(SYSTEM(30).EQ.1.0D0.OR.SYSTEM(30).EQ.2.0D0) THEN
!       HOLD PERFORMED. FIRST PERFORM A PARAXIAL TRACE TO
!       GET STARTING VARLUES
         ITYPEP=1
!       TELECENTRIC STUFF, 11/12/2000
         IF(SYSTEM(63).EQ.1.0D0) THEN
            IF(SYSTEM(64).EQ.0.0D0.AND.SYSTEM(67).EQ.0.0D0) THEN
               OUTLYNE='WHEN "TEL ON" IS SET, NAO OR FNO MUST BE USED'
               CALL SHOWIT(1)
               OUTLYNE='TO SPECIFY THE MARGINAL PARAXIAL RAY STARTING'
               CALL SHOWIT(1)
               OUTLYNE='VALUES'
               CALL SHOWIT(1)
               OUTLYNE='PARAXIAL TRACE STOPPED'
               CALL SHOWIT(1)
               CALL MACFAL
               RETURN
            ELSE
               IF(SYSTEM(64).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
               END IF
               IF(SYSTEM(64).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(64).EQ.2.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(67).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
               END IF
               IF(SYSTEM(67).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
               IF(SYSTEM(67).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
            END IF
         END IF
!
         OUTLYNE = "ABOUT TO CALL PRTRA "
         CALL SHOWIT(19)
         CALL PRTRA
         OUTLYNE = "JUST FINISHED PRTRA"
         CALL SHOWIT(19)
         ITYPEP=1
         CALL FADJ
      ELSE
         IF(LNSTYP.EQ.1) THEN
!       MODE NOT CORRECT
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            OUTLYNE='AN "FNBY HLD" IS IN EFFECT.'
            CALL SHOWIT(1)
            OUTLYNE='"FNBY HLD" REQUIRES THE FOCAL OR UFOCAL MODES.'
            CALL SHOWIT(1)
            IF(SYSTEM(30).EQ.3.0D0) THEN
               OUTLYNE='CURRENT MODE IS AFOCAL.'
               CALL SHOWIT(1)
            END IF
            IF(SYSTEM(30).EQ.4.0D0) THEN
               OUTLYNE='CURRENT MODE IS UAFOCAL'
               CALL SHOWIT(1)
            END IF
            OUTLYNE='"FNBY HLD" NOT PERFORMED.'
            CALL SHOWIT(1)
         END IF
      END IF
!       NO FNBY HLD IN EFFECT
   END IF
   IF(SYSTEM(45).EQ.-1.0D0.AND.SYSTEM(83).EQ.0.0D0.AND.SYSTEM(84).EQ.0.0D0) THEN
!               THERE IS AN F NUMBER HOLD (XZ PLANE)
!       CHECK LENS MODE, MUST BE FOCAL OR UFOCAL
      IF(SYSTEM(30).EQ.1.0D0.OR.SYSTEM(30).EQ.2.0D0) THEN
!       HOLD PERFORMED. FIRST PERFORM A PARAXIAL TRACE TO
!       GET STARTING VALUES.
         ITYPEP=3
!       TELECENTRIC STUFF, 11/12/2000
         IF(SYSTEM(63).EQ.1.0D0) THEN
            IF(SYSTEM(64).EQ.0.0D0.AND.SYSTEM(67).EQ.0.0D0) THEN
               OUTLYNE='WHEN "TEL ON" IS SET, NAO OR FNO MUST BE USED'
               CALL SHOWIT(1)
               OUTLYNE='TO SPECIFY THE MARGINAL PARAXIAL RAY STARTING'
               CALL SHOWIT(1)
               OUTLYNE='VALUES'
               CALL SHOWIT(1)
               OUTLYNE='PARAXIAL TRACE STOPPED'
               CALL SHOWIT(1)
               CALL MACFAL
               RETURN
            ELSE
               IF(SYSTEM(64).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
               END IF
               IF(SYSTEM(64).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(64).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(67).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
               END IF
               IF(SYSTEM(67).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
               IF(SYSTEM(67).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
            END IF
         END IF
!
         OUTLYNE = "ABOUT TO CALL PRTRA 1724"
         CALL SHOWIT(19)
         CALL PRTRA
         ITYPEP=2
         OUTLYNE = "ABOUT TO CALL FADJ"
         CALL SHOWIT(19)
         CALL FADJ
      ELSE
!       MODE NOT CORRECT
         IF(LNSTYP.EQ.1) THEN
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            OUTLYNE='AN "FNBX HLD" IS IN EFFECT.'
            CALL SHOWIT(1)
            OUTLYNE='"FNBX HLD" REQUIRES THE FOCAL OR UFOCAL MODES.'
            CALL SHOWIT(1)
            IF(SYSTEM(30).EQ.3.0D0) THEN
               OUTLYNE='CURRENT MODE IS AFOCAL.'
               CALL SHOWIT(1)
            END IF
            IF(SYSTEM(30).EQ.4.0D0) THEN
               OUTLYNE='CURRENT MODE IS UAFOCAL'
               CALL SHOWIT(1)
            END IF
            OUTLYNE='"FNBX HLD" NOT PERFORMED.'
            CALL SHOWIT(1)
         END IF
      END IF
!       NO FNBX HLD IN EFFECT
   END IF
!       NOW CHECK FOR ERY AND ERX HOLDS AND CHECK THE MODE.
!       IF NOT FOCAL OR UFOCAL, PRINT MESSAGE THAT HOLD WAS IGNORED.
!       CHECK FOR FNBY OR FNBX HOLD
   IF(SYSTEM(44).EQ.-2.0D0.AND.SYSTEM(83).EQ.0.0D0.AND.SYSTEM(84).EQ.0.0D0) THEN
!               THERE IS AN EXIT PUPIL RADIUS HOLD (YZ PLANE)
!       CHECK LENS MODE, MUST BE AFOCAL OR UAFOCAL
      IF(SYSTEM(30).EQ.3.0D0.OR.SYSTEM(30).EQ.4.0D0) THEN
!       HOLD PERFORMED. FIRST PERFORM A PARAXIAL TRACE TO GET
!       STATRING VALUES.
         ITYPEP=1
!       TELECENTRIC STUFF, 11/12/2000
         IF(SYSTEM(63).EQ.1.0D0) THEN
            IF(SYSTEM(64).EQ.0.0D0.AND.SYSTEM(67).EQ.0.0D0) THEN
               OUTLYNE='WHEN "TEL ON" IS SET, NAO OR FNO MUST BE USED'
               CALL SHOWIT(1)
               OUTLYNE='TO SPECIFY THE MARGINAL PARAXIAL RAY STARTING'
               CALL SHOWIT(1)
               OUTLYNE='VALUES'
               CALL SHOWIT(1)
               OUTLYNE='PARAXIAL TRACE STOPPED'
               CALL SHOWIT(1)
               CALL MACFAL
               RETURN
            ELSE
               IF(SYSTEM(64).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
               END IF
               IF(SYSTEM(64).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(64).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(67).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
               END IF
               IF(SYSTEM(67).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
               IF(SYSTEM(67).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
            END IF
         END IF
!
         OUTLYNE = "ABOUT TO CALL PRTRA "
         CALL SHOWIT(19)
         CALL PRTRA
         ITYPEP=1
         OUTLYNE = "ABOUT TO CALL ERADJ "
         CALL SHOWIT(19)
         CALL ERADJ
      ELSE
         IF(LNSTYP.EQ.1) THEN
!       MODE NOT CORRECT
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            OUTLYNE='AN "ERY HLD" IS IN EFFECT.'
            CALL SHOWIT(1)
            OUTLYNE='"ERY HLD" REQUIRES THE AFOCAL OR UAFOCAL MODES.'
            CALL SHOWIT(1)
            IF(SYSTEM(30).EQ.1.0D0) THEN
               OUTLYNE='CURRENT MODE IS FOCAL.'
               CALL SHOWIT(1)
            END IF
            IF(SYSTEM(30).EQ.2.0D0) THEN
               OUTLYNE='CURRENT MODE IS UFOCAL'
               CALL SHOWIT(1)
            END IF
            OUTLYNE='"ERY HLD" NOT PERFORMED.'
            CALL SHOWIT(1)
         END IF
      END IF
!       NO ERY HLD IN EFFECT
   END IF
   IF(SYSTEM(45).EQ.-2.0D0.AND.SYSTEM(83).EQ.0.0D0.AND.SYSTEM(84).EQ.0.0D0) THEN
!               THERE IS AN EXIT PUPIL RADIUS HOLD (XZ PLANE)
!       CHECK LENS MODE, MUST BE AFOCAL OR UAFOCAL
      IF(SYSTEM(30).EQ.3.0D0.OR.SYSTEM(30).EQ.4.0D0) THEN
!       HOLD PERFORMED. FIRST PERFORM A PARAXIAL TRACE TO GET
!       STARTING VALUES.
         ITYPEP=3
!       TELECENTRIC STUFF, 11/12/2000
         IF(SYSTEM(63).EQ.1.0D0) THEN
            IF(SYSTEM(64).EQ.0.0D0.AND.SYSTEM(67).EQ.0.0D0) THEN
               OUTLYNE='WHEN "TEL ON" IS SET, NAO OR FNO MUST BE USED'
               CALL SHOWIT(1)
               OUTLYNE='TO SPECIFY THE MARGINAL PARAXIAL RAY STARTING'
               CALL SHOWIT(1)
               OUTLYNE='VALUES'
               CALL SHOWIT(1)
               OUTLYNE='PARAXIAL TRACE STOPPED'
               CALL SHOWIT(1)
               CALL MACFAL
               RETURN
            ELSE
               IF(SYSTEM(64).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
               END IF
               IF(SYSTEM(64).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(64).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(67).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
               END IF
               IF(SYSTEM(67).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
               IF(SYSTEM(67).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
            END IF
         END IF
!
         OUTLYNE = "ABOUT TO CALL PRTRA "
         CALL SHOWIT(19)
         CALL PRTRA
         ITYPEP=2
         OUTLYNE = "ABOUT TO CALL ERADJ"
         CALL SHOWIT(19)
         CALL ERADJ
      ELSE
         IF(LNSTYP.EQ.1) THEN
!       MODE NOT CORRECT
            OUTLYNE='WARNING:'
            CALL SHOWIT(1)
            OUTLYNE='AN "ERX HLD" IS IN EFFECT.'
            CALL SHOWIT(1)
            OUTLYNE='"ERX HLD" REQUIRES THE AFOCAL OR UAFOCAL MODES.'
            CALL SHOWIT(1)
            IF(SYSTEM(30).EQ.1.0D0) THEN
               OUTLYNE='CURRENT MODE IS AFOCAL.'
               CALL SHOWIT(1)
            END IF
            IF(SYSTEM(30).EQ.2.0D0) THEN
               OUTLYNE='CURRENT MODE IS UAFOCAL'
               CALL SHOWIT(1)
            END IF
            OUTLYNE='"ERX HLD" NOT PERFORMED.'
            CALL SHOWIT(1)
         END IF
      END IF
!       NO ERX HLD IN EFFECT
   END IF

!
!       NOW WE GO TO THE PARAXIAL RAYTRACE AND
!       PERFORM ENOUGH PARAXIAL RAYTRACING TO AIM
!       RAYS TO THE STOP, RESOLVE SOLVES, AND RESOLVE
!       STOP ADJUSTMENTS AND PARAXIAL BASED HOLDS.
!       WE START BY BRANCHING OUT TO THE PAXAXIAL TRACE
!       BY CALLING PRTRA1. ALL CURRANT VARIABLES ARE
!       PASSED VIA COMMONS TO PRTRA1 AND PRTRA2.
!
!       PRTRA1 DOES THE YZ PLANE TRACE
!       PRTRA2 DOES THE XZ PLANE TRACE
!       AN XZ TRACE IS ALWAYS PERFORMED AND IS AVALIABLE
!       EVEN WHEN TORICS ARE NOT PRESENT
!
!
!       PIKUPS ARE RESOLVED BY (PIKRES) FOR EACH LENS SURFACE
!       GOING FROM SURFACE 0 TO IMMAGE SURFACE. THIS ACTION
!       IS TAKEN FROM WITHIN THE PARAXIAL RAYTRACE SUBROUTINES.
   ITYPEP=3
!       TELECENTRIC STUFF, 11/12/2000
   IF(SYSTEM(63).EQ.1.0D0) THEN
      IF(SYSTEM(64).EQ.0.0D0.AND.SYSTEM(67).EQ.0.0D0) THEN
         OUTLYNE='WHEN "TEL ON" IS SET, NAO OR FNO MUST BE USED'
         CALL SHOWIT(1)
         OUTLYNE='TO SPECIFY THE MARGINAL PARAXIAL RAY STARTING'
         CALL SHOWIT(1)
         OUTLYNE='VALUES'
         CALL SHOWIT(1)
         OUTLYNE='PARAXIAL TRACE STOPPED'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      ELSE
         IF(SYSTEM(64).EQ.1.0D0) THEN
            SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
         END IF
         IF(SYSTEM(64).EQ.2.0D0) THEN
            SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
         END IF
         IF(SYSTEM(64).EQ.3.0D0) THEN
            SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
            SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
         END IF
         IF(SYSTEM(67).EQ.1.0D0) THEN
            SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
         END IF
         IF(SYSTEM(67).EQ.2.0D0) THEN
            SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
         END IF
         IF(SYSTEM(67).EQ.3.0D0) THEN
            SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
            SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
         END IF
      END IF
   END IF
!
   OUTLYNE = "ABOUT TO CALL PRTRA 1964"
   CALL SHOWIT(19)
   CALL PRTRA

   OUTLYNE = "JUST CALLED PRTRA"
   CALL SHOWIT(19)
!
   IF(SYSTEM(83).NE.0.0D0.AND.SYSTEM(26).NE.-99.0D0.OR.SYSTEM(84).NE.0.0D0.AND.SYSTEM(26).NE.-99.0D0) THEN
      IF(surf_clap_type(INT(SYSTEM(26))).EQ.0.0D0.OR.surf_multi_clap_flag(INT(SYSTEM(26))).NE.0.0D0) THEN
!     NO ADJUSTMENTS TO SAY AND SAX ARE DONE, NO CLAP IS ON
!     STOP SURFACE
      ELSE
         IF(surf_clap_type(INT(SYSTEM(26))).EQ.1.0D0.AND.surf_multi_clap_flag(INT(SYSTEM(26))).EQ.0.0D0) THEN
            IF(surf_clap_dim(INT(SYSTEM(26)), 1).LE.surf_clap_dim(INT(SYSTEM(26)), 2)) THEN
               YCLAP=surf_clap_dim(INT(SYSTEM(26)), 1)/DABS(PXTRAY(1,INT(SYSTEM(26))))
               XCLAP=surf_clap_dim(INT(SYSTEM(26)), 1)/DABS(PXTRAX(1,INT(SYSTEM(26))))
            ELSE
               YCLAP=surf_clap_dim(INT(SYSTEM(26)), 2)/DABS(PXTRAY(1,INT(SYSTEM(26))))
               XCLAP=surf_clap_dim(INT(SYSTEM(26)), 2)/DABS(PXTRAX(1,INT(SYSTEM(26))))
            END IF
         END IF
         IF(surf_clap_type(INT(SYSTEM(26))).EQ.5.0D0.AND.surf_multi_clap_flag(INT(SYSTEM(26))).EQ.0.0D0) THEN
            YCLAP=surf_clap_dim(INT(SYSTEM(26)), 1)/DABS(PXTRAY(1,INT(SYSTEM(26))))
            XCLAP=surf_clap_dim(INT(SYSTEM(26)), 1)/DABS(PXTRAX(1,INT(SYSTEM(26))))
         END IF
         IF(surf_clap_type(INT(SYSTEM(26))).GT.1.0D0.AND.surf_clap_type(INT(SYSTEM(26))).LE.4.0D0.AND.surf_multi_clap_flag(INT(SYSTEM(26))).EQ.0.0D0) THEN
            YCLAP=surf_clap_dim(INT(SYSTEM(26)), 1)/DABS(PXTRAY(1,INT(SYSTEM(26))))
            XCLAP=surf_clap_dim(INT(SYSTEM(26)), 2)/DABS(PXTRAX(1,INT(SYSTEM(26))))
         END IF
         IF(SYSTEM(83).NE.0.0D0) THEN
            SYSTEM(12)=SYSTEM(12)*YCLAP
         END IF
         IF(SYSTEM(83).NE.0.0D0) THEN
            SYSTEM(13)=SYSTEM(13)*XCLAP
         END IF
         ITYPEP=3
!       TELECENTRIC STUFF, 11/12/2000
         IF(SYSTEM(63).EQ.1.0D0) THEN
            IF(SYSTEM(64).EQ.0.0D0.AND.SYSTEM(67).EQ.0.0D0) THEN
               OUTLYNE='WHEN "TEL ON" IS SET, NAO OR FNO MUST BE USED'
               CALL SHOWIT(1)
               OUTLYNE='TO SPECIFY THE MARGINAL PARAXIAL RAY STARTING'
               CALL SHOWIT(1)
               OUTLYNE='VALUES'
               CALL SHOWIT(1)
               OUTLYNE='PARAXIAL TRACE STOPPED'
               CALL SHOWIT(1)
               CALL MACFAL
               RETURN
            ELSE
               IF(SYSTEM(64).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
               END IF
               IF(SYSTEM(64).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(64).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(67).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
               END IF
               IF(SYSTEM(67).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
               IF(SYSTEM(67).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
            END IF
         END IF
!
         CALL PRTRA
         OUTLYNE = "JUST CALLED PRTRA"
         CALL SHOWIT(19)

         IF(surf_clap_type(INT(SYSTEM(26))).EQ.1.0D0.AND.surf_multi_clap_flag(INT(SYSTEM(26))).EQ.0.0D0) THEN
            IF(surf_clap_dim(INT(SYSTEM(26)), 1).LE.surf_clap_dim(INT(SYSTEM(26)), 2)) THEN
               YCLAP=surf_clap_dim(INT(SYSTEM(26)), 1)/DABS(PXTRAY(1,INT(SYSTEM(26))))
               XCLAP=surf_clap_dim(INT(SYSTEM(26)), 1)/DABS(PXTRAX(1,INT(SYSTEM(26))))
            ELSE
               YCLAP=surf_clap_dim(INT(SYSTEM(26)), 2)/DABS(PXTRAY(1,INT(SYSTEM(26))))
               XCLAP=surf_clap_dim(INT(SYSTEM(26)), 2)/DABS(PXTRAX(1,INT(SYSTEM(26))))
            END IF
         END IF
         IF(surf_clap_type(INT(SYSTEM(26))).EQ.5.0D0.AND.surf_multi_clap_flag(INT(SYSTEM(26))).EQ.0.0D0) THEN
            YCLAP=surf_clap_dim(INT(SYSTEM(26)), 1)/DABS(PXTRAY(1,INT(SYSTEM(26))))
            XCLAP=surf_clap_dim(INT(SYSTEM(26)), 1)/DABS(PXTRAX(1,INT(SYSTEM(26))))
         END IF
         IF(surf_clap_type(INT(SYSTEM(26))).GT.1.0D0.AND.surf_clap_type(INT(SYSTEM(26))).LE.4.0D0.AND.surf_multi_clap_flag(INT(SYSTEM(26))).EQ.0.0D0) THEN
            YCLAP=surf_clap_dim(INT(SYSTEM(26)), 1)/DABS(PXTRAY(1,INT(SYSTEM(26))))
            XCLAP=surf_clap_dim(INT(SYSTEM(26)), 2)/DABS(PXTRAX(1,INT(SYSTEM(26))))
         END IF
         IF(SYSTEM(83).NE.0.0D0) THEN
            SYSTEM(12)=SYSTEM(12)*YCLAP
         END IF
         IF(SYSTEM(83).NE.0.0D0) THEN
            SYSTEM(13)=SYSTEM(13)*XCLAP
         END IF
         ITYPEP=3
!       TELECENTRIC STUFF, 11/12/2000
         IF(SYSTEM(63).EQ.1.0D0) THEN
            IF(SYSTEM(64).EQ.0.0D0.AND.SYSTEM(67).EQ.0.0D0) THEN
               OUTLYNE='WHEN "TEL ON" IS SET, NAO OR FNO MUST BE USED'
               CALL SHOWIT(1)
               OUTLYNE='TO SPECIFY THE MARGINAL PARAXIAL RAY STARTING'
               CALL SHOWIT(1)
               OUTLYNE='VALUES'
               CALL SHOWIT(1)
               OUTLYNE='PARAXIAL TRACE STOPPED'
               CALL SHOWIT(1)
               CALL MACFAL
               RETURN
            ELSE
               IF(SYSTEM(64).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
               END IF
               IF(SYSTEM(64).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(64).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)*SYSTEM(65)
                  SYSTEM(13)=surf_thickness(0)*SYSTEM(66)
               END IF
               IF(SYSTEM(67).EQ.1.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
               END IF
               IF(SYSTEM(67).EQ.2.0D0) THEN
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
               IF(SYSTEM(67).EQ.3.0D0) THEN
                  SYSTEM(12)=surf_thickness(0)/(2.0D0*SYSTEM(68))
                  SYSTEM(13)=surf_thickness(0)/(2.0D0*SYSTEM(69))
               END IF
            END IF
         END IF
!
         CALL PRTRA
         OUTLYNE = "JUST CALLED PRTRA "
         CALL SHOWIT(19)
      END IF
   END IF
!
!       NOW ALL PARAXIAL BASED CHANGES TO THE LENS HAVE BEEN
!       MADE.
!
!***************************************************************
!       NOW RESOLVE THE  SYMMETRY SWITCH SETTING
!     XZ-PLANE
!       SYSTEM(28)=1.0D0 MEANS XZ SYMMETRY
!       SYSTEM(28)=0.0D0 MEANS NO XZ SYMMETRY
   SYSTEM(28)=1.0D0
!       A SETTING OF 1.0 MEANS ROTATIONAL SYMMETRY. 0 MEAN
!       NO ROTATIONAL SYMMETRY.
   DO III=0,INT(SYSTEM(20))
!
!       IF THERE IS AN XD, BETA OR GAMMA NON-ZERO
!       SET SYSTEM(28)=0.0D0
      IF(surf_beta(III).NE.0.0D0.OR.surf_gamma(III).NE.0.0D0.OR.surf_decenter_x(III).NE.0.0D0) THEN
         SYSTEM(28)=0.0D0
         GO TO 628
      END IF
!       IF A NON-ROTATIONALLY SYMMETRIC SPECIAL SURFACE EXISTS
!       AT THIS TIME (SEPT 1989) ONLY TYPE 0 (NONE) AND TYPE 1
!       (ROTATIONAL POLYNOMIAL) ARE ROTATIONALLY SYMMETRIC.
      IF(ABS(surf_special_type(III)) /= 0.AND.ABS(surf_special_type(III)) /= 1) THEN
         SYSTEM(28)=0.0D0
         GO TO 628
      END IF
   END DO
!       REFS ORIENTATION NOT 0.0 OR CLAP TILT EXITS ON THE
!       REFERENCE SURFACE
   IF(surf_clap_type(NEWREF) /= 0.AND.surf_clap_tilt(NEWREF).NE.0.0D0 .AND.surf_multi_clap_flag(NEWREF) == 0.OR.surf_multi_clap_flag(NEWREF) == 0 .AND.SYSTEM(59).NE.0.0D0) SYSTEM(28)=0.0D0
628 CONTINUE
!     YZ-PLANE
!       SYSTEM(48)=1.0D0 MEANS YZ SYMMETRY
!       SYSTEM(48)=0.0D0 MEANS NO YZ SYMMETRY
   SYSTEM(48)=1.0D0
!       A SETTING OF 1.0 MEANS ROTATIONAL SYMMETRY. 0 MEAN
!       NO ROTATIONAL SYMMETRY.
   DO III=0,INT(SYSTEM(20))
!
!       IF THERE IS AN YD, ALPHA OR GAMMA NON-ZERO
!       SET SYSTEM(48)=0.0D0
      IF(surf_alpha_deg(III).NE.0.0D0.OR.surf_gamma_deg(III).NE.0.0D0.OR.surf_focus_dy(III).NE.0.0D0) THEN
         SYSTEM(48)=0.0D0
         GO TO 629
      END IF
!       IF A NON-ROTATIONALLY SYMMETRIC SPECIAL SURFACE EXISTS
!       AT THIS TIME (SEPT 1989) ONLY TYPE 0 (NONE) AND TYPE 1
!       (ROTATIONAL POLYNOMIAL) ARE ROTATIONALLY SYMMETRIC.
      IF(ABS(surf_special_type(III)) /= 0.AND.ABS(surf_special_type(III)) /= 1) THEN
         SYSTEM(48)=0.0D0
         GO TO 629
      END IF
   END DO
629 CONTINUE
!*******************************************************************
!
!       NOW IF F12=1, MAIN CONFIG, THEN MAKE THE PERMANENT LENS RECORD
!       EQUAL TO THE CURRENT DATA UNLESS LNSTYP = 3
   IF(LNSTYP.EQ.1.OR.LNSTYP.EQ.2) THEN
      IF(F12.EQ.1) THEN
         CALL CTOP
         OUTLYNE = "CTOP JUST FINISHED"
         CALL SHOWIT(19)
!************************************************************
!               PERMANENT LENS UPDATED
!       F12 NOT 1, PROCEED
      END IF
   END IF
!     NOW UPDATE DUMMM
!     SURFACES 0 AND INT(SYSTEM(20)) ARE NEVER DUMMIES
   DUMMMY(0)=.FALSE.
   DUMMMY(INT(SYSTEM(20)))=.FALSE.
!
   DO ZZTOP=1,INT(SYSTEM(20))-1
      DUMMMY(ZZTOP)=.FALSE.
      IF(GLANAM(ZZTOP,1).EQ.GLANAM((ZZTOP-1),1).AND.GLANAM(ZZTOP,2).EQ.GLANAM((ZZTOP-1),2).AND.GLANAM(ZZTOP,2).NE.'REFL'.AND.GLANAM(ZZTOP,2).NE.'REFLTIRO'.AND.GLANAM(ZZTOP,2).NE.'IDEAL'.AND.GLANAM(ZZTOP,2).NE.'PERFECT      ') DUMMMY(ZZTOP)=.TRUE.
      IF(GLANAM(ZZTOP,1).EQ.'MODEL        ') DUMMMY(ZZTOP)=.FALSE.
      IF(GLANAM(ZZTOP-1,1).EQ.'MODEL        ') DUMMMY(ZZTOP)=.FALSE.
      IF(surf_refractive_index(ZZTOP, 1).EQ.surf_refractive_index(ZZTOP-1, 1).AND.surf_refractive_index(ZZTOP, 2).EQ.surf_refractive_index(ZZTOP-1, 2).AND.surf_refractive_index(ZZTOP, 3).EQ.surf_refractive_index(ZZTOP-1, 3).AND.surf_refractive_index(ZZTOP, 4).EQ.surf_refractive_index(ZZTOP-1, 4).AND.surf_refractive_index(ZZTOP, 6).EQ.surf_refractive_index(ZZTOP-1, 6).AND.surf_refractive_index(ZZTOP, 7).EQ.surf_refractive_index(ZZTOP-1, 7).AND.surf_refractive_index(ZZTOP, 8).EQ.surf_refractive_index(ZZTOP-1, 8).AND.surf_refractive_index(ZZTOP, 9).EQ.surf_refractive_index(ZZTOP-1, 9).AND.surf_refractive_index(ZZTOP, 10).EQ.surf_refractive_index(ZZTOP-1, 10).AND.surf_refractive_index(ZZTOP, 5).EQ.surf_refractive_index(ZZTOP-1, 5)) DUMMMY(ZZTOP)=.TRUE.
      IF(GLANAM(ZZTOP,1).EQ.'MODEL        '.AND.GLANAM(ZZTOP-1,1).EQ.'MODEL        '.AND.GLANAM(ZZTOP-1,2).EQ.GLANAM(ZZTOP,2)) THEN
         DUMMMY(ZZTOP)=.FALSE.
         IF(surf_fict_n(ZZTOP).EQ.surf_fict_n(ZZTOP-1).AND.surf_fict_v(ZZTOP).EQ.surf_fict_v(ZZTOP-1).AND.surf_fict_w(ZZTOP).EQ.surf_fict_w(ZZTOP-1)) DUMMMY(ZZTOP)=.TRUE.
      END IF
      IF(surf_dummy_val(ZZTOP) == 1.AND.DUMMMY(ZZTOP))DUMMMY(ZZTOP)=.FALSE.
!
   END DO
!
!     RESOLVE CHARACTERISTICS OF PERFECT LENSES
   I=INT(SYSTEM(20))-1
   IF(GLANAM(I,2).EQ.'PERFECT      ') THEN
      call set_surf_curvature(I, 0.0D0)
      call set_surf_conic(I, 0.0D0)
      call set_surf_asphere_coeff(I, 4, 0.0D0)
      call set_surf_asphere_coeff(I, 6, 0.0D0)
      call set_surf_asphere_coeff(I, 8, 0.0D0)
      call set_surf_asphere_coeff(I, 10, 0.0D0)
      call set_surf_asphere_flag(I, .false.)
      call set_surf_clap_type(I, 0)
      call set_surf_multi_clap_flag(I, 0)
      call set_surf_toric_flag(I, 0)
      call set_surf_toric_curvature(I, 0.0D0)
      call set_surf_decenter_flag(I, 0)
      call set_surf_decenter_y(I, 0.0D0)
      call set_surf_decenter_x(I, 0.0D0)
      call set_surf_pickup_count(I, 0)
      call set_surf_solve_flag(I, 0.0D0)
      call set_surf_special_type(I, 0)
      call set_surf_asi_enabled(I, 0)
      call set_surf_anamorphic_flag(I, 0)
      call set_surf_anamorphic_coeff(I, 4, 0.0D0)
      call set_surf_anamorphic_coeff(I, 6, 0.0D0)
      call set_surf_anamorphic_coeff(I, 8, 0.0D0)
      call set_surf_anamorphic_coeff(I, 10, 0.0D0)
      call set_surf_anamorphic_conic(I, 0.0D0)
      call set_surf_asphere_coeff(I, 2, 0.0D0)
      ALENS(45,I)=0.0D0
      call set_surf_cobs_ape_type(I, 0)
      call set_surf_pivot_flag(I, 0)
      call set_surf_cobs_era_type(I, 0)
      call set_surf_dummy_val(I, 1)
      call set_surf_decenter_z(I, 0.0D0)
      call set_surf_ret_surf_num(I, 0)
      call set_surf_tilt_return_flag(I, 0)
      call set_surf_pivot_x(I, 0.0D0)
      call set_surf_pivot_y(I, 0.0D0)
      call set_surf_pivot_z(I, 0.0D0)
      call set_surf_pivot_z(I, 0.0D0)
      call set_surf_asphere_coeff(I, 12, 0.0D0)
      call set_surf_asphere_coeff(I, 14, 0.0D0)
      call set_surf_asphere_coeff(I, 16, 0.0D0)
      call set_surf_asphere_coeff(I, 18, 0.0D0)
      call set_surf_asphere_coeff(I, 20, 0.0D0)
      call set_surf_fict_n(I, 0.0D0)
      call set_surf_fict_v(I, 0.0D0)
      call set_surf_aux88(I, 0.0D0)
      call set_surf_fict_w(I, 0.0D0)
      call set_surf_global_dx(I, 0.0D0)
      call set_surf_global_dy(I, 0.0D0)
      call set_surf_global_dz(I, 0.0D0)
      call set_surf_global_alpha(I, 0.0D0)
      call set_surf_global_beta(I, 0.0D0)
      call set_surf_global_gamma(I, 0.0D0)
      call set_surf_diffraction_flag(I, 0)
      call set_surf_grating_order(I, 0.0D0)
      call set_surf_grating_spacing(I, 0.0D0)
      call set_surf_grating_vx(I, 0.0D0)
      call set_surf_grating_vy(I, 0.0D0)
      call set_surf_grating_vz(I, 0.0D0)
      call set_surf_spgr(I, 0.0D0)
      call set_surf_default_flag(I, 0)
      call set_surf_mtracei_nx(I, 0.0D0)
      call set_surf_mtracei_ny(I, 0.0D0)
      call set_surf_psfbin_data(I, 0.0D0)
      call set_surf_profit_data(I, 0.0D0)
      ALENS(108,I)=0.0D0
      ALENS(109,I)=0.0D0
      call set_surf_mirror_thickness(I, 0.0D0)
      call set_surf_tilt_flag(I, 0)
      call set_surf_alpha(I, 0.0D0)
      call set_surf_beta(I, 0.0D0)
      call set_surf_gamma(I, 0.0D0)
      call set_surf_focus_dx(I, 0.0D0)
      call set_surf_focus_dy(I, 0.0D0)
      call set_surf_focus_dz(I, 0.0D0)
      call set_surf_alpha_deg(I, 0.0D0)
      call set_surf_beta_deg(I, 0.0D0)
      call set_surf_gamma_deg(I, 0.0D0)
      I=INT(SYSTEM(20))
      call set_surf_curvature(I, 0.0D0)
      call set_surf_conic(I, 0.0D0)
      call set_surf_asphere_coeff(I, 4, 0.0D0)
      call set_surf_asphere_coeff(I, 6, 0.0D0)
      call set_surf_asphere_coeff(I, 8, 0.0D0)
      call set_surf_asphere_coeff(I, 10, 0.0D0)
      call set_surf_asphere_flag(I, .false.)
      call set_surf_clap_type(I, 0)
      call set_surf_multi_clap_flag(I, 0)
      call set_surf_toric_flag(I, 0)
      call set_surf_toric_curvature(I, 0.0D0)
      call set_surf_decenter_flag(I, 0)
      call set_surf_decenter_y(I, 0.0D0)
      call set_surf_focus_dx(I, 0.0D0)
      call set_surf_focus_dy(I, 0.0D0)
      call set_surf_focus_dz(I, 0.0D0)
      call set_surf_decenter_x(I, 0.0D0)
      call set_surf_pickup_count(I, 0)
      call set_surf_solve_flag(I, 0.0D0)
      call set_surf_special_type(I, 0)
      call set_surf_asi_enabled(I, 0)
      call set_surf_anamorphic_flag(I, 0)
      call set_surf_anamorphic_coeff(I, 4, 0.0D0)
      call set_surf_anamorphic_coeff(I, 6, 0.0D0)
      call set_surf_anamorphic_coeff(I, 8, 0.0D0)
      call set_surf_anamorphic_coeff(I, 10, 0.0D0)
      call set_surf_anamorphic_conic(I, 0.0D0)
      call set_surf_asphere_coeff(I, 2, 0.0D0)
      ALENS(45,I)=0.0D0
      call set_surf_cobs_ape_type(I, 0)
      call set_surf_pivot_flag(I, 0)
      call set_surf_cobs_era_type(I, 0)
      call set_surf_dummy_val(I, 1)
      call set_surf_decenter_z(I, 0.0D0)
      call set_surf_ret_surf_num(I, 0)
      call set_surf_tilt_return_flag(I, 0)
      call set_surf_pivot_x(I, 0.0D0)
      call set_surf_pivot_y(I, 0.0D0)
      call set_surf_pivot_z(I, 0.0D0)
      call set_surf_pivot_z(I, 0.0D0)
      call set_surf_asphere_coeff(I, 12, 0.0D0)
      call set_surf_asphere_coeff(I, 14, 0.0D0)
      call set_surf_asphere_coeff(I, 16, 0.0D0)
      call set_surf_asphere_coeff(I, 18, 0.0D0)
      call set_surf_asphere_coeff(I, 20, 0.0D0)
      call set_surf_fict_n(I, 0.0D0)
      call set_surf_fict_v(I, 0.0D0)
      call set_surf_aux88(I, 0.0D0)
      call set_surf_fict_w(I, 0.0D0)
      call set_surf_global_dx(I, 0.0D0)
      call set_surf_global_dy(I, 0.0D0)
      call set_surf_global_dz(I, 0.0D0)
      call set_surf_global_alpha(I, 0.0D0)
      call set_surf_global_beta(I, 0.0D0)
      call set_surf_global_gamma(I, 0.0D0)
      call set_surf_diffraction_flag(I, 0)
      call set_surf_grating_order(I, 0.0D0)
      call set_surf_grating_spacing(I, 0.0D0)
      call set_surf_grating_vx(I, 0.0D0)
      call set_surf_grating_vy(I, 0.0D0)
      call set_surf_grating_vz(I, 0.0D0)
      call set_surf_spgr(I, 0.0D0)
      call set_surf_default_flag(I, 0)
      call set_surf_mtracei_nx(I, 0.0D0)
      call set_surf_mtracei_ny(I, 0.0D0)
      call set_surf_psfbin_data(I, 0.0D0)
      call set_surf_profit_data(I, 0.0D0)
      ALENS(108,I)=0.0D0
      ALENS(109,I)=0.0D0
      call set_surf_mirror_thickness(I, 0.0D0)
      call set_surf_tilt_flag(I, 0)
      call set_surf_alpha(I, 0.0D0)
      call set_surf_beta(I, 0.0D0)
      call set_surf_gamma(I, 0.0D0)
      call set_surf_alpha_deg(I, 0.0D0)
      call set_surf_beta_deg(I, 0.0D0)
      call set_surf_gamma_deg(I, 0.0D0)
   END IF
   I=INT(SYSTEM(20))-1
   IF(GLANAM(I,2).EQ.'PERFECT      ') THEN
      IF(SYSTEM(30).GE.3.0D0) THEN
         IF(SYSTEM(30).EQ.3.0D0) SYSTEM(30)=1.0D0
         IF(SYSTEM(30).EQ.4.0D0) SYSTEM(30)=2.0D0
         OUTLYNE='"PERFECT" SURFACE IN USE. LENS MODE HAS BEEN'
         CALL SHOWIT(1)
         IF(SYSTEM(30).EQ.1.0D0) OUTLYNE='RESET TO THE "FOCAL" MODE'
         IF(SYSTEM(30).EQ.2.0D0) OUTLYNE='RESET TO THE "UFOCAL" MODE'
         CALL SHOWIT(1)
      END IF
   END IF
!     RESOLVE CHARACTERISTICS OF IDEAL LENSES
   I=INT(SYSTEM(20))-1
   IF(GLANAM(I,2).EQ.'IDEAL        ') THEN
      ALENS(1:2,I)=0.0D0
      ALENS(4:9,I)=0.0D0
      call set_surf_multi_clap_flag(I, 0)
      ALENS(23:24,I)=0.0D0
      call set_surf_decenter_flag(I, 0)
      ALENS(30:43,I)=0.0D0
      ALENS(45,I)=0.0D0
      call set_surf_cobs_ape_type(I, 0)
      call set_surf_pivot_flag(I, 0)
      call set_surf_cobs_era_type(I, 0)
      call set_surf_dummy_val(I, 1)
      call set_surf_decenter_z(I, 0.0D0)
      call set_surf_ret_surf_num(I, 0)
      ALENS(77:110,I)=0.0D0
      ALENS(25:28,I)=0.0D0
      ALENS(114:120,I)=0.0D0
      I=INT(SYSTEM(20))
      ALENS(1:2,I)=0.0D0
      ALENS(4:9,I)=0.0D0
      call set_surf_multi_clap_flag(I, 0)
      ALENS(23:24,I)=0.0D0
      ALENS(29:30,I)=0.0D0
      ALENS(114:116,I)=0.0D0
      ALENS(31:43,I)=0.0D0
      ALENS(45,I)=0.0D0
      call set_surf_cobs_ape_type(I, 0)
      call set_surf_pivot_flag(I, 0)
      call set_surf_cobs_era_type(I, 0)
      call set_surf_dummy_val(I, 1)
      call set_surf_decenter_z(I, 0.0D0)
      call set_surf_ret_surf_num(I, 0)
      ALENS(77:110,I)=0.0D0
      ALENS(25:28,I)=0.0D0
      ALENS(118:120,I)=0.0D0
   END IF
   I=INT(SYSTEM(20))-1
   IF(GLANAM(I,2).EQ.'IDEAL        ') THEN
      IF(SYSTEM(30).GE.3.0D0) THEN
         IF(SYSTEM(30).EQ.3.0D0) SYSTEM(30)=1.0D0
         IF(SYSTEM(30).EQ.4.0D0) SYSTEM(30)=2.0D0
         OUTLYNE='"IDEAL" SURFACE IN USE. LENS MODE HAS BEEN'
         CALL SHOWIT(1)
         IF(SYSTEM(30).EQ.1.0D0) OUTLYNE='RESET TO THE "FOCAL" MODE'
         IF(SYSTEM(30).EQ.2.0D0) OUTLYNE='RESET TO THE "UFOCAL" MODE'
         CALL SHOWIT(1)
      END IF
   END IF
!
!
!     ADDED ON 3/17/93
!     SET UP THE FAST ACCESS CFG ARRAYS FOR OPTIMIZATION
!     IF THERE ARE CONFIGS

   IF(INT(SYSTEM(56)).GT.1.AND.LNSTYP.NE.3) CALL AUXCFG
   OUTLYNE = "JUST FINISHED AUXCFG CHECK"
   CALL SHOWIT(19)
!
!     INITIALIZE THE FRONT FOCAL LENGTH, BACK FOCAL LENGTH
!     AND ENTRANCE TO EXIT PUPIL MAG VARIABLES BASED ON
!     PARAXIAL DATA
!
   RFFLX=0.0D0
   RFFLY=0.0D0
   RBFLX=0.0D0
   RBFLY=0.0D0
   RMAGX=0.0D0
   RMAGY=0.0D0
   MAGXOR=0.0D0
   MAGYOR=0.0D0
!
   IF(PXTRAX(6,NEWREF).NE.0.0D0) THEN
      MAGXOR=PXTRAX(6,NEWOBJ)/PXTRAX(6,NEWREF)
   ELSE
      IF(PXTRAX(6,NEWOBJ).GE.0.0D0) MAGXOR=1.0D10
      IF(PXTRAX(6,NEWOBJ).LT.0.0D0) MAGXOR=-1.0D10
   END IF
   IF(PXTRAY(6,NEWREF).NE.0.0D0) THEN
      MAGYOR=PXTRAY(6,NEWOBJ)/PXTRAY(6,NEWREF)
   ELSE
      IF(PXTRAY(6,NEWOBJ).GE.0.0D0) MAGYOR=1.0D10
      IF(PXTRAY(6,NEWOBJ).LT.0.0D0) MAGYOR=-1.0D10
   END IF
!
!     RFFLX,RFFLY,RBFLX,RBFLY
!
   I=NEWOBJ
   J=NEWIMG-1
   IF(((PXTRAY(2,I)*PXTRAY(6,J))-(PXTRAY(6,I)*PXTRAY(2,J))).NE.0.0D0) THEN
      REFLY=-(((PXTRAY(2,I)*PXTRAY(5,I+1))-(PXTRAY(1,I+1)*PXTRAY(6,I )))/((PXTRAY(2,I)*PXTRAY(6,J))-(PXTRAY(6,I)*PXTRAY(2,J))))
   ELSE
      REFLY=1.0D20
   END IF
   IF(((PXTRAX(2,I)*PXTRAX(6,J))-(PXTRAX(6,I)*PXTRAX(2,J))).NE.0.0D0) THEN
      REFLX=-(((PXTRAX(2,I)*PXTRAX(5,I+1))-(PXTRAX(1,I+1)*PXTRAX(6,I )))/((PXTRAX(2,I)*PXTRAX(6,J))-(PXTRAX(6,I)*PXTRAX(2,J))))
   ELSE
      REFLX=1.0D20
   END IF
   IF(((PXTRAY(2,I)*PXTRAY(6,J))-(PXTRAY(6,I)*PXTRAY(2,J))).NE.0.0D0) THEN
      RBFLY=-(((PXTRAY(2,I)*PXTRAY(5,J))-(PXTRAY(6,I)*PXTRAY(1,J)))/((PXTRAY(2,I)*PXTRAY(6,J))-(PXTRAY(6,I)*PXTRAY(2,J))))
   ELSE
      RBFLY=1.0D20
   END IF
   IF(((PXTRAX(2,I)*PXTRAX(6,J))-(PXTRAX(6,I)*PXTRAX(2,J))).NE.0.0D0) THEN
      RBFLX=-(((PXTRAX(2,I)*PXTRAX(5,J))-(PXTRAX(6,I)*PXTRAX(1,J)))/((PXTRAX(2,I)*PXTRAX(6,J))-(PXTRAX(6,I)*PXTRAX(2,J))))
   ELSE
      RBFLX=1.0D20
   END IF
   IF(((PXTRAY(2,I)*PXTRAY(6,J))-(PXTRAY(6,I)*PXTRAY(2,J))).NE.0.0D0) THEN
      RFFLY=-(((PXTRAY(1,I+1)*PXTRAY(6,J))-(PXTRAY(2,J)*PXTRAY(5,I+1 )))/((PXTRAY(2,I)*PXTRAY(6,J))-(PXTRAY(6,I)*PXTRAY(2,J))))
   ELSE
      RFFLY=1.0D20
   END IF
   IF(((PXTRAX(2,I)*PXTRAX(6,J))-(PXTRAX(6,I)*PXTRAX(2,J))).NE.0.0D0) THEN
      RFFLX=-(((PXTRAX(1,I+1)*PXTRAX(6,J))-(PXTRAX(2,J)*PXTRAX(5,I+1 )))/((PXTRAX(2,I)*PXTRAX(6,J))-(PXTRAX(6,I)*PXTRAX(2,J))))
   ELSE
      RFFLX=1.0D20
   END IF
!
!     F-NUMBERS
!
   IF(PXTRAX(2,NEWOBJ).NE.0.0D0) THEN
      RFFNX=-0.5D0/PXTRAX(2,NEWOBJ)
   ELSE
      IF(RFFLX.GE.0.0D0) RFFNX=1.0D10
      IF(RFFLX.LT.0.0D0) RFFNX=-1.0D10
   END IF
   IF(PXTRAY(2,NEWOBJ).NE.0.0D0) THEN
      RFFNY=-0.5D0/PXTRAY(2,NEWOBJ)
   ELSE
      IF(RFFLY.GE.0.0D0) RFFNY=1.0D10
      IF(RFFLY.LT.0.0D0) RFFNY=-1.0D10
   END IF
   IF(PXTRAX(2,NEWIMG).NE.0.0D0) THEN
      RBFNX=-0.5D0/PXTRAX(2,NEWIMG)
   ELSE
      IF(RBFLX.GE.0.0D0) RBFNX=1.0D10
      IF(RBFLX.LT.0.0D0) RBFNX=-1.0D10
   END IF
   IF(PXTRAY(2,NEWIMG).NE.0.0D0) THEN
      RBFNY=-0.5D0/PXTRAY(2,NEWIMG)
   ELSE
      IF(RBFLY.GE.0.0D0) RBFNY=1.0D10
      IF(RBFLY.LT.0.0D0) RBFNY=-1.0D10
   END IF
!     RMAGX AND RMAGY
   IF(PXTRAX(6,NEWOBJ).NE.0.0D0) THEN
      RMAGX=PXTRAX(6,NEWIMG)/PXTRAX(6,NEWOBJ)
   ELSE
      IF(PXTRAX(6,NEWOBJ).GE.0.0D0) RMAGX=1.0D10
      IF(PXTRAX(6,NEWOBJ).LT.0.0D0) RMAGX=-1.0D10
   END IF
   IF(PXTRAY(6,NEWOBJ).NE.0.0D0) THEN
      RMAGY=PXTRAY(6,NEWIMG)/PXTRAY(6,NEWOBJ)
   ELSE
      IF(PXTRAY(6,NEWOBJ).GE.0.0D0) RMAGY=1.0D10
      IF(PXTRAY(6,NEWOBJ).LT.0.0D0) RMAGY=-1.0D10
   END IF
!     PARAXIAL DEFAULT PUPIL DATA
!     NOW THE ENTRANCE AND EXIT PUPIL POSITIONS
   IF(DABS(PXTRAY(6,1)).EQ.0.0) THEN
      ENPOSY=-(surf_thickness(0))
   ELSE
      !ENPOSY=(-PXTRAY(5,1)/PXTRAY(6,1))
      ! JN:  The entrance pupil position was not being
      ! calculated per standard convention for infinite
      ! object distance.  The chief ray angle that was
      ! being used was the angle after surface 1, not
      ! the angle at the object plane. Updated this to
      ! use the angle at the object plane (0 index)
      ENPOSY=(-PXTRAY(5,1)/PXTRAY(6,0))
   END IF
   IF(DABS(PXTRAX(6,1)).EQ.0.0D0) THEN
      ENPOSX=-(surf_thickness(0))
   ELSE
      !ENPOSX=(-PXTRAX(5,1)/PXTRAX(6,1))
      ENPOSX=(-PXTRAX(5,1)/PXTRAX(6,0))
   END IF
   ENPUX=0.0D0
   ENPUY=0.0D0
   ENPUZ=(ENPOSX+ENPOSY)/2.0D0
!     NOW THE EXIT PUPIL POSITIONS
   IF(DABS(PXTRAY(6,INT(SYSTEM(20)))).EQ.0.0D0) THEN
      EXPOSY=surf_thickness(0)
   ELSE
      EXPOSY=(-PXTRAY(5,INT(SYSTEM(20)))/PXTRAY(6,INT(SYSTEM(20))))
   END IF
   IF(DABS(PXTRAX(6,INT(SYSTEM(20)))).EQ.0.0D0) THEN
      EXPOSX=surf_thickness(0)
   ELSE
      EXPOSX=(-PXTRAX(5,INT(SYSTEM(20)))/PXTRAX(6,INT(SYSTEM(20))))
   END IF
   EXPUX=0.0D0
   EXPUY=0.0D0
   EXPUZ=(EXPOSX+EXPOSY)/2.0D0
!     NOW THE ENTRANCE AND EXIT PUPIL DIAMETERS
   ENDIAX=2.0D0*DABS(PXTRAX(1,1)+(ENPUZ*PXTRAX(2,0)))
   ENDIAY=2.0D0*DABS(PXTRAY(1,1)+(ENPUZ*PXTRAY(2,0)))
   EXDIAX=2.0D0*DABS(PXTRAX(1,INT(SYSTEM(20)))+(EXPUZ *PXTRAX(2,INT(SYSTEM(20)))))
   EXDIAY=2.0D0*DABS(PXTRAY(1,INT(SYSTEM(20)))+(EXPUZ *PXTRAY(2,INT(SYSTEM(20)))))

   !JN:  Now that we have the entrance and exit pupils, call
   ! RATRA one more time such that we can properly trace
   ! the marginal ray for finite conjugate systems
   call curr_par_ray_trace%calculateFirstOrderParameters(curr_lens_data)
   CALL PRTRA
!
!     NOW SET THE INR FOR PHASE SURFACE RAY TRACES
!     THE INR IS THE LARGER OF THE ABSOLUTE VALUE OF THE
!     X-CLAP PLUS X-CLAP OFFSET OR THE Y-CLAP PLUS Y-CLAP OFFSET
!     IF THERE IS A CLAP. IF NO CLAP, IT IS THE SUM OF THE ABSOLUTE
!     VALUES OF THE PY PLUS PCY AT THAT SURFACE
   DO I=0,INT(SYSTEM(20))
      IF(surf_inr_flag(I).EQ.0.0D0) THEN
!     MAKE A DEFAULT ASSIGNMENT
         IF(surf_clap_type(I) /= 0.AND.surf_multi_clap_flag(I) == 0) THEN
!     USE CLAP DATA
            IF(surf_clap_type(I) /= 5) THEN
               A1=DABS(surf_clap_dim(I, 1))+DABS(surf_clap_dim(I, 3))
               A2=DABS(surf_clap_dim(I, 2))+DABS(surf_clap_dim(I, 4))
            ELSE
               A1=DABS(surf_clap_dim(I, 1))+DABS(surf_clap_dim(I, 3))
               A2=DABS(surf_clap_dim(I, 1))+DABS(surf_clap_dim(I, 4))
            END IF
            IF(A1.GE.A2) THEN
               call set_surf_inr_value(I, A1)
            ELSE
               call set_surf_inr_value(I, A2)
            END IF
         ELSE
!     USE PARAX DATA
            A1=DABS(PXTRAX(1,I))+DABS(PXTRAX(5,I))
            A2=DABS(PXTRAY(1,I))+DABS(PXTRAY(5,I))
            IF(A1.GE.A2) THEN
               call set_surf_inr_value(I, A1)
            ELSE
               call set_surf_inr_value(I, A2)
            END IF
         END IF
!     NO ASSIGNMENT IS NECESSARY
      END IF
   END DO
!     11/04/96
!     RESOLVE ALL TILT RETURNS AND APPLY ALL TILT RETURN RULES
!     BY CALLING TILT_RETURN
   SYSTEM(90)=0.0D0
   DO I=0,INT(SYSTEM(20))
!     IF THE TILT RET FLAG RES WAS ON, SET THE TILT TYPE TO TILT RET
!     THEN SET RESOLUTION FLAG TO OFF OR ZERO
      IF(surf_tilt_return_flag(I) == 1) call set_surf_tilt_flag(I, 6)
      call set_surf_tilt_return_flag(I, 0)
   END DO
!     RESOLVE ALL PIVOTS WHICH BY THEIR NATURE DEFINE NEW DECENTERS
!     ON THE AFFECTED SURFACES
   DO I=0,INT(SYSTEM(20))
      IF(surf_tilt_flag(I) == 1.OR.surf_tilt_flag(I).EQ.-1.0D0.OR.surf_tilt_flag(I) == 5) THEN
         OUTLYNE = "ABOUT TO CHECK PIVDEC"
         CALL SHOWIT(19)
         IF(surf_pivot_flag(I).EQ.1.0D0) CALL PIVDEC(I)
         OUTLYNE = "JUST FINISHED PIVDEC CHECK"
         CALL SHOWIT(19)
      END IF
   END DO
   ERCODE=.FALSE.
   TRYES=.FALSE.
!     THIS CALL FINDS ILLEGAL TILT RETS AND TILT AUTOS WHICH PRECEED
!     TILT RETS AND FIXES THEM
   CALL TILT_RETURN(ERCODE,TRYES)
   IF(ERCODE) THEN
      OUTLYNE = "ERCODE IS TRUE in LNSEOS1"
      CALL SHOWIT(19)
!     THERE WERE ERRORS RESOLVING TILT RETURN, CALL MACFAL
!     AND SET ERCODE TO .FALSE.
      ERCODE=.FALSE.
!     STOP A MACRO IF ONE IS RUNNING, THEN PROCEED
      CALL MACFAL
   END IF
   IF(TRYES) THEN
!     RESOLVE TILT RETURNS INTO TILTS AND DECENTER VALUES
!     ON SURFACES
!
      CALL RETRES
      OUTLYNE = "RETRES ROUTINE FINISHED "
      CALL SHOWIT(19)
!
   END IF
!     FORCE IMAGE SURFACE TO HAVE ZERO THICKNESS
!       CHECK FOR LAST SURFACE THICKNESS NOT ZERO
!     THE FINAL SURFACE ALWAYS HAS ZERO THICKNESS
   ! JN:  test violating this
!       IF(surf_thickness(INT(SYSTEM(20))).NE.0.0D0) THEN
!       surf_thickness(INT(SYSTEM(20)))=0.0D0
!         OUTLYNE=
!      1  'WARNING: FINAL SURFACE THICKNESS WAS RESET TO ZERO'
!       CALL SHOWIT(1)
!                         END IF
   DO I=1,INT(SYSTEM(20))
      call set_surf_decenter_flag(I, 0)
      IF(surf_decenter_y(I).NE.0.0D0.OR.surf_decenter_x(I).NE.0.0D0.OR.surf_decenter_z(I).NE.0.0D0) call set_surf_decenter_flag(I, 1)
   END DO
   IF(.NOT.REDOLNSEOS) THEN
      IF(SYSTEM(94).NE.0.0D0.OR.SYSTEM(98).NE.0.0D0) THEN
         CALL REDOXOBJ(REDOLNSEOS)
         OUTLYNE = "REDOXOBJ FINISHED"
         CALL SHOWIT(19)
      END IF
      IF(SYSTEM(95).NE.0.0D0.OR.SYSTEM(99).NE.0.0D0) THEN
         CALL REDOYOBJ(REDOLNSEOS)
         OUTLYNE = "REDOYOBJ FINISHED"
         CALL SHOWIT(19)
      END IF
   ELSE
!     DONE
      RETURN
   END IF
   IF(REDOLNSEOS) THEN
      F1=0
      F6=1
      F22=0
      GO TO 999
   END IF
   ! Update the NEW data structures
   call check_clear_apertures(curr_lens_data)
   call curr_asph_data%updateAsphereTable(INT(SYSTEM(20))+1)
   call sysConfig%updateParameters()

   RETURN
END
SUBROUTINE REDOXOBJ(REDOLNSEOS)
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
   REAL*8 A,B,JK_FACTOR
   LOGICAL REDOLNSEOS
!
   JK_FACTOR=1.0D0
   IF(SYSTEM(94).EQ.1.0D0.OR.SYSTEM(98).EQ.1.0D0) THEN
!     IMAGE ANGLES SCALE
      B=PXTRAX(6,INT(SYSTEM(20)))
      IF(B.NE.0.0D0) THEN
         IF(SYSTEM(94).EQ.1.0D0)JK_FACTOR=DTAN(PII*SYSTEM(92)/180.0D0)/B
         IF(SYSTEM(98).EQ.1.0D0)JK_FACTOR=DTAN(PII*SYSTEM(96)/180.0D0)/B
      END IF
   ELSE
!     IMAGE HT SCALE
      B=PXTRAX(5,INT(SYSTEM(20)))
      IF(B.NE.0.0D0) THEN
         IF(SYSTEM(94).EQ.-1.0D0)JK_FACTOR=SYSTEM(92)/B
         IF(SYSTEM(98).EQ.-1.0D0)JK_FACTOR=SYSTEM(96)/B
      END IF
   END IF
!     SET SCX
   SYSTEM(16)=SYSTEM(16)*JK_FACTOR
   SYSTEM(17)=0.0D0
   SYSTEM(19)=0.0D0
   SYSTEM(52)=1.0D0
   SYSTEM(54)=0.0D0
   SYSTEM(61)=1.0D0
   REDOLNSEOS=.TRUE.
   RETURN
END
SUBROUTINE REDOYOBJ(REDOLNSEOS)
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
   REAL*8 A,B,JK_FACTOR
   LOGICAL REDOLNSEOS
!
   JK_FACTOR=1.0D0
   IF(SYSTEM(95).EQ.1.0D0.OR.SYSTEM(99).EQ.1.0D0) THEN
!     IMAGE ANGLES SCALE
      B=PXTRAY(6,INT(SYSTEM(20)))
      IF(B.NE.0.0D0) THEN
         IF(SYSTEM(95).EQ.1.0D0)JK_FACTOR=DTAN(PII*SYSTEM(93)/180.0D0)/B
         IF(SYSTEM(99).EQ.1.0D0)JK_FACTOR=DTAN(PII*SYSTEM(97)/180.0D0)/B
      END IF
   ELSE
!     IMAGE HT SCALE
      B=PXTRAY(5,INT(SYSTEM(20)))
      IF(B.NE.0.0D0) THEN
         IF(SYSTEM(95).EQ.-1.0D0)JK_FACTOR=SYSTEM(93)/B
         IF(SYSTEM(99).EQ.-1.0D0)JK_FACTOR=SYSTEM(97)/B
      END IF
   END IF
!     SET SCY
   SYSTEM(14)=SYSTEM(14)*JK_FACTOR
   SYSTEM(15)=0.0D0
   SYSTEM(18)=0.0D0
   SYSTEM(51)=1.0D0
   SYSTEM(53)=0.0D0
   SYSTEM(60)=1.0D0
   REDOLNSEOS=.TRUE.
   RETURN
END
SUBROUTINE RERROR
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
   INTEGER I
   DO I=1,INT(SYSTEM(20))
      IF(surf_ray_error(I).NE.0.0D0) THEN
         WRITE(OUTLYNE,10) surf_ray_error(I),I
         CALL SHOWIT(0)
10       FORMAT('RAYERROR = ',G23.15,' FOR SURFACE # ',I3)
      END IF
   END DO
END
