! Goal of this routine is to provide print statements of tons of
! Variables to facilitate debugging
subroutine megaDebugLogger(subName)


   USE GLOBALS
!
   use DATSPD
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_asphere_coeff
   IMPLICIT NONE

   character(len=*), intent(in) :: subName
   CHARACTER(LEN=*), PARAMETER  :: FMTFLAGS =&
   &"(A12,I2,I2,I2,I2,I2,I2,I2,I2,I2,I2,I2,I2,I2,I2,I2,I2,&
   &  I2,I2,I2,I2)"
   CHARACTER(LEN=*), PARAMETER  :: FMTCMDS = "(A12, A9,A9,A9)"
   CHARACTER(LEN=*), PARAMETER  :: FMTW =&
   &"(A12, G15.7,G15.7,G15.7,G15.7,G15.7)"


   INTEGER IISURF,FFT,FFS,I,J,ICNT,ICNTEST
!
   CHARACTER LUNI*3
!
   REAL*8 XPFOB,YPFOB
   COMMON/PFOB/XPFOB,YPFOB,LUNI
!
   REAL*8 FT,FS,X00,Y00,Z0 &
   &,LAMBDA,ANGLE1,XK,YK,XLN,XMN,XNN,XFOBB0,YFOBB0,ZFOBB0 &
   &,ANGJK1,ANGJK2,XXANG,YYANG,FACTER,XA,YA,ZA,XJIM,YJIM,ZJIM &
   &,ZSAG,ANGLE2,SCLFACY,SCLFACX,AWW1,AWW2
!
   REAL*8 XRAYER,YRAYER,ZRAYER
   COMMON/RAYERPASS/XRAYER,YRAYER,ZRAYER
!
   COMMON/OHFOB/XFOBB0,YFOBB0,ZFOBB0
!
   LOGICAL FANEXT,ZEEERR,SAGERR
   COMMON/ERRZEE/ZEEERR
!
   COMMON/FANEXI/FANEXT
!
!       FOBB0=TRUE FOR ON AXIS AND FALSE FOR OFF AXIS
   LOGICAL FOBB0,FOBB0X,FOBB0Y
!
   COMMON/FFOOBB/FOBB0,FOBB0X,FOBB0Y
!
   COMMON/FBDIFF/FS,FT,FFS,FFT
!


   PRINT FMTFLAGS, subName, F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,&
   &F15,F16,F17,F18,F19,F20

   PRINT *, "WC, WQ, WS"
   PRINT FMTCMDS, subName, WC, WQ, WS

   PRINT *, "W1-W5"
   PRINT FMTW, subName, W1, W2, W3, W4, W5

1234 FORMAT(G15.7, G15.7, G15.7, G15.7, G15.7,&
   &G15.7, G15.7, G15.7, G15.7, G15.7)
   PRINT 1234, surf_asphere_coeff(I,2), surf_asphere_coeff(I,4), surf_asphere_coeff(I,6),&
   &surf_asphere_coeff(I,8),surf_asphere_coeff(I,10),surf_asphere_coeff(I,12),surf_asphere_coeff(I,14),&
   &surf_asphere_coeff(I,16),surf_asphere_coeff(I,18),surf_asphere_coeff(I,20)

!     LATEST STUFF
!
!        CHARACTER WC*8,WQ*8,WS*80
!
!        COMMON/CNTLCH/WC,WQ,WS
!
!        INTEGER SB1,SB2,SC1,SC2,SQ,SST,S1,S2,S3,S4,S5,
!     1  DF1,DF2,DF3,DF4,DF5,SN,STI
!
!        REAL*8 W1,W2,W3,W4,W5
!



end subroutine

subroutine PRINTNEUTARRAY()

   USE GLOBALS
   use DATHGR
   IMPLICIT NONE


   INTEGER :: J, I1,I2,I3,I4,I5,I6,I7,I8
   REAL :: RRR1, RRR2
   CHARACTER(len=1) :: STRINGER
   CHARACTER(len=20) :: C1A,C1B,C1C,C1D

   PRINT *, "PRINTING OUT CURRENT STATE OF NEUTARRAY"
   PRINT *, "NEUTTOTAL IS ", NEUTTOTAL
   J=2
   DO WHILE (J<NEUTTOTAL)
      !PRINT *,"J=",J

      READ(NEUTARRAY(J),2000) STRINGER,I1,I2,I3,I4,I5,I6,I7,I8


2000  FORMAT(A1,I5,I5,I5,I5,I5,I5,I5,I5)

      WRITE(*,2000) STRINGER,I1,I2,I3,I4,I5,I6,I7,I8

      IF(STRINGER.EQ.'F') THEN
         !     SETTING THE CHARACTER ASPECT
         J=J+1
3000     FORMAT(E15.7,E15.7,11X)
         READ(NEUTARRAY(J),3000) RRR1,RRR2
         WRITE(*,3000) RRR1, RRR2
      END IF


      IF(STRINGER.EQ.'D') THEN

!     PLOTTING A STRING
         J=J+1
1003     FORMAT(A20,22X)
         READ(NEUTARRAY(J),1003)C1A
         J=J+1
         READ(NEUTARRAY(J),1003)C1B
         J=J+1
         READ(NEUTARRAY(J),1003)C1C
         J=J+1
         READ(NEUTARRAY(J),1003)C1D
         PRINT *, C1A//C1B//C1C//C1D
      END IF

      J = J+1
   END DO


end subroutine
