module DATLEN

!
!       RDM TRUE IS RADIUS MODE FOR GUI
!       RDM FALSE IS CURVATURE MODE FOR GUI
    
    LOGICAL RDM
    COMMON/MDR/RDM
!
!     DON'T FORGET ABOUT ALENA WHEN CHANGING LENS DATA SIZES
!       VARIABLES FOR SPSRF FITTING
!       THIS SETS THE MAXIMUM NUMBER OF DATA PAIRS WHICH
!       MAY BE FIT. SET NOW AT 2000
!       MAXSPS IS SET TO 2000 IN PROGRAM.FOR
!
!       NOTE:
!       NMAX, THE VALUE FOR DIM OF TMP SVD ROUTINES SHOULD BE
!       CHANGED TO MATCH THE VALUE OF MAXSPS SET IN PROGRAM.FOR
!       NMAX IS THE NUMBER OF DATA POINTS WHICH MAY BE FIT.

!      PRINCIPLE PLANE DATA CALCULATED WITH THE LAST FIRD COMMAND
    REAL*8 PPY1,PPY2,PPX1,PPX2
    COMMON/PPLANES/PPY1,PPY2,PPX1,PPX2
!
    CHARACTER IDTAG(1:10)*75
    COMMON/TAGID/IDTAG
    REAL*8 DDATA(1:4,1:2000),CFTYPE(1:96)
    COMMON/SPDATA/DDATA
    COMMON/CFTYP/CFTYPE
    INTEGER MAXSPS
    COMMON/MXSPS/MAXSPS
!
!       SPOT DIAGRAM AND CAPFN EXISTENCE FLAGS
!
    LOGICAL GSPDEXT,SPDEXT,CPFNEXT,PSFEXT

    COMMON/SPDYES/GSPDEXT,SPDEXT,CPFNEXT,PSFEXT

!     TIME AND DATE STAMPING ADDED 5/25/95 AT GOLDYS REQUEST
  LOGICAL STMPT,STMPD
  COMMON/STAMPIT/STMPT,STMPD

!       COEFFICIENT FLAGS FOR SPECIAL SURFACES

    INTEGER CFF(1:96),LNSTYP

  COMMON/ENDER/LNSTYP

    COMMON/CCOEF/CFF

!       SET FOR 500 SURFACE LENSES
!       VARIABLES FOR THE CURRENT LENS
    CHARACTER LI*80,LIC(1:4)*80,INNI*80,LLTYPE*80,                  &
 &GLANAM(0:499,1:2)*13,LBL(0:499)*80,PLBL(0:499)*80
  INTEGER LICCNT,NEWOBJ,NEWREF,NEWIMG                               &
 &  ,OLDOBJ,OLDREF,OLDIMG,MAXSUR,FLCHG(0:499),SSIZ,LSIZ,PSIZ
!       LSIZ IS NUMBER OF PARAMETERS PER LENS SURFACE
!       SSIZ IS NUMBER OF PARAMETERS IN SYSTEM
!       PSIZ IS NUMBER OF PARAMETERS PER LENS PIKUP

  INTEGER RAYSIZ,CFLDCNT,AFLDCNT,PFLDCNT,CFLDTYPE,PFLDTYPE          &
 &,AFLDTYPE,AFLDTYPECF,DIFSIZ,AFLDCNTCF,BFLDCNT,BFLDTYPE            &
 &,BFLDTYPECF,BFLDCNTCF

    COMMON/FLCH/FLCHG

    COMMON/MXSUR/MAXSUR

!     EULER TRUE OR FALSE SETS THE PROGRAM SURFACE ANGLES MODE TO
!     EITHER "EULER" OR "RIGHT" OR TO "MIXED" MODE. "MIXED" IS THE DEFAULT
!     SET IN PROGRAM.FOR AT START UP. fLAG IS PASSED BY COMMON MANED "OILY"
    LOGICAL EULER
    COMMON/OILY/EULER

!       SSIZ IS THE SIZE OF THE SYSTEM ARRAYS AND LSIZ IS THE
!       NUMBER OF PARAMETERS PER SURFACE IN THE LENS ARRAYS
!       PSIZ IS THE NUMBER OF THINGS IN THE PIKUP ARRAY
!       RAYSIZ IS THE NUMBER OF RAY PARAMETERS STORED
!       DIFSIZ IS THE NUMBER OF DIFF RAY PARAMETERS STORED
    COMMON/SYSSIZ/SSIZ,LSIZ,PSIZ,RAYSIZ,DIFSIZ
!
    REAL*8 SYSTEM(1:150),CFLDS(1:2,1:10),PFLDS(1:2,1:10),           &
 &  ALENS(1:160,0:499),SOLVE(0:9,0:499),PIKUP(1:6,0:499,1:45),      &
 &  FTFL01(1:96,0:499),AFLDS(1:2,1:10),MULTCLAP(1:1000,1:3,0:499)   &
 &  ,MULTCLAPP(1:1000,1:3,0:499),MULTCOBS(1:1000,1:3,0:499),        &
 &  MULTCOBSP(1:1000,1:3,0:499),AFLDSCF(1:2,1:10)                   &
 &,BFLDS(1:2,1:10),BFLDSCF(1:2,1:10)                                &
 &,IPOLYX(1:200,0:499,1:4),IPOLYY(1:200,0:499,1:4)
    COMMON/MULTICLAP/MULTCLAP,MULTCLAPP
    COMMON/MULTICOBS/MULTCOBS,MULTCOBSP
    COMMON/FIELDING/PFLDS,CFLDS,AFLDS,PFLDCNT,CFLDCNT,AFLDCNT,      &
 &PFLDTYPE,CFLDTYPE,AFLDTYPE,AFLDTYPECF,AFLDSCF,AFLDCNTCF           &
 &,BFLDS,BFLDCNT,BFLDTYPE,BFLDTYPECF,BFLDSCF,BFLDCNTCF
    COMMON/SPFT/FTFL01
    COMMON/SLV/SOLVE
    COMMON/PIK/PIKUP
  COMMON/LLABL/LBL
    COMMON/GLNAME/GLANAM
    COMMON/LTITLE/LI,LIC,INNI,LLTYPE
    COMMON/CTITLE/LICCNT
    COMMON/LENS1/SYSTEM,ALENS
    COMMON/LENS2/IPOLYX,IPOLYY
    COMMON/NNWW55/NEWOBJ,NEWREF,NEWIMG,OLDOBJ,OLDREF,OLDIMG

!       VARIABLES FOR THE PERMANENT LENS USED TO FORM CFGS
    CHARACTER LICP(1:4)*80,LIP*80,GLANMP(0:499,1:2)*13,INNIP*80     &
 &,LLTYPEP*80
    REAL*8 SYSP(1:150),ALENP(1:160,0:499),PIPOLYX(1:200,0:499,1:4), &
 &  SLVP(0:9,0:499),PIKP(1:6,0:499,1:45),FT01P(1:96,0:499),         &
 &  PIPOLYY(1:200,0:499,1:4)

  REAL*8 INR
  COMMON/INRPHAS/INR

    COMMON/PLENS/SYSP,ALENP,SLVP,PIKP,FT01P
    COMMON/PLENS2/PIPOLYX,PIPOLYY

    COMMON/CPLENS/GLANMP,LIP,LICP,INNIP,LLTYPEP

  COMMON/PLLABL/PLBL

!       VARIABLES FOR PARAXIAL AND 357 DATA
!       COLX AND COLY ARE COLOR PARAX TRACES WITHOUT SOLVE
!       OR PIKUP RESOLUTION AND ARE USED IN CALCULATING
!       3,5,7 CHROMATIC DIFFERENCES

    REAL*8 MAB3(1:11,0:499),PXTRAY(1:8,0:499),                      &
 &  PXTRAX(1:8,0:499),COLORX(1:8,0:499),COLORY(1:8,0:499)           &
 &  ,SAB57(1:20,0:499),MAB57(1:20,0:499),XMAB3(1:11,0:499)          &
 &  ,XMAB57(1:20,0:499),XSAB57(1:20,0:499)                          &
 &  ,O_PXTRAY(1:8,0:499),O_PXTRAX(1:8,0:499)

    REAL*8 COLY(1:8,0:499),COLX(1:8,0:499)

!       CHROMATIC 357 CONTRIBUTIONS

    REAL*8 PDF3(1:10,0:499),PDF57(1:20,0:499),                      &
 &  SDF3(1:10,0:499),SDF57(1:20,0:499),                             &
 &  XPDF3(1:10,0:499),XPDF57(1:20,0:499),                           &
 &  XSDF3(1:10,0:499),XSDF57(1:20,0:499)

!     FIRST DIMENSION IS FOV NUMBER ,NO 1, NO2 AND NO3.
!     SECOND DIMENSION IS THE ITEM NUMBER
!     THIRD DIMENSION DESIGNATES TYPE OF DATA STORED
!     WHICH VARIES FOR EACH TYPE OF PLOT
!     FOURTH DIMENSION IS WAVELENGTH NUMBER 1 TO 10

  REAL*8 FFAANN(1:3,1:21,1:6,1:10),                                 &
 &ABSIS,DRAX(1:21),DRAY(1:21)                                       &
 &,STEPJP

    COMMON/CR1/MAB3,MAB57,SAB57,XMAB3,XMAB57,XSAB57,COLORY,COLORX   &
 &  ,COLY,COLX,PDF3,PDF57,SDF3,SDF57,XPDF3,XPDF57,XSDF3,XSDF57      &
 &  ,FFAANN,ABSIS,DRAX,DRAY,STEPJP

    COMMON/PARAX_IAL/PXTRAY,PXTRAX,O_PXTRAY,O_PXTRAX

!       REAL RAY TRACE VARIABLES

!       FOBYES IS A FLAG SET WHEN A FOB IS ISSUED
!       IT IS PASSED VIA
!       THE COMMON/YESFOB/FOBYES

!       LAST FOB DATA (USED FOR TRACING WHEN REF RAY FAILS AND NULL
!       IS TRUE)
!       CHLFOB HOLDS THE LAST QUALIFIER USED WITH THE LAST FOB
    CHARACTER CHLFOB*8
    COMMON/CHL/CHLFOB
!       LFOB(1:7) HOLDS THE LAST NUMERIC DATA USED WITH THE LAST FOB
    REAL*8 LFOB(1:7),LFOBA(1:3)
    COMMON/LFFOB/LFOB,LFOBA
!       1=NW1
!       2=NW2
!       3=NW3
!       4=NW4
!       5=DBLE(NEWOBJ)
!       6=DBLE(NEWREF)
!       7=DBLE(NEWIMG)
!       LFOBA(1:3) HOLDS THE LAST NUMERIC DATA USED WITH THE LAST FOBA
!       1=NW1
!       2=NW2
!       3=NW3
!
    LOGICAL FOBYES,REVSTR
!     REVSTR IS TRUE IF ALENS(NEWOBJ) IS NEG AND IS USED TO ADJUST
!     SIGNS IN OPD CALCS
    COMMON/REVST/REVSTR
    COMMON/YESFOB/FOBYES

    REAL*8 SAVE(1:50,0:499),DIFF(1:18,0:499),                       &
 &  RFDIFF(1:18,0:499),REFRY(1:50,0:499),RAYRAY(1:50,0:499),        &
 &  DELX,DELY,RFDELX,RFDELY,RELX,RELY,CURLAM,OLREFRY(1:50,0:499)    &
 &  ,OLRFDIFF(1:18,0:499),H_RAY(1:50,0:499)

    REAL*8 GPXY(1:4,0:499)
    COMMON/PXYG/GPXY

    REAL*8 QRAY(1:9,0:499)

!     QRAY IS USED IN QUICK RAY TRACING FOR THE FOOTPRINT
!     OPTION
    COMMON/KURLAM/CURLAM
    COMMON/SV/SAVE
    COMMON/DDIIFF/DIFF,DELX,DELY
    COMMON/RRIIFF/RFDIFF,RFDELX,RFDELY,OLRFDIFF
    COMMON/REFR/REFRY,OLREFRY
    COMMON/RAYCMN/RAYRAY,RELX,RELY,QRAY,H_RAY

!       LDIF TRUE MAKES DIFFERENTIAL RAYS TRACE, LDIF FALSE KEEPS
!       THEM FROM BEING TRACED. THE LDIF IS CONTROLED BY THE
!       "DIFRAY" COMMAND FROM THE CMD LEVEL. THE PROGRAM STARTS WITH
!       LDIF = .TRUE., SET IN PROGRAM.FOR

!       LDIF2 TRUE MAKES DIFFERENTIAL REF RAYS TRACE, LDIF2 FALSE KEEPS
!       THEM FROM BEING TRACED. THE LDIF2 IS CONTROLED BY THE
!       "DIFFOB" COMMAND FROM THE CMD LEVEL. THE PROGRAM STARTS WITH
!       LDIF2 = .TRUE., SET IN PROGRAM.FOR

!       LVIG TRUE MAKES VIGNETTING OPTIONAL COMMANDS USE VIGNETTING
!       LVIG = .TRUE., SET IN PROGRAM.FOR

!       NOVIRT TRUE TURNS OFF VIRTUAL RAY PLOTTING AND IS THE PROGRAM DEFAULT
!       NOVIRT = .TRUE., SET IN PROGRAM.FOR

    LOGICAL LDIF,OLDIF,LDIF2,NOVIRT,LVIG,OLDIF2,OPDIF

    COMMON/LDFLDF/LDIF,OLDIF,LDIF2,NOVIRT,LVIG,OLDIF2,OPDIF

    REAL*8 OFFX,OFFY,OFFZ,OFFA,OFFB,OFFC
    INTEGER GLSURF
    LOGICAL GLOBE
    COMMON/GLOBL1/GLOBE
    COMMON/GLOBL2/OFFX,OFFY,OFFZ,OFFA,OFFB,OFFC,GLSURF

    REAL*8 OOFFX,OOFFY,OOFFZ,OOFFA,OOFFB,OOFFC
    INTEGER OLSURF
    LOGICAL OGLOBE
    COMMON/OLOBL1/OGLOBE
    COMMON/OLOBL2/OOFFX,OOFFY,OOFFZ,OOFFA,OOFFB,OOFFC,OLSURF

!       VERTEX HAS GLOBAL VERTEX DATA STORED AND
!       GLRAY HAS X,Y,Z,L,M,N,LP,MP,NP,LN,MN,MM DATA FOR CURRENT RAY
!       IN GLOBAL REPRESENTATION
    REAL*8 VERTEX(1:12,0:499),GLRAY(1:12,0:499)
    COMMON/VERT/VERTEX,GLRAY
!
!       DATA FOR RAY PLOTTING (3/27/92)
!       VERTEX HAS GLOBAL VERTEX DATA STORED AND

!       DATA FOR RAY PLOTTING (3/27/92)
!       VERTEX HAS GLOBAL VERTEX DATA STORED AND
!       GLBRAY HAS X,Y,Z,L,M,N,LP,MP,NP DATA FOR CURRENT RAY
!       IN GLOBAL REPRESENTATION FOR PLOTTING

  REAL*8 GLPRAY(1:9,0:499),PGLPRAY(1:12,0:499)

  COMMON/GLPL/GLPRAY,PGLPRAY

  LOGICAL GLVIRT(0:499)

  COMMON/GLPLVT/GLVIRT

    LOGICAL PLTRAY

    COMMON/PLRAYY/PLTRAY

    LOGICAL DUM(0:499)

    COMMON/DUMREV/DUM

  LOGICAL DUMMMY(0:499)

  COMMON/DUMMMM/DUMMMY

  INTEGER SURF

  COMMON/SURCNT/SURF

!     RAYTRACE VARIABLES PASSED WITH TH1S INCLUDE


    COMMON/RAYC/RAYCOD

    REAL*8 DINFAC,ONTOL,SINGTOL                                     &
 &  ,DINMUL,PFAC,SAGDEL,LINTOL,                                     &
 &  SURTOL,AIMTOL,SERINC,SERLIM,CAIMTOL,                            &
 &  DIFTOL,DELSUR,PFACA,PFACM,NMFTOL,IPFTOL

    LOGICAL REFEXT,NULL,FAIL,RAYEXT,GPRAYEXT

    COMMON/RFEXIT/REFEXT,NULL

    COMMON/RYEXIT/RAYEXT,FAIL

    COMMON/GPRYEXIT/GPRAYEXT

    INTEGER RAYCOD(1:2),REFITR,MRAYS                                &
 &  ,NRAITR,HHHOPD,FLOOD,ASIAD,ASITD,NMIT,IPIT

   COMMON/OPCON1/SURTOL,AIMTOL,PFAC,DINMUL,                         &
 & DIFTOL,DELSUR,DINFAC,SAGDEL,MRAYS,CAIMTOL                        &
 &,PFACA,PFACM,NMIT,IPIT,NMFTOL,IPFTOL,SERINC,SERLIM                &
 &,ONTOL,SINGTOL,LINTOL

    COMMON/OPCON2/                                                  &
 &  NRAITR,HHHOPD,FLOOD,ASIAD,ASITD,REFITR

!       THIS IS THE PLOTTING INCLUDE FILE STUFF
!
    CHARACTER PPLI*80
!
    COMMON/PPLLII/PPLI
!
    LOGICAL DASHH
!
    LOGICAL PLTLBL,PLTLLI,DRALOK,DRAVUE,LOKFLG,VUEFLG,VIGFLG
!
  COMMON/DLK/DRALOK,DRAVUE,LOKFLG,VUEFLG,VIGFLG
!
  COMMON/PLOLLI/PLTLLI,PLTLBL
!
  INTEGER LBLSURF
!
  COMMON/SURFLBL/LBLSURF
!
    COMMON/DDASHH/DASHH
!
    INTEGER DEVTYP,LNTYPE,SYMB,ORX,ORY,PENSTA                       &
 &  ,YPEN,XPEN,YPENOL,XPENOL,OLLNTP
!
    COMMON/LNTP/LNTYPE,OLLNTP

    REAL*8 SCFAY,SCFAX,PSIZY,PSIZX                                  &
 &  ,SCFAYP,SCFAXP,PSIZYP,PSIZXP

    REAL*8 LOOKY,LOOKX,LOOKZ,VIEALF,VIEPHI

    COMMON/LOOKER/LOOKY,LOOKX,LOOKZ,VIEALF,VIEPHI

    COMMON/PORIGN/ORX,ORY

    COMMON/PLSCL/SCFAY,SCFAX,PSIZY,PSIZX                            &
 &  ,SCFAYP,SCFAXP,PSIZYP,PSIZXP

    LOGICAL GRASET,PLEXIS,PLTAXS,AUTSL,PLSC,PLSZ                    &
 &,SCFLG,SZFLG,DRASCL,DRASZZ,PLTVIG,DXFSET,DXFEXIS

  CHARACTER LAYER*8
  COMMON/DXFLAYERVAL/LAYER

    COMMON/PENPEN/PENSTA,YPEN,XPEN,YPENOL,XPENOL

    COMMON/GRAPH/GRASET,PLEXIS,PLTAXS,AUTSL,PLSC,PLSZ               &
 &,SCFLG,SZFLG,DRASCL,DRASZZ,PLTVIG,DXFSET,DXFEXIS

    COMMON/DVTYPE/DEVTYP

    INTEGER NTSIZ,SYMSIZ,LABSIZ

    INTEGER NTANG,SYMANG,LABANG

    COMMON/LABLEL/LABSIZ,LABANG

    COMMON/NNOTEE/NTSIZ,NTANG

    COMMON/SIMBOL/SYMB,SYMSIZ,SYMANG

!     RIGHT,CENTER AND LEFT PLOT JUSTIFICATION FLAG FOR PLOTS
!     OF THE LENS DATA

!     RCL=1 MEANS LEFT JUSTIFY
!     RCL=2 MEANS CENTER JUSTIFY (DEFAULT)
!     RCL=3 MEANS RIGHT JUSTIFY
!     JUSOFF IS THE DEVICE COORDINATE X-OFFSET TO BE USED.
!     THE DEFAULT IS ALWAYS 0 AND IT IS ALWAYS CALCULATED ONCE
!     FOR EACH PLOT WHEREIN IT HAS MEANING.

  INTEGER RCL
  REAL*8 JUSOFF
  COMMON/JUSRCL/JUSOFF,RCL

!     NOW THE FLAGS TO TRACK IF THINGS HAVE BEEN DONE ONCE

!     FLAG TO SEE IF "LBL" HAS BEEN PLOTTED
!     BY DEFAULT SET TO FALSE
!                LBLFLG=.FALSE.

!     FLAG TO SEE IF "LI" HAS BEEN PLOTTED
!     BY DEFAULT SET TO FALSE
!                LIFLG=.FALSE.

!     FLAG TO SEE IF "AXIS" HAS BEEN PLOTTED
!     BY DEFAULT SET TO FALSE
!                AXFLG=.FALSE.

!     FLAG TO SEE IF "LABLE" HAS BEEN PLOTTED
!     BY DEFAULT SET TO FALSE
!                LBLFLG=.FALSE.

!     FLAG TO SEE IF AN AUTO-SCALE FACTOR HAS BEEN CALCULATED
!     BY DEFAULT SET TO FALSE
!                ASCFLG=.FALSE.

  LOGICAL LIFLG,AXFLG,LBLFLG,ASCFLG

  COMMON/PLTDUN/LIFLG,LBLFLG,AXFLG,ASCFLG

!     LAST STARTING AND ENDING SURFACE FOR LENS PLOTS ARE
!     STASUR AND STPSUR

  INTEGER STASUR,STPSUR

  COMMON/STASTP/STASUR,STPSUR

!     SETS CLIPPING VALUES FOR CALLS TO PLOTTO
  INTEGER XXMIN,XXMAX,YYMIN,YYMAX
  COMMON/BONDRY/XXMIN,XXMAX,YYMIN,YYMAX

  INTEGER SURA,SURB

  COMMON/PROSUR/SURA,SURB

!     CERTER OF ROTATION FOR LOOK/VIEW, HAS IT BEEN SET

  LOGICAL ROTSET

  REAL*8 XROT,YROT,ZROT

  COMMON/RTST/ROTSET

  COMMON/ROTPNT/XROT,YROT,ZROT

!     NEXT LINES DEFINE AND PASS THE ARRAY THAT
!     HOLDS RAY PLOTTING DATA
!     AND EDGE PLOTTING DATA
!     AND CLAP PLOTTING DATA
!     AND PROFILE PLOTTING DATA

!     P1ARAY MOVED TO GLOBALS.FOR AND IS NOW ALLOCATABLE

!     PLOT SHIFTS AND ROTATIONS

  INTEGER PXSHFT,PYSHFT,PGAMMA

  COMMON/SHFTER/PXSHFT,PYSHFT,PGAMMA

!     NOW FAN PLOTTING VARIABLES

  LOGICAL FANWV1,FANWV2,FANWV3,FANWV4,FANWV5,FANCW,SSIFLG           &
 &,FANWV6,FANWV7,FANWV8,FANWV9,FANWV10,FSSIFLG
!
  COMMON/PLTFN/FANWV1,FANWV2,FANWV3,FANWV4,FANWV5,FANCW,SSIFLG      &
 &,FANWV6,FANWV7,FANWV8,FANWV9,FANWV10,FSSIFLG

  REAL*8 FANOFF,YFOB1,YFOB2,YFOB3,                                  &
 & XFOB1,XFOB2,XFOB3,SSI,FSSI

  INTEGER FANTYP,QALTYP,FANNUM,FANNM1,FANNM2,REFWV,FANNOB           &
 &,FANNRF,FANNIM

  COMMON/PLTFN1/FANOFF,YFOB1,YFOB2,YFOB3,XFOB1,                     &
 &XFOB2,XFOB3,SSI,FANTYP,QALTYP,FANNUM,FANNM1,FANNM2                &
 &,FANNOB,FANNRF,FANNIM,REFWV,FSSI

  INTEGER MAXFAN                                                    &
 &,DRAFLG(1:21),DRAFLG2(1:21),NDRAX(1:21),NDRAY(1:21)

    COMMON/PFFAAN/MAXFAN,DRAFLG,DRAFLG2,NDRAX,NDRAY

!     ALL PROGRAM DISPLAY COLORS ARE DONE HERE

  INTEGER COLRAY,COLCLP,COLCOB,COLEDG,COLPRO,COLAXS,COLBAC          &
 &,COLR1,COLR2,COLR3,COLR4,COLR5,COLFRM,COLLBL,COLSPE               &
 &,COLPEN,COLR6,COLR7,COLR8,COLR9,COLR10,COLDEF, COLFILL

  COMMON/COLERS/COLRAY,COLCLP,COLCOB,COLEDG,COLPRO,COLAXS,COLBAC    &
 &,COLR1,COLR2,COLR3,COLR4,COLR5,COLFRM,COLLBL,COLSPE               &
 &,COLPEN,COLR6,COLR7,COLR8,COLR9,COLR10,COLDEF, COLFILL

!     COLRAY IS THE RAY COLOR IN LAYOUTS
!     COLCLP IS THE CLEAR APERTURE COLOR IN LAYOUTS
!     COLCOB IS THE OBSCURATION COLOR IN LAYOUTS
!     COLEDG IS THE EDGE COLOR IN LAYOUTS
!     COLPRO IS THE PROFILE COLOR IN LAYOUTS
!     COLAXS IS THE AXES (BOTTOM OF PLOT) COLOR IN LAYOUTS
!     COLBAC IS THE BACKGROUND COLOR IN ALL PLOTS
!     COLR1 IS THE COLOR FOR WAVELENGTH 1 IN OTHER PLOTS (RIM, MTF ETC)
!     COLR2 IS THE COLOR FOR WAVELENGTH 2 IN OTHER PLOTS (RIM, MTF ETC)
!     COLR3 IS THE COLOR FOR WAVELENGTH 3 IN OTHER PLOTS (RIM, MTF ETC)
!     COLR4 IS THE COLOR FOR WAVELENGTH 4 IN OTHER PLOTS (RIM, MTF ETC)
!     COLR5 IS THE COLOR FOR WAVELENGTH 5 IN OTHER PLOTS (RIM, MTF ETC)
!     COLR6 IS THE COLOR FOR WAVELENGTH 6 IN OTHER PLOTS (RIM, MTF ETC)
!     COLR7 IS THE COLOR FOR WAVELENGTH 7 IN OTHER PLOTS (RIM, MTF ETC)
!     COLR8 IS THE COLOR FOR WAVELENGTH 8 IN OTHER PLOTS (RIM, MTF ETC)
!     COLR9 IS THE COLOR FOR WAVELENGTH 9 IN OTHER PLOTS (RIM, MTF ETC)
!     COLR10 IS THE COLOR FOR WAVELENGTH 10 IN OTHER PLOTS (RIM, MTF ETC)
!     COLFRM IS THE FRAMING COLOR IN ALL PLOTS
!     COLLBL IS THE LABELING COLOR IN ALL PLOTS
!     COLTXT IS THE COLOR IN ALL NON-GRAPHIC TEXT
!     TXTBAC IS THE COLOR OF NON-GRAPHICS BACKGROUND
!     COLSPE IS THE COLOR OF ALL CURVES PLOTTED IN THE SPECTRAL SECTION
!     OF THE PROGRAM
!     COLFILL IS THE COLOR FOR LENSES THAT ARE FILLED IN LENS PLOT

!     NEW COMMONS FOR MARCH 4993
  LOGICAL MSG
  COMMON/RAYMES/MSG
  INTEGER STOPP
  COMMON/RAYSTP/STOPP
  INTEGER ISURI
  COMMON/RAYSUR/ISURI
  CHARACTER WWQ*8
  REAL*8 WW1,WW2,WW3,WW4,WW5
  COMMON/RAYWWQ/WWQ
  COMMON/RAYNWR/WW1,WW2,WW3,WW4,WW5
  REAL*8 WVN
  COMMON/RAYWVN/WVN
  INTEGER CACOCH,FOB0
  COMMON/RFSTUF/CACOCH,FOB0
  LOGICAL RV,POSRAY
  COMMON/RAYREV/RV,POSRAY
  INTEGER R_I,INTERS,SEC
  REAL*8 R_X,R_Y,R_Z,R_L,R_M,R_N,XSTRT,YSTRT,ZSTRT                  &
 &,X1AIM,Y1AIM,Z1AIM,XAIMOL,YAIMOL,ZAIMOL,COSI,COSIP,LN,MN,NN       &
 &,R_XAIM,R_YAIM,R_ZAIM,XOLD,YOLD,ZOLD,OLDL,OLDM,OLDN,              &
 &XXXANG,YYYANG,ZZZANG,YR_L,YR_M,YR_N                               &
 &,YOLDL,YOLDM,YOLDN
  COMMON/R_XYZ/R_X,R_Y,R_Z,R_L,R_M,R_N,X1AIM,Y1AIM,Z1AIM            &
 &,XAIMOL,YAIMOL,ZAIMOL,COSI,COSIP,LN,MN,NN,R_XAIM,R_YAIM,R_ZAIM    &
 &,XOLD,YOLD,ZOLD,OLDL,OLDM,OLDN,R_I,INTERS,SEC,YR_L                &
 &,YR_M,YR_N,YOLDL,YOLDM,YOLDN
  REAL*8 RXL(0:499),RXM(0:499),RXN(0:499)
  REAL*8 RYL(0:499),RYM(0:499),RYN(0:499)
  COMMON/YXVECT/RXL,RXM,RXN,RYL,RYM,RYN


  COMMON/MAIIAM/XSTRT,YSTRT,ZSTRT,YYYANG,XXXANG                     &
 &,ZZZANG

  REAL*8 R_TX,R_TY,R_TZ
  COMMON/BAKK1/R_TX,R_TY,R_TZ

  REAL*8 RCOR,OCOR
  COMMON/PASOPD/RCOR,OCOR

  REAL*8 X0,Y0,XT(1:2000),YT(1:2000)
  INTEGER NP
  COMMON/J_INSIDE/X0,Y0,XT,YT,NP

!     AUTOMATIC EXIT PUPIL CALCULATION FLAG
  LOGICAL EXPAUT
  COMMON/EXITP/EXPAUT

!     REFERENCE SPHERE CENT OF CHIEF FLAG
  INTEGER REFLOC
  LOGICAL CENCEN
!     REFLOC=1 = CHIEF RAY
!     REFLOC=2 = SPOT CENTROID
!     REFLOC=3 = REMOVE TILT
!     REFLOC=4 = REMOVE TILT AND FOCUS
  COMMON/LOCREF/REFLOC,CENCEN

!     COMMON FOR PHASE SURFACES
  REAL*8 PHASE,DELL,DELM,RLRL,RMRM,RNRN,MYX,MYY
  INTEGER MYI,XRLRL,XRMRM,XRNRN,YRLRL,YRMRM,YRNRN

  COMMON/PHASER/PHASE,DELL,DELM,RLRL,RMRM,RNRN,MYX,MYY,MYI          &
 &,XRLRL,XRMRM,XRNRN,YRLRL,YRMRM,YRNRN

!     FFL,BFL AND MAGS BASED ON PARAXIAL OR DIFFERENTIAL TRACE

  REAL*8 RMAGX,RMAGY,RFFLX,RFFLY,RBFLX,RBFLY                        &
 &,MAGXOR,MAGYOR,RFFNX,RFFNY,RBFNX,RBFNY,REFLX,REFLY                &
 &,ENPUDX,ENPUDY,EXPUDX,EXPUDY

  COMMON/FLSCALE/RMAGX,RMAGY,RFFLX,RFFLY,RBFLX,RBFLY,MAGXOR,MAGYOR  &
 &,RFFNX,RFFNY,RBFNX,RBFNY,REFLX,REFLY,ENPUDX,ENPUDY,EXPUDX,EXPUDY

  REAL*8 GLSWV(1:10)

  COMMON/GLWV/GLSWV

!     TRACKS IF WE ARE DOING A LENS RETRIEVAL FROM THE LIBRARY
  LOGICAL LIBGET
  COMMON/GETLIB/LIBGET

!     ENTRANCE AND EXIT PUPIL POSITIONS AND DIAMETERS
  REAL*8 ENPOSX,ENPOSY,ENDIAX,ENDIAY,EXPOSX,EXPOSY                  &
 &,EXDIAX,EXDIAY,ENPUX,ENPUY,ENPUZ,EXPUX,EXPUY,EXPUZ

  COMMON/JAGGER/ENPOSX,ENPOSY,EXPOSX,EXPOSY,ENDIAX,ENDIAY           &
 &,EXDIAX,EXDIAY,ENPUX,ENPUY,ENPUZ,EXPUX,EXPUY,EXPUZ

  REAL*8 R_L0,R_M0,R_N0

  COMMON/DPAHSE/R_L0,R_M0,R_N0

  REAL*8 XAIMER,YAIMER,ZAIMER

  COMMON/AIMIT/XAIMER,YAIMER,ZAIMER

!     REAL RAY VARIABLES FOR TRACE
  LOGICAL NINTY,ANGIN,RVSTART

  COMMON/ANGER/ANGIN,NINTY,RVSTART

  REAL*8 XC,YC,ZC

  COMMON/ZEEEEE/XC,YC,ZC

  REAL*8 TRYX,TRYY,TRYZ

  COMMON/TRYIT/TRYX,TRYY,TRYZ

!       AIMRFDIF AND AIMRYDIF ARE TRUE FOR ITERATIVE
!       DIFFERENTIAL RAY AIMING AND FALSE FOR NO DIFFERENTIAL RAY
!       AIMING. uSED TO SPEED UP OPTIMIZATION

  LOGICAL AIMRFDIF,AIMRYDIF

  COMMON/DIFAIM/AIMRFDIF,AIMRYDIF

  LOGICAL ANAAIM

  COMMON/AIMANA/ANAAIM

  LOGICAL ITRACE

  COMMON/TRACEI/ITRACE

  LOGICAL LORIENT

  INTEGER SORIENT

  COMMON/ANDY/LORIENT,SORIENT

  LOGICAL MTFGRIDS

  COMMON/GRIDMTF/MTFGRIDS

    LOGICAL VIGOFF,VSYM, VIEOVERLAY

    COMMON/OFFVIG/VIGOFF,VSYM,VIEOVERLAY

  INTEGER GRSPT

  COMMON/SPOTGR/GRSPT

!     CMD LEVEL PIVOT POSITIONS FOR STILT AND BTILT COMMANDS
  REAL*8 STILTXP,STILTYP,STILTZP
  REAL*8 BTILTXP,BTILTYP,BTILTZP
  COMMON/STILTPIV/STILTXP,STILTYP,STILTZP
  COMMON/BTILTPIV/BTILTXP,BTILTYP,BTILTZP
  LOGICAL STILTAUTO, BTILTAUTO
  COMMON/AUTOPIV/STILTAUTO,BTILTAUTO

!     THRU-FOCUS VARIABLES FOR TFMOTION COMMAND
  REAL*8 TFDELT,TFTMIN,TFTMAX
  INTEGER TFSURF,TFDIRECTION
  COMMON/TFSTUFF/TFDELT,TFTMIN,TFTMAX,TFSURF,TFDIRECTION
!     REMEMBERS FOB FOR TF CALCS
  REAL*8 TFFOB(1:7)
  COMMON/TFFOBS/TFFOB
!     REMEMBERS FREQ FOR TF CALCS
  REAL*8 TFFREQ
  COMMON/TFFREQS/TFFREQ
  LOGICAL COATSET
  COMMON/SETCOATSET/COATSET

!     ADDED FOR 1/12/99 TO SUPPORT CURVED IMAGE PLANE
!     REPRESENTATIONS

  REAL*8 IPLANE_X ,IPLANE_Y ,IPLANE_Z
  REAL*8 IPLANE_L ,IPLANE_M ,IPLANE_N
  REAL*8 IPLANE_LN,IPLANE_MN,IPLANE_NN
  COMMON/KENNY/IPLANE_X,IPLANE_Y,IPLANE_Z,                          &
 &IPLANE_L,IPLANE_M,IPLANE_N,IPLANE_LN,IPLANE_MN,IPLANE_NN

  LOGICAL CARTMAN
  COMMON/BILLYBEER/CARTMAN

  REAL*8 COS_B_ANG,COS_A_ANG
  COMMON/CARTANG/COS_A_ANG,COS_B_ANG
  REAL*8 NEWX,NEWY,NEWZ
  COMMON/CARTPOS/NEWX,NEWY,NEWZ

  INTEGER ALLONUM
  LOGICAL ALLO
  COMMON/CAPALLO/ALLO,ALLONUM

  LOGICAL SUMMOR
  COMMON/ORSUMM/SUMMOR

  LOGICAL USEOLREF,SAVEREF

  COMMON/OLDDATA/USEOLREF,SAVEREF

!     USED BY SAVERAY, RESTRAY AND CLEARRAY COMMANDS

  REAL*8 OLD_REF,OLD_RAY,OLD_REF_DIF,OLD_RAY_DIF                    &
 &,SLFOB,SLFOBA

  DIMENSION OLD_REF(1:50,0:499),OLD_RAY(1:50,0:499),                &
 &OLD_REF_DIF(1:18,0:499),                                          &
 &OLD_RAY_DIF(1:18,0:499),SLFOB(1:7),SLFOBA(1:3)

  LOGICAL SLDIF,SLDIF2

  COMMON/RAYSAVERAY/OLD_REF,OLD_RAY,OLD_REF_DIF,OLD_RAY_DIF,SLFOB   &
 &,SLFOBA

  LOGICAL SREFEXT,SRAYEXT,SRAYDIFEXT,SREFDIFEXT

  COMMON/RAYSAVEFLAG/SREFEXT,SRAYEXT,SRAYDIFEXT,SREFDIFEXT

  LOGICAL CHRSHIFTEXT
  COMMON/CHRSHIFTER/CHRSHIFTEXT

  LOGICAL NOCOAT
  COMMON/COATNO/NOCOAT

  INTEGER SAGCODE
  COMMON/CODESAG/SAGCODE

!     REAL HOE STUFF

  INTEGER HOE_WAV_NUM
  REAL*8 XHOE,YHOE,ZHOE,L1HOE,M1HOE,N1HOE,L2HOE,M2HOE,N2HOE
  INTEGER HOE_DO_IT,HOECFG1,HOECFG2,BLACK_HOE,WHITE_HOE,            &
 &YELLOW_HOE,BROWN_HOE,VELVET_JONES,HOE_X1,HOE_Y1,HOE_Z1            &
 &,HOE_X2,HOE_Y2,HOE_Z2
  COMMON/BE_A_HOE/XHOE,YHOE,ZHOE,L1HOE,M1HOE,N1HOE                  &
 &,L2HOE,M2HOE,N2HOE,HOE_DO_IT,HOECFG1,HOECFG2                      &
 &,BLACK_HOE,WHITE_HOE,YELLOW_HOE,BROWN_HOE,VELVET_JONES            &
 &,HOE_X1,HOE_Y1,HOE_Z1,HOE_X2,HOE_Y2,HOE_Z2,HOE_WAV_NUM

  LOGICAL RAYCLEAR
  COMMON/CLEARRAY/RAYCLEAR

  REAL*8 POLANGX(0:499),POLANGY(0:499)
  LOGICAL POLEXT
  COMMON/ANGPOL/POLANGX,POLANGY,POLEXT

!       GUI LENS EDITOR SURFACE NUMBER TRACKER

    INTEGER EDIT_SURFACE
    COMMON/SURFACE_EDIT/EDIT_SURFACE


!       TRACK IF THE SPREAD SHEET LENS EDITOR IS OPEN
    LOGICAL EDITOROPEN
    COMMON/OPENEDIT/EDITOROPEN

    CHARACTER*75 MFG,CATNUM
    COMMON/CATNUMMFG/MFG,CATNUM

!       ARRAY TO SUPPORT GLASS CATALOG SURFACE EDIT
    CHARACTER CATARRAY(1:9999)*50,FNDARRAY(1:9999)*27
    COMMON/ARRAYCAT/CATARRAY,FNDARRAY

!       ARRAY TO SUPPORT LIB P GUI
    CHARACTER LIBARRAY(1:999)*80,LFNDARRAY(1:999)*80
    COMMON/ARRAYLIB/LIBARRAY,LFNDARRAY

    LOGICAL REFMISS
    COMMON/REFMISSREF/REFMISS

!       BULK ABSORBTION COEFFICIENT ADDED TO COATINGS ON 12/10/2002
!       see code changes in raytra5.for and raytra6.for

  REAL*8 ABSCOEF(1:10),OLDABSCOEF(1:10)
  COMMON/COEFABS/ABSCOEF,OLDABSCOEF

    REAL*8 GUTRAY(1:50,0:499)
    COMMON/GUTGUT/GUTRAY

!       TRACK IF DIFFERENTIAL TRACING IS GOING ON
    LOGICAL DIFRAY_TRACE,DIFREF_TRACE
    COMMON/RAYREF_DIF/DIFRAY_TRACE,DIFREF_TRACE

!       3/20/2003 REMEMBER LAST NSS RAY COORDINATES BEFORE STRIKING
!       EXIT PORT
    REAL*8 LAST_NSS_R_X,LAST_NSS_R_Y,LAST_NSS_R_Z
    REAL*8 LAST_NSS_R_L,LAST_NSS_R_M,LAST_NSS_R_N
    COMMON/NSS_LASTRAY/LAST_NSS_R_X,LAST_NSS_R_Y,LAST_NSS_R_Z ,     &
 &  LAST_NSS_R_L,LAST_NSS_R_M,LAST_NSS_R_N

    REAL*8 LAST_NSS_OR_X,LAST_NSS_OR_Y,LAST_NSS_OR_Z
    REAL*8 LAST_NSS_OR_L,LAST_NSS_OR_M,LAST_NSS_OR_N
    COMMON/NSS_OLASTRAY/LAST_NSS_OR_X,LAST_NSS_OR_Y,LAST_NSS_OR_Z , &
 &  LAST_NSS_OR_L,LAST_NSS_OR_M,LAST_NSS_OR_N

!       DEFORMABLE MIRROR DATA


  REAL*8 DEFGR1,DEFGR2,DEFGR3,DEFGR4,DEFGR5,DEFGR6                  &
 &,DEFGR7,DEFGR8
  INTEGER ACTNUM
  COMMON/DEFGRS/DEFGR1,DEFGR2,DEFGR3,DEFGR4,DEFGR5,DEFGR6,DEFGR7    &
 &,ACTNUM,DEFGR8

!       TO LET PLOT SCALE KNOW IT IT IS WORKING NSS
    LOGICAL NSSSCALE

!       ARRAY LENS SUPPORT (6/23/2004)
    REAL*8 A_R_X,A_R_Y,A_R_Z,A_R_L,A_R_M,A_R_N,OLDARRAYX,OLDARRAYY
    COMMON/ARRAYLENS/A_R_X,A_R_Y,A_R_Z,A_R_L,A_R_M,A_R_N            &
 &  ,OLDARRAYX,OLDARRAYY


end module