module DATMAI


    !       MAIN PROGRAM INCLUDE FILE
!
!     FIGURE TITLE
    CHARACTER FIGTITLE*80
    COMMON/TITLEFIG/FIGTITLE
!
    LOGICAL APPEND,ALLSET
!
    COMMON/SETALL/ALLSET
!
    COMMON/REEPER/APPEND
!
      CHARACTER INPUT*140,AA*20,BB*8,CNULL*80
      COMMON/JK_CHAR/INPUT,AA,BB,CNULL
!
!     OUTLYNE*140 AND THE COMMON BLOCK REPLWRIT ARE USED TO REPLACE
!     ALL CALLS TO WRITE WITH CALLS TO THE SUBROUTINE SHOWIT.FOR
!     ADDED 12/18/95
    CHARACTER*140 OUTLYNE
    CHARACTER*256 OUTLYNE_LONG
    COMMON/REPLWRIT/OUTLYNE,OUTLYNE_LONG
!
!     CONTROLS THE "SHOW" CMD LEVEL COMMAND
      LOGICAL SHOW,ASHOW
      COMMON/SHOWER/SHOW,ASHOW
!
      LOGICAL HALT2,HT,HALTING
!
    COMMON/HALTT/HT,HALTING
!
      COMMON/HHALTT/HALT2
!
      LOGICAL KILOPT
      COMMON/OPTKIL/KILOPT
!
      CHARACTER(LEN=255) :: LIBMAC, OLIBMAC, LIBLEN
      CHARACTER LIBTRA*255,CURLENS*255,LIBSPO*255                       &
   &  ,LIBGLA*255,LIBAUT*7,LIBPLO*7,MYEDIT*8,DIRLEN*80
!
      COMMON/EDTEDT/MYEDIT
!
      COMMON/FLXCFG/LIBLEN,LIBMAC,LIBTRA,LIBSPO,LIBGLA,LIBAUT         &
   &  ,LIBPLO,DIRLEN,OLIBMAC,CURLENS


!
      LOGICAL HEADIN
!
      COMMON/HDINGS/HEADIN
!
      REAL*8 PII,TWOPII,HALFPII
      REAL RPII,RTWOPII,RHALFPII
!
      COMMON/PPIIEE/PII,TWOPII,HALFPII,RPII,RTWOPII,RHALFPII
!
!     LATEST STUFF
!
      CHARACTER WC*8,WQ*8,WS*80
!
      COMMON/CNTLCH/WC,WQ,WS
!
      INTEGER SB1,SB2,SC1,SC2,SQ,SST,S1,S2,S3,S4,S5,                  &
   &  DF1,DF2,DF3,DF4,DF5,SN,STI
!
      REAL*8 W1,W2,W3,W4,W5
!
      COMMON/CNTLNM/W1,W2,W3,W4,W5,SB1,SB2,SC1,SC2,SQ,SST,            &
   &  S1,S2,S3,S4,S5,DF1,DF2,DF3,DF4,DF5,SN

      INTEGER ECH,IN,OUT,NRECL
!
      INTEGER W1CODE,W2CODE,W3CODE,W4CODE,W5CODE
!
      COMMON/CODEWW/W1CODE,W2CODE,W3CODE,W4CODE,W5CODE
!
      INTEGER                                                         &
   &  F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,F16,         &
   &  F17,F18,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28,F29,F30,        &
   &  F31,F32,F33,F34,F35,F36,F37,F38,F39,F40,F41,F42,F43,F44,        &
   &  F45,F46,F47,F48,F49,F50,F51,F52,F53,F54,F55,F56,F57,F58,F59     &
   &  ,F60,F61,F62,F63,F64,F65,F66,F67,F68,F69                        &
   &  ,F70,F71,F72,F73,F74,F75,F76,F77,F78,F79                        &
   &  ,F80,F81,F82,F83,F84,F85,F86,F87,F88,F89                        &
   &  ,F90,F91,F92,F93,F94,F95,F96,F97,F98,F99,F100

      COMMON/FLAGS/                                                   &
   &  F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,F16,         &
   &  F17,F18,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28,F29,F30,        &
   &  F31,F32,F33,F34,F35,F36,F37,F38,F39,F40,F41,F42,F43,F44,        &
   &  F45,F46,F47,F48,F49                                             &
   &  ,F50,F51,F52,F53,F54,F55,F56,F57,F58,F59                        &
   &  ,F60,F61,F62,F63,F64,F65,F66,F67,F68,F69                        &
   &  ,F70,F71,F72,F73,F74,F75,F76,F77,F78,F79                        &
   &  ,F80,F81,F82,F83,F84,F85,F86,F87,F88,F89                        &
   &  ,F90,F91,F92,F93,F94,F95,F96,F97,F98,F99,F100
!
    COMMON/RECLL/NRECL
!
      COMMON/MAINIO/IN,OUT,ECH

    COMMON/KUERRY/STI
!
!     PREVIOUS STUFF(USED TO REMEMBER PREVIOUS VALUES IN SPECIAL CASES)
!
      CHARACTER P_WC*8,P_WQ*8,P_WS*80
!
      COMMON/PNTLCH/P_WC,P_WQ,P_WS
!
      INTEGER P_SB1,P_SB2,P_SC1,P_SC2,P_SQ,P_SST,P_S1,P_S2,           &
   &  P_S3,P_S4,P_S5,                                                 &
   &  P_DF1,P_DF2,P_DF3,P_DF4,P_DF5,P_SN,P_STI
!
      REAL*8 P_W1,P_W2,P_W3,P_W4,P_W5
!
      COMMON/PNTLNM/P_W1,P_W2,P_W3,P_W4,P_W5,P_SB1,P_SB2,P_SC1,       &
   &  P_SC2,P_SQ,P_SST,                                               &
   &  P_S1,P_S2,P_S3,P_S4,P_S5,P_DF1,P_DF2,P_DF3,P_DF4,P_DF5,P_SN
!
      INTEGER P_ECH,P_IN,P_OUT
!
      COMMON/PAINIO/P_IN,P_OUT,P_ECH
!
      COMMON/PUERRY/P_STI
!
!     REGISTERS BOTH NAMED AND NUMBERED GENERAL PURPOSE
!
      REAL*8 REG(1:50)
!
      COMMON/MEMORY/REG
!
      REAL*8 GPREG(0:100000)
!
      CHARACTER AGPREG(0:100000)*80
!
      COMMON/MEM2/GPREG
!
      COMMON/AMEM2/AGPREG
!
      CHARACTER WFORM*80,LFORM*80
!
      COMMON/WWFOR/WFORM,LFORM
!
!     RADUNITS 1=WATTS, 2=PHOTONS
    INTEGER RADUNI
!
    COMMON/RDUNI/RADUNI
!
    LOGICAL MORANT
!
    COMMON/BREAKER/MORANT
!
!     PARALLEL AND SERIAL PORT NAMES
!
    CHARACTER*4 PARPORT,COMPORT
    COMMON/PORTER/PARPORT,COMPORT
!
    LOGICAL GOOY
    COMMON/LOTAGOO/GOOY
!
!     OUTFILE NAME
    CHARACTER OFILN*80,LASTFIL*80
    COMMON/OOFILNN/OFILN,LASTFIL
    CHARACTER CMDLINE*127
    COMMON/LINECMD/CMDLINE
!
!     TEXT FRONT AND BACK COLORS
    INTEGER IFRONT,IBACK
    COMMON/TEXTCOLORS/IFRONT,IBACK
!
!     THE NEXT VARIABLES ARE USED TO SEE IF THE LAST COMMAND WORD
!     WAS FOB OR NOT TO SUPPORT MULTI FOV IN MTF ANALYSES
!
      CHARACTER LASTCOMWRD*8
!
      LOGICAL LASTWASFOB
!
      COMMON/LASTCOM/LASTCOMWRD,LASTWASFOB

!
!     OPTIMIZATION AUTOMATIC RE-INITIALIZATION
    INTEGER OPTM_INIT
    COMMON/INITOPTIM/OPTM_INIT
!
!     NEAR/FAR FOR OTF CALCS
    INTEGER NEAR_FAR
    COMMON/NEARER/NEAR_FAR
!
!     THESE LINES SUPPORT THE 50 LEVELS OF INPUT SAVE AND RECALL IN KDP
    LOGICAL REST_KDP(1:200)
    COMMON/KDPREST/REST_KDP
    LOGICAL SAVE_KDP(1:200)
    COMMON/KDPSAVE/SAVE_KDP
    LOGICAL RESTINPT
    LOGICAL SAVEINPT
    EXTERNAL RESTINPT
    EXTERNAL SAVEINPT
!
!     MIN/MAX REGISTERS
    REAL*8 MIN_REG(1:100),MAX_REG(1:100)
    COMMON/MINMAX_REG/MIN_REG,MAX_REG
!
    LOGICAL PLOTCAPCON,PLOTPSFCON,PLOTINTENCON
    COMMON/CAPCON/PLOTCAPCON,PLOTPSFCON,PLOTINTENCON
!
!     VARIABLES USED IN PENMV1.FOR
    LOGICAL FIXUP
    COMMON/UPFIX/FIXUP
!     3-D LINE PLOTTING VARIABLES (9/4/2001)
    REAL*8 LX1,LX2,LY1,LY2,LZ1,LZ2
    COMMON/THREEDEELINE/LX1,LX2,LY1,LY2,LZ1,LZ2
    LOGICAL NORAYPLOT
    COMMON/TDRAY/NORAYPLOT
    LOGICAL MACFAILURE
    COMMON/FAILMAC/MACFAILURE
!
!       USER VECTOR OPERATIONS
      DOUBLE PRECISION AXVEC,AYVEC,AZVEC,BXVEC,BYVEC,BZVEC
      DOUBLE PRECISION CXVEC,CYVEC,CZVEC
      COMMON/VEC/AXVEC,AYVEC,AZVEC,BXVEC,BYVEC,BZVEC                  &
   &  ,CXVEC,CYVEC,CZVEC
!
      LOGICAL ALLSTOP
      COMMON/STOPPER/ALLSTOP
!
      LOGICAL GUIERROR
      COMMON/ERRORGUI/GUIERROR
end module