module DATSP1
   use iso_fortran_env, only: real64

!     VARIABLES FOR DSPOTT USAGE IN SPOTIT.FOR ADDED 6/99
    INTEGER ID,NDSPOTT
    COMMON/SPOTTER/ID,NDSPOTT
!     END OF WORK ON SPOTIT.FOR
!
    real(real64) DSPOT(1:60),RINGRAD(0:50),RINGANG(0:50)                    &
  &,RINGTOT,RNUMBR
!
    LOGICAL APODGAUSS
    real(real64) APODDBLOSS
    COMMON/APODLOSS/APODGAUSS,APODDBLOSS
!
    real(real64) FCSFT,FCSFTX,FCSFTY
!
    LOGICAL STATSP
!
    COMMON/FULSTA/STATSP
!
    COMMON/FCSHFT/FCSFT,FCSFTX,FCSFTY
!
    real(real64) OPRINGRAD(0:50),OPRINGANG(0:50)                            &
  &,OPRINGTOT,OPRNUMBR
!
    INTEGER OPRINGPNT(0:2500),OPSPDTYPE,OPNRECT
!
    INTEGER RINGPNT(0:2500),SPDTYPE,NRECT
!
    COMMON/RINGER/RINGRAD,RINGANG,RINGPNT,RINGTOT,RNUMBR              &
  &,SPDTYPE,NRECT,OPSPDTYPE,                                          &
  &OPRINGRAD,OPRINGANG,OPRINGPNT,OPRINGTOT,OPRNUMBR,                  &
  &OPNRECT

    COMMON/CR2/DSPOT

    LOGICAL LSF

    COMMON/LSFTF/LSF

    INTEGER ITOT

    real(real64) DDEELL

    COMMON/TTTOT/ITOT,DDEELL

end module DATSP1
