module DATSPD
   use iso_fortran_env, only: real64

    !       SPOT DIAGRAM COMMONS
!
!       SPOT DIAGRAM STORAGE
    real(real64)                                                          &
    &  SPA,SPB,SPC,SPD,AFSPB,AFSPD,SSSP,SSSQ,SSSR,LA,LB,LC,LD          &
    &  ,ASSSP,ASSSQ,ASSSR,AFLB,AFLD,REDVLX,REDVLY,SPE,SPF,AFSPF        &
    &  ,LE,LF,AFLF,SHRTWAVE,WVSHORT,GRI,NRDFACTOR,NNRD
!
     INTEGER NRD,OPNRD,TOLNRD,TGR,PGR,TGRFLG,NRDFLG,GRIFLG
!
     COMMON/NRDNRD/OPNRD,TOLNRD,TGR,PGR,NRDFLG,TGRFLG,GRIFLG,GRI,NRD   &
    &,NRDFACTOR,NNRD
!
!     THESE NEXT 6 VARIABLES TRACK STATUS OF FIELD,RAY,CFG,SPDEXT
!     CPFNEXT AND ZERNIKE FIT
!     FOR PREDEFINED OPERANDS TO MINIMIZE EXCESSIVE RAY TRACING
     INTEGER OLDF,OLDW,OLDLAMM,OLDR,OLDCFG
!
     LOGICAL OLDCSPD,OLDGSPD,OLDSPD,OLDCPFN,OLDZRNFT,GAUSSAP
!
     COMMON/OLDIES1/OLDF,OLDW,OLDLAMM,OLDR,OLDCFG,GAUSSAP
!
     COMMON/OLDIES2/OLDCSPD,OLDGSPD,OLDSPD,OLDCPFN,OLDZRNFT
!
     LOGICAL MSGSPD
     COMMON/SPDMES/MSGSPD
!
       INTEGER MAXGRD,IWIW,NUMTOT,REDV1,IRED,NFAIL,ILSF,SHORT,NUMCOL   &
    &,IW,NUMBEROF
!
       COMMON/NCOLL/SHORT,NUMCOL,SHRTWAVE,WVSHORT
!
       INTEGER FALFAL(0:499)
!
       COMMON/LAFLAF/FALFAL
!
!       MAXGRD SET TO THE SQUARE ROOT OF THE DSPOT1 FIRST DIM
!       UPPER LIMIT IN PROGRAM.FOR
!
       COMMON/IDSPOT/MAXGRD
!
       COMMON/REDCOM/REDVLX,REDVLY,REDV1,IRED,NFAIL,ILSF,NUMBEROF
!
       COMMON/SPABCD/SPA,SPB,SPC,SPD,SSSP,SSSQ,SSSR,LA,LB,LC,LD        &
    &  ,ASSSP,ASSSQ,ASSSR,AFSPB,AFSPD,AFLB,AFLD,SPE,SPF,AFSPF          &
    &  ,LE,LF,AFLF
!
       real(real64) SSSPX,SSSQX,SSSRX,SSSPY,SSSQY,SSSRY                      &
    &  ,ASSSPX,ASSSQX,ASSSRX,ASSSPY,ASSSQY,ASSSRY                      &
    &  ,RMS,RMSX,RMSY,CENTX,CENTY,RSS,RSSX,RSSY
!
       COMMON/GETSPD/RMS,RMSX,RMSY,CENTX,CENTY,RSS,RSSX,RSSY
!
       COMMON/SPXY/SSSPX,SSSPY,SSSQX,SSSQY,SSSRX,SSSRY,ASSSPX          &
    &  ,ASSSPY,ASSSQX,ASSSQY,ASSSRX,ASSSRY
!
       COMMON/IWIWIW/IWIW,NUMTOT,IW
!
!     SPOT DIAGRAM OPD VARIABLES
!
     real(real64) OOPD,OPDW,RMSOPD,PTOVOPD(0:10),RMSOP(0:10)
!
     COMMON/SPDOPD/OOPD,OPDW,RMSOPD,PTOVOPD,RMSOP
!
     INTEGER SPACEBALL
!
     COMMON/YOGURT/SPACEBALL
!
     LOGICAL SPOTSSI,DETER,DETCENT,DETCHIEF,SPDCENT,SPDCHIEF
!
!     SPOTSSI IS TRUE IF SSI EXPLICITYL SET, ELSE FALSE
!     DETER IS TRUE IF DET ON ELSE FALSE IF OFF
!     DETCENT=TRUE IF CENT     DET
!     DETCHIEF=TRUE IF CHIEF   DET
!     SPDCENT=TRUE IF CENT     SPOT
!     SPDCHIEF=TRUE IF CHIEF   SPOT
!
     COMMON/SPOTTI/SPOTSSI,DETER,DETCENT,DETCHIEF,SPDCHIEF,SPDCENT
!
!     DETTX IS X DIM
!     DETTY IS Y DIM
!     DETDELX IS X OFFSET
!     DETDELY IS Y OFFSET
!     DETTHETA ID ANGLE
!
     real(real64) DETDIAM,DETTX,DETTY,DETDELX,DETDELY,DETTHETA               &
    &,SPDSSIVAL
!
     INTEGER DETTYP
!
     COMMON/SPOTTI2/DETDIAM,DETTX,DETTY,DETDELX,DETDELY,DETTHETA       &
    &,DETTYP
     COMMON/SPOTTI3/SPDSSIVAL
!
     LOGICAL ROTCAPFN,PSFHC
!
     COMMON/PSFWRT/ROTCAPFN,PSFHC
!
     CHARACTER PSFTAG*12,PSFLI*80,CAPFNTAG*12,CAPFNLI*80
!
     COMMON/TAGPSF/PSFTAG,PSFLI,CAPFNTAG,CAPFNLI
!
!     PSF STREAK SETTINGS
     LOGICAL STKPLT,STKWRT
     INTEGER STREAKIT
     COMMON/STREAKER/STKPLT,STKWRT,STREAKIT
!
     real(real64) CENTERVAL
!
     COMMON/VALCENTER/CENTERVAL
!
     real(real64) RSTREHL
     LOGICAL DOSTREHL,RSTREHL_EXIST
     COMMON/STREHLDO/DOSTREHL,RSTREHL_EXIST,RSTREHL
!
!     TRACKS NUMBER OF OTF DATA PAIRS TO BE PLOTTED
!     MAX IS 6 (FIRST PAIR WHEN MULTIPLE PAIRS ARE DONE
!     IS DIFFRACTION LIMIT
     INTEGER OTFPAIR
     COMMON/PAIROTF/OTFPAIR
!
     real(real64) CAPDEF
     COMMON/DEFCAP/CAPDEF
     real(real64) OLDSP(1:10)
     COMMON/SPOLD/OLDSP
!
!     TILT REMOVAL FROM WAVEFRONT
     real(real64) DLLX,DLLY,DLLZ,RREF,LAMAVE
     COMMON/TILWAVE/DLLX,DLLY,DLLZ,RREF,LAMAVE
!
     INTEGER ONRD, OPGR, OTGR
     real(real64) OGRI
     COMMON/OLDPSF/ONRD,OPGR,OTGR,OGRI
!
     LOGICAL MFREQ
     COMMON/MFREQOTF/MFREQ
     INTEGER PSFLIN,PSFLOG
     COMMON/PSFLOGLIN/PSFLIN,PSFLOG
!
     LOGICAL NEAR
!
     COMMON/FREQNEAR/NEAR
!
     LOGICAL DLEICA(0:10),GLEICA(1:10)
     COMMON/LEICASKIP/DLEICA,GLEICA
!
     real(real64) COHERENCE_FACTOR
     COMMON/FACTCOHER/COHERENCE_FACTOR
     real(real64) SPDTRANS,JK_TRANS
     COMMON/TRANSPASS/JK_TRANS,SPDTRANS
!
!       FLAG FOR CAPFN PERFECT 10/9/2002
       LOGICAL PERFECT,NOOB
       COMMON/PERFPERF/PERFECT,NOOB
!
       INTEGER SPDSURF
       COMMON/ALTSPDSURF/SPDSURF
end module