module DATSUB
   use iso_fortran_env, only: real64

! Legacy optimizer support arrays. The legacy KDP optimizer/tolerancing
! (OPTIM1-11) was removed; the entries below survive because live code still
! reads or resets them:
!   VARABL/VBCNT      - raytra9 DEFGRIDS writes deformable-surface "actuator
!                       pseudo-variables"; LDM6/UTILITY4/6 read them
!   TVBCNT/CMPCNT     - reset on lens load (LDM16/18); CMPCNT listed by LDM6
!   MAXVB/MAXTVB/MAXCMP - UTILITY1 config commands
!   TOLER             - compound tolerance store read by LDM15/UTILITY5
!   ISCRIT/ISCOMP/ISTOP - reset on lens load (LDM16/18)
!   OPERND/OPCNT/CURFIG - UTILITY6 GET operand queries (report zeros now)
!   FMTFLG/SOLEXT/DEREXT/CFCH/FMTEXT/OPTMES - flags still written by
!                       CONFIG3/UTILITY4/LDM16/LDM18 reset paths
!   LCVLCV            - UTILITY6 GET LCV
!   FIELDX../RAYX..   - shared ray/field scratch used outside the optimizer
!   AUXCF* / BADOPS / MAXOPT/MAXREG / CHROMATIC - live readers (LDM11,
!                       macro-stubs, register system, spectral code)

    INTEGER TVBCNT,CMPCNT,VBCNT,MAXVB,MAXTVB,MAXCMP
    real(real64) VARABL(1:100000,1:17)
!
!     TOLER TRACKS COMPUND TOLERANCE VALUES AS THEY CAN'T BE TRACKED IN THE
!     LENS ARRAY
!
  real(real64) TOLER(1:60,0:499)
  COMMON/TOLCOM/TOLER

  LOGICAL ISCRIT(1:10)

  COMMON/ISYCRIT/ISCRIT

  LOGICAL ISCOMP(1:10)

  COMMON/COMPIS/ISCOMP

  LOGICAL ISTOP(1:10)

  COMMON/ISYTOP/ISTOP

!       VARIABLES COMMON
    COMMON/SUBPS3/MAXVB,VBCNT,VARABL,TVBCNT,CMPCNT &
  ,MAXTVB,MAXCMP
!
  INTEGER MAXOPT,MAXREG
  COMMON/REGMAX/MAXOPT,MAXREG
!
  INTEGER OPCNT
  real(real64) OPERND(1:100000,1:20),CURFIG
!
!       MERIT COMMON
    COMMON/SUBPS5/OPCNT,OPERND,CURFIG
!
!     AUXILLIARY CFG ARRAYS
  INTEGER CFADD(1:410,1:9),AUXMAX,LASCFG
  LOGICAL ULON,USON
  real(real64) CFVAL(1:410,1:2)
  CHARACTER CFCHAR(1:410,1:2)*23
  COMMON/AUXCF1/CFVAL,CFADD,AUXMAX,LASCFG
  COMMON/AUXCF2/CFCHAR
  COMMON/AUXCF3/ULON,USON
!
  LOGICAL FMTFLG
  COMMON/FMTT1/FMTFLG
!
  LOGICAL SOLEXT,DEREXT,CFCH,OPTMES,FMTEXT
!
  COMMON/MESOPT/OPTMES
!
  COMMON/DEEXIS/SOLEXT,DEREXT,CFCH,FMTEXT
!
!     KEEPS THE LAST CHANGE VECTOR LENGTH
  real(real64) LCVLCV
!
  COMMON /VCLVCL/LCVLCV
!
!     RAYS AND FIELDS FOR OPTIMIZATION
!
  real(real64) FIELDX(1:200),FIELDY(1:200),FIELDZ(1:200) &
  ,FIELDW(1:200),RAYX(1:5000),RAYY(1:5000),RAYW(1:5000)
!
  COMMON/FRS/FIELDX,FIELDY,FIELDZ,FIELDW,RAYX,RAYY,RAYW
!
  LOGICAL BADOPS

  COMMON/OPSBAD/BADOPS
!
    LOGICAL CHROMATIC
    COMMON/MONOCHROME/CHROMATIC
!

end module
