module DATPTS
   use iso_fortran_env, only: real64

!     PART DRAWING INCLUDE FILE
!     FLAG FOR PART DRAWINGS INPUT IN PROGRESS
!
    LOGICAL PARTS
    COMMON/PARPAR/PARTS
!
!     PART SURFACE NUMBERS
!
    INTEGER ISURFF,JSURFF,KSURFF,LSURFF
    COMMON/PTSSURF/ISURFF,JSURFF
!
!     GENERAL FLOATING POINT VALUES
!
    real(real64) ODV1,ODV2,DIATOLV,RADTOV1,RADTOLV2 &
    &,RADLFV1,RADTLFV2,FRNGV1,FRNGV2,THITILV,CLERAPV1,CLERAPV2 &
    &,QUALV,FNGDIAV1,FNGDIAV2,GLSCDV1,GLSCDV2 &
    &,CENTIR
    COMMON/PTSVAL/ODV1,ODV2,DIATOLV,RADTOV1,RADTOLV2 &
    &,RADLFV1,RADTLFV2,FRNGV1,FRNGV2,THITILV,CLERAPV1,CLERAPV2 &
    &,QUALV,FNGDIAV1,FNGDIAV2,GLSCDV1,GLSCDV2 &
    &,CENTIR
!
!     CHARACTER VALUES
!
    INTEGER DRAWSURF,GLSCD1,GLSCD2
    LOGICAL FRINTOL1,FRINTOL2,FLAT1,FLAT2
    CHARACTER SURQUAL*20,SURCOAT*20,DTITLE*32,DWGNO*12,SURMATL*13 &
    &,CONAME*32
    real(real64) POD1,POD2,DIATOL,RADTOL1,RADTOL2,THITOL,CLP1,CLP2,WAVEL1 &
    &,FNGDIA1,FNGDIA2,BRKEDG,SAGTL1,SAGTL2 &
    &,PRPNTL1,PRPNTL2,FRNG1,FRNG2
    COMMON/PRTDWG/DRAWSURF,POD1,POD2,DIATOL,RADTOL1,RADTOL2 &
    &,FRINTOL1,THITOL,CLP1,CLP2,FNGDIA1,FNGDIA2,&
    &BRKEDG,SAGTL1,SAGTL2,PRPNTL1,PRPNTL2,&
    &FRNG1,FRNG2,WAVEL1,FRINTOL2
    COMMON/PRTDWG2/SURQUAL,SURCOAT,DTITLE,DWGNO,SURMATL,CONAME,&
    &FLAT1,FLAT2
!
    LOGICAL PARTISDRAWING
    COMMON/ISPART/PARTISDRAWING
!
    real(real64) TEST1,TEST2,PODA1,PODA2,PODB1,PODB2
    COMMON/PARTS3/TEST1,TEST2,PODA1,PODA2,PODB1,PODB2
!
    LOGICAL CLP1SET,CLP2SET
    COMMON/CLPSETS/CLP1SET,CLP2SET
!
    LOGICAL SINGLET,DOUBLET,NOTEPAGE
    COMMON/SINGDOUB/SINGLET,DOUBLET,NOTEPAGE

end module DATPTS
