SUBROUTINE DXFNSSSFS
   USE NSSMOD
   use DATMAI
   INTEGER I,ISFI
   real(real64) SFI
   IF(.NOT.NEXISTN) THEN
      WRITE(OUTLYNE,*) 'NO NSS DATABASE EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'NO DXF OUTPUT POSSIBLE'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   CALL NSS_VERTEX_SILENT
!       NOW VERTEX DATA EXISTS IN GLOBAL COORDINATES
   DO I=1,MAXS
!       PLOT THE CLAP FOR ACTIVE SURFACES ONLY
      IF(NSSALENS(19,I).NE.0.0D0) THEN
         SFI=1.0D0
!        IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.
!     1  NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)
!     1  CALL DXFNSSCLP(I,SFI)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE HOLES FOR ACTIVE SURFACES ONLY
      IF(NSSALENS(25,I).NE.0.0D0) THEN
!        IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.
!     1  NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)
!     1  CALL DXFNSSHOL(I)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE PROFX FOR ACTIVE SURFACES ONLY
      IF(NSSALENS(19,I).NE.0.0D0) THEN
!        IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.
!     1  NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)
!     1  CALL DXFNSSPRO(I,0.0D0)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE PROFY FOR ACTIVE SURFACES ONLY
      IF(NSSALENS(19,I).NE.0.0D0) THEN
!        IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.
!     1  NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)
!     1  CALL DXFNSSPRO(I,90.0D0)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE INDIVIDUAL CLAPS OF ALL MEM PIXELS FOR A MEM SURFACE
      IF(NSSALENS(1,I).EQ.5.0D0) THEN
!        CALL DXFNSSMEMPLT(I)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE TUBE CLAPS
      IF(NSSALENS(1,I).EQ.6.0D0) THEN
!        CALL DXFNSSCLPTUB(I)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE TUBE PROFILES
      IF(NSSALENS(1,I).EQ.6.0D0) THEN
!         CALL DXFNSSPROTUB(I,0.0D0)
!         CALL DXFNSSPROTUB(I,45.0D0)
!         CALL DXFNSSPROTUB(I,90.0D0)
!         CALL DXFNSSPROTUB(I,135.0D0)
!         CALL DXFNSSPROTUB(I,180.0D0)
!         CALL DXFNSSPROTUB(I,225.0D0)
!         CALL DXFNSSPROTUB(I,270.0D0)
!         CALL DXFNSSPROTUB(I,315.0D0)
      END IF
   END DO
   RETURN
END
SUBROUTINE DXFNSSRY
   USE NSSMOD
!
   use DATLEN
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS ROUTINE DOES THE PLOT RAY COMMAND AT THE CMD LEVEL
!
   real(real64) X,Y,Z,XN,YN,ZN,ROT1X,ROT1Z,ROT2Y,&
   &ROT2Z,AX,AY,AZ,AALF,APHI,YMAXI,YMINI,XMAXI,XMINI &
   &,XNEW,YNEW,LKG,VIEPH,VIEAL,NSSFACTOR,L,M,N
!
   INTEGER CN
!
   LOGICAL GGO
!
   INTEGER IX,IY,I,II,IPST,COLPAS,FLAG,JK
   INTEGER NSSP1ARRAY,ALLOERR,ICOUNT
   DIMENSION NSSP1ARRAY(:,:)
   ALLOCATABLE :: NSSP1ARRAY
!
!
!     LOOK.VIEW TRANSFORMS

   ROT1X(AX,AZ,APHI)=((AX*DCOS(APHI))-(AZ*DSIN(APHI)))
   ROT1Z(AX,AZ,APHI)=((AX*DSIN(APHI))+(AZ*DCOS(APHI)))
!
   ROT2Z(AZ,AY,AALF)=((AZ*DCOS(AALF))+(AY*DSIN(AALF)))
   ROT2Y(AZ,AY,AALF)=((-AZ*DSIN(AALF))+(AY*DCOS(AALF)))
   IF(.NOT.NEXISTN) THEN
      WRITE(OUTLYNE,*) 'NO NSS DATABASE EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'NO NSS RAY CAN BE DRAWN'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   CALL NSS_VERTEX_SILENT
!
   DEALLOCATE(NSSP1ARRAY,STAT=ALLOERR)
   X=0.0D0
   Y=0.0D0
   VIEPH=(PII/180.0D0)*VIEPHI
   VIEAL=(PII/180.0D0)*VIEALF
!       NOW WE HAVE THE REAL WORLD COORDINATES OF THE RAY TO BE PLOTTED
!       THEY ARE STORED IN THE FILE NSSRHIST.DAT
!
!     HERE IS WHERE REAL WORK BEGINS. FIRST PROJECT THE 3D WORLD COORDINATES
!     OF THE VERTICIES ONTO THE 2D PLANE INDICATED BY THE PLOT LOOK/ PLOT VIEW
!     DATA. THE DIRECTION COSINES OF THE LOOK VECTOR ARE LOOKX, LOOKY AND
!     LOOKZ. THE TRANSFORMATIONS ARE:
!
   CALL NSSROT
!
!     AFTER THIS TRANSFORMATION, THE WORLD X COORDINATE IS PLOTTED IN THE
!     HORIZONTAL X-AXIS OF THE DISPLAY AND THE Y WORLD COORDINATE IS PLOTTED
!     IN THE VERTICAL Y-AXIS OF THE DISPLAY AFTER A CONVERSION TO
!     DEVICE INDEPENDENT COORDINATES ARE MADE.
!
   CALL NSSPLTSC
!
   ICOUNT=0
   OPEN(UNIT=92,FILE='NSSHT.DAT',STATUS='UNKNOWN')
   REWIND(UNIT=92)
5  CONTINUE
   CN=NSSWAVNUM
   READ(UNIT=92,FMT=*,END=6) I,X,Y,Z,L,M,N,CN
   ICOUNT=ICOUNT+1
   GO TO 5
6  CONTINUE
   CALL CLOSE_FILE(92,1)
   IF(ICOUNT.EQ.0) THEN
      WRITE(OUTLYNE,*) 'NO RAYS EXIST TO BE PLOTTED'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   ALLOCATE(NSSP1ARRAY(1:ICOUNT,1:3),STAT=ALLOERR)
   OPEN(UNIT=92,FILE='NSSHT.DAT',STATUS='UNKNOWN')
!     HERE IS THE LOOP WHICH PLOTS THE RAYS USING CALLS TO
!     PENMV2(IX,IY,IPST)
   REWIND(UNIT=92)
   DO II=1,ICOUNT
      READ(UNIT=92,FMT=*) I,X,Y,Z,L,M,N,CN
      X=X-XROT
      Y=Y-YROT
      Z=Z-ZROT
      XN=ROT1X(X,Z,VIEPH)
      YN=Y
      ZN=ROT1Z(X,Z,VIEPH)
      X=XN
      Y=YN
      Z=ZN
!
      ZN=ROT2Z(Z,Y,VIEAL)
      YN=ROT2Y(Z,Y,VIEAL)
      XN=X
      X=XN
      Y=YN
      Z=ZN
!
!     RIGHT NOW,COORDINATES ARE IN WORLD COORDINATES
!     CONVERT THEM TO DEVICE INDEPENDENT GRAPHICS COORDINATES IN
!     TWO STEPS.
!
!     THE WORLD X PLOTS TO THE PLOTTER X
!     THE WORLD Y PLOTS TO THE PLOTTER Y
!
!     STEP 1: CONVERT USING AN APPROPRIATE SCALE FACTOR
!               CALCULATING AN APPROPRIATE FACTOR IF NECESSARY
!
      Y=(Y/NSSSCFA)*1000.0D0
!
      X=(X/NSSSCFA)*1000.0D0
!
!     STEP 2: APPLY THE SCREEN Y-OFFSET AND SCREEN GAMMA ROTATION
!
!     APPLY THE PLOT LOOK/VIEW Y-OFFSET VALUE
!
      IF(LORIENT) CALL ORSHIFT
      Y=Y+3500.0D0+DBLE(PYSHFT)
      X=X+DBLE(PXSHFT)
!
!     IF THERE ARE X-OFFSETS (JUSTIFICATION) TO APPLY, DO THEM HERE.
!
      IF(RCL.EQ.1.OR.RCL.EQ.-1) THEN
         JUSOFF=500.0D0-((XMINI/NSSSCFA)*1000.0D0)
         RCL=-1
      ELSE
      END IF
      IF(RCL.EQ.2.OR.RCL.EQ.-2) THEN
         RCL=-2
         JUSOFF=5000.0D0
      ELSE
      END IF
      IF(RCL.EQ.3.OR.RCL.EQ.-3) THEN
         JUSOFF=9500.0D0-((XMAXI/NSSSCFA)*1000.0D0)
         RCL=-3
      ELSE
      END IF
!
      X=X+JUSOFF
!
!     IF THERE IS A NON-ZERO GAMMA SPECIFIED IN PLOT LOOK OR PLOT VIEW THEN
!     ROTATE IN GAMMA ON THE SCREEN ABOUT THE CENTER OF THE SCREEN
!     WHICH HAS COORDINATES X=5000.0D0,Y=3500.0D0
!
!     FIRST SHIFT THE COORDINATE ORIGIN TO THE CETER OF THE DISPLAY
!
      X=X-5000.0D0
      Y=Y-3500.0D0
!     THE SCREEN COORDINATE IN real(real64) IN THE SHIFTED COORDINATE
!     FRAME IS NOW X AND Y

      IF(DBLE(PGAMMA).NE.0.0D0) THEN
         LKG=(PII/180.0D0)*DBLE(PGAMMA)
         XNEW=((X*DCOS(LKG))-(Y*DSIN(LKG)))
         YNEW=((X*DSIN(LKG))+(Y*DCOS(LKG)))
         X=XNEW
         Y=YNEW
      ELSE
      END IF

!     THE ROTATION IS DONE, NOW SHIFT THE ORIGIN BACK TO THE BOTTOM
!     LEFT HAND CORNER
      X=X+5000.0D0
      Y=Y+3500.0D0
!
!     PUT INSTRUCTIONS IN NSSP1ARRAY TO DROP PEN AND DRAW
      IPST=1
      IF(X.LT.-2.0D9) X=-2.0D9
      IF(Y.LT.-2.0D9) Y=-2.0D9
      IF(X.GT.2.0D9) X=2.0D9
      IF(Y.GT.2.0D9) Y=2.0D9
      IX=INT(X)
      IY=INT(Y)
!     MOVE TO NEW POSITION WITH LOWERED PEN
      NSSP1ARRAY(II,1)=IX
      NSSP1ARRAY(II,2)=IY
      IF(I.EQ.0) THEN
         NSSP1ARRAY(II,3)=0
      ELSE
         NSSP1ARRAY(II,3)=1
      END IF
      IF(.NOT.PLEXIS) PLEXIS=.TRUE.
      CONTINUE
   END DO
   CALL CLOSE_FILE(92,1)
!
!     NOW ISSUE THE PLOTTING COMMANDS STORED IN THE P1ARRAY ARRAY
!
   COLPAS=COLRAY
   CALL MY_COLTYP(COLPAS)
   NSSP1ARRAY(1,3)=0
   FIXUP=.FALSE.
   DO I=1,ICOUNT
      CALL PENMV2(NSSP1ARRAY(I,1),NSSP1ARRAY(I,2),NSSP1ARRAY(I,3))
   END DO
   COLPAS=COLLBL
   CALL MY_COLTYP(COLPAS)
   DEALLOCATE(NSSP1ARRAY,STAT=ALLOERR)
   RETURN
END
