!       FIRST COLLECTION OF NSS FILES
!
SUBROUTINE GETOANGLES
   USE NSSMOD
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE

   real(real64) D31,D32,D33,COSB,SINB,ALPHA,BETA
!
!
!     OBJL,OBJM AND OBJN ARE THE L,M AND N-DIRECTION COSINES OF THE
!     ROTATED COORDINATE SYSTEM. 0.0, 0.0 AND 1.0 ARE THE DIRECTION
!     COSINES OF THE UNROTATED SYSTEM. ONLY AN ALPHA AND A BETA ROTATION
!     RELATE THE TWO SYSTEMS. GAMMA IS ALWAYS ZERO.
   D31=OBJL
   D32=OBJM
   D33=OBJN
!
!     NOW CALCULATE ALPHA,BETA
!     CALCULATE BETA
   BETA=DASIN(-D31)
   COSB=DCOS(BETA)
   IF(COSB.NE.0.0D0) THEN
!     COSINE OF BETA IS NOT ZERO
!     COSINE OF BETA IS NOT ZERO
      IF((D32/COSB).EQ.0.0D0.AND.(D33/COSB).NE.0.0D0) ALPHA=0.0D0
      IF((D32/COSB).EQ.0.0D0.AND.(D33/COSB).EQ.0.0D0) ALPHA=0.0D0
      IF((D32/COSB).NE.0.0D0.AND.(D33/COSB).EQ.0.0D0) ALPHA=PII/2.0D0
      IF((D32/COSB).NE.0.0D0.AND.(D33/COSB).NE.0.0D0)&
      &ALPHA=DATAN2((D32/COSB),(D33/COSB))
   END IF
   IF(COSB.EQ.0.0D0) THEN
!     COSINE OF BETA IS ZERO
      IF(D31.EQ.-1.0D0) SINB=1
      IF(D31.EQ.1.0D0) SINB=-1
      IF(SINB.EQ.1) BETA=PII/2.0D0
      IF(SINB.EQ.-1) BETA=-PII/2.0D0
      IF(SINB.EQ.1) THEN
         IF((D32).EQ.0.0D0.AND.(D33).NE.0.0D0) ALPHA=0.0D0
         IF((D32).EQ.0.0D0.AND.(D33).EQ.0.0D0) ALPHA=0.0D0
         IF((D32).NE.0.0D0.AND.(D33).EQ.0.0D0) ALPHA=PII/2.0D0
         IF((D32).NE.0.0D0.AND.(D33).NE.0.0D0)&
         &ALPHA=DATAN2((D32),(D33))
      END IF
      IF(SINB.EQ.-1) THEN
         IF((D32).EQ.0.0D0.AND.(D33).NE.0.0D0) ALPHA=0.0D0
         IF((D32).EQ.0.0D0.AND.(D33).EQ.0.0D0) ALPHA=0.0D0
         IF((D32).NE.0.0D0.AND.(D33).EQ.0.0D0) ALPHA=PII/2.0D0
         IF((D32).NE.0.0D0.AND.(D33).NE.0.0D0)&
         &ALPHA=DATAN2((-D32),(-D33))
      END IF
   END IF
!     CONVERT TO DEGREES
   OALPHA=(180.0D0/PII)*ALPHA
   OBETA=(180.0D0/PII)*BETA
   OGAMMA=0.0D0
   RETURN
END

SUBROUTINE NSSUSER(J)
   USE NSSMOD
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
   INTEGER J
   NSS_INTERSECT=.FALSE.
   RETURN
END
SUBROUTINE NSSTRACE
   USE NSSMOD
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
   INTEGER NREF,NOBJ,I,J,K,L,M
   real(real64) ODEL,RDEL,OCENX,OCENY,OCENZ,MAG,XSTART,YSTART,ZSTART
   real(real64) OX,OY,OZ,RX,RY,RZ,LSTART,MSTART,NSTART,GOX,GOY,GRX,GRY
   real(real64) OGRID_SPAN,RGRID_SPAN,XANG,YANG,RSHAPE,GRZ,GOZ,SSHAPE
   real(real64) OOX,OOY,ORX,ORY,FRX,FRY,RCENX,RCENY,RCENZ
   LOGICAL TESTSHAPES,TESTSHAPER
!       THIS CONTROLS THE NSS DATABASE RAY TRACE
!       CALCULATE THE STARTING RAY LOCATION AND DIRECTION COSINES
!       IN GLOBAL COORDINATES
!
   RHISTN=0
!       OBJECT GRID SPACING IS ODEL
   ODEL=NSSSYSTEM(37)
!       DIMENSION OF THE OBJECT GRID IS NOBJ
   NOBJ=INT(NSSSYSTEM(32))
!       CENTER OF OBJECT GRID IS LOCATED AT OCENX,OCENY,OCENZ
   OCENX=NSSSYSTEM(29)
   OCENY=NSSSYSTEM(30)
   OCENZ=NSSSYSTEM(31)
!       CENTER OF REFERENCE GRID IS LOCATED AT RCENX,RCENY,RCENZ
   RCENX=NSSSYSTEM(40)
   RCENY=NSSSYSTEM(41)
   RCENZ=NSSSYSTEM(42)
!       THE DIRECTION COSINES OF THE LINE CONNECTING THE CENTER OF THE OBJECT GRID
!       WITH THE CENTER OF THEREFERENCE GRID ARE: OBJL, OBJM AND OBJN
   OMAG=DSQRT(((RCENX-OCENX)**2)+((RCENY-OCENY)**2)+&
   &((RCENZ-OCENZ)**2))
   IF(OMAG.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*) 'OBJECT AND REFERENCE GRIDS ARE CO-LOCATED'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'NO RAYS MAY BE TRACED'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   OBJL=(RCENX-OCENX)/OMAG
   OBJM=(RCENY-OCENY)/OMAG
   OBJN=(RCENZ-OCENZ)/OMAG
!       DETERMINE THE ALPHA,BETA AND GAMMA ROTATION ANGLES WHICH CAN PRODUCE THESE
!       DIRECTION COSINES.
   CALL GETOANGLES
!       OALPHA,OBETA AND OGAMMA ARE THE EULER ROTATION ANGLES IN CODE-V SIGN CONVENTION
!       WHICH ROTATE THE 0,0,1 INTO OBJL,OBJM AND OBJN. THESE WILL BE USED TO CONVERT OX,OY AND OZ
!       FROM THE LOCAL OBJECT AND REFERENCE GRIDS INTO GLOBAL COORDINATES IN ORDER TO GET GLOBAL
!       RAY STARTING POSITIONS AND DIRECTION COSINES.
!
!       REFERENCE GRID SPACING IS RDEL
   RDEL=NSSSYSTEM(38)
!       DIMENSION OF THE OBJECT GRID IS NOBJ
   NREF=INT(NSSSYSTEM(36))
!       CENTER OF REFERENCE GRID IS LOCATED AT RCENX,RCENY AND RCENZ
!       DO A RAY'S STARTING DATA,IN GLOBAL COORDINATES THEN TRACE THE RAY
!       THE OBJECT GRID POINTS SPAN A SEMI-DISTANCE OF DBLE(NOBJ-1)*ODEL/2
!       IN GLOBAL COORDINATES, THE LOCATION OF THE STARTING POINTS ARE:
   IF(DABS(DBLE(NOBJ/2)-(DBLE(NOBJ)/2.0D0)).EQ.0.0D0) THEN
      OBJODD=.FALSE.
   ELSE
      OBJODD=.TRUE.
   END IF
   IF(DABS(DBLE(NREF/2)-(DBLE(NREF)/2.0D0)).NE.0.0D0) THEN
      REFODD=.FALSE.
   ELSE
      REFODD=.TRUE.
   END IF
!     IN THE LOCAL COORDINATE SYSTEM OF THE OBJECT PLANE WHICH
!     IS PERPENDICULAR TO THE LINE CONNECTING THE CENTERS OF THE OBJECT AND REFERENCE GRID
!     THE X AND Y NEGATIVE LIMITA ARE OOX AND OOY
   IF(OBJODD) THEN
!       ODD GRID
      OGRID_SPAN=DBLE(NOBJ-1)*ODEL/2.0D0
      OOX=-OGRID_SPAN
      OOY=-OGRID_SPAN
      OZ=OCENZ
      GOZ=OCENZ
   ELSE
!       EVEN GRID
      OGRID_SPAN=DBLE(NOBJ-1)*ODEL/2.0D0
      OOX=-OGRID_SPAN
      OOY=-OGRID_SPAN
      OZ=OCENZ
      GOZ=OCENZ
   END IF
   TESTSHAPES=.FALSE.
   IF(NSSSYSTEM(33).EQ.0.0D0) TESTSHAPES=.TRUE.
   IF(TESTSHAPES) THEN
      SSHAPE=DABS(OOX)
      IF(DABS(OOY).GT.DABS(OOX)) SSHAPE=DABS(OOY)
   END IF
!       THE REFERENCE GRID POINTS SPAN A SEMIDISTANCE OF DBLE(NREF-1)*RDEL/2
!     IN THE LOCAL COORDINATE SYSTEM OF THE REFERENCE PLANE WHICH
!     IS PERPENDICULAR TO THE LINE CONNECTING THE CENTERS OF THE OBJECT AND REFERENCE GRID
!     THE X AND Y NEGATIVE LIMITA ARE OOX AND OOY
   IF(REFODD) THEN
!       ODD GRID
      RGRID_SPAN=DBLE(NREF-1)*RDEL/2.0D0
      ORX=-RGRID_SPAN
      ORY=-RGRID_SPAN
      RZ=RCENZ
      GRZ=RCENZ
   ELSE
!       EVEN GRID
      RGRID_SPAN=DBLE(NREF-1)*RDEL/2.0D0
      ORX=-RGRID_SPAN
      ORY=-RGRID_SPAN
      RZ=RCENZ
      GRZ=RCENZ
   END IF
   TESTSHAPER=.FALSE.
   IF(NSSSYSTEM(22).EQ.0.0D0) TESTSHAPER=.TRUE.
   IF(TESTSHAPER) THEN
      RSHAPE=DABS(ORX)
      IF(DABS(ORY).GT.DABS(ORX)) RSHAPE=DABS(ORY)
   END IF
!       INITIALIZE THE RAY HISTORY FILES
   OPEN(UNIT=48,FILE='NSSRHIST.DAT')
   OPEN(UNIT=91,FILE='NSSHIST.DAT')
   OPEN(UNIT=92,FILE='NSSHT.DAT')
   CALL CLOSE_FILE(48,0)
   CALL CLOSE_FILE(91,0)
   CALL CLOSE_FILE(92,0)
   OPEN(UNIT=48,FILE='NSSRHIST.DAT')
   OPEN(UNIT=91,FILE='NSSHIST.DAT')
   OPEN(UNIT=92,FILE='NSSHT.DAT')
!
!       THE OUTER MOST LOOP, LOOPS THROUGH THE ACTIVE WAVELEGTNS
   DO M=1,10
      IF(NSSSYSTEM(M).NE.0.0D0.AND.NSSSYSTEM(M+10).NE.0.0D0) THEN
         NSSWAVL=NSSSYSTEM(M)
         CURWAVELENGTH=NSSWAVL
         NSSWVWT=NSSSYSTEM(M+10)
         NSSWAVNUM=M
!       TRACE THAT WAVELENGTH
         DO I=1,NOBJ
            OX=OOX+(DBLE(I-1)*ODEL)
            OY=OOY
            DO J=1,NOBJ
               OY=OOY+(DBLE(J-1)*ODEL)
               IF(TESTSHAPES) THEN
                  IF(DSQRT((OX**2)+(OY**2)).GT.SSHAPE) THEN
!       SKIP TRACING THIS RAY. IT DOES NOT GO INTO THE RAY HISTORY
                     CYCLE
                  END IF
               END IF
               DO K=1,NREF
                  RX=ORX+(DBLE(K-1)*RDEL)
                  RY=ORY
                  DO L=1,NREF
                     RY=ORY+(DBLE(L-1)*RDEL)
                     IF(TESTSHAPER) THEN
                        IF(DSQRT((RX**2)+(RY**2)).GT.RSHAPE) THEN
!       SKIP TRACING THIS RAY. IT DOES NOT GO INTO THE RAY HISTORY
                           CYCLE
                        END IF
                     END IF
!       STARTING RAY COORDINATES ARE XSTART,YSTART,ZSTART
!
!       NOW CONVERT THE OX, OY AND RX AND RY FROM THE LOCAL COORDINATES OF THEIR
!       RESPECTIVE GRID PLANES INTO GLOBAL COORDINATES
!
                     CALL OXOYRXRY_LOCAL_TO_GLOBAL(OX,OY,RX,RY,GOX,GOY,GRX,GRY)
!
!       NOW ADD THE GLOBAL OBJECT AND REFERENCE GRID CENTERS
                     GOX=GOX+OCENX
                     GOY=GOY+OCENY
                     GRX=GRX+RCENX
                     GRY=GRY+RCENY
!       WE ALREADY HAD OZ AND RZ
!
!       PROCEED WITH THE RAY TRACE
!
                     XSTART=GOX
                     YSTART=GOY
                     ZSTART=GOZ
!       STARTING RAY DIRECTION COSINES ARE:
                     LSTART=(GRX-GOX)
                     MSTART=(GRY-GOY)
                     NSTART=(GRZ-GOZ)
                     MAG=DSQRT((LSTART**2)+(MSTART**2)+(NSTART**2))
                     LSTART=(GRX-GOX)/MAG
                     MSTART=(GRY-GOY)/MAG
                     NSTART=(GRZ-GOZ)/MAG
!       FRACTIONAL REFERENCE GRID COORDINATES ARE FRX,FRY
                     FRX=GRX/ORX
                     FRY=GRY/ORY
                     IF(ORX.EQ.0.0D0) FRX=0.0D0
                     IF(ORY.EQ.0.0D0) FRY=1.0D0
!       WE NOW HAVE THE STARTING RAY COORDINATES AND DIRECTION COSINES
!       IN GLOBAL COORDINATES FOR A RAY.
!       CALCULATE THE PERPENDICULARS TO THIS STARTING RAY BECAUSE
!       THESE MUST BE TRACKED FOR POLARIZATION.
!       THEN CALL NSSRAY INORDER TO ACTUALLY PERFOM
!       THE NSS RAY TRACE FOR THE SPECIFIC RAY.
!       WE START AT THE OBJECT SURFACE WITH THESE STARTING VALUES AND TRACE
!       THE RAY THROUGH THE SYSTEM. tHE STARTING RAY DATA IN THE GLOBAL COORDINATE
!       SYSTEM IS KEPT IN THE START ARRAY, THE CORRESPONDING RAY DATA AT A SURFACE
!       IN THE SURFACE COORDINATE SYSTEM ID KEPT IN STARTP, BOTH PASSED IN NSSMOD MODULE
                     START(1)=XSTART
                     START(2)=YSTART
                     START(3)=ZSTART
                     START(4)=LSTART
                     START(5)=MSTART
                     START(6)=NSTART
                     IF(NSSSYSTEM(34).EQ.-1.0D0) THEN
!       THE OBJECT IS VIRTUAL AND THE RAY REALLY STARTS AT THE REFERENCE GRID LOCATION
!       RX,RY,RZ (ADDED 4/13/2004)
                        START(1)=GRX
                        START(2)=GRY
                        START(3)=GRZ
                        START(4)=LSTART
                        START(5)=MSTART
                        START(6)=NSTART
                     END IF
                     IF(START(6).EQ.0.0D0) THEN
                        YANG=PII/2.0D0
                        XANG=PII/2.0D0
                     ELSE
                        IF(DABS(START(5)).LE.1.0D-15.AND.DABS(START(6)).LE.1.0D-15) THEN
                           YANG=0.0D0
                        ELSE
                           YANG=DATAN2(START(5),START(6))
                        END IF
                        IF(DABS(START(4)).LE.1.0D-15.AND.DABS(START(6)).LE.1.0D-15) THEN
                           XANG=0.0D0
                        ELSE
                           XANG=DATAN2(START(4),START(6))
                        END IF
                     END IF
                     START(7)=(1.0D0*DCOS(XANG))
                     START(8)=0.0D0
                     START(9)=-(1.0D0*DSIN(XANG))
                     START(10)=0.0D0
                     START(11)=(1.0D0*DCOS(XANG))
                     START(12)=-(1.0D0*DSIN(YANG))
                     START(13)=0.0D0
                     START(14)=0.0D0
                     START(15)=1.0D0
!
!       1. INITIALIZE ALL STARTING RAY DAYA
                     CALL INITIALIZE_RAY(FRX,FRY)
                     CURINDEXR=CURINDEX(M)
                     PREVINDEXR=CURINDEX(M)
                     CURINDEXI=CURINDEX(M+10)
                     PREVINDEXI=CURINDEX(M+10)
!       CURINDEX() AND PREVINDEXR AND I AND CURINDEXR AND I
!       WILL BE UPDATED AFTER THE COMPLETION OF EACH SURFACE INTERACTION.
!       TRACE THE NON-SEQUENTIAL RAY
                     RHISTN=RHISTN+1
                     CALL NSSRAY
                  END DO
               END DO
            END DO
         END DO
      ELSE
!       SKIP AND GO TO NEXT WAVELENGTH
      END IF
!       DO THE NEXT WAVELENGTH
   END DO
   CALL CLOSE_FILE(48,1)
   CALL CLOSE_FILE(91,1)
   CALL CLOSE_FILE(92,1)
!                       RETURN
END
SUBROUTINE INITIALIZE_RAY(FRX,FRY)
   USE NSSMOD
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
   INTEGER I
   real(real64) FRX,FRY,APX,APR
   NSSRAYFAIL=.FALSE.
   NSSRAYFAILCODE(1)=0
   NSSRAYFAILCODE(2)=0
!       THE RAY IS AT THE CORRECT LOCATION AT THE REFERENCE GRID LOCATION.
   OLD_LTEST=0.0D0
!       SNUM IS THE SURFACE NUMBER FOR THE NEXT SURFACE INTERACTION
!       AFTER OPTIMAL RAY INTERSECTION
   SNUM=-1
!       RAY ENERGY INCLUDING GAUSSIAN RAY APODIZATION TERM
!       ADDED 4/1/2004
   NSSRAY_ENERGY=1.0D0
   APX=-DLOG(10.0D0**(-DABS(NSSSYSTEM(23))/10.0D0))
   APR=(FRX**2)+(FRY**2)
   NSSRAY_ENERGY=NSSRAY_ENERGY*DEXP(-APX*APR)
   START(16)=NSSRAY_ENERGY

   NSSRAY_HITS=0
!       RAY POLARIZATION DATA
   NSSRAY_RPOL(1:20)=0.0D0
   NSSRAY_IPOL(1:20)=0.0D0
!       RAY EXISTENCE STATUS (ASSUME IT EXISTS)
   NSSRAY_EXIST=.TRUE.
!       CURRENT RAY DATA IS AT SURFACE 0 AT STARTING SOURCE LOCATION
   NSS_GRAY(1:50)=START(1:50)
   NSS_GRAYP(1:50)=START(1:50)
   NSS_LRAY(1:50)=START(1:50)
   NSS_LRAYP(1:50)=START(1:50)
   CURGLASS(1)=NSSOGLASS(1)
   CURGLASS(2)=NSSOGLASS(2)
   CURINDEX(1:20)=OBJINDEX(1:20)
   RETURN
END
SUBROUTINE NSSHIST(J)
!       ANNOTATED RAY HISTORY FILE
   USE NSSMOD
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
   INTEGER J,K
!       WRITE OBJECT,SURFACE,FAILURE CODES
   WRITE(91,*) 'SURF#     FAILURE CODE'
   WRITE(91,1) J,NSSRAYFAILCODE(2)
1  FORMAT(I5,5X,I3)
   IF(J.EQ.0) THEN
   END IF
!       WRITE RAY GLOBAL POSITION
   WRITE(91,*) 'RAY GLOBAL POSITIONS'
   WRITE(91,7)
7  FORMAT(10X,'X',12X,2X,10X,'Y',12X,2X,'Z')
8  FORMAT(10X,'L',12X,2X,10X,'M',12X,2X,'N')
9  FORMAT(10X,'XL',11X,2X,10X,'XM',11X,2X,'XN')
10 FORMAT(10X,'YL',11X,2X,10X,'YM',11X,2X,'YN')
11 FORMAT(10X,'LN',11X,2X,10X,'MN',11X,2X,'NN')
12 FORMAT(10X,' N',11X,2X,10X,'NP')
   WRITE(91,2) NSS_GRAY(1),NSS_GRAY(2),NSS_GRAY(3)
!       WRITE RAY LOCAL POSITION
   WRITE(91,*) 'RAY LOCAL POSITIONS'
   WRITE(91,7)
   WRITE(91,2) NSS_LRAY(1),NSS_LRAY(2),NSS_LRAY(3)
2  FORMAT(D23.15,2X,D23.15,2X,D23.15)
13 FORMAT(D23.15,2X,D23.15)
!       WRITE RAY GLOBAL DIR COSINES
   WRITE(91,*) 'BEFORE SURFACE INTERACTION'
   WRITE(91,*) 'RAY GLOBAL DIRECTIONS'
   WRITE(91,8)
   WRITE(91,2) NSS_GRAY(4),NSS_GRAY(5),NSS_GRAY(6)
   WRITE(91,*) 'RAY GLOBAL DIRECTIONS, X-VECTOR'
   WRITE(91,9)
   WRITE(91,2) NSS_GRAY(7),NSS_GRAY(8),NSS_GRAY(9)
   WRITE(91,*) 'RAY GLOBAL DIRECTIONS, Y-VECTOR'
   WRITE(91,10)
   WRITE(91,2) NSS_GRAY(10),NSS_GRAY(11),NSS_GRAY(12)
!       WRITE RAY LOCAL DIR COSINES
   WRITE(91,*) 'RAY LOCAL DIRECTIONS'
   WRITE(91,8)
   WRITE(91,2) NSS_LRAY(4),NSS_LRAY(5),NSS_LRAY(6)
   WRITE(91,*) 'RAY LOCAL DIRECTIONS, X-VECTOR'
   WRITE(91,9)
   WRITE(91,2) NSS_LRAY(7),NSS_LRAY(8),NSS_LRAY(9)
   WRITE(91,*) 'RAY LOCAL DIRECTIONS, Y-VECTOR'
   WRITE(91,10)
   WRITE(91,2) NSS_LRAY(10),NSS_LRAY(11),NSS_LRAY(12)
!       WRITE RAY GLOBALP DIR COSINES
   WRITE(91,*) 'AFTER SURFACE INTERACTION'
   WRITE(91,*) 'RAY GLOBAL DIRECTIONS'
   WRITE(91,8)
   WRITE(91,2) NSS_GRAYP(4),NSS_GRAYP(5),NSS_GRAYP(6)
   WRITE(91,*) 'RAY GLOBAL DIRECTIONS, X-VECTOR'
   WRITE(91,9)
   WRITE(91,2) NSS_GRAYP(7),NSS_GRAYP(8),NSS_GRAYP(9)
   WRITE(91,*) 'RAY GLOBAL DIRECTIONS, Y-VECTOR'
   WRITE(91,10)
   WRITE(91,2) NSS_GRAYP(10),NSS_GRAYP(11),NSS_GRAYP(12)
!       WRITE RAY LOCALP  DIR COSINES
   WRITE(91,*) 'RAY LOCAL DIRECTIONS'
   WRITE(91,8)
   WRITE(91,2) NSS_LRAYP(4),NSS_LRAYP(5),NSS_LRAYP(6)
   WRITE(91,*) 'RAY LOCAL DIRECTIONS, X-VECTOR'
   WRITE(91,9)
   WRITE(91,2) NSS_LRAYP(7),NSS_LRAYP(8),NSS_LRAYP(9)
   WRITE(91,*) 'RAY LOCAL DIRECTIONS, Y-VECTOR'
   WRITE(91,10)
   WRITE(91,2) NSS_LRAYP(10),NSS_LRAYP(11),NSS_LRAYP(12)
!       WRITE SURFACE NORMAL LOCAL DIR COSINES AT RAY INTERSECTION POINT
   WRITE(91,*) 'LOCAL SURFACE NORMALS'
   WRITE(91,11)
   WRITE(91,2) NSSLN,NSSMN,NSSNN
   WRITE(91,*) 'REFRACTIVE INDEX VALUES'
   WRITE(91,12)
   WRITE(91,13) NSS_GRAY(17),NSS_GRAYP(17)
!       WRITE RAY ENERGY AND NUMBER OF HITS
   WRITE(91,*) 'RELATIVE RAY ENERGY       RAY HITS'
   WRITE(91,3) NSSRAY_ENERGY,NSSRAY_HITS
3  FORMAT(D23.15,'  ',I10)
!       WRITE RAY LENGTH AND OPL FROM LAST INTERSECTION TO THIS
   WRITE(91,*) 'OPL AND PHYSICAL RAY LENGTH FROM LAST SURFACE'
   WRITE(91,13) NSS_OPL,NSS_RAYLENGTH
!       WRITE RAY POLARIZATION DATA
   WRITE(91,*) 'POLARIZATION ARRAY DATA'
   DO K=1,20
      WRITE(91,4) NSSRAY_RPOL(K),NSSRAY_IPOL(K)
   END DO
4  FORMAT(D23.15,','D23.15)
!       WRITE CURRENT WAVELENGTH VALUE
   WRITE(91,*) 'CURRENT WAVELENGTH IN MICRONS:'
!       WRITE PREVIOUS AND CURRENT INDEX VALUES
   WRITE(91,5) CURWAVELENGTH
   WRITE(91,*) 'PREVIOUS REAL AND IMAGINARY INDEX VALUES:'
   WRITE(91,6) PREVINDEXR,PREVINDEXI
   WRITE(91,*) 'CURRENT REAL AND IMAGINARY INDEX VALUES:'
   WRITE(91,6) CURINDEXR,CURINDEXI
5  FORMAT(D23.15)
6  FORMAT(D23.15,','D23.15)
   WRITE(91,*) '*************************************************'
   RETURN
END
SUBROUTINE NSSHT(J)
!       SHORT RAY HISTORY FILE
   USE NSSMOD
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
   INTEGER J,K
!       J IS RAY NUMBER
!       WRITE(OUTLYNE,*) J
!       CALL SHOWIT(1)
!       WRITE(OUTLYNE,*)
!    1  NSS_GRAY(1),NSS_GRAY(2),NSS_GRAY(3)
!       CALL SHOWIT(1)
   WRITE(92,1) J,&
   &NSS_GRAY(1),NSS_GRAY(2),NSS_GRAY(3),NSS_GRAY(4),NSS_GRAY(5)&
   &,NSS_GRAY(6),NSSWAVNUM,NSSRAY_HITS
1  FORMAT(I5,D23.15,D23.15,D23.15,D23.15,D23.15,D23.15,I2,I8)
   RETURN
END
SUBROUTINE NSSRHIST(J)
!       NON ANNOTATED RAY HISTORY FILE
   USE NSSMOD
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
   INTEGER J,K
   LOGICAL ERR
!       WRITE OBJECT,SURFACE,FAILURE CODES
   WRITE(48,*) J,NSSRAYFAILCODE(1),&
   &NSSRAYFAILCODE(2)
!       WRITE RAYDATA
   WRITE(48,*)&
   &(NSS_LRAY(K),K=1,17)
   WRITE(48,*)&
   &(NSS_LRAYP(K),K=1,17)
   WRITE(48,*)&
   &(NSS_GRAY(K),K=1,17)
   WRITE(48,*)&
   &(NSS_GRAYP(K),K=1,17)
!       WRITE RAY ENERGY AND NUMBER OF HITS
   WRITE(48,*) NSSRAY_ENERGY,NSSRAY_HITS
!       WRITE RAY POLARIZATION DATA
   WRITE(48,*) (NSSRAY_RPOL(K),K=1,20)
   WRITE(48,*) (NSSRAY_IPOL(K),K=1,20)
!       WRITE CURRENT WAVELENGTH VALUE
!       WRITE PREVIOUS AND CURRENT INDEX VALUES
   WRITE(48,*) CURWAVELENGTH
   WRITE(48,*) PREVINDEXR,PREVINDEXI
   WRITE(48,*) CURINDEXR,CURINDEXI
   RETURN
END
SUBROUTINE TAG_RHIST(K)
   USE NSSMOD
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
   INTEGER K
!       WRITE RAY NUMBER TO BOTH HISTORY FILES
   WRITE(48,1) K
   WRITE(91,1) K
1  FORMAT(I10)
   RETURN
END
SUBROUTINE NSSRAY
   USE NSSMOD
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
   INTEGER JJ,I

!       THIS IS AN INDIVIDUAL RAY TRACE LOOP WHICH GOES UNTIL THE RAY
!       RUNS OUT OF ENERGY OR HITS THE DETECTOR SURFACE.
!       A RAY RUNS OUT OF ENERGY WHEN IT HAS INTERSECTED
!       NSSSYSTEM(27) SURFACES OR WHEN ITS ENERGY DROPS BELOW OF THE VALUE NSSSYSTEM(26)
!       THE VARIABLE NSSRAY_HITS TRACKS THE NUMBER OF SURFACE HITS, THE VARIABLE NSS_ENERGY TRACKS
!       THE FRACTIONAL RAY ENERGY. DETSNUM TRACKS THE DETECTOR SURFACE AND AT
!       THE DETECTOR SURFACE, NSSSYSTEM(49)
!       OUTPUT RAY HISTORY FOR THE OBJECT SURFACE (SOURCE)
   CALL TAG_RHIST(RHISTN)
   CALL NSSRHIST(0)
   CALL NSSHIST(0)
   CALL NSSHT(0)
!       INITIALIZE OPL AND RAY LENGTHS TO ZERO
   NSS_OPL=0.0D0
   NSS_RAYLENGTH=0.0D0
   GO TO 11
!       FIRST TIME IN, WE DON'T RUN THE FOLLOWING TEST
10 CONTINUE
!       STATEMENT 10 IS THE RETURN POINT FOR THE NEXT ATTEMPTED RAY/SURFACE INTERSECTION
!       AND INTERACTION. CHECK TO SEE THAT THE RAY HAS ENOUGH ENERGY LEFT TO PROCEED.
   IF(NSSRAY_HITS.GE.INT(NSSSYSTEM(27)).OR.&
   &NSSRAY_ENERGY.LE.NSSSYSTEM(26).OR.JJ.EQ.MAXS+1) RETURN
!       RAY HAS DIED, RETURN TO NSSTRACE TO TRACE THE NEXT RAY
11 CONTINUE
!
!       WE HAVE THE STARTING RAY COORDINATES AND DIRECTION
!       COSINES IN GLOBAL AND LOCAL COORDINATES PLUS STARTING ENERGY, POLARIZATION
!       AND EXISTENCE FLAGS HAVE BEEN SET ALL IN NSSTRACE FOR A SPECIFIC RAY. WE KNOW
!       EVERYTHING ABOUT THE RAY AT THE SOURCE.
!
!       1. FIND OUT WHICH SURFACE NUMBER THE RAY STRIKES
!       WITH LEAST POSITIVE, NON ZERO OPTICAL PATH LENGTH.
!       THE RAY MUST FALL INSIDE THE SURFACE
!       BOUNDARY AND INSIDE THE ASSIGNED CLAP AND NOT INSIDE AN ASSIGED HOLE.
!       THAT OBJECT AND SURFACE NUMBER IS RETURNED VIA JJ
!
!       NOTE:
!       IN THIS SEARCH PROCESS, THE PERMANENT RAY DATA IS NOT CHANGED!
!
   I=LASTSUR
   LVECTOR(1:I)=0.0D0
   VECTORL(1:I)=0.0D0
   VECTORM(1:I)=0.0D0
   VECTORN(1:I)=0.0D0
   CALL NSS_FIND_SURFACE(JJ)
!
!       NOW INTERSECT SURFACE JJ
   IF(JJ.EQ.MAXS+1) THEN
!       SAVE PREVIOUS RAYS DATA
!       WE ARE GOING TO INTERSECT TRAVEL THE "TERMINAL RAY DISTANCE"
!       SAVED IN NSSSYSTEM(25)
! LOCAL
      RRX=NSS_LRAY(1)
      RRY=NSS_LRAY(2)
      RRZ=NSS_LRAY(3)
      RRX=RRX+(NSSSYSTEM(25)*RRL)
      RRY=RRY+(NSSSYSTEM(25)*RRM)
      RRZ=RRZ+(NSSSYSTEM(25)*RRN)
      NSS_LRAY(1)=RRX
      NSS_LRAY(2)=RRY
      NSS_LRAY(3)=RRZ
      NSS_LRAY(4)=RRL
      NSS_LRAY(5)=RRM
      NSS_LRAY(6)=RRN
      NSS_LRAY(7)=XRRL
      NSS_LRAY(8)=XRRM
      NSS_LRAY(9)=XRRN
      NSS_LRAY(10)=YRRL
      NSS_LRAY(11)=YRRM
      NSS_LRAY(12)=YRRN
! GLOBAL
      RRX=NSS_GRAY(1)
      RRY=NSS_GRAY(2)
      RRZ=NSS_GRAY(3)
      RRL=NSS_GRAY(4)
      RRM=NSS_GRAY(5)
      RRN=NSS_GRAY(6)
      XRRN=NSS_GRAY(7)
      XRRN=NSS_GRAY(8)
      XRRN=NSS_GRAY(9)
      YRRN=NSS_GRAY(10)
      YRRN=NSS_GRAY(11)
      YRRN=NSS_GRAY(12)
      RRX=RRX+(NSSSYSTEM(25)*RRL)
      RRY=RRY+(NSSSYSTEM(25)*RRM)
      RRZ=RRZ+(NSSSYSTEM(25)*RRN)
      NSS_GRAY(1)=RRX
      NSS_GRAY(2)=RRY
      NSS_GRAY(3)=RRZ
      NSS_GRAY(4)=RRL
      NSS_GRAY(5)=RRM
      NSS_GRAY(6)=RRN
      NSS_GRAY(7)=XRRN
      NSS_GRAY(8)=XRRN
      NSS_GRAY(9)=XRRN
      NSS_GRAY(10)=YRRN
      NSS_GRAY(11)=YRRN
      NSS_GRAY(12)=YRRN
!
      NSS_LRAYP(1:50)=NSS_LRAY(1:50)
      NSS_GRAYP(1:50)=NSS_GRAY(1:50)
   ELSE
!       SAVE PREVIOUS RAYS DATA
!       NOT JJ=0
!
!       CONVERT GLOBAL RAY DATA TO LOCAL RAY DATA
      CALL NSS_TRANSF(JJ)
      CALL NSS_TRANSFP(JJ)
      CALL NSS_HIT_SURFACE(JJ)
!
!       2. WE ARE NOW AT JJ, INTERACT THE RAY WITH THE SURFACE.
!       SET THE NSS ENERGYS FOR THE BEFORE INTERACTION RAYS
      NSS_GRAY(16)=NSSRAY_ENERGY
      NSS_LRAY(16)=NSSRAY_ENERGY
      CALL NSS_SURFACE_INTERACT(JJ)
      NSS_GRAY(17)=NSS_N
      NSS_LRAY(17)=NSS_N
      NSS_GRAYP(17)=NSS_NP
      NSS_LRAYP(17)=NSS_NP
      CALL NSS_TRANSF_BACK(JJ)
      CALL NSS_TRANSFP_BACK(JJ)
   END IF

!                       IF RAY FAILURE HAPPENED OR WE HIT UNIVERSE SPHERE
   IF(NSSRAYFAIL.AND.JJ.NE.MAXS+1) THEN
      NSSRAY_ENERGY=0.0D0
   END IF
!
!       3. WRITE THE RAY DATA IN THE RAY HISTORY FILE AND THEN RETURN TO STATEMENT 10
!       TO PROCEED WITH THE NEXT RAY/SURFACE INTERSECTION/INTERACTION
!
   NSSRAYFAILCODE(1)=JJ
   NSSRAY_HITS=NSSRAY_HITS+1
   CALL TAG_RHIST(RHISTN)
   CALL NSSRHIST(JJ)
   CALL NSSHIST(JJ)
   CALL NSSHT(JJ)
!       NOW THE "P" RAY DATA BECOMES THE UN"P" DATA FOR THE NEXT SURFACE
   NSS_GRAY(1)=NSS_GRAYP(1)
   NSS_GRAY(2)=NSS_GRAYP(2)
   NSS_GRAY(3)=NSS_GRAYP(3)
   NSS_GRAY(4)=NSS_GRAYP(4)
   NSS_GRAY(5)=NSS_GRAYP(5)
   NSS_GRAY(6)=NSS_GRAYP(6)
   NSS_GRAY(7)=NSS_GRAYP(7)
   NSS_GRAY(8)=NSS_GRAYP(8)
   NSS_GRAY(9)=NSS_GRAYP(9)
   NSS_GRAY(10)=NSS_GRAYP(10)
   NSS_GRAY(11)=NSS_GRAYP(11)
   NSS_GRAY(12)=NSS_GRAYP(12)
   NSS_GRAY(13)=NSS_GRAYP(13)
   NSS_GRAY(14)=NSS_GRAYP(14)
   NSS_GRAY(15)=NSS_GRAYP(15)
   NSS_LRAY(1)=NSS_LRAYP(1)
   NSS_LRAY(2)=NSS_LRAYP(2)
   NSS_LRAY(3)=NSS_LRAYP(3)
   NSS_LRAY(4)=NSS_LRAYP(4)
   NSS_LRAY(5)=NSS_LRAYP(5)
   NSS_LRAY(6)=NSS_LRAYP(6)
   NSS_LRAY(7)=NSS_LRAYP(7)
   NSS_LRAY(8)=NSS_LRAYP(8)
   NSS_LRAY(9)=NSS_LRAYP(9)
   NSS_LRAY(10)=NSS_LRAYP(10)
   NSS_LRAY(11)=NSS_LRAYP(11)
   NSS_LRAY(12)=NSS_LRAYP(12)
   NSS_LRAY(13)=NSS_LRAYP(13)
   NSS_LRAY(14)=NSS_LRAYP(14)
   NSS_LRAY(15)=NSS_LRAYP(15)
!
!       SET AFTER INTERACTION ENERGY LEVELS
   NSS_LRAYP(16)=NSSRAY_ENERGY
   NSS_GRAYP(16)=NSSRAY_ENERGY
   GO TO 10
END
SUBROUTINE NSS_HIT_SURFACE(J)
   USE NSSMOD
   use DATMAI
   INTEGER J
   real(real64) URAD
!       WE ARE NOW AT J
!       THE REFRACTIVE INDEX VALUES ARE:
!       WHERE 1 AND 2 REFER TO THE SPACES ON EACH SIDE OF THE SURFACE
   REALINDEX1=NSSALENS(100+NSSWAVNUM,J)
   REALINDEX2=NSSALENS(120+NSSWAVNUM,J)
   IMAGINDEX1=NSSALENS(110+NSSWAVNUM,J)
   IMAGINDEX2=NSSALENS(130+NSSWAVNUM,J)
!       SET SIMPLE LOCAL RAY DATA VALUES
   RRX=NSS_LRAY(1)
   RRY=NSS_LRAY(2)
   RRZ=NSS_LRAY(3)
   RRL=NSS_LRAY(4)
   RRM=NSS_LRAY(5)
   RRN=NSS_LRAY(6)
   XRRL=NSS_LRAY(7)
   XRRM=NSS_LRAY(8)
   XRRN=NSS_LRAY(9)
   YRRL=NSS_LRAY(10)
   YRRM=NSS_LRAY(11)
   YRRN=NSS_LRAY(12)
!       THE SURFACE DIR COSINES AT THE SURFACE VERTEX ARE:
   NSSLN=0.0D0
   NSSMN=0.0D0
   NSSNN=1.0D0
   IF(INT(NSSALENS(1,J)).EQ.1)  CALL NSSFLA(J)
   IF(INT(NSSALENS(1,J)).EQ.2)  CALL NSSASP(J)
   IF(INT(NSSALENS(1,J)).EQ.3)  CALL NSSANA(J)
   IF(INT(NSSALENS(1,J)).EQ.4) CALL NSSUSER(J)
   IF(INT(NSSALENS(1,J)).EQ.5)  CALL NSSMEM(J)
   IF(INT(NSSALENS(1,J)).EQ.6) CALL NSSTUB(J)
!        THE SINGLE INTERSECTION POINT IS, BY DEFINITION, CORRECT
!        NOW LOAD THE RAY DATA INTO THE LOCAL ARRAY
   NSS_LRAY(1)=RRX
   NSS_LRAY(2)=RRY
   NSS_LRAY(3)=RRZ
   NSS_LRAY(4)=RRL
   NSS_LRAY(5)=RRM
   NSS_LRAY(6)=RRN
   NSS_LRAY(7)=XRRL
   NSS_LRAY(8)=XRRM
   NSS_LRAY(9)=XRRN
   NSS_LRAY(10)=YRRL
   NSS_LRAY(11)=YRRM
   NSS_LRAY(12)=YRRN
   NSS_LRAY(13)=NSSLN
   NSS_LRAY(14)=NSSMN
   NSS_LRAY(15)=NSSNN
   RETURN
END
SUBROUTINE NSSCLP(JJ,SFI)
   USE NSSMOD
   USE GLOBALS
!
   use DATLEN
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
   real(real64) X,Y,Z,XN,YN,ZN,ROT1X,ROT1Z,ROT2Y,MDX,MDY,GAMGAM &
   &,ROT2Z,AX,AY,AZ,AALF,APHI,YMAXI,YMINI,XMAXI,XMINI &
   &,XNEW,YNEW,LKG,VIEPH,VIEAL,Z1,ANGLE,AN2,ZDELZ &
   &,X00,Y00,Z0,LX0,LY0,LZ0,ZCORR,SFI &
   &,X1,Y1,MX0,MY0,MZ0,NX0,NY0,NZ0,XID,YID
!
   INTEGER JJSTOP,J,IK,III,NO,JJ,ALLOERR,IIRUN,CLPTYPE
!
   INTEGER M1,M2,M3,M4,M5,IX,IY,I,II,IPST,K,L,POINT(1:2,1:3)
!
   INTEGER SURFACEI
!
   INTEGER COLPAS
!
!
   REAL CLPDAT
   DIMENSION CLPDAT(:,:)
   ALLOCATABLE :: CLPDAT
!
!     LOOK.VIEW TRANSFORMS

   ROT1X(AX,AZ,APHI)=((AX*DCOS(APHI))-(AZ*DSIN(APHI)))
   ROT1Z(AX,AZ,APHI)=((AX*DSIN(APHI))+(AZ*DCOS(APHI)))
!
   ROT2Z(AZ,AY,AALF)=((AZ*DCOS(AALF))+(AY*DSIN(AALF)))
   ROT2Y(AZ,AY,AALF)=((-AZ*DSIN(AALF))+(AY*DCOS(AALF)))
!
   DEALLOCATE(CLPDAT,STAT=ALLOERR)
   ALLOCATE(CLPDAT(0:360,3),STAT=ALLOERR)
!
   VIEPH=(PII/180.0D0)*VIEPHI
   VIEAL=(PII/180.0D0)*VIEALF
!
   CLPDAT(0:360,1:3)=0.0
!
   X=0.0D0
   Y=0.0D0
   XID=0.0D0
   YID=0.0D0
!
!       ALL INPUT IS OK, KEEP GOING
!     THE ARRAY CONTAINING SURFACE CLAP DATA IS:
!     CLPDAT(0:360,1:3)
!
!     THE FIRST DIMENSION IS FOR THE DATA POINT NUMBER
!     THE SECOND DIMENSION IS FOR THE X,Y AND Z COORDINATES OR THE POINT
!     THE THIRD IS THE SURFACE NUMBER
!
!     WE NEED TO LOAD THE ARRAY BEFORE PLOTTING
!
!     THE PROCEDURE IS:
!
!     CYCLE THROUGH ALL THE SURFACES
!
!     1. WE WILL CLOCK AROUND THE CLEAR APERTURE FROM THE LOCAL +X
!     TOWARD THE LOCAL +Y AXIS,
!     4.0 DEGREE INCREMENTS AS MEASURED
!     BY AN OBSERVER AT THE SURFACE VERTEX, IN THE LOCAL COORDINATE
!     SYSTEM OF THE SURFACE, WITH THE OBSERVER FACING THE -Z AXIS
!     DIRECTION
!
   DO J=0,360
      ANGLE=(DBLE(J)*PII)/180.0D0
      AN2=(DBLE(J+1)*PII)/180.0D0
!     NOW ALONG THIS ANGLED LINE, WHAT ARE THE X AND Y COORDINATES
!     OF THE CLEAR APERTURE
!
      CALL NSSCAO1(JJ,X,Y,ANGLE,AN2)
      X=X*SFI
      Y=Y*SFI
!
!     THE RETURNED X AND Y ARE WHERE THE SAG IS TO BE CALCULATED
!
!     2. USE APPROPRIATE CALLS TO THE NSSSAG ROUTINE
!
      CALL NSSSAG(JJ,X,Y,Z)
!
!     ASSIGN ARRAY VALUES BASED ON J VALUE
      CLPDAT(J,1)=X
      CLPDAT(J,2)=Y
      CLPDAT(J,3)=Z
   END DO
!
!     3. THE ARRAYS NOW HAVE LOCAL X,Y AND Z VALUES STORED IN THEM
!     CONVERT THE LOCAL X ANY Y CLAPS TO GLOBAL NUMBERS
!     GLOBAL VERTEX DATA IS
   DO I=0,360
      X00=NSSVERTEX(1,JJ)
      Y00=NSSVERTEX(2,JJ)
      Z0 =NSSVERTEX(3,JJ)
      LX0=NSSVERTEX(4,JJ)
      MX0=NSSVERTEX(5,JJ)
      NX0=NSSVERTEX(6,JJ)
      LY0=NSSVERTEX(7,JJ)
      MY0=NSSVERTEX(8,JJ)
      NY0=NSSVERTEX(9,JJ)
      LZ0=NSSVERTEX(10,JJ)
      MZ0=NSSVERTEX(11,JJ)
      NZ0=NSSVERTEX(12,JJ)
      X=CLPDAT(I,1)
      Y=CLPDAT(I,2)
      Z=CLPDAT(I,3)
!
      X1=X00+((LX0*(X))+(LY0*(Y))&
      &+(LZ0*(Z)))
      Y1=Y00+((MX0*(X))+(MY0*(Y))&
      &+(MZ0*(Z)))
      Z1=Z0+((NX0*(X))+(NY0*(Y))&
      &+(NZ0*(Z)))
      CLPDAT(I,1)=X1
      CLPDAT(I,2)=Y1
      CLPDAT(I,3)=Z1
   END DO
!
!     4. NOW DETERMINE THE BEST PLACE FOR THE ROTATION POINT FOR
!               PLOT LOOK/VIEW
!
   CALL NSSROT
!
!     5.  CONVERT THE GLOBAL X AND Y CLAP VALUES
!               USING THE LOOK/VIEW VALUES
   DO I=0,360
      X=CLPDAT(I,1)
      Y=CLPDAT(I,2)
      Z=CLPDAT(I,3)
      X=X-XROT
      Y=Y-YROT
      Z=Z-ZROT
      XN=ROT1X(X,Z,VIEPH)
      YN=Y
      ZN=ROT1Z(X,Z,VIEPH)
      X=XN
      Y=YN
      Z=ZN
!
      ZN=ROT2Z(Z,Y,VIEAL)
      YN=ROT2Y(Z,Y,VIEAL)
      XN=X
      CLPDAT(I,1)=XN
      CLPDAT(I,2)=YN
      CLPDAT(I,3)=ZN
   END DO
!
!     THE ARRAYS NOW HAVE GLOBAL SURFACE CLAP DATA IN THEM
!
!     6.IF NEEDED, DETERMINE SCALE FACTORS AND PLOT RANGE
!
   CALL NSSPLTSC
!
!     7.CYCLE THROUGH THE THE ARRAYS, APPLY SCALE FACTORS
!
!     RIGHT NOW,COORDINATES ARE IN WORLD COORDINATES
!     CONVERT THEM TO DEVICE INDEPENDENT GRAPHICS COORDINATES IN
!     TWO STEPS.
!
!     THE WORLD X PLOTS TO THE PLOTTER X
!     THE WORLD Y PLOTS TO THE PLOTTER Y
!
!     STEP 1: CONVERT USING AN APPROPRIATE SCALE FACTOR
!               CALCULATING AN APPROPRIATE FACTOR IF NECESSARY
!
   DO I=0,360
      CLPDAT(I,1)=(CLPDAT(I,1)/NSSSCFA)*1000.0D0
      CLPDAT(I,2)=(CLPDAT(I,2)/NSSSCFA)*1000.0D0
   END DO
!
!     8. APPLY THE XSHIFT AND YSHIFT VALUES
   DO I=0,360
      IF(LORIENT) CALL ORSHIFT
      CLPDAT(I,1)=CLPDAT(I,1)+DBLE(PXSHFT)
      CLPDAT(I,2)=CLPDAT(I,2)+3500.0D0+DBLE(PYSHFT)
   END DO
!
!     9. SET THE PLOT JUSTIFICATION IF NEEDED
!     IF THERE ARE X-OFFSETS (JUSTIFICATION) TO APPLY, DO THEM HERE.
!
!     NOW
   IF(RCL.EQ.1.OR.RCL.EQ.-1) THEN
      JUSOFF=500.0D0-((XMINI/NSSSCFA)*1000.0D0)
      RCL=-1
   ELSE
   END IF
   IF(RCL.EQ.2.OR.RCL.EQ.-2) THEN
      RCL=-2
      JUSOFF=5000.0D0
   ELSE
   END IF
   IF(RCL.EQ.3.OR.RCL.EQ.-3) THEN
      JUSOFF=9500.0D0-((XMAXI/NSSSCFA)*1000.0D0)
      RCL=-3
   ELSE
   END IF
!
   DO I=0,360
      CLPDAT(I,1)=CLPDAT(I,1)+JUSOFF
   END DO
!     9. PLOT GAMMA
!     IF THERE IS A NON-ZERO GAMMA SPECIFIED IN PLOT LOOK OR PLOT VIEW THEN
!     ROTATE IN GAMMA ON THE SCREEN ABOUT THE CENTER OF THE SCREEN
!     WHICH HAS COORDINATES X=5000.0D0,Y=3500.0D0
!
!     FIRST SHIFT THE COORDINATE ORIGIN TO THE CETER OF THE DISPLAY
!
   DO I=0,360
      CLPDAT(I,1)=CLPDAT(I,1)-5000.0D0
      CLPDAT(I,2)=CLPDAT(I,2)-3500.0D0
   END DO
!     THE SCREEN COORDINATE IN real(real64) IN THE SHIFTED COORDINATE
!     FRAME IS NOW X AND Y

   IF(DBLE(PGAMMA).NE.0.0D0) THEN
      LKG=(PII/180.0D0)*DBLE(PGAMMA)

      DO I=0,360
         X=CLPDAT(I,1)
         Y=CLPDAT(I,2)
         XNEW=((X*DCOS(LKG))-(Y*DSIN(LKG)))
         YNEW=((X*DSIN(LKG))+(Y*DCOS(LKG)))
         CLPDAT(I,1)=XNEW
         CLPDAT(I,2)=YNEW
      END DO
   ELSE
   END IF
!     THE ROTATION IS DONE, NOW SHIFT THE ORIGIN BACK TO THE BOTTOM
!     LEFT HAND CORNER
   DO I=0,360
      CLPDAT(I,1)=CLPDAT(I,1)+5000.0D0
      CLPDAT(I,2)=CLPDAT(I,2)+3500.0D0
   END DO
!
!     NOW DRAW THE CLAP
!     WITH THE PEN UP, GO TO THE STARTING PLOT POSITION
   IF(.NOT.PLEXIS) PLEXIS=.TRUE.
   DO J=0,360
!     PUT INSTRUCTIONS IN P1ARAY TO DROP PEN AND DRAW
      IF(J.EQ.0) IPST=0
      IF(J.NE.0) IPST=1
      IF(CLPDAT(J,1).GT.1.0D6) CLPDAT(J,1)=1.0D6
      IF(CLPDAT(J,2).GT.1.0D6) CLPDAT(J,2)=1.0D6
      IF(CLPDAT(J,1).LT.-1.0D6) CLPDAT(J,1)=-1.0D6
      IF(CLPDAT(J,2).LT.-1.0D6) CLPDAT(J,2)=-1.0D6
      IX=INT(CLPDAT(J,1))
      IY=INT(CLPDAT(J,2))
      P1ARAY(J,1,1)=IX
      P1ARAY(J,2,1)=IY
      P1ARAY(J,3,1)=IPST
      IF(.NOT.PLEXIS) PLEXIS=.TRUE.
   END DO
!     FINISHED WITH THAT CLAP, LIFT PEN
   IPST=0
!     NOW ISSUE THE PLOTTING COMMANDS STORED IN THE P1ARAY ARRAY
!
!     LINE TYPE SETTING
   COLPAS=COLCLP
   CALL MY_COLTYP(COLPAS)
   OLLNTP=LNTYPE
   LNTYPE=0
   FIXUP=.FALSE.
   DO IK=0,360
      CALL PENMV2(P1ARAY(IK,1,1),P1ARAY(IK,2,1),P1ARAY(IK,3,1))
   END DO
   LNTYPE=OLLNTP
!
   DEALLOCATE(CLPDAT,STAT=ALLOERR)
   RETURN
END
SUBROUTINE NSSHOL(JJ)
   USE NSSMOD
   USE GLOBALS
!
   use DATLEN
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
   real(real64) X,Y,Z,XN,YN,ZN,ROT1X,ROT1Z,ROT2Y,MDX,MDY,GAMGAM &
   &,ROT2Z,AX,AY,AZ,AALF,APHI,YMAXI,YMINI,XMAXI,XMINI &
   &,XNEW,YNEW,LKG,VIEPH,VIEAL,Z1,ANGLE,AN2,ZDELZ &
   &,X00,Y00,Z0,LX0,LY0,LZ0,ZCORR &
   &,X1,Y1,MX0,MY0,MZ0,NX0,NY0,NZ0,XID,YID
!
   INTEGER JJSTOP,J,IK,III,NO,JJ,ALLOERR,IIRUN,CLPTYPE
!
   INTEGER M1,M2,M3,M4,M5,IX,IY,I,II,IPST,K,L,POINT(1:2,1:3)
!
   INTEGER SURFACEI
!
   INTEGER COLPAS
!
!
   REAL CLPDAT
   DIMENSION CLPDAT(:,:)
   ALLOCATABLE :: CLPDAT
!
!     LOOK.VIEW TRANSFORMS

   ROT1X(AX,AZ,APHI)=((AX*DCOS(APHI))-(AZ*DSIN(APHI)))
   ROT1Z(AX,AZ,APHI)=((AX*DSIN(APHI))+(AZ*DCOS(APHI)))
!
   ROT2Z(AZ,AY,AALF)=((AZ*DCOS(AALF))+(AY*DSIN(AALF)))
   ROT2Y(AZ,AY,AALF)=((-AZ*DSIN(AALF))+(AY*DCOS(AALF)))
!
   DEALLOCATE(CLPDAT,STAT=ALLOERR)
   ALLOCATE(CLPDAT(0:360,3),STAT=ALLOERR)
!
   VIEPH=(PII/180.0D0)*VIEPHI
   VIEAL=(PII/180.0D0)*VIEALF
!
   CLPDAT(0:360,1:3)=0.0
!
   X=0.0D0
   Y=0.0D0
   XID=0.0D0
   YID=0.0D0
!
!       ALL INPUT IS OK, KEEP GOING
!     THE ARRAY CONTAINING SURFACE CLAP DATA IS:
!     CLPDAT(0:360,1:3)
!
!     THE FIRST DIMENSION IS FOR THE DATA POINT NUMBER
!     THE SECOND DIMENSION IS FOR THE X,Y AND Z COORDINATES OR THE POINT
!     THE THIRD IS THE SURFACE NUMBER
!
!     WE NEED TO LOAD THE ARRAY BEFORE PLOTTING
!
!     THE PROCEDURE IS:
!
!     CYCLE THROUGH ALL THE SURFACES
!
!     1. WE WILL CLOCK AROUND THE CLEAR APERTURE FROM THE LOCAL +X
!     TOWARD THE LOCAL +Y AXIS,
!     4.0 DEGREE INCREMENTS AS MEASURED
!     BY AN OBSERVER AT THE SURFACE VERTEX, IN THE LOCAL COORDINATE
!     SYSTEM OF THE SURFACE, WITH THE OBSERVER FACING THE -Z AXIS
!     DIRECTION
!
   DO J=0,360
      ANGLE=(DBLE(J)*PII)/180.0D0
      AN2=(DBLE(J+1)*PII)/180.0D0
!     NOW ALONG THIS ANGLED LINE, WHAT ARE THE X AND Y COORDINATES
!     OF THE CLEAR APERTURE
!
      CALL NSSCAO2(JJ,X,Y,ANGLE,AN2)
!
!     THE RETURNED X AND Y ARE WHERE THE SAG IS TO BE CALCULATED
!
!     2. USE APPROPRIATE CALLS TO THE NSSSAG ROUTINE
!
      CALL NSSSAG(JJ,X,Y,Z)
!
!     ASSIGN ARRAY VALUES BASED ON J VALUE
      CLPDAT(J,1)=X
      CLPDAT(J,2)=Y
      CLPDAT(J,3)=Z
   END DO
!
!     3. THE ARRAYS NOW HAVE LOCAL X,Y AND Z VALUES STORED IN THEM
!     CONVERT THE LOCAL X ANY Y CLAPS TO GLOBAL NUMBERS
!     GLOBAL VERTEX DATA IS
   DO I=0,360
      X00=NSSVERTEX(1,JJ)
      Y00=NSSVERTEX(2,JJ)
      Z0 =NSSVERTEX(3,JJ)
      LX0=NSSVERTEX(4,JJ)
      MX0=NSSVERTEX(5,JJ)
      NX0=NSSVERTEX(6,JJ)
      LY0=NSSVERTEX(7,JJ)
      MY0=NSSVERTEX(8,JJ)
      NY0=NSSVERTEX(9,JJ)
      LZ0=NSSVERTEX(10,JJ)
      MZ0=NSSVERTEX(11,JJ)
      NZ0=NSSVERTEX(12,JJ)
      X=CLPDAT(I,1)
      Y=CLPDAT(I,2)
      Z=CLPDAT(I,3)
!
      X1=X00+((LX0*(X))+(LY0*(Y))&
      &+(LZ0*(Z)))
      Y1=Y00+((MX0*(X))+(MY0*(Y))&
      &+(MZ0*(Z)))
      Z1=Z0+((NX0*(X))+(NY0*(Y))&
      &+(NZ0*(Z)))
      CLPDAT(I,1)=X1
      CLPDAT(I,2)=Y1
      CLPDAT(I,3)=Z1
   END DO
!
!     4. NOW DETERMINE THE BEST PLACE FOR THE ROTATION POINT FOR
!               PLOT LOOK/VIEW
!
   CALL NSSROT
!
!     5.  CONVERT THE GLOBAL X AND Y CLAP VALUES
!               USING THE LOOK/VIEW VALUES
   DO I=0,360
      X=CLPDAT(I,1)
      Y=CLPDAT(I,2)
      Z=CLPDAT(I,3)
      X=X-XROT
      Y=Y-YROT
      Z=Z-ZROT
      XN=ROT1X(X,Z,VIEPH)
      YN=Y
      ZN=ROT1Z(X,Z,VIEPH)
      X=XN
      Y=YN
      Z=ZN
!
      ZN=ROT2Z(Z,Y,VIEAL)
      YN=ROT2Y(Z,Y,VIEAL)
      XN=X
      CLPDAT(I,1)=XN
      CLPDAT(I,2)=YN
      CLPDAT(I,3)=ZN
   END DO
!
!     THE ARRAYS NOW HAVE GLOBAL SURFACE CLAP DATA IN THEM
!
!     6.IF NEEDED, DETERMINE SCALE FACTORS AND PLOT RANGE
!
   CALL NSSPLTSC
!
!     7.CYCLE THROUGH THE THE ARRAYS, APPLY SCALE FACTORS
!
!     RIGHT NOW,COORDINATES ARE IN WORLD COORDINATES
!     CONVERT THEM TO DEVICE INDEPENDENT GRAPHICS COORDINATES IN
!     TWO STEPS.
!
!     THE WORLD X PLOTS TO THE PLOTTER X
!     THE WORLD Y PLOTS TO THE PLOTTER Y
!
!     STEP 1: CONVERT USING AN APPROPRIATE SCALE FACTOR
!               CALCULATING AN APPROPRIATE FACTOR IF NECESSARY
!
   DO I=0,360
      CLPDAT(I,1)=(CLPDAT(I,1)/NSSSCFA)*1000.0D0
      CLPDAT(I,2)=(CLPDAT(I,2)/NSSSCFA)*1000.0D0
   END DO
!
!     8. APPLY THE XSHIFT AND YSHIFT VALUES
   DO I=0,360
      IF(LORIENT) CALL ORSHIFT
      CLPDAT(I,1)=CLPDAT(I,1)+DBLE(PXSHFT)
      CLPDAT(I,2)=CLPDAT(I,2)+3500.0D0+DBLE(PYSHFT)
   END DO
!
!     9. SET THE PLOT JUSTIFICATION IF NEEDED
!     IF THERE ARE X-OFFSETS (JUSTIFICATION) TO APPLY, DO THEM HERE.
!
!     NOW
   IF(RCL.EQ.1.OR.RCL.EQ.-1) THEN
      JUSOFF=500.0D0-((XMINI/NSSSCFA)*1000.0D0)
      RCL=-1
   ELSE
   END IF
   IF(RCL.EQ.2.OR.RCL.EQ.-2) THEN
      RCL=-2
      JUSOFF=5000.0D0
   ELSE
   END IF
   IF(RCL.EQ.3.OR.RCL.EQ.-3) THEN
      JUSOFF=9500.0D0-((XMAXI/NSSSCFA)*1000.0D0)
      RCL=-3
   ELSE
   END IF
!
   DO I=0,360
      CLPDAT(I,1)=CLPDAT(I,1)+JUSOFF
   END DO
!     9. PLOT GAMMA
!     IF THERE IS A NON-ZERO GAMMA SPECIFIED IN PLOT LOOK OR PLOT VIEW THEN
!     ROTATE IN GAMMA ON THE SCREEN ABOUT THE CENTER OF THE SCREEN
!     WHICH HAS COORDINATES X=5000.0D0,Y=3500.0D0
!
!     FIRST SHIFT THE COORDINATE ORIGIN TO THE CETER OF THE DISPLAY
!
   DO I=0,360
      CLPDAT(I,1)=CLPDAT(I,1)-5000.0D0
      CLPDAT(I,2)=CLPDAT(I,2)-3500.0D0
   END DO
!     THE SCREEN COORDINATE IN real(real64) IN THE SHIFTED COORDINATE
!     FRAME IS NOW X AND Y

   IF(DBLE(PGAMMA).NE.0.0D0) THEN
      LKG=(PII/180.0D0)*DBLE(PGAMMA)

      DO I=0,360
         X=CLPDAT(I,1)
         Y=CLPDAT(I,2)
         XNEW=((X*DCOS(LKG))-(Y*DSIN(LKG)))
         YNEW=((X*DSIN(LKG))+(Y*DCOS(LKG)))
         CLPDAT(I,1)=XNEW
         CLPDAT(I,2)=YNEW
      END DO
   ELSE
   END IF
!     THE ROTATION IS DONE, NOW SHIFT THE ORIGIN BACK TO THE BOTTOM
!     LEFT HAND CORNER
   DO I=0,360
      CLPDAT(I,1)=CLPDAT(I,1)+5000.0D0
      CLPDAT(I,2)=CLPDAT(I,2)+3500.0D0
   END DO
!
!     NOW DRAW THE CLAP
!     WITH THE PEN UP, GO TO THE STARTING PLOT POSITION
   IF(.NOT.PLEXIS) PLEXIS=.TRUE.
   DO J=0,360
!     PUT INSTRUCTIONS IN P1ARAY TO DROP PEN AND DRAW
      IF(J.EQ.0) IPST=0
      IF(J.NE.0) IPST=1
      IF(CLPDAT(J,1).GT.1.0D6) CLPDAT(J,1)=1.0D6
      IF(CLPDAT(J,2).GT.1.0D6) CLPDAT(J,2)=1.0D6
      IF(CLPDAT(J,1).LT.-1.0D6) CLPDAT(J,1)=-1.0D6
      IF(CLPDAT(J,2).LT.-1.0D6) CLPDAT(J,2)=-1.0D6
      IX=INT(CLPDAT(J,1))
      IY=INT(CLPDAT(J,2))
      P1ARAY(J,1,1)=IX
      P1ARAY(J,2,1)=IY
      P1ARAY(J,3,1)=IPST
      IF(.NOT.PLEXIS) PLEXIS=.TRUE.
   END DO
!     FINISHED WITH THAT CLAP, LIFT PEN
   IPST=0
!     NOW ISSUE THE PLOTTING COMMANDS STORED IN THE P1ARAY ARRAY
!
!     LINE TYPE SETTING
   COLPAS=COLCLP
   CALL MY_COLTYP(COLPAS)
   OLLNTP=LNTYPE
   LNTYPE=0
   FIXUP=.FALSE.
   DO IK=0,360
      CALL PENMV2(P1ARAY(IK,1,1),P1ARAY(IK,2,1),P1ARAY(IK,3,1))
   END DO
   LNTYPE=OLLNTP
!
   DEALLOCATE(CLPDAT,STAT=ALLOERR)
   RETURN
END
SUBROUTINE NSSPRO(JJ,V3)
   USE NSSMOD
   USE GLOBALS
!
   use DATLEN
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS ROUTINE DOES THE PLOTTING OF SURFACE PROFILES FOR THE NSS DATABASE
!
   real(real64) X,Y,Z,XN,YN,ZN,ROT1X,ROT1Z,ROT2Y,XX1,XX2,YY1,V1,V2,V3,&
   &ROT2Z,AX,AY,AZ,AALF,APHI,YMAXI,YMINI,XMAXI,XMINI,RANGE &
   &,XNEW,YNEW,LKG,VIEPH,VIEAL,Z1,YY2,AX1,AX2,AY1,AY2,ZDELZ &
   &,X00,Y00,Z0,LX0,LY0,LZ0,ACALL1,ACALL2,XM,YM,ZCORR,ZDELZ1 &
   &,X1,X2,Y1,Y2,SLOPE,DELXX,DELYY,MX0,MY0,MZ0,NX0,NY0,NZ0
!
   LOGICAL ALT,VERT,INSIT,YESONE1,YESONE2,YESONE3,YESONE4 &
   &,YESONE5,YESONE6,NSSINSIDEIT
!
   COMMON/YESSIR/YESONE1,YESONE2,YESONE3,YESONE4,YESONE5,YESONE6
!
   EXTERNAL NSSINSIDEIT
!
   INTEGER M1,M2,M3,M4,CAFLG,COFLG,J,K,IK,III,NO,ALLOERR &
   &,COLPAS,JJ
!
   real(real64) XMIN,YMIN,XMAX,YMAX,ZA,ZB,ZM,FRACRAD,&
   &XMINO,YMINO,XMAXO,YMAXO,DRAPRO,THETA &
   &,TEMP,YMIN2,XMIN2,YMAX2,XMAX2,CALL1,CALL2
!
   INTEGER IX,IY,I,II,IPST
!
!
   real(real64) PRO
!
   DIMENSION PRO(:,:)
   ALLOCATABLE :: PRO
!     LOOK.VIEW TRANSFORMS

   ROT1X(AX,AZ,APHI)=((AX*DCOS(APHI))-(AZ*DSIN(APHI)))
   ROT1Z(AX,AZ,APHI)=((AX*DSIN(APHI))+(AZ*DCOS(APHI)))
!
   ROT2Z(AZ,AY,AALF)=((AZ*DCOS(AALF))+(AY*DSIN(AALF)))
   ROT2Y(AZ,AY,AALF)=((-AZ*DSIN(AALF))+(AY*DCOS(AALF)))
!
   M1=360
   M2=4
   DEALLOCATE (PRO,STAT=ALLOERR)
   ALLOCATE (PRO(M1,M2),STAT=ALLOERR)
   PRO(1:360,1:4)=0.0D0
!
   X=0.0D0
   Y=0.0D0
!
   VIEPH=(PII/180.0D0)*VIEPHI
   VIEAL=(PII/180.0D0)*VIEALF
!
!       USES GLOBAL NSSVERTEX ARRAY
!
!     CONVERT THETA TO RADIAN MEASURE
   IF(V3.GE.89.95D0.AND.V3.LE.90.05D0) V3=90.001D0
   IF(V3.GE.269.95D0.AND.V3.LE.270.05D0) V3=270.001D0
   THETA=V3*PII/180.0D0
!     THE ARRAY CONTAINING SURFACE PROFILE DATA ARE:
!
!     PRO(1:360,1:3)
!
!     THE FIRST DIMENSION IS FOR THE DATA POINT NUMBER
!     THE SECOND DIMENSION IS FOR THE X,Y AND Z COORDINATES OR THE POINT
!
!     WE NEED TO LOAD THE ARRAY BEFORE PLOTTING
!
!     THE PROCEDURE IS:
!     1. DETERMINE THE MAXIMUM AND MINIMUM LOCAL X AND Y
!               COORDINATES FOR A SURFACE FOR WHICH THE PROFILE
!               IS TO BE CALCULATED.
!
!     CYCLE THROUGH ALL THE SURFACES BUT SKIP SURFACES WITH MULTIPLE
!     APERTURE DEFS ON IT
!
   II=JJ
   YESONE1=.FALSE.
   YESONE2=.FALSE.
   YESONE3=.FALSE.
   YESONE4=.FALSE.
   YESONE5=.FALSE.
   YESONE6=.FALSE.
   X1=0.0D0
   X2=0.0D0
   Y1=0.0D0
   Y2=0.0D0
   AX1=0.0D0
   AX2=0.0D0
   AY1=0.0D0
   AY2=0.0D0
   XX1=0.0D0
   XX2=0.0D0
   YY1=0.0D0
   YY2=0.0D0
   XMIN=0.0D0
   YMIN=0.0D0
   XMAX=0.0D0
   YMAX=0.0D0
   XMIN2=0.0D0
   YMIN2=0.0D0
   XMAX2=0.0D0
   YMAX2=0.0D0
   XMINO=0.0D0
   YMINO=0.0D0
   XMAXO=0.0D0
   YMAXO=0.0D0
   CAFLG=0
   COFLG=0
   III=II
!
!     NOW FOR THE II SURFACE WE CALCULATE ALL THE END POINTS
!
   ZDELZ=0.0D0
   CALL NSSCAOJK(YMIN,XMIN,YMAX,XMAX,&
   &YMINO,XMINO,YMAXO,XMAXO,CAFLG,&
   &COFLG,III,&
   &YMIN2,XMIN2,YMAX2,XMAX2,THETA,ZDELZ)
!
!     NOW WE HAVE THE END POINTS, CYCLE THROUGH ALL FOUR PAIRS
!
!     2. USE APPROPRIATE CALLS TO THE NSSSAG ROUTINE
!               TO CALCULATE THE SAG AND MAKE
!               CERTAIN THE SIGN IS CORRECT FOR A LOCAL Z COORDINATE
!
   X1=XMIN
   Y1=YMIN
   X2=XMAX
   Y2=YMAX
   AX1=XMIN2
   AY1=YMIN2
   AX2=XMAX2
   AY2=YMAX2
   XX1=XMINO
   YY1=YMINO
   XX2=XMAXO
   YY2=YMAXO
!     SET UP THE LINE SLOPE AND THE INITIAL DELXX VALUE
   IF((X2-X1).NE.0.0D0)SLOPE=(Y2-Y1)/(X2-X1)
   VERT=.FALSE.
   IF((X2-X1).EQ.0.0D0) VERT=.TRUE.
!
   DELXX=(X2-X1)/(360.0D0-1.0D0)
   DELYY=(Y2-Y1)/(360.0D0-1.0D0)
!     NOW WE HAVE THE END POINTS, CYCLE THROUGH ALL THE PAIRS AND LOAD
!     ALL THE ARRAYS WITH SURFACE LOCAL X,Y AND Z DATA
!
   DO J=1,360
      IF(J.EQ.1) THEN
         X=X1
      ELSE
         X=X+DELXX
      END IF
      IF(.NOT.VERT) Y=(SLOPE*(X-X1))+Y1
      IF(VERT) THEN
         IF(J.EQ.1) THEN
            Y=Y1
         ELSE
            Y=Y+DELYY
         END IF
      ELSE
      END IF
!
      III=II
      ACALL1=X
      ACALL2=Y
      ALT=.FALSE.
      ALT=.FALSE.
      IF(X.LT.AX1) THEN
         ACALL1=AX1
         ALT=.TRUE.
      END IF
      IF(X.GT.AX2) THEN
         ACALL1=AX2
         ALT=.TRUE.
      END IF
      IF(Y.LT.AY1) THEN
         ACALL2=AY1
         ALT=.TRUE.
      END IF
      IF(Y.GT.AY2) THEN
         ACALL2=AY2
         ALT=.TRUE.
      END IF
      IF(NSSALENS(19,III).EQ.1.0D0) THEN
!     CIRCULAR CLEAR APERTURE
         ALT=.FALSE.
         IF(X.LT.AX1) THEN
            ACALL1=AX1
            ALT=.TRUE.
         END IF
         IF(X.GT.AX2) THEN
            ACALL1=AX2
            ALT=.TRUE.
         END IF
         IF(Y.LT.AY1) THEN
            ACALL2=AY1
            ALT=.TRUE.
         END IF
         IF(Y.GT.AY2) THEN
            ACALL2=AY2
            ALT=.TRUE.
         END IF
      END IF
      CALL NSSSAG(III,ACALL1,ACALL2,Z)
      IF(NSSALENS(19,III).NE.1.0D0.OR.NSSALENS(19,III).EQ.1.0D0 &
      &.AND.NSSALENS(23,III).NE.0.0D0.OR.ALENS(19,III).EQ.1.0D0.AND.&
      &NSSALENS(24,III).NE.0.0D0) THEN
         FRACRAD=0.0D0
      ELSE
         IF(NSSALENS(20,III).NE.NSSALENS(21,III)) THEN
            FRACRAD=((DSQRT((X**2)+(Y**2))-NSSALENS(21,III))/&
            &(NSSALENS(20,III)-NSSALENS(21,III)))
            IF(FRACRAD.LE.0.0D0) FRACRAD=0.0D0
         ELSE
            FRACRAD=0.0D0
         END IF
      END IF
      ZDELZ1=ZDELZ*FRACRAD
      Z=Z+ZDELZ1
!
!     ASSIGN ARRAY VALUES
      PRO(J,1)=X
      PRO(J,2)=Y
      IF(J.GT.1) THEN
         XM=PRO(J-1,1)
         YM=PRO(J-1,2)
      ELSE
         XM=PRO(J,1)
         YM=PRO(J,2)
      END IF
!     DO WE HAVE TO DO A FIX FOR A HOLE
!
! IF XM,YM AND X,Y ARE INSIDE A HOLE DRAPRO=0.0D0
!                  OTHERWISE
!                  DRAPRO=1.0D0

      INSIT=.FALSE.
      INSIT=NSSINSIDEIT(II,X,Y,XM,YM)
      IF(INSIT) DRAPRO=0.0D0
      IF(.NOT.INSIT)DRAPRO=1.0D0
      PRO(J,3)=Z
      PRO(J,4)=DRAPRO
!
!               CYCLE THROUGH THE NEXT DATA PAIR
   END DO
!
!     3. THE ARRAYS NOW HAVE LOCAL X,Y AND Z VALUES STORED IN THEM
!     CONVERT THE LOCAL X ANY Y PROFILES TO GLOBAL NUMBERS
!     GLOBAL VERTEX DATA IS
   II=JJ
   DO I=1,360
      X00=NSSVERTEX(1,II)
      Y00=NSSVERTEX(2,II)
      Z0= NSSVERTEX(3,II)
      LX0=NSSVERTEX(4,II)
      MX0=NSSVERTEX(5,II)
      NX0=NSSVERTEX(6,II)
      LY0=NSSVERTEX(7,II)
      MY0=NSSVERTEX(8,II)
      NY0=NSSVERTEX(9,II)
      LZ0=NSSVERTEX(10,II)
      MZ0=NSSVERTEX(11,II)
      NZ0=NSSVERTEX(12,II)
      X=PRO(I,1)
      Y=PRO(I,2)
      Z=PRO(I,3)
!
      X1=X00+((LX0*(X))+(LY0*(Y))&
      &+(LZ0*(Z)))
      Y1=Y00+((MX0*(X))+(MY0*(Y))&
      &+(MZ0*(Z)))
      Z1=Z0+((NX0*(X))+(NY0*(Y))&
      &+(NZ0*(Z)))
      PRO(I,1)=X1
      PRO(I,2)=Y1
      PRO(I,3)=Z1
   END DO
!
!     4. NOW DETERMINE THE BEST PLACE FOR THE ROTATION POINT FOR
!               PLOT LOOK/VIEW
!
   CALL NSSROT
!
!     5.  CONVERT THE GLOBAL X ANY Y PROFILES
!               USING THE LOOK/VIEW VALUES
   II=JJ
   DO I=1,360
      X=PRO(I,1)
      Y=PRO(I,2)
      Z=PRO(I,3)
      X=X-XROT
      Y=Y-YROT
      Z=Z-ZROT
      XN=ROT1X(X,Z,VIEPH)
      YN=Y
      ZN=ROT1Z(X,Z,VIEPH)
      X=XN
      Y=YN
      Z=ZN
!
      ZN=ROT2Z(Z,Y,VIEAL)
      YN=ROT2Y(Z,Y,VIEAL)
      XN=X
      PRO(I,1)=XN
      PRO(I,2)=YN
      PRO(I,3)=ZN
   END DO
!
!     THE ARRAYS NOW HAVE GLOBAL SURFACE PROFILE DATA IN THEM
!
!     6.IF NEEDED, DETERMINE SCALE FACTORS AND PLOT RANGE
!
   CALL NSSPLTSC
!
!     7.CYCLE THROUGH THE THE ARRAYS, APPLY SCALE FACTORS
!
!     RIGHT NOW,COORDINATES ARE IN WORLD COORDINATES
!     CONVERT THEM TO DEVICE INDEPENDENT GRAPHICS COORDINATES IN
!     TWO STEPS.
!
!     THE WORLD X PLOTS TO THE PLOTTER X
!     THE WORLD Y PLOTS TO THE PLOTTER Y
!
!     STEP 1: CONVERT USING AN APPROPRIATE SCALE FACTOR
!               CALCULATING AN APPROPRIATE FACTOR IF NECESSARY
!
   II=JJ
   DO I=1,360
      PRO(I,1)=(PRO(I,1)/NSSSCFA)*1000.0D0
      PRO(I,2)=(PRO(I,2)/NSSSCFA)*1000.0D0
   END DO
!
!     8. APPLY THE PLOT XSHIFT AND YSHIFT VALUES
   DO I=1,360
      II=JJ
      IF(LORIENT) CALL ORSHIFT
      PRO(I,1)=PRO(I,1)+DBLE(PXSHFT)
      PRO(I,2)=PRO(I,2)+3500.0D0+DBLE(PYSHFT)
   END DO
!
!     9. SET THE PLOT JUSTIFICATION IF NEEDED
!     IF THERE ARE X-OFFSETS (JUSTIFICATION) TO APPLY, DO THEM HERE.
!
!     NOW
   IF(RCL.EQ.1.OR.RCL.EQ.-1) THEN
      JUSOFF=500.0D0-((XMINI/NSSSCFA)*1000.0D0)
      RCL=-1
   ELSE
   END IF
   IF(RCL.EQ.2.OR.RCL.EQ.-2) THEN
      RCL=-2
      JUSOFF=5000.0D0
   ELSE
   END IF
   IF(RCL.EQ.3.OR.RCL.EQ.-3) THEN
      JUSOFF=9500.0D0-((XMAXI/NSSSCFA)*1000.0D0)
      RCL=-3
   ELSE
   END IF
!
   DO I=1,360
      II=JJ
      PRO(I,1)=PRO(I,1)+JUSOFF
   END DO
!     9. PLOT GAMMA
!     IF THERE IS A NON-ZERO GAMMA SPECIFIED IN PLOT LOOK OR PLOT VIEW THEN
!     ROTATE IN GAMMA ON THE SCREEN ABOUT THE CENTER OF THE SCREEN
!     WHICH HAS COORDINATES X=5000.0D0,Y=3500.0D0
!
!     FIRST SHIFT THE COORDINATE ORIGIN TO THE CETER OF THE DISPLAY
!
   DO I=1,360
      II=JJ
      PRO(I,1)=PRO(I,1)-5000.0D0
      PRO(I,2)=PRO(I,2)-3500.0D0
   END DO
!     THE SCREEN COORDINATE IN real(real64) IN THE SHIFTED COORDINATE
!     FRAME IS NOW X AND Y

   IF(DBLE(PGAMMA).NE.0.0D0) THEN
      LKG=(PII/180.0D0)*DBLE(PGAMMA)

      DO I=1,360
         II=JJ
         X=PRO(I,1)
         Y=PRO(I,2)
         XNEW=((X*DCOS(LKG))-(Y*DSIN(LKG)))
         YNEW=((X*DSIN(LKG))+(Y*DCOS(LKG)))
         PRO(I,1)=XNEW
         PRO(I,2)=YNEW
      END DO
   END IF
!     THE ROTATION IS DONE, NOW SHIFT THE ORIGIN BACK TO THE BOTTOM
!     LEFT HAND CORNER
   DO I=1,360
      II=JJ
      PRO(I,1)=PRO(I,1)+5000.0D0
      PRO(I,2)=PRO(I,2)+3500.0D0
   END DO
!
   I=JJ
!     NOW DRAW THE X PROFILE OF THE CLAP AT SURFACE I
!     WITH THE PEN UP, GO TO THE STARTING PLOT POSITION
   IF(.NOT.PLEXIS) PLEXIS=.TRUE.
!     FIRST CLAP PROFILE
   DO J=1,360
!     PUT INSTRUCTIONS IN P1ARAY TO DROP PEN AND DRAW
      DRAPRO=PRO(J,4)
      IF(J.EQ.1) IPST=0
      IF(J.GT.1.AND.DRAPRO.EQ.1.0D0.AND.PRO((J-1),4).EQ.0.0D0) IPST=0
      IF(J.GT.1.AND.DRAPRO.EQ.1.0D0.AND.PRO((J-1),4).EQ.1.0D0) IPST=1
      IF(J.GT.1.AND.DRAPRO.EQ.0.0D0) IPST=0
      IF(PRO(J,1).GT.1.0D6) PRO(J,1)=1.0D6
      IF(PRO(J,2).GT.1.0D6) PRO(J,2)=1.0D6
      IF(PRO(J,1).LT.-1.0D6) PRO(J,1)=-1.0D6
      IF(PRO(J,2).LT.-1.0D6) PRO(J,2)=-1.0D6
      IX=INT(PRO(J,1))
      IY=INT(PRO(J,2))
      P1ARAY(J,1,1)=IX
      P1ARAY(J,2,1)=IY
      P1ARAY(J,3,1)=IPST
      IF(.NOT.PLEXIS) PLEXIS=.TRUE.
   END DO
!
!     LINE TYPE SETTING
   COLPAS=COLPRO
   CALL MY_COLTYP(COLPAS)
   OLLNTP=LNTYPE
   LNTYPE=0
   FIXUP=.FALSE.
   DO IK=1,360
      CALL PENMV2(P1ARAY(IK,1,1),P1ARAY(IK,2,1),P1ARAY(IK,3,1))
   END DO
!     FINISHED WITH THAT PROFILE, LIFT PEN
   IPST=0
   LNTYPE=OLLNTP
   DEALLOCATE (PRO,STAT=ALLOERR)
   RETURN
END
FUNCTION NSSINSIDEIT(I,XONE,YONE,XTWO,YTWO)
   USE NSSMOD
!
   use DATLEN
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
   EXTERNAL INSID1,INSID2
!
   INTEGER I,CAFLG,COFLG,N,ITIIT,III
!
   real(real64) X,Y,XONE,YONE,XTWO,YTWO,ANGLE,&
   &XR,YR,LS,RS,XRD,YRD,X1,X2,X3,X4,Y1,Y2,Y3,Y4,&
   &X5,X6,X7,X8,Y5,Y6,Y7,Y8,XC1,XC2,XC3,XC4,YC1,YC2,&
   &A22,YC3,YC4,RAD2,MAXSID,CS1,CS2,CS3,CS4
!
   LOGICAL NSSINSIDEIT,INS,INSID1,INSID2,INITIT(1:2)
!
   INTEGER CAERAS,COERAS
!
   COMMON/CACO/CAERAS,COERAS,LS
!
!     VARIABLES FOR SPOT TRACING
!
   LOGICAL TCLPRF,SPDTRA
!
   COMMON/SPRA1/SPDTRA
!
!       I IS THE CURRENT SURFACE NUMBER
!
!       THIS ROUTINE SETS THE FLAGS
!       CAERAS AND COERAS ARE
!       FLAGS SET IF THE NEXT CURRENT SURFACE HAS A COBS OR
!       CLAP ERASE.
!
   COFLG=INT(NSSALENS(25,I))
!       THERE IS COBS, PROCEED CHECKING
!
   NSSINSIDEIT=.FALSE.
!
   DO ITIIT=1,2
      INITIT(ITIIT)=.FALSE.
      IF(ITIIT.EQ.1) THEN
         X=XONE
         Y=YONE
      ELSE
         X=XTWO
         Y=YTWO
      END IF
!
!******************************************************************
!       COFLG NON-ZERO, RESOLVE ALL COBS BLOCKAGES NOW
!******************************************************************
!
!       COFLG=1 CIRCULAR COBS, DOES IT STOP THE RAY
      IF(COFLG.EQ.1) THEN
!
         LS=0.0D0
!       CIRCULAR COBS EQUATION IS:
!
!       (X)**2 + (Y)**2 = R**2
!
!       SUB X AND Y IN THE LEFT SIDE. IF THE LEFT SIDE IS
!       LESS THAN OR EQUAL TO THE RIGHT SIDE, THE RAY IS BLOCKED
!       ELSE IT IS NOT BLOCKED.
!
!       IF NON-ZERO COBS DECENTRATIONS EXISTS, THEY MUST BE CONSIDERED
!       IN COBS CHECKING. WE CONVERT THE RAY COORDINATES X AND Y
!       TO XR AND YR IN THE COORDINATE SYSTEM OF THE DECENTERED
!       OBSCURATION. REMEMBER.
!
         XR=X-ALENS(28,I)
         YR=Y-ALENS(29,I)
!
         LS=DSQRT((XR**2)+(YR**2))
!
         RS=DSQRT(ALENS(26,I)**2)-AIMTOL
         IF(REAL(LS).LT.REAL(RS)) THEN
!       RAY IS BLOCKED BY COBS ON SURFACE I
            LS=10.0D0
            INITIT(ITIIT)=.TRUE.
         ELSE
            LS=0.0D0
            INITIT(ITIIT)=.FALSE.
         END IF
!       COFLG NOT 1
      END IF
!
!       COFLG=2 RECTANGULAR OBSCURATION, DOES IT STOP THE RAY
      IF(COFLG.EQ.2) THEN
!
         LS=0.0D0
         INITIT(ITIIT)=.FALSE.
!
!       IN THE COORDINATE SYSTEM OF THE RECTANGLE, THE CORNER
!       COORDINATES ARE:
         X1=-NSSALENS(26,I)-AIMTOL
         Y1=NSSALENS(27,I)+AIMTOL
         X2=-NSSALENS(26,I)-AIMTOL
         Y2=-NSSALENS(27,I)-AIMTOL
         X3=NSSALENS(26,I)+AIMTOL
         Y3=-NSSALENS(27,I)-AIMTOL
         X4=NSSALENS(26,I)+AIMTOL
         Y4=NSSALENS(27,I)+AIMTOL
!
         XRD=X
         YRD=Y

!       IF NON-ZERO COBS DECENTRATIONS EXISTS, THEY MUST BE CONSIDERED
!       IN COBS CHECKING. WE CONVERT THE RAY COORDINATES X AND Y
!       TO XRD AND YRD IN THE COORDINATE SYSTEM OF THE DECENTERED
!       OBSCURATION. REMEMBER.
!
         XRD=XRD-NSSALENS(28,I)
         YRD=YRD-NSSALENS(29,I)
!
!       IF A NON-ZERO COBS TILT EXISTS, IT MUST BE CONSIDERED
!       IN COBS CHECKING. WE CONVERT THE RAY COORDINATES XRD AND YRD
!       TO XR AND YR IN THE COORDINATE SYSTEM OF THE ROTATED
!       OBSCURATION. REMEMBER. GAMMA ROTATION OF A CLAP OR
!       COBS HAS THE SAME SIGN AS IN A SURFACE ROTATION

         A22=NSSALENS(30,I)*PII/180.0D0
         XR=(XRD*DCOS(A22))+(YRD*DSIN(A22))
         YR=(YRD*DCOS(A22))-(XRD*DSIN(A22))
!
!
!
!       ARE THE POINTS XR AND YR ON THE RECTANGLE OR OUTSIDE
!       IF YES, SET LS=10.0D0
!       IF NO SET LS=0.0D0
         XT(1)=X1
         YT(1)=Y1
         XT(2)=X2
         YT(2)=Y2
         XT(3)=X3
         YT(3)=Y3
         XT(4)=X4
         YT(4)=Y4
         NP=4
         X0=XR
         Y0=YR
         INS=INSID2()
         IF(INS) THEN
!       RAY  BLOCKED
            LS=10.0D0
            INITIT(ITIIT)=.TRUE.
         ELSE
            LS=0.0D0
            INITIT(ITIIT)=.FALSE.
!       RAY NOT BLOCKED
         END IF
!
!       COFLG NOT 2
      END IF
!
!       COFLG=3 ELLIPTICAL COBS, DOES IT STOP THE RAY
      IF(COFLG.EQ.3) THEN
!
         LS=0.0D0
!       ELLIPTICAL COBS EQUATION IS:
!
!       (X)**2/A**2  + (Y)**2/B**2 = 1
!
!       SUB X AND Y IN THE LEFT SIDE. IF THE LEFT SIDE IS
!       LESS THAN 1.0D0, THE RAY IS BLOCKED
!       ELSE IT IS NOT BLOCKED.
!
         XRD=X
         YRD=Y

!       IF NON-ZERO COBS DECENTRATIONS EXISTS, THEY MUST BE CONSIDERED
!       IN COBS CHECKING. WE CONVERT THE RAY COORDINATES X AND Y
!       TO XRD AND YRD IN THE COORDINATE SYSTEM OF THE DECENTERED
!       OBSCURATION. REMEMBER.
!
         XRD=XRD-NSSALENS(28,I)
         YRD=YRD-NSSALENS(29,I)
!
!       IF A NON-ZERO COBS TILT EXISTS, IT MUST BE CONSIDERED
!       IN COBS CHECKING. WE CONVERT THE RAY COORDINATES XRD AND YRD
!       TO XR AND YR IN THE COORDINATE SYSTEM OF THE ROTATED
!       OBSCURATION. REMEMBER. GAMMA ROTATION OF A CLAP OR
!       COBS HAS THE SAME SIGN AS IN A SURFACE ROTATION

         A22=NSSALENS(30,I)*PII/180.0D0
         XR=(XRD*DCOS(A22))+(YRD*DSIN(A22))
         YR=(YRD*DCOS(A22))-(XRD*DSIN(A22))
!
!
         LS=((XR**2)/(NSSALENS(26,I)**2))+&
         &((YR**2)/(NSSALENS(27,I)**2))
!
         IF(REAL(LS).LT.(1.0-(AIMTOL**2))) THEN
!       RAY IS BLOCKED BY COBS ON SURFACE I
            LS=10.0D0
            INITIT(ITIIT)=.TRUE.
         ELSE
            LS=0.0D0
            INITIT(ITIIT)=.FALSE.
         END IF
!       COFLG NOT 3
      END IF
   END DO
   NSSINSIDEIT=.FALSE.
   IF(INITIT(1).AND.INITIT(2))NSSINSIDEIT=.TRUE.
!
   RETURN
END
SUBROUTINE PLTNSSSFS
   USE NSSMOD
   use DATMAI
   INTEGER I,ISFI
   real(real64) SFI
   IF(.NOT.NEXISTN) THEN
      WRITE(OUTLYNE,*) 'NO NSS DATABASE EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'NO NSS SURFACES CAN BE DRAWN'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   CALL NSS_VERTEX_SILENT
!       NOW VERTEX DATA EXISTS IN GLOBAL COORDINATES
   DO I=1,MAXS
!       PLOT THE CLAP FOR ACTIVE SURFACES ONLY
      IF(NSSALENS(19,I).NE.0.0D0) THEN
         SFI=1.0D0
         IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.&
         &NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)&
         &CALL NSSCLP(I,SFI)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE HOLES FOR ACTIVE SURFACES ONLY
      IF(NSSALENS(25,I).NE.0.0D0) THEN
         IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.&
         &NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)&
         &CALL NSSHOL(I)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE PROFX FOR ACTIVE SURFACES ONLY
      IF(NSSALENS(19,I).NE.0.0D0) THEN
         IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.&
         &NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)&
         &CALL NSSPRO(I,0.0D0)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE PROFY FOR ACTIVE SURFACES ONLY
      IF(NSSALENS(19,I).NE.0.0D0) THEN
         IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.&
         &NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)&
         &CALL NSSPRO(I,90.0D0)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE INDIVIDUAL CLAPS OF ALL MEM PIXELS FOR A MEM SURFACE
      IF(NSSALENS(1,I).EQ.5.0D0) THEN
         CALL NSSMEMPLT(I)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE TUBE CLAPS
      IF(NSSALENS(1,I).EQ.6.0D0) THEN
         CALL NSSCLPTUB(I)
      END IF
   END DO
   DO I=1,MAXS
!       PLOT THE TUBE PROFILES
      IF(NSSALENS(1,I).EQ.6.0D0) THEN
         CALL NSSPROTUB(I,0.0D0)
         CALL NSSPROTUB(I,45.0D0)
         CALL NSSPROTUB(I,90.0D0)
         CALL NSSPROTUB(I,135.0D0)
         CALL NSSPROTUB(I,180.0D0)
         CALL NSSPROTUB(I,225.0D0)
         CALL NSSPROTUB(I,270.0D0)
         CALL NSSPROTUB(I,315.0D0)
      END IF
   END DO
   RETURN
END
SUBROUTINE PLTNSSSF
   USE NSSMOD
   use DATMAI
   INTEGER I,ISFI
   real(real64) SFI
   IF(.NOT.NEXISTN) THEN
      WRITE(OUTLYNE,*) 'NO NSS DATABASE EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'NO NSS SURFACE CAN BE DRAWN'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   I=INT(W1)
   IF(S1.EQ.0) THEN
      WRITE(OUTLYNE,*)&
      &'"PLOT NSSSURF" REQUIRES EXPLICIT NUMERIC WORD #1 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(S2.EQ.1.OR.S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)&
      &'"PLOT NSSSURF" ONLY TAKES NUMERIC WORD #1 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(I.LT.1.OR.I.GT.MAXS) THEN
      WRITE(OUTLYNE,*)&
      &'SURFACE NUMBER BEYOND LEGAL BOUNDS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SST.EQ.1) THEN
      WRITE(OUTLYNE,*)&
      &'"PLOT NSSSURF" TAKES NO STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   CALL NSS_VERTEX_SILENT
!       NOW VERTEX DATA EXISTS IN GLOBAL COORDINATES
!       PLOT THE CLAP FOR ACTIVE SURFACES ONLY
   IF(NSSALENS(19,I).NE.0.0D0) THEN
      SFI=1.0D0
      IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.&
      &NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)&
      &CALL NSSCLP(I,SFI)
   END IF
!       PLOT THE HOLES FOR ACTIVE SURFACES ONLY
   IF(NSSALENS(25,I).NE.0.0D0) THEN
      IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.&
      &NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)&
      &CALL NSSHOL(I)
   END IF
!       PLOT THE PROFX FOR ACTIVE SURFACES ONLY
   IF(NSSALENS(19,I).NE.0.0D0) THEN
      IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.&
      &NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)&
      &CALL NSSPRO(I,0.0D0)
   END IF
!       PLOT THE PROFY FOR ACTIVE SURFACES ONLY
   IF(NSSALENS(19,I).NE.0.0D0) THEN
      IF(NSSALENS(1,I).EQ.1.0D0.OR.NSSALENS(1,I).EQ.2.0D0.OR.&
      &NSSALENS(1,I).EQ.3.0D0.OR.NSSALENS(1,I).EQ.4.0D0)&
      &CALL NSSPRO(I,90.0D0)
   END IF
!       PLOT THE INDIVIDUAL CLAPS OF ALL MEM PIXELS FOR A MEM SURFACE
   IF(NSSALENS(1,I).EQ.5.0D0) CALL NSSMEMPLT(I)
!       PLOT THE TUBE CLAPS
   IF(NSSALENS(1,I).EQ.6.0D0) THEN
      CALL NSSCLPTUB(I)
   END IF
!       PLOT THE TUBE PROFILES
   IF(NSSALENS(1,I).EQ.6.0D0) THEN
      CALL NSSPROTUB(I,0.0D0)
      CALL NSSPROTUB(I,45.0D0)
      CALL NSSPROTUB(I,90.0D0)
      CALL NSSPROTUB(I,135.0D0)
      CALL NSSPROTUB(I,180.0D0)
      CALL NSSPROTUB(I,225.0D0)
      CALL NSSPROTUB(I,270.0D0)
      CALL NSSPROTUB(I,315.0D0)
   END IF
   RETURN
END
SUBROUTINE PLTNSSRY
   USE NSSMOD
!
   use DATLEN
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS ROUTINE DOES THE PLOT RAY COMMAND AT THE CMD LEVEL
!
   real(real64) X,Y,Z,XN,YN,ZN,ROT1X,ROT1Z,ROT2Y,&
   &ROT2Z,AX,AY,AZ,AALF,APHI,YMAXI,YMINI,XMAXI,XMINI &
   &,XNEW,YNEW,LKG,VIEPH,VIEAL,NSSFACTOR,L,M,N
!
   INTEGER CN
!
   LOGICAL GGO,LONG
!
   INTEGER IX,IY,I,II,IPST,COLPAS,FLAG,JK
   INTEGER NSSP1ARRAY,ALLOERR,ICOUNT,IINEXT
   DIMENSION NSSP1ARRAY(:,:)
   ALLOCATABLE :: NSSP1ARRAY
!
!
!     LOOK.VIEW TRANSFORMS

   ROT1X(AX,AZ,APHI)=((AX*DCOS(APHI))-(AZ*DSIN(APHI)))
   ROT1Z(AX,AZ,APHI)=((AX*DSIN(APHI))+(AZ*DCOS(APHI)))
!
   ROT2Z(AZ,AY,AALF)=((AZ*DCOS(AALF))+(AY*DSIN(AALF)))
   ROT2Y(AZ,AY,AALF)=((-AZ*DSIN(AALF))+(AY*DCOS(AALF)))
   IF(.NOT.NEXISTN) THEN
      WRITE(OUTLYNE,*) 'NO NSS DATABASE EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'NO NSS RAY CAN BE DRAWN'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   CALL NSS_VERTEX_SILENT
!
   DEALLOCATE(NSSP1ARRAY,STAT=ALLOERR)
   X=0.0D0
   Y=0.0D0
   VIEPH=(PII/180.0D0)*VIEPHI
   VIEAL=(PII/180.0D0)*VIEALF
!       NOW WE HAVE THE REAL WORLD COORDINATES OF THE RAY TO BE PLOTTED
!       THEY ARE STORED IN THE FILE NSSRHIST.DAT
!
!     HERE IS WHERE REAL WORK BEGINS. FIRST PROJECT THE 3D WORLD COORDINATES
!     OF THE VERTICIES ONTO THE 2D PLANE INDICATED BY THE PLOT LOOK/ PLOT VIEW
!     DATA. THE DIRECTION COSINES OF THE LOOK VECTOR ARE LOOKX, LOOKY AND
!     LOOKZ. THE TRANSFORMATIONS ARE:
!
   CALL NSSROT
!
!     AFTER THIS TRANSFORMATION, THE WORLD X COORDINATE IS PLOTTED IN THE
!     HORIZONTAL X-AXIS OF THE DISPLAY AND THE Y WORLD COORDINATE IS PLOTTED
!     IN THE VERTICAL Y-AXIS OF THE DISPLAY AFTER A CONVERSION TO
!     DEVICE INDEPENDENT COORDINATES ARE MADE.
!
   CALL NSSPLTSC
!
   ICOUNT=0
   OPEN(UNIT=92,FILE='NSSHT.DAT',STATUS='UNKNOWN')
   REWIND(UNIT=92)
5  CONTINUE
   CN=NSSWAVNUM
   READ(UNIT=92,FMT=*,END=6) I,X,Y,Z,L,M,N,CN
   ICOUNT=ICOUNT+1
   GO TO 5
6  CONTINUE
   CALL CLOSE_FILE(92,1)
   IF(ICOUNT.EQ.0) THEN
      WRITE(OUTLYNE,*) 'NO RAYS EXIST TO BE PLOTTED'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   ALLOCATE(NSSP1ARRAY(1:ICOUNT,1:3),STAT=ALLOERR)
   OPEN(UNIT=92,FILE='NSSHT.DAT',STATUS='UNKNOWN')
!     HERE IS THE LOOP WHICH PLOTS THE RAYS USING CALLS TO
!     PENMV2(IX,IY,IPST)
   REWIND(UNIT=92)
   DO II=1,ICOUNT
      READ(UNIT=92,FMT=*) I,X,Y,Z,L,M,N,CN
      IF(I.EQ.0) THEN
         IF(DABS(X).GT.1.0D10.OR.DABS(Y).GT.1.0D10.OR.&
         &DABS(Z).GT.1.0D10) THEN
            IINEXT=2
         ELSE
            IINEXT=1
         END IF
      END IF
      X=X-XROT
      Y=Y-YROT
      Z=Z-ZROT
      XN=ROT1X(X,Z,VIEPH)
      YN=Y
      ZN=ROT1Z(X,Z,VIEPH)
      X=XN
      Y=YN
      Z=ZN
!
      ZN=ROT2Z(Z,Y,VIEAL)
      YN=ROT2Y(Z,Y,VIEAL)
      XN=X
      X=XN
      Y=YN
      Z=ZN
!
!     RIGHT NOW,COORDINATES ARE IN WORLD COORDINATES
!     CONVERT THEM TO DEVICE INDEPENDENT GRAPHICS COORDINATES IN
!     TWO STEPS.
!
!     THE WORLD X PLOTS TO THE PLOTTER X
!     THE WORLD Y PLOTS TO THE PLOTTER Y
!
!     STEP 1: CONVERT USING AN APPROPRIATE SCALE FACTOR
!               CALCULATING AN APPROPRIATE FACTOR IF NECESSARY
!
      Y=(Y/NSSSCFA)*1000.0D0
!
      X=(X/NSSSCFA)*1000.0D0
!
!     STEP 2: APPLY THE SCREEN Y-OFFSET AND SCREEN GAMMA ROTATION
!
!     APPLY THE PLOT LOOK/VIEW Y-OFFSET VALUE
!
      IF(LORIENT) CALL ORSHIFT
      Y=Y+3500.0D0+DBLE(PYSHFT)
      X=X+DBLE(PXSHFT)
!
!     IF THERE ARE X-OFFSETS (JUSTIFICATION) TO APPLY, DO THEM HERE.
!
      IF(RCL.EQ.1.OR.RCL.EQ.-1) THEN
         JUSOFF=500.0D0-((XMINI/NSSSCFA)*1000.0D0)
         RCL=-1
      ELSE
      END IF
      IF(RCL.EQ.2.OR.RCL.EQ.-2) THEN
         RCL=-2
         JUSOFF=5000.0D0
      ELSE
      END IF
      IF(RCL.EQ.3.OR.RCL.EQ.-3) THEN
         JUSOFF=9500.0D0-((XMAXI/NSSSCFA)*1000.0D0)
         RCL=-3
      ELSE
      END IF
!
      X=X+JUSOFF
!
!     IF THERE IS A NON-ZERO GAMMA SPECIFIED IN PLOT LOOK OR PLOT VIEW THEN
!     ROTATE IN GAMMA ON THE SCREEN ABOUT THE CENTER OF THE SCREEN
!     WHICH HAS COORDINATES X=5000.0D0,Y=3500.0D0
!
!     FIRST SHIFT THE COORDINATE ORIGIN TO THE CETER OF THE DISPLAY
!
      X=X-5000.0D0
      Y=Y-3500.0D0
!     THE SCREEN COORDINATE IN real(real64) IN THE SHIFTED COORDINATE
!     FRAME IS NOW X AND Y

      IF(DBLE(PGAMMA).NE.0.0D0) THEN
         LKG=(PII/180.0D0)*DBLE(PGAMMA)
         XNEW=((X*DCOS(LKG))-(Y*DSIN(LKG)))
         YNEW=((X*DSIN(LKG))+(Y*DCOS(LKG)))
         X=XNEW
         Y=YNEW
      ELSE
      END IF

!     THE ROTATION IS DONE, NOW SHIFT THE ORIGIN BACK TO THE BOTTOM
!     LEFT HAND CORNER
      X=X+5000.0D0
      Y=Y+3500.0D0
!
!     PUT INSTRUCTIONS IN NSSP1ARRAY TO DROP PEN AND DRAW
      IPST=1
      LONG=.FALSE.
      IF(DABS(X).GT.2.0D9.OR.DABS(Y).GT.2.0D9) LONG=.TRUE.
      IF(X.LT.-2.0D9) X=-2.0D9
      IF(Y.LT.-2.0D9) Y=-2.0D9
      IF(X.GT.2.0D9) X=2.0D9
      IF(Y.GT.2.0D9) Y=2.0D9
      IX=INT(X)
      IY=INT(Y)
!     MOVE TO NEW POSITION WITH LOWERED PEN
      NSSP1ARRAY(II,1)=IX
      NSSP1ARRAY(II,2)=IY
      IF(I.EQ.0.OR.I.EQ.1.AND.IINEXT.EQ.2) THEN
         IF(IINEXT.EQ.2.AND.I.EQ.1) IINEXT=1
         NSSP1ARRAY(II,3)=0
      ELSE
         NSSP1ARRAY(II,3)=1
      END IF
      IF(.NOT.PLEXIS) PLEXIS=.TRUE.
      CONTINUE
   END DO
   CALL CLOSE_FILE(92,1)
!
!     NOW ISSUE THE PLOTTING COMMANDS STORED IN THE P1ARRAY ARRAY
!
   COLPAS=COLRAY
   CALL MY_COLTYP(COLPAS)
   NSSP1ARRAY(1,3)=0
   FIXUP=.FALSE.
   DO I=1,ICOUNT
      CALL PENMV2(NSSP1ARRAY(I,1),NSSP1ARRAY(I,2),NSSP1ARRAY(I,3))
   END DO
   COLPAS=COLLBL
   CALL MY_COLTYP(COLPAS)
   DEALLOCATE(NSSP1ARRAY,STAT=ALLOERR)
   RETURN
END
SUBROUTINE PLTNSSSPOTS(V1,V2)
   USE NSSMOD
!
   use DATLEN
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS ROUTINE DOES THE PLOT NSSSPOTS COMMAND AT THE CMD LEVEL ON SURFACE V1
!
   real(real64) X,Y,Z,XN,YN,ZN,ROT1X,ROT1Z,ROT2Y,&
   &ROT2Z,AX,AY,AZ,AALF,APHI,YMAXI,YMINI,XMAXI,XMINI &
   &,XNEW,YNEW,LKG,VIEPH,VIEAL,NSSFACTOR,V1,L,M,N,V2
!
   LOGICAL GGO
!
   INTEGER IX,IY,I,II,IPST,COLPAS,FLAG,JK
   INTEGER ICOUNT,BAR,CN
!
!
!     LOOK.VIEW TRANSFORMS

   ROT1X(AX,AZ,APHI)=((AX*DCOS(APHI))-(AZ*DSIN(APHI)))
   ROT1Z(AX,AZ,APHI)=((AX*DSIN(APHI))+(AZ*DCOS(APHI)))
!
   ROT2Z(AZ,AY,AALF)=((AZ*DCOS(AALF))+(AY*DSIN(AALF)))
   ROT2Y(AZ,AY,AALF)=((-AZ*DSIN(AALF))+(AY*DCOS(AALF)))
!
   BAR=INT(DABS(V2))
!
   CALL NSS_VERTEX_SILENT
!
   X=0.0D0
   Y=0.0D0
   VIEPH=(PII/180.0D0)*VIEPHI
   VIEAL=(PII/180.0D0)*VIEALF
!       NOW WE HAVE THE REAL WORLD COORDINATES OF THE RAY TO BE PLOTTED
!       THEY ARE STORED IN THE FILE NSSRHIST.DAT
!
!     HERE IS WHERE REAL WORK BEGINS. FIRST PROJECT THE 3D WORLD COORDINATES
!     OF THE VERTICIES ONTO THE 2D PLANE INDICATED BY THE PLOT LOOK/ PLOT VIEW
!     DATA. THE DIRECTION COSINES OF THE LOOK VECTOR ARE LOOKX, LOOKY AND
!     LOOKZ. THE TRANSFORMATIONS ARE:
!
   CALL NSSROT
!
!     AFTER THIS TRANSFORMATION, THE WORLD X COORDINATE IS PLOTTED IN THE
!     HORIZONTAL X-AXIS OF THE DISPLAY AND THE Y WORLD COORDINATE IS PLOTTED
!     IN THE VERTICAL Y-AXIS OF THE DISPLAY AFTER A CONVERSION TO
!     DEVICE INDEPENDENT COORDINATES ARE MADE.
!
   CALL NSSPLTSC
!
   ICOUNT=0
   OPEN(UNIT=92,FILE='NSSHT.DAT',STATUS='UNKNOWN')
   REWIND(UNIT=92)
5  CONTINUE
   READ(UNIT=92,FMT=*,END=6) I,X,Y,Z,L,M,N,CN
   ICOUNT=ICOUNT+1
   GO TO 5
6  CONTINUE
   CALL CLOSE_FILE(92,1)
   OPEN(UNIT=92,FILE='NSSHT.DAT',STATUS='UNKNOWN')
1  FORMAT(I5,D23.15,D23.15,D23.15,D23.15,D23.15,D23.15)
!     HERE IS THE LOOP WHICH PLOTS THE RAYS USING CALLS TO
!     PENMV2(IX,IY,IPST)
   REWIND(UNIT=92)
   DO II=1,ICOUNT
!     THE RAY IS A RAY AT THE SURFACE OF INTEREST
      READ(UNIT=92,FMT=*) I,X,Y,Z,L,M,N,CN
      IF(I.EQ.INT(V1)) THEN
         X=X-XROT
         Y=Y-YROT
         Z=Z-ZROT
         XN=ROT1X(X,Z,VIEPH)
         YN=Y
         ZN=ROT1Z(X,Z,VIEPH)
         X=XN
         Y=YN
         Z=ZN
!
         ZN=ROT2Z(Z,Y,VIEAL)
         YN=ROT2Y(Z,Y,VIEAL)
         XN=X
         X=XN
         Y=YN
         Z=ZN
!
!     RIGHT NOW,COORDINATES ARE IN WORLD COORDINATES
!     CONVERT THEM TO DEVICE INDEPENDENT GRAPHICS COORDINATES IN
!     TWO STEPS.
!
!     THE WORLD X PLOTS TO THE PLOTTER X
!     THE WORLD Y PLOTS TO THE PLOTTER Y
!
!     STEP 1: CONVERT USING AN APPROPRIATE SCALE FACTOR
!               CALCULATING AN APPROPRIATE FACTOR IF NECESSARY
!
         Y=(Y/NSSSCFA)*1000.0D0
!
         X=(X/NSSSCFA)*1000.0D0
!
!     STEP 2: APPLY THE SCREEN Y-OFFSET AND SCREEN GAMMA ROTATION
!
!     APPLY THE PLOT LOOK/VIEW Y-OFFSET VALUE
!
         IF(LORIENT) CALL ORSHIFT
         Y=Y+3500.0D0+DBLE(PYSHFT)
         X=X+DBLE(PXSHFT)
!
!     IF THERE ARE X-OFFSETS (JUSTIFICATION) TO APPLY, DO THEM HERE.
!
         IF(RCL.EQ.1.OR.RCL.EQ.-1) THEN
            JUSOFF=500.0D0-((XMINI/NSSSCFA)*1000.0D0)
            RCL=-1
         ELSE
         END IF
         IF(RCL.EQ.2.OR.RCL.EQ.-2) THEN
            RCL=-2
            JUSOFF=5000.0D0
         ELSE
         END IF
         IF(RCL.EQ.3.OR.RCL.EQ.-3) THEN
            JUSOFF=9500.0D0-((XMAXI/NSSSCFA)*1000.0D0)
            RCL=-3
         ELSE
         END IF
!
         X=X+JUSOFF
!
!     IF THERE IS A NON-ZERO GAMMA SPECIFIED IN PLOT LOOK OR PLOT VIEW THEN
!     ROTATE IN GAMMA ON THE SCREEN ABOUT THE CENTER OF THE SCREEN
!     WHICH HAS COORDINATES X=5000.0D0,Y=3500.0D0
!
!     FIRST SHIFT THE COORDINATE ORIGIN TO THE CETER OF THE DISPLAY
!
         X=X-5000.0D0
         Y=Y-3500.0D0
!     THE SCREEN COORDINATE IN real(real64) IN THE SHIFTED COORDINATE
!     FRAME IS NOW X AND Y

         IF(DBLE(PGAMMA).NE.0.0D0) THEN
            LKG=(PII/180.0D0)*DBLE(PGAMMA)
            XNEW=((X*DCOS(LKG))-(Y*DSIN(LKG)))
            YNEW=((X*DSIN(LKG))+(Y*DCOS(LKG)))
            X=XNEW
            Y=YNEW
         ELSE
         END IF

!     THE ROTATION IS DONE, NOW SHIFT THE ORIGIN BACK TO THE BOTTOM
!     LEFT HAND CORNER
         X=X+5000.0D0
         Y=Y+3500.0D0
!
!       PLOT THE SPOT
!       X AND Y ARE THE LOCATIONS OF THE RAY IN DEVICE DEPENDENT COORDINATES
         IPST=0
         IX=INT(X)
         IY=INT(Y)
!     MOVE TO NEW POSITION WITH RAISED PEN
!       PLOT SPOT HERE
!     NOW ISSUE THE PLOTTING COMMANDS STORED IN THE P1ARRAY ARRAY
!
         IF(CN.EQ.1)  COLPAS=(COLR1)
         IF(CN.EQ.2)  COLPAS=(COLR2)
         IF(CN.EQ.3)  COLPAS=(COLR3)
         IF(CN.EQ.4)  COLPAS=(COLR4)
         IF(CN.EQ.5)  COLPAS=(COLR5)
         IF(CN.EQ.6)  COLPAS=(COLR6)
         IF(CN.EQ.7)  COLPAS=(COLR7)
         IF(CN.EQ.8)  COLPAS=(COLR8)
         IF(CN.EQ.9)  COLPAS=(COLR9)
         IF(CN.EQ.10) COLPAS=(COLR10)
         CALL MY_COLTYP(COLPAS)
         CALL PENMV2(IX,IY,0)
         CALL PENMV2(IX+BAR,IY,1)
         CALL PENMV2(IX-BAR,IY,1)
         CALL PENMV2(IX,IY,0)
         CALL PENMV2(IX,IY+BAR,1)
         CALL PENMV2(IX,IY-BAR,1)
         CALL PENMV2(IX,IY,0)
         COLPAS=COLLBL
         CALL MY_COLTYP(COLPAS)
         IF(.NOT.PLEXIS) PLEXIS=.TRUE.
      ELSE
!       RAY WAS NOT AT THE SURFACE OF INTEREST
      END IF
   END DO
   CALL CLOSE_FILE(92,1)
!
   RETURN
END
SUBROUTINE NSSCLPTUB(JJ)
   USE NSSMOD
   USE GLOBALS
!
   use DATLEN
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
   real(real64) X,Y,Z,XN,YN,ZN,ROT1X,ROT1Z,ROT2Y,MDX,MDY,GAMGAM &
   &,ROT2Z,AX,AY,AZ,AALF,APHI,YMAXI,YMINI,XMAXI,XMINI &
   &,XNEW,YNEW,LKG,VIEPH,VIEAL,Z1,ANGLE,AN2,ZDELZ &
   &,X00,Y00,Z0,LX0,LY0,LZ0,ZCORR,SFI &
   &,X1,Y1,MX0,MY0,MZ0,NX0,NY0,NZ0,XID,YID
!
   INTEGER JJSTOP,J,IK,III,NO,JJ,ALLOERR,IIRUN,CLPTYPE
!
   INTEGER M1,M2,M3,M4,M5,IX,IY,I,II,IPST,K,L,POINT(1:2,1:3),N
!
   INTEGER SURFACEI
!
   INTEGER COLPAS
!
!
   REAL CLPDAT
   DIMENSION CLPDAT(:,:)
   ALLOCATABLE :: CLPDAT
!
!     LOOK.VIEW TRANSFORMS

   ROT1X(AX,AZ,APHI)=((AX*DCOS(APHI))-(AZ*DSIN(APHI)))
   ROT1Z(AX,AZ,APHI)=((AX*DSIN(APHI))+(AZ*DCOS(APHI)))
!
   ROT2Z(AZ,AY,AALF)=((AZ*DCOS(AALF))+(AY*DSIN(AALF)))
   ROT2Y(AZ,AY,AALF)=((-AZ*DSIN(AALF))+(AY*DCOS(AALF)))
!
!
   DEALLOCATE(CLPDAT,STAT=ALLOERR)
   ALLOCATE(CLPDAT(0:360,3),STAT=ALLOERR)
!
   VIEPH=(PII/180.0D0)*VIEPHI
   VIEAL=(PII/180.0D0)*VIEALF
!
   CLPDAT(0:360,1:3)=0.0
!
   X=0.0D0
   Y=0.0D0
   XID=0.0D0
   YID=0.0D0
!
!       ALL INPUT IS OK, KEEP GOING
!     THE ARRAY CONTAINING SURFACE CLAP DATA IS:
!     CLPDAT(0:360,1:3)
!
!     THE FIRST DIMENSION IS FOR THE DATA POINT NUMBER
!     THE SECOND DIMENSION IS FOR THE X,Y AND Z COORDINATES OR THE POINT
!     THE THIRD IS THE SURFACE NUMBER
!
!     WE NEED TO LOAD THE ARRAY BEFORE PLOTTING
!
!     THE PROCEDURE IS:
!
!     CYCLE THROUGH ALL THE SURFACES
!
!     1. WE WILL CLOCK AROUND THE CLEAR APERTURE FROM THE LOCAL +X
!     TOWARD THE LOCAL +Y AXIS,
!     4.0 DEGREE INCREMENTS AS MEASURED
!     BY AN OBSERVER AT THE SURFACE VERTEX, IN THE LOCAL COORDINATE
!     SYSTEM OF THE SURFACE, WITH THE OBSERVER FACING THE -Z AXIS
!     DIRECTION
   DO N=1,2
!       N=1 IS START OF TUBE
!       N=2 IS END OF TUBE
      DO J=0,360
         ANGLE=(DBLE(J)*PII)/180.0D0
         AN2=(DBLE(J+1)*PII)/180.0D0
!     NOW ALONG THIS ANGLED LINE, WHAT ARE THE X AND Y COORDINATES
!     OF THE CLEAR APERTURE
!
         CALL NSSCAO3(JJ,X,Y,ANGLE,AN2)
!
!     THE RETURNED X AND Y ARE WHERE THE SAG IS TO BE CALCULATED
!
!     2. ASSIGN SAG BASED ON N
         IF(N.EQ.1) Z=0.0D0
         IF(N.EQ.2) Z=DABS(NSSALENS(11,JJ))
!
!
!     ASSIGN ARRAY VALUES BASED ON J VALUE
         CLPDAT(J,1)=X
         CLPDAT(J,2)=Y
         CLPDAT(J,3)=Z
      END DO
!
!     3. THE ARRAYS NOW HAVE LOCAL X,Y AND Z VALUES STORED IN THEM
!     CONVERT THE LOCAL X ANY Y CLAPS TO GLOBAL NUMBERS
!     GLOBAL VERTEX DATA IS
      DO I=0,360
         X00=NSSVERTEX(1,JJ)
         Y00=NSSVERTEX(2,JJ)
         Z0 =NSSVERTEX(3,JJ)
         LX0=NSSVERTEX(4,JJ)
         MX0=NSSVERTEX(5,JJ)
         NX0=NSSVERTEX(6,JJ)
         LY0=NSSVERTEX(7,JJ)
         MY0=NSSVERTEX(8,JJ)
         NY0=NSSVERTEX(9,JJ)
         LZ0=NSSVERTEX(10,JJ)
         MZ0=NSSVERTEX(11,JJ)
         NZ0=NSSVERTEX(12,JJ)
         X=CLPDAT(I,1)
         Y=CLPDAT(I,2)
         Z=CLPDAT(I,3)
!
         X1=X00+((LX0*(X))+(LY0*(Y))&
         &+(LZ0*(Z)))
         Y1=Y00+((MX0*(X))+(MY0*(Y))&
         &+(MZ0*(Z)))
         Z1=Z0+((NX0*(X))+(NY0*(Y))&
         &+(NZ0*(Z)))
         CLPDAT(I,1)=X1
         CLPDAT(I,2)=Y1
         CLPDAT(I,3)=Z1
      END DO
!
!     4. NOW DETERMINE THE BEST PLACE FOR THE ROTATION POINT FOR
!               PLOT LOOK/VIEW
!
      CALL NSSROT
!
!     5.  CONVERT THE GLOBAL X AND Y CLAP VALUES
!               USING THE LOOK/VIEW VALUES
      DO I=0,360
         X=CLPDAT(I,1)
         Y=CLPDAT(I,2)
         Z=CLPDAT(I,3)
         X=X-XROT
         Y=Y-YROT
         Z=Z-ZROT
         XN=ROT1X(X,Z,VIEPH)
         YN=Y
         ZN=ROT1Z(X,Z,VIEPH)
         X=XN
         Y=YN
         Z=ZN
!
         ZN=ROT2Z(Z,Y,VIEAL)
         YN=ROT2Y(Z,Y,VIEAL)
         XN=X
         CLPDAT(I,1)=XN
         CLPDAT(I,2)=YN
         CLPDAT(I,3)=ZN
      END DO
!
!     THE ARRAYS NOW HAVE GLOBAL SURFACE CLAP DATA IN THEM
!
!     6.IF NEEDED, DETERMINE SCALE FACTORS AND PLOT RANGE
!
      CALL NSSPLTSC
!
!     7.CYCLE THROUGH THE THE ARRAYS, APPLY SCALE FACTORS
!
!     RIGHT NOW,COORDINATES ARE IN WORLD COORDINATES
!     CONVERT THEM TO DEVICE INDEPENDENT GRAPHICS COORDINATES IN
!     TWO STEPS.
!
!     THE WORLD X PLOTS TO THE PLOTTER X
!     THE WORLD Y PLOTS TO THE PLOTTER Y
!
!     STEP 1: CONVERT USING AN APPROPRIATE SCALE FACTOR
!               CALCULATING AN APPROPRIATE FACTOR IF NECESSARY
!
      DO I=0,360
         CLPDAT(I,1)=(CLPDAT(I,1)/NSSSCFA)*1000.0D0
         CLPDAT(I,2)=(CLPDAT(I,2)/NSSSCFA)*1000.0D0
      END DO
!
!     8. APPLY THE XSHIFT AND YSHIFT VALUES
      DO I=0,360
         IF(LORIENT) CALL ORSHIFT
         CLPDAT(I,1)=CLPDAT(I,1)+DBLE(PXSHFT)
         CLPDAT(I,2)=CLPDAT(I,2)+3500.0D0+DBLE(PYSHFT)
      END DO
!
!     9. SET THE PLOT JUSTIFICATION IF NEEDED
!     IF THERE ARE X-OFFSETS (JUSTIFICATION) TO APPLY, DO THEM HERE.
!
!     NOW
      IF(RCL.EQ.1.OR.RCL.EQ.-1) THEN
         JUSOFF=500.0D0-((XMINI/NSSSCFA)*1000.0D0)
         RCL=-1
      ELSE
      END IF
      IF(RCL.EQ.2.OR.RCL.EQ.-2) THEN
         RCL=-2
         JUSOFF=5000.0D0
      ELSE
      END IF
      IF(RCL.EQ.3.OR.RCL.EQ.-3) THEN
         JUSOFF=9500.0D0-((XMAXI/NSSSCFA)*1000.0D0)
         RCL=-3
      ELSE
      END IF
!
      DO I=0,360
         CLPDAT(I,1)=CLPDAT(I,1)+JUSOFF
      END DO
!     9. PLOT GAMMA
!     IF THERE IS A NON-ZERO GAMMA SPECIFIED IN PLOT LOOK OR PLOT VIEW THEN
!     ROTATE IN GAMMA ON THE SCREEN ABOUT THE CENTER OF THE SCREEN
!     WHICH HAS COORDINATES X=5000.0D0,Y=3500.0D0
!
!     FIRST SHIFT THE COORDINATE ORIGIN TO THE CETER OF THE DISPLAY
!
      DO I=0,360
         CLPDAT(I,1)=CLPDAT(I,1)-5000.0D0
         CLPDAT(I,2)=CLPDAT(I,2)-3500.0D0
      END DO
!     THE SCREEN COORDINATE IN real(real64) IN THE SHIFTED COORDINATE
!     FRAME IS NOW X AND Y

      IF(DBLE(PGAMMA).NE.0.0D0) THEN
         LKG=(PII/180.0D0)*DBLE(PGAMMA)

         DO I=0,360
            X=CLPDAT(I,1)
            Y=CLPDAT(I,2)
            XNEW=((X*DCOS(LKG))-(Y*DSIN(LKG)))
            YNEW=((X*DSIN(LKG))+(Y*DCOS(LKG)))
            CLPDAT(I,1)=XNEW
            CLPDAT(I,2)=YNEW
         END DO
      ELSE
      END IF
!     THE ROTATION IS DONE, NOW SHIFT THE ORIGIN BACK TO THE BOTTOM
!     LEFT HAND CORNER
      DO I=0,360
         CLPDAT(I,1)=CLPDAT(I,1)+5000.0D0
         CLPDAT(I,2)=CLPDAT(I,2)+3500.0D0
      END DO
!
!     NOW DRAW THE CLAP
!     WITH THE PEN UP, GO TO THE STARTING PLOT POSITION
      IF(.NOT.PLEXIS) PLEXIS=.TRUE.
      DO J=0,360
!     PUT INSTRUCTIONS IN P1ARAY TO DROP PEN AND DRAW
         IF(J.EQ.0) IPST=0
         IF(J.NE.0) IPST=1
         IF(CLPDAT(J,1).GT.1.0D6) CLPDAT(J,1)=1.0D6
         IF(CLPDAT(J,2).GT.1.0D6) CLPDAT(J,2)=1.0D6
         IF(CLPDAT(J,1).LT.-1.0D6) CLPDAT(J,1)=-1.0D6
         IF(CLPDAT(J,2).LT.-1.0D6) CLPDAT(J,2)=-1.0D6
         IX=INT(CLPDAT(J,1))
         IY=INT(CLPDAT(J,2))
         P1ARAY(J,1,1)=IX
         P1ARAY(J,2,1)=IY
         P1ARAY(J,3,1)=IPST
         IF(.NOT.PLEXIS) PLEXIS=.TRUE.
      END DO
!     FINISHED WITH THAT CLAP, LIFT PEN
      IPST=0
!     NOW ISSUE THE PLOTTING COMMANDS STORED IN THE P1ARAY ARRAY
!
!     LINE TYPE SETTING
      COLPAS=COLCLP
      CALL MY_COLTYP(COLPAS)
      OLLNTP=LNTYPE
      LNTYPE=0
      FIXUP=.FALSE.
      DO IK=0,360
         CALL PENMV2(P1ARAY(IK,1,1),P1ARAY(IK,2,1),P1ARAY(IK,3,1))
      END DO
      LNTYPE=OLLNTP
!
   END DO
   DEALLOCATE(CLPDAT,STAT=ALLOERR)
   RETURN
END
SUBROUTINE NSSPROTUB(JJ,V3)
   USE NSSMOD
   USE GLOBALS
!
   use DATLEN
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS ROUTINE DOES THE PLOTTING OF SURFACE PROFILES FOR NSS TUBES
!
   real(real64) X,Y,Z,XN,YN,ZN,ROT1X,ROT1Z,ROT2Y,XX1,XX2,YY1,V1,V2,V3,&
   &ROT2Z,AX,AY,AZ,AALF,APHI,YMAXI,YMINI,XMAXI,XMINI,RANGE &
   &,XNEW,YNEW,LKG,VIEPH,VIEAL,Z1,YY2,AX1,AX2,AY1,AY2,ZDELZ &
   &,X00,Y00,Z0,LX0,LY0,LZ0,ACALL1,ACALL2,XM,YM,ZCORR,ZDELZ1 &
   &,X1,X2,Y1,Y2,SLOPE,DELXX,DELYY,MX0,MY0,MZ0,NX0,NY0,NZ0
!
   LOGICAL ALT,VERT,INSIT,YESONE1,YESONE2,YESONE3,YESONE4 &
   &,YESONE5,YESONE6,NSSINSIDEIT
!
   COMMON/YESSIR/YESONE1,YESONE2,YESONE3,YESONE4,YESONE5,YESONE6
!
   EXTERNAL NSSINSIDEIT
!
   INTEGER M1,M2,M3,M4,CAFLG,COFLG,J,K,IK,III,NO,ALLOERR &
   &,COLPAS,JJ
!
   real(real64) XMIN,YMIN,XMAX,YMAX,ZA,ZB,ZM,FRACRAD,&
   &XMINO,YMINO,XMAXO,YMAXO,THETA &
   &,TEMP,YMIN2,XMIN2,YMAX2,XMAX2,CALL1,CALL2
!
   INTEGER IX,IY,I,II,IPST
!
!
   real(real64) PRO
!
   DIMENSION PRO(:,:)
   ALLOCATABLE :: PRO
!     LOOK.VIEW TRANSFORMS

   ROT1X(AX,AZ,APHI)=((AX*DCOS(APHI))-(AZ*DSIN(APHI)))
   ROT1Z(AX,AZ,APHI)=((AX*DSIN(APHI))+(AZ*DCOS(APHI)))
!
   ROT2Z(AZ,AY,AALF)=((AZ*DCOS(AALF))+(AY*DSIN(AALF)))
   ROT2Y(AZ,AY,AALF)=((-AZ*DSIN(AALF))+(AY*DCOS(AALF)))
!
   M1=2
   M2=3
   DEALLOCATE (PRO,STAT=ALLOERR)
   ALLOCATE (PRO(M1,M2),STAT=ALLOERR)
   PRO(1:2,1:3)=0.0D0
!
   X=0.0D0
   Y=0.0D0
!
   VIEPH=(PII/180.0D0)*VIEPHI
   VIEAL=(PII/180.0D0)*VIEALF
!
!       USES GLOBAL NSSVERTEX ARRAY
!
!     CONVERT THETA TO RADIAN MEASURE
   IF(V3.GE.89.95D0.AND.V3.LE.90.05D0) V3=90.001D0
   IF(V3.GE.269.95D0.AND.V3.LE.270.05D0) V3=270.001D0
   THETA=V3*PII/180.0D0
!     THE ARRAY CONTAINING SURFACE PROFILE DATA ARE:
!
!     PRO(1:2,1:3)
!
!     THE FIRST DIMENSION IS FOR THE DATA POINT NUMBER
!     THE SECOND DIMENSION IS FOR THE X,Y AND Z COORDINATES OR THE POINT
!
!     WE NEED TO LOAD THE ARRAY BEFORE PLOTTING
!
!     THE PROCEDURE IS:
!     1. DETERMINE THE MAXIMUM AND MINIMUM LOCAL X AND Y
!               COORDINATES FOR A SURFACE FOR WHICH THE PROFILE
!               IS TO BE CALCULATED.
!
!     CYCLE THROUGH ALL THE SURFACES BUT SKIP SURFACES WITH MULTIPLE
!     APERTURE DEFS ON IT
!
   II=JJ
   III=II
!
!     NOW FOR THE II SURFACE WE CALCULATE ALL THE END POINTS
!
!     NOW WE HAVE THE END POINTS, CYCLE THROUGH ALL THE PAIRS AND LOAD
!     ALL THE ARRAYS WITH SURFACE LOCAL X,Y AND Z DATA
!
   X=DABS(NSSALENS(10,JJ))
   Y=DABS(NSSALENS(10,JJ))
   PRO(1,1)=X*DCOS(V3*PII/180.0D0)
   PRO(2,1)=X*DCOS(V3*PII/180.0D0)
   PRO(1,2)=Y*DSIN(V3*PII/180.0D0)
   PRO(2,2)=Y*DSIN(V3*PII/180.0D0)
   PRO(1,3)=0.0D0
   PRO(2,3)=DABS(NSSALENS(11,JJ))
!
!     THE ARRAYS NOW HAVE LOCAL X,Y AND Z VALUES STORED IN THEM
!     CONVERT THE LOCAL X ANY Y PROFILES TO GLOBAL NUMBERS
!     GLOBAL VERTEX DATA IS
   II=JJ
   DO I=1,2
      X00=NSSVERTEX(1,II)
      Y00=NSSVERTEX(2,II)
      Z0= NSSVERTEX(3,II)
      LX0=NSSVERTEX(4,II)
      MX0=NSSVERTEX(5,II)
      NX0=NSSVERTEX(6,II)
      LY0=NSSVERTEX(7,II)
      MY0=NSSVERTEX(8,II)
      NY0=NSSVERTEX(9,II)
      LZ0=NSSVERTEX(10,II)
      MZ0=NSSVERTEX(11,II)
      NZ0=NSSVERTEX(12,II)
      X=PRO(I,1)
      Y=PRO(I,2)
      Z=PRO(I,3)
!
      X1=X00+((LX0*(X))+(LY0*(Y))&
      &+(LZ0*(Z)))
      Y1=Y00+((MX0*(X))+(MY0*(Y))&
      &+(MZ0*(Z)))
      Z1=Z0+((NX0*(X))+(NY0*(Y))&
      &+(NZ0*(Z)))
      PRO(I,1)=X1
      PRO(I,2)=Y1
      PRO(I,3)=Z1
   END DO
!
!     4. NOW DETERMINE THE BEST PLACE FOR THE ROTATION POINT FOR
!               PLOT LOOK/VIEW
!
   CALL NSSROT
!
!     5.  CONVERT THE GLOBAL X ANY Y PROFILES
!               USING THE LOOK/VIEW VALUES
   II=JJ
   DO I=1,2
      X=PRO(I,1)
      Y=PRO(I,2)
      Z=PRO(I,3)
      X=X-XROT
      Y=Y-YROT
      Z=Z-ZROT
      XN=ROT1X(X,Z,VIEPH)
      YN=Y
      ZN=ROT1Z(X,Z,VIEPH)
      X=XN
      Y=YN
      Z=ZN
!
      ZN=ROT2Z(Z,Y,VIEAL)
      YN=ROT2Y(Z,Y,VIEAL)
      XN=X
      PRO(I,1)=XN
      PRO(I,2)=YN
      PRO(I,3)=ZN
   END DO
!
!     THE ARRAYS NOW HAVE GLOBAL SURFACE PROFILE DATA IN THEM
!
!     6.IF NEEDED, DETERMINE SCALE FACTORS AND PLOT RANGE
!
   CALL NSSPLTSC
!
!     7.CYCLE THROUGH THE THE ARRAYS, APPLY SCALE FACTORS
!
!     RIGHT NOW,COORDINATES ARE IN WORLD COORDINATES
!     CONVERT THEM TO DEVICE INDEPENDENT GRAPHICS COORDINATES IN
!     TWO STEPS.
!
!     THE WORLD X PLOTS TO THE PLOTTER X
!     THE WORLD Y PLOTS TO THE PLOTTER Y
!
!     STEP 1: CONVERT USING AN APPROPRIATE SCALE FACTOR
!               CALCULATING AN APPROPRIATE FACTOR IF NECESSARY
!
   II=JJ
   DO I=1,2
      PRO(I,1)=(PRO(I,1)/NSSSCFA)*1000.0D0
      PRO(I,2)=(PRO(I,2)/NSSSCFA)*1000.0D0
   END DO
!
!     8. APPLY THE PLOT XSHIFT AND YSHIFT VALUES
   DO I=1,2
      II=JJ
      IF(LORIENT) CALL ORSHIFT
      PRO(I,1)=PRO(I,1)+DBLE(PXSHFT)
      PRO(I,2)=PRO(I,2)+3500.0D0+DBLE(PYSHFT)
   END DO
!
!     9. SET THE PLOT JUSTIFICATION IF NEEDED
!     IF THERE ARE X-OFFSETS (JUSTIFICATION) TO APPLY, DO THEM HERE.
!
!     NOW
   IF(RCL.EQ.1.OR.RCL.EQ.-1) THEN
      JUSOFF=500.0D0-((XMINI/NSSSCFA)*1000.0D0)
      RCL=-1
   ELSE
   END IF
   IF(RCL.EQ.2.OR.RCL.EQ.-2) THEN
      RCL=-2
      JUSOFF=5000.0D0
   ELSE
   END IF
   IF(RCL.EQ.3.OR.RCL.EQ.-3) THEN
      JUSOFF=9500.0D0-((XMAXI/NSSSCFA)*1000.0D0)
      RCL=-3
   ELSE
   END IF
!
   DO I=1,2
      II=JJ
      PRO(I,1)=PRO(I,1)+JUSOFF
   END DO
!     9. PLOT GAMMA
!     IF THERE IS A NON-ZERO GAMMA SPECIFIED IN PLOT LOOK OR PLOT VIEW THEN
!     ROTATE IN GAMMA ON THE SCREEN ABOUT THE CENTER OF THE SCREEN
!     WHICH HAS COORDINATES X=5000.0D0,Y=3500.0D0
!
!     FIRST SHIFT THE COORDINATE ORIGIN TO THE CETER OF THE DISPLAY
!
   DO I=1,2
      II=JJ
      PRO(I,1)=PRO(I,1)-5000.0D0
      PRO(I,2)=PRO(I,2)-3500.0D0
   END DO
!     THE SCREEN COORDINATE IN real(real64) IN THE SHIFTED COORDINATE
!     FRAME IS NOW X AND Y

   IF(DBLE(PGAMMA).NE.0.0D0) THEN
      LKG=(PII/180.0D0)*DBLE(PGAMMA)

      DO I=1,2
         II=JJ
         X=PRO(I,1)
         Y=PRO(I,2)
         XNEW=((X*DCOS(LKG))-(Y*DSIN(LKG)))
         YNEW=((X*DSIN(LKG))+(Y*DCOS(LKG)))
         PRO(I,1)=XNEW
         PRO(I,2)=YNEW
      END DO
   END IF
!     THE ROTATION IS DONE, NOW SHIFT THE ORIGIN BACK TO THE BOTTOM
!     LEFT HAND CORNER
   DO I=1,2
      II=JJ
      PRO(I,1)=PRO(I,1)+5000.0D0
      PRO(I,2)=PRO(I,2)+3500.0D0
   END DO
!
   I=JJ
!     NOW DRAW THE X PROFILE OF THE CLAP AT SURFACE I
!     WITH THE PEN UP, GO TO THE STARTING PLOT POSITION
   IF(.NOT.PLEXIS) PLEXIS=.TRUE.
!     FIRST CLAP PROFILE
   DO J=1,2
!     PUT INSTRUCTIONS IN P1ARAY TO DROP PEN AND DRAW
      IF(J.EQ.1) IPST=0
      IF(J.EQ.2) IPST=1
      IF(PRO(J,1).GT.1.0D6) PRO(J,1)=1.0D6
      IF(PRO(J,2).GT.1.0D6) PRO(J,2)=1.0D6
      IF(PRO(J,1).LT.-1.0D6) PRO(J,1)=-1.0D6
      IF(PRO(J,2).LT.-1.0D6) PRO(J,2)=-1.0D6
      IX=INT(PRO(J,1))
      IY=INT(PRO(J,2))
      P1ARAY(J,1,1)=IX
      P1ARAY(J,2,1)=IY
      P1ARAY(J,3,1)=IPST
      IF(.NOT.PLEXIS) PLEXIS=.TRUE.
   END DO
!
!     LINE TYPE SETTING
   COLPAS=COLPRO
   CALL MY_COLTYP(COLPAS)
   OLLNTP=LNTYPE
   LNTYPE=0
   FIXUP=.FALSE.
   DO IK=1,2
      CALL PENMV2(P1ARAY(IK,1,1),P1ARAY(IK,2,1),P1ARAY(IK,3,1))
   END DO
!     FINISHED WITH THAT PROFILE, LIFT PEN
   IPST=0
   LNTYPE=OLLNTP
   DEALLOCATE (PRO,STAT=ALLOERR)
   RETURN
END
