MODULE NSSMOD
   use iso_fortran_env, only: real64
!
   PUBLIC
!
!     NON-SEQUENTIAL STUFF
!
   LOGICAL NEXISTN
!
   CHARACTER*7 NSSDIR
!
   INTEGER SFID,MAXS
!
   real(real64) NSSSYSTEM,NSSALENS,LVECTOR,VECTORL,VECTORM,VECTORN
   DIMENSION NSSSYSTEM(:),NSSALENS(:,:),LVECTOR(:)
   DIMENSION VECTORL(:),VECTORM(:),VECTORN(:)
   ALLOCATABLE :: NSSSYSTEM,NSSALENS,LVECTOR,VECTORL,VECTORM,VECTORN
!
   real(real64)    NSSVERTEX
   DIMENSION NSSVERTEX(:,:)
   ALLOCATABLE :: NSSVERTEX
!
   real(real64)    NSSBOUNDS
   DIMENSION NSSBOUNDS(:,:)
   ALLOCATABLE :: NSSBOUNDS
!
   CHARACTER*80 NSSSNAM,NSSONAM
   DIMENSION NSSSNAM(:)
   ALLOCATABLE :: NSSSNAM
!
   CHARACTER NSSOGLASS(1:2)*13,CURGLASS(1:2)*13
   CHARACTER FROM_MEDIA(1:2)*13
   CHARACTER TO_MEDIA(1:2)*13
   CHARACTER NSSGLASS1*13,NSSGLASS2*13
   DIMENSION NSSGLASS1(:,:),NSSGLASS2(:,:)
   ALLOCATABLE :: NSSGLASS1,NSSGLASS2
!
   real(real64) OBJINDEX(1:20),CURINDEX(1:20)

!     NSS RAY STUFF
!
   INTEGER SNUM
!
   INTEGER DETONUM,DETSNUM,LASTSUR
!
   real(real64) OLD_LTEST
!
   real(real64) NSSRAY_ENERGY,NSSRAY_RPOL(1:20),&
   &NSSRAY_IPOL(1:20)
!
   INTEGER NSSRAY_HITS
!
   LOGICAL NSSRAY_EXIST
!
!       SET TO 50 BUT ONLY USE 16 AS OF 4/2004
!       START IS THE ORIGINAL STARTING RAY DATA
   real(real64) START(1:50)
!
!     GRAY IS THE RAY DATA IN GLOBAL COORDINATES BEFORE SURFACE INTERACTION
   real(real64) NSS_GRAY(1:50)
!     LRAY IS THE RAY DATA IN LOCAL COORDINATES BEFORE SURFACE INTERACTION
   real(real64) NSS_LRAY(1:50)
!     GRAYP IS THE RAY DATA IN GLOBAL COORDINATES AFTER SURFACE INTERACTION
   real(real64) NSS_GRAYP(1:50)
!     LRAYP IS THE RAY DATA IN LOCAL COORDINATES AFTER SURFACE INTERACTION
   real(real64) NSS_LRAYP(1:50)
!
!     OGRAY IS THE PREVIOUS RAY DATA IN GLOBAL COORDINATES BEFORE SURFACE INTERACTION
   real(real64) NSS_OGRAY(1:50)
!     OLRAY IS THE PREVIOUS RAY DATA IN LOCAL COORDINATES BEFORE SURFACE INTERACTION
   real(real64) NSS_OLRAY(1:50)
!     OGRAYP IS THE PREVIOUS RAY DATA IN GLOBAL COORDINATES AFTER SURFACE INTERACTION
   real(real64) NSS_OGRAYP(1:50)
!     OLRAYP IS THE PREVIOUS RAY DATA IN LOCAL COORDINATES AFTER SURFACE INTERACTION
   real(real64) NSS_OLRAYP(1:50)
!
   CHARACTER*13, TO_MEDA,TO_MEDB,FROM_MEDA,FROM_MEDB
!
   LOGICAL NSS_INTERSECT
!
   real(real64) NSSWAVL,NSSWVWT,REALINDEX1,REALINDEX2,IMAGINDEX1
   real(real64) IMAGINDEX2
   INTEGER NSSWAVNUM
!
   real(real64) RRX0,RRY0,RRZ0,RRL0,RRM0,RRN0
   real(real64) XRRL0,XRRM0,XRRN0
   real(real64) YRRL0,YRRM0,YRRN0
!
   real(real64) RRX,RRY,RRZ,RRL,RRM,RRN,NSSLN,NSSMN,NSSNN
   real(real64) NLN,NMN,NNN
   real(real64) XRRL,XRRM,XRRN
   real(real64) YRRL,YRRM,YRRN
   LOGICAL NSSRAYFAIL
   INTEGER NSSRAYFAILCODE(1:2)
!       1 IS THE FAILED SURFACE
!       2 IS FAILURE CODE
!               1. INTERACTION FAILURE
!
!     GLOBAL RAY DATA BEFORE SURFACE SEARCH
   real(real64) GRRX,GRRY,GRRZ,GRRL,GRRM,GRRN
   real(real64) GXRRL,GXRRM,GXRRN
   real(real64) GYRRL,GYRRM,GYRRN
!     LOCAL RAY DATA BEFORE SURFACE SEARCH
   real(real64) LRRX,LRRY,LRRZ,LRRL,LRRM,LRRN
   real(real64) LXRRL,LXRRM,LXRRN
   real(real64) LYRRL,LYRRM,LYRRN
!
   real(real64) CURWAVELENGTH,CURINDEXR,CURINDEXI,PREVINDEXR,PREVINDEXI
!
!       RAY TRAVEL DIRECTION 1= FROM MEDIA1 TO 2, 2= MEDIA2 TO 1
   INTEGER TRAVEL
!
!       EVEN OR ODD GRIDS
   LOGICAL OBJODD,REFODD
!
!       SAG ERROR FLAG
   LOGICAL NSSSAGERR
!
!       NSS SCALE FACTOR
   real(real64) NSSSCFA,NSSPSIZP
   real(real64) NSSSCFAP,NSSPSIZ
   LOGICAL NSSPLSZ,NSSPLSC
!
!       MEM ARRAYS
   real(real64) MEMX,MEMY,MEMXERROR,MEMYERROR
   INTEGER MEMXSTATE,MEMYSTATE
   DIMENSION MEMX(:,:),MEMY(:,:),MEMXERROR(:,:),&
   &MEMYERROR(:,:)
   DIMENSION MEMXSTATE(:,:),MEMYSTATE(:,:)
   ALLOCATABLE :: MEMX,MEMY,MEMXSTATE,MEMYSTATE
   ALLOCATABLE :: MEMXERROR,MEMYERROR
!
!       NSS SPOT DIAGRAM TYPES
!       0=NO SPOT
!       1=SPOT
!       2_SPOTADD
   INTEGER NSSSPOTTYPE
   INTEGER NSSSPOTSURF,NSPOT,NSSSPOTHITS
   LOGICAL NSSSPOTEXIST
!
!       CURRENT REAL INDEX VALUES
   real(real64) NSS_N,NSS_NP
!
!       OPL AND RAYLENGTH
   real(real64) NSS_OPL,NSS_RAYLENGTH
!
!       RAY HISTORY NUMBER TAG
   INTEGER RHISTN
!
!       STATS
   real(real64) NSSMEANX
   real(real64) NSSMEANY
   real(real64) NSSMEANR
   real(real64) NSSRMSX
   real(real64) NSSRMSY
   real(real64) NSSRMSR
!
!       SUPPORT FOR LINE CONNECTING OBJ CENTER AND REF CENTER
   real(real64) OMAG,OBJL,OBJM,OBJN,OALPHA,OBETA,OGAMMA
!
!       SUPPORT 200 LEVEL SURFACE POSITION NESTING
   INTEGER NSSNEST(0:200),INEST
!
   real(real64) XMEMCOR(1:4),YMEMCOR(1:4)
!
END MODULE NSSMOD
