!       FIRST FILE OF GENERAL OPTICAL ENGINEERING UTILITIES

! SUB XXF.FOR
SUBROUTINE XXF
!
   use DATMAI
   IMPLICIT NONE
!
!     XXF IS A SUBROUTINE WHICH CALCULATES OBJECT OR IMAGE
!     DISTACE OR FOCAL LENGTH GIVEN ANY TWO OF THE THREE VALUES
!     USING THE NEWTONIAN EQUATION:
!
!     f**2=-X*X'
!
!       XXF, NW1 NW2 NW2
!       WHERE NW1 IS THE DISTANCE X
!       WHERE NW2 IS THE DISTANCE X'
!       WHERE NW3 IS THE FOCAL LENGTH
!
   REAL*8 VALUE
!
!
   IF(SST.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"XXF (P)" ONLY TAKES NUMERIC WORD #1, #2 AND #3 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(SQ.EQ.1.AND.WQ.NE.'P') THEN
      WRITE(OUTLYNE,*)'"P" IS THE ONLY OPTIONAL QUALIFIER WORD FOR "XXF"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(DF1.EQ.0.AND.W1.EQ.0.0D0.OR.DF2.EQ.0.AND.W2.EQ.0.0D0 .OR.DF3.EQ.0.AND.W3.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'"XXF (P)" DOES NOT ACCEPT 0.0 FOR ANY OF ITS INPUT VALUES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(W1.GT.0.0D0.AND.W2.GT.0.0D0.OR.W1.LT.0.0D0.AND.W2.LT.0.0D0)THEN
      WRITE(OUTLYNE,*)'"(X) AND (X`) MAY NOT BE BOTH POSITIVE OF BOTH NEGATIVE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(DF1.EQ.1.AND.DF2.EQ.0.AND.DF3.EQ.0.OR.DF1.EQ.0.AND.DF2.EQ.1.AND.DF3.EQ.0.OR.DF1.EQ.0.AND.DF2.EQ.0.AND.DF3.EQ.1) THEN
!     PROCEED

      IF(DF1.EQ.1) VALUE=-(W3**2)/(W2)
      IF(DF2.EQ.1) VALUE=-(W3**2)/(W1)
      IF(DF3.EQ.1) VALUE=DSQRT(-(W1*W2))
!       UPDATE LASTX
      REG(40)=REG(9)
      REG(9) = VALUE
!
      IF(WQ.EQ.'P') THEN
         IF(DF1.EQ.1) WRITE(OUTLYNE,100) VALUE
         IF(DF1.EQ.1) CALL SHOWIT(0)
         IF(DF1.EQ.1) WRITE(OUTLYNE,20) W2
         IF(DF1.EQ.1) CALL SHOWIT(0)
         IF(DF1.EQ.1) WRITE(OUTLYNE,30) W3
         IF(DF1.EQ.1) CALL SHOWIT(0)
         IF(DF2.EQ.1) WRITE(OUTLYNE,200) VALUE
         IF(DF2.EQ.1) CALL SHOWIT(0)
         IF(DF2.EQ.1) WRITE(OUTLYNE,10) W1
         IF(DF2.EQ.1) CALL SHOWIT(0)
         IF(DF2.EQ.1) WRITE(OUTLYNE,30) W3
         IF(DF2.EQ.1) CALL SHOWIT(0)
         IF(DF3.EQ.1) WRITE(OUTLYNE,300) VALUE
         IF(DF3.EQ.1) CALL SHOWIT(0)
         IF(DF3.EQ.1) WRITE(OUTLYNE,10) W1
         IF(DF3.EQ.1) CALL SHOWIT(0)
         IF(DF3.EQ.1) WRITE(OUTLYNE,20) W2
         IF(DF4.EQ.1) CALL SHOWIT(0)
10       FORMAT('  INPUT (X) DISTANCE WAS = ',G13.6)
20       FORMAT(' INPUT (X`) DISTANCE WAS = ',G13.6)
30       FORMAT('  INPUT FOCAL LENGTH WAS = ',G13.6)
100      FORMAT(' THE NEW (X) DISTANCE IS = ',G13.6)
200      FORMAT('THE NEW (X`) DISTANCE IS = ',G13.6)
300      FORMAT(' THE NEW FOCAL LENGTH IS = ',G13.6)
      END IF
      RETURN
   ELSE
      WRITE(OUTLYNE,*)'"XXF (P)" REQUIRES TWO EXPLICIT NUMERIC VALUES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
   END IF
   RETURN
END
! SUB XXFF.FOR
SUBROUTINE XXFF
!
   use DATMAI
   IMPLICIT NONE
!
!
!     XXFF IS A SUBROUTINE WHICH CALCULATES OBJECT OR IMAGE
!     DISTACE OR FOCAL LENGTH GIVEN ANY THREE OF THE FOUR VALUES
!     USING THE NEWTONIAN EQUATION:
!
!     ff'=-X*X'
!
!       XXF, NW1 NW2 NW2
!       WHERE NW1 IS THE DISTANCE X
!       WHERE NW2 IS THE DISTANCE X'
!       WHERE NW3 IS THE FOCAL LENGTH f
!       WHERE NW3 IS THE FOCAL LENGTH f'
!
   REAL*8 VALUE
!
!
   IF(SST.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"XXFF (P)" ONLY TAKES NUMERIC WORD #1, #2, #3 AND #4 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(SQ.EQ.1.AND.WQ.NE.'P') THEN
      WRITE(OUTLYNE,*)'"P" IS THE ONLY OPTIONAL QUALIFIER WORD FOR "XXFF"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(DF1.EQ.0.AND.W1.EQ.0.0D0.OR.DF2.EQ.0.AND.W2.EQ.0.0D0 .OR.DF3.EQ.0.AND.W3.EQ.0.0D0.OR.DF4.EQ.0.AND.W4.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'"XXFF (P)" DOES NOT ACCEPT 0.0 FOR ANY OF ITS INPUT VALUES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(DF1.EQ.1.AND.DF2.EQ.0.AND.DF3.EQ.0.AND.DF4.EQ.1.OR.DF1.EQ.0.AND.DF2.EQ.1.AND.DF3.EQ.0.AND.DF4.EQ.0.OR.DF1.EQ.0.AND.DF2.EQ.0.AND.DF3.EQ.1.AND.DF4.EQ.0.OR.DF1.EQ.0.AND.DF2.EQ.0.AND.DF3.EQ.0.AND.DF4.EQ.1) THEN
!     PROCEED

      IF(DF1.EQ.1) VALUE=-(W3*W4)/(W2)
      IF(DF2.EQ.1) VALUE=-(W3*W4)/(W1)
      IF(DF3.EQ.1) VALUE=(-(W1*W2))/W4
      IF(DF4.EQ.1) VALUE=(-(W1*W2))/W3
!       UPDATE LASTX
      REG(40)=REG(9)
      REG(9) =VALUE
!
      IF(WQ.EQ.'P') THEN
         IF(DF1.EQ.1) WRITE(OUTLYNE,100) VALUE
         IF(DF1.EQ.1) CALL SHOWIT(0)
         IF(DF1.EQ.1) WRITE(OUTLYNE,20) W2
         IF(DF1.EQ.1) CALL SHOWIT(0)
         IF(DF1.EQ.1) WRITE(OUTLYNE,30) W3
         IF(DF1.EQ.1) CALL SHOWIT(0)
         IF(DF1.EQ.1) WRITE(OUTLYNE,40) W4
         IF(DF1.EQ.1) CALL SHOWIT(0)
         IF(DF2.EQ.1) WRITE(OUTLYNE,200) VALUE
         IF(DF2.EQ.1) CALL SHOWIT(0)
         IF(DF2.EQ.1) WRITE(OUTLYNE,10) W1
         IF(DF2.EQ.1) CALL SHOWIT(0)
         IF(DF2.EQ.1) WRITE(OUTLYNE,30) W3
         IF(DF2.EQ.1) CALL SHOWIT(0)
         IF(DF2.EQ.1) WRITE(OUTLYNE,40) W4
         IF(DF2.EQ.1) CALL SHOWIT(0)
         IF(DF3.EQ.1) WRITE(OUTLYNE,300) VALUE
         IF(DF3.EQ.1) CALL SHOWIT(0)
         IF(DF3.EQ.1) WRITE(OUTLYNE,10) W1
         IF(DF3.EQ.1) CALL SHOWIT(0)
         IF(DF3.EQ.1) WRITE(OUTLYNE,20) W2
         IF(DF3.EQ.1) CALL SHOWIT(0)
         IF(DF3.EQ.1) WRITE(OUTLYNE,40) W4
         IF(DF3.EQ.1) CALL SHOWIT(0)
         IF(DF4.EQ.1) WRITE(OUTLYNE,400) VALUE
         IF(DF4.EQ.1) CALL SHOWIT(0)
         IF(DF4.EQ.1) WRITE(OUTLYNE,10) W1
         IF(DF4.EQ.1) CALL SHOWIT(0)
         IF(DF4.EQ.1) WRITE(OUTLYNE,20) W2
         IF(DF4.EQ.1) CALL SHOWIT(0)
         IF(DF4.EQ.1) WRITE(OUTLYNE,30) W3
         IF(DF4.EQ.1) CALL SHOWIT(0)
10       FORMAT('  INPUT (X) DISTANCE WAS = ',G13.6)
20       FORMAT(' INPUT (X`) DISTANCE WAS = ',G13.6)
30       FORMAT('           INPUT (F) WAS = ',G13.6)
40       FORMAT('           INPUT (F`) WAS = ',G13.6)
100      FORMAT(' THE NEW (X) DISTANCE IS = ',G13.6)
200      FORMAT('THE NEW (X`) DISTANCE IS = ',G13.6)
300      FORMAT('          THE NEW (F) IS = ',G13.6)
400      FORMAT('         THE NEW (F`) IS = ',G13.6)
      END IF
      RETURN
   ELSE
      WRITE(OUTLYNE,*)'"XXFF (P)" REQUIRES TWO EXPLICIT NUMERIC VALUES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
   END IF
   RETURN
END
! SUB OUTFLT.FOR
SUBROUTINE OUTFLT
!
   use DATLEN
   use mod_system
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE OUTFLT. THIS SUBROUTINE IMPLEMENTS THE
!       CURVATURE FOR M FRINGES OUT OF FLAT CALCULATION AND
!     OUTPUTS THE CURVATURE CORRESPONDING
!     TO AN OUT OF FLAT CONDITION MEASURES IN FRINGES AT AN ARBITRARY
!     WAVELENGTH
!       NW1=NUMBER FOR FRINGES OR FRACTION OF FRINGES (REQUIRED)
!       NW2=PART DIAMETER IN CURRENT LENS UNITS (REQUIRED)
!       NW3=WAVELENGTH IN MICRONS (DEFAULT = 0.5461)
!         NW4 AND NW5 NOT USED
!         WQ NOT USED
!         WS NOT USED
!
   CHARACTER UN*12
!
   REAL*8 CURVE,WAVE
!
!
   IF(sys_units().EQ.1.0) UN='/INCHES     '
   IF(sys_units().EQ.2.0) UN='/CENTIMETERS'
   IF(sys_units().EQ.3.0) UN='/MILLIMETERS'
   IF(sys_units().EQ.4.0) UN='/METERS'
!
!
   IF(SST.EQ.1) THEN
      WRITE(OUTLYNE,*)'"OUTFLT" TAKES NO ALPHANUMERIC STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"OUTFLT" TAKES NO NUMERIC WORD #4 OR #5 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.1.AND.WQ.NE.'ACC') THEN
      WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "OUTFLT"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       HANDLE DEFAULT VALUES FOR NW1, NW2 AND NW3
!
   IF(DF1.EQ.1.OR.DF2.EQ.1) THEN
      WRITE(OUTLYNE,*)'"OUTFLT" REQUIRES EXPLICIT NUMERIC WORD #1 AND #2 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(DF3.EQ.1) W3=0.5461D0
   IF(W1.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'NUMERIC WORD #1 MUST BE NON-ZERO'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(W2.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'NUMERIC WORD #2 MUST BE NON-ZERO'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(W3.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'NUMERIC WORD #3 MUST BE NON-ZERO'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(sys_units().EQ.1.0) WAVE=(W3*1.0D-3)/(25.4D0)
   IF(sys_units().EQ.2.0) WAVE=W3*1.0D-4
   IF(sys_units().EQ.3.0) WAVE=W3*1.0D-3
   IF(sys_units().EQ.4.0) WAVE=W3*1.0D-6
   CURVE=1.0D0/DABS((W2**2)/(4.0D0*W1*WAVE))
   IF(WQ.EQ.'ACC') THEN
      REG(40)=REG(9)
      REG(9)=CURVE
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2010) W1
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2001) W2,UN(2:12)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2002) W3
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2003) CURVE,UN
      CALL SHOWIT(0)
      RETURN
   END IF
1000 FORMAT(1X)
2000 FORMAT('    CURVATURE FOR M FRINGES OUT OF FLAT')
2010 FORMAT('    NUMBER OF FRINGES OUT OF FLAT = ',G12.4)
2001 FORMAT('                    PART DIAMETER = ',G15.6,1X,A11)
2002 FORMAT ('                       WAVELENGTH = ',G12.4,' MICRONS')
2003 FORMAT('   CORRESPONDING SURFCE CURVATURE = ',G15.6,1X,A12)
   RETURN
END
! SUB SCHWARTZ.FOR
SUBROUTINE SCHWARTZ
!       MAY THE SCHWARTZ BE WITH YOU
!
   use DATMAI
   IMPLICIT NONE
!
!       THIS SUBROUTINE HANDELS THE "RADUNITS", "WIEN", "PLANK"
!       AND "STEFBOLT" CMD LEVEL COMMANDS
!
!                       DEFINE VARIABLES
!
!       "MAY THE SCHWARTZ BE WITH YOU!"
!
!
   REAL*8 T,C1,C1P,C2,VAL ,VAL1,VAL2,SIG,SIGP,RETVAL
!
   EXTERNAL RETVAL
!
!
   C1=37415.0D0
   C1P=1.88365D23
   C2=14387.9D0
   SIG=5.6697D-12
   SIGP=1.52041D+11
!
!     WC IS RADUNITS
   IF(WC.EQ.'RADUNITS') THEN
      IF(STI.EQ.1) THEN
         IF(RADUNI.EQ.1) WRITE(OUTLYNE,10)
         IF(RADUNI.EQ.2) WRITE(OUTLYNE,20)
         CALL SHOWIT(0)
         RETURN
      END IF
      IF(SQ.EQ.1.AND.WQ.NE.'WATTS'.AND.WQ.NE.'PHOTONS') THEN
         WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "RADUNITS"'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(SQ.EQ.0..OR.SST.EQ.1) THEN
         IF(RADUNI.EQ.1) WRITE(OUTLYNE,10)
         IF(RADUNI.EQ.2) WRITE(OUTLYNE,20)
         CALL SHOWIT(0)
10       FORMAT('"RADUNITS" IS SET TO "WATTS"')
20       FORMAT('"RADUNITS" IS SET TO "PHOTONS"')
         RETURN
      END IF
      IF(WQ.EQ.'WATTS') RADUNI=1
      IF(WQ.EQ.'PHOTONS') RADUNI=2
   END IF
!
!
!     WC IS WIEN
   IF(WC.EQ.'WIEN') THEN
      IF(SQ.EQ.1.AND.WQ.NE.'P') THEN
         WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "WIEN"'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(SST.EQ.1) THEN
         WRITE(OUTLYNE,*) 'NO ADDITIONAL INFORMATION AVAILABLE'
         CALL SHOWIT(1)
         RETURN
      END IF
      IF(DF1.EQ.1) THEN
         WRITE(OUTLYNE,*) '"WIEN" REQUIRES EXPLICIT NUMERIC WORD #1 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(W1.LE.0.0D0) THEN
         WRITE(OUTLYNE,*) '"WIEN" REQUIRES (T) GREATER THAN 0'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(RADUNI.EQ.1) THEN
         VAL=2897.8D0/W1
      END IF
      IF(RADUNI.EQ.2) THEN
         VAL=3669.73D0/W1
      END IF
      IF(WQ.EQ.'P') THEN
         IF(RADUNI.EQ.1) WRITE(OUTLYNE,30) VAL
30       FORMAT('WAVELENGTH FOR PEAK RADIANT EMITTANCE = ',G23.15,' MICRON(S)')
         IF(RADUNI.EQ.2) WRITE(OUTLYNE,40) VAL
40       FORMAT('WAVELENGTH FOR PEAK RADIANT PHOTON EMITTANCE = ',G23.15,' MICRON(S)')
         CALL SHOWIT(0)
      END IF
      REG(40)=REG(9)
      REG(9)=VAL
   END IF
!
!
!     WC IS PLANK
   IF(WC.EQ.'PLANK') THEN
      IF(SQ.EQ.1.AND.WQ.NE.'P') THEN
         WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "PLANK"'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(SST.EQ.1) THEN
         WRITE(OUTLYNE,*) 'NO ADDITIONAL INFORMATION AVAILABLE'
         CALL SHOWIT(1)
         RETURN
      END IF
      IF(DF1.EQ.1.OR.DF2.EQ.1) THEN
         WRITE(OUTLYNE,*)'"PLANK" REQUIRES EXPLICIT NUMERIC WORD #1 AND #2 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(W1.LE.0.0D0) THEN
         WRITE(OUTLYNE,*) '"PLANK" REQUIRES (T) GREATER THAN 0'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(W2.LE.0.0D0) THEN
         WRITE(OUTLYNE,*) '"PLANK" REQUIRES (LAMBDA) GREATER THAN 0'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(RADUNI.EQ.1) THEN
         VAL=(C1/(W2**5))/(DEXP(C2/(W1*W2))-1.0D0)
      END IF
      IF(RADUNI.EQ.2) THEN
         VAL=(C1P/(W2**4))/(DEXP(C2/(W1*W2))-1.0D0)
      END IF
      IF(WQ.EQ.'P') THEN
         IF(RADUNI.EQ.1) WRITE(OUTLYNE,35) VAL
35       FORMAT('RADIANT EMITTANCE = ',G23.15,' WATTS/CM2-MICRON')

         IF(RADUNI.EQ.2) WRITE(OUTLYNE,45) VAL
45       FORMAT('RADIANT PHOTON EMITTANCE = ',G23.15,' PHOTONS/SEC-CM2-MICRON')
         CALL SHOWIT(0)
      END IF
      REG(40)=REG(9)
      REG(9)=VAL
   END IF
!
!
!     WC IS STEFBOLT
   IF(WC.EQ.'STEFBOLT') THEN
      IF(SQ.EQ.1.AND.WQ.NE.'P') THEN
         WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "STEFBOLT"'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(SST.EQ.1) THEN
         WRITE(OUTLYNE,*) 'NO ADDITIONAL INFORMATION AVAILABLE'
         CALL SHOWIT(1)
         RETURN
      END IF
      IF(DF1.EQ.1) THEN
         WRITE(OUTLYNE,*)'"STEFBOLT" REQUIRES EXPLICIT NUMERIC WORD #1'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(W1.LE.0.0D0) THEN
         WRITE(OUTLYNE,*) '"STEFBOLT" REQUIRES (T) GREATER THAN 0'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(DF2.EQ.1) W2=1.0D20
      IF(DF3.EQ.1) W3=0.0D0
      IF(W2.LE.0.0D0) THEN
         WRITE(OUTLYNE,*)'"STEFBOLT" REQUIRES (LAMBDA UPPER) GREATER THAN 0'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(W3.LT.0.0D0) THEN
         WRITE(OUTLYNE,*)'"STEFBOLT" REQUIRES (LAMBDA LOWER) GREATER THAN OR EQUAL TO 0'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(W3.GE.W2) THEN
         WRITE(OUTLYNE,*) '"STEFBOLT" REQUIRES (LAMBDA UPPER)'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'GREATER THAN (LAMBDA LOWER)'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(RADUNI.EQ.1) THEN
!     CASE OF TOTAL
         IF(W2.EQ.1.0D20.AND.W3.EQ.0.0D0) THEN
            VAL=SIG*(W1**4)
            GO TO 200
         END IF
!     CASE OF ONLY LAMBDA UPPER
         IF(W2.LT.1.0D20.AND.W3.EQ.0.0D0) THEN
            VAL=RETVAL(W1,W2,RADUNI)
            GO TO 200
         END IF
!     CASE OF RANGE
         IF(W2.LT.1.0D20.AND.W3.GT.0.0D0) THEN
            VAL1=RETVAL(W1,W2,RADUNI)
            VAL2=RETVAL(W1,W3,RADUNI)
            VAL=VAL1-VAL2
            GO TO 200
         END IF
      END IF
      IF(RADUNI.EQ.2) THEN
!     CASE OF TOTAL
         IF(W2.EQ.1.0D20.AND.W3.EQ.0.0D0) THEN
            VAL=SIGP*(W1**3)
            GO TO 200
         END IF
!     CASE OF ONLY LAMBDA UPPER
         IF(W2.LT.1.0D20.AND.W3.EQ.0.0D0) THEN
            VAL=RETVAL(W1,W2,RADUNI)
            GO TO 200
         END IF
!     CASE OF RANGE
         IF(W2.LT.1.0D20.AND.W3.GT.0.0D0) THEN
            VAL1=RETVAL(W1,W2,RADUNI)
            VAL2=RETVAL(W1,W3,RADUNI)
            VAL=VAL1-VAL2
            GO TO 200
         END IF
      END IF
200   CONTINUE
      IF(WQ.EQ.'P') THEN
!     HEADING
         IF(W2.EQ.1.0D20.AND.W3.EQ.0.0D0) WRITE(OUTLYNE,150)
         IF(W2.EQ.1.0D20.AND.W3.EQ.0.0D0) CALL SHOWIT(0)
         IF(W2.LT.1.0D20.AND.W3.EQ.0.0D0) WRITE(OUTLYNE,151)W2
         IF(W2.LT.1.0D20.AND.W3.EQ.0.0D0) CALL SHOWIT(0)
         IF(W2.LT.1.0D20.AND.W3.GT.0.0D0) WRITE(OUTLYNE,152)W2,W3
         IF(W2.LT.1.0D20.AND.W3.GT.0.0D0) CALL SHOWIT(0)
150      FORMAT('INTEGERATED OVER ALL WAVELENGTHS')
151      FORMAT('BELOW ',G14.6,' MICRONS')
152      FORMAT('IN THE ',G14.6,' TO ',G14.6,' MICRON BAND')
!
         IF(RADUNI.EQ.1) WRITE(OUTLYNE,135) VAL
135      FORMAT('TOTAL RADIANT EMITTANCE = ',G23.15,' WATTS/CM2')

         IF(RADUNI.EQ.2) WRITE(OUTLYNE,145) VAL
145      FORMAT('TOTAL RADIANT PHOTON EMITTANCE = ',G23.15,' PHOTONS/SEC-CM2')
         CALL SHOWIT(0)
      END IF
      REG(40)=REG(9)
      REG(9)=VAL
   END IF
!
   RETURN
END
FUNCTION RETVAL(T,LAMBDA,RADUNI)
   IMPLICIT NONE
   REAL*8 T,LAMBDA,C1,C2,C1P,SUMOLD,RETVAL,SUM ,A
   INTEGER RADUNI,K
   C1=37415.0D0
   C1P=1.88365D23
   C2=14387.9D0
   IF(RADUNI.EQ.1) THEN
!     WATT UNITS
      SUM=0.0D0
      DO K=1,1000000
         SUMOLD=SUM
         A=DEXP((-C2*DBLE(K))/(LAMBDA*T))/DBLE(K)
         SUM=SUM+(((1.0D0/LAMBDA**3)+((3.0D0*T)/(DBLE(K)*C2*(LAMBDA**2)))+((6.0D0*(T**2))/(DBLE((K**2))*(C2**2)*LAMBDA))+((6.0D0*(T**3))/(DBLE((K**3))*(C2**3))))*A)
         IF(DABS(SUM-SUMOLD).LE.1.0D-10) GO TO 999
      END DO
999   RETVAL=((T*C1)/C2)*SUM
      RETURN
   END IF
   IF(RADUNI.EQ.2) THEN
!     PHOTON UNITS
      SUM=0.0D0
      DO K=1,1000000
         SUMOLD=SUM
         A=DEXP((-C2*DBLE(K))/(LAMBDA*T))/DBLE(K)
         SUM=SUM+(((1.0D0/(LAMBDA**2))+((2.0D0*T)/(DBLE(K)*C2*LAMBDA))+((2.0D0*(T**2))/(DBLE((K**2))*(C2**2))))*A)
         IF(DABS(SUM-SUMOLD).LE.1.0D-10) GO TO 888
      END DO
888   RETVAL=((T*C1P)/C2)*SUM
      RETURN
   END IF
   RETURN
END
!
!     THIS ROUTINE DOES CROSS TRACK SPECTRAL
!
SUBROUTINE SCE(VALVAL,TYPE,V1,ERROR)
   use DATLEN
   use mod_system
   use mod_surface
   use DATMAI
   IMPLICIT NONE
   INTEGER ERROR,TYPE,I,J,K,JJ
   REAL*8 VALVAL,VALVAL1(1:3),V1,YMAX,YMIN,YV1,YV2,YV3 ,MINMIN,JKV,VV1,VAL(1:10),MAXMAX
   LOGICAL OLDLDIF,OLDLDIF2
!
!     IF TYPE=1 XFOB
!     IF TYPE=2 YFOB
   YV1=0.0D0
   YV2=0.0D0
   YV3=0.0D0
!     FOCAL AND UFOCAL ONLY
   IF(sys_mode().GE.3.0D0) THEN
      ERROR=1
      RETURN
   END IF
!
!     WAVELENGTHS ARE OK
!
   IF(TYPE.EQ.1) THEN
      VALVAL1(1:3)=0.0D0
      DO K=1,3
         IF(K.EQ.1) JKV=1.0
         IF(K.EQ.2) JKV=0.0
         IF(K.EQ.3) JKV=-1.0
         J=0
         VAL(1:10)=0.0D0
         DO 10 I=1,10
            VV1=DBLE(I)
!     CHECK WAVELENGTH
            IF(VV1.EQ.1.0D0.AND.sys_wavelength(1).EQ.0.0D0.OR.VV1.EQ.2.0D0.AND.sys_wavelength(2).EQ.0.0D0.OR.VV1.EQ.3.0D0.AND.sys_wavelength(3).EQ.0.0D0.OR.VV1.EQ.4.0D0.AND.sys_wavelength(4).EQ.0.0D0.OR.VV1.EQ.5.0D0.AND.sys_wavelength(5).EQ.0.0D0.OR.VV1.EQ.6.0D0.AND.sys_wavelength(6).EQ.0.0D0.OR.VV1.EQ.7.0D0.AND.sys_wavelength(7).EQ.0.0D0.OR.VV1.EQ.8.0D0.AND.sys_wavelength(8).EQ.0.0D0.OR.VV1.EQ.9.0D0.AND.sys_wavelength(9).EQ.0.0D0.OR.VV1.EQ.10.0D0.AND.sys_wavelength(10).EQ.0.0D0) GO TO 10
!     Y COMPONENTS OF XFOB AT DESIGNATED WAVELENGTH
            J=J+1
!
!     DO THE FOB 0 JKV 0 VV1
            SAVE_KDP(1)=SAVEINPT(1)
            OLDLDIF2=LDIF2
            OLDLDIF=LDIF
            LDIF2=.FALSE.
            LDIF=.FALSE.
            WQ='        '
            SQ=0
            SST=0
            STI=0
            W1=0.0D0
            W2=JKV
            W3=0.0D0
            W4=VV1
            W5=0.0D0
            DF1=0
            DF2=0
            DF3=0
            DF4=0
            DF5=1
            S1=1
            S2=1
            S3=1
            S4=1
            S5=0
            SN=1
!     SET MSG TO FALSE
            MSG=.FALSE.
            WC='FOB     '
            CALL FFOB
            IF(.NOT.REFEXT) THEN
               ERROR=1
               RETURN
            END IF
            REST_KDP(1)=RESTINPT(1)
! NOW THE RAY 0 0
            SAVE_KDP(1)=SAVEINPT(1)
            WQ='        '
            SQ=0
            SST=0
            DF1=1
            DF2=1
            DF3=0
            DF4=1
            DF5=1
            S1=0
            S2=0
            S3=1
            S4=0
            S5=0
            SN=0
            W1=0.0D0
            W2=0.0D0
            W3=VV1
            W4=0.0D0
            W5=0.0D0
            WC='RAY     '
            NOCOAT=.TRUE.
            GRASET=.FALSE.
            DXFSET=.FALSE.
            CALL RRAY
            IF(.NOT.RAYEXT) THEN
               ERROR=1
               RETURN
            END IF
            REST_KDP(1)=RESTINPT(1)
!     WRITE DOWN THE FIRST Y VALUE
            VAL(J)=RAYRAY(1,NEWIMG)
10       CONTINUE
         MAXMAX=-1.0D300
         MINMIN=1.0D300
         DO JJ=1,J
            IF(VAL(JJ).GT.MAXMAX) MAXMAX=VAL(JJ)
            IF(VAL(JJ).LT.MINMIN) MINMIN=VAL(JJ)
         END DO
         VALVAL1(K)=DABS(MAXMAX-MINMIN)
      END DO
      MAXMAX=-1.0D300
      DO K=1,3
         IF(VALVAL1(K).GT.MAXMAX) MAXMAX=VALVAL1(K)
      END DO
      VALVAL=MAXMAX
      IF(V1.NE.0.0D0) VALVAL=(VALVAL/V1)*100.0D0
      ERROR=0
      RETURN
   END IF
   IF(TYPE.EQ.2) THEN
      VALVAL1(1:3)=0.0D0
      DO K=1,3
         IF(K.EQ.1) JKV=1.0
         IF(K.EQ.2) JKV=0.0
         IF(K.EQ.3) JKV=-1.0
         J=0
         VAL(1:10)=0.0D0
         DO 20 I=1,10
            VV1=DBLE(I)
!     CHECK WAVELENGTH
            IF(VV1.EQ.1.0D0.AND.sys_wavelength(1).EQ.0.0D0.OR.VV1.EQ.2.0D0.AND.sys_wavelength(2).EQ.0.0D0.OR.VV1.EQ.3.0D0.AND.sys_wavelength(3).EQ.0.0D0.OR.VV1.EQ.4.0D0.AND.sys_wavelength(4).EQ.0.0D0.OR.VV1.EQ.5.0D0.AND.sys_wavelength(5).EQ.0.0D0.OR.VV1.EQ.6.0D0.AND.sys_wavelength(6).EQ.0.0D0.OR.VV1.EQ.7.0D0.AND.sys_wavelength(7).EQ.0.0D0.OR.VV1.EQ.8.0D0.AND.sys_wavelength(8).EQ.0.0D0.OR.VV1.EQ.9.0D0.AND.sys_wavelength(9).EQ.0.0D0.OR.VV1.EQ.10.0D0.AND.sys_wavelength(10).EQ.0.0D0) GO TO 20
!     Y COMPONENTS OF XFOB AT DESIGNATED WAVELENGTH
            J=J+1
!
!     DO THE FOB 0 JKV 0 VV1
            SAVE_KDP(1)=SAVEINPT(1)
            OLDLDIF2=LDIF2
            OLDLDIF=LDIF
            LDIF2=.FALSE.
            LDIF=.FALSE.
            WQ='        '
            SQ=0
            SST=0
            STI=0
            W1=JKV
            W2=0.0D0
            W3=0.0D0
            W4=VV1
            W5=0.0D0
            DF1=0
            DF2=0
            DF3=0
            DF4=0
            DF5=1
            S1=1
            S2=1
            S3=1
            S4=1
            S5=0
            SN=1
!     SET MSG TO FALSE
            MSG=.FALSE.
            WC='FOB     '
            CALL FFOB
            IF(.NOT.REFEXT) THEN
               ERROR=1
               RETURN
            END IF
            REST_KDP(1)=RESTINPT(1)
! NOW THE RAY 0 0
            SAVE_KDP(1)=SAVEINPT(1)
            WQ='        '
            SQ=0
            SST=0
            DF1=1
            DF2=1
            DF3=0
            DF4=1
            DF5=1
            S1=0
            S2=0
            S3=1
            S4=0
            S5=0
            SN=0
            W1=0.0D0
            W2=0.0D0
            W3=VV1
            W4=0.0D0
            W5=0.0D0
            WC='RAY     '
            NOCOAT=.TRUE.
            GRASET=.FALSE.
            DXFSET=.FALSE.
            CALL RRAY
            IF(.NOT.RAYEXT) THEN
               ERROR=1
               RETURN
            END IF
            REST_KDP(1)=RESTINPT(1)
!     WRITE DOWN THE FIRST Y VALUE
            VAL(J)=RAYRAY(2,NEWIMG)
20       CONTINUE
         MAXMAX=-1.0D300
         MINMIN=1.0D300
         VAL(1:10)=DABS(VAL(1:10))
         DO JJ=1,J
            IF(VAL(JJ).GT.MAXMAX) MAXMAX=VAL(JJ)
            IF(VAL(JJ).LT.MINMIN) MINMIN=VAL(JJ)
         END DO
         VALVAL1(K)=DABS(MAXMAX-MINMIN)
      END DO
      MAXMAX=-1.0D300
      DO K=1,3
         IF(VALVAL1(K).GT.MAXMAX) MAXMAX=VALVAL1(K)
      END DO
      VALVAL=MAXMAX
      IF(V1.NE.0.0D0) VALVAL=(VALVAL/V1)*100.0D0
      ERROR=0
      RETURN
   END IF
END
! SUB OIF.FOR
SUBROUTINE OIF
!
   use DATMAI
   IMPLICIT NONE
!
!
!     OIF IS A SUBROUTINE WHICH CALCULATES OBJECT OR IMAGE
!     DISTACE OR FOCAL LENGTH GIVEN ANY TWO OF THE THREE VALUES
!     USING:
!
!     1/F=1/0+1/I
!
!       OIF, NW1 NW2 NW2
!       WHERE NW1 IS THE IMAGE DISTANCE
!       WHERE NW2 IS THE OBJECT DISTANCE
!       WHERE NW3 IS THE FOCAL LENGTH
!
   REAL*8 VALUE
!
!
   IF(SST.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"OIF (P)" ONLY TAKES NUMERIC WORD #1, #2 AND #3 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(SQ.EQ.1.AND.WQ.NE.'P') THEN
      WRITE(OUTLYNE,*)'"P" IS THE ONLY OPTIONAL QUALIFIER WORD FOR "OIF"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(DF1.EQ.0.AND.W1.EQ.0.0D0.OR.DF2.EQ.0.AND.W2.EQ.0.0D0 .OR.DF3.EQ.0.AND.W3.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'"OIF (P)" DOES NOT ACCEPT 0.0 FOR ANY OF ITS INPUT VALUES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(DF1.EQ.1.AND.DF2.EQ.0.AND.DF3.EQ.0.OR.DF1.EQ.0.AND.DF2.EQ.1.AND.DF3.EQ.0.OR.DF1.EQ.0.AND.DF2.EQ.0.AND.DF3.EQ.1) THEN
!     PROCEED

      IF(DF1.EQ.1) VALUE=(1.0D0/W3)-(1.0D0/W2)
      IF(DF2.EQ.1) VALUE=(1.0D0/W3)-(1.0D0/W1)
      IF(DF3.EQ.1) VALUE=(1.0D0/W1)+(1.0D0/W2)
!       UPDATE LASTX
      REG(40)=REG(9)
      REG(9) = 1.0D0/VALUE
!
      IF(WQ.EQ.'P') THEN
         IF(DF1.EQ.1) WRITE(OUTLYNE,100) (1.0D0/VALUE)
         IF(DF1.EQ.1) CALL SHOWIT(0)
         IF(DF1.EQ.1) WRITE(OUTLYNE,20) W2
         IF(DF1.EQ.1) CALL SHOWIT(0)
         IF(DF1.EQ.1) WRITE(OUTLYNE,30) W3
         IF(DF1.EQ.1) CALL SHOWIT(0)
         IF(DF2.EQ.1) WRITE(OUTLYNE,200) (1.0D0/VALUE)
         IF(DF2.EQ.1) CALL SHOWIT(0)
         IF(DF2.EQ.1) WRITE(OUTLYNE,10) W1
         IF(DF2.EQ.1) CALL SHOWIT(0)
         IF(DF2.EQ.1) WRITE(OUTLYNE,30) W3
         IF(DF2.EQ.1) CALL SHOWIT(0)
         IF(DF3.EQ.1) WRITE(OUTLYNE,300) (1.0D0/VALUE)
         IF(DF3.EQ.1) CALL SHOWIT(0)
         IF(DF3.EQ.1) WRITE(OUTLYNE,10) W1
         IF(DF3.EQ.1) CALL SHOWIT(0)
         IF(DF3.EQ.1) WRITE(OUTLYNE,20) W2
         IF(DF3.EQ.1) CALL SHOWIT(0)
10       FORMAT(' INPUT OBJECT DISTANCE WAS = ',G13.6)
20       FORMAT('  INPUT IMAGE DISTANCE WAS = ',G13.6)
30       FORMAT('    INPUT FOCAL LENGTH WAS = ',G13.6)
100      FORMAT('THE NEW OBJECT DISTANCE IS = ',G13.6)
200      FORMAT(' THE NEW IMAGE DISTANCE IS = ',G13.6)
300      FORMAT('   THE NEW FOCAL LENGTH IS = ',G13.6)
      END IF
      RETURN
   ELSE
      WRITE(OUTLYNE,*)'"OIF (P)" REQUIRES TWO EXPLICIT NUMERIC VALUES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
   END IF
   RETURN
END
! SUB RAYLEIGH.FOR
SUBROUTINE RAYLEIGH
!
   use DATLEN
   use mod_system
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE RAYLEIGH. THIS SUBROUTINE IMPLEMENTS THE
!       RAYLEIGH RANGE CALCULATION
!       NW1=OPTIONAL BEAM WAIST DIAMETER AT 1/E2 POINT
!       NW2=OPTIONAL WAVELENGTH
!         NW3, NW4 AND NW5 NOT USED
!         WQ IS EITHER BLANK OR 'ACC'
!         WS NOT USED
!
   INTEGER I
!
   REAL*8 W0,B,LAMBDA,CFAC,LAM0
!
   CHARACTER*8 UN

!
!
   IF(sys_units().EQ.1.0) CFAC=1.0D-3/25.4D0
   IF(sys_units().EQ.2.0) CFAC=1.0D-4
   IF(sys_units().EQ.3.0) CFAC=1.0D-3
   IF(sys_units().EQ.4.0) CFAC=1.0D-6
   IF(sys_units().EQ.1.0) UN='INCH(ES)'
   IF(sys_units().EQ.2.0) UN='CM(S)'
   IF(sys_units().EQ.3.0) UN='MM(S)'
   IF(sys_units().EQ.4.0) UN='METER(S)'
!
   IF(SST.EQ.1) THEN
      WRITE(OUTLYNE,*)'"RAYLEIGH" TAKES NO ALPHANUMERIC STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"RAYLEIGH" TAKES NO NUMERIC WORD #3, #4 OR #5 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.1.AND.WQ.NE.'ACC') THEN
      WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "RAYLEIGH"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(DF1.EQ.1) THEN
      W0=2.0D0*sys_wry()
   ELSE
      W0=W1
   END IF
   IF(DF2.EQ.1) THEN
      IF(sys_wl_ref().LE.5.0D0) THEN
         LAMBDA=sys_wavelength(INT(sys_wl_ref()))
      ELSE
         LAMBDA=SYSTEM(65+INT(sys_wl_ref()))
      END IF
   ELSE
      LAMBDA=W2
   END IF
   LAM0=LAMBDA
   LAMBDA=LAMBDA*CFAC
   IF(W0.LE.0.0D0) THEN
      WRITE(OUTLYNE,*)'WAIST DIAMETER MUST BE GREATER THAN 0.0 WITH "RAYLEIGH"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(LAMBDA.LE.0.0D0) THEN
      WRITE(OUTLYNE,*)'WAVELENGTH MUST BE GREATER THAN 0.0 WITH "RAYLEIGH"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   B=(TWOPII*(W0**2))/LAMBDA
   IF(WQ.EQ.'ACC') THEN
      REG(40)=REG(9)
      REG(9)=B
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      REG(40)=REG(9)
      REG(9)=B
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2010) W0
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2020) LAM0
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2002) B,UN
      CALL SHOWIT(0)
      RETURN
   END IF
1000 FORMAT(1X)
2000 FORMAT('RAYLEIGH RANGE CALCULATION')
2010 FORMAT('BEAM WAIST DIAMETER = ',G15.6,1X,A8)
2020 FORMAT('         WAVELENGTH = ',G15.6,1X,'MICRON(S)')
2002 FORMAT('     RAYLEIGH RANGE = ',G15.6,1X,A8)
   RETURN
END
! SUB COST.FOR
SUBROUTINE COST
!
   use DATLEN
   use mod_system
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE COST. THIS SUBROUTINE IMPLEMENTS THE
!       COST CALCULATION
!       NW1=STARTING SURFACE NUMBER
!       NW2=ENDING SURFACE NUMBER
!         NW3, NW4 AND NW5 NOT USED
!         WQ IS EITHER BLANK OR 'ACC'
!         WS NOT USED
!
   INTEGER I
!
   REAL*8 VOL1,VOL2,CFAC,WEIGT,RHO2,COR1,COR2,SAG1 ,C2,RD,C,SIGNIT1,RHOA,RHOB,H,PLUG,TOTALW,MYWEIGHT,SAG2,SIGNIT2,THMFACTOR
!
!
   IF(sys_units().EQ.1.0) CFAC=(2.54D0)**3
   IF(sys_units().EQ.2.0) CFAC=1.0D0
   IF(sys_units().EQ.3.0) CFAC=0.1D0**3
   IF(sys_units().EQ.4.0) CFAC=100.D0**3
!
!
   IF(SST.EQ.1) THEN
      WRITE(OUTLYNE,*)'"COST" TAKES NO ALPHANUMERIC STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"COST" TAKES NO NUMERIC WORD #3, #4 OR #5 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.1.AND.WQ.NE.'ACC') THEN
      WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "COST"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(DF1.EQ.1) THEN
      WRITE(OUTLYNE,*)'"COST" REQUIRES EXPLICIT NUMERIC WORD #1 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(W1.LT.0.0D0.OR.W1.GT.sys_last_surf()) THEN
      WRITE(OUTLYNE,*)'NUMERIC WORD #1, SURFACE NUMBER BEYOND LEGAL BOUNDS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(S2.EQ.1) THEN
      IF(W2.LT.0.0D0.OR.W2.GT.sys_last_surf()) THEN
         WRITE(OUTLYNE,*)'NUMERIC WORD #2, SURFACE NUMBER BEYOND LEGAL BOUNDS'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(W2.LE.W1) THEN
         WRITE(OUTLYNE,*)'SECOND SURFACE MUST FOLLOW FIRST SURFACE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
   END IF
   IF(DF2.EQ.1) W2=W1+1
!
!     DO COST CALC HERE
   TOTALW=0.0D0
   IF((INT(W2)).GT.INT(W1)) THEN
      DO I=INT(W1),INT(W2)-1
         IF(surf_spgr(I).NE.0.0D0) THEN
!     ADJUSTMENT FOR R1
            IF(surf_clap_type(I).EQ.1.0D0.AND.surf_multi_clap_flag(I).EQ.0.0D0) THEN
               RHOA=DABS(surf_clap_dim(I, 1))
            ELSE
               RHOA=DABS(PXTRAY(1,I))+DABS(PXTRAY(5,I))
            END IF
            IF(surf_curvature(I).EQ.0.0D0) THEN
               COR1=0.0D0
            ELSE
               RD=DABS(1.0D0/surf_curvature(I))
               C=surf_curvature(I)
               C2=surf_curvature(I)**2
               RHO2=RHOA**2
               SAG1=((C*RHO2)/(1.0D0+(DSQRT(1.0D0-(C2*RHO2)))))
               IF(SAG1.GE.0.0D0) SIGNIT1=1.0D0
               IF(SAG1.LT.0.0D0) SIGNIT1=-1.0D0
               SAG1=DABS(SAG1)
               COR1=(1.0D0/3.0D0)*PII*(SAG1**2)*((3.0D0*RD)-SAG1)
               COR1=DABS(COR1)
               IF(SIGNIT1.LT.0.0D0) THEN
                  COR1=(PII*RHO2*SAG1)-COR1
               END IF
            END IF
!     ADJUSTMENT FOR R2
            IF(surf_clap_type(I+1).EQ.1.0D0.AND.surf_multi_clap_flag(I+1).EQ.0.0D0) THEN
               RHOB=DABS(surf_clap_dim(I+1, 1))
            ELSE
               RHOB=DABS(PXTRAY(1,I+1))+DABS(PXTRAY(5,I+1))
            END IF
            IF(surf_curvature(I+1).EQ.0.0D0) THEN
               COR2=0.0D0
            ELSE
               RD=DABS(1.0D0/surf_curvature(I+1))
               C=surf_curvature(I+1)
               C2=surf_curvature(I+1)**2
               RHO2=RHOB**2
               SAG2=((C*RHO2)/(1.0D0+(DSQRT(1.0D0-(C2*RHO2)))))
               IF(SAG2.GE.0.0D0) SIGNIT2=1.0D0
               IF(SAG2.LT.0.0D0) SIGNIT2=-1.0D0
               SAG2=DABS(SAG2)
               COR2=(1.0D0/3.0D0)*PII*(SAG2**2)*((3.0D0*RD)-SAG2)
               COR2=DABS(COR2)
               IF(SIGNIT2.GT.0.0D0) THEN
                  COR2=(PII*RHO2*SAG2)-COR2
               END IF
            END IF
!     WEIGHT OF PLUG
            H=DABS(surf_thickness(I))
            IF(SIGNIT1.GT.0.0D0) H=H-SAG1
            IF(SIGNIT2.LT.0.0D0) H=H-SAG2
            PLUG=(1.0D0/3.0D0)*PII*H*((RHOA**2)+(RHOA*RHOB)+(RHOB**2))
            MYWEIGHT=(((PLUG+COR1+COR2)*CFAC)*surf_spgr(I))
            IF(MYWEIGHT.LT.0.0D0) MYWEIGHT=0.0D0
            TOTALW=TOTALW+MYWEIGHT
            MYWEIGHT=0.0D0
         END IF
      END DO
   END IF
   DO I=INT(W1),INT(W2)
      IF(surf_mirror_thickness(I).NE.0.0D0) THEN
!     MIRROR THICKNESS
!     ADJUSTMENT FOR R1
         IF(surf_clap_type(I).EQ.1.0D0.AND.surf_multi_clap_flag(I).EQ.0.0D0) THEN
            RHOA=DABS(surf_clap_dim(I, 1))
         ELSE
            RHOA=DABS(PXTRAY(1,I))+DABS(PXTRAY(5,I))
         END IF
         IF(surf_curvature(I).EQ.0.0D0) THEN
            COR1=0.0D0
         ELSE
            RD=DABS(1.0D0/surf_curvature(I))
            C=surf_curvature(I)
            C2=surf_curvature(I)**2
            RHO2=RHOA**2
            SAG1=((C*RHO2)/(1.0D0+(DSQRT(1.0D0-(C2*RHO2)))))
            IF(SAG1.GE.0.0D0) SIGNIT1=1.0D0
            IF(SAG1.LT.0.0D0) SIGNIT1=-1.0D0
            SAG1=DABS(SAG1)
            COR1=(1.0D0/3.0D0)*PII*(SAG1**2)*((3.0D0*RD)-SAG1)
            COR1=DABS(COR1)
            IF(SIGNIT1.LT.0.0D0) THEN
               COR1=(PII*RHO2*SAG1)-COR1
            END IF
         END IF
!     ADJUSTMENT FOR BACK OF MIRROR
         IF(surf_clap_type(I).EQ.1.0D0.AND.surf_multi_clap_flag(I).EQ.0.0D0) THEN
            RHOB=DABS(surf_clap_dim(I, 1))
         ELSE
            RHOB=DABS(PXTRAY(1,I))+DABS(PXTRAY(5,I))
         END IF
         IF(surf_curvature(I).EQ.0.0D0) THEN
            COR2=0.0D0
         ELSE
            IF(surf_refractive_index(I, 1).LT.0.0D0) THEN
               RD=(1.0D0/surf_curvature(I))-DABS(surf_mirror_thickness(I))
            ELSE
               RD=(1.0D0/surf_curvature(I))+DABS(surf_mirror_thickness(I))
            END IF
            C=1.0D0/RD
            C2=C**2
            RHO2=RHOB**2
            SAG2=((C*RHO2)/(1.0D0+(DSQRT(1.0D0-(C2*RHO2)))))
            IF(SAG2.GE.0.0D0) SIGNIT2=1.0D0
            IF(SAG2.LT.0.0D0) SIGNIT2=-1.0D0
            SAG2=DABS(SAG2)
            COR2=(1.0D0/3.0D0)*PII*(SAG2**2)*((3.0D0*RD)-SAG2)
            COR2=DABS(COR2)
            IF(SIGNIT2.GT.0.0D0) THEN
               COR2=(PII*RHO2*SAG2)-COR2
            END IF
         END IF
!     WEIGHT OF PLUG
         H=DABS(surf_mirror_thickness(I))
         IF(SIGNIT1.GT.0.0D0) H=H-SAG1
         IF(SIGNIT2.LT.0.0D0) H=H-SAG2
         PLUG=(1.0D0/3.0D0)*PII*H*((RHOA**2)+(RHOA*RHOB)+(RHOB**2))
         THMFACTOR=(((PLUG+COR1+COR2)*CFAC)*surf_spgr(I))
         IF(THMFACTOR.LT.0.0D0) THMFACTOR=0.0D0
         MYWEIGHT=MYWEIGHT+THMFACTOR
         TOTALW=TOTALW+((MYWEIGHT/1000.0D0)*surf_price(I))
      END IF
   END DO
   MYWEIGHT=0.0D0
   THMFACTOR=0.0D0
   WEIGT=TOTALW
   TOTALW=0.0D0
!
   IF(WQ.EQ.'ACC') THEN
      REG(40)=REG(9)
      REG(9)=WEIGT
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      REG(40)=REG(9)
      REG(9)=WEIGT
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2010) INT(W1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2020) INT(W2)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2002) WEIGT
      CALL SHOWIT(0)
      RETURN
   END IF
1000 FORMAT(1X)
2000 FORMAT('    WEIGHT CALCULATION')
2010 FORMAT('    FROM SURFACE # = ',I3)
2020 FORMAT('      TO SURFACE # = ',I3)
2002 FORMAT('              COST = ',G15.6,1X,'Cost Units')
   RETURN
END
! SUB WEIGHT.FOR
SUBROUTINE WEIGHT
!
   use DATLEN
   use mod_system
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE WEIGHT. THIS SUBROUTINE IMPLEMENTS THE
!       WEIGHT CALCULATION
!       NW1=STARTING SURFACE NUMBER
!       NW2=ENDING SURFACE NUMBER
!         NW3, NW4 AND NW5 NOT USED
!         WQ IS EITHER BLANK OR 'ACC'
!         WS NOT USED
!
   INTEGER I
!
   REAL*8 VOL1,VOL2,CFAC,WEIGT,RHO2,COR1,COR2,SAG1 ,C2,RD,C,SIGNIT1,RHOA,RHOB,H,PLUG,TOTALW,MYWEIGHT,SAG2,SIGNIT2,THMFACTOR
!
!
   IF(sys_units().EQ.1.0) CFAC=(2.54D0)**3
   IF(sys_units().EQ.2.0) CFAC=1.0D0
   IF(sys_units().EQ.3.0) CFAC=0.1D0**3
   IF(sys_units().EQ.4.0) CFAC=100.D0**3
!
!
   IF(SST.EQ.1) THEN
      WRITE(OUTLYNE,*)'"WEIGHT" TAKES NO ALPHANUMERIC STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"WEIGHT" TAKES NO NUMERIC WORD #3, #4 OR #5 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.1.AND.WQ.NE.'ACC') THEN
      WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "WEIGHT"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(DF1.EQ.1) THEN
      WRITE(OUTLYNE,*)'"WEIGHT" REQUIRES EXPLICIT NUMERIC WORD #1 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(S2.EQ.1) THEN
      IF(W1.LT.0.0D0.OR.W1.GT.sys_last_surf()) THEN
         WRITE(OUTLYNE,*)'NUMERIC WORD #1, SURFACE NUMBER BEYOND LEGAL BOUNDS'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(W2.LT.0.0D0.OR.W2.GT.sys_last_surf()) THEN
         WRITE(OUTLYNE,*)'NUMERIC WORD #2, SURFACE NUMBER BEYOND LEGAL BOUNDS'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(W2.LE.W1) THEN
         WRITE(OUTLYNE,*)'SECOND SURFACE MUST FOLLOW FIRST SURFACE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
   END IF
   IF(DF2.EQ.1) W2=W1+1
!
!     DO WEIGHT CALC HERE
   TOTALW=0.0D0
   IF((INT(W2)).GT.INT(W1)) THEN
      DO I=INT(W1),INT(W2)-1
         IF(surf_spgr(I).NE.0.0D0) THEN
!     ADJUSTMENT FOR R1
            IF(surf_clap_type(I).EQ.1.0D0.AND.surf_multi_clap_flag(I).EQ.0.0D0) THEN
               RHOA=DABS(surf_clap_dim(I, 1))
            ELSE
               RHOA=DABS(PXTRAY(1,I))+DABS(PXTRAY(5,I))
            END IF
            IF(surf_curvature(I).EQ.0.0D0) THEN
               COR1=0.0D0
            ELSE
               RD=DABS(1.0D0/surf_curvature(I))
               C=surf_curvature(I)
               C2=surf_curvature(I)**2
               RHO2=RHOA**2
               SAG1=((C*RHO2)/(1.0D0+(DSQRT(1.0D0-(C2*RHO2)))))
               IF(SAG1.GE.0.0D0) SIGNIT1=1.0D0
               IF(SAG1.LT.0.0D0) SIGNIT1=-1.0D0
               SAG1=DABS(SAG1)
               COR1=(1.0D0/3.0D0)*PII*(SAG1**2)*((3.0D0*RD)-SAG1)
               COR1=DABS(COR1)
               IF(SIGNIT1.LT.0.0D0) THEN
                  COR1=(PII*RHO2*SAG1)-COR1
               END IF
            END IF
!     ADJUSTMENT FOR R2
            IF(surf_clap_type(I+1).EQ.1.0D0.AND.surf_multi_clap_flag(I+1).EQ.0.0D0) THEN
               RHOB=DABS(surf_clap_dim(I+1, 1))
            ELSE
               RHOB=DABS(PXTRAY(1,I+1))+DABS(PXTRAY(5,I+1))
            END IF
            IF(surf_curvature(I+1).EQ.0.0D0) THEN
               COR2=0.0D0
            ELSE
               RD=DABS(1.0D0/surf_curvature(I+1))
               C=surf_curvature(I+1)
               C2=surf_curvature(I+1)**2
               RHO2=RHOB**2
               SAG2=((C*RHO2)/(1.0D0+(DSQRT(1.0D0-(C2*RHO2)))))
               IF(SAG2.GE.0.0D0) SIGNIT2=1.0D0
               IF(SAG2.LT.0.0D0) SIGNIT2=-1.0D0
               SAG2=DABS(SAG2)
               COR2=(1.0D0/3.0D0)*PII*(SAG2**2)*((3.0D0*RD)-SAG2)
               COR2=DABS(COR2)
               IF(SIGNIT2.GT.0.0D0) THEN
                  COR2=(PII*RHO2*SAG2)-COR2
               END IF
            END IF
!     WEIGHT OF PLUG
            H=DABS(surf_thickness(I))
            IF(SIGNIT1.GT.0.0D0) H=H-SAG1
            IF(SIGNIT2.LT.0.0D0) H=H-SAG2
            PLUG=(1.0D0/3.0D0)*PII*H*((RHOA**2)+(RHOA*RHOB)+(RHOB**2))
            MYWEIGHT=(((PLUG+COR1+COR2)*CFAC)*surf_spgr(I))
            IF(MYWEIGHT.LT.0.0D0) MYWEIGHT=0.0D0
            TOTALW=TOTALW+MYWEIGHT
         END IF
      END DO
   END IF
   DO I=INT(W1),INT(W2)
      IF(surf_mirror_thickness(I).NE.0.0D0) THEN
!     MIRROR THICKNESS
!     ADJUSTMENT FOR R1
         IF(surf_clap_type(I).EQ.1.0D0.AND.surf_multi_clap_flag(I).EQ.0.0D0) THEN
            RHOA=DABS(surf_clap_dim(I, 1))
         ELSE
            RHOA=DABS(PXTRAY(1,I))+DABS(PXTRAY(5,I))
         END IF
         IF(surf_curvature(I).EQ.0.0D0) THEN
            COR1=0.0D0
         ELSE
            RD=DABS(1.0D0/surf_curvature(I))
            C=surf_curvature(I)
            C2=surf_curvature(I)**2
            RHO2=RHOA**2
            SAG1=((C*RHO2)/(1.0D0+(DSQRT(1.0D0-(C2*RHO2)))))
            IF(SAG1.GE.0.0D0) SIGNIT1=1.0D0
            IF(SAG1.LT.0.0D0) SIGNIT1=-1.0D0
            SAG1=DABS(SAG1)
            COR1=(1.0D0/3.0D0)*PII*(SAG1**2)*((3.0D0*RD)-SAG1)
            COR1=DABS(COR1)
            IF(SIGNIT1.LT.0.0D0) THEN
               COR1=(PII*RHO2*SAG1)-COR1
            END IF
         END IF
!     ADJUSTMENT FOR BACK OF MIRROR
         IF(surf_clap_type(I).EQ.1.0D0.AND.surf_multi_clap_flag(I).EQ.0.0D0) THEN
            RHOB=DABS(surf_clap_dim(I, 1))
         ELSE
            RHOB=DABS(PXTRAY(1,I))+DABS(PXTRAY(5,I))
         END IF
         IF(surf_curvature(I).EQ.0.0D0) THEN
            COR2=0.0D0
         ELSE
            IF(surf_refractive_index(I, 1).LT.0.0D0) THEN
               RD=(1.0D0/surf_curvature(I))-DABS(surf_mirror_thickness(I))
            ELSE
               RD=(1.0D0/surf_curvature(I))+DABS(surf_mirror_thickness(I))
            END IF
            C=1.0D0/RD
            C2=C**2
            RHO2=RHOB**2
            SAG2=((C*RHO2)/(1.0D0+(DSQRT(1.0D0-(C2*RHO2)))))
            IF(SAG2.GE.0.0D0) SIGNIT2=1.0D0
            IF(SAG2.LT.0.0D0) SIGNIT2=-1.0D0
            SAG2=DABS(SAG2)
            COR2=(1.0D0/3.0D0)*PII*(SAG2**2)*((3.0D0*RD)-SAG2)
            COR2=DABS(COR2)
            IF(SIGNIT2.GT.0.0D0) THEN
               COR2=(PII*RHO2*SAG2)-COR2
            END IF
         END IF
!     WEIGHT OF PLUG
         H=DABS(surf_mirror_thickness(I))
         IF(SIGNIT1.GT.0.0D0) H=H-SAG1
         IF(SIGNIT2.LT.0.0D0) H=H-SAG2
         PLUG=(1.0D0/3.0D0)*PII*H*((RHOA**2)+(RHOA*RHOB)+(RHOB**2))
         THMFACTOR=(((PLUG+COR1+COR2)*CFAC)*surf_spgr(I))
         IF(THMFACTOR.LT.0.0D0) THMFACTOR=0.0D0
         MYWEIGHT=MYWEIGHT+THMFACTOR
         TOTALW=TOTALW+MYWEIGHT
         MYWEIGHT=0.0D0
         THMFACTOR=0.0D0
      END IF
   END DO
!     CONVERT TO Kgs from gms
   WEIGT=TOTALW/1000.0D0
!
   IF(WQ.EQ.'ACC') THEN
      REG(40)=REG(9)
      REG(9)=WEIGT
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      REG(40)=REG(9)
      REG(9)=WEIGT
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2010) INT(W1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2020) INT(W2)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2002) WEIGT
      CALL SHOWIT(0)
      RETURN
   END IF
1000 FORMAT(1X)
2000 FORMAT('    WEIGHT CALCULATION')
2010 FORMAT('    FROM SURFACE # = ',I3)
2020 FORMAT('      TO SURFACE # = ',I3)
2002 FORMAT('     MASS (WEIGHT) = ',G15.6,1X,'Kgs')
   RETURN
END
! SUB DLRPFR.FOR
SUBROUTINE DLRPFR
!
   use DATLEN
   use mod_system
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE DLRPFR. THIS SUBROUTINE IMPLEMENTS THE
!       DELTA RADIUS PER FRINGE CALCULATION
!       NW1=RADIUS OF CURVATURE IN CURRENT LENS UNITS (REQUIRED)
!       NW2=PART DIAMETER IN CURRENT LENS UNITS (REQUIRED)
!       NW3=WAVELENGTH IN MICRONS (DEFAULT = 0.5461)
!         NW4 AND NW5 NOT USED
!         WQ NOT USED
!         WS NOT USED
!
   CHARACTER UN*11
!
   REAL*8 DR,WAVE,ARG1
!
!
   IF(sys_units().EQ.1.0) UN='INCHES     '
   IF(sys_units().EQ.2.0) UN='CENTIMETERS'
   IF(sys_units().EQ.3.0) UN='MILLIMETERS'
   IF(sys_units().EQ.4.0) UN='METERS'
!
!
   IF(SST.EQ.1) THEN
      WRITE(OUTLYNE,*)'"DR/FR" TAKES NO ALPHANUMERIC STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"DR/FR" TAKES NO NUMERIC WORD #4 OR #5 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.1.AND.WQ.NE.'ACC') THEN
      WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "DR/FR"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       HANDLE DEFAULT VALUES FOR NW1, NW2 AND NW3
!
   IF(DF1.EQ.1.OR.DF2.EQ.1) THEN
      WRITE(OUTLYNE,*)'"DR/FR" REQUIRES EXPLICIT NUMERIC WORD #1 AND #2 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(DF3.EQ.1) W3=0.5461D0
   IF(W1.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'NUMERIC WORD #1 MUST BE NON-ZERO'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(W2.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'NUMERIC WORD #2 MUST BE NON-ZERO'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(W3.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'NUMERIC WORD #3 MUST BE NON-ZERO'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   ARG1=(W1**2)-((W2/2.0D0)**2)
   IF(ARG1.LT.0.0D0) THEN
      WRITE(OUTLYNE,*)'DR/FR CAN NOT BE CALCULATED FOR CURRENT INPUT VALUES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(sys_units().EQ.1.0) WAVE=(W3*1.0D-3)/(25.4D0)
   IF(sys_units().EQ.2.0) WAVE=W3*1.0D-4
   IF(sys_units().EQ.3.0) WAVE=W3*1.0D-3
   IF(sys_units().EQ.4.0) WAVE=W3*1.0D-6
   DR=DABS((WAVE*DSQRT(ARG1))/(2.0D0*(DSQRT(ARG1)-DABS(W1))))
   IF(WQ.EQ.'ACC') THEN
      REG(40)=REG(9)
      REG(9)=DR
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2010) W1,UN
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2001) W2,UN
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2002) W3
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2003) DR,UN
      CALL SHOWIT(0)
      RETURN
   END IF
1000 FORMAT(1X)
2000 FORMAT('    DELTA RADIUS PER FRINGE CALCULATION')
2010 FORMAT('    RADIUS OF CURVATURE = ',G15.6,1X,A11)
2001 FORMAT('          PART DIAMETER = ',G15.6,1X,A11)
2002 FORMAT('             WAVELENGTH = ',G12.4,' MICRONS')
2003 FORMAT('DELTA RADIUS PER FRINGE = ',G15.6,1X,A11)
   RETURN
END
! SUB DTOR.FOR
SUBROUTINE DTOR
!
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE DTOR. THIS SUBROUTINE IMPLEMENTS
!     THE CMD LEVEL "DTOR" COMMAND
!
!       FORM OF THE DTOR COMMAND IS:
!
!       DTOR , DVALUE ,EVALUE
!
!
   IF(STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"DTOR" CONVERTS D TO R USING THE (e) VALUE'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1.OR.SQ.EQ.1) THEN
      WRITE(OUTLYNE,*)'"DTOR" ONLY TAKES NUMERIC WORD #1 AND #2 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       HANDLE DEFAULT VALUES FOR NW1 AND NW2 AND NW3
!
   IF(DF1.EQ.1.OR.DF2.EQ.1) THEN
      WRITE(OUTLYNE,*)'"DTOR" REQUIRES EXPLICIT NUMERIC WORD #1 AND #2 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(W1.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'"DTOR" REQUIRES A NON-ZERO D VALUE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(W2.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'"DTOR" REQUIRES A NON-ZERO (e) VALUE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5001) W1
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5002) W2
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5003) -(W1*W2)
   CALL SHOWIT(0)
   REG(40)=REG(9)
   REG(9)=-(W1*W2)
!
1000 FORMAT(1X)
5000 FORMAT('FOR THE INPUT VALUES OF:')
5001 FORMAT('D = ',D23.15,' LENS UNITS')
5002 FORMAT('e = ',D23.15)
5003 FORMAT('R = ',D23.15,' LENS UNITS')
   RETURN
END
! SUB RTOD.FOR
SUBROUTINE RTOD
!
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE RTOD. THIS SUBROUTINE IMPLEMENTS
!     THE CMD LEVEL "RTOD" COMMAND
!
!       FORM OF THE DTOR COMMAND IS:
!
!       RTOD , RVALUE ,EVALUE
!
!
   IF(STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"RTOD" CONVERTS R TO D USING THE (e) VALUE'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1.OR.SQ.EQ.1) THEN
      WRITE(OUTLYNE,*)'"RTOD" ONLY TAKES NUMERIC WORD #1 AND #2 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       HANDLE DEFAULT VALUES FOR NW1 AND NW2 AND NW3
!
   IF(DF1.EQ.1.OR.DF2.EQ.1) THEN
      WRITE(OUTLYNE,*)'"RTOD" REQUIRES EXPLICIT NUMERIC WORD #1 AND #2 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(W1.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'"RTOD" REQUIRES A NON-ZERO R VALUE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(W2.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'"RTOD" REQUIRES A NON-ZERO (e) VALUE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5001) W1
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5002) W2
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5003) -W1/W2
   CALL SHOWIT(0)
   REG(40)=REG(9)
   REG(9)=-(W1/W2)
!
1000 FORMAT(1X)
5000 FORMAT('FOR THE INPUT VALUES OF:')
5001 FORMAT('R = ',D23.15,' LENS UNITS')
5002 FORMAT('e = ',D23.15)
5003 FORMAT('D = ',D23.15,' LENS UNITS')
   RETURN
END
! SUB ETOCC.FOR
SUBROUTINE ETOCC
!
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE ETOCC. THIS SUBROUTINE IMPLEMENTS
!     THE CMD LEVEL "ETOCC" COMMAND
!
!       FORM OF THE ETOCC COMMAND IS:
!
!       ETOCC , (e) , (-1.0 IF e IS IMAGINARY)
!
!
   IF(STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"ETOCC" CONVERTS (e) TO CC'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1.OR.SQ.EQ.1) THEN
      WRITE(OUTLYNE,*)'"ETOCC" ONLY TAKES NUMERIC WORD #1 AND #2 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       HANDLE DEFAULT VALUES FOR NW1
!
   IF(DF1.EQ.1) THEN
      WRITE(OUTLYNE,*)'"ETOCC" REQUIRES EXPLICIT NUMERIC WORD #1'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(W1.LT.0.0D0) THEN
      WRITE(OUTLYNE,*)'"ETOCC" REQUIRES A POSITIVE NUMERIC WORD #1'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(S2.EQ.1.AND.W2.NE.-1.0D0) THEN
      WRITE(OUTLYNE,*)'EXPLICIT NUMERIC WORD #2 INPUT MUST BE "-1.0"'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(DF2.EQ.1) W2=1.0D0
!
!
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5001) W1
   CALL SHOWIT(0)
   IF(W2.NE.-1.0D0) WRITE(OUTLYNE,5003)
   IF(W2.NE.-1.0D0) CALL SHOWIT(0)
   IF(W2.EQ.-1.0D0) WRITE(OUTLYNE,5004)
   IF(W2.EQ.-1.0D0) CALL SHOWIT(0)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5002) -W2*(W1**2)
   CALL SHOWIT(0)
   REG(40)=REG(9)
   REG(9)=-W2*(W1**2)
!
1000 FORMAT(1X)
5000 FORMAT('FOR THE INPUT VALUE OF:')
5001 FORMAT('(e) = ',D23.15)
5002 FORMAT('CC  = ',D23.15)
5003 FORMAT('(e) WAS INPUT AS REAL')
5004 FORMAT('(e) WAS INPUT AS IMAGINARY')
   RETURN
END
! SUB CCTOE.FOR
SUBROUTINE CCTOE
!
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE CCTOE. THIS SUBROUTINE IMPLEMENTS
!     THE CMD LEVEL "CCTOE" COMMAND
!
!       FORM OF THE CCTOE COMMAND IS:
!
!       CCTOE , CC
!
!
   IF(STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"CCTOE" CONVERTS CC TO (e)'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1.OR.SQ.EQ.1 .OR.S2.EQ.1) THEN
      WRITE(OUTLYNE,*)'"CCTOE" ONLY TAKES NUMERIC WORD #1 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       HANDLE DEFAULT VALUES FOR NW1
!
   IF(DF1.EQ.1) THEN
      WRITE(OUTLYNE,*)'"CCTOE" REQUIRES EXPLICIT NUMERIC WORD #1'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5001) W1
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   IF(W1.NE.0.0D0) WRITE(OUTLYNE,5002) DSQRT(DABS(W1))
   IF(W1.NE.0.0D0) CALL SHOWIT(0)
   IF(W1.EQ.0.0D0) WRITE(OUTLYNE,5002) W1
   IF(W1.EQ.0.0D0) CALL SHOWIT(0)
   IF(W1.LE.0.0D0) WRITE(OUTLYNE,5003)
   IF(W1.LE.0.0D0) CALL SHOWIT(0)
   IF(W1.GT.0.0D0) WRITE(OUTLYNE,5004)
   IF(W1.GT.0.0D0) CALL SHOWIT(0)
   REG(40)=REG(9)
   IF(W1.NE.0.0D0) REG(9)=DSQRT(DABS(W1))
   IF(W1.EQ.0.0D0) REG(9)=0.0D0
!
1000 FORMAT(1X)
5000 FORMAT('FOR THE INPUT VALUE OF:')
5001 FORMAT('CC  = ',D23.15)
5002 FORMAT('(e)  = ',D23.15)
5003 FORMAT('(e) IS REAL')
5004 FORMAT('(e) IS IMAGINARY')
   RETURN
END
! SUB ZZEEOO.FOR
SUBROUTINE ZZEEOO
!
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE ZZEEOO. THIS SUBROUTINE IMPLEMENTS
!     THE CMD LEVEL "Z0" COMMAND WHICH CALCULTES THE Z POSITIONS OF
!     OF CONIC GIVEN THE CURVATURE CV, THE CONIC CONSTANT CC
!     AND A RHO HEIGHT.
!
!       FORM OF THE FOCI COMMAND IS:
!
!       Z0 (R or C) ,(radius or curvature) , (conic constant) , RHO
!
   REAL*8 RHO,CEE,Z1,Z2,AC,KAPPA
!
!
   IF(STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"Z0" COMPUTES AND DISPLAYS CONIC SECTION Z POSITIONS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'GIVEN RADII OR CURVATURE CONIC CONSTANT AND RHO AS INPUTS'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"Z0" ONLY TAKES QUALIFIER AND NUMERIC WORD #1, #2 AND #3 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       HANDLE DEFAULT VALUES FOR NW1 AND NW2 AND NW3
!
   IF(DF1.EQ.1.OR.DF2.EQ.1.OR.DF3.EQ.1) THEN
      WRITE(OUTLYNE,*)'"Z0" REQUIRES EXPLICIT NUMERIC WORD #1, #2 AND #3 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      SQ=1
      WQ='R       '
   END IF
   IF(WQ(1:1).NE.'R'.AND.WQ(1:1).NE.'C') THEN
      WRITE(OUTLYNE,*)'"Z0" ONLY TAKES "R" (FOR RADIUS)'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'               OR "C" (FOR CURVATURE) AS QUALIFIER WORDS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
!     FLAT SURFACES
   IF(W1.EQ.0.0D0.OR.WQ.EQ.'R'.AND.DABS(W1).GT.1.0D20) THEN
      WRITE(OUTLYNE,*)'"Z0" REQUIRES A NON-PLANO SURFACE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   Z1=0.0D0
   Z2=0.0D0
   IF(WQ(1:1).EQ.'R') CEE=1/W1
   IF(WQ(1:1).EQ.'C') CEE=W1
   KAPPA=W2
   RHO=W3
   AC=4.0D0-(4.0D0*(KAPPA+1.0D0)*(RHO**2)*(CEE**2))
   IF(AC.LT.0.0D0) THEN
      WRITE(OUTLYNE,*)'"Z0" CAN NOT BE CALCULATED WITH CURRENT INPUT VALUES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*) 'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF((KAPPA+1.0D0).NE.0.0D0) THEN
      Z1=(2.0D0+DSQRT(AC))/(2.0D0*(KAPPA+1.0D0)*CEE)
      Z2=(2.0D0-DSQRT(AC))/(2.0D0*(KAPPA+1.0D0)*CEE)
   ELSE
!     PARABOLA
      Z1=((RHO**2)*CEE)/2.0D0
   END IF
   IF((KAPPA+1.0D0).EQ.0.0D0) THEN
!     ONE Z VALUE
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,5000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,5001)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1001) CEE,(1.0D0/CEE)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1002) KAPPA
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1003) RHO
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2000) Z1
      CALL SHOWIT(0)
      REG(40)=REG(9)
      REG(9)=(Z1)
   ELSE
!     TWO ZEE VALUES
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,5000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,5002)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1001) CEE,(1.0D0/CEE)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1002) KAPPA
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1003) RHO
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2001) Z1
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2002) Z2
      CALL SHOWIT(0)
      REG(40)=REG(9)
      REG(10)=Z1
      REG(9)=Z2
   END IF
!
1000 FORMAT(1X)
5000 FORMAT('FOR THE INPUT VALUES OF:')
5001 FORMAT('PARABOLA WITH ONE Z VALUE')
5002 FORMAT('NON-PARABOLA WITH TWO Z VALUES')
1001 FORMAT('     CURVATURE = ',D23.15,' (RADIUS = ',D23.15,')')
1002 FORMAT('CONIC CONSTANT = ',D23.15)
1003 FORMAT('           RHO = ',D23.15)
2000 FORMAT('  THE NEW Z IS = ',D23.15)
2001 FORMAT(' THE NEW Z1 IS = ',D23.15)
2002 FORMAT(' THE NEW Z2 IS = ',D23.15)
   RETURN
END
! SUB RRHHOO.FOR
SUBROUTINE RRHHOO
!
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE RRHHOO. THIS SUBROUTINE IMPLEMENTS
!     THE CMD LEVEL "RHO" COMMAND WHICH CALCULTES THE RHO POSITIONS OF
!     OF CONICS GIVEN THE CURVATURE CV, THE CONIC CONSTANT CC
!     AND A Z-POSITION (Z).
!
!       FORM OF THE FOCI COMMAND IS:
!
!       RHO (R or C) ,(radius or curvature) , (conic constant) , Z
!
   REAL*8 RHO2,RHO,CEE,ZEE,KAPPA
!
!
   IF(STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"RHO" COMPUTES AND DISPLAYS CONIC SECTION RHO HEIGHTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'GIVEN RADII OR CURVATURE CONIC CONSTANT AND Z AS INPUTS'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"RHO" ONLY TAKES QUALIFIER AND NUMERIC WORD #1, #2 AND #3 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       HANDLE DEFAULT VALUES FOR NW1 AND NW2 AND NW3
!
   IF(DF1.EQ.1.OR.DF2.EQ.1.OR.DF3.EQ.1) THEN
      WRITE(OUTLYNE,*)'"RHO" REQUIRES EXPLICIT NUMERIC WORD #1, #2 AND #3 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      SQ=1
      WQ='R       '
   END IF
   IF(WQ(1:1).NE.'R'.AND.WQ(1:1).NE.'C') THEN
      WRITE(OUTLYNE,*)'"RHO" ONLY TAKES "R" (FOR RADIUS)'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'               OR "C" (FOR CURVATURE) AS QUALIFIER WORDS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
!     FLAT SURFACES
   IF(W1.EQ.0.0D0.OR.WQ.EQ.'R'.AND.DABS(W1).GT.1.0D20) THEN
      WRITE(OUTLYNE,*)'"RHO" REQUIRES A NON-PLANO SURFACE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   RHO2=0.0D0
   IF(WQ(1:1).EQ.'R') CEE=1/W1
   IF(WQ(1:1).EQ.'C') CEE=W1
   KAPPA=W2
   ZEE=W3
   RHO2=(((2.0D0*ZEE)-(CEE*(KAPPA+1.0D0)*(ZEE**2)))/CEE)
   IF(RHO2.LT.0.0D0) THEN
      WRITE(OUTLYNE,*)'"RHO" WILL BE IMAGINARY WITH CURRENT INPUT VALUES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   RHO=DSQRT(RHO2)
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1001) CEE,(1.0D0/CEE)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1002) KAPPA
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1003) ZEE
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,2000) RHO
   CALL SHOWIT(0)
   REG(40)=REG(9)
   REG(9)=RHO
!
!
1000 FORMAT(1X)
5000 FORMAT('FOR THE INPUT VALUES OF:')
1001 FORMAT('     CURVATURE = ',D23.15,' (RADIUS = ',D23.15,')')
1002 FORMAT('CONIC CONSTANT = ',D23.15)
1003 FORMAT('             Z = ',D23.15)
2000 FORMAT('THE NEW RHO IS = ',D23.15)
   RETURN
END
! SUB FOCII.FOR
SUBROUTINE FOCII
!
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE FOCII. THIS SUBROUTINE IMPLEMENTS
!     THE CMD LEVEL "FOCI" COMMAND WHICH CALCULTES THE POSITIONS OF
!     FOCI OF CONICS GIVEN THE CURVATURE CV AND THE CONIC CONSTANT CC
!
!       FORM OF THE FOCI COMMAND IS:
!
!       FOCI (R or C) ,(radius or curvature) , (conic constant)
!
   REAL*8 W11,B,FC,FC1,FC2
!
!
   FC=0.0D0
   FC1=0.0D0
   FC2=0.0D0
!       THE FOCI COMMAND ACCEPTS ONLY NW1 AND NW2 NUMERIC
!       INPUT . IT DOES NOT ACCEPT STING OR QUALIFIER
!       INPUT.
!
   IF(STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"FOCI" COMPUTES AND DISPLAYS CONIC SECTION FOCI POSITIONS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'GIVEN RADII OR CURVATURE AND CONIC CONSTANT AS INPUTS'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"FOCI" ONLY TAKES QUALIFIER AND NUMERIC WORD #1 AND #2 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       HANDLE DEFAULT VALUES FOR NW1 AND NW2
!
   IF(DF1.EQ.1.OR.DF2.EQ.1) THEN
      WRITE(OUTLYNE,*)'"FOCI" REQUIRES EXPLICIT NUMERIC WORD #1 AND #2 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      SQ=1
      WQ='R       '
   END IF
   IF(WQ(1:1).NE.'R'.AND.WQ(1:1).NE.'C') THEN
      WRITE(OUTLYNE,*)'"FOCI" ONLY TAKES "R" (FOR RADIUS)'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'               OR "C" (FOR CURVATURE) AS QUALIFIER WORDS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
!     FLAT SURFACES
   IF(W1.EQ.0.0D0.OR.WQ.EQ.'R'.AND.DABS(W1).GT.1.0D20) THEN
      WRITE(OUTLYNE,*)'"FOCI" REQUIRES A NON-PLANO SURFACE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
!     SPHERICAL SURFACES
   IF(W2.EQ.0.0D0) THEN
      WRITE(OUTLYNE,*)'"FOCI" REQUIRES A NON-SPHERICAL SURFACE (CC NOT = 0)'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
!     CC > 0 OBLATE SHPEROID SURFACES
   IF(W2.GT.0.0D0) THEN
      WRITE(OUTLYNE,*)'"FOCI" DOES NOT WORK WITH OBLATE SPHERIODS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'"FOCI" REQUIRES CC < 0)'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   IF(W2.EQ.-1.0D0) THEN
!     PARABOLA
      IF(WQ(1:1).EQ.'C') W11=W1
      IF(WQ(1:1).EQ.'R') W11=1.0D0/W1
      FC=1.0D0/(W11*2.0D0)
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1001)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1002) FC
      CALL SHOWIT(0)
      REG(40)=REG(9)
      REG(9)=FC
      RETURN
   END IF
   IF(W2.LT.-1.0D0) THEN
!     HYPERBOLA
      IF(WQ(1:1).EQ.'C') W11=W1
      IF(WQ(1:1).EQ.'R') W11=1.0D0/W1
      B=-1.0D0/(W11*(W2+1.0D0))
      FC1=B*(DSQRT(-W2)-1.0D0)
      FC2=B*(-DSQRT(-W2)-1.0D0)
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2001)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2002) FC1
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2003) FC2
      CALL SHOWIT(0)
      REG(40)=REG(9)
      REG(10)=FC1
      REG(9)=FC2
      RETURN
   END IF
   IF(W2.LT.0.0D0.AND.W2.GT.-1.0D0) THEN
!     PROLATE SPHERIOD
      IF(WQ(1:1).EQ.'C') W11=W1
      IF(WQ(1:1).EQ.'R') W11=1.0D0/W1
      B=(1.0D0/(W11*(W2+1.0D0)))
      FC1=B*(1.0D0-DSQRT(DABS(W2)))
      FC2=B*(1.0D0+DSQRT(DABS(W2)))
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,3001)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,3002) FC1
      CALL SHOWIT(0)
      WRITE(OUTLYNE,3003) FC2
      CALL SHOWIT(0)
      REG(40)=REG(9)
      REG(10)=FC1
      REG(9)=FC2
      RETURN
   END IF
1000 FORMAT(1X)
1001 FORMAT('SURFACE TYPE = PARABOLA')
1002 FORMAT('SURFACE VERTEX TO FOCUS DISTANCE IS = ',D23.15)
2001 FORMAT('SURFACE TYPE = HYPERBOLA')
2002 FORMAT('SURFACE VERTEX TO NEAR FOCUS DISTANCE IS = ',D23.15)
2003 FORMAT('SURFACE VERTEX TO FAR  FOCUS DISTANCE IS = ',D23.15)
3001 FORMAT('SURFACE TYPE = PROLATE SPHERIOD')
3002 FORMAT('SURFACE VERTEX TO NEAR FOCUS DISTANCE IS = ',D23.15)
3003 FORMAT('SURFACE VERTEX TO FAR  FOCUS DISTANCE IS = ',D23.15)
   RETURN
END
! SUB APOVERT.FOR
SUBROUTINE APOVERT
!
   use DATMAI
   IMPLICIT NONE
!
!       THIS SUBROUTINE HANDELS THE "K0" AND "CVG"
!       CMD LEVEL COMMANDS
!
!                       DEFINE VARIABLES
!
   REAL*8 CURVE,ZZERO
!
!
   ZZERO=0.0D0
   IF(SQ.EQ.1.OR.SST.EQ.1) THEN
      WRITE(OUTLYNE,*)'"K0" AND "CVG" TAKE NO QUALIFIER OR STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(WC.EQ.'K0'.AND.STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"K0" DOES A K0, APO-VERTEXT CALCULATION'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(WC.EQ.'CVG'.AND.STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"CVG" DOES A CURVATURE, APO-VERTEXT CALCULATION'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(WC.EQ.'K0') THEN
      IF(S4.EQ.1.OR.S5.EQ.1) THEN
         WRITE(OUTLYNE,*)'"K0" TAKES NO NUMERIC WORD #4 OR #5 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         RETURN
      END IF
      IF(DF1.EQ.1.OR.DF2.EQ.1.OR.DF3.EQ.1) THEN
         WRITE(OUTLYNE,*)'"K0" REQUIRES EXPLICIT NUMERIC WORD #1, #2 AND #3 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         RETURN
      END IF
      IF(W1.EQ.0.0D0) THEN
         WRITE(OUTLYNE,*)'"K0" REQUIRES A NON-ZERO NUMERIC WORD #1 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         RETURN
      END IF
      ZZERO=(1.0D0/W1)+((1.0D0+W2)*W3)
10    FORMAT('THE "Z0" VALUE IS : ',D23.15,' LENS UNITS')
      WRITE(OUTLYNE,10) ZZERO
      CALL SHOWIT(0)
      REG(40)=REG(9)
      REG(9)=ZZERO
      RETURN
   END IF
   IF(WC.EQ.'CVG') THEN
      IF(S4.EQ.1.OR.S5.EQ.1) THEN
         WRITE(OUTLYNE,*)'"CVG" TAKES NO NUMERIC WORD #4 OR #5 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         RETURN
      END IF
      IF(DF1.EQ.1.OR.DF2.EQ.1.OR.DF3.EQ.1) THEN
         WRITE(OUTLYNE,*)'"CVG" REQUIRES EXPLICIT NUMERIC WORD #1, #2 AND #3 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         RETURN
      END IF
      CURVE=(W1)+((1.0D0+W2)*W3)
      IF(CURVE.EQ.0.0D0) THEN
         WRITE(OUTLYNE,*)'THE "CVR" VALUE WAS INFINITE. CHECK YOUR INPUT VALUES'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         REG(40)=REG(9)
         REG(9)=0.0D0
         CALL MACFAL
         RETURN
      END IF
20    FORMAT('THE "CVR" VALUE IS : ',D23.15,' INVERSE LENS UNITS')
      WRITE(OUTLYNE,20) (1.0D0/CURVE)
      CALL SHOWIT(0)
      REG(40)=REG(9)
      REG(9)=(1.0D0/CURVE)
      RETURN
   END IF
!
END
