!       THIRD SET OF OPTIMIZATION ROUTINES

! SUB CVRBL1.FOR
SUBROUTINE CVRBL1
!
   use DATSUB
   use DATMAI
   IMPLICIT NONE
!
!
   LOGICAL YES
!
   INTEGER I,J
!
!       THIS IS SUBROUTINE CVRBL1. THIS IS THE SUBROUTINE WHICH
!       INITIALLY STARTS THE SETUP OF A NEW COMP VARIABLE SUBFILE
!       THE CMD LEVEL IS DISABLED AND FLAG F52 IS SET TO 1.
!
   IF(SQ.EQ.1.OR.SST.EQ.1.OR.SN.EQ.1) THEN
      WRITE(OUTLYNE,*)'"',WC,'" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   F1=0
   F52=1
!
!       SET THE COUNTER TO THE TOP OF THE VARIABLE ARRAY STRUCTURE.
!       (VARIABLE VBCNT)
   VBCNT=0
   ISCOMP(1:MAXCMP)=.FALSE.
   VARABL(1:MAXCMP,1:17)=0.0D0
!
!       THE MAXIMUM NUMBER OF COMP VARIABLES ALLOWABLE
!       IS SET IN PROGRAM.FOR WITH THE VALUE MAXCMP WHICH IS
!       PASSED IN A COMMON IN THE INCLUDE FILE DATSUB.FOR
!
   RETURN
END
! SUB VRBL1.FOR
SUBROUTINE VRBL1
!
   use DATSUB
   use DATMAI
   IMPLICIT NONE
!
!
   INTEGER I,J
!
!       THIS IS SUBROUTINE VRBL1. THIS IS THE SUBROUTINE WHICH
!       INITIALLY STARTS THE SETUP OF A NEW VARIABLE SUBFILE
!       THE CMD LEVEL IS DISABLED AND FLAG F29 IS SET TO 1.
!
   IF(SQ.EQ.1.OR.SST.EQ.1.OR.SN.EQ.1) THEN
      WRITE(OUTLYNE,*)'"',WC,'" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   F1=0
   F29=1
!
!       SET THE COUNTER TO THE TOP OF THE VARIABLE ARRAY STRUCTURE.
!       (VARIABLE VBCNT)
   VBCNT=0
   TVBCNT=0
!
!       THE MAXIMUM NUMBER OF VARIABLES ALLOWABLE
!       IS SET IN PROGRAM.FOR WITH THE VALUE MAXVB WHICH IS
!       PASSED IN A COMMON IN THE INCLUDE FILE DATSUB.FOR
!
!       THE ARRAY VARIABLE STORES VARIABLE INFORMATION
!       IT IS PASSED IN COMMON IN THE INCLUDE FILE DATSUB.FOR
!
!                       SET VBCFG=1
   VBCFG=1
!     THIS MAKES CFG 1 THE DEFAULT CONFIG FOR VARIABLES
!
   RETURN
END
! SUB TVRBL1.FOR
SUBROUTINE TVRBL1
!
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
!
   INTEGER I,J
!
!       THIS IS SUBROUTINE TVRBL1. THIS IS THE SUBROUTINE WHICH
!       INITIALLY STARTS THE SETUP OF A NEW TOLERANCE VARIABLE SUBFILE
!       THE CMD LEVEL IS DISABLED AND FLAG F51 IS SET TO 1.
!
   IF(SQ.EQ.1.OR.SST.EQ.1.OR.SN.EQ.1) THEN
      WRITE(OUTLYNE,*)'"',WC,'" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   F1=0
   F51=1
!
!       SET THE COUNTER TO THE TOP OF THE TVAR ARRAY STRUCTURE.
!       (VARIABLE TVBCNT)
   TVBCNT=0
   VBCNT=0
!     ZERO THE TOLER ARRAY
   TOLER(1:60,0:MAXSUR)=0.0D0
   ASTILTXP=0.0D0
   ASTILTYP=0.0D0
   ASTILTZP=0.0D0
   BSTILTXP=0.0D0
   BSTILTYP=0.0D0
   BSTILTZP=0.0D0
   GSTILTXP=0.0D0
   GSTILTYP=0.0D0
   GSTILTZP=0.0D0
   ABTILTXP=0.0D0
   ABTILTYP=0.0D0
   ABTILTZP=0.0D0
   BBTILTXP=0.0D0
   BBTILTYP=0.0D0
   BBTILTZP=0.0D0
   GBTILTXP=0.0D0
   GBTILTYP=0.0D0
   GBTILTZP=0.0D0
!
!       THE MAXIMUM NUMBER OF TVARIABLES ALLOWABLE
!       IS SET TO VALUE MAXTVB. MAXTVB IS
!       PASSED IN A COMMON IN THE INCLUDE FILE DATSUB.FOR
!
!       THE ARRAY VARIABLE STORES VARIABLE INFORMATION
!       IT IS PASSED IN COMMON IN THE INCLUDE FILE DATSUB.FOR
!
   RETURN
END
! SUB UCVRBL1.FOR
SUBROUTINE UCVRBL1
!
   use DATSUB
   use DATMAI
   IMPLICIT NONE
!
!
!       THIS IS SUBROUTINE UCVRBL1. THIS IS THE SUBROUTINE WHICH
!       STARTS AN UPDATE COMPENSATION VARIABLE SESSION.
!       THE CMD LEVEL IS DISABLED AND FLAG F52 IS SET TO 2.
!
   IF(SST.EQ.1.OR.SN.EQ.1) THEN
      WRITE(OUTLYNE,*)'"UPDATE COMPVAR" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   F1=0
   F52=2
!
!       ANY OTHER ACTION TO BE TAKEN DURING RAYSET UPDATE IS HANDLED
!       FROM WITHIN SUBROUTINE CVARBLL.FOR.
!
   RETURN
END
! SUB UVRBL1.FOR
SUBROUTINE UVRBL1
!
   use DATSUB
   use DATMAI
   IMPLICIT NONE
!
!
!       THIS IS SUBROUTINE UVRBL1. THIS IS THE SUBROUTINE WHICH
!       STARTS AN UPDATE VARIABLE SESSION.
!       THE CMD LEVEL IS DISABLED AND FLAG F29 IS SET TO 2.
!
   IF(SST.EQ.1.OR.SN.EQ.1) THEN
      WRITE(OUTLYNE,*)'"UPDATE VARIABLE" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   F1=0
   F29=2
!
!                       SET VBCFG=1
   VBCFG=1
!     THIS MAKES CFG 1 THE DEFAULT CONFIG FOR VARIABLES
!
!       ANY OTHER ACTION TO BE TAKEN DURING RAYSET UPDATE IS HANDLED
!       FROM WITHIN SUBROUTINE VARBLL.FOR.
!
   RETURN
END
! SUB TUVRBL1.FOR
SUBROUTINE TUVRBL1
!
   use DATSUB
   use DATMAI
   IMPLICIT NONE
!
!
!       THIS IS SUBROUTINE TUVRBL1. THIS IS THE SUBROUTINE WHICH
!       STARTS AN UPDATE TOLERANCE VARIABLE SESSION.
!       THE CMD LEVEL IS DISABLED AND FLAG F29 IS SET TO 2.
!
   IF(SST.EQ.1.OR.SN.EQ.1) THEN
      WRITE(OUTLYNE,*)'"UPDATE TVAR" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   F1=0
   F51=2
!
!       ANY OTHER ACTION TO BE TAKEN DURING RAYSET UPDATE IS HANDLED
!       FROM WITHIN SUBROUTINE TVARBLL.FOR.
!
   RETURN
END
! SUB UTOPER.FOR
SUBROUTINE UTOPER
!
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
!
!       THIS IS SUBROUTINE UTOPER. THIS IS THE SUBROUTINE WHICH
!       STARTS AN UPDATE TOPER SESSION.
!       THE CMD LEVEL IS DISABLED AND FLAG F53 IS SET TO 2.
!
   IF(SST.EQ.1.OR.SN.EQ.1) THEN
      WRITE(OUTLYNE,*)'"UPDATE TOPER" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   F1=0
   F53=2
   CORMOD=1
   RETURN
END
! SUB UFOCRIT.FOR
SUBROUTINE UFOCRIT
!
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
!
!       THIS IS SUBROUTINE UFOCRIT. THIS IS THE SUBROUTINE WHICH
!       STARTS AN UPDATE FOCRIT SESSION.
!       THE CMD LEVEL IS DISABLED AND FLAG F54 IS SET TO 2.
!
   IF(SST.EQ.1.OR.SN.EQ.1) THEN
      WRITE(OUTLYNE,*)'"UPDATE FOCRIT" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   F1=0
   F54=2
   CORMOD=1
   RETURN
END
! SUB UMERIT.FOR
SUBROUTINE UMERIT
!
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
!
!       THIS IS SUBROUTINE UMERIT. THIS IS THE SUBROUTINE WHICH
!       STARTS AN UPDATE MERIT SESSION.
!       THE CMD LEVEL IS DISABLED AND FLAG F27 IS SET TO 2.
!
   IF(SST.EQ.1.OR.SN.EQ.1) THEN
      WRITE(OUTLYNE,*)'"UPDATE MERIT" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   F1=0
   F27=2
   CORMOD=1
   MODEFLAG=.FALSE.
!
   RETURN
END
SUBROUTINE SPLINT(XA,YA,Y2A,N,X,Y)
!     THIS IS A MODIFIED VERSION FROM NUMERICAL RECIPIES
   use DATMAI
   IMPLICIT NONE
   REAL*8 XA,YA,Y2A,X,Y,H,A,B
   INTEGER KLO,KHI,N,K
   DIMENSION XA(N),YA(N),Y2A(N)
   KLO=1
   KHI=N
1  IF (KHI-KLO.GT.1) THEN
      K=(KHI+KLO)/2
      IF(XA(K).GT.X)THEN
         KHI=K
      ELSE
         KLO=K
      ENDIF
      GOTO 1
   ENDIF
   H=XA(KHI)-XA(KLO)
   IF (H.EQ.0.0D0) THEN
      OUTLYNE= 'SERIOUS ERROR IN CALL TO SPLINE INTERPOLATION'
      CALL SHOWIT(1)
      OUTLYNE= 'REPORT THIS IMMEDIATELY'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   A=(XA(KHI)-X)/H
   B=(X-XA(KLO))/H
   Y=A*YA(KLO)+B*YA(KHI)+((A**3-A)*Y2A(KLO)+(B**3-B)*Y2A(KHI))*(H**2)/6.0D0
   RETURN
END
SUBROUTINE SPLINE(X,Y,N,YP1,YPN,Y2)
!     THIS IS A MODIFIED VERSION FROM NUMERICAL RECIPIES
   IMPLICIT NONE
   REAL*8 X,Y,Y2,U,SIG,P,YPN,QN,UN,YP1
   INTEGER NMAX,I,N,K
   PARAMETER (NMAX=250)
   DIMENSION X(N),Y(N),Y2(N),U(NMAX)
   PRINT *, "N is ", N
   PRINT *, "Y(N)) is ", Y(N)
   IF (YP1.GT..99D30) THEN
      Y2(1)=0.0D0
      U(1)=0.0D0
   ELSE
      Y2(1)=-0.5D0
      U(1)=(3.0D0/(X(2)-X(1)))*((Y(2)-Y(1))/(X(2)-X(1))-YP1)
   ENDIF
   DO 11 I=2,N-1
      SIG=(X(I)-X(I-1))/(X(I+1)-X(I-1))
      P=SIG*Y2(I-1)+2.0D0
      Y2(I)=(SIG-1.0D0)/P
      U(I)=(6.0D0*((Y(I+1)-Y(I))/(X(I+1)-X(I))-(Y(I)-Y(I-1))/(X(I)-X(I-1)))/(X(I+1)-X(I-1))-SIG*U(I-1))/P
11 CONTINUE
   IF (YPN.GT..99D30) THEN
      QN=0.0D0
      UN=0.0D0
   ELSE
      QN=0.5D0
      UN=(3.0D0/(X(N)-X(N-1)))*(YPN-(Y(N)-Y(N-1))/(X(N)-X(N-1)))
   ENDIF
   Y2(N)=(UN-QN*U(N-1))/(QN*Y2(N-1)+1.0D0)
   DO 12 K=N-1,1,-1
      Y2(K)=Y2(K)*Y2(K+1)+U(K)
12 CONTINUE
   RETURN
END
! SUB ROBB.FOR
SUBROUTINE ROBB
!
   use DATCFG
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
   INTEGER IROBB,RMAX,I,J,VTYPE,K,ALTYPE,VADD,VCFG,KMIN
!
   CHARACTER AV1*23
!
   INTEGER VCN,ALLOERR
!
   REAL*8 ROBBB,ROBDD,OLDX,VSAVE,OROBFMT ,V1,FMT1,DELOLDX
!
   INTEGER ISURF
!
   REAL*8 NEWDEFVAL
!
   COMMON/DEFVALCOM/NEWDEFVAL
!
   DIMENSION OLDX(:),DELOLDX(:),VSAVE(:)
!
   ALLOCATABLE :: OLDX,DELOLDX,VSAVE
!
   COMMON/CAUX1/V1,AV1
!
   LOGICAL ERR1,ERR2
!
   VCN=VBCNT
   DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
   ALLOCATE(OLDX(VCN),DELOLDX(VCN),VSAVE(VCN),STAT=ALLOERR)
!
!       THIS IS SUBROUTINE ROBB.FOR THIS IS THE SUBROUTINE WHICH
!       HANDLES CMD LEVEL COMMANDS "ROBB"
!
!       "ROBB" EITHER TAKES OPTINAL NW1 AND NW2
   IF(STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"ROBB" PERFORMS CONVERGENCE ACCELERATION'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
   IF(SQ.EQ.1.OR.SST.EQ.1) THEN
      WRITE(OUTLYNE,*)'"ROBB" TAKES NO QUALIFIER OR STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
   IF(S4.EQ.1.OR.S5.EQ.1) THEN
      WRITE(OUTLYNE,*)'"ROBB" TAKES NO NUMERIC WORD #4 OR #5 INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
   IF(DF3.EQ.0.AND.W3.LT.5.0D0) THEN
      WRITE(OUTLYNE,*)'"ROBB" REQUIRES "rmax" TO BE GREATER THAN OR EQUAL TO 5'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
   IF(DF3.EQ.1) W3=100.0D0
   RMAX=INT(W3)
!
   IF(KILOPT) THEN
      OUTLYNE='SOME OPERANDS ARE NOT CALCULABLE'
      CALL SHOWIT(1)
      OUTLYNE='NO ACCELERATION IS POSSIBLE'
      CALL SHOWIT(1)
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
!
   IF(DF1.EQ.1) W1=1.0D0
   IF(DF2.EQ.1) W2=1.1D0
   ROBBB=W1
   ROBDD=W2
!
!       PROCEED WITH ACTION FOR COMMAND
   IF(.NOT.SOLEXT) THEN
      WRITE(OUTLYNE,*)'NO SOLUTION VECTOR EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO ACTION TAKEN'
      CALL SHOWIT(1)
      CALL MACFAL
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
!       PROCEED WITH ACTION FOR COMMAND
   IF(VBCNT.EQ.0) THEN
      WRITE(OUTLYNE,*)'THE VARIABLE SUBFILE IS EMPTY'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO VARIABLE DATA VALUES EXISTS TO RESTORE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO ACTION TAKEN'
      CALL SHOWIT(1)
      CALL MACFAL
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
   IF(OPCNT.EQ.0) THEN
      WRITE(OUTLYNE,*)'THE MERIT SUBFILE IS EMPTY'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO OPERAND DATA VALUES EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO ACTION TAKEN'
      CALL SHOWIT(1)
      CALL MACFAL
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF

!     THERE IS A SOLUTION TO ACCELERATE, DO IT
!
!     SAVE THE CURRENT FMT
   OROBFMT=FMTFMT
!
!     CALCULATE AND STORE THE LAST OLD SOLUTION VECTOR
   DO I=1,VBCNT
      OLDX(I)=VARABL(I,4)-VARABL(I,5)
   END DO
!     NOW START SCALING AND APPLYING THE CHANGE TO THE SOLUTION VECTOR
!     TO THE CURRENT LENS WHICH ALREADY HAS THE EXISTING SOLUTION
!     VECTOR IN IT.
   IROBB=0

30 FORMAT('  I  SCALE FACTOR   CURRENT FMT')
   WRITE(OUTLYNE,30)
   CALL SHOWIT(0)
1  CONTINUE
   IROBB=IROBB+1
   IF(IROBB.GT.RMAX) THEN
      WRITE(OUTLYNE,98) RMAX
      CALL SHOWIT(1)
98    FORMAT('MAXIMUM NUMBER OF "ROBB" CYCLES, ',I5,' ,HAS BEEN REACHED')
      RETURN
   END IF
   ROBBB=ROBBB*ROBDD
   DO I=1,VBCNT
      DELOLDX(I)=(ROBBB*OLDX(I))-OLDX(I)
   END DO
   DO I=1,VBCNT
!     REMEMBER THE CURRENT VARIABLE VALUE BEFORE SCALING
      VSAVE(I)=VARABL(I,4)
!     CALCULATE THE NEW VARIABLE VALUE AFTER SCALING
      VARABL(I,4)=VSAVE(I)+DELOLDX(I)
!
!     BOUNDS CHECKER
      IF(VARABL(I,4).LT.VARABL(I,9)) THEN
         VARABL(I,4)=VARABL(I,9)
         WRITE(OUTLYNE,*)'WARNING: '
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS LOWER BOUNDARY VALUE'
         CALL SHOWIT(1)
      END IF
      IF(VARABL(I,4).GT.VARABL(I,10)) THEN
         VARABL(I,4)=VARABL(I,10)
         WRITE(OUTLYNE,*)'WARNING: '
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS UPPER BOUNDARY VALUE'
         CALL SHOWIT(1)
      END IF
      VARABL(I,6)=VARABL(I,4)-VARABL(I,5)
!
   END DO
!
!     CHANGE THE LENS
!**********************************************************************
!     NOW APPLY THE CHANGE VECTOR TO THE LENS
   DO I=1,VBCNT
!     FIRST, IF THE VARIABLE IS A CONFIG 1 VARIABLE
!     NEXT IF THE VARIABLE IS IN A CONFIG OTHER THAN 1
      IF(VARABL(I,2).EQ.1.0D0) THEN
!     NON-CONFIGS VARIABLE MEANING CONFIG 1
!     THIS IS A LENS LEVEL VARIABLE CHANGE
!     GET THE DATA TYPE NUMBER OF THE VARIABLE
         VTYPE=INT(VARABL(I,1))
!                          CURVATURE
         IF(VTYPE.EQ.2.OR.VTYPE.EQ.1) THEN
!     SURFACE CURVATURE
!     NEW VALUE IS:
            V1=VARABL(I,4)
            call set_surf_curvature(INT(VARABL(I,3)), V1)
!                       CURVATURE DONE
         END IF
         IF(VTYPE.EQ.10.OR.VTYPE.EQ.9) THEN
!     SURFACE TORIC CURVATURE
!     NEW VALUE IS:
            V1=VARABL(I,4)
            call set_surf_toric_curvature(INT(VARABL(I,3)), V1)
!                       TORIC CURVATURE DONE
         END IF
         IF(VTYPE.GE.3.AND.VTYPE.LE.8) THEN
            IF(VTYPE.EQ.3) ALTYPE=3
            IF(VTYPE.EQ.4) ALTYPE=2
            IF(VTYPE.EQ.5) ALTYPE=4
            IF(VTYPE.EQ.6) ALTYPE=5
            IF(VTYPE.EQ.7) ALTYPE=6
            IF(VTYPE.EQ.8) ALTYPE=7
!     NEW VALUE IS:
            V1=VARABL(I,4)
            ALENS(ALTYPE,INT(VARABL(I,3)))=V1
!                       THESE VARIABLES DONE
         END IF
         IF(VTYPE.GE.11.AND.VTYPE.LE.25.OR.VTYPE.EQ.75.OR.VTYPE.GE.124.AND.VTYPE.LE.149) THEN
            IF(VTYPE.EQ.11) ALTYPE=41
            IF(VTYPE.EQ.12) ALTYPE=37
            IF(VTYPE.EQ.13) ALTYPE=38
            IF(VTYPE.EQ.14) ALTYPE=39
            IF(VTYPE.EQ.15) ALTYPE=40
            IF(VTYPE.EQ.16) ALTYPE=118
            IF(VTYPE.EQ.17) ALTYPE=119
            IF(VTYPE.EQ.18) ALTYPE=120
            IF(VTYPE.EQ.19) ALTYPE=114
            IF(VTYPE.EQ.20) ALTYPE=115
            IF(VTYPE.EQ.21) ALTYPE=46
            IF(VTYPE.EQ.22) ALTYPE=47
            IF(VTYPE.EQ.23) ALTYPE=48
            IF(VTYPE.EQ.24) ALTYPE=49
            IF(VTYPE.EQ.25) ALTYPE=50
            IF(VTYPE.EQ.75) ALTYPE=43
            IF(VTYPE.EQ.124) ALTYPE=71
            IF(VTYPE.EQ.125) ALTYPE=72
            IF(VTYPE.EQ.126) ALTYPE=73
            IF(VTYPE.EQ.127) ALTYPE=74
            IF(VTYPE.EQ.128) ALTYPE=75
            IF(VTYPE.EQ.129) ALTYPE=81
            IF(VTYPE.EQ.130) ALTYPE=82
            IF(VTYPE.EQ.131) ALTYPE=83
            IF(VTYPE.EQ.132) ALTYPE=84
            IF(VTYPE.EQ.133) ALTYPE=85
            IF(VTYPE.EQ.134) ALTYPE=116
            IF(VTYPE.EQ.135) ALTYPE=86
            IF(VTYPE.EQ.136) ALTYPE=87
            IF(VTYPE.EQ.137) ALTYPE=78
            IF(VTYPE.EQ.138) ALTYPE=79
            IF(VTYPE.EQ.139) ALTYPE=80
            IF(VTYPE.EQ.140) ALTYPE=89
            IF(VTYPE.EQ.141) ALTYPE=11
            IF(VTYPE.EQ.142) ALTYPE=10
            IF(VTYPE.EQ.143) ALTYPE=90
            IF(VTYPE.EQ.144) ALTYPE=91
            IF(VTYPE.EQ.145) ALTYPE=92
            IF(VTYPE.EQ.146) ALTYPE=93
            IF(VTYPE.EQ.147) ALTYPE=94
            IF(VTYPE.EQ.148) ALTYPE=95
            IF(VTYPE.EQ.149) ALTYPE=98
!     NEW VALUE IS:
            V1=VARABL(I,4)
            ALENS(ALTYPE,INT(VARABL(I,3)))=V1
         END IF
         IF(VTYPE.EQ.150) THEN
!     NEW VALUE IS:
            V1=VARABL(I,4)
            GPREG(INT(VARABL(I,3)))=V1
         END IF
         IF(VTYPE.GE.250.AND.VTYPE.LE.4218) THEN
            ALTYPE=VTYPE-249
!     NEW VALUE IS:
            V1=VARABL(I,4)
!     RESET THE APPRORIATE ARRAY VALUE IN THE DEFORMABLE SURFACE
            ISURF=INT(VARABL(I,3))
            DEFGR1=surf_default_flag(ISURF)
            DEFGR2=surf_mtracei_nx(ISURF)
            DEFGR3=surf_mtracei_ny(ISURF)
            DEFGR4=surf_psfbin_data(ISURF)
            DEFGR5=surf_profit_data(ISURF)
            DEFGR6=0.0D0
            DEFGR7=ALENS(109,ISURF)
            DEFGR8=0.0D0
            ACTNUM=ALTYPE
            NEWDEFVAL=V1
            ERR1=.FALSE.
            ERR2=.FALSE.
            CALL DEFGRIDS(6,ISURF,ERR1,ERR2)
         END IF
         IF(VTYPE.GE.27.AND.VTYPE.LE.74) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
            V1=VARABL(I,4)
            FTFL01((VTYPE-26),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
         END IF
         IF(VTYPE.GE.76.AND.VTYPE.LE.123) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
            V1=VARABL(I,4)
            FTFL01((VTYPE-27),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
         END IF
!
      ELSE
!     CONFIGS VARIABLE
!     VCFG IS THE CONFIG NUMBER
         VCFG=INT(VARABL(I,2))
!     VTYPE IS THE VARIABLE TYPE NUMBER AS USED IN THE VARIABLES ARRAYS
         VTYPE=INT(VARABL(I,1))
!
!     FOR VARIABLE I, APPLY THE SPECIFIED CHANGE TO THE SPECIFIED
!     CONFIG
!
!     THE NEW VARAIBLE VALUE IS JUST
         V1=VARABL(I,4)
!     CONVERT THIS VALUE TO A CHARACTER*23 CHARACTER VARIABLE
         VADD=INT(VARABL(I,14))
         IF(CFADD(VADD,1).EQ.1.AND.V1.NE.0.0D0) V1=1.0D0/V1
         IF(CFADD(VADD,1).EQ.9.AND.V1.NE.0.0D0) V1=1.0D0/V1
         CALL AUXNTA
!
!     THE POSITION IN THE CFADD,CFVAL AND CFCHAR ARRAYS WHERE THIS
!     VARIABLE IS FOUND IS:
!
         IF(CFADD(VADD,1).GE.27.AND.CFADD(VADD,1).LE.74.OR.CFADD(VADD,1).GE.76.AND.CFADD(VADD,1).LE.123 .OR.CFADD(VADD,1).EQ.141) THEN
            CFVAL(VADD,2)=V1
            CFCHAR(VADD,2)=AV1
!     NOW UPDATE THE CONFIG ARRAY
            CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,6):CFADD(VADD,7))=AV1(1:23)
         ELSE
            CFVAL(VADD,1)=V1
            CFCHAR(VADD,1)=AV1
!     NOW UPDATE THE CONFIG ARRAY
            CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,4):CFADD(VADD,5))=AV1(1:23)
         END IF
!     NOW LOOK UP WHERE THIS CHARACTER REPRESENTATION OF THE NEW VALUE
!     SHOULD BE STUFFED INTO THE CONFIG ARRAYS CONFG AND
!     STUFF IT THERE.
!
!     NOW LOOP BACK AND REPEAT FOR THE NEXT VARIABLE.
!     FINISHED WITH A CONFIG VARIABLE
      END IF
!     LOOP TO NEXT VARIABL
   END DO
!     UPDATE THE LENS OR THE PERMANENT LENS WILL BE ******!
   CALL FIXDEFORMFILE
   F6=1
   F1=0
   F22=0
   LNSTYP=2
   CALL LNSEOS
!**********************************************************************
!     EVALUATE OPREANDS AND FMT
   OPCALC_TYPE=3
   CALL OPCALC
   IF(F28.EQ.0) DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
   IF(F28.EQ.0) RETURN
   CALL OPLOAD
   IF(F28.EQ.0) DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
   IF(F28.EQ.0) RETURN
   FMT1=0.0D0
   DO I=1,OPCNT
      IF(OPERND(I,19).EQ.0.0D0) FMT1=FMT1+(OPERND(I,14)**2)
   END DO
!     NOW IS THE NEW FMT LESS THAN THE OLD FMT
   IF(FMT1.LE.OROBFMT) THEN
!     WE IMPROVED THE LENS, LETS TRY IT AGAIN
10    FORMAT(I3,2X,G13.6,2X,G13.6)
      WRITE(OUTLYNE,10) IROBB,ROBBB,FMT1
      CALL SHOWIT(0)
      OROBFMT=FMT1
      GO TO 1
   ELSE
      WRITE(OUTLYNE,10) IROBB,ROBBB,FMT1
      CALL SHOWIT(0)
      WRITE(OUTLYNE,20)
      CALL SHOWIT(0)
20    FORMAT('RESTORING TO THE LAST SOLUTION VECTOR')
!     RESTORE THE LENS TO THE LAST SET OF VARIABLES
   END IF
   DO I=1,VBCNT
!     GO BACK TO THE LAST VARIABLE VALUES
      VARABL(I,4)=VSAVE(I)
!
!     BOUNDS CHECKER
      IF(VARABL(I,4).LT.VARABL(I,9)) THEN
         VARABL(I,4)=VARABL(I,9)
         WRITE(OUTLYNE,*)'WARNING: '
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS LOWER BOUNDARY VALUE'
         CALL SHOWIT(1)
      END IF
      IF(VARABL(I,4).GT.VARABL(I,10)) THEN
         VARABL(I,4)=VARABL(I,10)
         WRITE(OUTLYNE,*)'WARNING: '
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS UPPER BOUNDARY VALUE'
         CALL SHOWIT(1)
      END IF
      VARABL(I,6)=VARABL(I,4)-VARABL(I,5)
!
   END DO
!
!     CHANGE THE LENS (RESTORE IT)
!**********************************************************************
   DO I=1,VBCNT
!     FIRST, IF THE VARIABLE IS A CONFIG 1 VARIABLE
!     NEXT IF THE VARIABLE IS IN A CONFIG OTHER THAN 1
      IF(VARABL(I,2).EQ.1.0D0) THEN
!     NON-CONFIGS VARIABLE MEANING CONFIG 1
!     THIS IS A LENS LEVEL VARIABLE CHANGE
!     GET THE DATA TYPE NUMBER OF THE VARIABLE
         VTYPE=INT(VARABL(I,1))
!                          CURVATURE
         IF(VTYPE.EQ.2.OR.VTYPE.EQ.1) THEN
!     SURFACE CURVATURE
!     NEW VALUE IS:
            V1=VARABL(I,4)
            call set_surf_curvature(INT(VARABL(I,3)), V1)
!                       CURVATURE DONE
         END IF
         IF(VTYPE.EQ.10.OR.VTYPE.EQ.9) THEN
!     SURFACE TORIC CURVATURE
!     NEW VALUE IS:
            V1=VARABL(I,4)
            call set_surf_toric_curvature(INT(VARABL(I,3)), V1)
!                       TORIC CURVATURE DONE
         END IF
         IF(VTYPE.GE.3.AND.VTYPE.LE.8) THEN
            IF(VTYPE.EQ.3) ALTYPE=3
            IF(VTYPE.EQ.4) ALTYPE=2
            IF(VTYPE.EQ.5) ALTYPE=4
            IF(VTYPE.EQ.6) ALTYPE=5
            IF(VTYPE.EQ.7) ALTYPE=6
            IF(VTYPE.EQ.8) ALTYPE=7
!     NEW VALUE IS:
            V1=VARABL(I,4)
            ALENS(ALTYPE,INT(VARABL(I,3)))=V1
!                       THESE VARIABLES DONE
         END IF
         IF(VTYPE.GE.11.AND.VTYPE.LE.25.OR.VTYPE.EQ.75.OR.VTYPE.GE.124.AND.VTYPE.LE.149) THEN
            IF(VTYPE.EQ.11) ALTYPE=41
            IF(VTYPE.EQ.12) ALTYPE=37
            IF(VTYPE.EQ.13) ALTYPE=38
            IF(VTYPE.EQ.14) ALTYPE=39
            IF(VTYPE.EQ.15) ALTYPE=40
            IF(VTYPE.EQ.16) ALTYPE=118
            IF(VTYPE.EQ.17) ALTYPE=119
            IF(VTYPE.EQ.18) ALTYPE=120
            IF(VTYPE.EQ.19) ALTYPE=114
            IF(VTYPE.EQ.20) ALTYPE=115
            IF(VTYPE.EQ.21) ALTYPE=46
            IF(VTYPE.EQ.22) ALTYPE=47
            IF(VTYPE.EQ.23) ALTYPE=48
            IF(VTYPE.EQ.24) ALTYPE=49
            IF(VTYPE.EQ.25) ALTYPE=50
            IF(VTYPE.EQ.75) ALTYPE=43
            IF(VTYPE.EQ.124) ALTYPE=71
            IF(VTYPE.EQ.125) ALTYPE=72
            IF(VTYPE.EQ.126) ALTYPE=73
            IF(VTYPE.EQ.127) ALTYPE=74
            IF(VTYPE.EQ.128) ALTYPE=75
            IF(VTYPE.EQ.129) ALTYPE=81
            IF(VTYPE.EQ.130) ALTYPE=82
            IF(VTYPE.EQ.131) ALTYPE=83
            IF(VTYPE.EQ.132) ALTYPE=84
            IF(VTYPE.EQ.133) ALTYPE=85
            IF(VTYPE.EQ.134) ALTYPE=116
            IF(VTYPE.EQ.135) ALTYPE=86
            IF(VTYPE.EQ.136) ALTYPE=87
            IF(VTYPE.EQ.137) ALTYPE=78
            IF(VTYPE.EQ.138) ALTYPE=79
            IF(VTYPE.EQ.139) ALTYPE=80
            IF(VTYPE.EQ.140) ALTYPE=89
            IF(VTYPE.EQ.141) ALTYPE=11
            IF(VTYPE.EQ.142) ALTYPE=10
            IF(VTYPE.EQ.143) ALTYPE=90
            IF(VTYPE.EQ.144) ALTYPE=91
            IF(VTYPE.EQ.145) ALTYPE=92
            IF(VTYPE.EQ.146) ALTYPE=93
            IF(VTYPE.EQ.147) ALTYPE=94
            IF(VTYPE.EQ.148) ALTYPE=95
            IF(VTYPE.EQ.149) ALTYPE=98
!     NEW VALUE IS:
            V1=VARABL(I,4)
            ALENS(ALTYPE,INT(VARABL(I,3)))=V1
         END IF
         IF(VTYPE.EQ.150) THEN
!     NEW VALUE IS:
            V1=VARABL(I,4)
            GPREG(INT(VARABL(I,3)))=V1
         END IF
         IF(VTYPE.GE.250.AND.VTYPE.LE.4218) THEN
            ALTYPE=VTYPE-249
!     NEW VALUE IS:
            V1=VARABL(I,4)
!     RESET THE APPRORIATE ARRAY VALUE IN THE DEFORMABLE SURFACE
            ISURF=INT(VARABL(I,3))
            DEFGR1=surf_default_flag(ISURF)
            DEFGR2=surf_mtracei_nx(ISURF)
            DEFGR3=surf_mtracei_ny(ISURF)
            DEFGR4=surf_psfbin_data(ISURF)
            DEFGR5=surf_profit_data(ISURF)
            DEFGR6=0.0D0
            DEFGR7=ALENS(109,ISURF)
            DEFGR8=0.0D0
            ACTNUM=ALTYPE
            NEWDEFVAL=V1
            ERR1=.FALSE.
            ERR2=.FALSE.
            CALL DEFGRIDS(6,ISURF,ERR1,ERR2)
         END IF
         IF(VTYPE.GE.27.AND.VTYPE.LE.74) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
            V1=VARABL(I,4)
            FTFL01((VTYPE-26),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
         END IF
         IF(VTYPE.GE.76.AND.VTYPE.LE.123) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
            V1=VARABL(I,4)
            FTFL01((VTYPE-27),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
         END IF
!
      ELSE
!     CONFIGS VARIABLE
!     VCFG IS THE CONFIG NUMBER
         VCFG=INT(VARABL(I,2))
!     VTYPE IS THE VARIABLE TYPE NUMBER AS USED IN THE VARIABLES ARRAYS
         VTYPE=INT(VARABL(I,1))
!
!     FOR VARIABLE I, APPLY THE SPECIFIED CHANGE TO THE SPECIFIED
!     CONFIG
!
!     THE NEW VARAIBLE VALUE IS JUST
         V1=VARABL(I,4)
!     CONVERT THIS VALUE TO A CHARACTER*23 CHARACTER VARIABLE
         VADD=INT(VARABL(I,14))
         IF(CFADD(VADD,1).EQ.1.AND.V1.NE.0.0D0) V1=1.0D0/V1
         IF(CFADD(VADD,1).EQ.9.AND.V1.NE.0.0D0) V1=1.0D0/V1
         CALL AUXNTA
!
!     THE POSITION IN THE CFADD,CFVAL AND CFCHAR ARRAYS WHERE THIS
!     VARIABLE IS FOUND IS:
!
         IF(CFADD(VADD,1).GE.27.AND.CFADD(VADD,1).LE.74.OR.CFADD(VADD,1).GE.76.AND.CFADD(VADD,1).LE.123 .OR.CFADD(VADD,1).EQ.141) THEN
            CFVAL(VADD,2)=V1
            CFCHAR(VADD,2)=AV1
!     NOW UPDATE THE CONFIG ARRAY
            CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,6):CFADD(VADD,7))=AV1(1:23)
         ELSE
            CFVAL(VADD,1)=V1
            CFCHAR(VADD,1)=AV1
!     NOW UPDATE THE CONFIG ARRAY
            CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,4):CFADD(VADD,5))=AV1(1:23)
         END IF
!     NOW LOOK UP WHERE THIS CHARACTER REPRESENTATION OF THE NEW VALUE
!     SHOULD BE STUFFED INTO THE CONFIG ARRAYS CONFG AND
!     STUFF IT THERE.
!
!     NOW LOOP BACK AND REPEAT FOR THE NEXT VARIABLE.
!     FINISHED WITH A CONFIG VARIABLE
      END IF
!     LOOP TO NEXT VARIABL
   END DO
!     UPDATE THE LENS OR THE PERMANENT LENS WILL BE ******!
   CALL FIXDEFORMFILE
   F6=1
   F1=0
   F22=0
   LNSTYP=2
   CALL LNSEOS
!
!     RE-EVALUATE THE OPERANDS AND DISPLAY
!     THE NEW FIGURE OF MERIT, THE OLD FIGURE OF MERIT  AND ITS CHANGE
   SAVE_KDP(4)=SAVEINPT(4)
   F28=1
   MSG=.FALSE.
   OPTMES=.FALSE.
   WC='FMT'
   WQ='        '
   SQ=0
   SN=0
   SST=0
   WS=' '
   DF1=1
   S1=0
   S2=0
   S3=0
   S4=0
   S5=0
   DF2=1
   DF3=1
   DF4=1
   DF5=1
   STI=0
   CALL FMT2
   REST_KDP(4)=RESTINPT(4)
   DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
   RETURN
!       ALL DONE
END
! SUB RESTMIN.FOR
SUBROUTINE RESTMIN
!
   use DATCFG
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
   INTEGER IROBB,RMAX,I,J,VTYPE,K,ALTYPE,VADD,VCFG,KMIN
!
   CHARACTER AV1*23
!
   INTEGER VCN,ALLOERR
!
   REAL*8 ROBBB,ROBDD,OLDX,VSAVE,OROBFMT ,V1,FMT1,DELOLDX
!
   INTEGER ISURF
!
   REAL*8 NEWDEFVAL
!
   COMMON/DEFVALCOM/NEWDEFVAL
!
   DIMENSION OLDX(:),DELOLDX(:),VSAVE(:)
!
   ALLOCATABLE :: OLDX,DELOLDX,VSAVE
!
   COMMON/CAUX1/V1,AV1
!
   LOGICAL ERR1,ERR2
!
   VCN=VBCNT
   DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
   ALLOCATE(OLDX(VCN),DELOLDX(VCN),VSAVE(VCN),STAT=ALLOERR)
!
!
   IF(STI.EQ.1) THEN
      WRITE(OUTLYNE,*)'"RESTORE MIN LOOKS ALONG THE CURRENT SOLUTION VECTOR'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'FOR A MINIMUM SOLUTION'
      CALL SHOWIT(1)
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
   IF(SN.EQ.1.OR.SST.EQ.1) THEN
      WRITE(OUTLYNE,*)'"RESTORE MIN TAKES NO NUMERIC OR STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
   RMAX=500.0D0
!
   IF(KILOPT) THEN
      OUTLYNE='SOME OPERANDS ARE NOT CALCULABLE'
      CALL SHOWIT(1)
      OUTLYNE='NO ACTION IS POSSIBLE'
      CALL SHOWIT(1)
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
!
   ROBBB=1.0D0
   ROBDD=1.1D0
!
!       PROCEED WITH ACTION FOR COMMAND
   IF(.NOT.SOLEXT) THEN
      WRITE(OUTLYNE,*)'NO SOLUTION VECTOR EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO ACTION TAKEN'
      CALL SHOWIT(1)
      CALL MACFAL
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
!       PROCEED WITH ACTION FOR COMMAND
   IF(VBCNT.EQ.0) THEN
      WRITE(OUTLYNE,*)'THE VARIABLE SUBFILE IS EMPTY'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO VARIABLE DATA VALUES EXISTS TO RESTORE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO ACTION TAKEN'
      CALL SHOWIT(1)
      CALL MACFAL
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF
   IF(OPCNT.EQ.0) THEN
      WRITE(OUTLYNE,*)'THE MERIT SUBFILE IS EMPTY'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO OPERAND DATA VALUES EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO ACTION TAKEN'
      CALL SHOWIT(1)
      CALL MACFAL
      DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
      RETURN
   END IF

!     THERE IS A SOLUTION TO ACCELERATE, DO IT
!
!     SAVE THE CURRENT FMT
   OROBFMT=FMTFMT
!
!     CALCULATE AND STORE THE LAST OLD SOLUTION VECTOR
   DO I=1,VBCNT
      OLDX(I)=VARABL(I,4)-VARABL(I,5)
   END DO
!     NOW START SCALING AND APPLYING THE CHANGE TO THE SOLUTION VECTOR
!     TO THE CURRENT LENS WHICH ALREADY HAS THE EXISTING SOLUTION
!     VECTOR IN IT.
   IROBB=0

1  CONTINUE
   IROBB=IROBB+1
   IF(IROBB.GT.RMAX) THEN
      WRITE(OUTLYNE,98) RMAX
      CALL SHOWIT(1)
98    FORMAT('MAXIMUM NUMBER CYCLES, ',I5,' ,HAS BEEN REACHED')
      WRITE(OUTLYNE,99)
      CALL SHOWIT(1)
99    FORMAT('ISSUE ANOTHER "RESTORE MIN"')
      RETURN
   END IF
   ROBBB=ROBBB*ROBDD
   DO I=1,VBCNT
      DELOLDX(I)=(ROBBB*OLDX(I))-OLDX(I)
   END DO
   DO I=1,VBCNT
!     REMEMBER THE CURRENT VARIABLE VALUE BEFORE SCALING
      VSAVE(I)=VARABL(I,4)
!     CALCULATE THE NEW VARIABLE VALUE AFTER SCALING
      VARABL(I,4)=VSAVE(I)+DELOLDX(I)
!
!     BOUNDS CHECKER
      IF(VARABL(I,4).LT.VARABL(I,9)) THEN
         VARABL(I,4)=VARABL(I,9)
         WRITE(OUTLYNE,*)'WARNING: '
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS LOWER BOUNDARY VALUE'
         CALL SHOWIT(1)
      END IF
      IF(VARABL(I,4).GT.VARABL(I,10)) THEN
         VARABL(I,4)=VARABL(I,10)
         WRITE(OUTLYNE,*)'WARNING: '
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS UPPER BOUNDARY VALUE'
         CALL SHOWIT(1)
      END IF
      VARABL(I,6)=VARABL(I,4)-VARABL(I,5)
!
   END DO
!
!     CHANGE THE LENS
!**********************************************************************
!     NOW APPLY THE CHANGE VECTOR TO THE LENS
   DO I=1,VBCNT
!     FIRST, IF THE VARIABLE IS A CONFIG 1 VARIABLE
!     NEXT IF THE VARIABLE IS IN A CONFIG OTHER THAN 1
      IF(VARABL(I,2).EQ.1.0D0) THEN
!     NON-CONFIGS VARIABLE MEANING CONFIG 1
!     THIS IS A LENS LEVEL VARIABLE CHANGE
!     GET THE DATA TYPE NUMBER OF THE VARIABLE
         VTYPE=INT(VARABL(I,1))
!                          CURVATURE
         IF(VTYPE.EQ.2.OR.VTYPE.EQ.1) THEN
!     SURFACE CURVATURE
!     NEW VALUE IS:
            V1=VARABL(I,4)
            call set_surf_curvature(INT(VARABL(I,3)), V1)
!                       CURVATURE DONE
         END IF
         IF(VTYPE.EQ.10.OR.VTYPE.EQ.9) THEN
!     SURFACE TORIC CURVATURE
!     NEW VALUE IS:
            V1=VARABL(I,4)
            call set_surf_toric_curvature(INT(VARABL(I,3)), V1)
!                       TORIC CURVATURE DONE
         END IF
         IF(VTYPE.GE.3.AND.VTYPE.LE.8) THEN
            IF(VTYPE.EQ.3) ALTYPE=3
            IF(VTYPE.EQ.4) ALTYPE=2
            IF(VTYPE.EQ.5) ALTYPE=4
            IF(VTYPE.EQ.6) ALTYPE=5
            IF(VTYPE.EQ.7) ALTYPE=6
            IF(VTYPE.EQ.8) ALTYPE=7
!     NEW VALUE IS:
            V1=VARABL(I,4)
            ALENS(ALTYPE,INT(VARABL(I,3)))=V1
!                       THESE VARIABLES DONE
         END IF
         IF(VTYPE.GE.11.AND.VTYPE.LE.25.OR.VTYPE.EQ.75.OR.VTYPE.GE.124.AND.VTYPE.LE.149) THEN
            IF(VTYPE.EQ.11) ALTYPE=41
            IF(VTYPE.EQ.12) ALTYPE=37
            IF(VTYPE.EQ.13) ALTYPE=38
            IF(VTYPE.EQ.14) ALTYPE=39
            IF(VTYPE.EQ.15) ALTYPE=40
            IF(VTYPE.EQ.16) ALTYPE=118
            IF(VTYPE.EQ.17) ALTYPE=119
            IF(VTYPE.EQ.18) ALTYPE=120
            IF(VTYPE.EQ.19) ALTYPE=114
            IF(VTYPE.EQ.20) ALTYPE=115
            IF(VTYPE.EQ.21) ALTYPE=46
            IF(VTYPE.EQ.22) ALTYPE=47
            IF(VTYPE.EQ.23) ALTYPE=48
            IF(VTYPE.EQ.24) ALTYPE=49
            IF(VTYPE.EQ.25) ALTYPE=50
            IF(VTYPE.EQ.75) ALTYPE=43
            IF(VTYPE.EQ.124) ALTYPE=71
            IF(VTYPE.EQ.125) ALTYPE=72
            IF(VTYPE.EQ.126) ALTYPE=73
            IF(VTYPE.EQ.127) ALTYPE=74
            IF(VTYPE.EQ.128) ALTYPE=75
            IF(VTYPE.EQ.129) ALTYPE=81
            IF(VTYPE.EQ.130) ALTYPE=82
            IF(VTYPE.EQ.131) ALTYPE=83
            IF(VTYPE.EQ.132) ALTYPE=84
            IF(VTYPE.EQ.133) ALTYPE=85
            IF(VTYPE.EQ.134) ALTYPE=116
            IF(VTYPE.EQ.135) ALTYPE=86
            IF(VTYPE.EQ.136) ALTYPE=87
            IF(VTYPE.EQ.137) ALTYPE=78
            IF(VTYPE.EQ.138) ALTYPE=79
            IF(VTYPE.EQ.139) ALTYPE=80
            IF(VTYPE.EQ.140) ALTYPE=89
            IF(VTYPE.EQ.141) ALTYPE=11
            IF(VTYPE.EQ.142) ALTYPE=10
            IF(VTYPE.EQ.143) ALTYPE=90
            IF(VTYPE.EQ.144) ALTYPE=91
            IF(VTYPE.EQ.145) ALTYPE=92
            IF(VTYPE.EQ.146) ALTYPE=93
            IF(VTYPE.EQ.147) ALTYPE=94
            IF(VTYPE.EQ.148) ALTYPE=95
            IF(VTYPE.EQ.149) ALTYPE=98
!     NEW VALUE IS:
            V1=VARABL(I,4)
            ALENS(ALTYPE,INT(VARABL(I,3)))=V1
         END IF
         IF(VTYPE.EQ.150) THEN
!     NEW VALUE IS:
            V1=VARABL(I,4)
            GPREG(INT(VARABL(I,3)))=V1
         END IF
         IF(VTYPE.GE.250.AND.VTYPE.LE.4218) THEN
            ALTYPE=VTYPE-249
!     NEW VALUE IS:
            V1=VARABL(I,4)
!     RESET THE APPRORIATE ARRAY VALUE IN THE DEFORMABLE SURFACE
            ISURF=INT(VARABL(I,3))
            DEFGR1=surf_default_flag(ISURF)
            DEFGR2=surf_mtracei_nx(ISURF)
            DEFGR3=surf_mtracei_ny(ISURF)
            DEFGR4=surf_psfbin_data(ISURF)
            DEFGR5=surf_profit_data(ISURF)
            DEFGR6=0.0D0
            DEFGR7=ALENS(109,ISURF)
            DEFGR8=0.0D0
            ACTNUM=ALTYPE
            NEWDEFVAL=V1
            ERR1=.FALSE.
            ERR2=.FALSE.
            CALL DEFGRIDS(6,ISURF,ERR1,ERR2)
         END IF
         IF(VTYPE.GE.27.AND.VTYPE.LE.74) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
            V1=VARABL(I,4)
            FTFL01((VTYPE-26),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
         END IF
         IF(VTYPE.GE.76.AND.VTYPE.LE.123) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
            V1=VARABL(I,4)
            FTFL01((VTYPE-27),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
         END IF
!
      ELSE
!     CONFIGS VARIABLE
!     VCFG IS THE CONFIG NUMBER
         VCFG=INT(VARABL(I,2))
!     VTYPE IS THE VARIABLE TYPE NUMBER AS USED IN THE VARIABLES ARRAYS
         VTYPE=INT(VARABL(I,1))
!
!     FOR VARIABLE I, APPLY THE SPECIFIED CHANGE TO THE SPECIFIED
!     CONFIG
!
!     THE NEW VARAIBLE VALUE IS JUST
         V1=VARABL(I,4)
!     CONVERT THIS VALUE TO A CHARACTER*23 CHARACTER VARIABLE
         VADD=INT(VARABL(I,14))
         IF(CFADD(VADD,1).EQ.1.AND.V1.NE.0.0D0) V1=1.0D0/V1
         IF(CFADD(VADD,1).EQ.9.AND.V1.NE.0.0D0) V1=1.0D0/V1
         CALL AUXNTA
!
!     THE POSITION IN THE CFADD,CFVAL AND CFCHAR ARRAYS WHERE THIS
!     VARIABLE IS FOUND IS:
!
         IF(CFADD(VADD,1).GE.27.AND.CFADD(VADD,1).LE.74.OR.CFADD(VADD,1).GE.76.AND.CFADD(VADD,1).LE.123 .OR.CFADD(VADD,1).EQ.141) THEN
            CFVAL(VADD,2)=V1
            CFCHAR(VADD,2)=AV1
!     NOW UPDATE THE CONFIG ARRAY
            CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,6):CFADD(VADD,7))=AV1(1:23)
         ELSE
            CFVAL(VADD,1)=V1
            CFCHAR(VADD,1)=AV1
!     NOW UPDATE THE CONFIG ARRAY
            CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,4):CFADD(VADD,5))=AV1(1:23)
         END IF
!     NOW LOOK UP WHERE THIS CHARACTER REPRESENTATION OF THE NEW VALUE
!     SHOULD BE STUFFED INTO THE CONFIG ARRAYS CONFG AND
!     STUFF IT THERE.
!
!     NOW LOOP BACK AND REPEAT FOR THE NEXT VARIABLE.
!     FINISHED WITH A CONFIG VARIABLE
      END IF
!     LOOP TO NEXT VARIABL
   END DO
!     UPDATE THE LENS OR THE PERMANENT LENS WILL BE ******!
   CALL FIXDEFORMFILE
   F6=1
   F1=0
   F22=0
   LNSTYP=2
   CALL LNSEOS
!**********************************************************************
!     EVALUATE OPREANDS AND FMT
   OPCALC_TYPE=3
   CALL OPCALC
   IF(F28.EQ.0) DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
   IF(F28.EQ.0) RETURN
   CALL OPLOAD
   IF(F28.EQ.0) DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
   IF(F28.EQ.0) RETURN
   FMT1=0.0D0
   DO I=1,OPCNT
      IF(OPERND(I,19).EQ.0.0D0) FMT1=FMT1+(OPERND(I,14)**2)
   END DO
!     NOW IS THE NEW FMT LESS THAN THE OLD FMT
   IF(FMT1.LE.OROBFMT) THEN
!     WE IMPROVED THE LENS, LETS TRY IT AGAIN
      OROBFMT=FMT1
      GO TO 1
   ELSE
!     RESTORE THE LENS TO THE LAST SET OF VARIABLES
   END IF
   DO I=1,VBCNT
!     GO BACK TO THE LAST VARIABLE VALUES
      VARABL(I,4)=VSAVE(I)
!
!     BOUNDS CHECKER
      IF(VARABL(I,4).LT.VARABL(I,9)) THEN
         VARABL(I,4)=VARABL(I,9)
         WRITE(OUTLYNE,*)'WARNING: '
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS LOWER BOUNDARY VALUE'
         CALL SHOWIT(1)
      END IF
      IF(VARABL(I,4).GT.VARABL(I,10)) THEN
         VARABL(I,4)=VARABL(I,10)
         WRITE(OUTLYNE,*)'WARNING: '
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS UPPER BOUNDARY VALUE'
         CALL SHOWIT(1)
      END IF
      VARABL(I,6)=VARABL(I,4)-VARABL(I,5)
!
   END DO
!
!     CHANGE THE LENS (RESTORE IT)
!**********************************************************************
   DO I=1,VBCNT
!     FIRST, IF THE VARIABLE IS A CONFIG 1 VARIABLE
!     NEXT IF THE VARIABLE IS IN A CONFIG OTHER THAN 1
      IF(VARABL(I,2).EQ.1.0D0) THEN
!     NON-CONFIGS VARIABLE MEANING CONFIG 1
!     THIS IS A LENS LEVEL VARIABLE CHANGE
!     GET THE DATA TYPE NUMBER OF THE VARIABLE
         VTYPE=INT(VARABL(I,1))
!                          CURVATURE
         IF(VTYPE.EQ.2.OR.VTYPE.EQ.1) THEN
!     SURFACE CURVATURE
!     NEW VALUE IS:
            V1=VARABL(I,4)
            call set_surf_curvature(INT(VARABL(I,3)), V1)
!                       CURVATURE DONE
         END IF
         IF(VTYPE.EQ.10.OR.VTYPE.EQ.9) THEN
!     SURFACE TORIC CURVATURE
!     NEW VALUE IS:
            V1=VARABL(I,4)
            call set_surf_toric_curvature(INT(VARABL(I,3)), V1)
!                       TORIC CURVATURE DONE
         END IF
         IF(VTYPE.GE.3.AND.VTYPE.LE.8) THEN
            IF(VTYPE.EQ.3) ALTYPE=3
            IF(VTYPE.EQ.4) ALTYPE=2
            IF(VTYPE.EQ.5) ALTYPE=4
            IF(VTYPE.EQ.6) ALTYPE=5
            IF(VTYPE.EQ.7) ALTYPE=6
            IF(VTYPE.EQ.8) ALTYPE=7
!     NEW VALUE IS:
            V1=VARABL(I,4)
            ALENS(ALTYPE,INT(VARABL(I,3)))=V1
!                       THESE VARIABLES DONE
         END IF
         IF(VTYPE.GE.11.AND.VTYPE.LE.25.OR.VTYPE.EQ.75.OR.VTYPE.GE.124.AND.VTYPE.LE.149) THEN
            IF(VTYPE.EQ.11) ALTYPE=41
            IF(VTYPE.EQ.12) ALTYPE=37
            IF(VTYPE.EQ.13) ALTYPE=38
            IF(VTYPE.EQ.14) ALTYPE=39
            IF(VTYPE.EQ.15) ALTYPE=40
            IF(VTYPE.EQ.16) ALTYPE=118
            IF(VTYPE.EQ.17) ALTYPE=119
            IF(VTYPE.EQ.18) ALTYPE=120
            IF(VTYPE.EQ.19) ALTYPE=114
            IF(VTYPE.EQ.20) ALTYPE=115
            IF(VTYPE.EQ.21) ALTYPE=46
            IF(VTYPE.EQ.22) ALTYPE=47
            IF(VTYPE.EQ.23) ALTYPE=48
            IF(VTYPE.EQ.24) ALTYPE=49
            IF(VTYPE.EQ.25) ALTYPE=50
            IF(VTYPE.EQ.75) ALTYPE=43
            IF(VTYPE.EQ.124) ALTYPE=71
            IF(VTYPE.EQ.125) ALTYPE=72
            IF(VTYPE.EQ.126) ALTYPE=73
            IF(VTYPE.EQ.127) ALTYPE=74
            IF(VTYPE.EQ.128) ALTYPE=75
            IF(VTYPE.EQ.129) ALTYPE=81
            IF(VTYPE.EQ.130) ALTYPE=82
            IF(VTYPE.EQ.131) ALTYPE=83
            IF(VTYPE.EQ.132) ALTYPE=84
            IF(VTYPE.EQ.133) ALTYPE=85
            IF(VTYPE.EQ.134) ALTYPE=116
            IF(VTYPE.EQ.135) ALTYPE=86
            IF(VTYPE.EQ.136) ALTYPE=87
            IF(VTYPE.EQ.137) ALTYPE=78
            IF(VTYPE.EQ.138) ALTYPE=79
            IF(VTYPE.EQ.139) ALTYPE=80
            IF(VTYPE.EQ.140) ALTYPE=89
            IF(VTYPE.EQ.141) ALTYPE=11
            IF(VTYPE.EQ.142) ALTYPE=10
            IF(VTYPE.EQ.143) ALTYPE=90
            IF(VTYPE.EQ.144) ALTYPE=91
            IF(VTYPE.EQ.145) ALTYPE=92
            IF(VTYPE.EQ.146) ALTYPE=93
            IF(VTYPE.EQ.147) ALTYPE=94
            IF(VTYPE.EQ.148) ALTYPE=95
            IF(VTYPE.EQ.149) ALTYPE=98
!     NEW VALUE IS:
            V1=VARABL(I,4)
            ALENS(ALTYPE,INT(VARABL(I,3)))=V1
         END IF
         IF(VTYPE.EQ.150) THEN
!     NEW VALUE IS:
            V1=VARABL(I,4)
            GPREG(INT(VARABL(I,3)))=V1
         END IF
         IF(VTYPE.GE.250.AND.VTYPE.LE.4218) THEN
            ALTYPE=VTYPE-249
!     NEW VALUE IS:
            V1=VARABL(I,4)
!     RESET THE APPRORIATE ARRAY VALUE IN THE DEFORMABLE SURFACE
            ISURF=INT(VARABL(I,3))
            DEFGR1=surf_default_flag(ISURF)
            DEFGR2=surf_mtracei_nx(ISURF)
            DEFGR3=surf_mtracei_ny(ISURF)
            DEFGR4=surf_psfbin_data(ISURF)
            DEFGR5=surf_profit_data(ISURF)
            DEFGR6=0.0D0
            DEFGR7=ALENS(109,ISURF)
            DEFGR8=0.0D0
            ACTNUM=ALTYPE
            NEWDEFVAL=V1
            ERR1=.FALSE.
            ERR2=.FALSE.
            CALL DEFGRIDS(6,ISURF,ERR1,ERR2)
         END IF
         IF(VTYPE.GE.27.AND.VTYPE.LE.74) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
            V1=VARABL(I,4)
            FTFL01((VTYPE-26),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
         END IF
         IF(VTYPE.GE.76.AND.VTYPE.LE.123) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
            V1=VARABL(I,4)
            FTFL01((VTYPE-27),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
         END IF
!
      ELSE
!     CONFIGS VARIABLE
!     VCFG IS THE CONFIG NUMBER
         VCFG=INT(VARABL(I,2))
!     VTYPE IS THE VARIABLE TYPE NUMBER AS USED IN THE VARIABLES ARRAYS
         VTYPE=INT(VARABL(I,1))
!
!     FOR VARIABLE I, APPLY THE SPECIFIED CHANGE TO THE SPECIFIED
!     CONFIG
!
!     THE NEW VARAIBLE VALUE IS JUST
         V1=VARABL(I,4)
!     CONVERT THIS VALUE TO A CHARACTER*23 CHARACTER VARIABLE
         VADD=INT(VARABL(I,14))
         IF(CFADD(VADD,1).EQ.1.AND.V1.NE.0.0D0) V1=1.0D0/V1
         IF(CFADD(VADD,1).EQ.9.AND.V1.NE.0.0D0) V1=1.0D0/V1
         CALL AUXNTA
!
!     THE POSITION IN THE CFADD,CFVAL AND CFCHAR ARRAYS WHERE THIS
!     VARIABLE IS FOUND IS:
!
         IF(CFADD(VADD,1).GE.27.AND.CFADD(VADD,1).LE.74.OR.CFADD(VADD,1).GE.76.AND.CFADD(VADD,1).LE.123 .OR.CFADD(VADD,1).EQ.141) THEN
            CFVAL(VADD,2)=V1
            CFCHAR(VADD,2)=AV1
!     NOW UPDATE THE CONFIG ARRAY
            CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,6):CFADD(VADD,7))=AV1(1:23)
         ELSE
            CFVAL(VADD,1)=V1
            CFCHAR(VADD,1)=AV1
!     NOW UPDATE THE CONFIG ARRAY
            CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,4):CFADD(VADD,5))=AV1(1:23)
         END IF
!     NOW LOOK UP WHERE THIS CHARACTER REPRESENTATION OF THE NEW VALUE
!     SHOULD BE STUFFED INTO THE CONFIG ARRAYS CONFG AND
!     STUFF IT THERE.
!
!     NOW LOOP BACK AND REPEAT FOR THE NEXT VARIABLE.
!     FINISHED WITH A CONFIG VARIABLE
      END IF
!     LOOP TO NEXT VARIABL
   END DO
!     UPDATE THE LENS OR THE PERMANENT LENS WILL BE ******!
   CALL FIXDEFORMFILE
   F6=1
   F1=0
   F22=0
   LNSTYP=2
   CALL LNSEOS
!
!     RE-EVALUATE THE OPERANDS AND DISPLAY
!     THE NEW FIGURE OF MERIT, THE OLD FIGURE OF MERIT  AND ITS CHANGE
   SAVE_KDP(4)=SAVEINPT(4)
   F28=1
   MSG=.FALSE.
   OPTMES=.FALSE.
   WC='FMT'
   WQ='        '
   SQ=0
   SN=0
   SST=0
   WS=' '
   DF1=1
   S1=0
   S2=0
   S3=0
   S4=0
   S5=0
   DF2=1
   DF3=1
   DF4=1
   DF5=1
   STI=0
   CALL FMT2
   REST_KDP(4)=RESTINPT(4)
   DEALLOCATE(OLDX,DELOLDX,VSAVE,STAT=ALLOERR)
   RETURN
!       ALL DONE
END
! SUB SOLVIT.FOR
SUBROUTINE SOLVIT(IID,JJD,MDERIV,SILENT)
   use type_utils
!
   use DATCFG
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
   CHARACTER OOLDWQ*8
!
   LOGICAL ITDER,SILENT
!
   INTEGER SSN,SM,NP2,MP,N,J,I,L,M,VTYPE,ALTYPE,VADD,VCFG ,VN1,MAXCNT,IV1,VN,ALLOERR,IID,JJD, II
!
   INTEGER ISURF
!
   REAL*8 NEWDEFVAL,PFACSCL
!
   COMMON/DEFVALCOM/NEWDEFVAL
!
   REAL*8 X(1:100000),WT,V1,MAX,VTEMP,OLDCUR,NEWCUR
!
   DIMENSION WT(:)
!
   ALLOCATABLE :: WT
!
   LOGICAL LVAL
!
   CHARACTER AV1*23

   COMMON/SVD1/SM,SSN,MP,NP2
!
   COMMON/SVD2/X
!
   COMMON/CAUX1/V1,AV1
!
   REAL*8 MDERIV
!
   DIMENSION MDERIV(1:IID,1:JJD)
!
   LOGICAL ERR1,ERR2
!
!
   REAL*8 W,V,BTB,BTG,DIAGSUM,WMAX,WMIN
   DIMENSION W(:),V(:,:),BTB(:,:),BTG(:)
   ALLOCATABLE :: W,V,BTB,BTG
   VN=IID
   VN1=IID
   DEALLOCATE(WT,W,V,BTB,BTG,STAT=ALLOERR)
   ALLOCATE (W(VN),V(VN,VN),WT(VN1),BTB(VN1,VN1),BTG(VN1),STAT=ALLOERR)
   W(1:VN)=0.0D0
   WT(1:VN)=0.0D0
   BTG(1:VN)=0.0D0
   V(1:VN,1:VN)=0.0D0
   BTB(1:VN,1:VN)=0.0D0
   OOLDWQ='        '
   ITDER=.FALSE.
   !call LogTermDebug("Starting SOLVIT")
   ! Hack because it seems damping is off.
   DMP = 6
!
   IF(WQ.NE.'D'.AND.WQ.NE.'DIR') THEN
!
!                JUST ITER OR ITER,1
!       THIS IS SUBROUTINE SOLVIT. THIS IS THE SUBROUTINE WHICH
!       HANDLES THE SOLUTION TO THE DAMPED LEAST SQUARES PROBLEM.
!     FORM (BTB+KC)
!     FIRST JUST BTB
!     THIS IS THE MATRIX PRODUCT OF THE TRANSPOSE OF THE DERIV MATRIX
!     TIMES THE DERIV MATRIX ITSELF
!     L IS THE FIRST INDEX OF BTB AND M IS THE SECOND
!     BTB IS SQUARE WITH DIMENSION VBCNT
!
      IF(VBCNT.GE.OPCNT) MAXCNT=VBCNT
      IF(VBCNT.LT.OPCNT) MAXCNT=OPCNT
!
!       ZERO OUT TOO SMALL DERIVATIVES
!
      DO I=1,MAXCNT
         DO M=1,MAXCNT
            IF(DABS(MDERIV(I,M)).LT.ONTOL) MDERIV(I,M)=0.0D0
         END DO
      END DO
!
      DO L=1,MAXCNT
         DO M=1,MAXCNT
            DO I=1,MAXCNT
               BTB(L,M)=BTB(L,M)+(MDERIV(I,L)*MDERIV(I,M))
            END DO
         END DO
      END DO
!     NOW KC IS A DIAGONAL TERM ADDED TO THE DIAGONAL ELEMENTS OF
!     BTB
!     NOTE IF THE VARIABLE WEIGHTS ARE ALL 1.0D0 (DEFAULT)
!     KC BECOMES KI, THE P FACTOR TIMES THE IDENTITY MATRIX.
      DO I=1,VBCNT
         IF(VARABL(I,7).NE.0.0D0) WT(I)=1.0D0/VARABL(I,7)
         IF(VARABL(I,7).EQ.0.0D0) WT(I)=0.0D0
      END DO
      IF(DMP.EQ.6) THEN
         DIAGSUM=0.0D0
         DO I=1,MAXCNT
            DIAGSUM=DIAGSUM+DABS(BTB(I,I))
         END DO
         IF(DIAGSUM.EQ.0.0D0) THEN
            WRITE(OUTLYNE,*) 'THE DIAGONAL OF BTB IS ZERO'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*) 'DAMPING WILL HAVE NO EFFECT'
            CALL SHOWIT(1)
         END IF
      END IF

      !call LogTermDebug("PFAC is "//real2str(PFAC))
      DO I=1,MAXCNT
         IF(DMP.EQ.6) then

            !call LogTermDebug("**************************")
            !I believe there is a bug here in the use of the damping factor
            !It should not be multiplied by the derivative transpose *
            !derivative, it should be added to it
            !Eg see Handbook of Optical Systems, VOl 3 Section 32.4.4
            !While I am at it I got rid of the factor of 1000 to make things
            !A bit cleßaner (time will tell whether I regret it)
            !BTB(I,I)=BTB(I,I)*(1.0D0+(1000.0D0*PFAC*WT(I)))
            BTB(I,I)=BTB(I,I)+PFAC*WT(I)
            !call LogTermDebug("**************************")
         end if
      END DO
!     NOW FORM BTG
      DO L=1,VBCNT
         DO I=1,OPCNT
            BTG(L)=BTG(L)+(MDERIV(I,L)*(-OPERND(I,14)))
         END DO
      END DO
!
!     NOW SOLVE THE PROBLEM WITH SVD AND THEN APPLY THE SOLUTION TO
!     THE LENS
!
      MP=MAXCNT
      NP2=MAXCNT
      N=MAXCNT
      M=MAXCNT
!       DO SINGULAR VALUE DECOMPOSITION
      SM=M
      SSN=N

      CALL SVDCMPA(W,V,VN,VN1,BTB,BTG)
      M=SM
      N=SSN
      WMAX=-1.0D300
      DO J=1,N
         IF(W(J).GT.WMAX) WMAX=W(J)
      END DO
      WMIN=WMAX*SINGTOL
      DO J=1,N
         IF(W(J).LT.WMIN) W(J)=0.0D0
      END DO
!
!       SOLVE LINEAR EQUATION
!
      SM=M
      SSN=N
      ! THis method is updating the solution vector
      ! Original numerical recipes code has X as a return value
      ! Not sure why that wasn't done here
      ! THis is supposed to sove A x = B
      ! A is solution of SVD (why W is used here)
      ! BTG = B
      CALL SVBKSBA(W,V,VN,VN1,BTB,BTG)
      M=SM
      N=SSN

      !call LogTermDebug("about tu update variables in SOLVIT!")
      !call LogTermDebug("VBCNT IS "//int2str(VBCNT))
      !call LogTermDebug("VAR 1 is "//real2str(VARABL(1,4)))
      !call LogTermDebug("X(I) is "//real2str(X(1)))
!
!
!     NOW APPLY THE SOLUTION VECTOR X(I) TO THE VARABL ARRAY AND TO THE LENS
!     THE ITH SOLUTION VECTOR COMPONENT APPLIES TO THE ITH VARIABLE
      LCVLCV=0.0D0
      DO I=1,VBCNT
!
!     THE CURRENT VARIABLE VALUE BECOMES THE PREVIOUS VARIABLE VALUE
         VARABL(I,5)=VARABL(I,4)
!
!     THE NEW SOLUTION VECTOR ADDED TO THE PREVIOS VARIABLE VALUE
!     BECOMES THE NEW SOLUTION VECTOR
!     VALUE
         LCVLCV=LCVLCV+DABS(((X(I)))/(DINMUL*VARABL(I,8)))
         VARABL(I,4)=VARABL(I,4)+(X(I))
!
         IF(VARABL(I,1).EQ.1.0D0) THEN
            IF(VARABL(I,9).LT.THMINLIM) VARABL(I,9)=THMINLIM
            IF(VARABL(I,10).GT.THMAXLIM) VARABL(I,10)=THMAXLIM
         END IF
         IF(VARABL(I,1).EQ.2.0D0.OR.VARABL(I,1).EQ.10.0D0) THEN
            IF(RDNEGLIM.EQ.0.0D0) RDNEGLIM=-1.0D-20
            IF(RDPOSLIM.EQ.0.0D0) RDPOSLIM=1.0D-20
            IF(VARABL(I,9).LT.(1.0D0/RDNEGLIM)) VARABL(I,9)=1.0D0/RDNEGLIM
            IF(VARABL(I,10).GT.(1.0D0/RDPOSLIM)) VARABL(I,10)=1.0D0/RDPOSLIM
         END IF
!     BOUNDS CHECKER
         IF(VARABL(I,4).LT.VARABL(I,9)) THEN
            VARABL(I,4)=VARABL(I,9)
            WRITE(OUTLYNE,*)'WARNING: '
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS LOWER BOUNDARY VALUE'
            CALL SHOWIT(1)
         END IF
         IF(VARABL(I,4).GT.VARABL(I,10)) THEN
            VARABL(I,4)=VARABL(I,10)
            WRITE(OUTLYNE,*)'WARNING: '
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS UPPER BOUNDARY VALUE'
            CALL SHOWIT(1)
         END IF
!
!
!     THE VARIABLE CHANGE IS (THE NEW CURRENT VALUE-OLD LAST CURRENT VALUE)
         VARABL(I,6)=VARABL(I,4)-VARABL(I,5)
!
!     DINCRS ARE ONLY CHANGED BY HAND AND BY THE ITER ADJUST COMMAND
!
      END DO
      LCVLCV=(LCVLCV)/DBLE(VBCNT)
!
!     NOW APPLY THE CHANGE VECTOR TO THE LENS
!**********************************************************************
      DO I=1,VBCNT
!     FIRST, IF THE VARIABLE IS A CONFIG 1 VARIABLE
!     NEXT IF THE VARIABLE IS IN A CONFIG OTHER THAN 1
         IF(VARABL(I,2).EQ.1.0D0) THEN
!     NON-CONFIGS VARIABLE MEANING CONFIG 1
!     THIS IS A LENS LEVEL VARIABLE CHANGE
!     GET THE DATA TYPE NUMBER OF THE VARIABLE
            VTYPE=INT(VARABL(I,1))
!                          CURVATURE
            IF(VTYPE.EQ.2.OR.VTYPE.EQ.1) THEN
!     SURFACE CURVATURE
!     NEW VALUE IS:
               V1=VARABL(I,4)
               call set_surf_curvature(INT(VARABL(I,3)), V1)
!                       CURVATURE DONE
            END IF
            IF(VTYPE.EQ.10.OR.VTYPE.EQ.9) THEN
!     SURFACE TORIC CURVATURE
!     NEW VALUE IS:
               V1=VARABL(I,4)
               call set_surf_toric_curvature(INT(VARABL(I,3)), V1)
!                       TORIC CURVATURE DONE
            END IF
            IF(VTYPE.GE.3.AND.VTYPE.LE.8) THEN
               IF(VTYPE.EQ.3) ALTYPE=3
               IF(VTYPE.EQ.4) ALTYPE=2
               IF(VTYPE.EQ.5) ALTYPE=4
               IF(VTYPE.EQ.6) ALTYPE=5
               IF(VTYPE.EQ.7) ALTYPE=6
               IF(VTYPE.EQ.8) ALTYPE=7
!     NEW VALUE IS:
               V1=VARABL(I,4)
               ALENS(ALTYPE,INT(VARABL(I,3)))=V1
!                       THESE VARIABLES DONE
            END IF
            IF(VTYPE.GE.11.AND.VTYPE.LE.25.OR.VTYPE.EQ.75.OR.VTYPE.GE.124.AND.VTYPE.LE.149) THEN
               IF(VTYPE.EQ.11) ALTYPE=41
               IF(VTYPE.EQ.12) ALTYPE=37
               IF(VTYPE.EQ.13) ALTYPE=38
               IF(VTYPE.EQ.14) ALTYPE=39
               IF(VTYPE.EQ.15) ALTYPE=40
               IF(VTYPE.EQ.16) ALTYPE=118
               IF(VTYPE.EQ.17) ALTYPE=119
               IF(VTYPE.EQ.18) ALTYPE=120
               IF(VTYPE.EQ.19) ALTYPE=114
               IF(VTYPE.EQ.20) ALTYPE=115
               IF(VTYPE.EQ.21) ALTYPE=46
               IF(VTYPE.EQ.22) ALTYPE=47
               IF(VTYPE.EQ.23) ALTYPE=48
               IF(VTYPE.EQ.24) ALTYPE=49
               IF(VTYPE.EQ.25) ALTYPE=50
               IF(VTYPE.EQ.75) ALTYPE=43
               IF(VTYPE.EQ.124) ALTYPE=71
               IF(VTYPE.EQ.125) ALTYPE=72
               IF(VTYPE.EQ.126) ALTYPE=73
               IF(VTYPE.EQ.127) ALTYPE=74
               IF(VTYPE.EQ.128) ALTYPE=75
               IF(VTYPE.EQ.129) ALTYPE=81
               IF(VTYPE.EQ.130) ALTYPE=82
               IF(VTYPE.EQ.131) ALTYPE=83
               IF(VTYPE.EQ.132) ALTYPE=84
               IF(VTYPE.EQ.133) ALTYPE=85
               IF(VTYPE.EQ.134) ALTYPE=116
               IF(VTYPE.EQ.135) ALTYPE=86
               IF(VTYPE.EQ.136) ALTYPE=87
               IF(VTYPE.EQ.137) ALTYPE=78
               IF(VTYPE.EQ.138) ALTYPE=79
               IF(VTYPE.EQ.139) ALTYPE=80
               IF(VTYPE.EQ.140) ALTYPE=89
               IF(VTYPE.EQ.141) ALTYPE=11
               IF(VTYPE.EQ.142) ALTYPE=10
               IF(VTYPE.EQ.143) ALTYPE=90
               IF(VTYPE.EQ.144) ALTYPE=91
               IF(VTYPE.EQ.145) ALTYPE=92
               IF(VTYPE.EQ.146) ALTYPE=93
               IF(VTYPE.EQ.147) ALTYPE=94
               IF(VTYPE.EQ.148) ALTYPE=95
               IF(VTYPE.EQ.149) ALTYPE=98
!     NEW VALUE IS:
               V1=VARABL(I,4)
               ALENS(ALTYPE,INT(VARABL(I,3)))=V1
            END IF
            IF(VTYPE.EQ.150) THEN
!     NEW VALUE IS:
               V1=VARABL(I,4)
               GPREG(INT(VARABL(I,3)))=V1
            END IF
            IF(VTYPE.GE.250.AND.VTYPE.LE.4218) THEN
               ALTYPE=VTYPE-249
!     NEW VALUE IS:
               V1=VARABL(I,4)
!     RESET THE APPRORIATE ARRAY VALUE IN THE DEFORMABLE SURFACE
               ISURF=INT(VARABL(I,3))
               DEFGR1=surf_default_flag(ISURF)
               DEFGR2=surf_mtracei_nx(ISURF)
               DEFGR3=surf_mtracei_ny(ISURF)
               DEFGR4=surf_psfbin_data(ISURF)
               DEFGR5=surf_profit_data(ISURF)
               DEFGR6=0.0D0
               DEFGR7=ALENS(109,ISURF)
               DEFGR8=0.0D0
               ACTNUM=ALTYPE
               NEWDEFVAL=V1
               ERR1=.FALSE.
               ERR2=.FALSE.
               CALL DEFGRIDS(6,ISURF,ERR1,ERR2)
            END IF
            IF(VTYPE.GE.27.AND.VTYPE.LE.74) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
               V1=VARABL(I,4)
               FTFL01((VTYPE-26),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
            END IF
            IF(VTYPE.GE.76.AND.VTYPE.LE.123) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
               V1=VARABL(I,4)
               FTFL01((VTYPE-27),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
            END IF
!
         ELSE
!     CONFIGS VARIABLE
!     VCFG IS THE CONFIG NUMBER
            VCFG=INT(VARABL(I,2))
!     VTYPE IS THE VARIABLE TYPE NUMBER AS USED IN THE VARIABLES ARRAYS
            VTYPE=INT(VARABL(I,1))
!
!     FOR VARIABLE I, APPLY THE SPECIFIED CHANGE TO THE SPECIFIED
!     CONFIG
!
!     THE NEW VARAIBLE VALUE IS JUST
            V1=VARABL(I,4)
!     CONVERT THIS VALUE TO A CHARACTER*23 CHARACTER VARIABLE
            VADD=INT(VARABL(I,14))
            IF(CFADD(VADD,1).EQ.1.AND.V1.NE.0.0D0) V1=1.0D0/V1
            IF(CFADD(VADD,1).EQ.9.AND.V1.NE.0.0D0) V1=1.0D0/V1
            CALL AUXNTA
!
!     THE POSITION IN THE CFADD,CFVAL AND CFCHAR ARRAYS WHERE THIS
!     VARIABLE IS FOUND IS:
!
            IF(CFADD(VADD,1).GE.27.AND.CFADD(VADD,1).LE.74.OR.CFADD(VADD,1).GE.76.AND.CFADD(VADD,1).LE.123 .OR.CFADD(VADD,1).EQ.141) THEN
               CFVAL(VADD,2)=V1
               CFCHAR(VADD,2)=AV1
!     NOW UPDATE THE CONFIG ARRAY
               CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,6):CFADD(VADD,7))=AV1(1:23)
            ELSE
               CFVAL(VADD,1)=V1
               CFCHAR(VADD,1)=AV1
!     NOW UPDATE THE CONFIG ARRAY
               CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,4):CFADD(VADD,5))=AV1(1:23)
            END IF
!     NOW LOOK UP WHERE THIS CHARACTER REPRESENTATION OF THE NEW VALUE
!     SHOULD BE STUFFED INTO THE CONFIG ARRAYS CONFG AND
!     STUFF IT THERE.
!
!     NOW LOOP BACK AND REPEAT FOR THE NEXT VARIABLE.
!     FINISHED WITH A CONFIG VARIABLE
         END IF
!     LOOP TO NEXT VARIABL
      END DO
!     UPDATE THE LENS OR THE PERMANENT LENS WILL BE ******!
      CALL FIXDEFORMFILE
      F6=1
      F1=0
      F22=0
      LNSTYP=2
      CALL LNSEOS
!**********************************************************************
!     AND RE-EVALUATE THE OPERANDS AND DISPLAY
!     THE NEW FIGURE OF MERIT, THE OLD FIGURE OF MERIT  AND ITS CHANGE
      SAVE_KDP(4)=SAVEINPT(4)
      F28=1
      MSG=.FALSE.
      OPTMES=.FALSE.
      WC='FMT'
      WQ='        '
      SQ=0
      SN=0
      SST=0
      WS=' '
      DF1=1
      DF2=1
      DF3=1
      DF4=1
      DF5=1
      STI=0
      SN=0
      S1=0
      S2=0
      S3=0
      S4=0
      S5=0
      W1=0.0D0
      IF(.NOT.SILENT) CALL FMT2
      IF(SILENT) CALL FMT3
      REST_KDP(4)=RESTINPT(4)
      DEALLOCATE(WT,W,V,BTB,BTG,STAT=ALLOERR)
      RETURN
   END IF
   IF(WQ.EQ.'D'.OR.WQ.EQ.'DIR') THEN
!
!       THIS IS ITER DIR.
!     FORM (A) STORED IN THE SPOT FOR BTB TO SAVE MEMORY ONLY
!     THIS IS JUST THE UNWEIGHTED DERIVATIVE MATRIX
!
      BTB(1:OPCNT,1:VBCNT)=MDERIV(1:OPCNT,1:VBCNT)
!     NOW FORM F STORED IN THE SPOT FOR BTG TO SAVE MEMORY ONLY
!     THIS IS JUST THE UNWEIGHTED DESIRED CHANGES TO THE OPERANDS
      BTG(1:OPCNT)=-OPERND(1:OPCNT,14)
!
!     NOW SOLVE THE PROBLEM WITH SVD AND THEN APPLY THE SOLUTION TO
!     THE LENS
!
      MP=VBCNT
      NP2=VBCNT
      N=VBCNT
      M=VBCNT
!       DO SINGULAR VALUE DECOMPOSITION
      SM=M
      SSN=N
      CALL SVDCMPA(W,V,VN,VN1,BTB,BTG)
      M=SM
      N=SSN
      WMAX=-1.0D300
      DO J=1,N
         IF(W(J).GT.WMAX) WMAX=W(J)
      END DO
      WMIN=WMAX*SINGTOL
      DO J=1,N
         IF(W(J).LT.WMIN) W(J)=0.0D0
      END DO
!
!       SOLVE LINEAR EQUATION
!
      SM=M
      SSN=N
      CALL SVBKSBA(W,V,VN,VN1,BTB,BTG)
      M=SM
      N=SSN
!
!     NOW APPLY THE SOLUTION VECTOR X(I) TO THE VARABL ARRAY AND TO THE LENS
!     THE ITH SOLUTION VECTOR COMPONENT APPLIES TO THE ITH VARIABLE
      LCVLCV=0.0D0
!
      DO I=1,VBCNT
!
!     THE CURRENT VARIABLE VALUE BECOMES THE PREVIOUS VARIABLE VALUE
         VARABL(I,5)=VARABL(I,4)
!
!     THE NEW SOLUTION VECTOR ADDED TO THE PREVIOS VARIABLE VALUE
!     BECOMES THE NEW SOLUTION VECTOR
!     VALUE
         VARABL(I,4)=VARABL(I,4)+(X(I))
         LCVLCV=LCVLCV+DABS(((X(I)))/(DINMUL*VARABL(I,8)))
!
!     BOUNDS CHECKER
         IF(VARABL(I,4).LT.VARABL(I,9)) THEN
            VARABL(I,4)=VARABL(I,9)
            WRITE(OUTLYNE,*)'WARNING: '
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS LOWER BOUNDARY VALUE'
            CALL SHOWIT(1)
         END IF
         IF(VARABL(I,4).GT.VARABL(I,10)) THEN
            VARABL(I,4)=VARABL(I,10)
            WRITE(OUTLYNE,*)'WARNING: '
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS UPPER BOUNDARY VALUE'
            CALL SHOWIT(1)
         END IF
!
!
!     THE VARIABLE CHANGE IS (THE NEW CURRENT VALUE-OLD LAST CURRENT VALUE)
         VARABL(I,6)=VARABL(I,4)-VARABL(I,5)
!
!     DINCRS ARE ONLY CHANGED BY HAND AND BY THE ITER ADJUST COMMAND
!
      END DO
      LCVLCV=DSQRT(LCVLCV)/DBLE(VBCNT)
!
!     NOW APPLY THE CHANGE VECTOR TO THE LENS
!**********************************************************************
      DO I=1,VBCNT
!     FIRST, IF THE VARIABLE IS A CONFIG 1 VARIABLE
!     NEXT IF THE VARIABLE IS IN A CONFIG OTHER THAN 1
         IF(VARABL(I,2).EQ.1.0D0) THEN
!     NON-CONFIGS VARIABLE MEANING CONFIG 1
!     THIS IS A LENS LEVEL VARIABLE CHANGE
!     GET THE DATA TYPE NUMBER OF THE VARIABLE
            VTYPE=INT(VARABL(I,1))
!                          CURVATURE
            IF(VTYPE.EQ.2.OR.VTYPE.EQ.1) THEN
!     SURFACE CURVATURE
!     NEW VALUE IS:
               V1=VARABL(I,4)
               call set_surf_curvature(INT(VARABL(I,3)), V1)
!                       CURVATURE DONE
            END IF
            IF(VTYPE.EQ.10.OR.VTYPE.EQ.9) THEN
!     SURFACE TORIC CURVATURE
!     NEW VALUE IS:
               V1=VARABL(I,4)
               call set_surf_toric_curvature(INT(VARABL(I,3)), V1)
!                       TORIC CURVATURE DONE
            END IF
            IF(VTYPE.GE.3.AND.VTYPE.LE.8) THEN
               IF(VTYPE.EQ.3) ALTYPE=3
               IF(VTYPE.EQ.4) ALTYPE=2
               IF(VTYPE.EQ.5) ALTYPE=4
               IF(VTYPE.EQ.6) ALTYPE=5
               IF(VTYPE.EQ.7) ALTYPE=6
               IF(VTYPE.EQ.8) ALTYPE=7
!     NEW VALUE IS:
               V1=VARABL(I,4)
               ALENS(ALTYPE,INT(VARABL(I,3)))=V1
!                       THESE VARIABLES DONE
            END IF
            IF(VTYPE.GE.11.AND.VTYPE.LE.25.OR.VTYPE.EQ.75.OR.VTYPE.GE.124.AND.VTYPE.LE.149) THEN
               IF(VTYPE.EQ.11) ALTYPE=41
               IF(VTYPE.EQ.12) ALTYPE=37
               IF(VTYPE.EQ.13) ALTYPE=38
               IF(VTYPE.EQ.14) ALTYPE=39
               IF(VTYPE.EQ.15) ALTYPE=40
               IF(VTYPE.EQ.16) ALTYPE=118
               IF(VTYPE.EQ.17) ALTYPE=119
               IF(VTYPE.EQ.18) ALTYPE=120
               IF(VTYPE.EQ.19) ALTYPE=114
               IF(VTYPE.EQ.20) ALTYPE=115
               IF(VTYPE.EQ.21) ALTYPE=46
               IF(VTYPE.EQ.22) ALTYPE=47
               IF(VTYPE.EQ.23) ALTYPE=48
               IF(VTYPE.EQ.24) ALTYPE=49
               IF(VTYPE.EQ.25) ALTYPE=50
               IF(VTYPE.EQ.75) ALTYPE=43
               IF(VTYPE.EQ.124) ALTYPE=71
               IF(VTYPE.EQ.125) ALTYPE=72
               IF(VTYPE.EQ.126) ALTYPE=73
               IF(VTYPE.EQ.127) ALTYPE=74
               IF(VTYPE.EQ.128) ALTYPE=75
               IF(VTYPE.EQ.129) ALTYPE=81
               IF(VTYPE.EQ.130) ALTYPE=82
               IF(VTYPE.EQ.131) ALTYPE=83
               IF(VTYPE.EQ.132) ALTYPE=84
               IF(VTYPE.EQ.133) ALTYPE=85
               IF(VTYPE.EQ.134) ALTYPE=116
               IF(VTYPE.EQ.135) ALTYPE=86
               IF(VTYPE.EQ.136) ALTYPE=87
               IF(VTYPE.EQ.137) ALTYPE=78
               IF(VTYPE.EQ.138) ALTYPE=79
               IF(VTYPE.EQ.139) ALTYPE=80
               IF(VTYPE.EQ.140) ALTYPE=89
               IF(VTYPE.EQ.141) ALTYPE=11
               IF(VTYPE.EQ.142) ALTYPE=10
               IF(VTYPE.EQ.143) ALTYPE=90
               IF(VTYPE.EQ.144) ALTYPE=91
               IF(VTYPE.EQ.145) ALTYPE=92
               IF(VTYPE.EQ.146) ALTYPE=93
               IF(VTYPE.EQ.147) ALTYPE=94
               IF(VTYPE.EQ.148) ALTYPE=95
               IF(VTYPE.EQ.149) ALTYPE=98
!     NEW VALUE IS:
               V1=VARABL(I,4)
               ALENS(ALTYPE,INT(VARABL(I,3)))=V1
            END IF
            IF(VTYPE.EQ.150) THEN
!     NEW VALUE IS:
               V1=VARABL(I,4)
               GPREG(INT(VARABL(I,3)))=V1
            END IF
            IF(VTYPE.GE.250.AND.VTYPE.LE.4218) THEN
               ALTYPE=VTYPE-249
!     NEW VALUE IS:
               V1=VARABL(I,4)
!     RESET THE APPRORIATE ARRAY VALUE IN THE DEFORMABLE SURFACE
               ISURF=INT(VARABL(I,3))
               DEFGR1=surf_default_flag(ISURF)
               DEFGR2=surf_mtracei_nx(ISURF)
               DEFGR3=surf_mtracei_ny(ISURF)
               DEFGR4=surf_psfbin_data(ISURF)
               DEFGR5=surf_profit_data(ISURF)
               DEFGR6=0.0D0
               DEFGR7=ALENS(109,ISURF)
               DEFGR8=0.0D0
               ACTNUM=ALTYPE
               NEWDEFVAL=V1
               ERR1=.FALSE.
               ERR2=.FALSE.
               CALL DEFGRIDS(6,ISURF,ERR1,ERR2)
            END IF
            IF(VTYPE.GE.27.AND.VTYPE.LE.74) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
               V1=VARABL(I,4)
               FTFL01((VTYPE-26),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
            END IF
            IF(VTYPE.GE.76.AND.VTYPE.LE.123) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
               V1=VARABL(I,4)
               FTFL01((VTYPE-27),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
            END IF
!
         ELSE
!     CONFIGS VARIABLE
!     VCFG IS THE CONFIG NUMBER
            VCFG=INT(VARABL(I,2))
!     VTYPE IS THE VARIABLE TYPE NUMBER AS USED IN THE VARIABLES ARRAYS
            VTYPE=INT(VARABL(I,1))
!
!     FOR VARIABLE I, APPLY THE SPECIFIED CHANGE TO THE SPECIFIED
!     CONFIG
!
!     THE NEW VARAIBLE VALUE IS JUST
            V1=VARABL(I,4)
!     CONVERT THIS VALUE TO A CHARACTER*23 CHARACTER VARIABLE
            VADD=INT(VARABL(I,14))
            IF(CFADD(VADD,1).EQ.1.AND.V1.NE.0.0D0) V1=1.0D0/V1
            IF(CFADD(VADD,1).EQ.9.AND.V1.NE.0.0D0) V1=1.0D0/V1
            CALL AUXNTA
!
!     THE POSITION IN THE CFADD,CFVAL AND CFCHAR ARRAYS WHERE THIS
!     VARIABLE IS FOUND IS:
!
            IF(CFADD(VADD,1).GE.27.AND.CFADD(VADD,1).LE.74.OR.CFADD(VADD,1).GE.76.AND.CFADD(VADD,1).LE.123 .OR.CFADD(VADD,1).EQ.141) THEN
               CFVAL(VADD,2)=V1
               CFCHAR(VADD,2)=AV1
!     NOW UPDATE THE CONFIG ARRAY
               CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,6):CFADD(VADD,7))=AV1(1:23)
            ELSE
               CFVAL(VADD,1)=V1
               CFCHAR(VADD,1)=AV1
!     NOW UPDATE THE CONFIG ARRAY
               CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,4):CFADD(VADD,5))=AV1(1:23)
            END IF
!     NOW LOOK UP WHERE THIS CHARACTER REPRESENTATION OF THE NEW VALUE
!     SHOULD BE STUFFED INTO THE CONFIG ARRAYS CONFG AND
!     STUFF IT THERE.
!
!     NOW LOOP BACK AND REPEAT FOR THE NEXT VARIABLE.
!     FINISHED WITH A CONFIG VARIABLE
         END IF
!     LOOP TO NEXT VARIABL
      END DO
!     UPDATE THE LENS OR THE PERMANENT LENS WILL BE ******!
      CALL FIXDEFORMFILE
      F6=1
      F1=0
      F22=0
      LNSTYP=2
      CALL LNSEOS
!**********************************************************************
!     AND RE-EVALUATE THE OPERANDS AND DISPLAY
!     THE NEW FIGURE OF MERIT, THE OLD FIGURE OF MERIT  AND ITS CHANGE
      SAVE_KDP(4)=SAVEINPT(4)
      F28=1
      MSG=.FALSE.
      OPTMES=.FALSE.
      WC='FMT'
      WQ='        '
      SQ=0
      SN=0
      SST=0
      WS=' '
      DF1=1
      DF2=1
      DF3=1
      DF4=1
      DF5=1
      STI=0
      SN=0
      S1=0
      S2=0
      S3=0
      S4=0
      S5=0
      W1=0.0D0
      IF(.NOT.SILENT) CALL FMT2
      IF(SILENT) CALL FMT3
      REST_KDP(4)=RESTINPT(4)
      DEALLOCATE(WT,W,V,BTB,BTG,STAT=ALLOERR)
      RETURN
   END IF
END
! SUB SOLVIT_POWELL.FOR
SUBROUTINE SOLVIT_POWELL(IID,JJD,MDERIV,SILENT)
   USE GLOBALS
!
   use DATCFG
   use DATSUB
   use DATLEN
   use mod_surface
   use DATMAI
   IMPLICIT NONE
!
   CHARACTER OOLDWQ*8
!
   LOGICAL ITDER,SILENT
!
   INTEGER SSN,SM,NP2,MP,N,J,I,L,M,VTYPE,ALTYPE,VADD,VCFG ,VN1,MAXCNT,IV1,VN,ALLOERR,IID,JJD
!
   INTEGER ISURF,IVB,IVBB
!
   REAL*8 NEWDEFVAL,PFACSCL
!
   COMMON/DEFVALCOM/NEWDEFVAL
!
   REAL*8 X(1:100000),WT,V1,MAX,VTEMP,OLDCUR,NEWCUR
!
   DIMENSION WT(:)
!
   ALLOCATABLE :: WT
!
   LOGICAL LVAL,OLDSILENT
!
   CHARACTER AV1*23

   COMMON/SVD1/SM,SSN,MP,NP2
!
   COMMON/SVD2/X
!
   COMMON/CAUX1/V1,AV1
!
   REAL*8 MDERIV
!
   DIMENSION MDERIV(1:IID,1:JJD)
!
   LOGICAL ERR1,ERR2
!
!
   REAL*8 W,V,BTB,BTG,DIAGSUM,WMAX,WMIN
   DIMENSION W(:),V(:,:),BTB(:,:),BTG(:)
   ALLOCATABLE :: W,V,BTB,BTG
   VN=IID
   VN1=IID
   DEALLOCATE(WT,W,V,BTB,BTG,STAT=ALLOERR)
   ALLOCATE (W(VN),V(VN,VN),WT(VN1),BTB(VN1,VN1),BTG(VN1),STAT=ALLOERR)
   W(1:VN)=0.0D0
   WT(1:VN)=0.0D0
   BTG(1:VN)=0.0D0
   V(1:VN,1:VN)=0.0D0
   BTB(1:VN,1:VN)=0.0D0
   OOLDWQ='        '
   ITDER=.FALSE.
!
!       THIS IS SUBROUTINE SOLVIT_POWELL. THIS IS THE SUBROUTINE WHICH
!       HANDLES THE SOLUTION TO THE ITER POWELL PROBLEM
!     FORM (BTB+KC)
!     FIRST JUST BTB
!     THIS IS THE MATRIX PRODUCT OF THE TRANSPOSE OF THE DERIV MATRIX
!     TIMES THE DERIV MATRIX ITSELF
!     L IS THE FIRST INDEX OF BTB AND M IS THE SECOND
!     BTB IS SQUARE WITH DIMENSION VBCNT
!
!     MAKE OUR SHUFFLE LIST OF RANDOMLY CHOSEN VARIABLE NUMBERS
   N=VBCNT
   DEALLOCATE (DARR,STAT=ALLOERR)
   ALLOCATE (DARR(1:N,1:2),STAT=ALLOERR)
   CALL SHUFFLE(N,DARR)
!
   IF(VBCNT.GE.OPCNT) MAXCNT=VBCNT
   IF(VBCNT.LT.OPCNT) MAXCNT=OPCNT
!
!       ZERO OUT TOO SMALL DERIVATIVES
!
   DO I=1,MAXCNT
      DO M=1,MAXCNT
         IF(DABS(MDERIV(I,M)).LT.ONTOL) MDERIV(I,M)=0.0D0
      END DO
   END DO
!
   DO L=1,MAXCNT
      DO M=1,MAXCNT
         DO I=1,MAXCNT
            BTB(L,M)=BTB(L,M)+(MDERIV(I,L)*MDERIV(I,M))
         END DO
      END DO
   END DO
!
!                       WE DO THIS ONCE FOR EACH VARIABLE
   DO IVBB=1,VBCNT
      IVB=INT(DARR(IVBB,2))
!
!     NO DAMPING IS USED IN ITER POWELL

!     NOW FORM BTG
      L=IVB
      DO I=1,OPCNT
         BTG(L)=BTG(L)+(MDERIV(I,L)*(-OPERND(I,14)))
      END DO
!
!     NOW SOLVE THE PROBLEM WITH SVD AND THEN APPLY THE SOLUTION TO
!     THE LENS
!
      MP=MAXCNT
      NP2=MAXCNT
      N=MAXCNT
      M=MAXCNT
!       DO SINGULAR VALUE DECOMPOSITION
      SM=M
      SSN=N
      CALL SVDCMPA(W,V,VN,VN1,BTB,BTG)
      M=SM
      N=SSN
      WMAX=-1.0D300
      DO J=1,N
         IF(W(J).GT.WMAX) WMAX=W(J)
      END DO
      WMIN=WMAX*SINGTOL
      DO J=1,N
         IF(W(J).LT.WMIN) W(J)=0.0D0
      END DO
!
!       SOLVE LINEAR EQUATION
!
      SM=M
      SSN=N
      CALL SVBKSBA(W,V,VN,VN1,BTB,BTG)
      M=SM
      N=SSN
!
!
!     NOW APPLY THE SOLUTION VECTOR X(I) TO THE VARABL ARRAY AND TO THE LENS
!     THE ITH SOLUTION VECTOR COMPONENT APPLIES TO THE ITH VARIABLE
      LCVLCV=0.0D0
      I=IVB
!
!     THE CURRENT VARIABLE VALUE BECOMES THE PREVIOUS VARIABLE VALUE
      VARABL(I,5)=VARABL(I,4)
!
!     THE NEW SOLUTION VECTOR ADDED TO THE PREVIOS VARIABLE VALUE
!     BECOMES THE NEW SOLUTION VECTOR
!     VALUE
      LCVLCV=LCVLCV+DABS(((X(I)))/(DINMUL*VARABL(I,8)))
      VARABL(I,4)=VARABL(I,4)+(X(I))
!
      IF(VARABL(I,1).EQ.1.0D0) THEN
         IF(VARABL(I,9).LT.THMINLIM) VARABL(I,9)=THMINLIM
         IF(VARABL(I,10).GT.THMAXLIM) VARABL(I,10)=THMAXLIM
      END IF
      IF(VARABL(I,1).EQ.2.0D0.OR.VARABL(I,1).EQ.10.0D0) THEN
         IF(RDNEGLIM.EQ.0.0D0) RDNEGLIM=-1.0D-20
         IF(RDPOSLIM.EQ.0.0D0) RDPOSLIM=1.0D-20
         IF(VARABL(I,9).LT.(1.0D0/RDNEGLIM)) VARABL(I,9)=1.0D0/RDNEGLIM
         IF(VARABL(I,10).GT.(1.0D0/RDPOSLIM)) VARABL(I,10)=1.0D0/RDPOSLIM
      END IF
!     BOUNDS CHECKER
      IF(VARABL(I,4).LT.VARABL(I,9)) THEN
         VARABL(I,4)=VARABL(I,9)
         WRITE(OUTLYNE,*)'WARNING: '
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS LOWER BOUNDARY VALUE'
         CALL SHOWIT(1)
      END IF
      IF(VARABL(I,4).GT.VARABL(I,10)) THEN
         VARABL(I,4)=VARABL(I,10)
         WRITE(OUTLYNE,*)'WARNING: '
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'VARIABLE # ',I,' HAS REACHED ITS UPPER BOUNDARY VALUE'
         CALL SHOWIT(1)
      END IF
!
!
!     THE VARIABLE CHANGE IS (THE NEW CURRENT VALUE-OLD LAST CURRENT VALUE)
      VARABL(I,6)=VARABL(I,4)-VARABL(I,5)
!
!     DINCRS ARE ONLY CHANGED BY HAND AND BY THE ITER ADJUST COMMAND
!
      LCVLCV=(LCVLCV)/DBLE(VBCNT)
!
!     NOW APPLY THE CHANGE VECTOR TO THE LENS
!**********************************************************************
      I=IVB
!     FIRST, IF THE VARIABLE IS A CONFIG 1 VARIABLE
!     NEXT IF THE VARIABLE IS IN A CONFIG OTHER THAN 1
      IF(VARABL(I,2).EQ.1.0D0) THEN
!     NON-CONFIGS VARIABLE MEANING CONFIG 1
!     THIS IS A LENS LEVEL VARIABLE CHANGE
!     GET THE DATA TYPE NUMBER OF THE VARIABLE
         VTYPE=INT(VARABL(I,1))
!                          CURVATURE
         IF(VTYPE.EQ.2.OR.VTYPE.EQ.1) THEN
!     SURFACE CURVATURE
!     NEW VALUE IS:
            V1=VARABL(I,4)
            call set_surf_curvature(INT(VARABL(I,3)), V1)
!                       CURVATURE DONE
         END IF
         IF(VTYPE.EQ.10.OR.VTYPE.EQ.9) THEN
!     SURFACE TORIC CURVATURE
!     NEW VALUE IS:
            V1=VARABL(I,4)
            call set_surf_toric_curvature(INT(VARABL(I,3)), V1)
!                       TORIC CURVATURE DONE
         END IF
         IF(VTYPE.GE.3.AND.VTYPE.LE.8) THEN
            IF(VTYPE.EQ.3) ALTYPE=3
            IF(VTYPE.EQ.4) ALTYPE=2
            IF(VTYPE.EQ.5) ALTYPE=4
            IF(VTYPE.EQ.6) ALTYPE=5
            IF(VTYPE.EQ.7) ALTYPE=6
            IF(VTYPE.EQ.8) ALTYPE=7
!     NEW VALUE IS:
            V1=VARABL(I,4)
            ALENS(ALTYPE,INT(VARABL(I,3)))=V1
!                       THESE VARIABLES DONE
         END IF
         IF(VTYPE.GE.11.AND.VTYPE.LE.25.OR.VTYPE.EQ.75.OR.VTYPE.GE.124.AND.VTYPE.LE.149) THEN
            IF(VTYPE.EQ.11) ALTYPE=41
            IF(VTYPE.EQ.12) ALTYPE=37
            IF(VTYPE.EQ.13) ALTYPE=38
            IF(VTYPE.EQ.14) ALTYPE=39
            IF(VTYPE.EQ.15) ALTYPE=40
            IF(VTYPE.EQ.16) ALTYPE=118
            IF(VTYPE.EQ.17) ALTYPE=119
            IF(VTYPE.EQ.18) ALTYPE=120
            IF(VTYPE.EQ.19) ALTYPE=114
            IF(VTYPE.EQ.20) ALTYPE=115
            IF(VTYPE.EQ.21) ALTYPE=46
            IF(VTYPE.EQ.22) ALTYPE=47
            IF(VTYPE.EQ.23) ALTYPE=48
            IF(VTYPE.EQ.24) ALTYPE=49
            IF(VTYPE.EQ.25) ALTYPE=50
            IF(VTYPE.EQ.75) ALTYPE=43
            IF(VTYPE.EQ.124) ALTYPE=71
            IF(VTYPE.EQ.125) ALTYPE=72
            IF(VTYPE.EQ.126) ALTYPE=73
            IF(VTYPE.EQ.127) ALTYPE=74
            IF(VTYPE.EQ.128) ALTYPE=75
            IF(VTYPE.EQ.129) ALTYPE=81
            IF(VTYPE.EQ.130) ALTYPE=82
            IF(VTYPE.EQ.131) ALTYPE=83
            IF(VTYPE.EQ.132) ALTYPE=84
            IF(VTYPE.EQ.133) ALTYPE=85
            IF(VTYPE.EQ.134) ALTYPE=116
            IF(VTYPE.EQ.135) ALTYPE=86
            IF(VTYPE.EQ.136) ALTYPE=87
            IF(VTYPE.EQ.137) ALTYPE=78
            IF(VTYPE.EQ.138) ALTYPE=79
            IF(VTYPE.EQ.139) ALTYPE=80
            IF(VTYPE.EQ.140) ALTYPE=89
            IF(VTYPE.EQ.141) ALTYPE=11
            IF(VTYPE.EQ.142) ALTYPE=10
            IF(VTYPE.EQ.143) ALTYPE=90
            IF(VTYPE.EQ.144) ALTYPE=91
            IF(VTYPE.EQ.145) ALTYPE=92
            IF(VTYPE.EQ.146) ALTYPE=93
            IF(VTYPE.EQ.147) ALTYPE=94
            IF(VTYPE.EQ.148) ALTYPE=95
            IF(VTYPE.EQ.149) ALTYPE=98
!     NEW VALUE IS:
            V1=VARABL(I,4)
            ALENS(ALTYPE,INT(VARABL(I,3)))=V1
         END IF
         IF(VTYPE.EQ.150) THEN
!     NEW VALUE IS:
            V1=VARABL(I,4)
            GPREG(INT(VARABL(I,3)))=V1
         END IF
         IF(VTYPE.GE.250.AND.VTYPE.LE.4218) THEN
            ALTYPE=VTYPE-249
!     NEW VALUE IS:
            V1=VARABL(I,4)
!     RESET THE APPRORIATE ARRAY VALUE IN THE DEFORMABLE SURFACE
            ISURF=INT(VARABL(I,3))
            DEFGR1=surf_default_flag(ISURF)
            DEFGR2=surf_mtracei_nx(ISURF)
            DEFGR3=surf_mtracei_ny(ISURF)
            DEFGR4=surf_psfbin_data(ISURF)
            DEFGR5=surf_profit_data(ISURF)
            DEFGR6=0.0D0
            DEFGR7=ALENS(109,ISURF)
            DEFGR8=0.0D0
            ACTNUM=ALTYPE
            NEWDEFVAL=V1
            ERR1=.FALSE.
            ERR2=.FALSE.
            CALL DEFGRIDS(6,ISURF,ERR1,ERR2)
         END IF
         IF(VTYPE.GE.27.AND.VTYPE.LE.74) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
            V1=VARABL(I,4)
            FTFL01((VTYPE-26),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
         END IF
         IF(VTYPE.GE.76.AND.VTYPE.LE.123) THEN
!     SPECIAL SURFACE COEFFICIENTS
!     NEW VALUE IS:
            V1=VARABL(I,4)
            FTFL01((VTYPE-27),INT(VARABL(I,3)))=V1
!                       SPECIAL SURFACE COEFICIENTS DONE
         END IF
!
      ELSE
!     CONFIGS VARIABLE
!     VCFG IS THE CONFIG NUMBER
         VCFG=INT(VARABL(I,2))
!     VTYPE IS THE VARIABLE TYPE NUMBER AS USED IN THE VARIABLES ARRAYS
         VTYPE=INT(VARABL(I,1))
!
!     FOR VARIABLE I, APPLY THE SPECIFIED CHANGE TO THE SPECIFIED
!     CONFIG
!
!     THE NEW VARAIBLE VALUE IS JUST
         V1=VARABL(I,4)
!     CONVERT THIS VALUE TO A CHARACTER*23 CHARACTER VARIABLE
         VADD=INT(VARABL(I,14))
         IF(CFADD(VADD,1).EQ.1.AND.V1.NE.0.0D0) V1=1.0D0/V1
         IF(CFADD(VADD,1).EQ.9.AND.V1.NE.0.0D0) V1=1.0D0/V1
         CALL AUXNTA
!
!     THE POSITION IN THE CFADD,CFVAL AND CFCHAR ARRAYS WHERE THIS
!     VARIABLE IS FOUND IS:
!
         IF(CFADD(VADD,1).GE.27.AND.CFADD(VADD,1).LE.74.OR.CFADD(VADD,1).GE.76.AND.CFADD(VADD,1).LE.123 .OR.CFADD(VADD,1).EQ.141) THEN
            CFVAL(VADD,2)=V1
            CFCHAR(VADD,2)=AV1
!     NOW UPDATE THE CONFIG ARRAY
            CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,6):CFADD(VADD,7))=AV1(1:23)
         ELSE
            CFVAL(VADD,1)=V1
            CFCHAR(VADD,1)=AV1
!     NOW UPDATE THE CONFIG ARRAY
            CONFG(CFADD(VADD,3),CFADD(VADD,9))(CFADD(VADD,4):CFADD(VADD,5))=AV1(1:23)
         END IF
!     NOW LOOK UP WHERE THIS CHARACTER REPRESENTATION OF THE NEW VALUE
!     SHOULD BE STUFFED INTO THE CONFIG ARRAYS CONFG AND
!     STUFF IT THERE.
!
!     NOW LOOP BACK AND REPEAT FOR THE NEXT VARIABLE.
!     FINISHED WITH A CONFIG VARIABLE
      END IF
!     LOOP TO NEXT VARIABL
!     WRITE(OUTLYNE,*)'VARIABLE ',IVB
!     CALL SHOWIT(1)
   END DO
!     UPDATE THE LENS OR THE PERMANENT LENS WILL BE ******!
   CALL FIXDEFORMFILE
   F6=1
   F1=0
   F22=0
   LNSTYP=2
   CALL LNSEOS
!**********************************************************************
!     AND RE-EVALUATE THE OPERANDS AND DISPLAY
!     THE NEW FIGURE OF MERIT, THE OLD FIGURE OF MERIT  AND ITS CHANGE
   SAVE_KDP(4)=SAVEINPT(4)
   F28=1
   MSG=.FALSE.
   OPTMES=.FALSE.
   WC='FMT'
   WQ='        '
   SQ=0
   SN=0
   SST=0
   WS=' '
   DF1=1
   DF2=1
   DF3=1
   DF4=1
   DF5=1
   STI=0
   SN=0
   S1=0
   S2=0
   S3=0
   S4=0
   S5=0
   W1=0.0D0
   CALL FMT3
   SOLEXT=.TRUE.
   REST_KDP(4)=RESTINPT(4)
   DEALLOCATE(WT,W,V,BTB,BTG,STAT=ALLOERR)
   RETURN
END
