!       SPLIT FROM PLOTCAD8.FOR FOR SMALLER IFX COMPILATION UNITS

SUBROUTINE FANTP
!
   use DATHGR
   use DATLEN
   use DATMAI
   IMPLICIT NONE
!
!       THIS ROUTINE DOES THE PLOTTING OF FAN TYPE AND UNITS
!     FOR FAN PLOTTING
!
   CHARACTER UNN*41,NNTT3*45,V1*3,V2*3,V3*3 &
   &,VV1*38,B*140
!
   INTEGER COLPAS,NUNN,NNT
!
!
   CALL MY_SETCHARASPECT(1.5,1.5)
!
   IF(FANTYP.EQ.1.AND.QALTYP.EQ.0)&
   &NNTT3='YZ-PLANE TRANSVERSE ABERRATIONS'
   IF(FANTYP.EQ.1.AND.QALTYP.EQ.1)&
   &NNTT3='YZ-PLANE OPTICAL PATH DIFFERENCES'
   IF(FANTYP.EQ.1.AND.QALTYP.EQ.2)&
   &NNTT3='YZ-PLANE CHROMATIC DIFFERENCES'
   IF(FANTYP.EQ.1.AND.QALTYP.EQ.3)&
   &NNTT3='YZ-PLANE LONGITUDINAL ABERRATIONS'
!
   IF(FANTYP.EQ.2.AND.QALTYP.EQ.0)&
   &NNTT3='XZ-PLANE TRANSVERSE ABERRATIONS'
   IF(FANTYP.EQ.2.AND.QALTYP.EQ.1)&
   &NNTT3='XZ-PLANE OPTICAL PATH DIFFERENCES'
   IF(FANTYP.EQ.2.AND.QALTYP.EQ.2)&
   &NNTT3='XZ-PLANE CHROMATIC DIFFERENCES'
   IF(FANTYP.EQ.2.AND.QALTYP.EQ.3)&
   &NNTT3='XZ-PLANE LONGITUDINAL ABERRATIONS'
!
   IF(FANTYP.EQ.3.AND.QALTYP.EQ.0)&
   &NNTT3='+45 DEG. TRANSVERSE ABERRATIONS'
   IF(FANTYP.EQ.3.AND.QALTYP.EQ.1)&
   &NNTT3='+45 DEG. OPTICAL PATH DIFFERENCES'
   IF(FANTYP.EQ.3.AND.QALTYP.EQ.2)&
   &NNTT3='+45 DEG. CHROMATIC DIFFERENCES'
   IF(FANTYP.EQ.3.AND.QALTYP.EQ.3)&
   &NNTT3='+45 DEG. LONGITUDINAL ABERRATIONS'
!
   IF(FANTYP.EQ.4.AND.QALTYP.EQ.0)&
   &NNTT3='-45 DEG. TRANSVERSE ABERRATIONS'
   IF(FANTYP.EQ.4.AND.QALTYP.EQ.1)&
   &NNTT3='-45 DEG. OPTICAL PATH DIFFERENCES'
   IF(FANTYP.EQ.4.AND.QALTYP.EQ.2)&
   &NNTT3='-45 DEG. CHROMATIC DIFFERENCES'
   IF(FANTYP.EQ.4.AND.QALTYP.EQ.3)&
   &NNTT3='-45 DEG. LONGITUDINAL ABERRATIONS'
!
   IF(FANTYP.EQ.5.AND.QALTYP.EQ.0)&
   &NNTT3='XZ/YZ-PLANE TRANSVERSE ABERRATIONS'
   IF(FANTYP.EQ.5.AND.QALTYP.EQ.1)&
   &NNTT3='XZ/YZ-PLANE OPTICAL PATH DIFFERENCES'
   IF(FANTYP.EQ.5.AND.QALTYP.EQ.2)&
   &NNTT3='XZ/YZ-PLANE CHROMATIC DIFFERENCES'
   IF(FANTYP.EQ.5.AND.QALTYP.EQ.3)&
   &NNTT3='XZ/YZ-PLANE LONGITUDINAL ABERRATIONS'
!
   IF(FANTYP.EQ.6.AND.QALTYP.EQ.0)&
   &NNTT3='XZ/YZ-PLANE TRANSVERSE ABERRATIONS'
   IF(FANTYP.EQ.6.AND.QALTYP.EQ.1)&
   &NNTT3='XZ/YZ-PLANE OPTICAL PATH DIFFERENCES'
   IF(FANTYP.EQ.6.AND.QALTYP.EQ.2)&
   &NNTT3='XZ/YZ-PLANE CHROMATIC DIFFERENCES'
   IF(FANTYP.EQ.6.AND.QALTYP.EQ.3)&
   &NNTT3='XZ/YZ-PLANE LONGITUDINAL ABERRATIONS'
!
   IF(FANTYP.EQ.1.AND.QALTYP.EQ.0)&
   &NNT=31
   IF(FANTYP.EQ.1.AND.QALTYP.EQ.1)&
   &NNT=33
   IF(FANTYP.EQ.1.AND.QALTYP.EQ.2)&
   &NNT=30
   IF(FANTYP.EQ.1.AND.QALTYP.EQ.3)&
   &NNT=33
!
   IF(FANTYP.EQ.2.AND.QALTYP.EQ.0)&
   &NNT=31
   IF(FANTYP.EQ.2.AND.QALTYP.EQ.1)&
   &NNT=33
   IF(FANTYP.EQ.2.AND.QALTYP.EQ.2)&
   &NNT=30
   IF(FANTYP.EQ.2.AND.QALTYP.EQ.3)&
   &NNT=33
!
   IF(FANTYP.EQ.3.AND.QALTYP.EQ.0)&
   &NNT=31
   IF(FANTYP.EQ.3.AND.QALTYP.EQ.1)&
   &NNT=33
   IF(FANTYP.EQ.3.AND.QALTYP.EQ.2)&
   &NNT=30
   IF(FANTYP.EQ.3.AND.QALTYP.EQ.3)&
   &NNT=33
!
   IF(FANTYP.EQ.4.AND.QALTYP.EQ.0)&
   &NNT=31
   IF(FANTYP.EQ.4.AND.QALTYP.EQ.1)&
   &NNT=33
   IF(FANTYP.EQ.4.AND.QALTYP.EQ.2)&
   &NNT=30
   IF(FANTYP.EQ.4.AND.QALTYP.EQ.3)&
   &NNT=33
!
   IF(FANTYP.EQ.5.AND.QALTYP.EQ.0)&
   &NNT=34
   IF(FANTYP.EQ.5.AND.QALTYP.EQ.1)&
   &NNT=36
   IF(FANTYP.EQ.5.AND.QALTYP.EQ.2)&
   &NNT=33
   IF(FANTYP.EQ.5.AND.QALTYP.EQ.3)&
   &NNT=36
!
   IF(FANTYP.EQ.6.AND.QALTYP.EQ.0)&
   &NNT=34
   IF(FANTYP.EQ.6.AND.QALTYP.EQ.1)&
   &NNT=36
   IF(FANTYP.EQ.6.AND.QALTYP.EQ.2)&
   &NNT=33
   IF(FANTYP.EQ.6.AND.QALTYP.EQ.3)&
   &NNT=36
!
   IF(SYSTEM(30).EQ.1.0D0.OR.SYSTEM(30).EQ.2.0D0) THEN
!     FOCAL OR UFOCAL
      IF(SYSTEM(6).EQ.1.0D0) UNN='UNITS = in(s)'
      IF(SYSTEM(6).EQ.2.0D0) UNN='UNITS = cm(s)'
      IF(SYSTEM(6).EQ.3.0D0) UNN='UNITS = mm(s)'
      IF(SYSTEM(6).EQ.4.0D0) UNN='UNITS = meter(s)'
      IF(SYSTEM(6).EQ.1.0D0) NUNN=13
      IF(SYSTEM(6).EQ.2.0D0) NUNN=13
      IF(SYSTEM(6).EQ.3.0D0) NUNN=13
      IF(SYSTEM(6).EQ.4.0D0) NUNN=16
   ELSE
!     NOT FOCAL
   END IF
   IF(SYSTEM(30).EQ.3.0D0.OR.SYSTEM(30).EQ.4.0D0) THEN
!     AFOCAL OR UAFOCAL
      UNN='UNITS = radian(s)'
      NUNN=17
   ELSE
!     NOT AFOCAL
   END IF
!     IF OPD RESET ABERRATION UNITS
   IF(QALTYP.EQ.1)&
   &UNN='UNITS = WAVES AT REFERENCE WAVELENGTH'
   IF(QALTYP.EQ.1)&
   &NUNN=37
!     NOW PLOT NNTT3 ABOVE UNN JUST TO THE RIGHT OF THE WAVELENGTH
!     LEGEND
!
   WRITE(B,181) NEWOBJ
   READ(B,201) V1
   WRITE(B,181) NEWREF
   READ(B,201) V2
   WRITE(B,181) NEWIMG
   READ(B,201) V3
181 FORMAT(I3)
201 FORMAT(A3)
!
   VV1=V1//'=OBJ SURF '//V2//'=REF SURF '//V3//'=IMG SURF'

!
!     DO THE PLOTTING OF THE PLOT TYPE
!
   COLPAS=COLLBL
   CALL MY_COLTYP(COLPAS)
   CALL MY_JUSTSTRING(4100,1175,NNTT3(1:NNT),0,1,3,3)
   CALL MY_JUSTSTRING(4100,1000,UNN(1:NUNN),0,1,3,3)
   CALL MY_JUSTSTRING(4100,850,VV1(1:37),0,1,3,3)
!
!     NOW BOX THE LEGENDS OFF
!
   COLPAS=COLFRM
   CALL MY_COLTYP(COLPAS)
!     LIFT PEN, MOVE TO TOP
   CALL MY_PLOT(3000,1325,0,0,-10,10010,-10,70010)
!     DROP PEN, DRAW LINE
   CALL MY_PLOT(10000,1325,1,0,-10,10010,-10,70010)
   CALL MY_PLOT(3000,700,0,0,-10,10010,-10,70010)
   CALL MY_PLOT(10000,700,1,0,-10,10010,-10,70010)
!     LIFT PEN, RETURN TO 0,0
   CALL MY_PLOT(0,0,0,0,-10,10010,-10,70010)
!
   IF(.NOT.PLEXIS) PLEXIS=.TRUE.
!
   RETURN
END
! SUB FANRWV.FOR
SUBROUTINE FANRWV
!
   use DATHGR
   use DATLEN
   use DATMAI
   IMPLICIT NONE
!
!       THIS ROUTINE DOES THE PLOTTING OF THE REFERENCE WAVELENGTH LEGEND
!     FOR FAN PLOTTING
!
   CHARACTER NNTT1*8,NNTT2*9,VALUE*8,NNTT3*10,VALUE1*10,NNTT4*22 &
   &,NNTT11*10,NNTT12*8,NNTT10*16,B*140
!
   INTEGER COLPAS,NT1ANG,NT1SIZ
!
!
!     SET LETTER SIZE AND ANGLE
   NT1SIZ=1
   NT1ANG=0
   CALL MY_SETCHARASPECT(1.5,1.5)
!
!     DO THE PLOTTING OF THE LEGEND FOR THE REFERENCE WAVELENGTH
   NNTT4='REFERENCE WAVELENGTH'
   COLPAS=COLLBL
   CALL MY_COLTYP(COLPAS)
   CALL MY_JUSTSTRING(3200,550,NNTT4(1:20),NT1ANG,NT1SIZ,3,3)
!
!     DO THE PLOTTING OF THE LEGEND FOR THE REFERENCE WAVELENGTH
   IF(SYSTEM(REFWV).GT.99.9D0) THEN
      IF(REFWV.GE.1.AND.REFWV.LE.5) THEN
         WRITE(B,180)REAL(SYSTEM(REFWV))
      END IF
      IF(REFWV.GE.6.AND.REFWV.LE.10) THEN
         WRITE(B,180)REAL(SYSTEM(65+REFWV))
      END IF
      READ(B,200) VALUE1
180   FORMAT(G10.4)
200   FORMAT(A10)
      NNTT3=VALUE1
      COLPAS=COLLBL
      CALL MY_COLTYP(COLPAS)
      CALL MY_JUSTSTRING(3200,350,NNTT3(1:10),NT1ANG,NT1SIZ,3,3)
   ELSE
      IF(REFWV.GE.1.AND.REFWV.LE.5) THEN
         WRITE(B,181)REAL(SYSTEM(REFWV))
      END IF
      IF(REFWV.GE.6.AND.REFWV.LE.10) THEN
         WRITE(B,181)REAL(SYSTEM(65+REFWV))
      END IF
      READ(B,201) VALUE
181   FORMAT(F8.5)
201   FORMAT(A8)
      NNTT1=VALUE
      COLPAS=COLLBL
      CALL MY_COLTYP(COLPAS)
      CALL MY_JUSTSTRING(3200,350,NNTT1(1:8),NT1ANG,NT1SIZ,3,3)
   END IF
   NNTT2='MICRON(S)'
   COLPAS=COLLBL
   CALL MY_COLTYP(COLPAS)
   CALL MY_JUSTSTRING(4200,350,NNTT2,NT1ANG,NT1SIZ,3,3)
!
   NNTT10='REL. APT. OFFSET'
   CALL MY_JUSTSTRING(5350,550,NNTT10(1:16),NT1ANG,NT1SIZ,3,3)
!
   IF(FANOFF.GT.99.9D0) THEN
      WRITE(B,180)REAL(FANOFF)
      READ(B,200) VALUE1
      NNTT11=VALUE1
      CALL MY_JUSTSTRING(5350,350,NNTT11(1:10),NT1ANG,NT1SIZ,3,3)
   ELSE
      WRITE(B,181)REAL(FANOFF)
      READ(B,201) VALUE
      NNTT12=VALUE
      COLPAS=COLLBL
      CALL MY_COLTYP(COLPAS)
      CALL MY_JUSTSTRING(5350,350,NNTT12(1:8),NT1ANG,NT1SIZ,3,3)
   END IF
!
   COLPAS=COLFRM
   CALL MY_COLTYP(COLPAS)
!     NOW BOX THE LEGENDS OFF
!
!     LIFT PEN, MOVE TO TOP
   CALL MY_PLOT(3000,700,0,0,-10,10010,-10,10010)
!     DROP PEN, DRAW LINE
   CALL MY_PLOT(5200,700,1,0,-10,10010,-10,10010)
   CALL MY_PLOT(5200,250,1,0,-10,10010,-10,10010)
   CALL MY_PLOT(3000,700,0,0,-10,10010,-10,10010)
!     DROP PEN, DRAW LINE
   CALL MY_PLOT(10000,700,1,0,-10,10010,-10,10010)
!     LIFT PEN, RETURN TO 0,0
   CALL MY_PLOT(0,0,0,0,-10,10010,-10,10010)
!
   IF(.NOT.PLEXIS) PLEXIS=.TRUE.
!
   RETURN
END
! SUB FANLI.FOR
SUBROUTINE FANLI
!
   use DATHGR
   use DATLEN
   use DATMAI
   IMPLICIT NONE
!
!       THIS ROUTINE DOES THE PLOTTING OF THE LENS IDENTIFIER "LI"
!     FOR FAN PLOTTING
!
   CHARACTER DTY*10,TMY*8,BL20*20,BLNOTE*80,NNTT1*80
!
   INTEGER COLPAS,NT1ANG,NT1SIZ,IIX,IIY,IIUD
!
!
   BL20='                    '
   BLNOTE=BL20//BL20//BL20//BL20
!
!     MOVE TO THE STARTING POSITION FOR THE LI
!
   CALL MY_PLOT(50,100,0,0,-10,10010,-10,10010)

!     DO THE PLOTTING OF THE LENS IDENTIFIER
   IF(STMPT) CALL MYTIME(TMY)
   IF(STMPD) CALL MYDATE(DTY)
   IF(.NOT.STMPT.AND..NOT.STMPD) NNTT1=LI
   IF(STMPT.AND.STMPD) NNTT1=TMY//' '//DTY//LI
   IF(STMPT.AND..NOT.STMPD) NNTT1=TMY//' '//LI
   IF(.NOT.STMPT.AND.STMPD) NNTT1=DTY//LI
   IF(NNTT1.NE.BLNOTE) THEN
      CALL MY_SETCHARASPECT(1.5,1.5)
      COLPAS=COLLBL
      CALL MY_COLTYP(COLPAS)
      CALL MY_JUSTSTRING(50,100,NNTT1(1:80),0,1,3,3)

      COLPAS=COLFRM
      CALL MY_COLTYP(COLPAS)
!     LIFT PEN, MOVE TO TOP
      CALL MY_PLOT(0,250,0,0,-10,10010,-10,10010)
!     DROP PEN, DRAW LINE
      CALL MY_PLOT(10000,250,1,0,-10,10010,-10,10010)
!     LIFT PEN, RETURN TO 0,0
      CALL MY_PLOT(0,0,0,0,-10,10010,-10,10010)
      IF(.NOT.PLEXIS) PLEXIS=.TRUE.
   ELSE
!     LI BLANK, NOT ACTION
   END IF
!
   RETURN
END
! SUB FANFOV.FOR
SUBROUTINE FANFOV
!
!       THIS IS SUBROUTINE FANFOV. THIS IS THE SUBROUTINE WHICH
!       HANDLES CMD LEVEL COMMAND "FANFIELD"
!
   use DATMAI
   IMPLICIT NONE
!
   REAL*8 F1X,F1Y,F2X,F2Y,F3X,F3Y
!
   COMMON/FANFOB/F1X,F1Y,F2X,F2Y,F3X,F3Y
!
!
   IF(STI.EQ.1.OR.SQ.EQ.0) THEN
      OUTLYNE=&
      &'"FANFIELD" SETS UP FIELDS FOR AUTOMATED FAN PLOTS'
      CALL SHOWIT(1)
      OUTLYNE='CURRENT FIELD SETTINGS ARE:'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'F1 (y-fob,xfob) = ',F1Y,' , ',F1X
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'F2 (y-fob,xfob) = ',F2Y,' , ',F2X
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'F3 (y-fob,xfob) = ',F3Y,' , ',F3X
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SQ.EQ.1.AND.SN.EQ.0) THEN
      IF(WQ.EQ.'F1') OUTLYNE=&
      &'CURRENT "F1" FIELD SETTINGS ARE:'
      IF(WQ.EQ.'F1') CALL SHOWIT(1)
      IF(WQ.EQ.'F1')&
      &WRITE(OUTLYNE,*)'F1 (y-fob,xfob) = ',F1Y,' , ',F1X
      IF(WQ.EQ.'F1') CALL SHOWIT(1)

      IF(WQ.EQ.'F2') OUTLYNE=&
      &'CURRENT "F2" FIELD SETTINGS ARE:'
      IF(WQ.EQ.'F2') CALL SHOWIT(1)
      IF(WQ.EQ.'F2')&
      &WRITE(OUTLYNE,*)'F2 (y-fob,xfob) = ',F2Y,' , ',F2X
      IF(WQ.EQ.'F2') CALL SHOWIT(1)

      IF(WQ.EQ.'F3') OUTLYNE=&
      &'CURRENT "F3" FIELD SETTINGS ARE:'
      IF(WQ.EQ.'F3') CALL SHOWIT(1)
      IF(WQ.EQ.'F3')&
      &WRITE(OUTLYNE,*)'F3 (y-fob,xfob) = ',F3Y,' , ',F3X
      IF(WQ.EQ.'F3') CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & '"FANFIELD" TAKES NO ALPHANUMERIC INPUT'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      OUTLYNE=&
      &'"FANFIELD" TAKES NO NUMERIC WORD #3, #4 OR #5 INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
!     IF(W1 OR W2 ARE DEFAULT, DON'T CHANGE THEM
   IF(WQ.EQ.'F1') THEN
      IF(DF1.EQ.0) F1Y=W1
      IF(DF2.EQ.0) F1X=W2
   END IF
   IF(WQ.EQ.'F2') THEN
      IF(DF1.EQ.0) F2Y=W1
      IF(DF2.EQ.0) F2X=W2
   END IF
   IF(WQ.EQ.'F3') THEN
      IF(DF1.EQ.0) F3Y=W1
      IF(DF2.EQ.0) F3X=W2
   END IF
   RETURN
!       ALL DONE
END
! SUB FANDO1.FOR
SUBROUTINE FANDO1(JCOMP,KCOMP)
!
   use DATHGR
   use DATLEN
   use DATMAI
   IMPLICIT NONE
!
!     DOES FAN DATA PLOTTING FOR USER-DEFINED FAN PLOTTING
!
   INTEGER I,JJJ,K,IK,IIK,L,JJJJ,IXVALUE,IYVALUE,JCOMP,KCOMP &
   &,COLPAS,OPLPOS,OPRPOS,ITES,XA1,XB1,YA1,YB1,ENDER
!
   INTEGER JIMX(1:102),JIMY(1:102),XA,XB,JIMFLG(1:102)
!
   REAL*8 YMAX,RANGE,YMIN,STEPJP1 &
   &,XP1,XP2 &
   &,XVAL,YVAL,DRAXX,FACTOR,XPOS,XXPOS,XXPOS1
!
   REAL*8 XY2(1:102)

   LOGICAL SPLFIT,FANEXT
!
   COMMON/FANEXI/FANEXT
!
   INTEGER XTENT,YTENT,CLIP
!
   COMMON/USEFAN/XTENT,YTENT,CLIP
!
   COLPAS=JCOMP
   CALL MY_COLTYP(COLPAS)
   IF(KCOMP.LT.0.OR.KCOMP.GT.9) KCOMP=0
   LNTYPE=KCOMP
   STEPJP1=DBLE(XTENT)/DBLE(MAXFAN)
!
   ENDER=INT(DBLE(XTENT)/(DBLE(XTENT)/100.0D0))
   I=ENDER
   JIMFLG(1:I)=0
   JIMX(1:I)=0
   JIMY(1:I)=0
   XY2(1:I)=0.0D0
   DRAFLG(1:21)=0
   DRAFLG2(1:21)=0
   NDRAY(1:21)=0
   NDRAX(1:21)=0
!
!     FIRST THE FSSI FACTOR
!     THE FSSI FACTOR IS ALWAYS MADE USING THE FIRST FIELD POSITION
!     AND THE FIRST WAVELENGTH FOR WHICH A FAN EXISTS
!
   IF(FSSIFLG) THEN
!     SCALE FACTOR EXISTS, DON'T CALCULATE IT
   ELSE
!     CALCULATE SSI BASED ON BIGGEST FAN VALUE
      YMAX=-1.0D10
!     PROCEED WITH THE CALCULATION
      DO JJJ=1,MAXFAN+1
         IF((FFAANN(1,JJJ,1,1)).GE.YMAX)&
         &YMAX=(FFAANN(1,JJJ,1,1))
      END DO
      YMIN=1.0D10
!     PROCEED WITH THE CALCULATION
      DO JJJ=1,MAXFAN+1
         IF((FFAANN(1,JJJ,1,1)).LE.YMIN)&
         &YMIN=(FFAANN(1,JJJ,1,1))
      END DO
      RANGE=DABS(YMAX-YMIN)
      RANGE=RANGE*2.0D0
      IF(RANGE.EQ.0.0D0) RANGE=1.0D20
      FSSI=RANGE
      FSSIFLG=.TRUE.
   END IF
!
!     NOW SCALE THE DATA BY DIVIDING BY SSI AND MULTIPLYING
!     BY (YTENT/2), THE EXTENT OF ALL VERTICAL PLOT AXES
!
   DO JJJ=1,MAXFAN+1
      FFAANN(1,JJJ,1,1)=((FFAANN(1,JJJ,1,1)/FSSI)*DBLE(YTENT/2))
   END DO
!     THE ACTUAL PLOTTING IS NOW DONE
!
!     SHIFT PLOT TO START AT LEFT EDGE
   DO JJJ=1,MAXFAN+1
      FFAANN(1,JJJ,1,1)=FFAANN(1,JJJ,1,1)+DBLE(YTENT/2)
   END DO
!     FAN DATA GOES FROM 0.0 TO YTENT.0
!     COLOR WAS SET BY JCOMP AT THE TOP OF THIS ROUTINE
!     LINESTYLE IS ALWAYS SET BY THE LINE STYLE COMMAND
!
!     ABSISSA DATA GOES FROM 0.0 TO XTENT
   ABSIS=DBLE(XTENT/2)/(DBLE(MAXFAN)/2.0D0)
   DRAXX=0.0D0
   FACTOR=0.0D0
   DO JJJ=1,MAXFAN+1
      DRAY(JJJ)=FFAANN(1,JJJ,1,1)
      DRAX(JJJ)=DRAXX+FACTOR
      FACTOR=FACTOR+ABSIS
      DRAFLG(JJJ)=INT(FFAANN(1,JJJ,5,1))
   END DO
   XP1=1.0D35
   XP2=1.0D35
!     NOW SPLINE FIT THESE AND INTERPOLATE TO ENDER POINTS
!     ACROSS THE Y PLOT DIRECTION
!
!     DON'T DO THE FIT IF ALL THE DRAY VALUES ARE THE SAME
   SPLFIT=.FALSE.
   DO ITES=2,MAXFAN+1
      IF(REAL(DRAY(ITES-1)).NE.REAL(DRAY(ITES))) SPLFIT=.TRUE.
   END DO
   IF(SPLFIT) CALL SPLINE(DRAX,DRAY,MAXFAN+1,XP1,XP2,XY2)
!     NOW INTERPOLATE THE VALUES AND PLOT THEM
!
   IK=1
   DO XVAL=0.0D0,DBLE(XTENT),DBLE(XTENT)/100.0D0
      IF(SPLFIT) CALL SPLINT(DRAX,DRAY,XY2,MAXFAN+1,XVAL,YVAL)
      JIMX(IK)=DRAY(1)
      IF(SPLFIT) JIMX(IK)=INT(YVAL)
      JIMY(IK)=-INT(XVAL)
      IK=IK+1
   END DO
! HERE DO THE APPROPRIATE SETTING OF JIMFLG()
   DO JJJJ=1,MAXFAN
!     XXPOS IS THE CURRENT POSITION ACROSS THE FAN IN THE NON-
!     INTERPOLATED DATA
      XXPOS=DBLE(JJJJ-1)*STEPJP1
!     XXPOS1 IS THE NEXT POSITION ACROSS THE FAN IN THE NON-
!     INTERPOLATED DATA
      XXPOS1=DBLE(JJJJ)*STEPJP1
!
      DO JJJ=1,ENDER
!     XPOS IS THE CURRENT POSITION ACROSS THE FAN IN THE INTERPOLATED
!     DATA
         XPOS=DBLE(JJJ-1)*(DBLE(XTENT)/(DBLE(ENDER)-1.0D0))
!
         IF(XPOS.GT.XXPOS1) GO TO 82
!     IF XPOS LIES AT OR BETWEEN XXPOS AND XXPOS1, DO A TEST
!     ELSE PROCEED
         IF(XPOS.GT.XXPOS.AND.XPOS.LT.XXPOS1) THEN
!     DO THE TEST AND SET JIMFLG APPROPRIATELY
!
            IF(DRAFLG(JJJJ).EQ.0.AND.DRAFLG(JJJJ+1).EQ.0 &
            &.OR.DRAFLG(JJJJ).EQ.0.AND.DRAFLG(JJJJ+1).EQ.1 &
            &.OR.DRAFLG(JJJJ).EQ.1.AND.DRAFLG(JJJJ+1).EQ.0) THEN
               JIMFLG(JJJ)=0
            ELSE
               JIMFLG(JJJ)=1
            END IF
!
         ELSE
!     NO TEST, PROCEED
         END IF
         IF(XPOS.EQ.XXPOS) THEN
!     DO THE TEST AND SET JIMFLG APPROPRIATELY
!
            IF(DRAFLG(JJJJ).EQ.0) THEN
               JIMFLG(JJJ)=0
            ELSE
               JIMFLG(JJJ)=1
            END IF
!
         ELSE
!     NO TEST, PROCEED
         END IF
         IF(XPOS.EQ.XXPOS1) THEN
!     DO THE TEST AND SET JIMFLG APPROPRIATELY
!
            IF(DRAFLG(JJJJ+1).EQ.0) THEN
               JIMFLG(JJJ)=0
            ELSE
               JIMFLG(JJJ)=1
            END IF
!
         ELSE
!     NO TEST, PROCEED
         END IF
!     XPOS MUST BE BETWEEN OR BELOW XXPOS TO GET HERE
      END DO
82    CONTINUE
   END DO
!
   IF(CLIP.EQ.0) THEN
      XA1=FANAXX-(XTENT/2)
      XB1=FANAXX+(XTENT/2)
      YA1=FANAXY-(YTENT/2)
      YB1=FANAXY+(YTENT/2)
   ELSE
      XA1=0
      XB1=10000
      YA1=0
      YB1=7000
   END IF
   IXVALUE=-JIMY(1)+FANAXX-(XTENT/2)
   IYVALUE=JIMX(1)+FANAXY-(YTENT/2)
   CALL MY_PLOT(IXVALUE,IYVALUE,0,LNTYPE,XA1,XB1,YA1,YB1)
   DO IIK=2,ENDER
      IF(JIMFLG(IIK-1).EQ.0.AND.JIMFLG(IIK).EQ.0.OR.&
      &JIMFLG(IIK-1).EQ.0.AND.JIMFLG(IIK).EQ.1.OR.&
      &JIMFLG(IIK-1).EQ.1.AND.JIMFLG(IIK).EQ.0)THEN
         IXVALUE=-JIMY(IIK)+FANAXX-(XTENT/2)
         IYVALUE=JIMX(IIK)+FANAXY-(YTENT/2)
         CALL MY_PLOTC(IXVALUE,IYVALUE,0,LNTYPE,XA1,XB1,YA1,YB1)
      ELSE
         IXVALUE=-JIMY(IIK)+FANAXX-(XTENT/2)
         IYVALUE=JIMX(IIK)+FANAXY-(YTENT/2)
         CALL MY_PLOTC(IXVALUE,IYVALUE,1,LNTYPE,XA1,XB1,YA1,YB1)
      END IF
   END DO
   COLPAS=COLFRM
   CALL MY_COLTYP(COLPAS)
   LNTYPE=1
   RETURN
END
! ALL INTERACTER/WINTERACTER CALLS HAVE BEEN MOVED TO ISS.FOR
! SUB FANDO0.FOR
