!       TENTH FILE OF PLOT/CAD ROUTINES

! SUB USER_CONTOUR.FOR
SUBROUTINE USER_CONTOUR(IIU)
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use command_utils, only: is_command_query
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
   REAL REFHT
!
   real(real64) WVAL
!
   LOGICAL PLOTIT(1:10)
!
   REAL ZMAX1,ZMIN1
!
   LOGICAL AUTOZSCALE
!
   COMMON/AUTSCALE/ZMAX1,ZMIN1,AUTOZSCALE
!
   INTEGER KKV,KKK,I,KVAL,G,IU,IIU
!
!
   PLOTCAPCON=.TRUE.
!
   AUTOZSCALE=.TRUE.
!
   IF(DF2.EQ.1) IIU=0
   IF(DF2.EQ.0) IIU=1
!
   IF(is_command_query()) THEN
      OUTLYNE= '"USERCONT" PLOTS THE EXISTING USER-DEFINED CONTOUR PLOT'
      CALL SHOWIT(1)
      OUTLYNE= '"AS A CONTOUR PLOT'
      CALL SHOWIT(1)
      OUTLYNE= 'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.SN.EQ.1.OR.SQ.EQ.1) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & '"USERCONT" TAKES NO ADDITIONAL INPUT'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
!       OPEN DATA FILE, READ NUMBER OF DATA POINTS
!       READ X,Y,Z DATA SETS
!       READ VERTICAL AND HORIZONTAL PLOT AXIS LABELS
!       READ VERTICAL AND HORIZONTAL PLOT AXIS UNITS
!       READ Z-AXIS LABEL AND UNITS
!
!
!     NOW CALL ROUTINES TO DO THE CONTOUR PLOT
   CALL CON_USERPLOT(1,KVAL,REFHT,WVAL,KKV,KKK &
   &,IU)
!
   RETURN
END
! SUB CON_USERPLOT.FOR
SUBROUTINE CON_USERPLOT(IJ,KVAL,REFHT,WVAL,KKV,KKK,IU)
!     KVAL IS THE FIRST RECORD OF THE SPOT FILE TO READ
!     REFHT IS THE NORMALIZING AP HT.
!     WVAL IS THE DESIRED WAVELENGTH NUMBER
!     KKV IS THE TOTAL NUMBER OF POINTS TO BE READ IN FROM DSPOTT
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
   LOGICAL ITSFLAT
!
   INTEGER IJ,KVAL,K,I,J,NNX,KKI2,NNY,KK,KKK,IQ,KKV,II,IIVAL
   INTEGER ALLOERR,WVNUMB,IU
!
   real(real64) DL1,FV &
   &,WVAL
   REAL REFHT,ZMAX2,ZMIN2,RI,RII,ZSTEP
   REAL F1PLT,F2PLT,DELGRID
!
   REAL ZMAX1,ZMIN1
!
   LOGICAL AUTOZSCALE
!
   COMMON/AUTSCALE/ZMAX1,ZMIN1,AUTOZSCALE
!
   DIMENSION F1PLT(:,:),F2PLT(:,:)
!
   ALLOCATABLE :: F1PLT,F2PLT
!
   KKI2=NINT(SQRT(FLOAT(KKV)))
   DEALLOCATE(F1PLT,F2PLT,STAT=ALLOERR)
   ALLOCATE(F1PLT(KKK,KKK),&
   &F2PLT(KKK,KKK),STAT=ALLOERR)
!
   ZMAX1=-1.0E10
   ZMIN1=1.0E10
   ZMAX2=1.0E0
   ZMIN2=0.0E0
   I=1
   J=0
   DO IQ=1,ITOT-1
!     LOAD DSPOTT(*,ID) INTO DSPOT(*)
      ID=IQ
      CALL SPOTIT(4)
      IF(DSPOT(16).NE.WVAL) THEN
         GO TO 101
      END IF
      J=J+1
      IF(J.GT.KKK) THEN
         J=1
         I=I+1
      END IF
      F1PLT(J,I)=SNGL(DSPOT(4)/(TWOPII))
      F2PLT(J,I)=SNGL(DSPOT(12))
      WVNUMB=INT(DSPOT(16))
      IF(F2PLT(J,I).NE.0.0) THEN
         IF(F1PLT(J,I).GT.ZMAX1) ZMAX1=(F1PLT(J,I))
         IF(F1PLT(J,I).LE.ZMIN1) ZMIN1=(F1PLT(J,I))
      END IF
101   CONTINUE
   END DO
   ITSFLAT=.FALSE.
   IF(ABS(ZMIN1-ZMAX1).LT.1.0E-6) THEN
      IF(ABS(ZMIN1).LE.1.0E-6) ZMIN1=0.0
      ZMAX1=ZMIN1+1.0
      ITSFLAT=.TRUE.
      GO TO 5
   END IF
!
5  DO I=-10000,10000,1
      RI=FLOAT(I)/100.0
      RII=FLOAT(I+1)/100.0
      IF(ZMAX1.GT.RI.AND.ZMAX1.LE.RII) THEN
         ZMAX1=RII
         GO TO 10
      END IF
   END DO
10 CONTINUE
   DO I=-10000,10000,1
      RI=FLOAT(I)/100.0
      RII=FLOAT(I+1)/100.0
      IF(ZMIN1.GE.RI.AND.ZMIN1.LT.RII) THEN
         ZMIN1=RI
         GO TO 20
      END IF
   END DO
20 CONTINUE
   IF(ZMIN1.EQ.ZMAX1) THEN
      ZMAX1=ZMIN1+0.01
      DO J=1,KKI2
         DO I=1,KKI2
            IF(F1PLT(I,J).LT.0.0.AND.ABS(F1PLT(I,J)).LT.0.0001)&
            &F1PLT(I,J)=-0.0001
            IF(F1PLT(I,J).GE.0.0.AND.ABS(F1PLT(I,J)).LT.0.0001)&
            &F1PLT(I,J)= 0.0001
         END DO
      END DO
   END IF
6  CONTINUE
   DO J=1,KKI2
      DO I=1,KKI2
         IF(F1PLT(I,J).LT.0.0.AND.ABS(F1PLT(I,J)).LT.0.0001)&
         &F1PLT(I,J)=-0.0001
         IF(F1PLT(I,J).GE.0.0.AND.ABS(F1PLT(I,J)).LT.0.0001)&
         &F1PLT(I,J)= 0.0001
      END DO
   END DO

   DELGRID=1.0/(FLOAT(KKI2)-1.0)
   DO J=1,KKI2
      DO I=1,KKI2
         F1PLT(I,J)=(F1PLT(I,J)-ZMIN1)/(ZMAX1-ZMIN1)
         IF(ABS(F1PLT(I,J)).LT.1E-6) F1PLT(I,J)=0.0
         IF(ABS(F2PLT(I,J)).LT.1E-6) F2PLT(I,J)=0.0
      END DO
   END DO
   IF(ITSFLAT) THEN
      J=KKI2
      I=KKI2
      F1PLT(1:I,1:J)=0.01
   END IF
!     WE NOW HAVE PLOTABLE ARRAYS F1PLT AND F2PLT
!     THE ARRAYS ARE DIMENSIONED 1 BY KKI2
!     THE REFERENCE APERTURE WIDTH IS REFHT, MIN AND MAX Z VALUES
!     ARE 0 AND 1.0
!     IJ IS 1 FOR OPD AND 2 FOR INTENSITY
!     WAVLENGTH NUMBER IS WVNUMB
   ZSTEP=0.0
   IF(W3.GT.0.0D0.AND.IJ.EQ.1) ZSTEP=SNGL(W3)
   CALL PLTCONT(KKI2,F1PLT,F2PLT,REFHT,IJ &
   &,ZMIN2,ZMAX2,WVNUMB,ZSTEP,IU)
   DEALLOCATE(F1PLT,F2PLT,STAT=ALLOERR)
   RETURN
END
SUBROUTINE USERCONT(PCOUNT,F1PLT,F2PLT,REFHT,IJ &
&,ZMIN2,ZMAX2,WVNUMB,ZSTEP,IU)
   use DATSP1
   use DATHGR
   use DATSPD
   use DATLEN
   use mod_system, only: sys_wavelength
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
   REAL SPACER
   INTEGER ROT,I,J,ALLOERR,PCOUNT,COLPAS,IJ,WVNUMB,NSTEP,IU
!
   CHARACTER B*10,WAVVAL*10
!
   REAL ZMAX1,ZMIN1,ZSTEP,OPDPEAK,OPDPIT
!
   LOGICAL AUTOZSCALE
!
   COMMON/AUTSCALE/ZMAX1,ZMIN1,AUTOZSCALE
!
   REAL F1PLT,F2PLT,FTF1,FTF2,ZMIN2 &
   &,ZMAX2,REFHT
!
   INTEGER NT1SIZ,NT1ANG,IF1PLT,IF2PLT
!
   DIMENSION IF1PLT(PCOUNT,PCOUNT)&
   &,IF2PLT(PCOUNT,PCOUNT)
!
   DIMENSION FTF1(:,:),F1PLT(PCOUNT,PCOUNT)&
   &,F2PLT(PCOUNT,PCOUNT),FTF2(:,:)
   ALLOCATABLE :: FTF1,FTF2
!

   DEALLOCATE(FTF1,FTF2,STAT=ALLOERR)
   ALLOCATE(FTF1(PCOUNT,PCOUNT),FTF2(PCOUNT,PCOUNT),STAT=ALLOERR)
   DO I=1,PCOUNT
      DO J=1,PCOUNT
         F1PLT(I,J)=(F1PLT(I,J))
         IF(F2PLT(I,J).EQ.0.0) THEN
            F1PLT(I,J)=0.0
         END IF
      END DO
   END DO
   DO I=1,PCOUNT
      DO J=1,PCOUNT
         IF(F2PLT(I,J).EQ.0.0) F1PLT(I,J)=0.0
         F1PLT(I,J)=(F1PLT(I,J))*5000.0
         IF1PLT(I,J)=INT(F1PLT(I,J))
         F2PLT(I,J)=(F2PLT(I,J))*5000.0
         IF2PLT(I,J)=INT(F2PLT(I,J))
      END DO
   END DO
!
!
!     NSTEP IS DISTANCE IN Z BETWEEN CONTOURS IN D. I. U.
   IF(AUTOZSCALE.OR.ZSTEP.EQ.0.0) THEN
      NSTEP=500
   ELSE
      IF(IJ.EQ.1) NSTEP=NINT((ABS(ZSTEP/(ZMAX1-ZMIN1)))*5000.0)
      IF(IJ.EQ.2) NSTEP=500
   END IF
!     CALL PLOT CONTOUR HERE
   IF(NSTEP.LT.250) NSTEP=250
!
!     GENERATE GRAPHIC
!     DO A PLOT NEW
   DEVTYP=1
   LOOKY=0.0D0
   LOOKX=-1.0D0
   LOOKZ=0.0D0
!     GENERATE GRAPHIC
   CALL PLTDEV
   GRASET=.TRUE.
   PLEXIS=.TRUE.
   NT1SIZ=1
   NT1ANG=0
   CALL MY_SETCHARASPECT(1.5,1.5)
   COLPAS=COLFRM
   CALL MY_COLTYP(COLPAS)
   SAVE_KDP(1)=SAVEINPT(1)
   INPUT='PLOT FRAME'
   CALL PROCES
   REST_KDP(1)=RESTINPT(1)
   SAVE_KDP(1)=SAVEINPT(1)
   INPUT='PLOT LI'
   CALL PROCES
   REST_KDP(1)=RESTINPT(1)
   CALL MY_PLOT(5400,1500,0,0,0,10000,0,7000)
   CALL MY_PLOT(5400,2000,1,0,0,10000,0,7000)
   CALL MY_PLOT(5400,1500,0,0,0,10000,0,7000)
   CALL MY_PLOT(5900,1500,1,0,0,10000,0,7000)
   CALL MY_JUSTSTRING(5285,2040,'+Y',0,1,3,3)
   CALL MY_JUSTSTRING(5940,1470,'+X',0,1,3,3)
   WRITE(B,180)REAL(sys_wavelength(WVNUMB))
   READ(B,200) WAVVAL
180 FORMAT(G10.4)
200 FORMAT(A10)
   IF(IJ.EQ.1) THEN
      CALL MY_JUSTSTRING(100,250,&
      &'WAVEFRONT CONTOUR MAP AT WAVELENGTH = '&
      &//TRIM(WAVVAL)//' MICRON(S)',0,1,3,3)
      CALL MY_JUSTSTRING(6550,5400,&
      &'WAVEFRONT CONTOUR LEVELS'&
      &,0,1,3,3)
   END IF
   IF(IJ.EQ.2) THEN
      CALL MY_JUSTSTRING(100,250,&
      &'PUPIL INTENSITY MAP AT WAVELENGTH = '&
      &//TRIM(WAVVAL)//' MICRON(S)',0,1,3,3)
      CALL MY_JUSTSTRING(6550,5400,&
      &'RELATIVE PUPIL INTENSITY'&
      &,0,1,3,3)
   END IF
!     OPD
   OPDPEAK=ZMAX1
   OPDPIT=ZMIN1
   IF(IJ.EQ.1)&
   &CALL PLOT_CONTOUR_OPD(PCOUNT,IF1PLT,NSTEP,IU,OPDPEAK,OPDPIT)
!     APD
   IF(IJ.EQ.2)&
   &CALL PLOT_CONTOUR_APD(PCOUNT,IF2PLT,NSTEP,IU)
!
   DEALLOCATE(FTF1,FTF2,STAT=ALLOERR)
   RETURN
END
