MODULE PROFIT_GLOBAL
!
   PUBLIC
!
!       PROFIT GLOBAL MODULE
!
!       MAIN DATA ARRAYS FOR PROFIT
!       TRACK STOCK NAME
   CHARACTER*80 PROFITNAMES
   DIMENSION PROFITNAMES(:)
   ALLOCATABLE :: PROFITNAMES

!       TRACK STOCK TICKER
   CHARACTER*8 PROFITTICKER
   DIMENSION PROFITTICKER(:)
   ALLOCATABLE :: PROFITTICKER
!
!       ARRAY TO TRACK NUMBER OF VALID ENTRIES FOR EACH ISSUE
   INTEGER PROFITENTRIES,KENTRIES
   DIMENSION PROFITENTRIES(:,:)
!       FIRST DIMENSION GOES FROM 1 TO MAX NO OF ISSUES, SECOND GOES 1:2
!       WHERE 1 IS THE STARTING RECORD FOR THAT ISSUE AND 2 IS THE ENDING RECORD OF THAT ISSUE
   ALLOCATABLE :: PROFITENTRIES

!       ARRAY TO TRACK STOCK DATA (PRIMARY AND DERIVED)
!       DIMENSION 1 (J) GOES FROM 1 TO MAXIMUM NUMBER OF DAYS IN THE DATABASE
!       DIMENSION 2 (K) GOES FROM 1 TO 100
   INTEGER IREC,JREC1,JREC2
!        K=1  : PRICE HI
!        K=2  : PRICE LO
!        K=3  : PRICE CLOSE
!        K=4  : SHORT MOVING AVERAGE
!        K=5  : MEDIUM MOVING AVERAGE
!        K=6  : LONG MOVING AVERAGE
!        K=7  : SHORT OSCILLATOR
!        K=8  : LONG OSCILLATOR
!        K=9  : SHORT TREND
!        K=10 : LONG TREND
!        K=11 : SPREAD
!        K=12 : VOLUME
!        K=13 : DATE YYYMMDD
!        K=14 : HI PRICE        DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=15 : LO PRICE        DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=16 : CLOSING PRICE  DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=17 : SHORT  MOVING AVERAGE DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=18 : MEDIUM MOVING AVERAGE DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=19 : LONG   MOVING AVERAGE DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=20 : SHORT OSCILLATOR DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=21 : LONG  OSCILLATOR DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=22 : SHORT TREND DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=23 : LONG  TREND DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=24 : SPREAD DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=25 : VOLUME DELTA (CURRENT VALUE - PREVIOUS DAYS VALUE), 0.0 FOR FIRST DAY
!        K=26 : NOT USED
!        K=27 TO K=38 ARE THE SECOND DELTAS OF K=14 TO K=25
!        K=40 : JULIAN DAY NUMBER
!        K=41 : JULIAN DAY NUMBER 1ST DELTA
!        K=42 : JULIAN DAY NUMBER 2ND DELTA
!
!        K=43 TO 45 NOT YET USED
!
!        K=46 : OPENING PRICE
!        K=47 : SREC (THE ISSUE NUMBER IN THE PROFIT.DAT FILE)
!        K=48 : IREC (SEQUENTIAL ENTRY NUMBER IN THE PROFIT.DAT FILE)
!        K=49 : JREC (SEQUENTIAL ENTRY FOR THE PARTICULAR ISSUE)
!        K=50 : TOTAL NUMBER OF VALID RECORDS FOR STOCK ITEM I, UPDATED EACH TIME A NEW DAY IS PROCESSED
!        K=51 : SHORT MOVING AVERAGE OF THE SPREAD
!        K=52 : MEDIUM MOVING AVERAGE OF THE SPREAD
!        K=53 : LONG MOVING AVERAGE OF THE SPREAD
!        K=54 TO 100 NOT YET USED
!
!       PROFITFILE TRACKS THE EXISTENCE OF THE FILE PROFIT.DAT. pROFITLOADED TRACKS THE EXISTENCE
!       OF PROFIT DATA LOADED FROM THE PROFIT.DAT FILE
   LOGICAL PROFITFILE,PROFITLOADED
!
!       ASCII FILE TO PASS IN STOCK DATA IS COMMA DELIMITED FILE.
!       EACH ENTRY HAS:
!
!       SYMBOL          CHARACTER*8 (SYM)
!       OPENING PRICE   REAL*8
!       HI PRICE        REAL*8
!       LO PRICE        REAL*8
!       CLOSE PRICE     REAL*8
!       VOLUME          INTEGER*4
!       DATA(YYYMMDD)   INTEGER*4
!       PNAME           CHARACTER*80
!
!
   CHARACTER*8 SYM
   REAL*8 PROFITDATA
   DIMENSION PROFITDATA(:,:)
   ALLOCATABLE :: PROFITDATA
!
!       VARIABLES TO HOLD NUMBER OF DAYS TO BASE SHORT, MEDIUM AND LONG MOVING AVERAGES
   INTEGER SHORT_TIME,MEDIUM_TIME,LONG_TIME,BUY_DELAY,SELL_DELAY
!       (DEFAULTS 5,15,30,5,5)
!
!       MAXI=NUMBER OF RECORDS IN THE PROFIT.DAT FILE (MAX FILE SIZE)
!
!       MAXJ=LARGEST NUMBER OF ENTRIES FOR ANY ONE STOCK (MAX DAYS)
!
!       MAXK=MAXIMUM NUMBER OF ISSUES IN THE PROFIT.DAT FILE
   INTEGER MAXI,MAXJ,MAXK
!
!       BUY SIGNAL IS A POSITIVE DIVERGENCE. THE PRICE IS A LOWER LOW WHILE THE SPREAD IS A HIGHER HIGH
!
!       SELL SIGNAL ID A NEGATIVE DIVERGENCE. THE PRICE IS A HIGHER HIGH WHILE THE SPREAD IS MAKING LOWER HIGHS
!
!       FLAG TO CHECK THAT AN ISSUE IS LOADED BY LOADISSU
   LOGICAL ISSUE_LOADED
!
!
   INTEGER FIRSTDAY,LASTDAY,PDAYS,ENDDAY,STARTDAY
!
!
END MODULE PROFIT_GLOBAL
