!      THIS IS THE TWELFTH FILE OF RAYTRACING ROUTINES
!
! SUB REFRAY.FOR
SUBROUTINE REFRAY(WPAS)
   USE GLOBALS
   use mod_lens_data_manager
   use real_ray_trace
   use type_utils, only: real2str, int2str
!
   use DATLEN
   use DATMAI
   use mod_surface
   use mod_system, only: sys_scx, sys_scy, sys_scy_fang, sys_scx_fang, &
      sys_ray_aiming, sys_telecentric, sys_aim_offset_x, sys_aim_offset_y, &
      sys_aim_offset_z, sys_scy_fang_set, sys_scx_fang_set, &
      sys_rxim, sys_rxim_fang_set, sys_ryim, sys_ryim_fang_set, &
      sys_set_rxim, sys_set_rxim_fang_set, sys_set_scx_fang_set, sys_set_scy_fang_set
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE REFRAY.FOR. THIS SUBROUTINE IMPLEMENTS
!       THE TRACING OF THE GUT OR REFERENCE RAY. THIS IS INITIATED
!       BY THE FOB COMMAND.
!
   integer :: jj
   INTEGER NO,KKK,ISYS20,I,KKKK,N_HITS

   INTEGER IISURF,CAERAS,COERAS,IJKTOTAL,IJK,IFINISH
!
   real(real64) X,Y,Z,L,M,N,SNINDX,LOLD,MOLD,NOLD,WPAS &
   &,D21,D22,LS,SNIND2,YL,YM,YN,OXSTRT,OYSTRT,OLDCX,OLDCY,&
   &D11,D12,A10,STX,STY,STZ,XAHT,YAHT,NXAHT,NYAHT,MAG,&
   &LSTART,MSTART,NSTART,YANG,XANG,X1LAST,LARGE,WHT1,WHT2,&
   &Y1LAST,X1ONE,Y1ONE,RXLAST,RYLAST,RXONE,RYONE,DDELX,DDELY,&
   &YYANG,XXANG,MF1,MF2,DET,TARX,TARY,XFOBB0,YFOBB0,ZFOBB0 &
   &,ANGJK1,ANGJK2,XC1,YC1,ZC1,WWWW1,WWWW2,WWWW3,XCHIEF_TARGET &
   &,ZSAG,SCLFACY,SCLFACX,AWW1,AWW2,YCHIEF_TARGET,RAT,CX,CY &
   &,CX1LAST,CY1LAST,CX1ONE,CY1ONE,CRXLAST,CRYLAST,CRXONE,CRYONE,&
   &CD11,CD12,CD21,CD22,CDET,CDDELX,CDDELY,CMF1,CMF2
!
   real(real64) XRAYER,YRAYER,ZRAYER,STEPL,STEPL1,ERRORVEC
   COMMON/RAYERPASS/XRAYER,YRAYER,ZRAYER
!
   COMMON/STRSTR/STX,STY,STZ
!
   COMMON/OHFOB/XFOBB0,YFOBB0,ZFOBB0
!
   COMMON/CACO/CAERAS,COERAS,LS
!
!       FOBB0=TRUE FOR ON AXIS AND FALSE FOR OFF AXIS
   LOGICAL SAGERR,FOBB0,FOBB0X,FOBB0Y,NOCALL,CDELFAIL,DELFAIL
!
   COMMON/FFOOBB/FOBB0,FOBB0X,FOBB0Y
!

   !call logger%logText("Reference Ray Routine Started")

   KKKK=0
   KKK=0
   YAIMOL=0.0D0
   XAIMOL=0.0D0
   ZAIMOL=0.0D0
   DDELX=0.001D0
   DDELY=0.001D0
   CDDELX=0.0001D0*sys_scx()
   CDDELY=0.0001D0*sys_scy()
   IF(WC.EQ.'FOB') THEN
      IF(sys_scy_fang().EQ.0.0D0) THEN
         SCLFACY=1.0D0
      ELSE
         SCLFACY=(1.0D0/sys_scy_fang())
      END IF
      IF(sys_scx_fang().EQ.0.0D0) THEN
         SCLFACX=1.0D0
      ELSE
         SCLFACX=(1.0D0/sys_scx_fang())
      END IF
      AWW1=WW1/SCLFACY
      AWW2=WW2/SCLFACX
   END IF
   IF(WC.EQ.'FOBH') THEN
      SCLFACY=1.0D0
      SCLFACX=1.0D0
      AWW1=WW1/SCLFACY
      AWW2=WW2/SCLFACX
   END IF
!
   WWWW1=WW1
   WWWW2=WW2
   WWWW3=WW3
!
!
!     PROPER INITIALIZE PROCEEDURE 3/3/96
   R_X=0.0D0
   R_Y=0.0D0
   R_Z=0.0D0
   XOLD=0.0D0
   YOLD=0.0D0
   ZOLD=0.0D0
   LOLD=0.0D0
   MOLD=0.0D0
   NOLD=0.0D0
!
!       DDELX AND DDELY ARE THE INITIAL INCREMENTORS FOR THE
!       DERIVATIVE CALCULATION IN NEWTON-RAPHSON SEARCH FOR
!       CHIEF RAY AIMING.
!
!     THE CHECK FOR TILTED AND DECENTERD OBJECT SURFACE HERE WAS REMOVED
!     ON 10/11/94
   LARGE=999999.99D0
   X1ONE=LARGE
   Y1ONE=LARGE
   X1LAST=LARGE
   Y1LAST=LARGE
   CX1ONE=LARGE
   CY1ONE=LARGE
   CX1LAST=LARGE
   CY1LAST=LARGE
!
!       SET INITIAL VALUES FOR RXONE, RYONE, RXLAST AND RYLAST
   RXONE=LARGE
   RYONE=LARGE
   RXLAST=LARGE
   RYLAST=LARGE
   CRXONE=LARGE
   CRYONE=LARGE
   CRXLAST=LARGE
   CRYLAST=LARGE
!
!       THE FIRST THING TO DO IS TO DETERMINE THE STARTING
!       COORDINATES OF THE RAY AT THE OBJECT SURFACE. FIRST
!       CONSIDER THAT WW5 IS ZERO AND THERE IS NO RE-ASSIGNMENT
!       OF OBJECT,REFERENCE OR IMAGE.
!
!       THE RELATIVE OBJECT HEIGHTS ARE TRANSLATED INTO REAL
!       X,Y AND Z POSITIONS WITH RESPECT TO THE OBJECT SURFACE HERE.
!
!       WW1 IS THE FRACTIONAL Y- OBJECT HEIGHT
!       WW2 IS THE FRACTIONAL X- OBJECT HEIGHT
!       WW3 IS THE FRACTIONAL OBJECT DISPLACEMENT FROM THE OBJECT SURFACE
!               PLANE. (ALLOWS FOR DEFINITION OF CURVED OBJECTS)
!       EXPRESSED AS THE WW3 FRACTION OF THE OBJECT SURFACE THICKNESS
!       WW4 IS THE WAVELENGTH NUMBER (1 TO 5)
!       WW5 IS CURRENTLY ASSUMED TO BE ZERO.
!
!       THE STARTING RAY COORDINATES FOR THE RAY TRACE ARE:
!       (AT THE OBJECT SURFACE)
!
   IF(WC.EQ.'FOBH') THEN
!       OBJ ANGLES CANT BE INPUT
      call sys_set_scy_fang_set(0.0D0)
      call sys_set_scx_fang_set(0.0D0)
   END IF
   IF(sys_scy_fang_set().EQ.1.AND.NEWOBJ.EQ.0.OR.&
   &sys_scx_fang_set().EQ.1.AND.NEWOBJ.EQ.0) THEN
!     OBJECT ANGLES INPUT
      ANGIN=.TRUE.
!     REF OBJ HT INPUT AS ANGLE
!     IN THIS CASE, FOB INDICATES FRACTIONS OF FIELD ANGLES
!     BUT ONLY IF THE NEWOBJ SURFACE IS SURFACE 0
!
!     THIS NEEDS MODIFICATION FOR FRACTIONS OF FIELD ANGLES
!
!     ANGLES IN RADIANS ARE:
      ANGJK1=AWW1
      ANGJK2=AWW2
      CALL ADJUSTANGLEIFCLOSETO90(ANGJK1)
      CALL ADJUSTANGLEIFCLOSETO90(ANGJK2)

!
      YYANG=ANGJK1*PII/180.0D0
      XXANG=ANGJK2*PII/180.0D0
!
      IF(DABS(ANGJK1).GT.90.0D0) YSTRT=DTAN(YYANG)*surf_thickness(NEWOBJ)
      IF(DABS(ANGJK1).LE.90.0D0) YSTRT=-DTAN(YYANG)*surf_thickness(NEWOBJ)
!
      IF(DABS(ANGJK2).GT.90.0D0) XSTRT=DTAN(XXANG)*surf_thickness(NEWOBJ)
      IF(DABS(ANGJK2).LE.90.0D0) XSTRT=-DTAN(XXANG)*surf_thickness(NEWOBJ)

      ZSTRT=2.0D0*surf_thickness(NEWOBJ)

      IF(ANGJK1.GT.90.0D0.AND.ANGJK1.LT.270.0D0.OR.&
      &ANGJK1.LT.-90.0D0.AND.ANGJK1.GT.-270.0D0) THEN
!
         IF(ANGJK2.GT.90.0D0.AND.ANGJK2.LT.270.0D0.OR.&
         &ANGJK2.LT.-90.0D0.AND.ANGJK2.GT.-270.0D0) THEN
            ZSTRT=0.0D0
         END IF
      END IF
      IF(ANGJK2.GT.90.0D0.AND.ANGJK2.LT.270.0D0.OR.&
      &ANGJK2.LT.-90.0D0.AND.ANGJK2.GT.-270.0D0) THEN
!
         IF(ANGJK1.GT.90.0D0.AND.ANGJK1.LT.270.0D0.OR.&
         &ANGJK1.LT.-90.0D0.AND.ANGJK1.GT.-270.0D0) THEN
            ZSTRT=0.0D0
         END IF
      END IF
      IF(ANGJK1.GE.0.0D0.AND.ANGJK1.LT.90.0D0.OR.&
      &ANGJK1.LE.0.0D0.AND.ANGJK1.GT.-90.0D0.OR.&
      &ANGJK1.GT.270.0D0.AND.ANGJK1.LE.0.0D0.OR.&
      &ANGJK1.LT.-270.0D0.AND.ANGJK1.GE.0.0D0) THEN
!
         IF(ANGJK2.GE.0.0D0.AND.ANGJK2.LT.90.0D0.OR.&
         &ANGJK2.LE.0.0D0.AND.ANGJK2.GT.-90.0D0.OR.&
         &ANGJK2.GT.270.0D0.AND.ANGJK2.LE.0.0D0.OR.&
         &ANGJK2.LT.-270.0D0.AND.ANGJK2.GE.0.0D0) THEN
            ZSTRT=0.0D0
         END IF
      END IF
      IF(ANGJK2.GE.0.0D0.AND.ANGJK2.LT.90.0D0.OR.&
      &ANGJK2.LE.0.0D0.AND.ANGJK2.GT.-90.0D0.OR.&
      &ANGJK2.GT.270.0D0.AND.ANGJK2.LE.0.0D0.OR.&
      &ANGJK2.LT.-270.0D0.AND.ANGJK2.GE.0.0D0) THEN
!
         IF(ANGJK1.GE.0.0D0.AND.ANGJK1.LT.90.0D0.OR.&
         &ANGJK1.LE.0.0D0.AND.ANGJK1.GT.-90.0D0.OR.&
         &ANGJK1.GT.270.0D0.AND.ANGJK1.LE.0.0D0.OR.&
         &ANGJK1.LT.-270.0D0.AND.ANGJK1.GE.0.0D0) THEN
            ZSTRT=0.0D0
         END IF
      END IF
      IF(sys_scy_fang_set().EQ.1.0D0.AND.sys_scy_fang().EQ.0.0D0) YSTRT=0.0D0
      IF(sys_scx_fang_set().EQ.1.0D0.AND.sys_scx_fang().EQ.0.0D0) XSTRT=0.0D0
      IF(XSTRT.EQ.0.0D0.AND.YSTRT.EQ.0.0D0) ZSTRT=0.0D0
   ELSE
!     OBJECT ANGLES NOT INPUT
      ANGIN=.FALSE.
!
      IF(surf_clap_type(NEWOBJ) == 0.OR.sys_rxim_fang_set().NE.0.0D0 &
      &.OR.sys_ryim_fang_set().NE.0.0D0.OR.surf_array_parity(NEWOBJ) /= 0) THEN
!     THE STARTING RAY COORDINATES ON THE OBJECT SURAFCE
!     ARE NOT DETERMINED BY THE CLAP ON THE OBJECT SURFACE
!     USING SCY AND SCX, FOB REPRESENTS FRACTIONS OF IMAGE HEIGHT
!     AND DEPTH.
         IF(sys_scx().NE.0.0D0) XSTRT=WW2*PXTRAX(5,NEWOBJ)
         IF(sys_scx().EQ.0.0D0) XSTRT=0.0D0
         IF(sys_scy().NE.0.0D0) YSTRT=WW1*PXTRAY(5,NEWOBJ)
         IF(sys_scy().EQ.0.0D0) YSTRT=0.0D0
         IF(sys_rxim_fang_set().NE.0.0D0.OR.sys_ryim_fang_set().NE.0.0D0) THEN
            XSTRT=XSTRT+XRAYER
            YSTRT=YSTRT+YRAYER
         END IF
         IISURF=NEWOBJ
         CALL SAGRET(IISURF,XSTRT,YSTRT,ZSAG,SAGERR)
         IF(SAGERR) CALL HANDLESAGRETFAILURE(MSG, NEWOBJ)

         ZSTRT=(WW3*surf_thickness(NEWOBJ))+ZSAG
      ELSE
!     USE Y HEIGHT OF CLAP WITH OFFSETS
         IF(surf_clap_type(NEWOBJ) == 1.AND.&
         &surf_array_parity(NEWOBJ) == 0) THEN
            IF(surf_clap_dim(NEWOBJ, 1).LE.surf_clap_dim(NEWOBJ, 2)) THEN
               XSTRT=WW2*(surf_clap_dim(NEWOBJ, 1)+surf_clap_dim(NEWOBJ, 4))
               YSTRT=WW1*(surf_clap_dim(NEWOBJ, 1)+surf_clap_dim(NEWOBJ, 3))
            ELSE
               XSTRT=WW2*(surf_clap_dim(NEWOBJ, 2)+surf_clap_dim(NEWOBJ, 4))
               YSTRT=WW1*(surf_clap_dim(NEWOBJ, 2)+surf_clap_dim(NEWOBJ, 3))
            END IF
            IISURF=NEWOBJ
            CALL SAGRET(IISURF,XSTRT,YSTRT,ZSAG,SAGERR)
            IF(SAGERR) CALL HANDLESAGRETFAILURE(MSG, NEWOBJ)

            ZSTRT=(WW3*surf_thickness(NEWOBJ))+ZSAG
         END IF
         IF(surf_clap_type(NEWOBJ) == 5.AND.surf_array_parity(NEWOBJ) == 0) THEN
            XSTRT=WW2*(surf_clap_dim(NEWOBJ, 1)+surf_clap_dim(NEWOBJ, 4))
            YSTRT=WW1*(surf_clap_dim(NEWOBJ, 1)+surf_clap_dim(NEWOBJ, 3))
            IISURF=NEWOBJ

            CALL SAGRET(IISURF,XSTRT,YSTRT,ZSAG,SAGERR)
            IF(SAGERR) CALL HANDLESAGRETFAILURE(MSG, NEWOBJ)

            ZSTRT=(WW3*surf_thickness(NEWOBJ))+ZSAG
         END IF
         IF(surf_clap_type(NEWOBJ) == 6.AND.surf_array_parity(NEWOBJ) == 0) THEN
            XSTRT=WW2*(surf_clap_dim(NEWOBJ, 2)+surf_clap_dim(NEWOBJ, 4))
            YSTRT=WW1*(surf_clap_dim(NEWOBJ, 2)+surf_clap_dim(NEWOBJ, 3))
            IISURF=NEWOBJ

            CALL SAGRET(IISURF,XSTRT,YSTRT,ZSAG,SAGERR)
            IF(SAGERR) CALL HANDLESAGRETFAILURE(MSG, NEWOBJ)

            ZSTRT=(WW3*surf_thickness(NEWOBJ))+ZSAG
         END IF
         IF(surf_clap_type(NEWOBJ) > 1.AND.surf_clap_type(NEWOBJ) <= 4.AND.&
         &surf_array_parity(NEWOBJ) == 0) THEN
            XSTRT=WW2*(surf_clap_dim(NEWOBJ, 2)+surf_clap_dim(NEWOBJ, 4))
            YSTRT=WW1*(surf_clap_dim(NEWOBJ, 1)+surf_clap_dim(NEWOBJ, 3))
            IISURF=NEWOBJ

            CALL SAGRET(IISURF,XSTRT,YSTRT,ZSAG,SAGERR)
            IF(SAGERR) CALL HANDLESAGRETFAILURE(MSG, NEWOBJ)

            ZSTRT=(WW3*surf_thickness(NEWOBJ))+ZSAG
         END IF
      END IF
   END IF
!
!               XSTRT,YSTRT AND ZSTRT HAVE BEEN INITIALLY SET
!
!               NOW CALCULATE THE TARGET FOR THE CHIEF RAY IF RXIM AND RYIM
!               ARE IN EFFECT.
!
!       THE WAVELENGTH NUMBER FOR THE REFERENCE RAY TRACE IS:
!       INT(WW4) OR INT(SYSTEM(11))
!     CALC AIM POINTS IF RYIM OR RXIM ARE IN EFFECT
   IF(sys_ryim_fang_set().NE.sys_rxim_fang_set())&
   &call sys_set_rxim_fang_set(sys_ryim_fang_set())
   IF(sys_ryim_fang_set().NE.sys_rxim_fang_set())&
   &call sys_set_rxim(sys_ryim())
   XCHIEF_TARGET=0.0D0
   YCHIEF_TARGET=0.0D0
   IF(sys_rxim_fang_set().NE.0.0D0) THEN
      XCHIEF_TARGET=(WW2*sys_rxim())
   END IF
   IF(sys_ryim_fang_set().NE.0.0D0) THEN
      YCHIEF_TARGET=(WW1*sys_ryim())
   END IF


!
!                       THE CHIEF RAY TARGETS HAVE BEEN COMPUTED
!
9898 CONTINUE
   KKKK=KKKK+1
   KKK=0

!     THE ABOVE CONTINUATION IS THE RE-ENTRY POINT FOR CHIEF RAY
!     ITERATION
!
!       NOW WHAT ARE THE STARTING DIRECTION COSINES AND HOW ARE
!       THEY DETERMINED?
!
!     STARTING POINTS AT SURFACE NEWOBJ+1 ARE THE PARAXIAL VALUES
!     MODULATED BY ANY DECENTER OR TILT ON NEWOBJ+1
!
   IF(sys_ray_aiming().EQ.0.0D0) THEN
!     RAY AIMING IS OFF
      IF(sys_telecentric().EQ.0.0D0) THEN
!     TEL OFF
         X1AIM=PXTRAX(5,(NEWOBJ+1))
         X1AIM=(X1AIM*WW2)-surf_decenter_x(NEWOBJ+1)+sys_aim_offset_x()
         Y1AIM=PXTRAY(5,(NEWOBJ+1))
         Y1AIM=(Y1AIM*WW1)-surf_decenter_y(NEWOBJ+1)+sys_aim_offset_y()
         Z1AIM=sys_aim_offset_z()
      ELSE
!     TEL ON,ALL RAYS ARE PARALLEL
         call logger%logText("Telecentric Ray Aiming On!")
         IF(sys_scx().NE.0.0D0) X1AIM=XSTRT
         IF(sys_scx().EQ.0.0D0) X1AIM=0.0D0
         IF(sys_scy().NE.0.0D0) Y1AIM=YSTRT
         IF(sys_scy().EQ.0.0D0) Y1AIM=0.0D0
         Z1AIM=0.0D0
      END IF
   ELSE
!     RAY AIMING IS ON
      !PRINT *, "TRYY = ", TRYY
      !PRINT *, "YFOBB0 = ", YFOBB0


      X1AIM=TRYX+XFOBB0
      Y1AIM=TRYY+YFOBB0
      Z1AIM=TRYZ+ZFOBB0
   END IF

   XC=X1AIM
   YC=Y1AIM
   ZC=Z1AIM
!     SAVE VERY FIRST X1AIM,Y1AIM, Z1AIM
   STX=X1AIM
   STY=Y1AIM
   STZ=Z1AIM
!     CALL BAKONE TO CONVERT TO NEWOBJ COORDINATES
   !IF (KKK.EQ.1) THEN
   !PRINT *, "YAIMOL LINE 445 is ", YAIMOL
   !PRINT *, "YC LINE 445 is ", YC
   !END IF

   XAIMOL=XC
   YAIMOL=YC
   ZAIMOL=ZC
   R_TX=X1AIM
   R_TY=Y1AIM
   R_TZ=Z1AIM
   CALL BAKONE
   X1AIM=R_TX
   Y1AIM=R_TY
   Z1AIM=R_TZ
!       NOW THE COORDINATES ARE IN THE NEWOBJ COORD SYSTEM
!
!       FOR NOW, IGNORE THE FOLLOWING:
!               1) CLAPS/COBS AND ERASES
!       NOW THE STARTING DIRECTION COSINES ARE RELATIVELY SIMPLE.
!
!       THEY ARE CALLED LSTART,MSTART AND NSTART
!
!       FIRST CONVERT THE SURFACE 0 AND 1 COORDINATES INTO YANG AND XANG
!       ANGULAR VALUES AS IN HEXAGON AND CODE V.
!       YANG AND XANG ANGLES IN RADIANS.
   STOPP=0
   REFEXT=.TRUE.
!
!       THE STARTING COORDINATES AND DIRECTION COSINES FOR THE VERY
!       FIRST PART OF THE CHIEF OR "GUT" RAY TRACE HAVE BEEN CALCULATED
!       BASED UPON THE RESULTS OF THE CURRENT PARAXIAL RAY TRACE AND
!       ASSUMING THAT SURFACE NEWOBJ+1 IS PLANO.
!
!       NEXT STEPS
!
!       1. TRANSLATE TO THE NEXT SURFACE
!       2. IF THAT SURFACE IS TILTED AND/OR DECENTERED,
!          TRANSFORM TO THAT SURFACES COORDINATE SYSTEM.
!       3. INTERSECT THE SURFACE
!       4. INTERACT WITH THAT SURFACE
!       5. REPEAT STEP 1.
!
!       1. TRANSFER TO NEXT SURFACES COORDINATE SYSTEM LOCATED
!       AT THE NEXT SURFACES VERTEX (THIS INCLUDES THE AXIAL THICKNESS).
!       AND TILTS AND DECENTERS.
!
!       CALL TRANSF
!
!       2. INTERSECT AND INTERACT
!
!       CALL HITSUR
!
!       3. REPEAT WITH A DO LOOP
!
!       STORE THE REFERENCE RAY DATA FOR SURFACE 0 IN THE ARRAY
!       REFRY(1:50,0:MAXSUR)
!
!       KKK COUNTS THE NUMBER OF TRIES TO GET A GOOD REFERENCE
!       SURFACE ZERO POINT INTERSECTION AND LABEL 9 IS THE RE-ENTRY POINT
!
!
!       THIS IS THE RE-ENTRY POINT FOR RAY AIMING. RE-ENTRY
!       IS PERFORMED AFTER NEW VALUES OF X1AIM AND Y1AIM WERE
!       CALCULATED JUST BEFORE ENCOUNTERING THE (GO TO 9)
!       STATEMENT NEAR THE END OF THIS ROUTINE.
9  CONTINUE
   RV=.FALSE.
   KKK=KKK+1

!       IF KKK EXCEEDS NRAITR TRIES, PRINT RAY ITERRATION ERROR
!       AND STOP SEARCHING.
   IF(KKK.GT.NRAITR) THEN
      !OUTLYNE = "GOING TO SEND REF RAY FAILURE 511"
      !CALL SHOWIT(19)
!                   PRINT *, "KKK is ", KKK
!                   WRITE(OUTLYNE, *), "ERROR VECTOR IS ",
!     1   DSQRT(((CX-XCHIEF_TARGET)**2)+((CY-YCHIEF_TARGET)**2))
!                   CALL SHOWIT(19)
      GO TO 14
   ELSE
      STOPP=0
      REFEXT=.TRUE.
!        PROCEED
   END IF
!
!     COMPUTE DIR COS DIRECTLY FROM POSITIONS
   MAG=DSQRT(((XSTRT-X1AIM)**2)+((YSTRT-Y1AIM)**2)&
   &+((ZSTRT-Z1AIM)**2))
   LSTART=(X1AIM-XSTRT)/MAG
   MSTART=(Y1AIM-YSTRT)/MAG
   NSTART=(Z1AIM-ZSTRT)/MAG
   NINTY=.FALSE.
   IF(NSTART.LT.0.0D0) NINTY=.TRUE.
   IF(NINTY) RVSTART=.TRUE.
   IF(NSTART.EQ.0.0D0) THEN
      YANG=PII/2.0D0
      XANG=PII/2.0D0
   ELSE
      IF(DABS(NSTART).EQ.0.0D0) THEN
         YANG=0.0D0
      ELSE
         YANG=DATAN2(MSTART,NSTART)
      END IF
      IF(DABS(NSTART).EQ.0.0D0) THEN
         XANG=0.0D0
      ELSE
         XANG=DATAN2(LSTART,NSTART)
      END IF
   END IF
   IF(NSTART.EQ.0.0D0) THEN
      YYANG=PII/2.0D0
      XXANG=PII/2.0D0
   ELSE
      IF(DABS(NSTART).EQ.0.0D0) THEN
         YYANG=0.0D0
      ELSE
         YYANG=DATAN2(MSTART,NSTART)
      END IF
      IF(DABS(NSTART).EQ.0.0D0) THEN
         XXANG=0.0D0
      ELSE
         XXANG=DATAN2(LSTART,NSTART)
      END IF
   END IF
!
!       FOR SURFACE NEWOBJ
!       REFRY(1,SURF)=X(LOCAL)- COORDINATE AT SURFACE I
!       REFRY(2,SURF)=Y(LOCAL)- COORDINATE AT SURFACE I
!       REFRY(3,SURF)=Z(LOCAL)- COORDINATE AT SURFACE I
!       REFRY(4,SURF)=L(LOCAL)- DIRECTION COSINE AT SURFACE I
!       REFRY(5,SURF)=M(LOCAL)- DIRECTION COSINE AT SURFACE I
!       REFRY(6,SURF)=N(LOCAL)- DIRECTION COSINE AT SURFACE I
!       REFRY(8,SURF)=LEN - PHYSICAL LENGTH ALONG RAY FROM SURF I-1 TO I
!       REFRY(7,SURF)=OPL - OPL FROM SURFACE I-1 TO I
!       REFRY(9,SURF)=COSINE(I)
!       REFRY(10,SURF)=COSINE(IP)
!       REFRY(11,SURF)=UX - (RADIAN) MARGINAL XZ SLOPE ANGLE
!       REFRY(12,SURF)=UY - (RADIAN) MARGINAL YZ SLOPE ANGLE
!       REFRY(13,SURF)=LN - SURFACE NORMAL DIRECTION COSINE
!       REFRY(14,SURF)=MN - SURFACE NORMAL DIRECTION COSINE
!       REFRY(15,SURF)=NN - SURFACE NORMAL DIRECTION COSINE
!       REFRY(16,SURF)=XOLD
!       REFRY(17,SURF)=YOLD
!       REFRY(18,SURF)=ZOLD
!       REFRY(19,SURF)=LOLD
!       REFRY(20,SURF)=MOLD
!       REFRY(21,SURF)=NOLD
!       REFRY(22,SURF)=OPL - OPL FROM SURFACE NEWOBJ TO I
!       REFRY(23,SURF)=1.00 FOR NOT REV, -1.00 FOR REV
!       REFRY(24,SURF)=1.0D0 FOR POSITIVE RAY, -1 FOR NEGATIVE RAY
!       REFRY(25,SURF)=FOB INTENSITY
!       REFRY(26 TO 31) ARE THE L,M AND N DIR COS OF THE RAY X AND Y
!       POINTER DIRECTIONS
!       REFRY(32,SURF) = WAVELENGTH NUMBER
!       REFRY(33,SURF) TO REFRY(35,SURF) RESERVED
   REFRY(25,NEWOBJ)=WPAS
   REFRY(32,NEWOBJ)=WW4
!       TRACK INTENSITY FOR ILLUMINATION RAY TRACING
   IF(WC.EQ.'IFOB') REFRY(25,NEWOBJ)=WW5
   REFRY(1,NEWOBJ)=XSTRT
   REFRY(2,NEWOBJ)=YSTRT
   REFRY(3,NEWOBJ)=ZSTRT
   REFRY(4,NEWOBJ)=LSTART
   REFRY(5,NEWOBJ)=MSTART
   REFRY(6,NEWOBJ)=NSTART
   REFRY(7,NEWOBJ)=0.0D0
   REFRY(8,NEWOBJ)=0.0D0
   SNIND2=DABS(ldm%getSurfIndex(NEWOBJ, INT(WW4)))/ldm%getSurfIndex(NEWOBJ, INT(WW4))
   IF(SNIND2.GT.0.0D0) REFRY(24,NEWOBJ)=1.0D0
   IF(SNIND2.LT.0.0D0) REFRY(24,NEWOBJ)=-1.0D0
   IF(SNIND2.GT.0.0D0) POSRAY=.TRUE.
   IF(SNIND2.LT.0.0D0) POSRAY=.FALSE.
   REFRY(9,NEWOBJ)=NSTART
   REFRY(10,NEWOBJ)=NSTART
   REFRY(11,NEWOBJ)=XXANG
   IF((REFRY(11,NEWOBJ)).LT.0.0D0)&
   &REFRY(11,NEWOBJ)=REFRY(11,NEWOBJ)+(TWOPII)
   REFRY(12,NEWOBJ)=YYANG
   IF((REFRY(12,NEWOBJ)).LT.0.0D0)&
   &REFRY(12,NEWOBJ)=REFRY(12,NEWOBJ)+(TWOPII)
   REFRY(13,NEWOBJ)=0.0D0
   REFRY(14,NEWOBJ)=0.0D0
   REFRY(15,NEWOBJ)=1.0D0
   REFRY(16,NEWOBJ)=XSTRT
   REFRY(17,NEWOBJ)=YSTRT
   REFRY(18,NEWOBJ)=ZSTRT
   REFRY(19,NEWOBJ)=LSTART
   REFRY(20,NEWOBJ)=MSTART
   REFRY(21,NEWOBJ)=NSTART
   REFRY(22,NEWOBJ)=0.0D0
   IF(surf_thickness(NEWOBJ).LT.0.0D0) REVSTR=.TRUE.
   IF(surf_thickness(NEWOBJ).GE.0.0D0) REVSTR=.FALSE.
!
   X=XSTRT
   Y=YSTRT
   Z=ZSTRT
   L=LSTART
   M=MSTART
   N=NSTART
   ISYS20=NEWIMG
   I=0
   GO TO 13
!       GO TO 14 IS THE ESCAPE FOR A FAILED RAY
!       GO TO 16 IS THE NON-ESCAPE ROUTE
14 CONTINUE
!     NO REFERENCE RAY SOLUTION, REF RAY FAILURE
   STOPP=1
   RAYCOD(1)=8
   RAYCOD(2)=I
   IF (KKK.EQ.10) THEN
      OUTLYNE = "SETTING CHIEF RAY TO FALSE 647"
      CALL SHOWIT(19)
   END IF
   REFEXT=.FALSE.
   IF(.NOT.NULL) FOBYES=.FALSE.
   IF(.NOT.NULL.AND.F34.EQ.0) CALL MACFAL
   RETURN
13 CONTINUE
   STOPP=0
   REFEXT=.TRUE.
!     HERE BEGINS A LOOP TO FIND VALUES OF TRYX AND TRYY
!     WHICH ARE BETTER THAN THE ONES BASED ON THE PARAXIAL TRACE
!     TEMP SET NOREF TO .TRUE. SO ERROR MESSAGE IS ISSUED
!
   DO 10 I=(NEWOBJ+1),ISYS20
      IF (I.EQ.0) THEN
         !call logger%logText("Ray Aiming Surface 0")
         !call logger%logTextWithNum("X Start is ", X)
         !call logger%logTextWithNum("Y Start is ", Y)
      END IF


!
!       WE ARE CURRENTLY AT SURFACE I-1 AND KNOW WHERE
!       WE ARE AND WHICH DIRECTION WE WANT TO GO.
!       CALLING TRANSFS.FOR TRANSFORMS THE X,Y,Z,L,M AND N INTO
!       THE COORDINATE SYSTEM OF SURFACE I,FOB0 TRACKS IF FOB 0 IS
!       USED OR FOB (SOMETHING NON-ZERO)
      R_X=X
      R_Y=Y
      R_Z=Z
      R_L=L
      R_M=M
      R_N=N
      R_I=I
      CALL TRANSF
      X=R_X
      Y=R_Y
      Z=R_Z
      L=R_L
      M=R_M
      N=R_N
      IF(NSTART.EQ.0.0D0) THEN
         YANG=PII/2.0D0
         XANG=PII/2.0D0
      ELSE
         IF(DABS(NSTART).EQ.0.0D0)THEN
            YANG=0.0D0
         ELSE
            YANG=DATAN2(MSTART,NSTART)
         END IF
         IF(DABS(NSTART).EQ.0.0D0)THEN
            XANG=0.0D0
         ELSE
            XANG=DATAN2(LSTART,NSTART)
         END IF
      END IF
      STOPP=0
      REFEXT=.TRUE.
!       NOW INTERSECT THE SURFACE I
!       THE COORDINATES OF THE CURRENT RAY AT SURF I-1 IN THE COORDINATE
!       SYSTEM OF SURFACE I ARE XOLD,YOLD AND ZOLD.
!
      XOLD=X
      YOLD=Y
      ZOLD=Z
      LOLD=L
      MOLD=M
      NOLD=N
!
      R_X=X
      R_Y=Y
      R_Z=Z
      R_L=L
      R_M=M
      R_N=N
      R_I=I
      R_XAIM=XAIMOL
      R_YAIM=YAIMOL
      R_ZAIM=ZAIMOL
      IF(REFRY(24,R_I-1).GT.0.0D0) POSRAY=.TRUE.
      IF(REFRY(24,R_I-1).LT.0.0D0) POSRAY=.FALSE.
      MSG=.FALSE.
      CALL HITSUR
      MSG=.TRUE.
      IF(STOPP.EQ.1) THEN
         !call logger%logTextWithNum("Failed to hit surface",I)
         REFEXT=.FALSE.
         RETURN
      END IF
      X=R_X
      Y=R_Y
      Z=R_Z
      L=R_L
      M=R_M
      N=R_N
      IF(NSTART.EQ.0.0D0) THEN
         YANG=PII/2.0D0
         XANG=PII/2.0D0
      ELSE
         IF(DABS(NSTART).EQ.0.0D0) THEN
            YANG=0.0D0
         ELSE
            YANG=DATAN2(MSTART,NSTART)
         END IF
         IF(DABS(NSTART).EQ.0.0D0) THEN
            XANG=0.0D0
         ELSE
            XANG=DATAN2(LSTART,NSTART)
         END IF
      END IF
      IF(RV) REFRY(23,I)=-1.0D0
      IF(.NOT.RV) REFRY(23,I)=1.0D0
!       LOAD REF RAY REGISTERS
!       FOR SURFACE NEWOBJ
!       REFRY(1,SURF)=X(LOCAL)- COORDINATE AT SURFACE I
!       REFRY(2,SURF)=Y(LOCAL)- COORDINATE AT SURFACE I
!       REFRY(3,SURF)=Z(LOCAL)- COORDINATE AT SURFACE I
!       REFRY(4,SURF)=L(LOCAL)- DIRECTION COSINE AT SURFACE I
!       REFRY(5,SURF)=M(LOCAL)- DIRECTION COSINE AT SURFACE I
!       REFRY(6,SURF)=N(LOCAL)- DIRECTION COSINE AT SURFACE I
!       REFRY(8,SURF)=LEN - PHYSICAL LENGTH ALONG RAY FROM SURF I-1 TO I
!       REFRY(7,SURF)=OPL - OPL FROM SURFACE I-1 TO I
!       REFRY(9,SURF)=COSINE(I)
!       REFRY(10,SURF)=COSINE(IP)
!       REFRY(11,SURF)=UX - (RADIAN) MARGINAL XZ SLOPE ANGLE
!       REFRY(12,SURF)=UY - (RADIAN) MARGINAL YZ SLOPE ANGLE
!       REFRY(13,SURF)=L DIRECTION COSINE OF SURFACE NORMAL
!       REFRY(14,SURF)=M DIRECTION COSINE OF SURFACE NORMAL
!       REFRY(15,SURF)=N DIRECTION COSINE OF SURFACE NORMAL
!       REFRY(16,SURF)=XOLD
!       REFRY(17,SURF)=YOLD
!       REFRY(18,SURF)=ZOLD
!       REFRY(19,SURF)=LOLD
!       REFRY(20,SURF)=MOLD
!       REFRY(21,SURF)=NOLD
!     THESE LAST 6 ITEMS ARE THE COORDINATES OF THE RAY AT
!     SURFACE I-1 IN THE COORDINATE SYSTEM OF SURFACE I
!       REFRY(22,SURF)=OPL - OPL FROM SURFACE NEWOBJ TO I
!       REFRY(23,SURF)=1.00 FOR NOT REV, -1.00 FOR REV
!       REFRY(24,SURF)=1.0D0 FOR POSITIVE RAY, -1 FOR NEGATIVE RAY
!       REFRY(25,SURF)=FOB INTENSITY
      REFRY(32,I)=WW4
!       REFRY(33,SURF) TO REFRY(35,SURF) RESERVED
      REFRY(25,I)=REFRY(25,I-1)
      REFRY(1,I)=X
      REFRY(2,I)=Y
      REFRY(3,I)=Z
      REFRY(4,I)=L
      REFRY(5,I)=M
      REFRY(6,I)=N
!       if(Y.NE.0.0D0) then
!          call LogTermFOR("Y is "
!      1    //int2str(I)// "= "//real2str(REFRY(2,I)))

!       end if
!       if(Z.NE.0.0D0) then
!          call LogTermFOR("Z is "
!      1    //int2str(I)// "= "//real2str(REFRY(3,I)))

!       end if
!       if(X.NE.0.0D0) then
!          call LogTermFOR("X is "
!      1    //int2str(I)// "= "//real2str(REFRY(1,I)))

!       end if

!
!     WHAT IS THE SIGN OF THE INDEX IN THE I-1 SPACE
      SNINDX=DABS(ldm%getSurfIndex(I-1, INT(WW4)))/ldm%getSurfIndex(I-1, INT(WW4))
      SNIND2=DABS(ldm%getSurfIndex(I, INT(WW4)))/ldm%getSurfIndex(I, INT(WW4))
!
!
!     PHYSICAL LENGTH OF THE RAY FROM I-1 TO I IS THE MAG OF THE
!     DIST TRAVELED TIME THE SNINDX (REVERSED IN SIGN IF RV) IN THE SPACE
!     FROM I-1 TO I
      IF(NUMHITS(I-1).EQ.1.AND.I.GE.1) THEN
         REFRY(8,I)=DSQRT(&
         &((REFRY(3,I)-ZOLD)**2)+((REFRY(2,I)-YOLD)**2)&
         &+((REFRY(1,I)-XOLD)**2))
      ELSE
!       NUMHITS STORED ON LAST SURFACE WAS GREATER THAN 1
         REFRY(8,I)=0.0D0
!       I-1 WAS AN NSS
         XOLD=0.0D0
         YOLD=0.0D0
         ZOLD=0.0D0
         DO N_HITS=1,NUMHITS(I-1)
            STEPL=DSQRT(&
            &(((MULTIREF_DATA(3,I-1,N_HITS))-ZOLD)**2)+&
            &(((MULTIREF_DATA(2,I-1,N_HITS))-YOLD)**2)+&
            &(((MULTIREF_DATA(1,I-1,N_HITS))-XOLD)**2)&
            &)
            IF(N_HITS.EQ.1) STEPL1=STEPL
            REFRY(8,I)=RAYRAY(8,I)+STEPL
!       CREATE NEW XOLD,YOLD,ZOLD
            XOLD=MULTIREF_DATA(1,I-1,N_HITS)
            YOLD=MULTIREF_DATA(2,I-1,N_HITS)
            ZOLD=MULTIREF_DATA(3,I-1,N_HITS)
         END DO
         REFRY(8,I)=REFRY(8,I)-STEPL1
      END IF
!
!     IF THE RAY HAS NO Z-COMPONENT THEN ITS SIGN IS ASSUMED TO BE
!     NEGATIVE IF THE INDEX IS NEGATIVE UNLESS IT IS A REVERSING RAY
      IF(RV) REFRY(8,I)=-REFRY(8,I)
      IF(.NOT.RV) REFRY(8,I)=REFRY(8,I)
!
      IF(SNIND2.GT.0.0D0) REFRY(24,I)=1.0D0
      IF(SNIND2.LT.0.0D0) REFRY(24,I)=-1.0D0
!
      IF(GLANAM(I-1,2).EQ.'PERFECT      ') THEN
         REFRY(7,I)=0.0D0
         REFRY(8,I)=0.0D0
      END IF
      IF(GLANAM(I-1,2).EQ.'IDEAL        ') THEN
         REFRY(8,I)=-(surf_ideal_efl(I-1)-surf_thickness(I-1))*REFRY(6,I-1)
      END IF
      REFRY(7,I)=REFRY(8,I)*DABS(ldm%getSurfIndex(I-1, INT(WW4)))
      IF(.NOT.RV) REFRY(7,I)=REFRY(7,I)+PHASE
      IF(RV) REFRY(7,I)=REFRY(7,I)-PHASE
      !print *, "REFRY(8,I) is ", REFRY(8,I)
      !print *, "REFRY(7,I) is ", REFRY(7,I)

!
      REFRY(9,I)=COSI
      REFRY(10,I)=COSIP
      IF(L.EQ.0.0D0) THEN
         IF(N.GE.0.0D0) REFRY(11,I)=0.0D0
         IF(N.LT.0.0D0) REFRY(11,I)=PII
      ELSE
         IF(DABS(L).GE.DABS(1.0D35*N)) THEN
            IF(L.GE.0.0D0) REFRY(11,I)=PII/2.0D0
            IF(L.LT.0.0D0) REFRY(11,I)=(3.0D0*PII)/2.0D0
         ELSE
            IF(DABS(N).EQ.0.0D0) THEN
               REFRY(11,I)=0.0D0
            ELSE
               REFRY(11,I)=DATAN2(L,N)
            END IF
            IF((REFRY(11,I)).LT.0.0D0)&
            &REFRY(11,I)=REFRY(11,I)+(TWOPII)
         END IF
      END IF
      IF(M.EQ.0.0D0) THEN
         IF(N.GE.0.0D0) REFRY(12,I)=0.0D0
         IF(N.LT.0.0D0) REFRY(12,I)=PII
      ELSE
         IF(DABS(M).GE.DABS(1.0D35*N)) THEN
            IF(M.GE.0.0D0) REFRY(12,I)=PII/2.0D0
            IF(M.LT.0.0D0) REFRY(12,I)=(3.0D0*PII)/2.0D0
         ELSE
            IF(DABS(N).EQ.0.0D0) THEN
               REFRY(12,I)=0.0D0
            ELSE
               REFRY(12,I)=DATAN2(M,N)
            END IF
            IF((REFRY(12,I)).LT.0.0D0)&
            &REFRY(12,I)=REFRY(12,I)+(TWOPII)
         END IF
      END IF
      REFRY(13,I)=LN
      REFRY(14,I)=MN
      REFRY(15,I)=NN
      REFRY(16,I)=XOLD
      REFRY(17,I)=YOLD
      REFRY(18,I)=ZOLD
      REFRY(19,I)=LOLD
      REFRY(20,I)=MOLD
      REFRY(21,I)=NOLD
      REFRY(22,I)=REFRY(22,(I-1))+REFRY(7,I)
      IF(STOPP.EQ.1.AND.KKKK.NE.0.AND.KKKK.GE.NRAITR) THEN
         OUTLYNE = "GOING TO SEND REF RAY FAILURE 904"
         CALL SHOWIT(19)
         GO TO 14
      ELSE
         STOPP=0
         REFEXT=.TRUE.
      END IF
      ! if(DABS(REFRY(7,I)) > .01 ) then
      ! call LogTermFOR("XOLD "//real2str(XOLD))
      ! call LogTermFOR("YOLD "//real2str(YOLD))
      ! call LogTermFOR("ZOLD "//real2str(ZOLD))
      ! call LogTermFOR("X "//real2str(REFRY(1,I)))
      ! call LogTermFOR("Y "//real2str(REFRY(2,I)))
      ! call LogTermFOR("Z "//real2str(REFRY(3,I)))
      ! call LogTermFOR("OPL "//real2str(REFRY(7,I)))
      ! call LogTermFOR("LEN "//real2str(REFRY(8,I)))
      ! end if

      if(I == ISYS20 .AND. ldm%getSurfThi(I) .NE. 0) then
!          do jj=1,I
!          call LogTermFOR("X "//int2str(jj)//
!      1  "= "//real2str(REFRY(1,jj)))
!          call LogTermFOR("Y "//int2str(jj)//
!      1  "= "//real2str(REFRY(2,jj)))
!          call LogTermFOR("Z "//int2str(jj)//
!      1  "= "//real2str(REFRY(3,jj)))
!          call LogTermFOR("OPL "//int2str(jj)//
!      1   "= "//real2str(REFRY(7,jj)))
!           end do

!                 call LogTermFOR("About to adjust REFRY")
         call adjustLastSurface_2(I, REFRY)
         ! call LogTermFOR("Done with adjusting REFRY")

      end if
!
!       CHECK THE RAY HEIGHT AT
!       NEWR AND ADJUST THE Y1AIM AND X1AIM AT SURFACE
!       NEWOBJ+1 SO THAT THE RAY HEIGHT AT NEWR IS WITHIN
!       AIMTOL . MAXIMUN NUMBER OF ITERRATIONS IS
!       NRAITR. (DEFAULT IS 100). DEFAULT AIMTOL IS 1.0D-6.
!
      !PRINT *, "AIMTOL = ", AIMTOL
      !PRINT *, "CAIMTOL = ", CAIMTOL

      IF(I.EQ.NEWREF) THEN
!       CALCULATE TARX AND TARY
         IF(surf_clap_type(I) >= 1.AND.surf_clap_type(I) <= 6.AND.&
         &surf_array_parity(I) == 0) THEN
!       REF SURF HAS CLAP ON IT
!       SET TARGET TO CENTER OF DECENTERED CLAP,
!
!       surf_clap_dim(I, 3) AND surf_clap_dim(I, 4) ARE CLAP DECENTRATIONS
!       HERE IS WERE THE TARGET FOR RAY AIMING IS SET FOR THE
!       CHIEF RAY. A SIMILAR BUT MORE COMPLEX SETTING IS REQUIRED
!       FOR NON-CHIEF RAYS IN THE SUBROUTINE RAYTRA.FOR
!
            TARY=surf_clap_dim(I, 3)
            TARX=surf_clap_dim(I, 4)
         ELSE
!       NO CLAP OF REF SURF.
            TARX=0.0D0
            TARY=0.0D0
         END IF
!

         IF(DSQRT(((TARX-X)**2)+((TARY-Y)**2)).LE.AIMTOL &
         &.OR.sys_ray_aiming().EQ.0.0D0) THEN
            !call logger%logTextWithNum("Within Aiming Tolerance for Surf",I)


            ! PRINT *, "AIM IS GOOD ENOUGH"
!       AIM IS GOOD ENOUGH, PROCEED
            GO TO 100
         ELSE
!     !  call logger%logTextWithNum("Aiming
!     !1 not good enough for iteration " 1,KKK)
!     !  call logger%logTextWithNum("Aiming Result is "
!     ! 1,DSQRT(((TARX-X)**2)+((TARY-Y)**2)))
!     !
!     !      call logger%logTextWithNum("X1Aim = ", X1AIM)
!     !      call logger%logTextWithNum("Y1Aim = ", Y1AIM)
            ! IF (KKK.EQ.1) Then
            !call logger%logTextWithNum("X Chief Ray Target = ",
            !1 XCHIEF_TARGET)
            !   call logger%logTextWithNum("Y Chief Ray Target = ",
            !2 YCHIEF_TARGET)
            ! END IF


!       AIM NOT GOOD ENOUGH, IMPROVE GUESS
         END IF
!
!       SET X1LAST TO X1ONE AND Y1LAST TO Y1ONE
         X1ONE=X1LAST
         Y1ONE=Y1LAST
!       SET XAIMOL AND YAIMOL TO X1LAST AND Y1LAST
         X1LAST=XAIMOL
         Y1LAST=YAIMOL
!       SET RXONE AND RYONE TO RXLAST AND RYLAST
         RXONE=RXLAST
         RYONE=RYLAST
!       SET RXLAST AND RYLAST TO X AND Y
         RXLAST=X
         RYLAST=Y
!       X AND Y ARE THE CURRENT RAY COORDINATES AT THE
!       REFERENCE SURFACE.
!
!       GUESS CASE 1, REPRESENTS THE FIRST REFINEMENT
!       OF THE AIMING POINT.
!       THIS OCCURS IF KKK=1
         IF(KKK.EQ.1) THEN
!       THIS IS CASE 1
!       IN THIS CASE WE SET THE SURFACE 1 AIMING POINTS
!       EQUAL TO THE OLD AIM POINTS PLUS A SMALL DELTA
!       IN ORDER TO CALCULATE DERIVATIVES.
!

            Y1AIM=YAIMOL+DDELY
            X1AIM=XAIMOL+DDELX
            Z1AIM=ZAIMOL
            XC=X1AIM
            YC=Y1AIM
            ZC=Z1AIM
1234        FORMAT(I3, G15.7, G15.7, G15.7)
            !PRINT *, "KKK=1"
            !PRINT *, "DDELY = ", DDELY
            !PRINT *, "YAIMOL = ", YAIMOL
            !PRINT 1234, KKK, XC, YC, ZC
            XC1=XC
            YC1=YC
            ZC1=ZC
            IF(surf_curvature(1).NE.0.0D0)&
            &CALL GETZEE1
            X1AIM=XC
            Y1AIM=YC
            Z1AIM=ZC
!
!       CALCULATE NEW SET OF VALUES FOR DERIVATIVES
!
!       CALL BAKONE TO CONVERT TO NEWOBJ COORDINATES
            XAIMOL=XC1
            YAIMOL=YC1
            ZAIMOL=ZC1
            R_TX=X1AIM
            R_TY=Y1AIM
            R_TZ=Z1AIM
            CALL BAKONE
            X1AIM=R_TX
            Y1AIM=R_TY
            Z1AIM=R_TZ
!       NOW THE COORDINATES ARE IN THE NEWOBJ COORD SYSTEM
            !IF (KKK.LT.2) PRINT *, "KKK, X1AIM, Y1AIM, Z1AIM"
            !PRINT 1234, KKK, X1AIM, Y1AIM, Z1AIM

            GO TO 9
         END IF
!       THIS IS NOT THE FIRST REFINEMENT, KKK NOT = 1
!
         CALL RAYDERIV(X1LAST,Y1LAST,X1ONE,Y1ONE &
         &,RXONE,RYONE,RXLAST,RYLAST,D11,D12,D21,D22)
!
!       MF1=TARX-RXLAST, MF2=TARY-RYLAST
!
!       TARX AND TARY ARE THE COORDINATES OF THE CENTER
!       OF THE DECENTERED CLEAR APERTURE ON THE REFERENCE
!       SURFACE IF THERE IS A CLEAR APERTURE DEFINED AND IT
!       IS DECENTERED. IF THESE CONDITIONS DO NOT EXIST,
!       TARY AND TARX ARE BOTH IDENTICALLY 0.0D0.
!
!
         MF1=TARX-RXLAST
         MF2=TARY-RYLAST
!
!       CALL NEWDEL
         DELFAIL=.FALSE.
         CALL NEWDEL(MF1,MF2,D11,D12,D21,D22,DELFAIL)
         IF(DELFAIL) THEN
            GO TO 14
         ELSE
            !IF (KKK.LT.2) PRINT *, "KKK, X1AIM, Y1AIM, Z1AIM"
            !PRINT 1234, KKK, X1AIM, Y1AIM, Z1AIM

            GO TO 9
         END IF
!       NOT AT THE REFERENCE SURFACE, NO RAY AIMING NEEDED
      END IF
!
100   CONTINUE
!
10 CONTINUE

   !call logger%logTextWithNum("CDDELX = ", CDDELX)
   !call logger%logTextWithNum("CDDELY = ", CDDELY)
   !call logger%logTextWithNum("YSTRT = ", YSTRT)

!     NOW IF RYIM OR RXIM ARE IN EFFECT, ITERATE THE CHEIF RAY
!     TO HIT THE IMAGE SURFACE AT THE CORRECT POINT
   !call logger%logTextWithNum("System(98) is ", sys_rxim_fang_set())

   IF(sys_rxim_fang_set().LT.0.0D0) THEN
      CX=REFRY(1,NEWIMG)
      CY=REFRY(2,NEWIMG)
   ELSE
      CX=REFRY(11,NEWIMG)*180.0D0/PII
      CY=REFRY(12,NEWIMG)*180.0D0/PII
   END IF
   ERRORVEC=DSQRT(((CX-XCHIEF_TARGET)**2)+((CY-YCHIEF_TARGET)**2))
   IF(sys_rxim_fang_set().NE.0.0D0.AND.sys_ryim_fang_set().NE.0.0D0.AND.&
   &ERRORVEC.GT.CAIMTOL) THEN
      PRINT *, "Error Vector too big?"
      IF(KKKK.EQ.1) THEN
         IF(sys_rxim_fang_set().LT.0.0D0) THEN
            OLDCX=REFRY(1,NEWIMG)
            OLDCY=REFRY(2,NEWIMG)
         ELSE
            OLDCX=REFRY(11,NEWIMG)*180.0D0/PII
            OLDCY=REFRY(12,NEWIMG)*180.0D0/PII
         END IF
!     FIRST TIME
         OXSTRT=XSTRT
         OYSTRT=YSTRT

         XSTRT=XSTRT+CDDELX
         YSTRT=YSTRT+CDDELY
!     COMPUTE THE APROPRIATE ZSTRT VALUE
         IISURF=NEWOBJ
         CALL SAGRET(IISURF,XSTRT,YSTRT,ZSAG,SAGERR)
         IF(SAGERR) CALL HANDLESAGRETFAILURE(MSG, NEWOBJ)

         ZSTRT=ZSAG
         GO TO 9898
      ELSE
!     NOT FIRST TIME
!     SET DEPENDENT VARIABLE VALUES
!
!     PREVIOUS X AND Y VALUES ON IMAGE SURFACE
         CRXONE=OLDCX
         CRYONE=OLDCY
!     CURRENT X AND Y VALUES ON IMAGE SURFACE
         IF(sys_rxim_fang_set().EQ.-1.0D0)&
         &CRXLAST=REFRY(1,NEWIMG)
         IF(sys_rxim_fang_set().EQ.1.0D0)&
         &CRXLAST=REFRY(11,NEWIMG)*180.0D0/PII
         IF(sys_ryim_fang_set().EQ.-1.0D0)&
         &CRYLAST=REFRY(2,NEWIMG)
         IF(sys_ryim_fang_set().EQ.1.0D0)&
         &CRYLAST=REFRY(12,NEWIMG)*180.0D0/PII
         OLDCX=CRXLAST
         OLDCY=CRYLAST
!     SET INDEPENDENT VARIABLE VALUES
         CX1ONE=OXSTRT
         CY1ONE=OYSTRT
         CX1LAST=XSTRT
         CY1LAST=YSTRT
         CD11=0.0D0
         CD12=0.0D0
         CD21=0.0D0
         CD22=0.0D0
         CDET=0.0D0
         CALL CRAYDERIV(CX1LAST,CY1LAST,CX1ONE,CY1ONE &
         &,CRXONE,CRYONE,CRXLAST,CRYLAST,CD11,CD12,CD21,CD22)
      END IF
      IF(KKKK.GT.NRAITR) THEN
!     MAXIMUM CYCLE
!     NO REFERENCE RAY SOLUTION, REF RAY FAILURE
         STOPP=1
         RAYCOD(1)=8
         RAYCOD(2)=I
         OUTLYNE = "SETTING CHIEF RAY TO FALSE 1111"
         CALL SHOWIT(19)
         REFEXT=.FALSE.
         IF(MSG) THEN
            CALL RAY_FAILURE(NEWOBJ)
            WRITE(OUTLYNE,*)'AIMED CHIEF RAY COULD NOT HIT THE DEFINED TARGET'
            CALL SHOWIT(1)
            IF(.NOT.NULL) FOBYES=.FALSE.
            IF(.NOT.NULL.AND.F34.EQ.0) CALL MACFAL
         END IF
         RETURN
      END IF
!     REFINE THE XSTRT,YSTRT VALUE
      CDELFAIL=.FALSE.
!       CMF1=XCHIEF_TARGET-CRXLAST, CMF2=YCHIEF_TARGET-CRYLAST
!
      CMF1=XCHIEF_TARGET-CRXLAST
      CMF2=YCHIEF_TARGET-CRYLAST
      CALL CNEWDEL(CMF1,CMF2,CD11,CD12,CD21,CD22,CDELFAIL,&
      &CDDELX,CDDELY)
      IF(CDELFAIL) THEN
         GO TO 14
      ELSE
         GO TO 9898
      END IF
   ELSE
!     TARGET MET!
      !PRINT *, "TARGET MET FOR SURFACE ", NEWOBJ
      !PRINT *, "Alternate Object Surface ", NEWOBJ
      !PRINT *, "Alternate Image Surface ", NEWIMG

   END IF
   RETURN
END
