!      THIS IS THE TENTH FILE OF RAYTRACING ROUTINES

! SUB GBEAM.FOR
SUBROUTINE GBEAM
!
   use DATLEN
   use DATMAI
   use command_utils, only: is_command_query
   use mod_system, only: sys_wl_ref, sys_last_surf, sys_wrx, sys_wry, sys_bdx, sys_bdy, &
      & sys_astop, sys_ref_surf, sys_set_astop, sys_set_ref_surf
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE GBEAM. THIS SUBROUTINE IMPLEMENTS
!       "BEA" OR "BEAM" GAUSSIAN BEAM COMMAND
!
   INTEGER SF,I,ERROR,OLDREF2,OLDSTOP
!
   SAVE OLDREF2,OLDSTOP
!
   REAL*8 PX,PY,PCX,PCY,PUX,PUY,PUCX,PUCY,DWORD2,DWORD3 &
   &,DWORD4,DWORD5,V1,V2,V3,V4,V5,V6,V7,V8,WRX,WRY,BDX,BDY &
   &,VALVA,VAL1,VAL2
!
!
!
   WRX=sys_wrx()
   WRY=sys_wry()
   BDX=sys_bdx()
   BDY=sys_bdy()
   IF(DF2.EQ.1) W2=0.0D0
   IF(DF3.EQ.1) W3=0.0D0
   IF(DF4.EQ.1) W4=0.0D0
   IF(DF5.EQ.1) W5=sys_wl_ref()
   DWORD2=W2
   DWORD3=W3
   DWORD4=W4
   DWORD5=W5
!
   IF(is_command_query()) THEN
      WRITE(OUTLYNE,*)&
      &'"BEA" OR "BEAM" OUTPUTS GAUSSIAN BEAM PROPERTIES'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1) THEN
      WRITE(OUTLYNE,*)&
      &'GAUSSIAN BEAM OUTPUT COMMANDS TAKE NO STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.1.AND.S1.EQ.1) THEN
      WRITE(OUTLYNE,*)&
      &'"BEA" AND "BEAM" TAKE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)&
      &'QUALIFIER OR NUMERIC WORD #1 INPUT BUT NOT BOTH'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(DWORD5.LT.1.0D0.OR.DWORD5.GT.10.0D0) THEN
      WRITE(OUTLYNE,*)'INVALID WAVELENGTH NUMBER ISSUED'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO GAUSSIAN BEAM DATA EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(sys_last_surf().EQ.0.0) THEN
      WRITE(OUTLYNE,*)'LENS SYSTEM HAS NO SURFACES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO GAUSSIAN BEAM DATA EXISTS'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
   OLDSTOP=INT(sys_astop())
   OLDREF2=INT(sys_ref_surf())
   call sys_set_ref_surf(1.0D0)
   call sys_set_astop(1.0D0)
!
!
   IF(SQ.EQ.1.AND.WQ.EQ.'ALL') THEN
      CALL GNPRTGEN(0,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
      &,DWORD2,DWORD3,DWORD4,DWORD5,1)
      IF(ERROR.EQ.1) THEN
         WRITE(OUTLYNE,*)'RAY COULD NOT BE TRACED'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'DIFFERENTIAL RAY VALUES NOT CALCULABLE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'NO ACTION TAKEN'
         CALL SHOWIT(1)
         CALL MACFAL
         call sys_set_ref_surf(DBLE(OLDREF2))
         call sys_set_astop(DBLE(OLDSTOP))
         RETURN
      END IF
      SF=INT(sys_last_surf())
      WRITE(OUTLYNE,6003)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6006) INT(DWORD5)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6007) DWORD2
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6008) DWORD3
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6009) DWORD4
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6010) WRX
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6011) WRY
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6012) BDX
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6013) BDY
      CALL SHOWIT(0)
!
!     FIRST XZ-PLANE
!
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6001) INT(F12)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6000)
      CALL SHOWIT(0)
      DO I=0,SF
         CALL GNPRTGEN(I,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
         &,DWORD2,DWORD3,DWORD4,DWORD5,1)
         V1=DSQRT((PX**2)+(PCX**2))
         IF(REAL(V1).EQ.0.0) THEN
            VALVA=1.0D20
         ELSE
            VALVA=((PX*PUX)+(PCX*PUCX))/V1
         END IF
         IF(REAL(VALVA).EQ.0.0) THEN
            V2=0.0D0
         ELSE
            V2=-V1/VALVA
         END IF
         IF(REAL((PUX**2)+(PUCX**2)).EQ.0.0) THEN
            V3=1.0D20
         ELSE
            V3=-((PX*PUX)+(PCX*PUCX))/((PUX**2)+(PUCX**2))
         END IF
         VAL1=PX+(PUX*V3)
         VAL2=PCX+(PUCX*V3)
         V4=DSQRT((VAL1**2)+(VAL2**2))
         WRITE(OUTLYNE,1500)I,V1,V2,V3,V4
         CALL SHOWIT(0)
      END DO
!
!     SECOND YZ-PLANE
!
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6002) INT(F12)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6000)
      CALL SHOWIT(0)
      DO I=0,SF
         CALL GNPRTGEN(I,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
         &,DWORD2,DWORD3,DWORD4,DWORD5,1)
         V5=DSQRT((PY**2)+(PCY**2))
         IF(REAL(V5).EQ.0.0) THEN
            VALVA=1.0D20
         ELSE
            VALVA=((PY*PUY)+(PCY*PUCY))/V5
         END IF
         IF(REAL(VALVA).EQ.0.0) THEN
            V6=0.0D0
         ELSE
            V6=-V5/VALVA
         END IF
         IF(REAL((PUY**2)+(PUCY**2)).EQ.0.0) THEN
            V7=1.0D20
         ELSE
            V7=-((PY*PUY)+(PCY*PUCY))/((PUY**2)+(PUCY**2))
         END IF
         VAL1=PY+(PUY*V7)
         VAL2=PCY+(PUCY*V7)
         V8=DSQRT((VAL1**2)+(VAL2**2))
         WRITE(OUTLYNE,1500)I,V5,V6,V7,V8
         CALL SHOWIT(0)
      END DO
      call sys_set_ref_surf(DBLE(OLDREF2))
      call sys_set_astop(DBLE(OLDSTOP))
      RETURN
   END IF
   IF(SQ.EQ.1.AND.WQ.EQ.'OBJ'.OR.SQ.EQ.1.AND.WQ.EQ.'OB') THEN
      SF=0
      CALL GNPRTGEN(SF,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
      &,DWORD2,DWORD3,DWORD4,DWORD5,1)
      IF(ERROR.EQ.1) THEN
         WRITE(OUTLYNE,*)'RAY COULD NOT BE TRACED'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'DIFFERENTIAL RAY VALUES NOT CALCULABLE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'NO ACTION TAKEN'
         CALL SHOWIT(1)
         CALL MACFAL
         call sys_set_ref_surf(DBLE(OLDREF2))
         call sys_set_astop(DBLE(OLDSTOP))
         RETURN
      END IF
      V1=DSQRT((PX**2)+(PCX**2))
      IF(REAL(V1).EQ.0.0) THEN
         VALVA=1.0D20
      ELSE
         VALVA=((PX*PUX)+(PCX*PUCX))/V1
      END IF
      IF(REAL(VALVA).EQ.0.0) THEN
         V2=0.0D0
      ELSE
         V2=-V1/VALVA
      END IF
      IF(REAL((PUX**2)+(PUCX**2)).EQ.0.0) THEN
         V3=1.0D20
      ELSE
         V3=-((PX*PUX)+(PCX*PUCX))/((PUX**2)+(PUCX**2))
      END IF
      VAL1=PX+(PUX*V3)
      VAL2=PCX+(PUCX*V3)
      V4=DSQRT((VAL1**2)+(VAL2**2))
      V5=DSQRT((PY**2)+(PCY**2))
      IF(REAL(V5).EQ.0.0) THEN
         VALVA=1.0D20
      ELSE
         VALVA=((PY*PUY)+(PCY*PUCY))/V5
      END IF
      IF(REAL(VALVA).EQ.0.0) THEN
         V6=0.0D0
      ELSE
         V6=-V5/VALVA
      END IF
      IF(REAL((PUY**2)+(PUCY**2)).EQ.0.0) THEN
         V7=1.0D20
      ELSE
         V7=-((PY*PUY)+(PCY*PUCY))/((PUY**2)+(PUCY**2))
      END IF
      VAL1=PY+(PUY*V7)
      VAL2=PCY+(PUCY*V7)
      V8=DSQRT((VAL1**2)+(VAL2**2))
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6003)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6006) INT(DWORD5)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6007) DWORD2
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6008) DWORD3
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6009) DWORD4
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6010) WRX
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6011) WRY
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6012) BDX
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6013) BDY
      CALL SHOWIT(0)
!     XZ-PLANE
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6001) INT(F12)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1500) SF,V1,V2,V3,V4
      CALL SHOWIT(0)
!     YZ-PLANE
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6002) INT(F12)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1500) SF,V5,V6,V7,V8
      CALL SHOWIT(0)
      call sys_set_ref_surf(DBLE(OLDREF2))
      call sys_set_astop(DBLE(OLDSTOP))
      RETURN
   END IF
   IF(SQ.EQ.1.AND.WQ.NE.'OBJ'.OR.SQ.EQ.1.AND.&
   &WQ.NE.'ALL'.OR.SQ.EQ.1.AND.WQ.NE.'OB') THEN
      WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      call sys_set_ref_surf(DBLE(OLDREF2))
      call sys_set_astop(DBLE(OLDSTOP))
      RETURN
   END IF
   IF(SQ.EQ.0.AND.DF1.EQ.1) THEN
!       OUTPUT IMAGE SURFACE
      SF=INT(sys_last_surf())
      CALL GNPRTGEN(SF,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
      &,DWORD2,DWORD3,DWORD4,DWORD5,1)
      IF(ERROR.EQ.1) THEN
         WRITE(OUTLYNE,*)'RAY COULD NOT BE TRACED'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'DIFFERENTIAL RAY VALUES NOT CALCULABLE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'NO ACTION TAKEN'
         CALL SHOWIT(1)
         CALL MACFAL
         call sys_set_ref_surf(DBLE(OLDREF2))
         call sys_set_astop(DBLE(OLDSTOP))
         RETURN
      END IF
      V1=DSQRT((PX**2)+(PCX**2))
      IF(REAL(V1).EQ.0.0) THEN
         VALVA=1.0D20
      ELSE
         VALVA=((PX*PUX)+(PCX*PUCX))/V1
      END IF
      IF(REAL(VALVA).EQ.0.0) THEN
         V2=0.0D0
      ELSE
         V2=-V1/VALVA
      END IF
      IF(REAL((PUX**2)+(PUCX**2)).EQ.0.0) THEN
         V3=1.0D20
      ELSE
         V3=-((PX*PUX)+(PCX*PUCX))/((PUX**2)+(PUCX**2))
      END IF
      VAL1=PX+(PUX*V3)
      VAL2=PCX+(PUCX*V3)
      V4=DSQRT((VAL1**2)+(VAL2**2))
      V5=DSQRT((PY**2)+(PCY**2))
      IF(REAL(V5).EQ.0.0) THEN
         VALVA=1.0D20
      ELSE
         VALVA=((PY*PUY)+(PCY*PUCY))/V5
      END IF
      IF(REAL(VALVA).EQ.0.0) THEN
         V6=0.0D0
      ELSE
         V6=-V5/VALVA
      END IF
      IF(REAL((PUY**2)+(PUCY**2)).EQ.0.0) THEN
         V7=1.0D20
      ELSE
         V7=-((PY*PUY)+(PCY*PUCY))/((PUY**2)+(PUCY**2))
      END IF
      VAL1=PY+(PUY*V7)
      VAL2=PCY+(PUCY*V7)
      V8=DSQRT((VAL1**2)+(VAL2**2))
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6003)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6006) INT(DWORD5)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6007) DWORD2
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6008) DWORD3
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6009) DWORD4
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6010) WRX
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6011) WRY
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6012) BDX
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6013) BDY
      CALL SHOWIT(0)
!     XZ-PLANE
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6001) INT(F12)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1500) SF,V1,V2,V3,V4
      CALL SHOWIT(0)
!     YZ-PLANE
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6002) INT(F12)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1500) SF,V5,V6,V7,V8
      CALL SHOWIT(0)
      call sys_set_ref_surf(DBLE(OLDREF2))
      call sys_set_astop(DBLE(OLDSTOP))
      RETURN
   END IF
   IF(SQ.EQ.0.AND.DF1.NE.1) THEN
      I=INT(W1)
      SF=INT(sys_last_surf())
      IF(I.GT.SF.OR.I.LT.0) THEN
         WRITE(OUTLYNE,*)'SURFACE NUMBER BEYOND LEGAL RANGE'
         CALL SHOWIT(1)
         CALL MACFAL
         call sys_set_ref_surf(DBLE(OLDREF2))
         call sys_set_astop(DBLE(OLDSTOP))
         RETURN
      END IF
      CALL GNPRTGEN(I,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
      &,DWORD2,DWORD3,DWORD4,DWORD5,1)
      IF(ERROR.EQ.1) THEN
         WRITE(OUTLYNE,*)'RAY COULD NOT BE TRACED'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'DIFFERENTIAL RAY VALUES NOT CALCULABLE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'NO ACTION TAKEN'
         CALL SHOWIT(1)
         CALL MACFAL
         call sys_set_ref_surf(DBLE(OLDREF2))
         call sys_set_astop(DBLE(OLDSTOP))
         RETURN
      END IF
      V1=DSQRT((PX**2)+(PCX**2))
      IF(REAL(V1).EQ.0.0) THEN
         VALVA=1.0D20
      ELSE
         VALVA=((PX*PUX)+(PCX*PUCX))/V1
      END IF
      IF(REAL(VALVA).EQ.0.0) THEN
         V2=0.0D0
      ELSE
         V2=-V1/VALVA
      END IF
      IF(REAL((PUX**2)+(PUCX**2)).EQ.0.0) THEN
         V3=1.0D20
      ELSE
         V3=-((PX*PUX)+(PCX*PUCX))/((PUX**2)+(PUCX**2))
      END IF
      VAL1=PX+(PUX*V3)
      VAL2=PCX+(PUCX*V3)
      V4=DSQRT((VAL1**2)+(VAL2**2))
      V5=DSQRT((PY**2)+(PCY**2))
      IF(REAL(V5).EQ.0.0) THEN
         VALVA=1.0D20
      ELSE
         VALVA=((PY*PUY)+(PCY*PUCY))/V5
      END IF
      IF(REAL(VALVA).EQ.0.0) THEN
         V6=0.0D0
      ELSE
         V6=-V5/VALVA
      END IF
      IF(REAL((PUY**2)+(PUCY**2)).EQ.0.0) THEN
         V7=1.0D20
      ELSE
         V7=-((PY*PUY)+(PCY*PUCY))/((PUY**2)+(PUCY**2))
      END IF
      VAL1=PY+(PUY*V7)
      VAL2=PCY+(PUCY*V7)
      V8=DSQRT((VAL1**2)+(VAL2**2))
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6003)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6006) INT(DWORD5)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6007) DWORD2
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6008) DWORD3
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6009) DWORD4
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6010) WRX
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6011) WRY
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6012) BDX
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6013) BDY
      CALL SHOWIT(0)
!     XZ-PLANE
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6001) INT(F12)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1500)I,V1,V2,V3,V4
      CALL SHOWIT(0)
!     YZ-PLANE
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6002) INT(F12)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6000)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,1500)I,V5,V6,V7,V8
      CALL SHOWIT(0)
   END IF
1500 FORMAT(I3,7X,G13.6,3X,G13.6,4X,G13.6,5X,G13.6)
6000 FORMAT('SURF',6X,'BEAM SEMI-DIA.',2X,'WAVFNT RADIUS'&
   &,4X,'DIST TO WAIST',5X,'WAIST SEMI-DIA.')
6001 FORMAT('GAUSSIAN BEAM DATA (XZ-PLANE)',&
   &' - (CFG #',I2,')')
6002 FORMAT('GAUSSIAN BEAM DATA (YZ-PLANE)',&
   &' - (CFG #',I2,')')
!
6003 FORMAT('GAUSSIAN BEAM ANALYSIS')
!
2501 FORMAT(1X)
6006 FORMAT('TRACED AT WAVELENGTH NUMBER = ',I2)
6007 FORMAT('TRACED FROM Y-FOB =  ',G13.6)
6008 FORMAT('TRACED FROM X-FOB =  ',G13.6)
6009 FORMAT('WITH OBJ. Z-SHIFT =  ',G13.6,' LENS UNITS')
6010 FORMAT(&
   &'      XZ-PLANE INPUT SEMI-DIA. =  ',G13.6,' LENS UNITS')
6011 FORMAT(&
   &'      YZ-PLANE INPUT SEMI-DIA. =  ',G13.6,' LENS UNITS')
6012 FORMAT(&
   &'XZ-PLANE DIVERGENCE HALF-ANGLE =  ',G13.6,' MILLIRADIANS')
6013 FORMAT(&
   &'YZ-PLANE DIVERGENCE HALF-ANGLE =  ',G13.6,' MILLIRADIANS')
!
END
! SUB GLPRY.FOR
SUBROUTINE GLPRY
   USE GLOBALS
!
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_thickness, surf_special_type
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE GLPRY.FOR. THIS SUBROUTINE IMPLEMENTS
!       CREATION OF GLOBAL RAY DATA FOR THE LAST RAY TRACED.
!       FOR RAY PLOTTING IT IS CALLED BY RAYTRA.FOR
!
   INTEGER JK,I,N_HITS
!
   REAL*8 GRX,GRY,GRZ,GRL,GRM,GRN,GRLP,GRMP,GRNP,&
   &X1,Y1,Z1,L1,M1,N1,X00,Y00,Z0,LX0,LY0,LZ0,&
   &MX0,MY0,MZ0,NX0,NY0,NZ0,LO1,MO1,NO1
!
!
   IF(DABS(surf_thickness(NEWOBJ)).LE.1.0D10) THEN
!       FINITE OBJECT THICKNESS
      JK=NEWOBJ
   ELSE
!       INFINITE OBJECT THICKNESS
      JK=NEWOBJ+1
   END IF
!
   DO 10 I=JK,NEWIMG
!
!       NOW TRANSFORM TO THE GLOBAL COORDINATE SYSTEM.
!       THE GLOBAL COORDINATES OF EACH LOCAL COORDINATE
!       SYSTEM ARE:
!
      X00=VERTEX(1,I)
      Y00=VERTEX(2,I)
      Z0=VERTEX(3,I)
      LX0=VERTEX(4,I)
      MX0=VERTEX(5,I)
      NX0=VERTEX(6,I)
      LY0=VERTEX(7,I)
      MY0=VERTEX(8,I)
      NY0=VERTEX(9,I)
      LZ0=VERTEX(10,I)
      MZ0=VERTEX(11,I)
      NZ0=VERTEX(12,I)
!
      X1=X00+((LX0*(RAYRAY(1,I)))+(LY0*(RAYRAY(2,I)))&
      &+(LZ0*(RAYRAY(3,I))))
      Y1=Y00+((MX0*(RAYRAY(1,I)))+(MY0*(RAYRAY(2,I)))&
      &+(MZ0*(RAYRAY(3,I))))
      Z1=Z0+((NX0*(RAYRAY(1,I)))+(NY0*(RAYRAY(2,I)))&
      &+(NZ0*(RAYRAY(3,I))))
!
      L1=((LX0*(RAYRAY(4,I)))+(LY0*(RAYRAY(5,I)))&
      &+(LZ0*(RAYRAY(6,I))))
      M1=((MX0*(RAYRAY(4,I)))+(MY0*(RAYRAY(5,I)))&
      &+(MZ0*(RAYRAY(6,I))))
      N1=((NX0*(RAYRAY(4,I)))+(NY0*(RAYRAY(5,I)))&
      &+(NZ0*(RAYRAY(6,I))))
!
      LO1=((LX0*(RAYRAY(19,I)))+(LY0*(RAYRAY(20,I)))&
      &+(LZ0*(RAYRAY(21,I))))
      MO1=((MX0*(RAYRAY(19,I)))+(MY0*(RAYRAY(20,I)))&
      &+(MZ0*(RAYRAY(21,I))))
      NO1=((NX0*(RAYRAY(19,I)))+(NY0*(RAYRAY(20,I)))&
      &+(NZ0*(RAYRAY(21,I))))
!
      GLPRAY(1,I)=X1
      GLPRAY(2,I)=Y1
      GLPRAY(3,I)=Z1
      GLPRAY(4,I)=L1
      GLPRAY(5,I)=M1
      GLPRAY(6,I)=N1
      GLPRAY(7,I)=LO1
      GLPRAY(8,I)=MO1
      GLPRAY(9,I)=NO1
      GLVIRT(I)=.FALSE.
!     IF THE CURRENT SURFACE IS A TRUE DUMMY
      IF(DUM(I).AND.surf_special_type(I).EQ.0 &
      &.AND.I.NE.NEWIMG) GLVIRT(I)=.TRUE.
      IF(I.EQ.NEWIMG) GLVIRT(I)=.FALSE.

!       THE CURRENT ENTRY FOR GLPRY REPRESENTS THE RAY AT THE BEGINNING
!       OF AN NSS OR GRIN ENVIRONMENT. NOW POPULATE THE ARRAY
!       GLOBAL_MULTIRAY_DATA STORED AT I TO REPRESENT THE INTERMEDIATE
!       RAY COORDINATES BETWEEN I AND I+1
      IF(I.GE.1) THEN
         IF(NUMHITS(I-1).GT.1) THEN
            DO N_HITS=1,NUMHITS(I-1)
               X00=VERTEX(1,I-1)
               Y00=VERTEX(2,I-1)
               Z0=VERTEX(3,I-1)
               LX0=VERTEX(4,I-1)
               MX0=VERTEX(5,I-1)
               NX0=VERTEX(6,I-1)
               LY0=VERTEX(7,I-1)
               MY0=VERTEX(8,I-1)
               NY0=VERTEX(9,I-1)
               LZ0=VERTEX(10,I-1)
               MZ0=VERTEX(11,I-1)
               NZ0=VERTEX(12,I-1)
               GRX=MULTI_DATA(1,I-1,N_HITS)
               GRY=MULTI_DATA(2,I-1,N_HITS)
               GRZ=MULTI_DATA(3,I-1,N_HITS)
               GRL=MULTI_DATA(4,I-1,N_HITS)
               GRM=MULTI_DATA(5,I-1,N_HITS)
               GRN=MULTI_DATA(6,I-1,N_HITS)
               GRLP=MULTI_DATA(19,I-1,N_HITS)
               GRMP=MULTI_DATA(20,I-1,N_HITS)
               GRNP=MULTI_DATA(21,I-1,N_HITS)
               X1=X00+((LX0*(GRX))+(LY0*(GRY))&
               &+(LZ0*(GRZ)))
               Y1=Y00+((MX0*(GRX))+(MY0*(GRY))&
               &+(MZ0*(GRZ)))
               Z1=Z0+((NX0*(GRX))+(NY0*(GRY))&
               &+(NZ0*(GRZ)))
!
               L1=((LX0*(GRL))+(LY0*(GRM))&
               &+(LZ0*(GRN)))
               M1=((MX0*(GRL))+(MY0*(GRM))&
               &+(MZ0*(GRN)))
               N1=((NX0*(GRL))+(NY0*(GRM))&
               &+(NZ0*(GRN)))
!
               LO1=((LX0*(GRLP))+(LY0*(GRMP))&
               &+(LZ0*(GRNP)))
               MO1=((MX0*(GRLP))+(MY0*(GRMP))&
               &+(MZ0*(GRNP)))
               NO1=((NX0*(GRLP))+(NY0*(GRMP))&
               &+(NZ0*(GRNP)))
!
               GLOBAL_MULTIRAY_DATA(1,I-1,N_HITS)=X1
               GLOBAL_MULTIRAY_DATA(2,I-1,N_HITS)=Y1
               GLOBAL_MULTIRAY_DATA(3,I-1,N_HITS)=Z1
               GLOBAL_MULTIRAY_DATA(4,I-1,N_HITS)=L1
               GLOBAL_MULTIRAY_DATA(5,I-1,N_HITS)=M1
               GLOBAL_MULTIRAY_DATA(6,I-1,N_HITS)=N1
               GLOBAL_MULTIRAY_DATA(19,I-1,N_HITS)=LO1
               GLOBAL_MULTIRAY_DATA(20,I-1,N_HITS)=MO1
               GLOBAL_MULTIRAY_DATA(21,I-1,N_HITS)=NO1
               GLOBAL_MULTIREF_DATA(1,I-1,N_HITS)=X1
               GLOBAL_MULTIREF_DATA(2,I-1,N_HITS)=Y1
               GLOBAL_MULTIREF_DATA(3,I-1,N_HITS)=Z1
               GLOBAL_MULTIREF_DATA(4,I-1,N_HITS)=L1
               GLOBAL_MULTIREF_DATA(5,I-1,N_HITS)=M1
               GLOBAL_MULTIREF_DATA(6,I-1,N_HITS)=N1
               GLOBAL_MULTIREF_DATA(19,I-1,N_HITS)=LO1
               GLOBAL_MULTIREF_DATA(20,I-1,N_HITS)=MO1
               GLOBAL_MULTIREF_DATA(21,I-1,N_HITS)=NO1
            END DO
         END IF
      END IF

10 CONTINUE
!       ALL GLOBAL TRANSFORMATIONS ARE COMPLETE
!
   RETURN
END
! SUB GLOBAL.FOR
SUBROUTINE GLOBAL
!
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_thickness
   use mod_system, only: sys_units, sys_last_surf
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE GLOBAL. THIS SUBROUTINE IMPLEMENTS
!       THE CMD COMMANDS "GLOBAL", "OFFSET" AND "VERTEX".
!
   CHARACTER UNIT*11
!
   INTEGER SF,I,JK
!
!
   IF(sys_units().EQ.1.0D0) UNIT='INCHES'
   IF(sys_units().EQ.2.0D0) UNIT='CENTIMETERS'
   IF(sys_units().EQ.3.0D0) UNIT='MILLIMETERS'
   IF(sys_units().EQ.4.0D0) UNIT='METERS'
!
   IF(WC.EQ.'GLOBAL') THEN
!
      IF(SQ.EQ.1.AND.S1.EQ.1) THEN
         WRITE(OUTLYNE,*)&
         &'"',WC(1:6),&
         &'" TAKES EITHER QUALIFIER OR NUMERIC WORD #1 INPUT NOT BOTH'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(SQ.EQ.1.AND.WQ.NE.'OFF') THEN
         WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "',&
         &WC(1:6),'" COMMAND'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(S2.EQ.1.OR.S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
         WRITE(OUTLYNE,*)'"',WC(1:6),&
         &'" ONLY TAKES QUALIFIER OR NUMERIC WORD #1 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(S1.EQ.1.AND.INT(W1).LT.NEWOBJ.OR.S1.EQ.1.AND.&
      &INT(W1).GT.NEWIMG) THEN
         WRITE(OUTLYNE,*)'SURFACE NUMBER BEYOND LEGAL RANGE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(DF1.EQ.1.AND.DF2.EQ.1.AND.DF3.EQ.1.AND.SQ.EQ.0.AND.&
      &DF4.EQ.1.AND.DF5.EQ.1) THEN
!       PRINT CURRENT GLOBAL STATUS
         IF(.NOT.GLOBE) THEN
            WRITE(OUTLYNE,100)
            CALL SHOWIT(0)
100         FORMAT('"GLOBAL" IS CURRENTLY SET TO "OFF"')
!                       RETURN
         END IF
         IF(GLOBE) THEN
            WRITE(OUTLYNE,101) GLSURF
            CALL SHOWIT(0)
101         FORMAT(&
            &'"GLOBAL" IS CURRENTLY "ON", REFERENCED TO SURFACE '&
            &,I3)
            WRITE(OUTLYNE,102) OFFX,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,103) OFFY,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,104) OFFZ,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,105) OFFA
            CALL SHOWIT(0)
            WRITE(OUTLYNE,106) OFFB
            CALL SHOWIT(0)
            WRITE(OUTLYNE,107) OFFC
            CALL SHOWIT(0)
102         FORMAT('WITH X-OFFSET   = ',G18.10,1X,A11)
103         FORMAT('WITH Y-OFFSET   = ',G18.10,1X,A11)
104         FORMAT('WITH Z-OFFSET   = ',G18.10,1X,A11)
105         FORMAT('WITH ALPHA TILT = ',G18.10,' DEGREES')
106         FORMAT('WITH BETA  TILT = ',G18.10,' DEGREES')
107         FORMAT('WITH GAMMA TILT = ',G18.10,' DEGREES')
!                       RETURN
         END IF
      END IF
      IF(WQ.EQ.'OFF') THEN
         IF(GLOBE) THEN
!       SET REFERENCE AND OTHER RAY STATUS TO FALSE
            FOBYES=.FALSE.
            REFEXT=.FALSE.
            SPDEXT=.FALSE.
            GSPDEXT=.FALSE.
            CPFNEXT=.FALSE.
            CALL DELPSF
            RAYEXT=.FALSE.
            GLOBE=.FALSE.
            GLSURF=0
            OFFX=0.0D0
            OFFY=0.0D0
            OFFZ=0.0D0
            OFFA=0.0D0
            OFFB=0.0D0
            OFFC=0.0D0
            RETURN
         END IF
         IF(.NOT.GLOBE) THEN
            RETURN
         END IF
      END IF
      IF(S1.EQ.1) THEN
         IF(DABS(surf_thickness(INT(W1))).GT.1.0D10.AND.INT(W1)&
         &.NE.NEWOBJ) THEN
            WRITE(OUTLYNE,*)&
            &'THE GLOBAL SURFACE SPECIFIED ,SURFACE NUMBER ',INT(W1)
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'HAS AN INFINITE THICKNESS ( MAGNITUDE GREATER THAN 1.0D+10)'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'"GLOBAL" WILL YIELD UNCERTAIN RESULTS IN THIS CASE'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'ADJUST THICKNESSES AND RE-ENTER THE "GLOBAL" COMMAND'
            CALL SHOWIT(1)
            REFEXT=.FALSE.
            SPDEXT=.FALSE.
            GSPDEXT=.FALSE.
            CPFNEXT=.FALSE.
            CALL DELPSF
            FOBYES=.FALSE.
            RAYEXT=.FALSE.
            GLOBE=.FALSE.
            CALL MACFAL
            RETURN
         END IF
         IF(DABS(surf_thickness(INT(W1))).GT.1.0D10.AND.INT(W1)&
         &.EQ.NEWOBJ) THEN
            WRITE(OUTLYNE,*)&
            &'GLOBAL SURFACE SELECTED WAS THE CURRENT OBJECT SURFACE'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'IT HAS AN INFINITE THICKNESS ( MAGNITUDE GREATER THAN 1.0D+10)'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'"GLOBAL" WILL YIELD UNCERTAIN RESULTS IN THIS CASE'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'RE-ENTER "GLOBAL" WITH A DIFFERENT SURFACE NUMBER'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'OR A REDUCED OBJECT THICKNESS'
            CALL SHOWIT(1)
            REFEXT=.FALSE.
            SPDEXT=.FALSE.
            GSPDEXT=.FALSE.
            CPFNEXT=.FALSE.
            CALL DELPSF
            FOBYES=.FALSE.
            RAYEXT=.FALSE.
            GLOBE=.FALSE.
            CALL MACFAL
            RETURN
         END IF
!       CHECK FOR AND THICKNESSES GT 1.0D10
         DO 1010 I=NEWOBJ+1,NEWIMG
            IF(DABS(surf_thickness(I)).GT.1.0D10) THEN
               WRITE(OUTLYNE,*)&
               &'SURFACE NUMBER ',I
               CALL SHOWIT(1)
               WRITE(OUTLYNE,*)&
               &'HAS AN INFINITE THICKNESS ( MAGNITUDE GREATER THAN 1.0D+10)'
               CALL SHOWIT(1)
               WRITE(OUTLYNE,*)&
               &'"GLOBAL" WILL YIELD UNCERTAIN RESULTS IN THIS CASE'
               CALL SHOWIT(1)
               WRITE(OUTLYNE,*)&
               &'ADJUST THICKNESSES AND RE-ENTER THE "GLOBAL" COMMAND'
               CALL SHOWIT(1)
               REFEXT=.FALSE.
               SPDEXT=.FALSE.
               GSPDEXT=.FALSE.
               CPFNEXT=.FALSE.
               CALL DELPSF
               FOBYES=.FALSE.
               RAYEXT=.FALSE.
               GLOBE=.FALSE.
               CALL MACFAL
               RETURN
            END IF
1010     CONTINUE
         REFEXT=.FALSE.
         SPDEXT=.FALSE.
         GSPDEXT=.FALSE.
         CPFNEXT=.FALSE.
         CALL DELPSF
         FOBYES=.FALSE.
         RAYEXT=.FALSE.
         GLOBE=.TRUE.
         GLSURF=INT(W1)
         OFFX=0.0D0
         OFFY=0.0D0
         OFFZ=0.0D0
         OFFA=0.0D0
         OFFB=0.0D0
         OFFC=0.0D0
         CALL GLVERT
         RETURN
      END IF
   END IF
!
   IF(WC.EQ.'OFFSET') THEN
!
      IF(.NOT.GLOBE) THEN
         WRITE(OUTLYNE,198)
         CALL SHOWIT(0)
199      FORMAT('"GLOBAL" IS CURRENTLY SET TO "OFF"')
         WRITE(OUTLYNE,199)WC,WQ
         CALL SHOWIT(0)
198      FORMAT(A6,' ',A4,&
         &' IS NOT A VALID COMMAND  WHEN "GLOBAL" IS SET TO "OFF"')
         RETURN
      END IF
      IF(WQ.NE.'DEC'.AND.WQ.NE.'TILT') THEN
         WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD USED WITH "',&
         &WC(1:6),'" COMMAND'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(S4.EQ.1.OR.S5.EQ.1.OR.SST.EQ.1) THEN
         WRITE(OUTLYNE,*)'"',WC(1:6),' ',WQ(1:4),&
         &'" TAKES NO STRING OR NUMERIC WORD 4 OR 5 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(DF1.EQ.1.AND.DF2.EQ.1.AND.DF3.EQ.1.AND.SQ.EQ.0.AND.&
      &DF4.EQ.1.AND.DF5.EQ.1) THEN
!       PRINT CURRENT OFFSET STATUS
         IF(.NOT.GLOBE) THEN
            WRITE(OUTLYNE,200)
            CALL SHOWIT(0)
200         FORMAT(&
            &'"GLOBAL" IS CURRENTLY SET TO "OFF", NO OFFSETS CAN EXIST')
            RETURN
         END IF
         IF(GLOBE) THEN
            WRITE(OUTLYNE,201) GLSURF
            CALL SHOWIT(0)
201         FORMAT(&
            &'"GLOBAL" IS CURRENTLY "ON", REFERENCED TO SURFACE '&
            &,I3)
            WRITE(OUTLYNE,220)
            CALL SHOWIT(0)
220         FORMAT('CURRENT OFFSET STATUS IS:')
            WRITE(OUTLYNE,202) OFFX,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,203) OFFY,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,204) OFFZ,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,205) OFFA
            CALL SHOWIT(0)
            WRITE(OUTLYNE,206) OFFB
            CALL SHOWIT(0)
            WRITE(OUTLYNE,207) OFFC
            CALL SHOWIT(0)
202         FORMAT('WITH X-OFFSET   = ',G18.10,1X,A11)
203         FORMAT('WITH Y-OFFSET   = ',G18.10,1X,A11)
204         FORMAT('WITH Z-OFFSET   = ',G18.10,1X,A11)
205         FORMAT('WITH ALPHA TILT = ',G18.10,' DEGREES')
206         FORMAT('WITH BETA  TILT = ',G18.10,' DEGREES')
207         FORMAT('WITH GAMMA TILT = ',G18.10,' DEGREES')
!                       RETURN
         END IF
      END IF
      IF(DF1.EQ.1.AND.DF2.EQ.1.AND.DF3.EQ.1.AND.SQ.EQ.0.AND.&
      &DF4.EQ.1.AND.DF5.EQ.1) THEN
!      OFFSET REQUIRES A QUALIFIER WITH NUMERIC INPUT
         WRITE(OUTLYNE,*)&
         &'"OFFSET" REQUIRES A QUALIFIER WITH NUMERIC INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(WQ.EQ.'DEC') THEN
         RAYEXT=.FALSE.
         REFEXT=.FALSE.
         SPDEXT=.FALSE.
         GSPDEXT=.FALSE.
         CPFNEXT=.FALSE.
         CALL DELPSF
         FOBYES=.FALSE.
         IF(DF1.EQ.1) W1=0.0D0
         IF(DF2.EQ.1) W2=0.0D0
         IF(DF3.EQ.1) W3=0.0D0
         OFFX=W1
         OFFY=W2
         OFFZ=W3
!       GLVERT.FOR CALCULATES THE X,Y,Z OF EACH SURFACE
!       VERTEX IN THE COORDINATE SYSTEM OF THE GLOBAL REFERENCE
!       COORDINATE SYSTEM AND ALSO THE L,M AND N OF THE X,Y AND Z
!       AXES AT EACH SURFACE VERTEX IN THE COORDINATE SYSTEM
!       OF THE GLOBAL REFERENCE POINT.
         CALL GLVERT
         RETURN
      END IF
      IF(WQ.EQ.'TILT') THEN
         RAYEXT=.FALSE.
         REFEXT=.FALSE.
         SPDEXT=.FALSE.
         GSPDEXT=.FALSE.
         CPFNEXT=.FALSE.
         CALL DELPSF
         FOBYES=.FALSE.
         IF(DF1.EQ.1) W1=0.0D0
         IF(DF2.EQ.1) W2=0.0D0
         IF(DF3.EQ.1) W3=0.0D0
         OFFA=W1
         OFFB=W2
         OFFC=W3
!       GLVERT.FOR CALCULATES THE X,Y,Z OF EACH SURFACE
!       VERTEX IN THE COORDINATE SYSTEM OF THE GLOBAL REFERENCE
!       COORDINATE SYSTEM AND ALSO THE L,M AND N OF THE X,Y AND Z
!       AXES AT EACH SURFACE VERTEX IN THE COORDINATE SYSTEM
!       OF THE GLOBAL REFERENCE POINT.
         CALL GLVERT
         RETURN
      END IF
!
   END IF

   IF(WC.EQ.'VERTEX') THEN
      IF(.NOT.GLOBE) THEN
!       NO VERTEX DATA TO OUTPUT
         WRITE(OUTLYNE,*)&
         &'NO CURRENT GLOBAL VERTEX DATA EXISTS TO OUTPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
!
      IF(SST.EQ.1.OR.S2.EQ.1.OR.S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
         WRITE(OUTLYNE,*)&
         &'"VERTEX" ONLY TAKES QUALIFIER OR NUMERIC WORD #1 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(SQ.EQ.1.AND.S1.EQ.1) THEN
         WRITE(OUTLYNE,*)&
         &'"VERTEX" TAKES EITHER QUALIFIER OR NUMERIC WORD #1 INPUT'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'BUT NOT BOTH'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(sys_last_surf().EQ.0.0D0) THEN
         WRITE(OUTLYNE,*)'LENS SYSTEM HAS NO SURFACES'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'NO GLOBAL VERTEX DATA CAN EXIST'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(SQ.EQ.1.AND.WQ.EQ.'ALL') THEN
!       PRINT WARNING FOR OBJECT THICKNESS INFINITE
         IF(DABS(surf_thickness(NEWOBJ)).GT.1.0D10)THEN
            WRITE(OUTLYNE,*)'WARNING:'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'INFINITE OBJECT THICKNESS (MAGNITUDE GREATER THAN 1.0D+10'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'OBJECT THICKNESS WAS IGNORED IN ALL GLOBAL CALCULATIONS'
            CALL SHOWIT(1)
            JK=NEWOBJ+1
         ELSE
            JK=NEWOBJ
         END IF
         SF=NEWIMG
         WRITE(OUTLYNE,5001) INT(F12)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,5002) GLSURF
         CALL SHOWIT(0)
         WRITE(OUTLYNE,102) OFFX,UNIT
         CALL SHOWIT(0)
         WRITE(OUTLYNE,103) OFFY,UNIT
         CALL SHOWIT(0)
         WRITE(OUTLYNE,104) OFFZ,UNIT
         CALL SHOWIT(0)
         WRITE(OUTLYNE,105) OFFA
         CALL SHOWIT(0)
         WRITE(OUTLYNE,106) OFFB
         CALL SHOWIT(0)
         WRITE(OUTLYNE,107) OFFC
         CALL SHOWIT(0)
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,5000)
         CALL SHOWIT(0)
         DO 10 I=JK,SF
            WRITE(OUTLYNE,2000)I,VERTEX(1,I),VERTEX(2,I),VERTEX(3,I)
            CALL SHOWIT(0)
10       CONTINUE
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,5003)
         CALL SHOWIT(0)
         DO 11 I=JK,SF
            WRITE(OUTLYNE,2000)I,VERTEX(4,I),VERTEX(5,I),VERTEX(6,I)
            CALL SHOWIT(0)
11       CONTINUE
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,5004)
         CALL SHOWIT(0)
         DO 12 I=JK,SF
            WRITE(OUTLYNE,2000)I,VERTEX(7,I),VERTEX(8,I),VERTEX(9,I)
            CALL SHOWIT(0)
12       CONTINUE
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,5005)
         CALL SHOWIT(0)
         DO 13 I=JK,SF
            WRITE(OUTLYNE,2000)I,VERTEX(10,I),VERTEX(11,I),VERTEX(12,I)
            CALL SHOWIT(0)
13       CONTINUE
         RETURN
      END IF
      IF(SQ.EQ.1.AND.WQ.EQ.'OBJ'.OR.SQ.EQ.1.AND.WQ.EQ.'OB') THEN
         SF=NEWOBJ
         IF(DABS(surf_thickness(SF)).GT.1.0D10) THEN
            WRITE(OUTLYNE,*)&
            &'NO GLOBAL RAY DATA EXISTS FOR THE OBJECT SURFACE'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'WHICH HAS INFINTE THICKNESS (GREATER THAN 1.0D10)'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
            CALL SHOWIT(1)
            CALL MACFAL
            RETURN
         END IF
         IF(HEADIN) THEN
            WRITE(OUTLYNE,5001) INT(F12)
            CALL SHOWIT(0)
            WRITE(OUTLYNE,5002) GLSURF
            CALL SHOWIT(0)
            WRITE(OUTLYNE,102) OFFX,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,103) OFFY,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,104) OFFZ,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,105) OFFA
            CALL SHOWIT(0)
            WRITE(OUTLYNE,106) OFFB
            CALL SHOWIT(0)
            WRITE(OUTLYNE,107) OFFC
            CALL SHOWIT(0)
         END IF
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5000)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)SF,VERTEX(1,SF),VERTEX(2,SF),VERTEX(3,SF)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5003)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)SF,VERTEX(4,SF),VERTEX(5,SF),VERTEX(6,SF)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5004)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)SF,VERTEX(7,SF),VERTEX(8,SF),VERTEX(9,SF)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5005)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)SF,VERTEX(10,SF),VERTEX(11,SF),VERTEX(12,SF)
         CALL SHOWIT(0)
         RETURN
      END IF
      IF(SQ.EQ.1.AND.WQ.NE.'OBJ'.OR.SQ.EQ.1.AND.&
      &WQ.NE.'ALL'.OR.SQ.EQ.1.AND.WQ.NE.'OB') THEN
         WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(SQ.EQ.0.AND.DF1.EQ.1) THEN
!       OUTPUT IMAGE SURFACE
         SF=NEWIMG
         IF(HEADIN) THEN
            WRITE(OUTLYNE,5001) INT(F12)
            CALL SHOWIT(0)
            WRITE(OUTLYNE,5002) GLSURF
            CALL SHOWIT(0)
            WRITE(OUTLYNE,102) OFFX,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,103) OFFY,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,104) OFFZ,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,105) OFFA
            CALL SHOWIT(0)
            WRITE(OUTLYNE,106) OFFB
            CALL SHOWIT(0)
            WRITE(OUTLYNE,107) OFFC
            CALL SHOWIT(0)
         END IF
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5000)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)SF,VERTEX(1,SF),VERTEX(2,SF),VERTEX(3,SF)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5003)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)SF,VERTEX(4,SF),VERTEX(5,SF),VERTEX(6,SF)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5004)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)SF,VERTEX(7,SF),VERTEX(8,SF),VERTEX(9,SF)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5005)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)SF,VERTEX(10,SF),VERTEX(11,SF),VERTEX(12,SF)
         CALL SHOWIT(0)
         RETURN
      END IF
      IF(SQ.EQ.0.AND.DF1.NE.1) THEN
         I=INT(W1)
         IF(DABS(surf_thickness(I)).GT.1.0D10) THEN
            WRITE(OUTLYNE,*)&
            &'NO GLOBAL RAY DATA EXISTS FOR THE OBJECT SURFACE'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)&
            &'WHICH HAS INFINTE THICKNESS (GREATER THAN 1.0D10)'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
            CALL SHOWIT(1)
            CALL MACFAL
            RETURN
         END IF
         SF=NEWIMG
         IF(I.GT.SF.OR.I.LT.NEWOBJ) THEN
            WRITE(OUTLYNE,*)'SURFACE NUMBER BEYOND LEGAL RANGE'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
            CALL SHOWIT(1)
            CALL MACFAL
            RETURN
         END IF
         IF(HEADIN) THEN
            WRITE(OUTLYNE,5001) INT(F12)
            CALL SHOWIT(0)
            WRITE(OUTLYNE,5002) GLSURF
            CALL SHOWIT(0)
            WRITE(OUTLYNE,102) OFFX,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,103) OFFY,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,104) OFFZ,UNIT
            CALL SHOWIT(0)
            WRITE(OUTLYNE,105) OFFA
            CALL SHOWIT(0)
            WRITE(OUTLYNE,106) OFFB
            CALL SHOWIT(0)
            WRITE(OUTLYNE,107) OFFC
            CALL SHOWIT(0)
         END IF
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5000)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)I,VERTEX(1,I),VERTEX(2,I),VERTEX(3,I)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5003)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)I,VERTEX(4,I),VERTEX(5,I),VERTEX(6,I)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5004)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)I,VERTEX(7,I),VERTEX(8,I),VERTEX(9,I)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,2501)
         CALL SHOWIT(0)
         IF(HEADIN) WRITE(OUTLYNE,5005)
         IF(HEADIN) CALL SHOWIT(0)

         WRITE(OUTLYNE,1500)I,VERTEX(10,I),VERTEX(11,I),VERTEX(12,I)
         CALL SHOWIT(0)
         RETURN
      END IF
1500  FORMAT(I3,1X,G23.15,1X,G23.15,1X,G23.15)
2000  FORMAT(I3,1X,G23.15,1X,G23.15,1X,G23.15)
5000  FORMAT('SURF',7X,'X',23X,'Y',23X,'Z')
5003  FORMAT('SURF',7X,'L(X)',20X,'M(X)',20X,'N(X)')
5004  FORMAT('SURF',7X,'L(Y)',20X,'M(Y)',20X,'N(Y)')
5005  FORMAT('SURF',7X,'L(Z)',20X,'M(Z)',20X,'N(Z)')
5001  FORMAT('CURRENT GLOBAL VERTEX DATA ','&
      &  - (CFG #',I2,')')
5002  FORMAT(&
      &'GLOBAL VERTEX DATA REFERENCED TO SURFACE NUMBER ',I3)
2501  FORMAT(1X)
      RETURN
   END IF
   RETURN
END

! SUB GLBRAY.FOR
SUBROUTINE GLBRAY
!
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_thickness
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE GLBRAY.FOR. THIS SUBROUTINE IMPLEMENTS
!       CREATION OF GLOBAL RAY DATA FOR THE LAST RAY TRACED.
!       IT IS CALLED BY RAYTRA.FOR
!
   INTEGER JK,I
!
   REAL*8 &
   &X1,Y1,Z1,L1,M1,N1,X00,Y00,Z0,LX0,LY0,LZ0,&
   &MX0,MY0,MZ0,NX0,NY0,NZ0,LO1,MO1,NO1,LN1,MN1,NN1
!
!
   IF(DABS(surf_thickness(0)).LE.1.0D10) THEN
!       FINITE OBJECT THICKNESS
      JK=0
   ELSE
!       INFINITE OBJECT THICKNESS
      JK=1
   END IF
!
   DO 10 I=JK,NEWIMG
!
!       NOW TRANSFORM TO THE GLOBAL COORDINATE SYSTEM.
!       THE GLOBAL COORDINATES OF EACH LOCAL COORDINATE
!       SYSTEM ARE:
!
      X00=VERTEX(1,I)
      Y00=VERTEX(2,I)
      Z0=VERTEX(3,I)
      LX0=VERTEX(4,I)
      MX0=VERTEX(5,I)
      NX0=VERTEX(6,I)
      LY0=VERTEX(7,I)
      MY0=VERTEX(8,I)
      NY0=VERTEX(9,I)
      LZ0=VERTEX(10,I)
      MZ0=VERTEX(11,I)
      NZ0=VERTEX(12,I)
!
      X1=X00+((LX0*(RAYRAY(1,I)))+(LY0*(RAYRAY(2,I)))&
      &+(LZ0*(RAYRAY(3,I))))
      Y1=Y00+((MX0*(RAYRAY(1,I)))+(MY0*(RAYRAY(2,I)))&
      &+(MZ0*(RAYRAY(3,I))))
      Z1=Z0+((NX0*(RAYRAY(1,I)))+(NY0*(RAYRAY(2,I)))&
      &+(NZ0*(RAYRAY(3,I))))
!
      L1=((LX0*(RAYRAY(4,I)))+(LY0*(RAYRAY(5,I)))&
      &+(LZ0*(RAYRAY(6,I))))
      M1=((MX0*(RAYRAY(4,I)))+(MY0*(RAYRAY(5,I)))&
      &+(MZ0*(RAYRAY(6,I))))
      N1=((NX0*(RAYRAY(4,I)))+(NY0*(RAYRAY(5,I)))&
      &+(NZ0*(RAYRAY(6,I))))
!
      LO1=((LX0*(RAYRAY(19,I)))+(LY0*(RAYRAY(20,I)))&
      &+(LZ0*(RAYRAY(21,I))))
      MO1=((MX0*(RAYRAY(19,I)))+(MY0*(RAYRAY(20,I)))&
      &+(MZ0*(RAYRAY(21,I))))
      NO1=((NX0*(RAYRAY(19,I)))+(NY0*(RAYRAY(20,I)))&
      &+(NZ0*(RAYRAY(21,I))))
!
      LN1=((LX0*(RAYRAY(13,I)))+(LY0*(RAYRAY(14,I)))&
      &+(LZ0*(RAYRAY(15,I))))
      MN1=((MX0*(RAYRAY(13,I)))+(MY0*(RAYRAY(14,I)))&
      &+(MZ0*(RAYRAY(15,I))))
      NN1=((NX0*(RAYRAY(13,I)))+(NY0*(RAYRAY(14,I)))&
      &+(NZ0*(RAYRAY(15,I))))
!
      GLRAY(1,I)=X1
      GLRAY(2,I)=Y1
      GLRAY(3,I)=Z1
      GLRAY(4,I)=L1
      GLRAY(5,I)=M1
      GLRAY(6,I)=N1
      GLRAY(7,I)=LO1
      GLRAY(8,I)=MO1
      GLRAY(9,I)=NO1
      GLRAY(10,I)=LN1
      GLRAY(11,I)=MN1
      GLRAY(12,I)=NN1
10 CONTINUE
!       ALL GLOBAL TRANSFORMATIONS ARE COMPLETE
!
   RETURN
END
! SUB GETOPD.FOR
SUBROUTINE GETOPD(LEN,LENW,OPDERROR)
   use type_utils, only: real2str
!
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_thickness
   use mod_system, only: sys_units, sys_mode, sys_last_surf, sys_wavelength
   use mod_lens_data_manager, only: ldm
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE GETOPD WHICH IMPLEMENTS THE GET OPD
!       AND GET OPDW
!       COMMANDS AT THE CMD LEVEL.
!
   INTEGER J,JJ
!
   REAL*8 LEN,LENW,WW,WAVE
!
   LOGICAL OPDERROR
!
   INTEGER WWVN
   COMMON/WVPASS/WWVN
   IF(INT(CURLAM).EQ.1) WWVN=46
   IF(INT(CURLAM).EQ.2) WWVN=47
   IF(INT(CURLAM).EQ.3) WWVN=48
   IF(INT(CURLAM).EQ.4) WWVN=49
   IF(INT(CURLAM).EQ.5) WWVN=50
   IF(INT(CURLAM).EQ.6) WWVN=71
   IF(INT(CURLAM).EQ.7) WWVN=72
   IF(INT(CURLAM).EQ.8) WWVN=73
   IF(INT(CURLAM).EQ.9) WWVN=74
   IF(INT(CURLAM).EQ.10) WWVN=75
!
!               CHECK FOR PRESENCE OF STRING,QUALIFIER,OR NUMERIC
!               INPUT AND
!               PRINT ERROR AND RETURN IF DISCOVERED.
!
   IF(RAYEXT.AND.REFEXT) THEN
      LEN=0.0D0
      RCOR=0.0D0
      OCOR=0.0D0
      IF(DABS(surf_thickness(NEWOBJ)).GE.1.0D10) JJ=NEWOBJ+2
      IF(DABS(surf_thickness(NEWOBJ)).LT.1.0D10) JJ=NEWOBJ+1
      DO J=JJ,NEWIMG
         LEN=LEN+RAYRAY(7,J)&
         &-(REFRY(7,J)*(ldm%getSurfIndex(J-1,INT(CURLAM))/ldm%getSurfIndex(J-1,INT(LFOB(4)))))
         ! call LogTermFOR("RAYRAY(7) "//real2str(RAYRAY(7,J)))
         ! call LogTermFOR("REFRY(7) "//real2str(REFRY(7,J)))
         ! call LogTermFOR("LEN "//real2str(LEN))


      END DO
      IF(sys_mode().EQ.1.0D0.OR.sys_mode().EQ.2.0D0) THEN
!       MODE FOCAL
         RCOR=0.0D0
         OCOR=0.0D0
         CALL FOPD
         ! call LogTermFOR("RCOR="//real2str(RCOR))
         ! call LogTermFOR("OCOR="//real2str(OCOR))
         ! call LogTermFOR("LEN="//real2str(LEN))

         LEN=LEN-(OCOR*(ldm%getSurfIndex(NEWOBJ,INT(CURLAM))))&
         &+(RCOR*(ldm%getSurfIndex(NEWOBJ,INT(CURLAM))))
         RCOR=0.0D0
         OCOR=0.0D0
         CENCEN=.FALSE.
         CALL LOPD
         ! call LogTermFOR("RCOR="//real2str(RCOR))
         ! call LogTermFOR("OCOR="//real2str(OCOR))
         ! call LogTermFOR("LEN="//real2str(LEN))

         LEN=LEN-(OCOR*(ldm%getSurfIndex(NEWIMG-1,INT(CURLAM))))&
         &+(RCOR*(ldm%getSurfIndex(NEWIMG-1,INT(CURLAM))))
         ! call LogTermFOR("LENPC="//real2str(LEN))
      ELSE
!       MODE AFOCAL
         RCOR=0.0D0
         OCOR=0.0D0
         CALL FOPD
         LEN=LEN-((OCOR*ldm%getSurfIndex(NEWOBJ,INT(CURLAM))))&
         &+(RCOR*(ldm%getSurfIndex(NEWOBJ,INT(CURLAM))))
         RCOR=0.0D0
         OCOR=0.0D0
         CENCEN=.FALSE.
         CALL LOPD
         ! call LogTermFOR("RCOR="//real2str(RCOR))
         ! call LogTermFOR("OCOR="//real2str(OCOR))
         LEN=LEN-(OCOR*(ldm%getSurfIndex(NEWIMG-1,INT(CURLAM))))&
         &+(RCOR*(ldm%getSurfIndex(NEWIMG-1,INT(CURLAM))))
      END IF
!     CALCULATE LEN IN WAVES AT THE REFERENCE RAY WAVELENGTH
      IF(INT(CURLAM).GE.1.AND.INT(CURLAM).LE.10) THEN
         WW=sys_wavelength(INT(CURLAM))
      END IF
      IF(sys_units().EQ.1.0) WAVE=(WW*1.0D-3)/(25.4D0)
      IF(sys_units().EQ.2.0) WAVE=WW*1.0D-4
      IF(sys_units().EQ.3.0) WAVE=WW*1.0D-3
      IF(sys_units().EQ.4.0) WAVE=WW*1.0D-6
      LEN=-LEN
      IF(REVSTR) LEN=-LEN
      LENW=LEN/WAVE
      OPDERROR=.FALSE.
      RETURN
   ELSE
!       NO RAY EXITS OR NO REF RAY
      IF(.NOT.REFEXT) THEN
         OUTLYNE=&
         &'NO REFERENCE RAY DATA EXISTS, "OPD" CAN NOT BE CALCULATED'
         CALL SHOWIT(1)
         CALL MACFAL
         OPDERROR=.TRUE.
      END IF
      IF(.NOT.RAYEXT) THEN
         OUTLYNE=&
         &'NO RAY DATA EXISTS, "OPD" CAN NOT BE CALCULATED'
         CALL SHOWIT(1)
         CALL MACFAL
         OPDERROR=.TRUE.
      END IF
   END IF
   RETURN
END
! SUB LOPDS.FOR
!         SUBROUTINE LOPDS(REFERR,TPT)
! C
!         USE GLOBALS
!         IMPLICIT NONE
! C
! C       THIS IS SUBROUTINE LOPD.FOR. THIS SUBROUTINE IS
! C       CALLED BY SPD AND COMPAP ROUTINES. IT CALCULATES ADJUSTMENTS TO THE
! C       OPD DUE TO THE IMAGE REFERENCE SPHERE. (FOR AFOCAL
! C       SYSTEMS THIS WILL BE A FLAT REFERENCE SURFACE)
! C
!         REAL*8 XREFI,XO,XOOY,XOOX,YO,YOOX,YOOY,ZO,ZOOX,ZOOY,
!      1  YREFI,RAD,AL,BE,GA,A,B,C,LEN,LEN1,LO,LOOX,LOOY,MO,MOOX,MOOY,
!      2  LEN2,Q,ARG,ZREFI,SIGNB,RL0,RM0,RN0,NO,NOOX,NOOY,THYNUM,THXNUM,
!      3  RRX0,RRZ0,T,RX0,RY0,RZ0,RRY0,M0,L0,N0,XA,THXDEN,THYDEN,
!      4  YA,ZA,LLL,MMM,NNN
! C
!       INTEGER TPT
! C
!         INCLUDE 'DATMAI.INC'
!         INCLUDE 'DATLEN.INC'
!         INCLUDE 'DATSPD.INC'
!         INCLUDE 'DATSP1.INC'
! C
!       LOGICAL REFERR
! C
!         RCOR=0.0D0
!         OCOR=0.0D0
!         REFERR=.FALSE.
! C
! C       CASE OF A PERFECT LENS AT sys_last_surf()-1,OR IDEAL
!       IF(GLANAM(INT(sys_last_surf())-1,2).EQ.'PERFECT      '
!      1.OR.GLANAM(INT(sys_last_surf())-1,2).EQ.'IDEAL        ') THEN
! C     ALWAYS ASSUME FOCAL MODE BUT THERE IS NOTHING TO SUBTRACT OFF
! C     SINCE NOTHING WAS ADDED
! C     EXCEPT FOR OFF AXIS IMAGE POINTS WHERE WAVEFRONT TILT MUST
! C     BE REMOVED AS IN THE CASE OF AFOCAL SYSTEMS. HERE HOWEVER, THE TILTED
! C     PLANE IS AT NEWING-1 RATHER THAN AT NEWIMG
! C       FLAT REFERENCE PLANE
! C       THE SO-CALLED FLAT REFERENCE PLANE IS A PLANE
! C       PERPENDICULAR TO THE REF RAY. THE INTERSECTION
! C       OF THIS REFERENCE PLANE WITH THE REFERENCE RAY OCCURRS
! C       AT THE FINAL SURFACE (NEWIMG-1). WITH THIS DEFINITION,
! C       THE CORRECTION TERM FOR THE REFERENCE RAY IS ALWAYS
! C       ZERO.
!                         RCOR=0.0D0
!                         RX0=REFRY(1,NEWIMG-1)
!                         RY0=REFRY(2,NEWIMG-1)
!                         RZ0=REFRY(3,NEWIMG-1)
!                         RL0=REFRY(19,NEWIMG-1)
!                         RM0=REFRY(20,NEWIMG-1)
!                         RN0=REFRY(21,NEWIMG-1)
! C       NOW THE OTHER RAY:
!                 RRX0=DSPOT(27)
!                 RRY0=DSPOT(28)
!                 RRZ0=DSPOT(29)
!                 L0=DSPOT(30)
!                 M0=DSPOT(31)
!                 N0=DSPOT(32)
! C       THE LINE DIRECTION NUMBERS ARE:
! C
! C       THE PLANE WHICH HAS ITS ORIGIN WHERE THE
! C       REFERENCE RAY INTERSECTS THE IMAGE PLANE-1
! C       AND IS PERPENDICULAR TO THE REFERENCE RAY HAS THE FORM:
! C
! C       (RL0*(X-RX0))+(RM0*(Y-RY0))+(RN0*(Z-RZ0))=0
! C       X,Y AND Z ARE ANY POINTS ON THE PLANE.
! C
! C       NOW DETERMINE THE INTERSECTION OF AN "OTHER" RAY
! C       WITH THIS REFERENCE PLANE.
! C
! C       THE EQUATION OF THE OTHER RAY IS
! C               XA=RRX0+(T*L0)
! C               YA=RRY0+(T*M0)
! C               ZA=RRZ0+(T*N0)
! C THE PARAMETER T IS DETERMINED BY SUBSTITUTING THIS LINE
! C       EQUATION INTO THE REFERENCE SURAFCE EQUATION
! C       AND SOLVING FOR T.
! C
!         T=((RL0*(RX0-RRX0))+(RM0*(RY0-RRY0))+(RN0*(RZ0-RRZ0)))/
!      1  ((RL0*L0)+(RM0*M0)+(RN0*N0))
! C
! C       NOW X,Y AND Z ARE:
!                 XA=RRX0+(T*L0)
!                 YA=RRY0+(T*M0)
!                 ZA=RRZ0+(T*N0)
!         OCOR=DSQRT(
!      1  ((DSPOT(27)-XA)**2)+
!      2  ((DSPOT(28)-YA)**2)+
!      3  ((DSPOT(29)-ZA)**2))
! C     IF T IS LESS THAN ZERO, THE RAY INTERSECTION WITH THE
! C     REFERENCE PLANE LIES ON THE NEGATIVE SIDE OF THE IMAGE SURFACE
! C     AND ZA LT DSPOT(29) AND OCOR MUST BE POSITIVE AND VICE VERSA.
! C       THE CORRECT SIGN IS:
!         IF(ZA.GT.DSPOT(29)) OCOR=-OCOR
!         IF(ZA.LE.DSPOT(29)) OCOR=OCOR
!         REFERR=.FALSE.
!                GO TO 900
!                         END IF
! C
! C       CASE OF AFOCAL SYSTEMS
! C
!         IF(sys_mode().EQ.3.0D0.OR.sys_mode().EQ.4.0D0) THEN
! C
! C       FLAT REFERENCE PLANE
! C       THE SO-CALLED FLAT REFERENCE PLANE IS A PLANE
! C       PERPENDICULAR TO THE REF RAY. THE INTERSECTION
! C       OF THIS REFERENCE PLANE WITH THE REFERENCE RAY OCCURRS
! C       AT THE FINAL SURFACE (NEWIMG). WITH THIS DEFINITION,
! C       THE CORRECTION TERM FOR THE REFERENCE RAY IS ALWAYS
! C       ZERO.
!                         RCOR=0.0D0
!                         RX0=REFRY(1,NEWIMG)
!                         RY0=REFRY(2,NEWIMG)
!                         RZ0=REFRY(3,NEWIMG)
!                         RL0=REFRY(19,NEWIMG)
!                         RM0=REFRY(20,NEWIMG)
!                         RN0=REFRY(21,NEWIMG)
! C       NOW THE OTHER RAY:
!                 RRX0=DSPOT(1)
!                 RRY0=DSPOT(2)
!                 RRZ0=DSPOT(3)
!                 L0=DSPOT(22)
!                 M0=DSPOT(23)
!                 N0=DSPOT(24)
! C       THE LINE DIRECTION NUMBERS ARE:
! C
! C       THE PLANE WHICH HAS ITS ORIGIN WHERE THE
! C       REFERENCE RAY INTERSECTS THE IMAGE PLANE
! C       AND IS PERPENDICULAR TO THE REFERENCE RAY HAS THE FORM:
! C
! C       (RL0*(X-RX0))+(RM0*(Y-RY0))+(RN0*(Z-RZ0))=0
! C       X,Y AND Z ARE ANY POINTS ON THE PLANE.
! C
! C       NOW DETERMINE THE INTERSECTION OF AN "OTHER" RAY
! C       WITH THIS REFERENCE PLANE.
! C
! C       THE EQUATION OF THE OTHER RAY IS
! C               XA=RRX0+(T*L0)
! C               YA=RRY0+(T*M0)
! C               ZA=RRZ0+(T*N0)
! C THE PARAMETER T IS DETERMINED BY SUBSTITUTING THIS LINE
! C       EQUATION INTO THE REFERENCE SURAFCE EQUATION
! C       AND SOLVING FOR T.
! C
!         T=((RL0*(RX0-RRX0))+(RM0*(RY0-RRY0))+(RN0*(RZ0-RRZ0)))/
!      1  ((RL0*L0)+(RM0*M0)+(RN0*N0))
! C
! C       NOW X,Y AND Z ARE:
!                 XA=RRX0+(T*L0)
!                 YA=RRY0+(T*M0)
!                 ZA=RRZ0+(T*N0)
!         OCOR=DSQRT(
!      1  ((DSPOT(1)-XA)**2)+
!      2  ((DSPOT(2)-YA)**2)+
!      3  ((DSPOT(3)-ZA)**2))
! C     IF T IS LESS THAN ZERO, THE RAY INTERSECTION WITH THE
! C     REFERENCE PLANE LIES ON THE NEGATIVE SIDE OF THE IMAGE SURFACE
! C     AND ZA LT DSPOT(3) AND OCOR MUST BE POSITIVE AND VICE VERSA.
! C       THE CORRECT SIGN IS:
!         IF(ZA.GT.DSPOT(3)) OCOR=-OCOR
!         IF(ZA.LE.DSPOT(3)) OCOR=OCOR
!         REFERR=.FALSE.
!                GO TO 900
!                         END IF
! C
! C     FOCAL SYSTEMS
! C
!         IF(sys_mode().EQ.1.0D0.OR.sys_mode().EQ.2.0D0) THEN
! C       SYSTEM FOCAL.
!       IF(.NOT.EXPAUT.OR.EXPAUT.AND..NOT.LDIF2) THEN
! C       THE REFERENCE SPHERE IS CENTERED WHERE THE REAL CHIEF
! C       RAY CROSSES THE FINAL SURFACE.
! C       THE RADIUS IS EQUAL
! C       TO THE DISTANCE FROM THE FINAL IMAGE SURFACE TO THE SURFACE
! C       PRECEEDING THE IMAGE SURFACE IF THE I-1 THICKNESS IS NON-ZERO
! C       AND IS THE DISTANCE TO THE PARAXIAL EXIT PUPIL IF TH (I-1)=0
! C       THIS IS JUST AS IN ACCOS V AND
! C       HEXAGON AND GIVES THE USER THE CHOICE FOR RADIUS. BY USING
! C       PIKUPS (NOT AVAILABLE IN CODE V), A WIDE VARIETY OF REFERENCE
! C       SURFACES MAY BE SELECTED.
! C
! C     IF EXPAUT AND NOT LDIF2, AN ASTOP EX IS DONE EVEN IF THE I-1
! C     THICKNESS IS NOT ZERO.
! C
! C       COORDINATES OF THE REAL CHIEF RAY AT THE IMAGE PLANE ARE:
! C       THIS IS THE REFERENCE SPHERE CENTER LOCATION.
!         XREFI=REFRY(1,NEWIMG)
!         YREFI=REFRY(2,NEWIMG)
!         ZREFI=REFRY(3,NEWIMG)
!         !call logger%logTextWithNum("XREFI=",XREFI)
!         !call logger%logTextWithNum("YREFI=",YREFI)
!         !call logger%logTextWithNum("ZREFI=",ZREFI)
!
!
!         IF(surf_thickness(NEWIMG-1).EQ.0.0D0.OR.surf_thickness(NEWIMG-1).NE.
!      10.0D0.AND..NOT.LDIF2) THEN
! C       DIST FROM I-1 TO I IS ZERO OF LDIF2 IS FALSE AND DIST NOT 0
! C       DO AN INTERNAL "ASTOP EX" ADJUSTMENT
!         IF(DABS(PXTRAY(5,NEWIMG)*1.0D-15).LT.
!      1DABS(PXTRAY(6,NEWIMG))) THEN
!               RAD=(PXTRAY(5,NEWIMG)/PXTRAY(6,NEWIMG))
!               RREF=RAD
!
!         END IF
!         IF(DABS(PXTRAY(5,NEWIMG)*1.0D-15).GE.
!      1DABS(PXTRAY(6,NEWIMG))) THEN
! C       REF RAY IS TELECENTRIC, SET RAD INFINITY
!             RAD=1.0D20
!             RREF=RAD
!         END IF
! C       USE EXISTING THICKNESS OF NEWIMG-1 AS RAD
!         ELSE
!         RAD=ALENS(3,NEWIMG-1)
!         RREF=RAD
!                         END IF
! C
! C       NOW WE HAVE LOCATION OF REFERENCE SPHERE CENTER
! C       AND ITS RADIUS
! C
! C       THE CHIEF RAY INTERSECTS THE REFERENCE SPHERE
! C       THE LENGTH FROM THIS INTERSECTION TO THE INTERSECTION
! C       OF THE REFERENCE RAY WITH THE FINAL SURFACE IS RCOR=RAD
! C       REFERENCE RAY INTERSECTION WITH THE TANGENT PLANE IS:
! C
!         RCOR=RAD
! C
! C       THE LENGTH FROM THE REFERENCE SPHERE
! C       TO THE FINAL SURFACE ALONG THE "OTHER" RAY IS:
! C
!         !call logger%logTextWithNum("Ref Sphere Radius is ",RAD)
!         !call logger%logTextWithNum("Ref Sphere Distance is ",RCOR)
!
!         AL=DSPOT(1)-XREFI
!         BE=DSPOT(2)-YREFI
!         GA=DSPOT(3)-ZREFI
!         C=(AL**2)+(BE**2)+(GA**2)-(RAD**2)
!         B=2.0D0*((DSPOT(22)*AL)+
!      1    (DSPOT(23)*BE)+
!      2    (DSPOT(24)*GA))
!         A=1.0D0
! C       SOLVE FOR LEN
!         IF(B.NE.0.0D0) SIGNB=((DABS(B))/(B))
!         IF(B.EQ.0.0D0) SIGNB=1.0D0
!                 IF(A.EQ.0.0D0) THEN
!                         LEN=-(C/B)
!                       ELSE
!         ARG=((B**2)-(4.0D0*A*C))
!         IF(ARG.LT.0.0D0) THEN
!       IF(TPT.EQ.1) THEN
!         PRINT *, "A=", A
!         PRINT *, "B=", B
!         PRINT *, "C=", C
!         PRINT *, "ARG=", ARG
!         OUTLYNE='RAY(S) COULD NOT INTERSECT REFERENCE SPHERE'
!       CALL SHOWIT(1)
!         OUTLYNE=
!      1  'TRY USING AN "ASTOP EX" OR ASTOP "EN/EX" ADJUSTMENT'
!       CALL SHOWIT(1)
!         OUTLYNE=
!      1  'OPD VALUES MAY BE SUSPECT'
!       CALL SHOWIT(1)
!                        END IF
!               OCOR=0.0D0
!               RCOR=0.0D0
!         REFERR=.TRUE.
!                         RETURN
! C       REFERENCE SPHERE INTERSECTED
!                         END IF
!         Q=(-0.5D0*(B+(SIGNB*(DSQRT((B**2)-(4.0D0*A*C))))))
!                         LEN1=C/Q
!                         LEN2=Q/A
!           IF(REFRY(6,NEWIMG).GT.0.0D0) THEN
!         IF(RAD.GT.0.0D0) THEN
! C     THEN THE INTERSECTION TO USE IS THE NEGATIVE INTERSECTION
!         IF(LEN1.LT.0.0D0) LEN=LEN1
!         IF(LEN2.LT.0.0D0) LEN=LEN2
!                         ELSE
! C       RAD NEG
! C     THEN THE INTERSECTION TO USE IS THE POSITIVE INTERSECTION
!         IF(LEN1.GT.0.0D0) LEN=LEN1
!         IF(LEN2.GT.0.0D0) LEN=LEN2
!                         END IF
!                         END IF
!           IF(REFRY(6,NEWIMG).LT.0.0D0) THEN
!         IF(RAD.GT.0.0D0) THEN
! C     THEN THE INTERSECTION TO USE IS THE NEGATIVE INTERSECTION
!         IF(LEN1.LT.0.0D0) LEN=-LEN2
!         IF(LEN2.LT.0.0D0) LEN=-LEN1
!                         ELSE
! C       RAD NEG
! C     THEN THE INTERSECTION TO USE IS THE POSITIVE INTERSECTION
!         IF(LEN1.GT.0.0D0) LEN=-LEN2
!         IF(LEN2.GT.0.0D0) LEN=-LEN1
!                         END IF
!                         END IF
!                         END IF
! C       NEGATIVE SIGN SINCE LEN1 AND LEN2 MEASURES DIRECTED
! C       DISTANCE FROM IMAGE TO SPHERE INTERSECTION AND
! C       LEN IS DIRECTED FROM SPHERE INTERSECTION TO IMAGE
!
!         OCOR=-LEN
!         REFERR=.FALSE.
!                    GO TO 900
! C     EXPAUT NOT FALSE
!                       END IF
!       IF(EXPAUT) THEN
! C       THE REFERENCE SPHERE IS CENTERED WHERE THE REAL CHIEF
! C       RAY CROSSES THE FINAL SURFACE.
! C       THE RADIUS IS EQUAL
! C       TO THE DISTANCE FROM POINT TO WHERE THE CHIEF RAY CROSSES THE REAL
! C     EXIT PUPIL
! C       THIS IS JUST AS IN CODE-V AND IS THE DEFAULT WHEN THE PROGRAM
! C     BEGINS
! C
! C       COORDINATES OF THE REAL CHIEF RAY AT THE IMAGE PLANE ARE:
! C       THIS IS THE REFERENCE SPHERE CENTER LOCATION.
!         XREFI=REFRY(1,NEWIMG)
!         YREFI=REFRY(2,NEWIMG)
!         ZREFI=REFRY(3,NEWIMG)
! C
! C       DO A REAL RAY INTERNAL EXIT PUPIL ADJUSTMENT
! C
!           XO=REFRY(1,NEWIMG)
!           YO=REFRY(2,NEWIMG)
!           ZO=REFRY(3,NEWIMG)
!           LO=REFRY(4,NEWIMG)
!           MO=REFRY(5,NEWIMG)
!           NO=REFRY(6,NEWIMG)
!           XOOX=RFDIFF(1,NEWIMG)
!           YOOX=RFDIFF(2,NEWIMG)
!           ZOOX=RFDIFF(3,NEWIMG)
!           LOOX=RFDIFF(4,NEWIMG)
!           MOOX=RFDIFF(5,NEWIMG)
!           NOOX=RFDIFF(6,NEWIMG)
!           XOOY=RFDIFF(7,NEWIMG)
!           YOOY=RFDIFF(8,NEWIMG)
!           ZOOY=RFDIFF(9,NEWIMG)
!           LOOY=RFDIFF(10,NEWIMG)
!           MOOY=RFDIFF(11,NEWIMG)
!           NOOY=RFDIFF(12,NEWIMG)
!       THXNUM=((XO-XOOX)*(LO-LOOX))+((YO-YOOX)*(MO-MOOX))
!      1+((ZO-ZOOX)*(NO-NOOX))
!       THYNUM=((XO-XOOY)*(LO-LOOY))+((YO-YOOY)*(MO-MOOY))
!      1+((ZO-ZOOY)*(NO-NOOY))
!       THXDEN=((LO-LOOX)**2)+((MO-MOOX)**2)
!      1+((NO-NOOX)**2)
!       THYDEN=((LO-LOOY)**2)+((MO-MOOY)**2)
!      1+((NO-NOOY)**2)
!         IF(DABS(THXNUM*1.0D-15).LT.DABS(THXDEN).AND.
!      1DABS(THYNUM*1.0D-15).LT.
!      1DABS(THYDEN)) THEN
!       RAD=-((-THXNUM/THXDEN)+(-THYNUM/THYDEN))/2.0D0
!         RREF=RAD
! C     THE EXIT PUPIL IS LOCATED AT:
!                XA=XO+(-RAD*LO)
!                YA=YO+(-RAD*MO)
!                ZA=ZO+(-RAD*NO)
!       RAD=DSQRT(
!      1((XA-XREFI)**2)+((YA-YREFI)**2)+((ZA-ZREFI)**2)
!      1)
!         RREF=RAD
!       IF(ZA.LE.ZO) THEN
! C     PUPIL LIES ON THE NEGATIVE SIDE OF NEWIMG SO RAD IS POS
!         RAD=RAD
!         RREF=RAD
!                       ELSE
!       RAD=-RAD
!         RREF=RAD
!                       END IF
!                         END IF
!         IF(DABS(THXNUM*1.0D-15).GE.DABS(THXDEN).OR.
!      1DABS(THYNUM*1.0D-15).GE.
!      1DABS(THYDEN)) THEN
! C       REF RAY IS TELECENTRIC, SET RAD INFINITY
! C       FLAT REFERENCE PLANE
!                        RAD=1.0D20
!         RREF=RAD
!                         END IF
! C
! C       NOW WE HAVE LOCATION OF REFERENCE SPHERE CENTER
! C       AND ITS RADIUS MAGNITUDE
! C
! C       THE CHIEF RAY INTERSECTS THE REFERENCE SPHERE
! C       THE LENGTH FROM THIS INTERSECTION TO THE INTERSECTION
! C       OF THE REFERENCE RAY WITH THE FINAL SURFACE IS RCOR=RAD
! C       REFERENCE RAY INTERSECTION WITH THE TANGENT PLANE IS:
! C
!         RCOR=RAD
! C
! C       THE LENGTH FROM THE REFERENCE SPHERE
! C       TO THE FINAL SURFACE ALONG THE "OTHER" RAY IS:
! C
!                 LLL=DSPOT(22)
!                 MMM=DSPOT(23)
!                 NNN=DSPOT(24)
!         AL=DSPOT(1)-XREFI
!         BE=DSPOT(2)-YREFI
!         GA=DSPOT(3)-ZREFI
!         C=(AL**2)+(BE**2)+(GA**2)-(RAD**2)
!         B=2.0D0*((LLL*AL)+
!      1    (MMM*BE)+
!      2    (NNN*GA))
!         A=1.0D0
! C       SOLVE FOR LEN
!         IF(B.NE.0.0D0) SIGNB=((DABS(B))/(B))
!         IF(B.EQ.0.0D0) SIGNB=1.0D0
!                 IF(A.EQ.0.0D0) THEN
!                         LEN=-(C/B)
!                       ELSE
!         ARG=((B**2)-(4.0D0*A*C))
!         IF(ARG.LT.0.0D0) THEN
!       IF(TPT.EQ.1) THEN
!         OUTLYNE='RAY(S) COULD NOT INTERSECT REFERENCE SPHERE'
!       CALL SHOWIT(1)
!         OUTLYNE=
!      1  'THE CURRENT SYSTEM MAY HAVE EXCESSIVE ABERRATIONS'
!       CALL SHOWIT(1)
!         OUTLYNE=
!      1  'OPD VALUES MAY BE SUSPECT'
!       CALL SHOWIT(1)
!                        END IF
!               OCOR=0.0D0
!               RCOR=0.0D0
!         REFERR=.TRUE.
!                         RETURN
! C       REFERENCE SPHERE INTERSECTED
!                         END IF
!         Q=(-0.5D0*(B+(SIGNB*(DSQRT((B**2)-(4.0D0*A*C))))))
!                         LEN1=C/Q
!                         LEN2=Q/A
!       IF(REFRY(6,NEWIMG).GT.0.0D0) THEN
!         IF(RAD.GT.0.0D0) THEN
! C     THEN THE INTERSECTION TO USE IS THE NEGATIVE INTERSECTION
!         IF(LEN1.LT.0.0D0) LEN=LEN1
!         IF(LEN2.LT.0.0D0) LEN=LEN2
!                         ELSE
! C       RAD NEG
! C     THEN THE INTERSECTION TO USE IS THE POSITIVE INTERSECTION
!         IF(LEN1.GT.0.0D0) LEN=LEN1
!         IF(LEN2.GT.0.0D0) LEN=LEN2
!                         END IF
!                         END IF
!       IF(REFRY(6,NEWIMG).LT.0.0D0) THEN
!         IF(RAD.GT.0.0D0) THEN
! C     THEN THE INTERSECTION TO USE IS THE NEGATIVE INTERSECTION
!         IF(LEN1.LT.0.0D0) LEN=-LEN2
!         IF(LEN2.LT.0.0D0) LEN=-LEN1
!                         ELSE
! C       RAD NEG
! C     THEN THE INTERSECTION TO USE IS THE POSITIVE INTERSECTION
!         IF(LEN1.GT.0.0D0) LEN=-LEN2
!         IF(LEN2.GT.0.0D0) LEN=-LEN1
!                         END IF
!                         END IF
!                         END IF
! C       NEGATIVE SIGN SINCE LEN1 AND LEN2 MEASURES DIRECTED
! C       DISTANCE FROM IMAGE TO SPHERE INTERSECTION AND
! C       LEN IS DIRECTED FROM SPHERE INTERSECTION TO IMAGE
!         OCOR=-LEN
!         REFERR=.FALSE.
!                        GO TO 900
! C     EXPAUT NOT TRUE
!                       END IF
!         REFERR=.FALSE.
! C     NOT FOCAL
!                        GO TO 900
!                         END IF
!         REFERR=.FALSE.
!  900                   CONTINUE
!       IF(DABS(RCOR).GT.1.0D10.OR.DABS(OCOR).GT.1.0D10) THEN
! C     INFINITE REFERENCE SPHERE
!       RCOR=0.0D0
!       IF(DABS(RCOR).GT.1.0D10.OR.DABS(OCOR).GT.1.0D10) THEN
! C     INFINITE REFERENCE SPHERE
!       RCOR=0.0D0
! C     OCOR IS THE DISTANCE ALONG THE RAY BETWEEN AN INTERSECTION
! C     WITH A PLANE PERPENDICULAR TO A PARALLEL RAY WHICH PASSES
! C     THROUGH A POINT ON THE IMAGE SURFACE WHERE THE CHIEF RAY
! C     HITS
!                         RCOR=0.0D0
!                         RCOR=0.0D0
!                         RX0=REFRY(1,NEWIMG-1)
!                         RY0=REFRY(2,NEWIMG-1)
!                         RZ0=REFRY(3,NEWIMG-1)
!                         RL0=DSPOT(30)
!                         RM0=DSPOT(31)
!                         RN0=DSPOT(32)
! C       NOW THE OTHER RAY:
!                 RRX0=DSPOT(27)
!                 RRY0=DSPOT(28)
!                 RRZ0=DSPOT(29)
!                 L0=DSPOT(30)
!                 M0=DSPOT(31)
!                 N0=DSPOT(32)
! C       THE LINE DIRECTION NUMBERS ARE:
! C
! C       THE PLANE WHICH HAS ITS ORIGIN WHERE THE
! C       REFERENCE RAY INTERSECTS THE IMAGE PLANE
! C       AND IS PERPENDICULAR TO THE REGULAR RAY HAS THE FORM:
! C
! C       (RL0*(X-RX0))+(RM0*(Y-RY0))+(RN0*(Z-RZ0))=0
! C       X,Y AND Z ARE ANY POINTS ON THE PLANE.
! C       NOW DETERMINE THE INTERSECTION OF AN "OTHER" RAY
! C       WITH THIS REFERENCE PLANE.
! C
! C       THE EQUATION OF THE OTHER RAY IS
! C               XA=RRX0+(T*L0)
! C               YA=RRY0+(T*M0)
! C               ZA=RRZ0+(T*N0)
! C THE PARAMETER T IS DETERMINED BY SUBSTITUTING THIS LINE
! C       EQUATION INTO THE REFERENCE SURAFCE EQUATION
! C       AND SOLVING FOR T.
! C
!         T=((RL0*(RX0-RRX0))+(RM0*(RY0-RRY0))+(RN0*(RZ0-RRZ0)))/
!      1  ((RL0*L0)+(RM0*M0)+(RN0*N0))
! C
! C       NOW X,Y AND Z ARE:
!                 XA=RRX0+(T*L0)
!                 YA=RRY0+(T*M0)
!                 ZA=RRZ0+(T*N0)
!         OCOR=DSQRT(
!      1  ((DSPOT(27)-XA)**2)+
!      2  ((DSPOT(28)-YA)**2)+
!      3  ((DSPOT(29)-ZA)**2))
! C     IF T IS LESS THAN ZERO, THE RAY INTERSECTION WITH THE
! C     REFERENCE PLANE LIES ON THE NEGATIVE SIDE OF THE IMAGE SURFACE
! C     AND ZA LT DSPOT(29) AND OCOR MUST BE POSITIVE AND VICE VERSA.
! C       THE CORRECT SIGN IS:
!         IF(ZA.GT.DSPOT(29)) OCOR=-OCOR
!         IF(ZA.LE.DSPOT(29)) OCOR=OCOR
!                        ELSE
!                        END IF
!                        ELSE
!                        END IF
!                         RETURN
!                         END
!  SUB LOPD.FOR
SUBROUTINE LOPD
!
   use DATSPD
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_thickness
   use mod_system, only: sys_last_surf, sys_mode
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE LOPD.FOR. THIS SUBROUTINE IS
!       CALLED BY FANS AND OTHER ROUTINES. IT CALCULATES ADJUSTMENTS TO THE
!       OPD DUE TO THE IMAGE REFERENCE SPHERE. (FOR AFOCAL
!       SYSTEMS THIS WILL BE A FLAT REFERENCE SURFACE)
!
   REAL*8 XREFI,XO,XOOY,XOOX,YO,YOOX,YOOY,ZO,ZOOX,ZOOY,&
   &YREFI,RAD,AL,BE,GA,A,B,C,LEN,LEN1,LO,LOOX,LOOY,MO,MOOX,MOOY,&
   &LEN2,Q,ARG,ZREFI,SIGNB,RL0,RM0,RN0,NO,NOOX,NOOY,THYNUM,THXNUM,&
   &RRX0,RRZ0,T,RX0,RY0,RZ0,RRY0,M0,L0,N0,XA,THXDEN,THYDEN,&
   &YA,ZA,LLL,MMM,NNN
!
!
   RCOR=0.0D0
   OCOR=0.0D0
!
!       CASE OF A PERFECT LENS AT sys_last_surf()-1
!     OR IDEAL LENS
   IF(GLANAM(INT(sys_last_surf())-1,2).EQ.'PERFECT      '&
   &.OR.GLANAM(INT(sys_last_surf())-1,2).EQ.'IDEAL        ') THEN
!     ALWAYS ASSUME FOCAL MODE BUT THERE IS NOTHING TO SUBTRACT OFF
!     SINCE NOTHING WAS ADDED
!     EXCEPT FOR OFF AXIS IMAGE POINTS WHERE WAVEFRONT TILT MUST
!     BE REMOVED AS IN THE CASE OF AFOCAL SYSTEMS. hERE HOWEVER, THE TILTED
!     PLANE IS AT NEWING-1 RATHER THAN AT NEWIMG
!       FLAT REFERENCE PLANE
!       THE SO-CALLED FLAT REFERENCE PLANE IS A PLANE
!       PERPENDICULAR TO THE REF RAY. THE INTERSECTION
!       OF THIS REFERENCE PLANE WITH THE REFERENCE RAY OCCURRS
!       AT THE FINAL SURFACE-1 (NEWIMG-1). WITH THIS DEFINITION,
!       THE CORRECTION TERM FOR THE REFERENCE RAY IS ALWAYS
!       ZERO.
      RCOR=0.0D0
      RX0=REFRY(1,NEWIMG-1)
      RY0=REFRY(2,NEWIMG-1)
      RZ0=REFRY(3,NEWIMG-1)
      RL0=REFRY(19,NEWIMG-1)
      RM0=REFRY(20,NEWIMG-1)
      RN0=REFRY(21,NEWIMG-1)
!       NOW THE OTHER RAY:
      RRX0=RAYRAY(1,NEWIMG-1)
      RRY0=RAYRAY(2,NEWIMG-1)
      RRZ0=RAYRAY(3,NEWIMG-1)
      L0=RAYRAY(19,NEWIMG-1)
      M0=RAYRAY(20,NEWIMG-1)
      N0=RAYRAY(21,NEWIMG-1)
!       THE LINE DIRECTION NUMBERS ARE:
!
!       THE PLANE WHICH HAS ITS ORIGIN WHERE THE
!       REFERENCE RAY INTERSECTS THE IMAGE PLANE
!       AND IS PERPENDICULAR TO THE REFERENCE RAY HAS THE FORM:
!
!       (RL0*(X-RX0))+(RM0*(Y-RY0))+(RN0*(Z-RZ0))=0
!       X,Y AND Z ARE ANY POINTS ON THE PLANE.
!
!       NOW DETERMINE THE INTERSECTION OF AN "OTHER" RAY
!       WITH THIS REFERENCE PLANE.
!
!       THE EQUATION OF THE OTHER RAY IS
!               XA=RRX0+(T*L0)
!               YA=RRY0+(T*M0)
!               ZA=RRZ0+(T*N0)
! THE PARAMETER T IS DETERMINED BY SUBSTITUTING THIS LINE
!       EQUATION INTO THE REFERENCE SURAFCE EQUATION
!       AND SOLVING FOR T.
!
      T=((RL0*(RX0-RRX0))+(RM0*(RY0-RRY0))+(RN0*(RZ0-RRZ0)))/&
      &((RL0*L0)+(RM0*M0)+(RN0*N0))
!
!       NOW X,Y AND Z ARE:
      XA=RRX0+(T*L0)
      YA=RRY0+(T*M0)
      ZA=RRZ0+(T*N0)
      OCOR=DSQRT(&
      &((RAYRAY(1,NEWIMG-1)-XA)**2)+&
      &((RAYRAY(2,NEWIMG-1)-YA)**2)+&
      &((RAYRAY(3,NEWIMG-1)-ZA)**2))
!     IF T IS LESS THAN ZERO, THE RAY INTERSECTION WITH THE
!     REFERENCE PLANE LIES ON THE NEGATIVE SIDE OF THE IMAGE SURFACE
!     AND ZA LT RAYRAY(3,NEWIMG-1) AND OCOR MUST BE POSITIVE AND VICE VERSA.
!       THE CORRECT SIGN IS:
      IF(ZA.GT.RAYRAY(3,NEWIMG-1)) OCOR=-OCOR
      IF(ZA.LE.RAYRAY(3,NEWIMG-1)) OCOR=OCOR
      GO TO 900
   END IF
!
!       CASE OF AFOCAL SYSTEMS
!
   IF(sys_mode().EQ.3.0D0.OR.sys_mode().EQ.4.0D0) THEN
!
!       FLAT REFERENCE PLANE
!       THE SO-CALLED FLAT REFERENCE PLANE IS A PLANE
!       PERPENDICULAR TO THE REF RAY. THE INTERSECTION
!       OF THIS REFERENCE PLANE WITH THE REFERENCE RAY OCCURRS
!       AT THE FINAL SURFACE (NEWIMG). WITH THIS DEFINITION,
!       THE CORRECTION TERM FOR THE REFERENCE RAY IS ALWAYS
!       ZERO.
      RCOR=0.0D0
      RX0=REFRY(1,NEWIMG)
      RY0=REFRY(2,NEWIMG)
      RZ0=REFRY(3,NEWIMG)
      RL0=REFRY(19,NEWIMG)
      RM0=REFRY(20,NEWIMG)
      RN0=REFRY(21,NEWIMG)
!       NOW THE OTHER RAY:
      RRX0=RAYRAY(1,NEWIMG)
      RRY0=RAYRAY(2,NEWIMG)
      RRZ0=RAYRAY(3,NEWIMG)
      L0=RAYRAY(19,NEWIMG)
      M0=RAYRAY(20,NEWIMG)
      N0=RAYRAY(21,NEWIMG)
!
!       THE PLANE WHICH HAS ITS ORIGIN WHERE THE
!       REFERENCE RAY INTERSECTS THE IMAGE PLANE
!       AND IS PERPENDICULAR TO THE REFERENCE RAY HAS THE FORM:
!
!       (RL0*(X-RX0))+(RM0*(Y-RY0))+(RN0*(Z-RZ0))=0
!       X,Y AND Z ARE ANY POINTS ON THE PLANE.
!
!       NOW DETERMINE THE INTERSECTION OF AN "OTHER" RAY
!       WITH THIS REFERENCE PLANE.
!
!       THE EQUATION OF THE OTHER RAY IS
!               XA=RRX0+(T*L0)
!               YA=RRY0+(T*M0)
!               ZA=RRZ0+(T*N0)
! THE PARAMETER T IS DETERMINED BY SUBSTITUTING THIS LINE
!       EQUATION INTO THE REFERENCE SURAFCE EQUATION
!       AND SOLVING FOR T.
!
      T=((RL0*(RX0-RRX0))+(RM0*(RY0-RRY0))+(RN0*(RZ0-RRZ0)))/&
      &((RL0*L0)+(RM0*M0)+(RN0*N0))
!
!       NOW X,Y AND Z ARE:
      XA=RRX0+(T*L0)
      YA=RRY0+(T*M0)
      ZA=RRZ0+(T*N0)
      OCOR=DSQRT(&
      &((RAYRAY(1,NEWIMG)-XA)**2)+&
      &((RAYRAY(2,NEWIMG)-YA)**2)+&
      &((RAYRAY(3,NEWIMG)-ZA)**2))
!     IF T IS LESS THAN ZERO, THE RAY INTERSECTION WITH THE
!     REFERENCE PLANE LIES ON THE NEGATIVE SIDE OF THE IMAGE SURFACE
!     AND ZA LT RAYRAY(3,NEWIMG) AND OCOR MUST BE POSITIVE AND VICE VERSA.
!       THE CORRECT SIGN IS:
      IF(ZA.GT.RAYRAY(3,NEWIMG)) OCOR=-OCOR
      IF(ZA.LE.RAYRAY(3,NEWIMG)) OCOR=OCOR
      GO TO 900
   END IF
!
!     FOCAL SYSTEMS
!
   IF(sys_mode().EQ.1.0D0.OR.sys_mode().EQ.2.0D0) THEN
!       SYSTEM FOCAL.
      IF(.NOT.EXPAUT.OR.EXPAUT.AND..NOT.LDIF2) THEN
!       THE REFERENCE SPHERE IS CENTERED WHERE THE REAL CHIEF
!       RAY CROSSES THE FINAL SURFACE.
!       THE RADIUS IS EQUAL
!       TO THE DISTANCE FROM THE FINAL IMAGE SURFACE TO THE SURFACE
!       PRECEEDING THE IMAGE SURFACE IF THE I-1 THICKNESS IS NON-ZERO
!       AND IS THE DISTANCE TO THE PARAXIAL EXIT PUPIL IF TH (I-1)=0
!       THIS IS JUST AS IN ACCOS V AND
!       HEXAGON AND GIVES THE USER THE CHOICE FOR RADIUS. BY USING
!       PIKUPS, A WIDE VARIETY OF REFERENCE
!       SURFACES MAY BE SELECTED.
!
!     IF EXPAUT AND NOT LDIF2, AN ASTOP EX IS DONE EVEN IF THE I-1
!     THICKNESS IS NOT ZERO.
!
!       COORDINATES OF THE REAL CHIEF RAY AT THE IMAGE PLANE ARE:
!       THIS IS THE REFERENCE SPHERE CENTER LOCATION.
         XREFI=REFRY(1,NEWIMG)
         YREFI=REFRY(2,NEWIMG)
         ZREFI=REFRY(3,NEWIMG)
         IF(surf_thickness(NEWIMG-1).EQ.0.0D0.OR.surf_thickness(NEWIMG-1).NE.&
         &0.0D0.AND..NOT.LDIF2) THEN
!       DIST FROM I-1 TO I IS ZERO OF LDIF2 IS FALSE AND DIST NOT 0
!       DO AN INTERNAL "ASTOP EX" ADJUSTMENT
            IF(DABS(PXTRAY(5,NEWIMG)*1.0D-15).LT.&
            &DABS(PXTRAY(6,NEWIMG))) THEN
               RAD=(PXTRAY(5,NEWIMG)/PXTRAY(6,NEWIMG))
            END IF
            IF(DABS(PXTRAY(5,NEWIMG)*1.0D-15).GE.&
            &DABS(PXTRAY(6,NEWIMG))) THEN
!       REF RAY IS TELECENTRIC, SET RAD = 1.0D20
               RAD=1.0D20
            END IF
!       USE EXISTING THICKNESS OF NEWIMG-1 AS RAD
         ELSE
            RAD=surf_thickness(NEWIMG-1)
         END IF
!
!       NOW WE HAVE LOCATION OF REFERENCE SPHERE CENTER
!       AND ITS RADIUS
!
!       THE CHIEF RAY INTERSECTS THE REFERENCE SPHERE
!       THE LENGTH FROM THIS INTERSECTION TO THE INTERSECTION
!       OF THE REFERENCE RAY WITH THE FINAL SURFACE IS RCOR=RAD
!       REFERENCE RAY INTERSECTION WITH THE TANGENT PLANE IS:
!
         RCOR=RAD
!
!       THE LENGTH FROM THE REFERENCE SPHERE
!       TO THE FINAL SURFACE ALONG THE "OTHER" RAY IS:
!
         AL=RAYRAY(1,NEWIMG)-XREFI
         BE=RAYRAY(2,NEWIMG)-YREFI
         GA=RAYRAY(3,NEWIMG)-ZREFI
         C=(AL**2)+(BE**2)+(GA**2)-(RAD**2)
         B=2.0D0*((RAYRAY(19,NEWIMG)*AL)+&
         &(RAYRAY(20,NEWIMG)*BE)+&
         &(RAYRAY(21,NEWIMG)*GA))
         A=1.0D0
!       SOLVE FOR LEN
         IF(B.NE.0.0D0) SIGNB=((DABS(B))/(B))
         IF(B.EQ.0.0D0) SIGNB=1.0D0
         IF(A.EQ.0.0D0) THEN
            LEN=-(C/B)
         ELSE
            ARG=((B**2)-(4.0D0*A*C))
            IF(ARG.LT.0.0D0) THEN
               OUTLYNE='RAY(S) COULD NOT INTERSECT REFERENCE SPHERE'
               CALL SHOWIT(1)
               OUTLYNE=&
               &'TRY USING AN "ASTOP EX" OR ASTOP "EN/EX" ADJUSTMENT'
               CALL SHOWIT(1)
               OUTLYNE=&
               &'OPD VALUES MAY BE SUSPECT'
               CALL SHOWIT(1)
               OCOR=0.0D0
               RCOR=0.0D0
               RETURN
!       REFERENCE SPHERE INTERSECTED
            END IF
            Q=(-0.5D0*(B+(SIGNB*(DSQRT((B**2)-(4.0D0*A*C))))))
            LEN1=C/Q
            LEN2=Q/A
            IF(REFRY(6,NEWIMG).GT.0.0D0) THEN
               IF(RAD.GT.0.0D0) THEN
!     THEN THE INTERSECTION TO USE IS THE NEGATIVE INTERSECTION
                  IF(LEN1.LT.0.0D0) LEN=LEN1
                  IF(LEN2.LT.0.0D0) LEN=LEN2
               ELSE
!       RAD NEG
!     THEN THE INTERSECTION TO USE IS THE POSITIVE INTERSECTION
                  IF(LEN1.GT.0.0D0) LEN=LEN1
                  IF(LEN2.GT.0.0D0) LEN=LEN2
               END IF
            END IF
            IF(REFRY(6,NEWIMG).LT.0.0D0) THEN
               IF(RAD.GT.0.0D0) THEN
!     THEN THE INTERSECTION TO USE IS THE NEGATIVE INTERSECTION
                  IF(LEN1.LT.0.0D0) LEN=-LEN2
                  IF(LEN2.LT.0.0D0) LEN=-LEN1
               ELSE
!       RAD NEG
!     THEN THE INTERSECTION TO USE IS THE POSITIVE INTERSECTION
                  IF(LEN1.GT.0.0D0) LEN=-LEN2
                  IF(LEN2.GT.0.0D0) LEN=-LEN1
               END IF
            END IF
         END IF
!       NEGATIVE SIGN SINCE LEN1 AND LEN2 MEASURES DIRECTED
!       DISTANCE FROM IMAGE TO SPHERE INTERSECTION AND
!       LEN IS DIRECTED FROM SPHERE INTERSECTION TO IMAGE

         OCOR=-LEN
         GO TO 900
!     EXPAUT NOT FALSE
      END IF
      IF(EXPAUT) THEN
!       THE REFERENCE SPHERE IS CENTERED WHERE THE REAL CHIEF
!       RAY CROSSES THE FINAL SURFACE.
!       THE RADIUS IS EQUAL
!       TO THE DISTANCE FROM POINT TO WHERE THE CHIEF RAY CROSSES THE REAL
!     EXIT PUPIL
!       THIS IS JUST AS IN CODE-V AND IS THE DEFAULT WHEN THE PROGRAM
!     BEGINS
!
!       COORDINATES OF THE REAL CHIEF RAY AT THE IMAGE PLANE ARE:
!       THIS IS THE REFERENCE SPHERE CENTER LOCATION.
         XREFI=REFRY(1,NEWIMG)
         YREFI=REFRY(2,NEWIMG)
         ZREFI=REFRY(3,NEWIMG)
!
!       DO A REAL RAY INTERNAL EXIT PUPIL ADJUSTMENT
!
         XO=REFRY(1,NEWIMG)
         YO=REFRY(2,NEWIMG)
         ZO=REFRY(3,NEWIMG)
         LO=REFRY(4,NEWIMG)
         MO=REFRY(5,NEWIMG)
         NO=REFRY(6,NEWIMG)
         XOOX=RFDIFF(1,NEWIMG)
         YOOX=RFDIFF(2,NEWIMG)
         ZOOX=RFDIFF(3,NEWIMG)
         LOOX=RFDIFF(4,NEWIMG)
         MOOX=RFDIFF(5,NEWIMG)
         NOOX=RFDIFF(6,NEWIMG)
         XOOY=RFDIFF(7,NEWIMG)
         YOOY=RFDIFF(8,NEWIMG)
         ZOOY=RFDIFF(9,NEWIMG)
         LOOY=RFDIFF(10,NEWIMG)
         MOOY=RFDIFF(11,NEWIMG)
         NOOY=RFDIFF(12,NEWIMG)
         THXNUM=((XO-XOOX)*(LO-LOOX))+((YO-YOOX)*(MO-MOOX))&
         &+((ZO-ZOOX)*(NO-NOOX))
         THYNUM=((XO-XOOY)*(LO-LOOY))+((YO-YOOY)*(MO-MOOY))&
         &+((ZO-ZOOY)*(NO-NOOY))
         THXDEN=((LO-LOOX)**2)+((MO-MOOX)**2)&
         &+((NO-NOOX)**2)
         THYDEN=((LO-LOOY)**2)+((MO-MOOY)**2)&
         &+((NO-NOOY)**2)
         IF(DABS(THXNUM*1.0D-15).LT.DABS(THXDEN).AND.&
         &DABS(THYNUM*1.0D-15).LT.&
         &DABS(THYDEN)) THEN
            RAD=-((-THXNUM/THXDEN)+(-THYNUM/THYDEN))/2.0D0
!     THE EXIT PUPIL IS LOCATED AT:
            XA=XO+(-RAD*LO)
            YA=YO+(-RAD*MO)
            ZA=ZO+(-RAD*NO)
            RAD=DSQRT(&
            &((XA-XREFI)**2)+((YA-YREFI)**2)+((ZA-ZREFI)**2)&
            &)
            IF(ZA.LE.ZO) THEN
!     PUPIL LIES ON THE NEGATIVE SIDE OF NEWIMG SO RAD IS POS
               RAD=RAD
            ELSE
               RAD=-RAD
            END IF
         END IF
         IF(DABS(THXNUM*1.0D-15).GE.DABS(THXDEN).OR.&
         &DABS(THYNUM*1.0D-15).GE.&
         &DABS(THYDEN)) THEN
!       REF RAY IS TELECENTRIC, SET RAD =1.0D20
            RAD=1.0D20
         END IF
!
!       NOW WE HAVE LOCATION OF REFERENCE SPHERE CENTER
!       AND ITS RADIUS MAGNITUDE
!
!       THE CHIEF RAY INTERSECTS THE REFERENCE SPHERE
!       THE LENGTH FROM THIS INTERSECTION TO THE INTERSECTION
!       OF THE REFERENCE RAY WITH THE FINAL SURFACE IS RCOR=RAD
!       REFERENCE RAY INTERSECTION WITH THE TANGENT PLANE IS:
!
         RCOR=RAD
!
!       THE LENGTH FROM THE REFERENCE SPHERE
!       TO THE FINAL SURFACE ALONG THE "OTHER" RAY IS:
!
         LLL=RAYRAY(19,NEWIMG)
         MMM=RAYRAY(20,NEWIMG)
         NNN=RAYRAY(21,NEWIMG)
         AL=RAYRAY(1,NEWIMG)-XREFI
         BE=RAYRAY(2,NEWIMG)-YREFI
         GA=RAYRAY(3,NEWIMG)-ZREFI
         C=(AL**2)+(BE**2)+(GA**2)-(RAD**2)
         B=2.0D0*((LLL*AL)+&
         &(MMM*BE)+&
         &(NNN*GA))
         A=1.0D0
!       SOLVE FOR LEN
         IF(B.NE.0.0D0) SIGNB=((DABS(B))/(B))
         IF(B.EQ.0.0D0) SIGNB=1.0D0
         IF(A.EQ.0.0D0) THEN
            LEN=-(C/B)
         ELSE
            ARG=((B**2)-(4.0D0*A*C))
            IF(ARG.LT.0.0D0) THEN
               OUTLYNE='RAY(S) COULD NOT INTERSECT REFERENCE SPHERE'
               CALL SHOWIT(1)
               OUTLYNE=&
               &'THE CURRENT SYSTEM MAY HAVE EXCESSIVE ABERRATIONS'
               CALL SHOWIT(1)
               OUTLYNE=&
               &'OPD VALUES MAY BE SUSPECT'
               CALL SHOWIT(1)
               OCOR=0.0D0
               RCOR=0.0D0
               RETURN
!       REFERENCE SPHERE INTERSECTED
            END IF
            Q=(-0.5D0*(B+(SIGNB*(DSQRT((B**2)-(4.0D0*A*C))))))
            LEN1=C/Q
            LEN2=Q/A
            IF(REFRY(6,NEWIMG).GT.0.0D0) THEN
               IF(RAD.GT.0.0D0) THEN
!     THEN THE INTERSECTION TO USE IS THE NEGATIVE INTERSECTION
                  IF(LEN1.LT.0.0D0) LEN=LEN1
                  IF(LEN2.LT.0.0D0) LEN=LEN2
               ELSE
!       RAD NEG
!     THEN THE INTERSECTION TO USE IS THE POSITIVE INTERSECTION
                  IF(LEN1.GT.0.0D0) LEN=LEN1
                  IF(LEN2.GT.0.0D0) LEN=LEN2
               END IF
            END IF
            IF(REFRY(6,NEWIMG).LT.0.0D0) THEN
               IF(RAD.GT.0.0D0) THEN
!     THEN THE INTERSECTION TO USE IS THE NEGATIVE INTERSECTION
                  IF(LEN1.LT.0.0D0) LEN=-LEN2
                  IF(LEN2.LT.0.0D0) LEN=-LEN1
               ELSE
!       RAD NEG
!     THEN THE INTERSECTION TO USE IS THE POSITIVE INTERSECTION
                  IF(LEN1.GT.0.0D0) LEN=-LEN2
                  IF(LEN2.GT.0.0D0) LEN=-LEN1
               END IF
            END IF
         END IF
!       NEGATIVE SIGN SINCE LEN1 AND LEN2 MEASURES DIRECTED
!       DISTANCE FROM IMAGE TO SPHERE INTERSECTION AND
!       LEN IS DIRECTED FROM SPHERE INTERSECTION TO IMAGE
         OCOR=-LEN
         GO TO 900
!     EXPAUT NOT TRUE
      END IF
      GO TO 900
!     NOT FOCAL
   END IF
900 CONTINUE
   IF(DABS(RCOR).GT.1.0D10.OR.DABS(OCOR).GT.1.0D10) THEN
!     INFINITE REFERENCE SPHERE
      RCOR=0.0D0
!     OCOR IS THE DISTANCE ALONG THE RAY BETWEEN AN INTERSECTION
!     WITH A PLANE PERPENDICULAR TO A PARALLEL RAY WHICH PASSES
!     THROUGH A POINT ON THE IMAGE SURFACE WHERE THE CHIEF RAY
!     HITS
      RCOR=0.0D0
      RX0=REFRY(1,NEWIMG-1)
      RY0=REFRY(2,NEWIMG-1)
      RZ0=REFRY(3,NEWIMG-1)
      RL0=RAYRAY(19,NEWIMG-1)
      RM0=RAYRAY(20,NEWIMG-1)
      RN0=RAYRAY(21,NEWIMG-1)
!       NOW THE OTHER RAY:
      RRX0=RAYRAY(1,NEWIMG-1)
      RRY0=RAYRAY(2,NEWIMG-1)
      RRZ0=RAYRAY(3,NEWIMG-1)
      L0=RAYRAY(19,NEWIMG-1)
      M0=RAYRAY(20,NEWIMG-1)
      N0=RAYRAY(21,NEWIMG-1)
!       THE LINE DIRECTION NUMBERS ARE:
!
!       THE PLANE WHICH HAS ITS ORIGIN WHERE THE
!       REFERENCE RAY INTERSECTS THE IMAGE PLANE
!       AND IS PERPENDICULAR TO THE REGULAR RAY HAS THE FORM:
!
!       (RL0*(X-RX0))+(RM0*(Y-RY0))+(RN0*(Z-RZ0))=0
!       X,Y AND Z ARE ANY POINTS ON THE PLANE.
!
!       NOW DETERMINE THE INTERSECTION OF AN "OTHER" RAY
!       WITH THIS REFERENCE PLANE.
!
!       THE EQUATION OF THE OTHER RAY IS
!               XA=RRX0+(T*L0)
!               YA=RRY0+(T*M0)
!               ZA=RRZ0+(T*N0)
! THE PARAMETER T IS DETERMINED BY SUBSTITUTING THIS LINE
!       EQUATION INTO THE REFERENCE SURAFCE EQUATION
!       AND SOLVING FOR T.
!
      T=((RL0*(RX0-RRX0))+(RM0*(RY0-RRY0))+(RN0*(RZ0-RRZ0)))/&
      &((RL0*L0)+(RM0*M0)+(RN0*N0))
!
!       NOW X,Y AND Z ARE:
      XA=RRX0+(T*L0)
      YA=RRY0+(T*M0)
      ZA=RRZ0+(T*N0)
      OCOR=DSQRT(&
      &((RAYRAY(1,NEWIMG-1)-XA)**2)+&
      &((RAYRAY(2,NEWIMG-1)-YA)**2)+&
      &((RAYRAY(3,NEWIMG-1)-ZA)**2))
!     IF T IS LESS THAN ZERO, THE RAY INTERSECTION WITH THE
!     REFERENCE PLANE LIES ON THE NEGATIVE SIDE OF THE IMAGE SURFACE
!     AND ZA LT RAYRAY(3,NEWIMG-1) AND OCOR MUST BE POSITIVE AND VICE VERSA.
!       THE CORRECT SIGN IS:
      IF(ZA.GT.RAYRAY(3,NEWIMG-1)) OCOR=-OCOR
      IF(ZA.LE.RAYRAY(3,NEWIMG-1)) OCOR=OCOR
   ELSE
   END IF
   RETURN
END
! SUB GPXT.FOR
SUBROUTINE GPXT
!
   use DATLEN
   use DATMAI
   use command_utils, only: is_command_query
   use mod_system, only: sys_wl_ref, sys_last_surf
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE GPXT. THIS SUBROUTINE IMPLEMENTS
!       THE GENERALIZED PARAXIAL RAY TRACE PRINTOUT COMMANDS
!       "GPXTX" AND "GPXTY"
!
   INTEGER SF,I,ERROR
!
   REAL*8 PX,PY,PCX,PCY,PUX,PUY,PUCX,PUCY,DWORD2,DWORD3 &
   &,DWORD4,DWORD5
!
!
   GPRAYEXT=.FALSE.
   IF(DF2.EQ.1) W2=0.0D0
   IF(DF3.EQ.1) W3=0.0D0
   IF(DF4.EQ.1) W4=0.0D0
   IF(DF5.EQ.1) W5=sys_wl_ref()
   DWORD2=W2
   DWORD3=W3
   DWORD4=W4
   DWORD5=W5
!
   IF(is_command_query()) THEN
      WRITE(OUTLYNE,*)&
      &'"GPXT(XorY)" OUTPUT GENERALIZED PARAXIAL DATA'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1) THEN
      WRITE(OUTLYNE,*)&
      &'GENERALIZED PARAXIAL RAYTRACE OUTPUT COMMANDS TAKE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)&
      &'NO STRING INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.1.AND.S1.EQ.1) THEN
      WRITE(OUTLYNE,*)&
      &'GENERALIZED PARAXIAL RAYTRACE OUTPUT COMMANDS TAKE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)&
      &'QUALIFIER OR NUMERIC WORD #1 INPUT BUT NOT BOTH'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(DWORD5.LT.1.0D0.OR.DWORD5.GT.10.0D0) THEN
      WRITE(OUTLYNE,*)'INVALID WAVELENGTH NUMBER ISSUED'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO GENERALIZED PARAXIAL DATA EXISTS'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(sys_last_surf().EQ.0.0) THEN
      WRITE(OUTLYNE,*)'LENS SYSTEM HAS NO SURFACES'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'NO GENERALIZED PARAXIAL DATA EXISTS'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.1.AND.WQ.EQ.'ALL') THEN
      CALL GNPRTGEN(0,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
      &,DWORD2,DWORD3,DWORD4,DWORD5,0)
      IF(ERROR.EQ.1) THEN
         WRITE(OUTLYNE,*)'RAY COULD NOT BE TRACED'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'DIFFERENTIAL RAY VALUES NOT CALCULABLE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'NO ACTION TAKEN'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      ELSE
         GPRAYEXT=.TRUE.
      END IF
      SF=INT(sys_last_surf())
      IF(WC.EQ.'GPXTX') WRITE(OUTLYNE,6001) INT(F12)
      IF(WC.EQ.'GPXTY') WRITE(OUTLYNE,6004) INT(F12)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6006) INT(DWORD5)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6007) DWORD2
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6008) DWORD3
      CALL SHOWIT(0)
      WRITE(OUTLYNE,6009) DWORD4
      CALL SHOWIT(0)
      IF(WC.EQ.'GPXTX') WRITE(OUTLYNE,6002)
      IF(WC.EQ.'GPXTY') WRITE(OUTLYNE,6005)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,2501)
      CALL SHOWIT(0)
      IF(WC.EQ.'GPXTX') WRITE(OUTLYNE,6000)
      IF(WC.EQ.'GPXTY') WRITE(OUTLYNE,6003)
      CALL SHOWIT(0)
      DO 10 I=0,SF
         CALL GNPRTGEN(I,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
         &,DWORD2,DWORD3,DWORD4,DWORD5,0)
         IF(ERROR.EQ.1) THEN
            WRITE(OUTLYNE,*)'RAY COULD NOT BE TRACED'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'DIFFERENTIAL RAY VALUES NOT CALCULABLE'
            CALL SHOWIT(1)
            WRITE(OUTLYNE,*)'NO ACTION TAKEN'
            CALL SHOWIT(1)
            CALL MACFAL
            RETURN
         ELSE
            GPRAYEXT=.TRUE.
         END IF
         GPXY(1,I)=PX
         GPXY(2,I)=PY
         GPXY(3,I)=PCX
         GPXY(4,I)=PCY
         IF(WC.EQ.'GPXTX') WRITE(OUTLYNE,1500)I,PX,PUX,PCX,PUCX
         IF(WC.EQ.'GPXTY') WRITE(OUTLYNE,1500)I,PY,PUY,PCY,PUCY
         CALL SHOWIT(0)
10    CONTINUE
      RETURN
   END IF
   IF(SQ.EQ.1.AND.WQ.EQ.'OBJ'.OR.SQ.EQ.1.AND.WQ.EQ.'OB') THEN
      SF=0
      CALL GNPRTGEN(SF,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
      &,DWORD2,DWORD3,DWORD4,DWORD5,0)
      IF(ERROR.EQ.1) THEN
         WRITE(OUTLYNE,*)'RAY COULD NOT BE TRACED'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'DIFFERENTIAL RAY VALUES NOT CALCULABLE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'NO ACTION TAKEN'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      ELSE
         GPRAYEXT=.TRUE.
      END IF
      IF(WC.EQ.'GPXTX')THEN
         IF(HEADIN) WRITE(OUTLYNE,6000)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500) SF,PX,PUX,PCX,PUCX
         CALL SHOWIT(0)
      END IF
      IF(WC.EQ.'GPXTY')THEN
         IF(HEADIN) WRITE(OUTLYNE,6003)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500) SF,PY,PUY,PCY,PUCY
         CALL SHOWIT(0)
      END IF
      RETURN
   END IF
   IF(SQ.EQ.1.AND.WQ.NE.'OBJ'.OR.SQ.EQ.1.AND.&
   &WQ.NE.'ALL'.OR.SQ.EQ.1.AND.WQ.NE.'OB') THEN
      WRITE(OUTLYNE,*)'INVALID QUALIFIER WORD'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.0.AND.DF1.EQ.1) THEN
!       OUTPUT IMAGE SURFACE
      SF=INT(sys_last_surf())
      CALL GNPRTGEN(SF,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
      &,DWORD2,DWORD3,DWORD4,DWORD5,0)
      IF(ERROR.EQ.1) THEN
         WRITE(OUTLYNE,*)'RAY COULD NOT BE TRACED'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'DIFFERENTIAL RAY VALUES NOT CALCULABLE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'NO ACTION TAKEN'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      ELSE
         GPRAYEXT=.TRUE.
      END IF
      IF(WC.EQ.'GPXTX')THEN
         IF(HEADIN) WRITE(OUTLYNE,6000)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500) SF,PX,PUX,PCX,PUCX
         CALL SHOWIT(0)
      END IF
      IF(WC.EQ.'GPXTY')THEN
         IF(HEADIN) WRITE(OUTLYNE,6003)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500) SF,PY,PUY,PCY,PUCY
         CALL SHOWIT(0)
      END IF
      RETURN
   END IF
   IF(SQ.EQ.0.AND.DF1.NE.1) THEN
      I=INT(W1)
      SF=INT(sys_last_surf())
      IF(I.GT.SF.OR.I.LT.0) THEN
         WRITE(OUTLYNE,*)'SURFACE NUMBER BEYOND LEGAL RANGE'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      CALL GNPRTGEN(I,PY,PX,PUY,PUX,PCY,PCX,PUCY,PUCX,ERROR &
      &,DWORD2,DWORD3,DWORD4,DWORD5,0)
      IF(ERROR.EQ.1) THEN
         WRITE(OUTLYNE,*)'RAY COULD NOT BE TRACED'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'DIFFERENTIAL RAY VALUES NOT CALCULABLE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'NO ACTION TAKEN'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      ELSE
         GPRAYEXT=.TRUE.
      END IF
      IF(WC.EQ.'GPXTX') THEN
         IF(HEADIN) WRITE(OUTLYNE,6000)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)I,PX,PUX,PCX,PUCX
         CALL SHOWIT(0)
      END IF
      IF(WC.EQ.'GPXTY') THEN
         IF(HEADIN) WRITE(OUTLYNE,6003)
         IF(HEADIN) CALL SHOWIT(0)
         WRITE(OUTLYNE,1500)I,PY,PUY,PCY,PUCY
         CALL SHOWIT(0)
      END IF
   END IF
1500 FORMAT(I3,2X,G13.6,2X,G13.6,2X,G13.6,2X,G13.6)
!
!       GPXTX
!
6000 FORMAT('SURF',6X,'PX',12X,'PUX',13X,'PCX',11X,'PUCX')
6001 FORMAT('GENERALIZED PARAXIAL RAYTRACE DATA (XZ-PLANE)',&
   &' - (CFG #',I2,')')
6002 FORMAT(&
   &'(PUX AND PUCX) MEASURED WITH RESPECT TO THE Z-AXIS')
!
!       GPXTY
!
6003 FORMAT('SURF',6X,'PY',12X,'PUY',13X,'PCY',11X,'PUCY')
6004 FORMAT('GENERALIZED PARAXIAL RAYTRACE DATA (YZ-PLANE)',&
   &' - (CFG #',I2,')')
6005 FORMAT(&
   &'(PUY AND PUCY) MEASURED WITH RESPECT TO THE Z-AXIS')
2501 FORMAT(1X)
6006 FORMAT('TRACED AT WAVELENGTH NUMBER = ',I2)
6007 FORMAT('TRACED FROM Y-FOB =  ',G13.6)
6008 FORMAT('TRACED FROM X-FOB =  ',G13.6)
6009 FORMAT('WITH OBJ. Z-SHIFT =  ',G13.6,' LENS UNITS')
!
END
! SUB PGLPRY.FOR
SUBROUTINE PGLPRY
!
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_thickness
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE GLPRAY.FOR. THIS SUBROUTINE IMPLEMENTS
!       CREATION OF GLOBAL RAY DATA FOR THE LAST RAY TRACED.
!       FOR RAY PLOTTING IT IS CALLED BY RAYTRA.FOR
!
   INTEGER JK,I
!
   REAL*8 X,Y,Z,&
   &X1,Y1,Z1,L1,M1,N1,X00,Y00,Z0,LX0,LY0,LZ0,&
   &MX0,MY0,MZ0,NX0,NY0,NZ0,LO1,MO1,NO1
!
!
   IF(DABS(surf_thickness(NEWOBJ)).LE.1.0D10) THEN
!       FINITE OBJECT THICKNESS
      JK=NEWOBJ
   ELSE
!       INFINITE OBJECT THICKNESS
      JK=NEWOBJ+1
   END IF
!
   DO 10 I=JK,NEWIMG
!
!       NOW TRANSFORM TO THE GLOBAL COORDINATE SYSTEM.
!       THE GLOBAL COORDINATES OF EACH LOCAL COORDINATE
!       SYSTEM ARE:
!
      X00=VERTEX(1,I)
      Y00=VERTEX(2,I)
      Z0=VERTEX(3,I)
      LX0=VERTEX(4,I)
      MX0=VERTEX(5,I)
      NX0=VERTEX(6,I)
      LY0=VERTEX(7,I)
      MY0=VERTEX(8,I)
      NY0=VERTEX(9,I)
      LZ0=VERTEX(10,I)
      MZ0=VERTEX(11,I)
      NZ0=VERTEX(12,I)
!
      X=GPXY(1,I)
      Y=0.0D0
      Z=0.0D0
      X1=X00+((LX0*(X))+(LY0*(Y))&
      &+(LZ0*(X)))
      Y1=Y00+((MX0*(X))+(MY0*(Y))&
      &+(MZ0*(Z)))
      Z1=Z0+((NX0*(X))+(NY0*(Y))&
      &+(NZ0*(Z)))
      PGLPRAY(1,I)=X1
      PGLPRAY(2,I)=Y1
      PGLPRAY(3,I)=Z1
      X=0.0D0
      Y=GPXY(2,I)
      Z=0.0D0
      X1=X00+((LX0*(X))+(LY0*(Y))&
      &+(LZ0*(X)))
      Y1=Y00+((MX0*(X))+(MY0*(Y))&
      &+(MZ0*(Z)))
      Z1=Z0+((NX0*(X))+(NY0*(Y))&
      &+(NZ0*(Z)))
      PGLPRAY(4,I)=X1
      PGLPRAY(5,I)=Y1
      PGLPRAY(6,I)=Z1
      X=GPXY(3,I)
      Y=0.0D0
      Z=0.0D0
      X1=X00+((LX0*(X))+(LY0*(Y))&
      &+(LZ0*(X)))
      Y1=Y00+((MX0*(X))+(MY0*(Y))&
      &+(MZ0*(Z)))
      Z1=Z0+((NX0*(X))+(NY0*(Y))&
      &+(NZ0*(Z)))
      PGLPRAY(7,I)=X1
      PGLPRAY(8,I)=Y1
      PGLPRAY(9,I)=Z1
      X=0.0D0
      Y=GPXY(4,I)
      Z=0.0D0
      X1=X00+((LX0*(X))+(LY0*(Y))&
      &+(LZ0*(X)))
      Y1=Y00+((MX0*(X))+(MY0*(Y))&
      &+(MZ0*(Z)))
      Z1=Z0+((NX0*(X))+(NY0*(Y))&
      &+(NZ0*(Z)))
      PGLPRAY(10,I)=X1
      PGLPRAY(11,I)=Y1
      PGLPRAY(12,I)=Z1
10 CONTINUE
!       ALL GLOBAL TRANSFORMATIONS ARE COMPLETE
   RETURN
END
