FUNCTION SAVEINPT(I)
!
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!     THIS ROUTINE SAVES THE EXISTING INPUT LINE
!     SO THAT A NEW LINE MAY BE CREATED AND SENT DIRECTLY TO THE
!     PROGRAM COMMAND PROCESSOR IN PROCES.FOR
!
!
!     THE ROUTINE RESTIO.FOR IS THE INVERSE OF THIS ROUTINE
!     USED TO RESTORE ALL AS IT WAS BEFORE ENTERING THE TWILIGHT ZONE
!
   LOGICAL SAVEINPT
   LOGICAL SAVE_KDP(1:200)
   COMMON/KDPSAVE/SAVE_KDP
   INTEGER KDPN,I
   PARAMETER (KDPN=200)
!
   CHARACTER WC*8,WQ*8,WS*80
!
   COMMON/CNTLCH/WC,WQ,WS
!
   INTEGER SB1,SB2,SC1,SC2,SQ,SST,S1,S2,S3,S4,S5,&
   &DF1,DF2,DF3,DF4,DF5,SN,STI
!
   real(real64) W1,W2,W3,W4,W5
!
   COMMON/CNTLNM/W1,W2,W3,W4,W5,SB1,SB2,SC1,SC2,SQ,SST,&
   &S1,S2,S3,S4,S5,DF1,DF2,DF3,DF4,DF5,SN
!
   COMMON/KUERRY/STI
!     PREVIOUS STUFF(USED TO REMEMBER PREVIOUS VALUES IN SPECIAL CASES)
!
   CHARACTER KDP_WC(0:KDPN)*8,KDP_WQ(0:KDPN)*8,KDP_WS(0:KDPN)*80
!
   COMMON/KDP_CNTLCH/KDP_WC,KDP_WQ,KDP_WS
!
   INTEGER KDP_SB1(0:KDPN),KDP_SB2(0:KDPN),KDP_SC1(0:KDPN)&
   &,KDP_SC2(0:KDPN),KDP_SQ(0:KDPN),KDP_SST(KDPN),KDP_S1(0:KDPN),&
   &KDP_S2(0:KDPN),&
   &KDP_S3(0:KDPN),KDP_S4(0:KDPN),KDP_S5(KDPN),&
   &KDP_DF1(0:KDPN),KDP_DF2(0:KDPN),KDP_DF3(0:KDPN),KDP_DF4(0:KDPN),&
   &KDP_DF5(0:KDPN),KDP_SN(0:KDPN),KDP_STI(0:KDPN)
!
   real(real64) KDP_W1(0:KDPN),KDP_W2(0:KDPN),KDP_W3(0:KDPN),&
   &KDP_W4(0:KDPN),KDP_W5(0:KDPN)
!
   COMMON/KDP_CNTLNM/KDP_W1,KDP_W2,KDP_W3,KDP_W4,KDP_W5,KDP_SB1 &
   &,KDP_SB2,KDP_SC1,&
   &KDP_SC2,KDP_SQ,KDP_SST,&
   &KDP_S1,KDP_S2,KDP_S3,KDP_S4,KDP_S5,KDP_DF1,KDP_DF2,KDP_DF3,&
   &KDP_DF4,KDP_DF5,KDP_SN
!
   COMMON/KDP_QUERRY/KDP_STI
!
   KDP_WC(I)=WC
   KDP_WQ(I)=WQ
   KDP_WS(I)=WS
   KDP_SB1(I)=SB1
   KDP_SB2(I)=SB2
   KDP_SC1(I)=SC1
   KDP_SC2(I)=SC2
   KDP_SQ(I)=SQ
   KDP_SST(I)=SST
   KDP_S1(I)=S1
   KDP_S2(I)=S2
   KDP_S3(I)=S3
   KDP_S4(I)=S4
   KDP_S5(I)=S5
   KDP_SN(I)=SN
   KDP_DF1(I)=DF1
   KDP_DF2(I)=DF2
   KDP_DF3(I)=DF3
   KDP_DF4(I)=DF4
   KDP_DF5(I)=DF5
   KDP_W1(I)=W1
   KDP_W2(I)=W2
   KDP_W3(I)=W3
   KDP_W4(I)=W4
   KDP_W5(I)=W5
   KDP_STI(I)=STI
   SAVEINPT=.TRUE.
   RETURN
END
FUNCTION RESTINPT(I)
!
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!     THIS ROUTINE RESTORES THE EXISTING INPUT LINE
!     SO THAT A NEW LINE MAY BE CREATED AND SENT DIRECTLY TO THE
!     PROGRAM COMMAND PROCESSOR IN PROCES.FOR
!
!
!     THE ROUTINE RESTIO.FOR IS THE INVERSE OF THIS ROUTINE
!     USED TO RESTORE ALL AS IT WAS BEFORE ENTERING THE TWILIGHT ZONE
!
   LOGICAL RESTINPT
   INTEGER KDPN,I
   PARAMETER (KDPN=200)
   LOGICAL REST_KDP(1:200)
   COMMON/KDPREST/REST_KDP
!
   CHARACTER WC*8,WQ*8,WS*80
!
   COMMON/CNTLCH/WC,WQ,WS
!
   INTEGER SB1,SB2,SC1,SC2,SQ,SST,S1,S2,S3,S4,S5,&
   &DF1,DF2,DF3,DF4,DF5,SN,STI
!
   real(real64) W1,W2,W3,W4,W5
!
   COMMON/CNTLNM/W1,W2,W3,W4,W5,SB1,SB2,SC1,SC2,SQ,SST,&
   &S1,S2,S3,S4,S5,DF1,DF2,DF3,DF4,DF5,SN
!
   COMMON/KUERRY/STI
!     PREVIOUS STUFF(USED TO REMEMBER PREVIOUS VALUES IN SPECIAL CASES)
!
   CHARACTER KDP_WC(0:KDPN)*8,KDP_WQ(0:KDPN)*8,KDP_WS(0:KDPN)*80
!
   COMMON/KDP_CNTLCH/KDP_WC,KDP_WQ,KDP_WS
!
   INTEGER KDP_SB1(0:KDPN),KDP_SB2(0:KDPN),KDP_SC1(0:KDPN)&
   &,KDP_SC2(0:KDPN),KDP_SQ(0:KDPN),KDP_SST(KDPN),KDP_S1(0:KDPN),&
   &KDP_S2(0:KDPN),&
   &KDP_S3(0:KDPN),KDP_S4(0:KDPN),KDP_S5(KDPN),&
   &KDP_DF1(0:KDPN),KDP_DF2(0:KDPN),KDP_DF3(0:KDPN),KDP_DF4(0:KDPN),&
   &KDP_DF5(0:KDPN),KDP_SN(0:KDPN),KDP_STI(0:KDPN)
!
   real(real64) KDP_W1(0:KDPN),KDP_W2(0:KDPN),KDP_W3(0:KDPN),&
   &KDP_W4(0:KDPN),KDP_W5(0:KDPN)
!
   COMMON/KDP_CNTLNM/KDP_W1,KDP_W2,KDP_W3,KDP_W4,KDP_W5,KDP_SB1 &
   &,KDP_SB2,KDP_SC1,&
   &KDP_SC2,KDP_SQ,KDP_SST,&
   &KDP_S1,KDP_S2,KDP_S3,KDP_S4,KDP_S5,KDP_DF1,KDP_DF2,KDP_DF3,&
   &KDP_DF4,KDP_DF5,KDP_SN
!
   COMMON/KDP_QUERRY/KDP_STI
!
   WC=KDP_WC(I)
   WQ=KDP_WQ(I)
   WS=KDP_WS(I)
   SB1=KDP_SB1(I)
   SB2=KDP_SB2(I)
   SC1=KDP_SC1(I)
   SC2=KDP_SC2(I)
   SQ=KDP_SQ(I)
   SST=KDP_SST(I)
   S1=KDP_S1(I)
   S2=KDP_S2(I)
   S3=KDP_S3(I)
   S4=KDP_S4(I)
   S5=KDP_S5(I)
   SN=KDP_SN(I)
   DF1=KDP_DF1(I)
   DF2=KDP_DF2(I)
   DF3=KDP_DF3(I)
   DF4=KDP_DF4(I)
   DF5=KDP_DF5(I)
   W1=KDP_W1(I)
   W2=KDP_W2(I)
   W3=KDP_W3(I)
   W4=KDP_W4(I)
   W5=KDP_W5(I)
   STI=KDP_STI(I)
   RESTINPT=.TRUE.
   RETURN
END
