!       FIRST SET OF SPECT ROUTINES

! SUB PFILE.FOR
SUBROUTINE PFILE
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE HANDELS FILING THE CONTENTS OF THE
!       CUMULATIVE MEMORY AREA TO A SPECT DISK FILE
!
!                       DEFINE VARIABLES
!
   CHARACTER NM*8,FN*10,DDATE*10,&
   &TTIME*8,TTTIM*8,DDDAT*10
!
   COMMON/STRNGR/DDDAT,TTTIM,NM,FN
!
   INTEGER POINTS,OCC,NTOTAL,NF,I,J,II
!
   real(real64) &
   &DATA1,DATA2,LAMB1,LAMB2
!
   real(real64) CUMULT(1:1001,1:3)
!
   LOGICAL EXISJK
!
   COMMON/CUM/CUMULT
!
   COMMON/WAVEL/LAMB1,LAMB2,NTOTAL
!
!
!       INITIALIZE II TO ZERO
   II=0
!
!       TABLE DATA IN BINARY FORMAT. TRA.DAT IS UNIT 35
!
!       DATA STORED IN TRA.DAT IS:
!               FILE NAME (WQ) CHARACTER *8
!               DATA1 STARTING WAVELENGTH (DOUBLE PRES.)
!               DATA2 ENDIG WAVLENGTH (DOUBLE PRES.)
!               POINTS - NUMBER OF DATA POINTS (INTEGER)
!               OCC- OCCUPANCY FLAG, 0=EMPTY, 1- FULL (INTEGER)
!               DDATE- CALENDER DATE FILE WAS STORED
!               TTIME-TIME FILED
!       WE MUST SEARCH FOR A FILE TO OVERWRITE
!       ***************************************************************
   EXISJK=.FALSE.
   INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
   IF(.NOT.EXISJK) THEN
      WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       ***************************************************************
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
   &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
   DO 9 I=1,200
      READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
      DDDAT=DDATE
      TTTIM=TTIME
      IF(NM.EQ.WQ) THEN
!       FOUND THE EARLIER VERSION OF THE TABLE FILE NAMED "WQ"
!       OVERWRITE IT.
         II=I
         GO TO 11
      END IF
!
9  CONTINUE
!
!       NO OVERWRITE TO DO, FIND A BLANK SPOT TO FILE IN
!
   DO 10 I=1,200
      READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
      DDDAT=DDATE
      TTTIM=TTIME
      IF(OCC.EQ.0) THEN
!       FOUND AN EMPTY SLOT
         II=I
         GO TO 11
      END IF
!
!       CHECK IF NM=WQ
!
10 CONTINUE
!       IF YOU GOT HERE, LIBRARY WAS FULL
   WRITE(OUTLYNE,*)&
   &'SPECT DISK FILE WAS FULL, CUMULATIVE DATA NOT FILED'
   CALL SHOWIT(1)
   WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
   CALL SHOWIT(1)
   CALL MACFAL
   RETURN
11 CONTINUE
!       PROCEED WITH STORAGE
!       FILE THE DIRECTORY DATA IN TRA.DAT
   DATA1=LAMB1
   DATA2=LAMB2
   POINTS=NTOTAL
   OCC=1
   CALL MYDATE(DDATE)
   CALL MYTIME(TTIME)
   DDDAT=DDATE
   TTTIM=TTIME
   WRITE(UNIT=35,REC=II) WQ,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
   CALL CLOSE_FILE(35,1)
   NF=II
   CALL TRAFIL(NF,FN)
!
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
   &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
   CALL CLOSE_FILE(35,0)
!       OPEN AND WRITE TO FILE
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
   &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
!
!       NOW OUTPUT TABLE DATA TO TRAXXX.DAT
!
   DO 210 J=1,NTOTAL
      WRITE(UNIT=35,REC=J) CUMULT(J,1),&
      &CUMULT(J,2),CUMULT(J,3)
210 CONTINUE
!
   CALL CLOSE_FILE(35,1)
   WRITE(OUTLYNE,*)&
   &'CUMULATIVE DATA STORED IN SPECT DISK FILE NO. ',II
   CALL SHOWIT(1)
   WRITE(OUTLYNE,*)'AS FILE ( ',WQ,' )'
   CALL SHOWIT(1)
   RETURN
!
END
! SUB TRFLEX.FOR
SUBROUTINE TRFLEX
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE ERASES ALL EXISTING TRANSMISSION FILES
!       TRAXXX.FOR
!
   LOGICAL LXIST
!
   INTEGER NF
!
   CHARACTER FN*10
!
!
   DO NF=1,999
      CALL TRAFIL(NF,FN)
      LXIST=.FALSE.
      INQUIRE(FILE=LIBTRA//FN,EXIST=LXIST)
      IF(LXIST) THEN
         OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
         &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
         CALL CLOSE_FILE(35,1)
      ELSE
!       CONTINUE SEARCH
      END IF
   END DO
   RETURN
END
! SUB TRAFIL.FOR
SUBROUTINE TRAFIL(N,FN)
!
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE IS USED TO DETERMIN THE CORRECT FILE
!       NAME GIVEN A FILE NUMBER( FOR TRANSMISSION FILES USED
!       IN SPECT)
!
   INTEGER N
!
   CHARACTER FN*10,AN*3
!
   CALL CCOONN(N,AN)
!
   IF(N.GT.0.AND.N.LE.9) FN='TRA00'//AN(3:3)//'.DAT'
   IF(N.GT.9.AND.N.LE.99) FN='TRA0'//AN(2:3)//'.DAT'
   IF(N.GT.99.AND.N.LE.999) FN='TRA'//AN(1:3)//'.DAT'
   RETURN
END
! SUB CCOONN.FOR
SUBROUTINE CCOONN(N,AN)
!
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE USES WRITE AND READS TO AN INTERNAL
!       FILE TO CONVERT INTEGER NUMERIC WORDS
!       TO CHARACTER VARIABLES
!
   INTEGER N
!
   CHARACTER B*20,AN*3

   WRITE(B,100) N
   READ(B,200) AN
100 FORMAT(I3)
200 FORMAT(A3)
   RETURN
END
! SUB TFILE.FOR
SUBROUTINE TFILE(TNAME)
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE HANDELS FILING TABLE DATA TO DISK
!
!                       DEFINE VARIABLES
!
   CHARACTER TNAME*8,NM*8,FN*10,DDATE*10,&
   &TTIME*8,TTTIM*8,DDDAT*10
!
   LOGICAL EXISJK
!
   COMMON/STRNGR/DDDAT,TTTIM,NM,FN
!
   INTEGER CTAB,POINTS,OCC,NTOTAL,I,J,II
!
   real(real64) TABLE(1:1001,1:3),&
   &DATA1,DATA2,LAMB1,LAMB2
!
   INTEGER NF
!
   COMMON/TABL/TABLE,CTAB
!
   COMMON/WAVEL/LAMB1,LAMB2,NTOTAL
!
!
!       INITIALIZE II TO ZERO
   II=0
!
!       IF NUMBER OF POINTS IS LESS THAN 2, DON'T FILE THE
!       FILE, GIVE MESSAGE AND RETURN.
!
   IF(CTAB.LT.2) THEN
      WRITE(OUTLYNE,*)'LEAVING THE "TABLE" INPUT MODE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)&
      &'NO TABLE DATA EXISTED TO FILE AND NO FILE WAS CREATED'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
!       TABLE DATA IN BINARY FORMAT. TRA.DAT IS UNIT 35
!
!       DATA STORED IN TRA.DAT IS:
!               FILE NAME (TNAME) CHARACTER *8
!               DATA1 STARTING WAVELENGTH (DOUBLE PRES.)
!               DATA2 ENDIG WAVLENGTH (DOUBLE PRES.)
!               POINTS - NUMBER OF DATA POINTS (INTEGER)
!               OCC- OCCUPANCY FLAG, 0=EMPTY, 1- FULL (INTEGER)
!               DDATE- CALENDER DATE FILE WAS STORED
!               TTIME-TIME FILED
!       WE MUST SEARCH FOR A FILE TO OVERWRITE
!       ***************************************************************
   EXISJK=.FALSE.
   INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
   IF(.NOT.EXISJK) THEN
      WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       ***************************************************************
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
   &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
   DO 9 I=1,999
      READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
      DDDAT=DDATE
      TTTIM=TTIME
      IF(NM.EQ.TNAME) THEN
!       FOUND THE EARLIER VERSION OF THE TABLE FILE NAMED "TNAME"
!       OVERWRITE IT.
         II=I
         GO TO 11
      END IF
!
9  CONTINUE
!
!       NO OVERWRITE TO DO, FIND A BLANK SPOT TO FILE IN
!
   DO 10 I=1,999
      READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
      DDDAT=DDATE
      TTTIM=TTIME
      IF(OCC.EQ.0) THEN
!       FOUND AN EMPTY SLOT
         II=I
         GO TO 11
      END IF
!
!       CHECK IF NM=TNAME
!
10 CONTINUE
!       IF YOU GOT HERE, LIBRARY WAS FULL
   WRITE(OUTLYNE,*)&
   &'SPECT DISK FILE WAS FULL, TABLE DATA NOT FILED'
   CALL SHOWIT(1)
   WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
   CALL SHOWIT(1)
   CALL MACFAL
   RETURN
11 CONTINUE
!       PROCEED WITH STORAGE
!       FILE THE DIRECTORY DATA IN TRA.DAT
   DATA1=LAMB1
   DATA2=LAMB2
   IF(TABLE(1,2).GT.0.0D0) DATA1=TABLE(1,2)
   IF(TABLE(CTAB,2).GT.0.0D0) DATA2=TABLE(CTAB,2)
   POINTS=CTAB
   OCC=1
   CALL MYDATE(DDATE)
   CALL MYTIME(TTIME)
   DDDAT=DDATE
   TTTIM=TTIME
   WRITE(UNIT=35,REC=II) TNAME,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
   CALL CLOSE_FILE(35,1)
!
   NF=II
   CALL TRAFIL(NF,FN)
!
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
   &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
   CALL CLOSE_FILE(35,0)
!       OPEN AND WRITE TO FILE
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
   &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
!
!       NOW OUTPUT TABLE DATA TO TRAXXX.DAT
!
   DO 210 J=1,POINTS
      WRITE(UNIT=35,REC=J) TABLE(J,1),TABLE(J,2),TABLE(J,3)
210 CONTINUE
!
   CALL CLOSE_FILE(35,1)
   WRITE(OUTLYNE,*)&
   &'TABLE ',TNAME,' STORED IN SPECT DISK FILE NO. ',II
   CALL SHOWIT(0)
   RETURN
!
END
! SUB TABDIR.FOR
SUBROUTINE TABDIR
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
   INTEGER I
!
!       THIS SUBROUTINE HANDELS PRINTING THE DIRECTORY OF
!       SPECT DISK FILES
!
   CHARACTER NM*8,DDATE*10,TTIME*8,FN*10,TTTIM*8,DDDAT*10
!
   LOGICAL EXISJK
!
   COMMON/STRNGR/DDDAT,TTTIM,NM,FN
!
   INTEGER POINTS,OCC,OTPUT
!
   real(real64) DATA1,DATA2
!
!
!       TABLE DATA IN BINARY FORMAT. TRA.DAT IS UNIT 35
!
!       DATA STORED IN TRA.DAT IS:
!               FILE NAME (TNAME) CHARACTER *8
!               DATA1 STARTING WAVELENGTH (DOUBLE PRES.)
!               DATA2 ENDIG WAVLENGTH (DOUBLE PRES.)
!               POINTS - NUMBER OF DATA POINTS (INTEGER)
!               OCC- OCCUPANCY FLAG, 0=EMPTY, 1- FULL (INTEGER)
!               DDATE-DATE FILED
!               TTIME=TIME FILED
   IF(DF1.EQ.1) THEN
!       LIST AFF FILES
!
!       ***************************************************************
      EXISJK=.FALSE.
      INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
      IF(.NOT.EXISJK) THEN
         WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
!       ***************************************************************
      OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
      &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
!
      OTPUT=0
      DO 10 I=1,999
         READ(UNIT=35,REC=I)&
         &NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
         DDDAT=DDATE
         TTTIM=TTIME
         IF(OCC.EQ.1) THEN
            OTPUT=1
            GO TO 12
         END IF
!
10    CONTINUE
!
      IF(OTPUT.EQ.0) THEN
         WRITE(OUTLYNE,*)'SPECT DISK FILE IS EMPTY'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'NO DIRECTORY PRINTED'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
12    CONTINUE
      WRITE(OUTLYNE,100)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,101)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,106)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,102)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,101)
      CALL SHOWIT(0)
      DO 11 I=1,999
         READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
         DDDAT=DDATE
         TTTIM=TTIME
         IF(OCC.EQ.1) THEN
            WRITE(OUTLYNE,103)I,NM,DATA1,DATA2,POINTS,DDATE,TTIME
            CALL SHOWIT(0)
         END IF
!
!
11    CONTINUE
      CALL CLOSE_FILE(35,1)
   ELSE
!       JUST LIST ONE FILE IF IT EXISTS
!       ***************************************************************
      EXISJK=.FALSE.
      INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
      IF(.NOT.EXISJK) THEN
         WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
!       ***************************************************************
      OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
      &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
!
      I=INT(W1)
      READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
      DDDAT=DDATE
      TTTIM=TTIME
      CALL CLOSE_FILE(35,1)
      IF(OCC.EQ.1) THEN
!       OUTPUT
         WRITE(OUTLYNE,105) INT(W1),NM
         CALL SHOWIT(0)
         WRITE(OUTLYNE,101)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,106)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,102)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,101)
         CALL SHOWIT(0)
         WRITE(OUTLYNE,103)I,NM,DATA1,DATA2,POINTS,DDATE,TTIME
         CALL SHOWIT(0)
         RETURN
      ELSE
!       PRINT MESSAGE
         WRITE(OUTLYNE,*)'FILE # ',INT(W1),' DOES NOT EXIST'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
      END IF
      RETURN
   END IF
100 FORMAT('DIRECTORY OF SPECT FILES STORED ON DISK')
105 FORMAT('DIRECTORY FOR SPECT FILE ',I3,1X,A8)
101 FORMAT(1X)
102 FORMAT(&
   &'           ',4X,'(MICRONS)',4X,'(MICRONS)')
106 FORMAT(&
   &'FILE #/NAME',4X,'LAMBDA 1',5X,'LAMBDA 2',3X,&
   &'NO. OF POINTS',2X,'DATE/TIME FILED')
103 FORMAT(I3,1X,A8,1X,G12.4,1X,G12.4,5X,I4,7X,A9,'/',A8)
   RETURN
!
END
! SUB SSTART.FOR
SUBROUTINE SSTART
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE IS CALLED TO ENTER THE SPECT LEVEL COMMAND
!       "START"
!
   INTEGER NTOTAL,I
!
   real(real64) LAMB1,LAMB2,&
   &CUMULT(1:1001,1:3)
!
   COMMON/CUM/CUMULT
!
   COMMON/WAVEL/LAMB1,LAMB2,NTOTAL
!
!
   IF(NTOTAL.LT.0) NTOTAL=1001
   DO 5 I=1,NTOTAL
      CUMULT(I,1)=DBLE(I)
      IF(I.EQ.1) CUMULT(I,2)=LAMB1
      IF(I.NE.1) CUMULT(I,2)=CUMULT((I-1),2)+&
      &((LAMB2-LAMB1)/(DBLE(NTOTAL-1)))
5  CONTINUE
!       DEFINE AND SET THE CUMULATIVE AREA OF MEMORY
   DO 10 I=1,NTOTAL
      CUMULT(I,3)=1.0D0
10 CONTINUE
!
!                       RETURN
END
! SUB SPECTR.FOR
SUBROUTINE SPECTR
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE IS CALLED TO ENTER THE SPECT LEVEL
!       FROM THE CMD LEVEL
!
   INTEGER NTOTAL
!
   real(real64) LAMB1,LAMB2,&
   &CUMULT(1:1001,1:3)
!
   COMMON/CUM/CUMULT
!
   COMMON/WAVEL/LAMB1,LAMB2,NTOTAL
!
!
!       SPECT TAKES NO INPUT
   IF(SQ.EQ.1.OR.SN.EQ.1.OR.SST.EQ.1) THEN
      WRITE(OUTLYNE,*)&
      &'"SPECTR" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
!                       SET F17=1, LEAVE F1=1
!       SET F18 AND F19 TO 0
!       F18 TRACKS TABLE INPUT LEVEL
!       F19 TRACKS EXISTENCE OF TABLE DATA
   IF(F1.NE.1) F1=1
   F18=0
   F19=0
   NTOTAL=-99
   LAMB1=0.05
   LAMB2=20.0
   F17=1
   CALL SSTART
!                       RETURN
END
! SUB PWORK.FOR
SUBROUTINE PWORK
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE IS CALLED TO ENTER THE SPECT LEVEL
!       COMMAND "WORK" AT THE SPECTR LEVEL
!
   INTEGER NTOTAL,COUNT,I
!
   real(real64) LAMB1,LAMB2,WORK(1:1001,1:3)
!
   COMMON/WRK/WORK
!
   COMMON/WAVEL/LAMB1,LAMB2,NTOTAL
!
   WRITE(OUTLYNE,200)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,204) LAMB1
   CALL SHOWIT(0)
   WRITE(OUTLYNE,205) LAMB2
   CALL SHOWIT(0)
   WRITE(OUTLYNE,206) NTOTAL
   CALL SHOWIT(0)
   WRITE(OUTLYNE,201)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,202)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,203)
   CALL SHOWIT(0)
!       PROCEED
   DO 10 I=1,NTOTAL
      COUNT=INT(WORK(I,1))
      WRITE(OUTLYNE,100) COUNT,WORK(I,2),WORK(I,3)
      CALL SHOWIT(0)
10 CONTINUE
100 FORMAT(5X,I3,8X,G18.10,5X,G18.10)
200 FORMAT(&
   &'LISTING OF THE "SPECT" WORK MEMORY AREA')
201 FORMAT(1X)
202 FORMAT('ENTRY NUMBER',4X,'WAVLENGTH-(MICRONS)',6X,&
   &'FUNCTION VALUE')
203 FORMAT(&
   &'--------------------------------------------------------')
204 FORMAT('LAMBDA(1) = ',G18.10)
205 FORMAT('LAMBDA(2) = ',G18.10)
206 FORMAT('TOTAL NUMBER OF DATA POINTS = ',I3)
!                       RETURN
END
! SUB PTABLE.FOR
SUBROUTINE PTABLE
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE IS CALLED TO ENTER THE SPECT LEVEL
!       COMMAND "LIST" AT THE SPECTR LEVEL
!
   CHARACTER TNAME*8
!
   INTEGER CTAB,COUNT,I
!
   real(real64) LAMB1,LAMB2,TABLE(1:1001,1:3)
!
   COMMON/TABL/TABLE,CTAB
!
   COMMON/CURNAM/TNAME
!
!
   LAMB1=TABLE(1,2)
   LAMB2=TABLE(CTAB,2)
   WRITE(OUTLYNE,200) TNAME
   CALL SHOWIT(0)
   WRITE(OUTLYNE,204) LAMB1
   CALL SHOWIT(0)
   WRITE(OUTLYNE,205) LAMB2
   CALL SHOWIT(0)
   WRITE(OUTLYNE,206) CTAB
   CALL SHOWIT(0)
   WRITE(OUTLYNE,201)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,202)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,203)
   CALL SHOWIT(0)
!       PROCEED
   DO 10 I=1,CTAB
      COUNT=INT(TABLE(I,1))
      WRITE(OUTLYNE,100) COUNT,TABLE(I,2),TABLE(I,3)
      CALL SHOWIT(0)
10 CONTINUE
100 FORMAT(5X,I3,8X,G18.10,5X,G18.10)
200 FORMAT(&
   &'LISTING OF THE "SPECT" TABLE MEMORY AREA FOR FILE (',&
   &A8,' )')
201 FORMAT(1X)
202 FORMAT('ENTRY NUMBER',4X,'WAVLENGTH-(MICRONS)',6X,&
   &'FUNCTION VALUE')
203 FORMAT(&
   &'--------------------------------------------------------')
204 FORMAT(&
   &'SHORTEST WAVELENGTH VALUE CURRENTLY IN THE FILE = '&
   &,G18.10,' MICRONS')
205 FORMAT(&
   &'LONGEST  WAVELENGTH VALUE CURRENTLY IN THE FILE = '&
   &,G18.10,' MICRONS')
206 FORMAT('TOTAL NUMBER OF DATA POINTS = ',I3)
!                       RETURN
END
! SUB BLCKBD.FOR
SUBROUTINE BLCKBD
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE HANDELS THE "BLACKBDY" SPECT COMMAND.
!       BLACK BODY RADIANT SPECTRAL EMMITTANCE OR
!       BLACK BODY RADIANT SPECTRAL PHOTON EMMITTANCE VALUES
!       ARE CALCULATED FOR THE VAVELENGTH VALUES IN THE CUMULATIVE
!       AREA AND THEN MULTIPLIED INTO THE FUNCTIONAL
!       AREA IN CUMULATIVE.
!
!                       DEFINE VARIABLES
!
   INTEGER I
!
   real(real64) CUMULT(1:1001,1:3),LAMB1,LAMB2,VAL,&
   &TEST
!
   INTEGER NTOTAL
!
   COMMON/CUM/CUMULT
!
   COMMON/WAVEL/LAMB1,LAMB2,NTOTAL
!
!
   IF(WQ.EQ.'SRE') THEN
      DO 10 I=1,NTOTAL
         IF(CUMULT(I,2).EQ.0.0D0) THEN
            CUMULT(I,3)=0.0D0
            GO TO 10
         ELSE
         END IF
!       CALCULATE BB VALUE
         TEST=1.43879D4/(CUMULT(I,2)*W1)
         IF(TEST.GE.10.0D0) THEN
            CUMULT(I,3)=CUMULT(I,3)*(DEXP(-TEST))*(3.7415D4)
            CUMULT(I,3)=CUMULT(I,3)/CUMULT(I,2)
            CUMULT(I,3)=CUMULT(I,3)/CUMULT(I,2)
            CUMULT(I,3)=CUMULT(I,3)/CUMULT(I,2)
            CUMULT(I,3)=CUMULT(I,3)/CUMULT(I,2)
            CUMULT(I,3)=CUMULT(I,3)/CUMULT(I,2)
         ELSE
            CUMULT(I,3)=CUMULT(I,3)*(3.7415D4/(CUMULT(I,2)**5))*&
            &(1.0D0/(DEXP(1.43879D4/(CUMULT(I,2)*W1))-1.0D0))
         END IF

10    CONTINUE
!       CUMULATIVE AREA HAS BEEM MULTIPLIED BY THE APPRORIATE
!       BLAKBODY VALUES.
!       PRINT MESSAGE AND RETURN
      WRITE(OUTLYNE,*)'FOR T = ',W1,' DEGREES KELVIN'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'BLACK BODY SPECTRAL RADIANT EMMITTANCE VALUES HAVE BEEN'
      CALL SHOWIT(1)
      OUTLYNE='MULTIPLIED INTO THE CUMULATIVE AREA'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'UNITS ARE: Watt/(cm2-micron)'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(WQ.EQ.'SRPE') THEN
      DO 20 I=1,NTOTAL
         IF(CUMULT(I,2).EQ.0.0D0) THEN
            CUMULT(I,3)=0.0D0
            GO TO 20
         ELSE
         END IF
         TEST=1.43879D4/(CUMULT(I,2)*W1)
         IF(TEST.GE.10.0D0) THEN
            VAL=(DEXP(-TEST))*(1.88356D3)
            VAL=VAL/CUMULT(I,2)
            VAL=VAL/CUMULT(I,2)
            VAL=VAL/CUMULT(I,2)
            VAL=VAL/CUMULT(I,2)
         ELSE
            VAL=(1.88356D3/(CUMULT(I,2)**4))*&
            &(1.0D0/(DEXP(1.43879D4/(CUMULT(I,2)*W1))-1.0D0))
         END IF
         CUMULT(I,3)=CUMULT(I,3)*VAL*(1D20)

20    CONTINUE
!       CUMULATIVE AREA HAS BEEM MULTIPLIED BY THE APPRORIATE
!       BLAKBODY VALUES.
!       PRINT MESSAGE AND RETURN
      WRITE(OUTLYNE,*)'FOR T = ',W1,' DEGREES KELVIN'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'BLACK BODY SPECTRAL RADIANT PHOTON EMMITTANCE VALUES HAVE BEEN'
      CALL SHOWIT(1)
      OUTLYNE='MULTIPLIED INTO THE CUMULATIVE AREA'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'UNITS ARE: Photon/(sec-cm2-micron)'
      CALL SHOWIT(1)
      RETURN
   END IF
END
! SUB SINSERT.FOR
SUBROUTINE SINSERT
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE HANDELS INSERTING OF A RECORD INTO
!       SPECT DISK FILE WQ
!
   INTEGER III,I,J
!
   CHARACTER DDATE*10,TTIME*8,FN*10,NM*8,TTTIM*8,DDDAT*10
!
   INTEGER POINTS,OCC,CTAB,NF
!
   LOGICAL EXISJK
!
   real(real64) DATA1,DATA2,TABLE(1:1001,1:3),&
   &LAMB1,LAMB2
!
   COMMON/STRNGR/DDDAT,TTTIM,NM,FN
!
   INTEGER NTOTAL
!
   COMMON/WAVEL/LAMB1,LAMB2,NTOTAL
!
   COMMON/TABL/TABLE,CTAB
!
!
   III=0
!
!       TABLE DATA IN BINARY FORMAT. TRA.DAT IS UNIT 35
!
!       DATA STORED IN TRA.DAT IS:
!               FILE NAME (TNAME) CHARACTER *8
!               DATA1 STARTING WAVELENGTH (DOUBLE PRES.)
!               DATA2 ENDIG WAVLENGTH (DOUBLE PRES.)
!               POINTS - NUMBER OF DATA POINTS (INTEGER)
!               OCC- OCCUPANCY FLAG, 0=EMPTY, 1- FULL (INTEGER)
!               DDATE-DATE FILED
!               TTIME=TIME FILED
!       FIND THE DESIRED FILE
!       ***************************************************************
   EXISJK=.FALSE.
   INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
   IF(.NOT.EXISJK) THEN
      WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       ***************************************************************
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
   &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
!
   DO 200 I=1,999
      READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
      DDDAT=DDATE
      TTTIM=TTIME
      IF(NM.EQ.WQ) THEN
!       FOUND FILE
         GO TO 300
      END IF
200 CONTINUE
!       IF YOU GOT HERE, FILE DID NOT EXIST
   WRITE(OUTLYNE,*)'FILE ',WQ,' DOES NOT EXIST'
   CALL SHOWIT(1)
   WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
   CALL SHOWIT(1)
   CALL CLOSE_FILE(35,1)
   CALL MACFAL
   RETURN
300 CONTINUE
!       LOAD FILE INTO TABLE ARRAY
!
   NF=I
   CALL TRAFIL(NF,FN)
!
!       OPEN AND READ FROM FILE
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
   &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
!
   DO 210 J=1,POINTS
      READ(UNIT=35,REC=J) TABLE(J,1),TABLE(J,2),TABLE(J,3)
210 CONTINUE
   CALL CLOSE_FILE(35,1)
   IF(W1.LT.LAMB1.OR.W1.GT.LAMB2) THEN
      WRITE(OUTLYNE,*)&
      &'NEW WAVELENGTH IS BEYOND CURRENTLY DEFINED RANGE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
!       FIND A SPOT FOR THE NEW ENTRY
!

   DO 350 I=1,(POINTS-1)
      IF(TABLE(I,2).EQ.W1.OR.TABLE((I+1),2).EQ.W1) THEN
         WRITE(OUTLYNE,*)&
         &'NEW WAVELENGTH ENTRY EQUALS AN EXISTING WAVELENGTH VALUE'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
      IF(TABLE(I,2).LT.W1.AND.TABLE((I+1),2).GT.W1) THEN
!       NEW ENTRY GOES BETWEEN THE TWO TESTED RECORDS.
         III=I+1
         GO TO 360
      END IF
      IF(W1.LT.TABLE(1,2)) THEN
!       NEW ENTRY GOES AT BEGINNING OF LIST.
         III=1
         GO TO 360
      END IF
      IF(W1.GT.TABLE(POINTS,2)) THEN
!       NEW ENTRY GOES AT END OF LIST.
         III=POINTS+1
         GO TO 360
      END IF
350 CONTINUE
   WRITE(OUTLYNE,*)'NO INSERTION POINT FOUND'
   CALL SHOWIT(1)
   WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
   CALL SHOWIT(1)
   CALL MACFAL
   RETURN
360 CONTINUE
!
!       INCREMENT TOTAL NUMBER OF POINTS
!
   POINTS=POINTS+1
!
!       PERFORM INSERTION HERE
!
!       MOVE EVERYTHING DOWN ONE
!
   DO 370 I=POINTS,(III+1),-1
      TABLE(I,1)=TABLE((I-1),1)+1.0D0
      TABLE(I,2)=TABLE((I-1),2)
      TABLE(I,3)=TABLE((I-1),3)
370 CONTINUE
!
!       WRITE IN THE NEW DATA ITEM
!
   TABLE(III,1)=DBLE(III)
   TABLE(III,2)=W1
   TABLE(III,3)=W2
!
!       RESET PARAMETERS FOR DIRECTORY
!
   CTAB=POINTS
   CALL MYTIME(TTIME)
   CALL MYDATE(DDATE)
   DDDAT=DDATE
   TTTIM=TTIME
   IF(POINTS.EQ.0) THEN
      DATA1=0.0D0
      DATA2=0.0D0
      OCC=0
      DDATE='         '
      TTIME='        '
      DDDAT='         '
      TTTIM='        '
      NM='        '
   END IF
!
!       FILE THE FILE IN THE APPROPRIATE SPOT
!       OPEN AND WRITE TO FILE
!       ***************************************************************
   EXISJK=.FALSE.
   INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
   IF(.NOT.EXISJK) THEN
      WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       ***************************************************************
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
   &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
   WRITE(UNIT=35,REC=NF) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
   CALL CLOSE_FILE(35,1)
   IF(OCC.EQ.0) THEN
      OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
      &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
      CALL CLOSE_FILE(35,0)
   END IF
!
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
   &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
   F19=1
   DO 220 J=1,POINTS
      WRITE(UNIT=35,REC=J) TABLE(J,1),TABLE(J,2),TABLE(J,3)
220 CONTINUE
   CALL CLOSE_FILE(35,1)
!       PRINT MESSAGE TO THAT EFFECT
   WRITE(OUTLYNE,*)'ENTRY INSERTED INTO FILE ',WQ
   CALL SHOWIT(1)
   IF(OCC.EQ.0) THEN
      WRITE(OUTLYNE,*)'FILE ',WQ,' IS EMPTY'
      CALL SHOWIT(1)
      F19=0
   END IF
   RETURN
END
! SUB INTSMP.FOR
SUBROUTINE INTSMP
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE IS CALLED INTEGRATE THE CUMULATIVE
!       MEMORY AREA AND PLACE THE VALUE OF THE INTEGRAL
!       IN THE X- REGISTER
!
   INTEGER NTOTAL,I
!
   real(real64) VALUE,CUMULT(1:1001,1:3),LAMB1,LAMB2,&
   &IVAL
!
   COMMON/CUM/CUMULT
!
   COMMON/WAVEL/LAMB1,LAMB2,NTOTAL
!
!
!       THERE ARE NTOTAL POINTS IN THE CUMULATIVE AREA INLUDING
!       THE END POINTS. THEY ARE EQUALLY SPACED. EACH POINT HAS A
!       FUNCTIONAL VALUE ASSIGNED TO IT.
!
!       THE VAULE OF EACH INTERVAL IS EXACTLY
!
!               (LAMB2-LAMB1)/DBLE(NTOTAL-1)=IVAL
!
   IVAL=(LAMB2-LAMB1)/(DBLE(NTOTAL-1))
   VALUE=0.0D0
   DO 10 I=1,(NTOTAL-1)
      VALUE=VALUE+&
      &IVAL*((CUMULT(I,3)+CUMULT((I+1),3))/2.0D0)
!
10 CONTINUE
!
!       NOW SAVE THE VALUE IN THE X- REGISTER, PUSH THE STACK
!       AND UPDATE THE LASTX REGISTER.
   REG(40)=REG(9)
   REG(9)=VALUE
   WRITE(OUTLYNE,1000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,2000) VALUE
   CALL SHOWIT(0)
   WRITE(OUTLYNE,3000)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,4000)
   CALL SHOWIT(0)
1000 FORMAT(&
   &'THE VALUE OF THE INTEGRAL OF THE "SPECT" CUMULATIVE')
2000 FORMAT('MEMORY AREA = ',G18.10)
3000 FORMAT(1X)
4000 FORMAT('THIS VALUE HAS BEEN STORED IN THE X-REGISTER')
   RETURN
END
! SUB ITF.FOR
SUBROUTINE ITF
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE INITIALIZES OR BLANKS OUT THE CURRENT
!       TRANSMISSION FILE DIRECTORY.
!
   INTEGER I,OH,N
!
   CHARACTER BLANK*8,B1*9,FN*10,AN*3
!
   real(real64) ZERO
!
   LOGICAL EXISJK
!
!
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',FORM=&
   &'UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
   CALL CLOSE_FILE(35,0)
   DO N=1,999
      CALL CCOONN(N,AN)
      IF(N.GT.0.AND.N.LE.9) FN='TRA00'//AN(3:3)//'.DAT'
      IF(N.GT.9.AND.N.LE.99) FN='TRA0'//AN(2:3)//'.DAT'
      IF(N.GT.99.AND.N.LE.999) FN='TRA'//AN(1:3)//'.DAT'
      EXISJK=.FALSE.
      INQUIRE(FILE=LIBTRA//FN,EXIST=EXISJK)
      IF(EXISJK) THEN
         OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
         &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
         CALL CLOSE_FILE(35,0)
      END IF
   END DO
!
   ZERO=0.0D0
   OH=0
   BLANK='        '
   B1=   '         '
!
!       OPEN UNIT 35 FOR I/O
!
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',FORM=&
   &'UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
!
   DO 25 I=1,999
      WRITE(UNIT=35,REC=I)&
      &BLANK,ZERO,ZERO,OH,OH,B1,BLANK
25 CONTINUE
!
   CALL CLOSE_FILE(35,1)
!
!       CHECK EXISTANCE OF MACRO FILESTRA001 TO TRA999.DAT
!       IF FOUND. DELETE THEM
   CALL TRFLEX
   WRITE(OUTLYNE,*)&
   &'TRANSMISSION/REFLECTION FILES INITIALIZED'
   CALL SHOWIT(1)
   RETURN
END
! SUB CUME.FOR
SUBROUTINE CUME
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE IS CALLED TO ENTER THE SPECT LEVEL
!       COMMAND "CUME" AT THE SPECTR LEVEL
!
   INTEGER NTOTAL,COUNT,I
!
   real(real64) LAMB1,LAMB2,CUMULT(1:1001,1:3)
!
   COMMON/CUM/CUMULT
!
   COMMON/WAVEL/LAMB1,LAMB2,NTOTAL
!
   WRITE(OUTLYNE,200)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,204) LAMB1
   CALL SHOWIT(0)
   WRITE(OUTLYNE,205) LAMB2
   CALL SHOWIT(0)
   WRITE(OUTLYNE,206) NTOTAL
   CALL SHOWIT(0)
   WRITE(OUTLYNE,201)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,202)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,203)
   CALL SHOWIT(0)
!       PROCEED
   DO 10 I=1,NTOTAL
      COUNT=INT(CUMULT(I,1))
      WRITE(OUTLYNE,100) COUNT,CUMULT(I,2),CUMULT(I,3)
      CALL SHOWIT(0)
10 CONTINUE
100 FORMAT(5X,I3,8X,G18.10,5X,G18.10)
200 FORMAT(&
   &'LISTING OF THE "SPECT" CUMULATIVE MEMORY AREA')
201 FORMAT(1X)
202 FORMAT('ENTRY NUMBER',4X,'WAVLENGTH-(MICRONS)',6X,&
   &'FUNCTION VALUE')
203 FORMAT(&
   &'--------------------------------------------------------')
204 FORMAT('LAMBDA(1) = ',G18.10)
205 FORMAT('LAMBDA(2) = ',G18.10)
206 FORMAT('TOTAL NUMBER OF DATA POINTS = ',I3)


   RETURN
END
! SUB WFACTOR.FOR
SUBROUTINE WFACTOR(NUM_JK)
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE IS CALLED TO EXECUTE THE SPECT COMMAND "WFACTOR"
!       COMMAND "CUME" AT THE SPECTR LEVEL
!
   INTEGER I,NUM_JK,ALLOERR,J
!
   real(real64) CUMULT(1:1001,1:3),WVDELT,SUBSPACE &
   &,SPWTS,SPWV,CURVAL,TAREA,BIG1,WVLIM,TESTAREA,TEST2,TEST2OLD &
   &,STARTWV,STOPWV
!
   DIMENSION SPWTS(:),SPWV(:),BIG1(:),WVLIM(:)
!
   COMMON/CUM/CUMULT
!
   ALLOCATABLE :: SPWTS,SPWV,BIG1,WVLIM
   DEALLOCATE(BIG1,SPWTS,SPWV,WVLIM,STAT=ALLOERR)
   ALLOCATE(BIG1(1000),SPWTS(10),SPWV(10),WVLIM(11),STAT=ALLOERR)
!
   SPWTS(1:10)=0.0D0
   SPWV(1:10)=0.0D0
   WVDELT=DABS(CUMULT(1001,2)-CUMULT(1,2))/100.0D0
!
!     INTEGERATE THE FULL CUMULT AREA
   DO I=1,1000
      CURVAL=((CUMULT(I,3)+CUMULT(I+1,3))/2.0D0)*WVDELT
      BIG1(I)=CURVAL
   END DO
!     CALCULATE SUB-DIVISION SPACING
   SUBSPACE=DABS(CUMULT(1001,2)-CUMULT(1,2))/DBLE(NUM_JK)
!     CALCULATE ENDS OF SUB-DIVISIONS
   WVLIM(1)=CUMULT(1,2)
   DO I=2,NUM_JK+1
      WVLIM(I)=WVLIM(I-1)+SUBSPACE
   END DO
   DO I=1,1000
      DO J=1,NUM_JK
         IF((CUMULT(I,2)+CUMULT(I+1,2))/2.0D0.GE.WVLIM(J).AND.&
         &(CUMULT(I,2)+CUMULT(I+1,2))/2.0D0.LE.WVLIM(J+1))&
         &SPWTS(J)=SPWTS(J)+BIG1(I)
      END DO
   END DO
!     COMPUTE THE FULL CUMULT AREA AND NORMALIZE THE WEIGHTING FACTORS
   TAREA=0.0D0
   DO I=1,NUM_JK
      TAREA=TAREA+SPWTS(I)
   END DO
   DO I=1,NUM_JK
      SPWTS(I)=SPWTS(I)/TAREA
   END DO
!
!     NOW COMPUTE THE AREA CENTER WAVELENGTHS FOR EACH BAND
   DO I=1,NUM_JK
      STARTWV=WVLIM(I)
      STOPWV =WVLIM(I+1)
      TESTAREA=0.0D0
      DO J=1,1000
         IF((CUMULT(J,2)+CUMULT(J+1,2))/2.0D0.GE.STARTWV.AND.&
         &(CUMULT(J,2)+CUMULT(I+J,2))/2.0D0.LE.STOPWV) THEN
            TESTAREA=TESTAREA+BIG1(J)
         END IF
      END DO
      TEST2=0.0D0
      TEST2OLD=0.0D0
      DO J=1,1000
         IF((CUMULT(J,2)+CUMULT(J+1,2))/2.0D0.GE.STARTWV.AND.&
         &(CUMULT(J,2)+CUMULT(J+1,2))/2.0D0.LE.STOPWV) THEN
            TEST2OLD=TEST2
            TEST2=TEST2+BIG1(J)
            IF(TEST2OLD.LE.(TESTAREA/2.0D0).AND.TEST2.GE.(TESTAREA/2.0D0))&
            &THEN
!     SET WAVELENGTH AND GO TO 25
               SPWV(I)=(CUMULT(J,2)+CUMULT(J+1,2))/2.0D0
               GO TO 25
            END IF
         END IF
      END DO
!
25    CONTINUE
   END DO
   WRITE(OUTLYNE,202)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,203)
   CALL SHOWIT(0)
!       PROCEED
   DO I=1,NUM_JK
      WRITE(OUTLYNE,100) SPWV(I),SPWTS(I)
      CALL SHOWIT(0)
   END DO
100 FORMAT(2X,G18.10,1X,6X,2X,G18.10)
200 FORMAT(&
   &'SPECTRAL WAVELENGTHS AND WEIGHTS')
201 FORMAT(1X)
202 FORMAT(' WAVLENGTH-(MICRONS) ',6X,&
   &'   SPECTRAL WEIGHT   ')
203 FORMAT(&
   &'--------------------------------------------------------')
   DEALLOCATE(BIG1,SPWTS,SPWV,WVLIM,STAT=ALLOERR)
   RETURN
END
! SUB DROP.FOR
SUBROUTINE DROP
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
   INTEGER I,J
!
!       THIS SUBROUTINE HANDELS DROPING OF RECORD W1 FROM
!       SPECT DISK FILE WQ
!
!                       DEFINE VARIABLES
!
   CHARACTER DDATE*10,TTIME*8,FN*10,NM*8,TTTIM*8,DDDAT*10
!
   INTEGER POINTS,OCC,CTAB
!
   real(real64) DATA1,DATA2,TABLE(1:1001,1:3)
!
   LOGICAL EXISJK
!
   INTEGER NF
!
   COMMON/STRNGR/TTTIM,DDDAT,NM,FN
!
   COMMON/TABL/TABLE,CTAB
!
!
!       TABLE DATA IN BINARY FORMAT. TRA.DAT IS UNIT 35
!
!       DATA STORED IN TRA.DAT IS:
!               FILE NAME (TNAME) CHARACTER *8
!               DATA1 STARTING WAVELENGTH (DOUBLE PRES.)
!               DATA2 ENDIG WAVLENGTH (DOUBLE PRES.)
!               POINTS - NUMBER OF DATA POINTS (INTEGER)
!               OCC- OCCUPANCY FLAG, 0=EMPTY, 1- FULL (INTEGER)
!               DDATE-DATE FILED
!               TTIME=TIME FILED
!       FIND THE DESIRED FILE
!       ***************************************************************
   EXISJK=.FALSE.
   INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
   IF(.NOT.EXISJK) THEN
      WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       ***************************************************************
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
   &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
!
   DO 200 I=1,999
      READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
      TTTIM=TTIME
      DDDAT=DDATE
      IF(NM.EQ.WQ) THEN
!       FOUND FILE
         GO TO 300
      END IF
200 CONTINUE
!       IF YOU GOT HERE, FILE DID NOT EXIST
   WRITE(OUTLYNE,*)'FILE ',WQ,' DOES NOT EXIST'
   CALL SHOWIT(1)
   WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
   CALL SHOWIT(1)
   CALL CLOSE_FILE(35,1)
   CALL MACFAL
   RETURN
300 CONTINUE
!       LOAD FILE INTO TABLE ARRAY
!
   NF=I
   CALL TRAFIL(NF,FN)
!
!       OPEN AND READ FROM FILE
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
   &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
!
   DO 210 J=1,POINTS
      READ(UNIT=35,REC=J) TABLE(J,1),TABLE(J,2),TABLE(J,3)
210 CONTINUE
   CALL CLOSE_FILE(35,1)
   IF(INT(W1).LT.1.OR.INT(W1).GT.POINTS) THEN
      WRITE(OUTLYNE,*)'ENTRY # ',INT(W1),' IS BEYOND LEGAL RANGE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!

!       DELETE RECORD INT(W1) IF FOUND
   DO 350 I=INT(W1),(POINTS-1)
      TABLE(I,1)=TABLE((I+1),1)-1.0D0
      TABLE(I,2)=TABLE((I+1),2)
      TABLE(I,3)=TABLE((I+1),3)
350 CONTINUE
   POINTS=POINTS-1
   CTAB=POINTS
   CALL MYTIME(TTIME)
   CALL MYDATE(DDATE)
   TTTIM=TTIME
   DDDAT=DDATE
   IF(POINTS.EQ.0) THEN
      DATA1=0.0D0
      DATA2=0.0D0
      OCC=0
      DDATE='         '
      TTIME='        '
      DDDAT='         '
      TTTIM='        '
      NM='        '
   END IF
!
!       FILE THE FILE IN THE APPROPRIATE SPOT
!       OPEN AND WRITE TO FILE
!       ***************************************************************
   EXISJK=.FALSE.
   INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
   IF(.NOT.EXISJK) THEN
      WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       ***************************************************************
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
   &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
   WRITE(UNIT=35,REC=NF) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
   CALL CLOSE_FILE(35,1)
   IF(OCC.EQ.0) THEN
      OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
      &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
      CALL CLOSE_FILE(35,0)
   END IF
!
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
   &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
   F19=1
   DO 220 J=1,POINTS
      WRITE(UNIT=35,REC=J) TABLE(J,1),TABLE(J,2),TABLE(J,3)
220 CONTINUE
   CALL CLOSE_FILE(35,1)
!       PRINT MESSAGE TO THAT EFFECT
   WRITE(OUTLYNE,*)'ENTRY # ',INT(W1),' DELETED FROM FILE ',WQ
   CALL SHOWIT(1)
   IF(OCC.EQ.0) THEN
      WRITE(OUTLYNE,*)'FILE ',WQ,' IS NOW EMPTY'
      CALL SHOWIT(1)
      F19=0
   END IF
!
   RETURN
!
END
! SUB DELETE.FOR
SUBROUTINE DELETE
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE HANDELS DELETING A SPECT DISK FILE
!
!                       DEFINE VARIABLES
!
   INTEGER NF,I
!
   CHARACTER NM*8,FN*10,DDATE*10,TTIME*8,DDDAT*10,TTTIM*8
!
   LOGICAL EXISJK
!
   INTEGER POINTS,OCC
!
   real(real64) DATA1,DATA2
!
   COMMON/STRNGR/DDDAT,TTTIM,NM,FN
!
!
!       TABLE DATA IN BINARY FORMAT. TRA.DAT IS UNIT 35
!
!       DATA STORED IN TRA.DAT IS:
!               FILE NAME (TNAME) CHARACTER *8
!               DATA1 STARTING WAVELENGTH (DOUBLE PRES.)
!               DATA2 ENDIG WAVLENGTH (DOUBLE PRES.)
!               POINTS - NUMBER OF DATA POINTS (INTEGER)
!               OCC- OCCUPANCY FLAG, 0=EMPTY, 1- FULL (INTEGER)
!               DDATE-DATE FILED
!               TTIME=TIME FILED
!       IF DF1=0, SPECIFIC NUMERIC FILE NUMBER TO BE DELETED
!
   IF(DF1.EQ.0) THEN
      WQ='        '
      SQ=1
      IF(W1.LE.0.0.OR.W1.GT.999.0) THEN
         WRITE(OUTLYNE,*)&
         &'FILE # REQUESTED FOR DELETION IS BEYOND DEFINED'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'FILE NUMBER RANGE. VALID RANGE IS 1 TO 999.'
         CALL SHOWIT(1)
         WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
         CALL SHOWIT(1)
         CALL MACFAL
         RETURN
      END IF
   ELSE
!       DF1=1, LOOK FOR A FILE BY NAME
      GO TO 100
   END IF
!       NOW TRY TO DELETE FILE INT(W1)
!
!       ***************************************************************
   EXISJK=.FALSE.
   INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
   IF(.NOT.EXISJK) THEN
      WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       ***************************************************************
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
   &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
!
   I=INT(W1)
   READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
   TTTIM=TTIME
   DDDAT=DDATE
   IF(OCC.EQ.0) THEN
!       FILE ALREADY EMPTY
      WRITE(OUTLYNE,*)'FILE # ',INT(W1),'DOES NOT EXIST'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   ELSE
!       FILE TO BE DELETED
      NM='        '
      DATA1=0.0D0
      DATA2=0.0D0
      POINTS=0
      OCC=0
      DDATE='         '
      TTIME='        '
      DDDAT='         '
      TTTIM='        '
      WRITE(UNIT=35,REC=I)NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
      CALL CLOSE_FILE(35,1)
      NF=I
      CALL TRAFIL(NF,FN)
      OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
      &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
      CALL CLOSE_FILE(35,0)
      WRITE(OUTLYNE,*)'FILE # ',INT(W1),' DELETED'
      CALL SHOWIT(1)
   END IF
   RETURN
!
100 CONTINUE
!
!       FILE FILE NAMED WQ
!
!       ***************************************************************
   EXISJK=.FALSE.
   INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
   IF(.NOT.EXISJK) THEN
      WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       ***************************************************************
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
   &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
!
   DO 200 I=1,999
!
      READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
      DDDAT=DDATE
      TTTIM=TTIME
!
      IF(NM.EQ.WQ) THEN
!       FOUND FILE TO DELETE
         NM='        '
         DATA1=0.0D0
         DATA2=0.0D0
         POINTS=0
         OCC=0
         DDATE='         '
         TTIME='        '
         DDDAT='         '
         TTTIM='        '
         WRITE(UNIT=35,REC=I)NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
         CALL CLOSE_FILE(35,1)
         NF=I
         CALL TRAFIL(NF,FN)
         OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
         &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
         CALL CLOSE_FILE(35,0)
         WRITE(OUTLYNE,*)'FILE NAMED ',WQ,' DELETED'
         CALL SHOWIT(1)
         RETURN
      END IF
200 CONTINUE
!       NEVER FOUND FILE
   WRITE(OUTLYNE,*)'FILE NAMED ',WQ,'DOES NOT EXIST'
   CALL SHOWIT(1)
   WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
   CALL SHOWIT(1)
   CALL MACFAL
   RETURN
!
END
! SUB GFILE.FOR
SUBROUTINE GFILE
!
   use DATMAI
   use iso_fortran_env, only: real64
   IMPLICIT NONE
!
!       THIS SUBROUTINE HANDELS THE "GETFILE" SPECT COMMAND.
!
!                       DEFINE VARIABLES
!
   INTEGER I,J,JK,KI
!
   CHARACTER NM*8,FN*10,DDATE*10,TTIME*8,TTTIM*8,DDDAT*10
!
   LOGICAL EXISJK
!
   real(real64) WORK(1:1001,1:3),L1,L2,&
   &DATA1,DATA2,LAMB1,LAMB2,CUMULT(1:1001,1:3),DELLAM,WORKFC,&
   &SLOPE
!
   COMMON/STRNGR/DDDAT,TTTIM,NM,FN
!
   INTEGER OCC,POINTS,NTOTAL,NF
!
   COMMON/CUM/CUMULT
!
   COMMON/WRK/WORK
!
   COMMON/WAVEL/LAMB1,LAMB2,NTOTAL
!
!
!       TABLE DATA IN BINARY FORMAT. TRA.DAT IS UNIT 35
!
!       DATA STORED IN TRA.DAT IS:
!               FILE NAME (TNAME) CHARACTER *8
!               DATA1 STARTING WAVELENGTH (DOUBLE PRES.)
!               DATA2 ENDIG WAVLENGTH (DOUBLE PRES.)
!               POINTS - NUMBER OF DATA POINTS (INTEGER)
!               OCC- OCCUPANCY FLAG, 0=EMPTY, 1- FULL (INTEGER)
!               DDATE-DATE FILED
!               TTIME=TIME FILED
!       FIND THE DESIRED FILE
!       ***************************************************************
   EXISJK=.FALSE.
   INQUIRE(FILE=LIBTRA//'TRA.DAT',EXIST=EXISJK)
   IF(.NOT.EXISJK) THEN
      WRITE(OUTLYNE,*)'"TABLE FILES DO NOT YET EXIST'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'TO INITIALIZE IT, USE "ITF" AND "PROCEED"'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!       ***************************************************************
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//'TRA.DAT',&
   &FORM='UNFORMATTED',RECL=(50*NRECL),STATUS='UNKNOWN')
!
   DO 200 I=1,999
      READ(UNIT=35,REC=I) NM,DATA1,DATA2,POINTS,OCC,DDATE,TTIME
      DDDAT=DDATE
      TTTIM=TTIME
      IF(NM.EQ.WQ) THEN
!       FOUND FILE
         GO TO 300
      END IF
200 CONTINUE
!       IF YOU GOT HERE, FILE DID NOT EXIST
   WRITE(OUTLYNE,*)'FILE ',WQ,' DOES NOT EXIST'
   CALL SHOWIT(1)
   WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
   CALL SHOWIT(1)
   CALL CLOSE_FILE(35,1)
   CALL MACFAL
   RETURN
300 CONTINUE
!
!       ESTABLISH NEW WAVELENGTH BOUNDARIES. NO WAVELENGTH
!       VALUE MAY BE LESS THAN 0.0 MICRONS
!
   L1=(LAMB1*W1)+W2
   IF(L1.LT.0.0D0) L1=0.0D0
   L2=(LAMB2*W1)+W2
!
   IF(L1.LT.0.0D0.OR.W2.LT.0.0D0) THEN
      WRITE(OUTLYNE,*)&
      &'A NEGATIVE WAVELENGTH VALUE IS NOT ALLOWED'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(L2.LE.0.0D0.OR.L2.LE.L1) THEN
!       NO WAVELENGTH RANGE EXISTS, NO INTERPOLATION POSSIBLE
      WRITE(OUTLYNE,*)'WAVELENGTH LIMITS ARE NOT REALISTIC'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   ELSE
!       REDEFINE LAMB1 AND LAMB2
      LAMB1=L1
      LAMB2=L2
   END IF
!
!       LOAD FILE INTO WORK ARRAY
!
   NF=I
   CALL TRAFIL(NF,FN)
!
!       OPEN AND READ FROM FILE
   OPEN(UNIT=35,ACCESS='DIRECT',FILE=LIBTRA//FN,&
   &FORM='UNFORMATTED',RECL=(80*NRECL),STATUS='UNKNOWN')
!
   DO 210 J=1,POINTS
      READ(UNIT=35,REC=J) WORK(J,1),WORK(J,2),WORK(J,3)
210 CONTINUE
   CALL CLOSE_FILE(35,1)
!
!
!       INTERPOLATE TO THE POINTS DEFINED IN THE CUMULATIVE
!       AREA BY LAMB1,LAMB2 AND NTOTAL.
!
!       THE DIFFERENCE IN WAVELENGTH BETWEEN ENTRIES IN THE NEW
!       DATA WILL BE
!       (LAMB2-LAMB1)/(NTOTAL-1)
!
   DELLAM=(LAMB2-LAMB1)/(DBLE(NTOTAL)-1.0D0)
!
!       SCALE THE CURRENT WORK DATA BY THE REQUESTED
!       TRANSFORMATION.
!
   DO 505 J=1,POINTS
      WORK(J,3)=(((WORK(J,3)*W3)+W4)**INT(DABS(W5)))
505 CONTINUE
   IF(INT(W5).LT.0.0D0) THEN
      DO 506 J=1,POINTS
         IF(WORK(J,3).NE.0.0D0) WORK(J,3)=1.0D0/WORK(J,3)
         IF(WORK(J,3).EQ.0.0D0) WORK(J,3)=0.0D0
506   CONTINUE
   END IF
!
!       THESE NEW FUNCTIONAL VALUES ARE FOR THE NEW WAVELENGTH
!       VALUES :
   DO 500 J=1,POINTS
      WORK(J,2)=(WORK(J,2)*W1)+W2
      IF(WORK(J,2).LT.0.0D0) WORK(J,2)=0.0D0
500 CONTINUE
!
   IF(WORK(POINTS,2).LE.WORK(1,2)) THEN
      WRITE(OUTLYNE,*)&
      &'NEW WAVELENGTHS IN WORK AREA ARE NOT IN ASCENDING ORDER AND'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)'"GETFILE" WAS ABORTED.'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
!
!       THE NEW FUNCTIONAL VALUES ARE SPREAD OVER THE NEW LAMB1 TO
!       LAMB2 RANGE IN CUMULT, WITH SPACING DELLAM.
!
   CUMULT(1,2)=LAMB1
   CUMULT(NTOTAL,2)=LAMB2
   DO 10 J=2,(NTOTAL-1)
      CUMULT(J,2)=CUMULT((J-1),2)+DELLAM
10 CONTINUE
!
!       NOW INTERPOLATE THE WORK AREA AND MULTIPLY INTO THE
!       CUMULATIVE AREA FUNCTIONAL VALUES.
!
   SLOPE=0.0D0
   JK=1
   DO 20 J=1,POINTS-1
!
!       CALCULATE A SLOPE FROM THE WORK DATA
!
      SLOPE=(((WORK((J+1),3))-(WORK(J,3)))/&
      &((WORK((J+1),2))-(WORK(J,2))))
      KI=JK
!
!       RULES FOR INTERPOLATION (EXTRAPOLATION MAY OCCUR
!       AT END POINTS)
!
!       GET A WAVELENGTH VALUE FROM THE CUMULATIVE AREA
!       AS LONG AS THE WAVELENGTH VALUE FROM THE
!       CUMULATIVE AREA IS NOT GREATER THAN THE CURRENT
!       VALUE OF WORK((J+1),2), WE KEEP USING THE CURRENT SLOPE.
!
!       IF THE WAVELENGTH VALUE FROM CUMULATIVE AREA BECOMES
!       GREATER THAN THE CURRENT WORK((J+1),2), CALCULATE A NEW
!       SLOPE UNLESS J+1=POINTS. IF J+1=POINTS, KEEP USING
!       THE CURRENT SLOPE UNTIL THE CUMULATIVE AREA IS FILLED.
!
!       IF THE LAST WAVELENGTH VALUE IN WORK IS REACHED(J=POINTS),
!
      DO 30 I=KI,NTOTAL
         IF(CUMULT(I,2).LE.WORK((J+1),2).AND.(J+1).LE.POINTS &
         &.OR.CUMULT(I,2).GT.WORK((J+1),2).AND.(J+1).GE.POINTS) THEN
            WORKFC=(SLOPE*(CUMULT(I,2)-WORK(J,2)))+WORK(J,3)
            CUMULT(I,3)=CUMULT(I,3)*(WORKFC)
         ELSE
!       WE MUST
!       CALCULATE A NEW SLOPE. THE UNLESS OUT OF POINTS CASE WAS DONE
!       ABOVE.
            JK=I
            GO TO 20
         END IF
30    CONTINUE
!
20 CONTINUE
!
!       CUMULATIVE AREA HAS BEEM MULTIPLIED BY THE TRANSFORMED,
!       INTERPOLATED WORK AREA. PRINT MESSAGE AND RETURN
   WRITE(OUTLYNE,*)&
   &'SPECT FILE ( ',WQ,' ) READ INTO WORK AREA MEMORY'
   CALL SHOWIT(1)
   WRITE(OUTLYNE,*)'TRANSFORMED, INTERPOLATED AND'
   CALL SHOWIT(1)
   WRITE(OUTLYNE,*)&
   &'MULTIPLIED INTO THE CUMULATIVE MEMORY AREA'
   CALL SHOWIT(1)
   F19=1
!
   RETURN
!
END
