!       FIRST FILE OF CAPFN/SPOT ROUTINES

! SUB OPDIN.FOR
SUBROUTINE OPDIN
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use mod_system, only: sys_units
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
!     THIS ROUTINE INPUTS THE COMPEX APERTURE FUNCTION FROM CAPFNOUT.DAT
!     THEN IT CALCULATES THE PTOV AND RMS OPD
!
!
   INTEGER I,J,WWVN,K,ALLOERR,MEANCNT,CAPLEN,INUMPTS,IVAL3,IVAL4
!
   REAL*8 DS,REFHT,SPACEYY,SYSWV,PIT,PEAK,MEAN
!
   REAL*8 NUMPTS,CAPFNIN,&
   &WV,VAL1,VAL2,PTVOPD,MEAN2,ARG,VAL5
!
   DIMENSION CAPFNIN(:,:,:)
!
   ALLOCATABLE CAPFNIN
!
   LOGICAL EXIS73
   LOGICAL EXIS43
!
   CHARACTER CAPOUT*80,BCAPOUT*80
!
   SAVE CAPFNIN
!
   LOGICAL PLOTIT(1:10)
   COMMON/ITPLOT/PLOTIT
!
!
!
   IF(is_command_query()) THEN
      IF(WC.EQ.'CAPFNIN') OUTLYNE=&
      &'"CAPFNIN" INPUTS A CAPFN FROM AN ASCII FILE'
      IF(WC.EQ.'CAPFNIN') OUTLYNE=&
      &'"CAPFNCLR" DEALLOCATES THE CAPFNIN/CAPFNADD ARRAYS'
      IF(WC.EQ.'CAPFNADD') OUTLYNE=&
      &'"CAPFNADD" INPUTS AND ADDS A CAPFN FROM AN ASCII FILE'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(WC.EQ.'CAPFNCLR') THEN
      IF(SQ.EQ.1.OR.SN.EQ.1.OR.SST.EQ.1) THEN
         WRITE(OUTLYNE,*) WC,&
         &' TAKES NO ADDITIONAL INPUT'
         CALL SHOWIT(1)
         CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
         RETURN
      END IF
      DEALLOCATE (CAPFNIN,STAT=ALLOERR)
      CPFNEXT=.FALSE.
      PLOTIT(1)=.FALSE.
      PLOTIT(2)=.FALSE.
      PLOTIT(3)=.FALSE.
      PLOTIT(4)=.FALSE.
      PLOTIT(5)=.FALSE.
      PLOTIT(6)=.FALSE.
      PLOTIT(7)=.FALSE.
      PLOTIT(8)=.FALSE.
      PLOTIT(9)=.FALSE.
      PLOTIT(10)=.FALSE.
      ALLO=.FALSE.
      SUMMOR=.FALSE.
      ALLONUM=0
      RETURN
   END IF
   IF(SQ.EQ.1.OR.SN.EQ.1) THEN
      WRITE(OUTLYNE,*) WC,&
      &' TAKES NO NUMERIC OR QUALIFIER INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
   CAPOUT=TRIM(WS)//'.DAT'
   BCAPOUT=TRIM(WS)//'.BIN'
   IF(SST.EQ.0) CAPOUT='CAPFNOUT.DAT'
   IF(SST.EQ.0) BCAPOUT='CAPFNOUT.BIN'
   IF(WC.EQ.'CAPFNIN') CPFNEXT=.FALSE.
   IF(WC.EQ.'CAPFNIN') THEN
      DEALLOCATE (CAPFNIN,STAT=ALLOERR)
      ALLO=.FALSE.
      SUMMOR=.FALSE.
      ALLONUM=0
   END IF
   INQUIRE(FILE=CAPOUT,EXIST=EXIS73)
   INQUIRE(FILE=BCAPOUT,EXIST=EXIS43)
   IF(EXIS73) CPFNEXT=.TRUE.
   IF(.NOT.EXIS73) THEN
      OUTLYNE=&
      &'THE REQUESTED ASCII CAPFN FILE DOES NOT EXIST TO INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
!
!     OPEN FILE
!
   OPEN(UNIT=73,FILE=CAPOUT,&
   &FORM='FORMATTED',STATUS='UNKNOWN')
   OPEN(UNIT=43,ACCESS='DIRECT',FILE=BCAPOUT,&
   &FORM='UNFORMATTED',RECL=(100*NRECL),STATUS='UNKNOWN')
   REWIND(UNIT=73)
!
   READ(73,*) NUMPTS,SPACEYY
   READ(73,*) REFHT,SYSWV
!
   WV=SYSWV
   IF(sys_units().EQ.1.0D0) THEN
      WV=WV*3.93700787402D-5
   END IF
   IF(sys_units().EQ.2.0D0) THEN
      WV=WV*1.0D-4
   END IF
   IF(sys_units().EQ.3.0D0) THEN
      WV=WV*1.0D-3
   END IF
   IF(sys_units().EQ.4.0D0) THEN
      WV=WV*1.0D-6
   END IF
   IF(WC.EQ.'CAPFNIN') THEN
      DEALLOCATE(CAPFNIN,STAT=ALLOERR)
      ALLOCATE(CAPFNIN(INT(NUMPTS),INT(NUMPTS),2),STAT=ALLOERR)
      ALLO=.TRUE.
      SUMMOR=.TRUE.
      ALLONUM=INT(NUMPTS)
   END IF
!
   IF(WC.EQ.'CAPFNIN') THEN
      J=INT(NUMPTS)
      I=INT(NUMPTS)
      CAPFNIN(1:I,1:J,1:2)=0.0D0
   END IF
!
   IF(WC.EQ.'CAPFNADD'.AND..NOT.ALLO) THEN
      OUTLYNE=&
      &'"CAPFNIN" MUST HAVE BEEN USED BEFORE "CAPFNADD" MAY BE USED'
      CALL SHOWIT(1)
      OUTLYNE='NO ACTION TAKEN'
      CALL SHOWIT(1)
      CALL CLOSE_FILE(73,1)
      CALL CLOSE_FILE(43,1)
      CALL MACFAL
      RETURN
   END IF
   IF(WC.EQ.'CAPFNADD'.AND.ALLONUM.NE.INT(NUMPTS)) THEN
      OUTLYNE=&
      &'"ADDED CAPFN IS NOT THE SAME DIMENSION AS CAPFN IN STORAGE'
      CALL SHOWIT(1)
      OUTLYNE='NO ACTION TAKEN'
      CALL SHOWIT(1)
      CALL CLOSE_FILE(73,1)
      CALL CLOSE_FILE(43,1)
      CALL MACFAL
      RETURN
   END IF
!
!     READ THE FILE AND ADD THE NON-ZERO ELEMENTS
   DO J=1,INT(NUMPTS)
      DO I=1,INT(NUMPTS)
         READ(73,*) VAL1,VAL2,IVAL3,IVAL4,VAL5
         IF(CAPFNIN(I,J,1).EQ.0.0D0.AND.VAL1.NE.0.0D0) THEN
            CAPFNIN(I,J,1)=CAPFNIN(I,J,1) + VAL1
            CAPFNIN(I,J,2)=CAPFNIN(I,J,2) + VAL2
         END IF
      END DO
   END DO
   INUMPTS=INT(NUMPTS)
!     NEXT REPLACE THE OLD OPD VALUE IN THE LAST READIN CAPFN FILE WITH
!     THE NEW CORRECTED VALUE BY READING IN UNIT 43, CHANGING DSPOT(4)
!     AND WRITING IT OUT AGAIN.
   PEAK=-1.0D+100
   PIT = 1.0D+100
   MEAN=0.0D0
   MEAN2=0.0D0
   RMSOPD=0.0D0
   PTVOPD=0.0D0
   MEANCNT=0
   DO J=1,INT(NUMPTS)
      DO I=1,INT(NUMPTS)
         IF(CAPFNIN(I,J,1).NE.0.0D0) THEN
            IF(CAPFNIN(I,J,2).GE.PEAK) PEAK=CAPFNIN(I,J,2)
            IF(CAPFNIN(I,J,2).LE.PIT)  PIT =CAPFNIN(I,J,2)
            MEAN=MEAN+((CAPFNIN(I,J,2))/(TWOPII))
            MEAN2=MEAN2+(((CAPFNIN(I,J,2))/(TWOPII))**2)
            MEANCNT=MEANCNT+1
         END IF
      END DO
   END DO
   PTVOPD=(PEAK-PIT)/(TWOPII)
   PTOVOPD(0)=PTVOPD
   PTOVOPD(1)=PTVOPD
   PTOVOPD(2)=PTVOPD
   PTOVOPD(3)=PTVOPD
   PTOVOPD(4)=PTVOPD
   PTOVOPD(5)=PTVOPD
   PTOVOPD(6)=PTVOPD
   PTOVOPD(7)=PTVOPD
   PTOVOPD(8)=PTVOPD
   PTOVOPD(9)=PTVOPD
   PTOVOPD(10)=PTVOPD

   ARG=((MEAN2-((MEAN**2)/&
   &DBLE(MEANCNT)))/DBLE(MEANCNT-1))
   IF(ARG.LT.0.0D0) THEN
      OUTLYNE=&
      &'RMSOPD ERROR OCCURED, CAPFNIN RMSOPD CALCULATION HAS FAILED'
      CALL SHOWIT(1)
      CALL MACFAL
      CALL CLOSE_FILE(73,1)
      CALL CLOSE_FILE(43,1)
      RETURN
   END IF
   RMSOPD=DSQRT(ARG)
   RMSOP(1)=DSQRT(ARG)
   RMSOP(2)=DSQRT(ARG)
   RMSOP(3)=DSQRT(ARG)
   RMSOP(4)=DSQRT(ARG)
   RMSOP(5)=DSQRT(ARG)
   RMSOP(6)=DSQRT(ARG)
   RMSOP(7)=DSQRT(ARG)
   RMSOP(8)=DSQRT(ARG)
   RMSOP(9)=DSQRT(ARG)
   RMSOP(10)=DSQRT(ARG)

!
   IF(WC.EQ.'CAPFNIN'.OR.WC.EQ.'CAPFNADD') THEN
!     SAVE THE SUMMED CAPFN
      ITOT=(INT(NUMPTS)**2)+1
      K=1
      DO J=2,ITOT
         READ(UNIT=43,REC=J) DSPOT(1),DSPOT(2),DSPOT(3),DSPOT(4)&
         &,DSPOT(5),DSPOT(6),DSPOT(7),DSPOT(8),DSPOT(9),DSPOT(10),&
         &DSPOT(11),DSPOT(12),DSPOT(13),DSPOT(14),DSPOT(15),DSPOT(16)&
         &,DSPOT(17)&
         &,DSPOT(18),DSPOT(19),DSPOT(20),DSPOT(21),DSPOT(22),DSPOT(23)&
         &,DSPOT(24)&
         &,DSPOT(25),DSPOT(26),DSPOT(27),DSPOT(28),DSPOT(29)&
         &,DSPOT(30),DSPOT(31),DSPOT(32),DSPOT(33),DSPOT(34),DSPOT(35)&
         &,DSPOT(36),DSPOT(37),DSPOT(38),DSPOT(39),DSPOT(40),DSPOT(41)&
         &,DSPOT(42),DSPOT(43),DSPOT(44),DSPOT(45),DSPOT(46),DSPOT(47)&
         &,DSPOT(48),DSPOT(49),DSPOT(50)
         IF(DSPOT(12).NE.0.0D0.AND.WC.EQ.'CAPFNADD'.OR.&
         &WC.EQ.'CAPFNIN') THEN
!     LOAD DSPOT(*) INTO DSPOTT(*,ID)
            ID=J-1
            CALL SPOTIT(3)
         END IF
      END DO
      NUMCOL=1
      READ(UNIT=43,REC=ITOT+1) WVSHORT,SHORT,NUMCOL,LFOB(1),LFOB(2)&
      &,LFOB(3),LFOB(4),LFOB(5),LFOB(6),LFOB(7),IW,DDEELL
      CALL CLOSE_FILE(43,1)
      CPFNEXT=.TRUE.
      PLOTIT(1)=.TRUE.
      PLOTIT(2)=.FALSE.
      PLOTIT(3)=.FALSE.
      PLOTIT(4)=.FALSE.
      PLOTIT(5)=.FALSE.
      PLOTIT(6)=.FALSE.
      PLOTIT(7)=.FALSE.
      PLOTIT(8)=.FALSE.
      PLOTIT(9)=.FALSE.
      PLOTIT(10)=.FALSE.
   END IF
!
   CALL CLOSE_FILE(73,1)
   CALL CLOSE_FILE(43,1)
   RETURN
END
! SUB CAPGRID.FOR
SUBROUTINE CAPGRID
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use mod_system, only: sys_units, sys_wavelength
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
!     THIS ROUTINE OUTPUTS THE COMPEX APERTURE FUNCTION AS A PHASE
!     AND AN APODIZATION GRID FILE FOR LATER INPUT
!
   INTEGER I,J,K,WWVN,NUMPTS,WVN1
!
   CHARACTER UNIS*6
!
   LOGICAL READOK
!
   REAL*8 SPACING,WAV,MAXX,MAXY,MINX,MINY
!
!
   IF(is_command_query()) THEN
      OUTLYNE=&
      &'"CAPGRID" OUTPUTS THE CURRENT CAPFN TO AN ASCII FILES'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'"GRIDAPD" AND "GRIDOPD'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.SQ.EQ.1) THEN
      OUTLYNE=&
      &'"CAPGRID" TAKES NO QUALIFIER OR STRING INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(S2.EQ.1.OR.S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      OUTLYNE=&
      &'"CAPGRID" TAKES NO NUMERIC WORD #2 THROUGH #5 INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(S1.EQ.0) THEN
      OUTLYNE=&
      &'"CAPGRID" REQUIRES EXPLICIT NUMERIC WORD #1 INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(.NOT.CPFNEXT) THEN
      OUTLYNE=&
      &'NO CAPFN EXISTS'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
!     DEFAULT WAVELENGTH IS CONTROL WAVELENGTH
   IF(INT(W1).LT.1.OR.INT(W1).GT.10) THEN
      OUTLYNE=&
      &'NUMERIC WORD #1 MUST BE 1, 2, 3, 4, 5, 6, 7, 8, 9 OR 10'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
   OPEN(UNIT=45,FILE='GRIDAPD.DAT',&
   &FORM='FORMATTED',STATUS='UNKNOWN')
   CALL CLOSE_FILE(45,0)
   OPEN(UNIT=46,FILE='GRIDOPD.DAT',&
   &FORM='FORMATTED',STATUS='UNKNOWN')
   CALL CLOSE_FILE(46,0)
!
!     OPEN GRIDAPD AND GRIDOPD.DAT
!
   OPEN(UNIT=45,FILE='GRIDAPD.DAT',&
   &FORM='FORMATTED',STATUS='UNKNOWN')
   OPEN(UNIT=46,FILE='GRIDOPD.DAT',&
   &FORM='FORMATTED',STATUS='UNKNOWN')
!
   WVN1=INT(LFOB(4))
   WAV=sys_wavelength(WVN1)
   IF(sys_units().EQ.1.0D0) WAV=WAV*&
   &((1.0D-3)/(25.4D0))
   IF(sys_units().EQ.2.0D0) WAV=WAV*(1.0D-4)
   IF(sys_units().EQ.3.0D0) WAV=WAV*(1.0D-3)
   IF(sys_units().EQ.4.0D0) WAV=WAV*(1.0D-6)
   READOK=.FALSE.
   NUMPTS=INT((DSQRT((DBLE(ITOT-1)/DBLE(NUMCOL)))))
   MAXX=-1E30
   MAXY=-1E30
   MINX=1E30
   MINY=1E30
   K=1
   DO J=1,NUMPTS
      DO I=1,NUMPTS
         K=K+1
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
         ID=K-1
         CALL SPOTIT(4)
         IF(DSPOT(16).EQ.W1) THEN
            IF(DSPOT(5).GE.MAXX) MAXX=DSPOT(5)
            IF(DSPOT(6).GE.MAXY) MAXY=DSPOT(6)
            IF(DSPOT(5).LE.MINX) MINX=DSPOT(5)
            IF(DSPOT(6).LE.MINY) MINY=DSPOT(6)
            WRITE(45,15) I,J,DSPOT(12)
            WRITE(46,15) I,J,(DSPOT(4)/(TWOPII))*WAV
            READOK=.TRUE.
         END IF
      END DO
   END DO
15 FORMAT(I6,',',I6,',',D23.15)
!
   IF(READOK) THEN
      CALL CLOSE_FILE(45,1)
      CALL CLOSE_FILE(46,1)
      WRITE(OUTLYNE,*)&
      &'CAPFN DATA FOR WAVELENGTH NUMBER ',INT(W1)
      CALL SHOWIT(1)
      OUTLYNE='EXISTS. "GRIDAPD.DAT" AND "GRIDOPD.DAT" WERE WRITTEN'
      CALL SHOWIT(1)
      IF((MAXX-MINX).GE.(MAXY-MINY)) THEN
         SPACING=(MAXX-MINX)/(DBLE(NUMPTS)-1.0D0)
      ELSE
         SPACING=(MAXY-MINY)/(DBLE(NUMPTS)-1.0D0)
      END IF
      IF(sys_units().EQ.1.0D0) UNIS='INCHES'
      IF(sys_units().EQ.2.0D0) UNIS='CM    '
      IF(sys_units().EQ.3.0D0) UNIS='MM    '
      IF(sys_units().EQ.4.0D0) UNIS='METERS'
      REG(40)=REG(9)
      REG(9)=SPACING
      WRITE(OUTLYNE,20) SPACING,UNIS
      CALL SHOWIT(0)
20    FORMAT(&
      &'GRID SPACING AT THE CURRENT REFERENCE SURFACE = ',G13.6,&
      &1X,A6)
   ELSE
      CALL CLOSE_FILE(44,1)
      CALL CLOSE_FILE(43,1)
      WRITE(OUTLYNE,*)&
      &'CAPFN DATA FOR WAVELENGTH NUMBER ',INT(W1)
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL(&
      & 'DOES NOT EXIST. NO ASCII CAPFN FILE WAS WRITTEN'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
   END IF
   RETURN
END
! SUB OPDOUT.FOR
SUBROUTINE OPDOUT
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_clap_type, surf_clap_dim, surf_array_parity
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
!     THIS ROUTINE OUTPUTS THE COMPEX APERTURE FUNCTION TO AN ASCII FILE
!
!
   INTEGER I,KK,G,WWVN,CAPLEN
!
   REAL*8 NUMPTS,REFHT,SPACEYY
!
   CHARACTER CAPOUT*80,BCAPOUT*80
!
!
!
   IF(is_command_query()) THEN
      OUTLYNE=&
      &'"CAPFNOUT" OUTPUTS THE CURRENT CAPFN TO AN ASCII FILE'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SQ.EQ.1.OR.SN.EQ.1) THEN
      OUTLYNE=&
      &'"CAPFNOUT" TAKES NO STRING OR QUALIFIER INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
   CAPOUT=TRIM(WS)//'.DAT'
   BCAPOUT=TRIM(WS)//'.BIN'
   IF(WS.EQ.'        ')  CAPOUT='CAPFNOUT.DAT'
   IF(WS.EQ.'        ') BCAPOUT='CAPFNOUT.BIN'
   IF(.NOT.CPFNEXT) THEN
      OUTLYNE=&
      &'NO CAPFN EXISTS'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
! WINRER
!        CALL IOSDELETEFILE(CAPOUT)
!        CALL IOSDELETEFILE(BCAPOUT)
!
!     OPEN CAPFNOUT.DAT
!
   OPEN(UNIT=73,FILE=CAPOUT,&
   &FORM='FORMATTED',STATUS='UNKNOWN')
   OPEN(UNIT=43,ACCESS='DIRECT',FILE=BCAPOUT,&
   &FORM='UNFORMATTED',RECL=(100*NRECL),STATUS='UNKNOWN')
!
!     DETERMINE THE REFERNCE APERTURE HEIGHT
!     OF THE REF SURFACE COORDINATES
   IF(surf_clap_type(NEWREF) >= 1.AND.surf_clap_type(NEWREF) <= 5.AND.surf_array_parity(NEWREF) == 0) THEN
      IF(surf_clap_type(NEWREF) == 1) THEN
         IF(surf_clap_dim(NEWREF, 1).LE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RECT CLAP
!
      IF(surf_clap_type(NEWREF) == 2) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        ELIP CLAP
!
      IF(surf_clap_type(NEWREF) == 3) THEN
         IF(surf_clap_dim(NEWREF, 1).GE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RCTK CLAP
!
      IF(surf_clap_type(NEWREF) == 4) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        POLY CLAP
!
      IF(surf_clap_type(NEWREF) == 5) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 1))
      END IF
!
!       IPOLY CLAP
!
      IF(surf_clap_type(NEWREF) == 6) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 5))
      END IF
!
   ELSE
!       NO CLAP ON REF SURF.
      IF(PXTRAY(1,NEWREF).GE.PXTRAX(1,NEWREF)) THEN
         REFHT=PXTRAY(1,NEWREF)
      ELSE
         REFHT=PXTRAX(1,NEWREF)
      END IF
   END IF
!
   KK=1
   WRITE(UNIT=43,REC=1) ITOT
   G=ITOT+1
   WRITE(UNIT=43,REC=G) WVSHORT,SHORT,NUMCOL,LFOB(1),LFOB(2)&
   &,LFOB(3),LFOB(4),LFOB(5),LFOB(6),LFOB(7),IW,DDEELL
!
   WVN=INT(LFOB(4))
   IF(WVN.EQ.1) WWVN=1
   IF(WVN.EQ.2) WWVN=2
   IF(WVN.EQ.3) WWVN=3
   IF(WVN.EQ.4) WWVN=4
   IF(WVN.EQ.5) WWVN=5
   IF(WVN.EQ.6) WWVN=71
   IF(WVN.EQ.7) WWVN=72
   IF(WVN.EQ.8) WWVN=73
   IF(WVN.EQ.9) WWVN=74
   IF(WVN.EQ.10) WWVN=75
   REFHT=REFHT*DDEELL
   NUMPTS=(DSQRT((DBLE(ITOT-1)/DBLE(NUMCOL))))
   SPACEYY=REFHT/(NUMPTS-1.0D0)
   REWIND(UNIT=73)
   WRITE(73,15) NUMPTS,SPACEYY
   DO I=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=I-1
      CALL SPOTIT(4)
      WRITE(UNIT=43,REC=I) DSPOT(1),DSPOT(2),DSPOT(3),DSPOT(4)&
      &,DSPOT(5),DSPOT(6),DSPOT(7),DSPOT(8),DSPOT(9),DSPOT(10),&
      &DSPOT(11),DSPOT(12),DSPOT(13),DSPOT(14),DSPOT(15),DSPOT(16)&
      &,DSPOT(17)&
      &,DSPOT(18),DSPOT(19),DSPOT(20),DSPOT(21),DSPOT(22),DSPOT(23)&
      &,DSPOT(24)&
      &,DSPOT(25),DSPOT(26),DSPOT(27),DSPOT(28),DSPOT(29)&
      &,DSPOT(30),DSPOT(31),DSPOT(32),DSPOT(33),DSPOT(34),DSPOT(35)&
      &,DSPOT(36),DSPOT(37),DSPOT(38),DSPOT(39),DSPOT(40),DSPOT(41)&
      &,DSPOT(42),DSPOT(43),DSPOT(44),DSPOT(45),DSPOT(46),DSPOT(47)&
      &,DSPOT(48),DSPOT(49),DSPOT(50)
      WRITE(73,19) DSPOT(12),DSPOT(4),INT(DSPOT(7))&
      &,INT(DSPOT(8)),DSPOT(35)
   END DO
   WRITE(73,17) REFRY(1,NEWOBJ),REFRY(2,NEWOBJ),REFRY(3,NEWOBJ)
   WRITE(73,17) REFRY(4,NEWOBJ),REFRY(5,NEWOBJ),REFRY(6,NEWOBJ)
   WRITE(73,18) REFRY(25,NEWOBJ)
15 FORMAT(D23.15,',',D23.15)
16 FORMAT(D23.15,',',D23.15,',',I3,',',I3)
17 FORMAT(D23.15,',',D23.15,',',D23.15)
18 FORMAT(D23.15)
19 FORMAT(D23.15,',',D23.15,',',I3,',',I3,',',D23.15)
!
   CALL CLOSE_FILE(73,1)
   CALL CLOSE_FILE(43,1)
   RETURN
END
! SUB WAMAP.FOR
SUBROUTINE WAMAP
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_clap_type, surf_clap_dim, surf_array_parity
   use mod_system, only: sys_wl_ref
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
   INTEGER KKK,KVAL,I,KKV,ALLOERR
!
   REAL*8 F,X,Y
   DIMENSION F(:,:),X(:),Y(:)
   ALLOCATABLE :: F,X,Y
!
   REAL*8 REFHT,WVAL
!
!
   IF(is_command_query()) THEN
      OUTLYNE=&
      &'"WAMAP" GENERATES A WAVEFRONT MAP USING CAPFN DATA'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(SQ.EQ.1.OR.SST.EQ.1) THEN
      OUTLYNE=&
      &'"WAMAP" TAKES NO QUALIFIER OR ALPHANUMERIC INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
!
   IF(S3.EQ.1.OR.S2.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      OUTLYNE=&
      &'"WAMAP" ONLY TAKES NUMERIC WORD #1 INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
!     DEFAULT WAVELENGTH IS CONTROL WAVELENGTH
   IF(DF1.EQ.1) W1=sys_wl_ref()
   IF(INT(W1).LT.1.OR.INT(W1).GT.10) THEN
      OUTLYNE=&
      &'NUMERIC WORD #1 MUST BE 1, 2, 3, 4, 5, 6, 7, 8, 9 OR 10'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(.NOT.CPFNEXT) THEN
      OUTLYNE=&
      &'NO CAPFN EXISTS'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
!
!     DETERMINE THE REFERNCE APERTURE HEIGHT
!     OF THE REF SURFACE COORDINATES
   IF(surf_clap_type(NEWREF) >= 1.AND.surf_clap_type(NEWREF) <= 5.AND.surf_array_parity(NEWREF) == 0) THEN
      IF(surf_clap_type(NEWREF) == 1) THEN
         IF(surf_clap_dim(NEWREF, 1).LE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RECT CLAP
!
      IF(surf_clap_type(NEWREF) == 2) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        ELIP CLAP
!
      IF(surf_clap_type(NEWREF) == 3) THEN
         IF(surf_clap_dim(NEWREF, 1).GE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RCTK CLAP
!
      IF(surf_clap_type(NEWREF) == 4) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        POLY CLAP
!
      IF(surf_clap_type(NEWREF) == 5) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 1))
      END IF
!        IPOLY CLAP
!
      IF(surf_clap_type(NEWREF) == 6) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 5))
      END IF
!
   ELSE
!       NO CLAP ON REF SURF.
      IF(PXTRAY(1,NEWREF).GE.PXTRAX(1,NEWREF)) THEN
         REFHT=(PXTRAY(1,NEWREF))
      ELSE
         REFHT=(PXTRAX(1,NEWREF))
      END IF
   END IF
!
   WVAL=(W1)
   KKV=(ITOT-1)/NUMCOL
!     KKV IS THE TOTAL NUMBER OF POINTS AT THE DESIRED COLOR
!     AND IT IS AN EXACT SQUARE
   DO I=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=I-1
      CALL SPOTIT(4)
!
      IF((DSPOT(16)).EQ.WVAL) THEN
         KVAL=I
         GO TO 10
      END IF
!
   END DO
10 CONTINUE
!
   IF(WVAL.GT.NUMCOL) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & 'CAPFN DATA FOR THE WAVELENGTH VALUE (NUMERIC WORD 1)'//'\n'//&
      & 'DOES NOT EXIST'//'\n'//&
      & 'NO ACTION TAKEN', 1)
      RETURN
   END IF
   KKK=INT(SQRT(REAL(KKV)))
   DEALLOCATE(F,X,Y,STAT=ALLOERR)
   ALLOCATE(F(KKK,KKK),X(KKK),Y(KKK),STAT=ALLOERR)
!
   CALL WAPPLOT(KVAL,REFHT,WVAL,KKV,F,X,Y,KKK)
   DEALLOCATE(F,X,Y,STAT=ALLOERR)
!
   RETURN
END
! SUB AMAP.FOR
SUBROUTINE AMAP
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_clap_type, surf_clap_dim, surf_array_parity
   use mod_system, only: sys_wl_ref
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
   INTEGER KKK,KVAL,I,KKV,ALLOERR
!
   REAL*8 F,X,Y
   DIMENSION F(:,:),X(:),Y(:)
   ALLOCATABLE :: F,X,Y
!
   REAL*8 REFHT,WVAL
!
!
   IF(is_command_query()) THEN
      OUTLYNE=&
      &'"AMAP" GENERATES AN APERTURE APODIZATION FILE USING CAPFN DATA'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(SQ.EQ.1.OR.SST.EQ.1) THEN
      OUTLYNE=&
      &'"AMAP" TAKES NO QUALIFIER OR ALPHANUMERIC INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
!
   IF(S3.EQ.1.OR.S2.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      OUTLYNE=&
      &'"AMAP" ONLY TAKES NUMERIC WORD #1 INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
!     DEFAULT WAVELENGTH IS CONTROL WAVELENGTH
   IF(DF1.EQ.1) W1=sys_wl_ref()
   IF(INT(W1).LT.1.OR.INT(W1).GT.10) THEN
      OUTLYNE=&
      &'NUMERIC WORD #1 MUST BE 1, 2, 3, 4, 5, 6, 7, 8, 9 OR 10'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(.NOT.CPFNEXT) THEN
      OUTLYNE=&
      &'NO CAPFN EXISTS'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
!
!     DETERMINE THE REFERNCE APERTURE HEIGHT
!     OF THE REF SURFACE COORDINATES
   IF(surf_clap_type(NEWREF) >= 1.AND.surf_clap_type(NEWREF) <= 5.AND.surf_array_parity(NEWREF) == 0) THEN
      IF(surf_clap_type(NEWREF) == 1) THEN
         IF(surf_clap_dim(NEWREF, 1).LE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RECT CLAP
!
      IF(surf_clap_type(NEWREF) == 2) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        ELIP CLAP
!
      IF(surf_clap_type(NEWREF) == 3) THEN
         IF(surf_clap_dim(NEWREF, 1).GE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RCTK CLAP
!
      IF(surf_clap_type(NEWREF) == 4) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        POLY CLAP
!
      IF(surf_clap_type(NEWREF) == 5) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 1))
      END IF
!        IPOLY CLAP
!
      IF(surf_clap_type(NEWREF) == 6) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 5))
      END IF
!
   ELSE
!       NO CLAP ON REF SURF.
      IF(PXTRAY(1,NEWREF).GE.PXTRAX(1,NEWREF)) THEN
         REFHT=PXTRAY(1,NEWREF)
      ELSE
         REFHT=PXTRAX(1,NEWREF)
      END IF
   END IF
!
   WVAL=(W1)
   KKV=(ITOT-1)/NUMCOL
!     KKV IS THE TOTAL NUMBER OF POINTS AT THE DESIRED COLOR
!     AND IT IS AN EXACT SQUARE
   DO I=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=I-1
      CALL SPOTIT(4)
!
      IF((DSPOT(16)).EQ.WVAL) THEN
         KVAL=I
         GO TO 10
      END IF
!
   END DO
10 CONTINUE
!
   IF(WVAL.GT.NUMCOL) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & 'CAPFN DATA FOR THE WAVELENGTH VALUE (NUMERIC WORD 1)'//'\n'//&
      & 'DOES NOT EXIST'//'\n'//&
      & 'NO ACTION TAKEN', 1)
      RETURN
   END IF
   KKK=INT(SQRT(REAL(KKV)))
!
   DEALLOCATE(F,X,Y,STAT=ALLOERR)
   ALLOCATE(F(KKK,KKK),X(KKK),Y(KKK),STAT=ALLOERR)
   CALL APPLOT(KVAL,REFHT,WVAL,KKV,F,X,Y,KKK)
!
   DEALLOCATE(F,X,Y,STAT=ALLOERR)
   RETURN
END
! SUB WAPPLOT.FOR
SUBROUTINE WAPPLOT(KVAL,REFHT,WVAL,KKV,F,X,Y,KKK)
!     KVAL IS THE FIRST RECORD OF THE SPOT FILE TO READ
!     REFHT IS THE NORMALIZING AP HT.
!     WVAL IS THE DESIRED WAVELENGTH NUMBER
!     KKV IS THE TOTAL NUMBER OF POINTS TO BE READ IN FROM DSPOTT
!
   use DATSP1
   use DATLEN
   use DATMAI
   IMPLICIT NONE
!
   INTEGER KVAL,K,I,J,NNX,NNY,KK,KKK,IQ,KKV,II,IIVAL
!
   CHARACTER AV(1:129)*129,SSYM*1
!
   REAL*8 F,X,Y,DL1,FV &
   &,REFHT,XMIN,YMIN,ZMIN,XMAX,YMAX,ZMAX,WVAL
!
   DIMENSION F(KKK,KKK),X(KKK),Y(KKK)
!
!
   XMAX=-1.0E10
   YMAX=-1.0E10
   ZMAX=-1.0E10
   XMIN=1.0E10
   YMIN=1.0E10
   ZMIN=1.0E10
   AV(1:129)=' '
   FV=0.0D0
!
!     OPEN OPDMAP.DAT FOR OUTPUT
!
   OPEN(UNIT=70,ACCESS='SEQUENTIAL',BLANK='NULL'&
   &,FORM='FORMATTED',FILE='OPDMAP.DAT'&
   &,STATUS='UNKNOWN')
!
   I=1
   J=0
   DO IQ=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=IQ-1
      CALL SPOTIT(4)
!
      IF(DSPOT(16).NE.WVAL) THEN
         GO TO 101
      END IF
!
      J=J+1
      IF(J.GT.KKK) THEN
         J=1
         I=I+1
      END IF
      F(J,I)=DSPOT(4)/(TWOPII)
1000  FORMAT(D14.6,1X,D14.6,1X,D14.6,1X,D14.6)
!     WRITE X AND Y RAY COORD AT REF SURFACE AND OPD VALUE AND REFHT
      WRITE(70,1000) DSPOT(5),DSPOT(6),F(J,I),REFHT
!     INCLUDE IT IN SEARCH FOR ZMAX AND ZMIN
      IF(F(J,I).GT.ZMAX) ZMAX=F(J,I)
      IF(F(J,I).LE.ZMIN) ZMIN=F(J,I)
101   CONTINUE
   END DO
   J=0
   I=1
   DO IQ=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=IQ-1
      CALL SPOTIT(4)
!
      IF(DSPOT(16).NE.WVAL) THEN
         GO TO 1100
      END IF
!
      J=J+1
      IF(J.GT.KKK) THEN
         GO TO 100
      END IF
      X(J)=DSPOT(5)/REFHT
      Y(J)=DSPOT(6)/REFHT
      IF(X(J).GT.XMAX) XMAX=X(J)
      IF(X(J).LE.XMIN) XMIN=X(J)
      IF(Y(J).GT.YMAX) YMAX=X(J)
      IF(Y(J).LE.YMIN) YMIN=X(J)
1100  CONTINUE
   END DO
100 CONTINUE
!     NOW DISPLAY THE WAVEFRONT MAP IN A TEXT FORM USING
!     1 THROUGH 9 AND A THROUGH Z TO REPRESENT 35 LEVELS FROM ZMIN
!     TO ZMAX. THE 0 IS RESERVED FOR OPD'S WHICH ARE EXACTLY ZERO
!     WHICH MIGHT MEAN ZERO OPD OR NO SYSTEM THROUGHPUT.
   DL1=DABS((ZMAX-ZMIN)/35.0D0)
!     Z REPRESENTS VALUES FROM ZMIN TO ZMIN+DL1
!     Y REPRESENTS VALUES FROM (ZMIN+DL1) TO
!         (ZMIN+(2.0D0*DL1)
!     ETC TILL
!     1 REPRESENTS ZMAX-DL1 TO ZMAX
!
   J=0
   I=1
!     READ DSPOTT
   DO IQ=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=IQ-1
      CALL SPOTIT(4)
!
      IF(DSPOT(16).NE.WVAL) THEN
         GO TO 105
      END IF
!
      J=J+1
      IF(J.GT.KKK) THEN
         J=1
         I=I+1
      END IF
      FV=DSPOT(4)/(TWOPII)
      IF(FV.GE.ZMIN.AND.FV.LT.(ZMIN+DL1)) SSYM='Z'
      IF(FV.GE.ZMIN+(1.0D0*DL1).AND.FV.LT.(ZMIN+(2.0D0*DL1))) SSYM='Y'
      IF(FV.GE.ZMIN+(2.0D0*DL1).AND.FV.LT.(ZMIN+(3.0D0*DL1))) SSYM='X'
      IF(FV.GE.ZMIN+(3.0D0*DL1).AND.FV.LT.(ZMIN+(4.0D0*DL1))) SSYM='W'
      IF(FV.GE.ZMIN+(4.0D0*DL1).AND.FV.LT.(ZMIN+(5.0D0*DL1))) SSYM='V'
      IF(FV.GE.ZMIN+(5.0D0*DL1).AND.FV.LT.(ZMIN+(6.0D0*DL1))) SSYM='U'
      IF(FV.GE.ZMIN+(6.0D0*DL1).AND.FV.LT.(ZMIN+(7.0D0*DL1))) SSYM='T'
      IF(FV.GE.ZMIN+(7.0D0*DL1).AND.FV.LT.(ZMIN+(8.0D0*DL1))) SSYM='S'
      IF(FV.GE.ZMIN+(8.0D0*DL1).AND.FV.LT.(ZMIN+(9.0D0*DL1))) SSYM='R'
      IF(FV.GE.ZMIN+(9.0D0*DL1).AND.FV.LT.(ZMIN+(10.0D0*DL1))) SSYM='Q'
      IF(FV.GE.ZMIN+(10.0D0*DL1).AND.FV.LT.(ZMIN+(11.0D0*DL1))) SSYM='P'
      IF(FV.GE.ZMIN+(11.0D0*DL1).AND.FV.LT.(ZMIN+(12.0D0*DL1))) SSYM='O'
      IF(FV.GE.ZMIN+(12.0D0*DL1).AND.FV.LT.(ZMIN+(13.0D0*DL1))) SSYM='N'
      IF(FV.GE.ZMIN+(13.0D0*DL1).AND.FV.LT.(ZMIN+(14.0D0*DL1))) SSYM='M'
      IF(FV.GE.ZMIN+(14.0D0*DL1).AND.FV.LT.(ZMIN+(15.0D0*DL1))) SSYM='L'
      IF(FV.GE.ZMIN+(15.0D0*DL1).AND.FV.LT.(ZMIN+(16.0D0*DL1))) SSYM='K'
      IF(FV.GE.ZMIN+(16.0D0*DL1).AND.FV.LT.(ZMIN+(17.0D0*DL1))) SSYM='J'
      IF(FV.GE.ZMIN+(17.0D0*DL1).AND.FV.LT.(ZMIN+(18.0D0*DL1))) SSYM='I'
      IF(FV.GE.ZMIN+(18.0D0*DL1).AND.FV.LT.(ZMIN+(19.0D0*DL1))) SSYM='H'
      IF(FV.GE.ZMIN+(19.0D0*DL1).AND.FV.LT.(ZMIN+(20.0D0*DL1))) SSYM='G'
      IF(FV.GE.ZMIN+(20.0D0*DL1).AND.FV.LT.(ZMIN+(21.0D0*DL1))) SSYM='F'
      IF(FV.GE.ZMIN+(21.0D0*DL1).AND.FV.LT.(ZMIN+(22.0D0*DL1))) SSYM='E'
      IF(FV.GE.ZMIN+(22.0D0*DL1).AND.FV.LT.(ZMIN+(23.0D0*DL1))) SSYM='D'
      IF(FV.GE.ZMIN+(23.0D0*DL1).AND.FV.LT.(ZMIN+(24.0D0*DL1))) SSYM='C'
      IF(FV.GE.ZMIN+(24.0D0*DL1).AND.FV.LT.(ZMIN+(25.0D0*DL1))) SSYM='B'
      IF(FV.GE.ZMIN+(25.0D0*DL1).AND.FV.LT.(ZMIN+(26.0D0*DL1))) SSYM='A'
      IF(FV.GE.ZMIN+(26.0D0*DL1).AND.FV.LT.(ZMIN+(27.0D0*DL1))) SSYM='9'
      IF(FV.GE.ZMIN+(27.0D0*DL1).AND.FV.LT.(ZMIN+(28.0D0*DL1))) SSYM='8'
      IF(FV.GE.ZMIN+(28.0D0*DL1).AND.FV.LT.(ZMIN+(29.0D0*DL1))) SSYM='7'
      IF(FV.GE.ZMIN+(29.0D0*DL1).AND.FV.LT.(ZMIN+(30.0D0*DL1))) SSYM='6'
      IF(FV.GE.ZMIN+(30.0D0*DL1).AND.FV.LT.(ZMIN+(31.0D0*DL1))) SSYM='5'
      IF(FV.GE.ZMIN+(31.0D0*DL1).AND.FV.LT.(ZMIN+(32.0D0*DL1))) SSYM='4'
      IF(FV.GE.ZMIN+(32.0D0*DL1).AND.FV.LT.(ZMIN+(33.0D0*DL1))) SSYM='3'
      IF(FV.GE.ZMIN+(33.0D0*DL1).AND.FV.LT.(ZMIN+(34.0D0*DL1))) SSYM='2'
      IF(FV.GE.ZMIN+(34.0D0*DL1).AND.FV.LT.(ZMIN+(35.0D0*DL1))) SSYM='1'
      IF(DSPOT(12).EQ.0.0D0) SSYM='0'
      AV(I)(J:J)=SSYM
105   CONTINUE
   END DO
   IIVAL=I
!     NOW DISPLAY THE MAP
   IF(IIVAL.GT.64) THEN
      IF(OUT.NE.6) THEN
         DO II=1,IIVAL
            WRITE(OUTLYNE,*) AV(II)(1:IIVAL)
            CALL SHOWIT(0)
         END DO
         GO TO 202
      ELSE
         DO II=1,IIVAL
            WRITE(OUTLYNE,*) AV(II)(1:64)
            CALL SHOWIT(0)
         END DO
         DO II=1,IIVAL
            WRITE(OUTLYNE,*) AV(II)(65:IIVAL)
            CALL SHOWIT(0)
         END DO
         GO TO 202
      END IF
   ELSE
!             IIVAL LE 64
      DO II=1,IIVAL
         WRITE(OUTLYNE,*) AV(II)(1:IIVAL)
         CALL SHOWIT(0)
      END DO
   END IF
202 CONTINUE
   WRITE(OUTLYNE,*)&
   &'35 LEVELS FROM "Z" (MINIMUM) TO "1" (MAXIMUM)'
   CALL SHOWIT(0)
   WRITE(OUTLYNE,*)&
   &'EACH LEVEL REPRESENTS OPD RANGE OF ',DL1, ' WAVES'
   CALL SHOWIT(0)
   IF(DL1.NE.0.0D0) THEN
      WRITE(OUTLYNE,*)&
      &'"1" = ',ZMAX-(0.0D0*DL1),' TO ',ZMAX-(1.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"2" = ',ZMAX-(1.0D0*DL1),' TO ',ZMAX-(2.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"3" = ',ZMAX-(2.0D0*DL1),' TO ',ZMAX-(3.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"4" = ',ZMAX-(3.0D0*DL1),' TO ',ZMAX-(4.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"5" = ',ZMAX-(4.0D0*DL1),' TO ',ZMAX-(5.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"6" = ',ZMAX-(5.0D0*DL1),' TO ',ZMAX-(6.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"7" = ',ZMAX-(6.0D0*DL1),' TO ',ZMAX-(7.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"8" = ',ZMAX-(7.0D0*DL1),' TO ',ZMAX-(8.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"9" = ',ZMAX-(8.0D0*DL1),' TO ',ZMAX-(9.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"A" = ',ZMAX-(9.0D0*DL1),' TO ',ZMAX-(10.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"B" = ',ZMAX-(10.0D0*DL1),' TO ',ZMAX-(11.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"C" = ',ZMAX-(11.0D0*DL1),' TO ',ZMAX-(12.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"D" = ',ZMAX-(12.0D0*DL1),' TO ',ZMAX-(13.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"E" = ',ZMAX-(13.0D0*DL1),' TO ',ZMAX-(14.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"F" = ',ZMAX-(14.0D0*DL1),' TO ',ZMAX-(15.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"G" = ',ZMAX-(15.0D0*DL1),' TO ',ZMAX-(16.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"H" = ',ZMAX-(16.0D0*DL1),' TO ',ZMAX-(17.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"I" = ',ZMAX-(17.0D0*DL1),' TO ',ZMAX-(18.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"J" = ',ZMAX-(18.0D0*DL1),' TO ',ZMAX-(19.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"K" = ',ZMAX-(19.0D0*DL1),' TO ',ZMAX-(20.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"L" = ',ZMAX-(20.0D0*DL1),' TO ',ZMAX-(21.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"M" = ',ZMAX-(21.0D0*DL1),' TO ',ZMAX-(22.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"N" = ',ZMAX-(22.0D0*DL1),' TO ',ZMAX-(23.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"O" = ',ZMAX-(23.0D0*DL1),' TO ',ZMAX-(24.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"P" = ',ZMAX-(24.0D0*DL1),' TO ',ZMAX-(25.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"Q" = ',ZMAX-(25.0D0*DL1),' TO ',ZMAX-(26.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"R" = ',ZMAX-(26.0D0*DL1),' TO ',ZMAX-(27.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"S" = ',ZMAX-(27.0D0*DL1),' TO ',ZMAX-(28.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"T" = ',ZMAX-(28.0D0*DL1),' TO ',ZMAX-(29.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"U" = ',ZMAX-(29.0D0*DL1),' TO ',ZMAX-(30.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"V" = ',ZMAX-(30.0D0*DL1),' TO ',ZMAX-(31.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"W" = ',ZMAX-(31.0D0*DL1),' TO ',ZMAX-(32.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"X" = ',ZMAX-(32.0D0*DL1),' TO ',ZMAX-(33.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"Y" = ',ZMAX-(33.0D0*DL1),' TO ',ZMAX-(34.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"Z" = ',ZMAX-(34.0D0*DL1),' TO ',ZMAX-(35.0D0*DL1),' WAVES'
      CALL SHOWIT(0)
!
      WRITE(OUTLYNE,*)'UPPER LEFT HAND CORNER OF MAP IS -X, -Y'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)'LOWER RIGHT HAND CORNER OF MAP IS +X, +Y'
      CALL SHOWIT(0)
      RETURN
   END IF
END
! SUB APPLOT.FOR
SUBROUTINE APPLOT(KVAL,REFHT,WVAL,KKV,F,X,Y,KKK)
!     KVAL IS THE FIRST RECORD OF THE SPOT FILE TO READ
!     REFHT IS THE NORMALIZING AP HT.
!     WVAL IS THE DESIRED WAVELENGTH NUMBER
!     KKV IS THE TOTAL NUMBER OF POINTS TO BE READ IN FROM DSPOTT
!
   use DATSP1
   use DATLEN
   use DATMAI
   IMPLICIT NONE
!
   INTEGER KVAL,K,I,J,NNX,NNY,KK,KKK,IQ,KKV,II,IIVAL
!
   CHARACTER AV(1:129)*129,SSYM*1
!
   REAL*8 F,X,Y,DL1,FV &
   &,REFHT,XMIN,YMIN,ZMIN,XMAX,YMAX,ZMAX,WVAL
!
   DIMENSION F(KKK,KKK),X(KKK),Y(KKK)
!
!
   XMAX=-1.0E10
   YMAX=-1.0E10
   ZMAX=-1.0E10
   XMIN=1.0E10
   YMIN=1.0E10
   ZMIN=1.0E10
   AV(1:129)=' '
   FV=0.0D0
!
!     OPEN APMAP.DAT FOR OUTPUT
!
   OPEN(UNIT=72,ACCESS='SEQUENTIAL',BLANK='NULL'&
   &,FORM='FORMATTED',FILE='APMAP.DAT'&
   &,STATUS='UNKNOWN')
!
   I=1
   J=0
   DO IQ=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=IQ-1
      CALL SPOTIT(4)
!
      IF(DSPOT(16).NE.WVAL) THEN
         GO TO 101
      END IF
!
      J=J+1
      IF(J.GT.KKK) THEN
         J=1
         I=I+1
      END IF
      F(J,I)=DSPOT(12)
1000  FORMAT(D14.6,1X,D14.6,1X,D14.6,1X,D14.6)
!     WRITE X AND Y RAY COORD AT REF SURFACE AND VALUE AND REFHT
      WRITE(72,1000) DSPOT(5),DSPOT(6),F(J,I),REFHT
!     INCLUDE IT IN SEARCH FOR ZMAX AND ZMIN
      IF(F(J,I).GE.ZMAX) ZMAX=F(J,I)
      IF(F(J,I).LE.ZMIN) ZMIN=F(J,I)
101   CONTINUE
   END DO
   IF(ZMAX.EQ.-1.0D10) ZMAX=1.0D0
   IF(ZMIN.EQ.1.0D10) ZMIN=0.0D0
   J=0
   I=1
   DO IQ=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=IQ-1
      CALL SPOTIT(4)
!
      IF(DSPOT(16).NE.WVAL) THEN
         GO TO 1100
      END IF
!
      J=J+1
      IF(J.GT.KKK) THEN
         J=1
         I=I+1
      END IF
      X(J)=DSPOT(5)/REFHT
      Y(J)=DSPOT(6)/REFHT
      IF(X(J).GE.XMAX) XMAX=X(J)
      IF(X(J).LE.XMIN) XMIN=X(J)
      IF(Y(J).GE.YMAX) YMAX=Y(J)
      IF(Y(J).LE.YMIN) YMIN=Y(J)
1100  CONTINUE
   END DO
100 CONTINUE
!     NOW DISPLAY THE APMAP IN A TEXT FORM USING
!     1 THROUGH 9 AND A THROUGH Z TO REPRESENT 35 LEVELS FROM ZMIN
!     TO ZMAX. THE 0 IS RESERVED FOR VALUES WHICH ARE EXACTLY ZERO
!     WHICH MEANS NO SYSTEM THROUGHPUT.
   DL1=DABS((ZMAX-ZMIN)/35.0D0)
!     Z REPRESENTS VALUES FROM ZMIN TO ZMIN+DL1
!     Y REPRESENTS VALUES FROM (ZMIN+DL1) TO
!         (ZMIN+(2.0D0*DL1)
!     ETC TILL
!     1 REPRESENTS ZMAX-DL1 TO ZMAX
!
   J=0
   I=1
!     READ DSPOTT
   DO IQ=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=IQ-1
      CALL SPOTIT(4)
!
      IF(DSPOT(16).NE.WVAL) THEN
         GO TO 105
      END IF
!
      J=J+1
      IF(J.GT.KKK) THEN
         J=1
         I=I+1
      END IF
      FV=DSPOT(12)
      IF(FV.LT.(ZMIN+DL1)) SSYM='Z'
      IF(FV.GE.ZMIN+(1.0D0*DL1).AND.FV.LT.(ZMIN+(2.0D0*DL1))) SSYM='Y'
      IF(FV.GE.ZMIN+(2.0D0*DL1).AND.FV.LT.(ZMIN+(3.0D0*DL1))) SSYM='X'
      IF(FV.GE.ZMIN+(3.0D0*DL1).AND.FV.LT.(ZMIN+(4.0D0*DL1))) SSYM='W'
      IF(FV.GE.ZMIN+(4.0D0*DL1).AND.FV.LT.(ZMIN+(5.0D0*DL1))) SSYM='V'
      IF(FV.GE.ZMIN+(5.0D0*DL1).AND.FV.LT.(ZMIN+(6.0D0*DL1))) SSYM='U'
      IF(FV.GE.ZMIN+(6.0D0*DL1).AND.FV.LT.(ZMIN+(7.0D0*DL1))) SSYM='T'
      IF(FV.GE.ZMIN+(7.0D0*DL1).AND.FV.LT.(ZMIN+(8.0D0*DL1))) SSYM='S'
      IF(FV.GE.ZMIN+(8.0D0*DL1).AND.FV.LT.(ZMIN+(9.0D0*DL1))) SSYM='R'
      IF(FV.GE.ZMIN+(9.0D0*DL1).AND.FV.LT.(ZMIN+(10.0D0*DL1))) SSYM='Q'
      IF(FV.GE.ZMIN+(10.0D0*DL1).AND.FV.LT.(ZMIN+(11.0D0*DL1))) SSYM='P'
      IF(FV.GE.ZMIN+(11.0D0*DL1).AND.FV.LT.(ZMIN+(12.0D0*DL1))) SSYM='O'
      IF(FV.GE.ZMIN+(12.0D0*DL1).AND.FV.LT.(ZMIN+(13.0D0*DL1))) SSYM='N'
      IF(FV.GE.ZMIN+(13.0D0*DL1).AND.FV.LT.(ZMIN+(14.0D0*DL1))) SSYM='M'
      IF(FV.GE.ZMIN+(14.0D0*DL1).AND.FV.LT.(ZMIN+(15.0D0*DL1))) SSYM='L'
      IF(FV.GE.ZMIN+(15.0D0*DL1).AND.FV.LT.(ZMIN+(16.0D0*DL1))) SSYM='K'
      IF(FV.GE.ZMIN+(16.0D0*DL1).AND.FV.LT.(ZMIN+(17.0D0*DL1))) SSYM='J'
      IF(FV.GE.ZMIN+(17.0D0*DL1).AND.FV.LT.(ZMIN+(18.0D0*DL1))) SSYM='I'
      IF(FV.GE.ZMIN+(18.0D0*DL1).AND.FV.LT.(ZMIN+(19.0D0*DL1))) SSYM='H'
      IF(FV.GE.ZMIN+(19.0D0*DL1).AND.FV.LT.(ZMIN+(20.0D0*DL1))) SSYM='G'
      IF(FV.GE.ZMIN+(20.0D0*DL1).AND.FV.LT.(ZMIN+(21.0D0*DL1))) SSYM='F'
      IF(FV.GE.ZMIN+(21.0D0*DL1).AND.FV.LT.(ZMIN+(22.0D0*DL1))) SSYM='E'
      IF(FV.GE.ZMIN+(22.0D0*DL1).AND.FV.LT.(ZMIN+(23.0D0*DL1))) SSYM='D'
      IF(FV.GE.ZMIN+(23.0D0*DL1).AND.FV.LT.(ZMIN+(24.0D0*DL1))) SSYM='C'
      IF(FV.GE.ZMIN+(24.0D0*DL1).AND.FV.LT.(ZMIN+(25.0D0*DL1))) SSYM='B'
      IF(FV.GE.ZMIN+(25.0D0*DL1).AND.FV.LT.(ZMIN+(26.0D0*DL1))) SSYM='A'
      IF(FV.GE.ZMIN+(26.0D0*DL1).AND.FV.LT.(ZMIN+(27.0D0*DL1))) SSYM='9'
      IF(FV.GE.ZMIN+(27.0D0*DL1).AND.FV.LT.(ZMIN+(28.0D0*DL1))) SSYM='8'
      IF(FV.GE.ZMIN+(28.0D0*DL1).AND.FV.LT.(ZMIN+(29.0D0*DL1))) SSYM='7'
      IF(FV.GE.ZMIN+(29.0D0*DL1).AND.FV.LT.(ZMIN+(30.0D0*DL1))) SSYM='6'
      IF(FV.GE.ZMIN+(30.0D0*DL1).AND.FV.LT.(ZMIN+(31.0D0*DL1))) SSYM='5'
      IF(FV.GE.ZMIN+(31.0D0*DL1).AND.FV.LT.(ZMIN+(32.0D0*DL1))) SSYM='4'
      IF(FV.GE.ZMIN+(32.0D0*DL1).AND.FV.LT.(ZMIN+(33.0D0*DL1))) SSYM='3'
      IF(FV.GE.ZMIN+(33.0D0*DL1).AND.FV.LT.(ZMIN+(34.0D0*DL1))) SSYM='2'
      IF(FV.GE.ZMIN+(34.0D0*DL1)) SSYM='1'
      IF(DSPOT(12).EQ.0.0D0) SSYM='0'
      AV(I)(J:J)=SSYM
105   CONTINUE
   END DO
   IIVAL=I
!     NOW DISPLAY THE MAP
   IF(IIVAL.GT.64) THEN
      IF(OUT.NE.6) THEN
         DO II=1,IIVAL
            WRITE(OUTLYNE,*) AV(II)(1:IIVAL)
            CALL SHOWIT(0)
         END DO
         GO TO 202
      ELSE
         DO II=1,IIVAL
            WRITE(OUTLYNE,*) AV(II)(1:64)
            CALL SHOWIT(0)
         END DO
         DO II=1,IIVAL
            WRITE(OUTLYNE,*) AV(II)(65:IIVAL)
            CALL SHOWIT(0)
         END DO
         GO TO 202
      END IF
   ELSE
!             IIVAL LE 64
      DO II=1,IIVAL
         WRITE(OUTLYNE,*) AV(II)(1:IIVAL)
         CALL SHOWIT(0)
      END DO
   END IF
202 CONTINUE
   WRITE(OUTLYNE,*)&
   &'35 LEVELS FROM "Z" (MINIMUM) TO "1" (MAXIMUM)'
   CALL SHOWIT(0)
   WRITE(OUTLYNE,*)'EACH LEVEL REPRESENTS RANGE OF ',DL1
   CALL SHOWIT(0)
   IF(DL1.NE.0.0D0) THEN
      WRITE(OUTLYNE,*)&
      &'"1" = ',ZMAX-(0.0D0*DL1),' TO ',ZMAX-(1.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"2" = ',ZMAX-(1.0D0*DL1),' TO ',ZMAX-(2.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"3" = ',ZMAX-(2.0D0*DL1),' TO ',ZMAX-(3.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"4" = ',ZMAX-(3.0D0*DL1),' TO ',ZMAX-(4.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"5" = ',ZMAX-(4.0D0*DL1),' TO ',ZMAX-(5.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"6" = ',ZMAX-(5.0D0*DL1),' TO ',ZMAX-(6.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"7" = ',ZMAX-(6.0D0*DL1),' TO ',ZMAX-(7.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"8" = ',ZMAX-(7.0D0*DL1),' TO ',ZMAX-(8.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"9" = ',ZMAX-(8.0D0*DL1),' TO ',ZMAX-(9.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"A" = ',ZMAX-(9.0D0*DL1),' TO ',ZMAX-(10.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"B" = ',ZMAX-(10.0D0*DL1),' TO ',ZMAX-(11.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"C" = ',ZMAX-(11.0D0*DL1),' TO ',ZMAX-(12.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"D" = ',ZMAX-(12.0D0*DL1),' TO ',ZMAX-(13.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"E" = ',ZMAX-(13.0D0*DL1),' TO ',ZMAX-(14.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"F" = ',ZMAX-(14.0D0*DL1),' TO ',ZMAX-(15.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"G" = ',ZMAX-(15.0D0*DL1),' TO ',ZMAX-(16.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"H" = ',ZMAX-(16.0D0*DL1),' TO ',ZMAX-(17.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"I" = ',ZMAX-(17.0D0*DL1),' TO ',ZMAX-(18.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"J" = ',ZMAX-(18.0D0*DL1),' TO ',ZMAX-(19.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"K" = ',ZMAX-(19.0D0*DL1),' TO ',ZMAX-(20.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"L" = ',ZMAX-(20.0D0*DL1),' TO ',ZMAX-(21.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"M" = ',ZMAX-(21.0D0*DL1),' TO ',ZMAX-(22.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"N" = ',ZMAX-(22.0D0*DL1),' TO ',ZMAX-(23.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"O" = ',ZMAX-(23.0D0*DL1),' TO ',ZMAX-(24.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"P" = ',ZMAX-(24.0D0*DL1),' TO ',ZMAX-(25.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"Q" = ',ZMAX-(25.0D0*DL1),' TO ',ZMAX-(26.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"R" = ',ZMAX-(26.0D0*DL1),' TO ',ZMAX-(27.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"S" = ',ZMAX-(27.0D0*DL1),' TO ',ZMAX-(28.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"T" = ',ZMAX-(28.0D0*DL1),' TO ',ZMAX-(29.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"U" = ',ZMAX-(29.0D0*DL1),' TO ',ZMAX-(30.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"V" = ',ZMAX-(30.0D0*DL1),' TO ',ZMAX-(31.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"W" = ',ZMAX-(31.0D0*DL1),' TO ',ZMAX-(32.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"X" = ',ZMAX-(32.0D0*DL1),' TO ',ZMAX-(33.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"Y" = ',ZMAX-(33.0D0*DL1),' TO ',ZMAX-(34.0D0*DL1)
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)&
      &'"Z" = ',ZMAX-(34.0D0*DL1),' TO ',ZMAX-(35.0D0*DL1)
      CALL SHOWIT(0)
!
      WRITE(OUTLYNE,*)'UPPER LEFT HAND CORNER OF MAP IS -X, -Y'
      CALL SHOWIT(0)
      WRITE(OUTLYNE,*)'LOWER RIGHT HAND CORNER OF MAP IS +X, +Y'
      CALL SHOWIT(0)
      RETURN
   END IF
END
! SUB OPDLOD.FOR
SUBROUTINE OPDLOD
   use zoa_file_handler
   use global_widgets, only: curr_opd
!
   use DATSP1
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_clap_type, surf_clap_dim, surf_array_parity
   use mod_system, only: sys_wl_ref
   IMPLICIT NONE
!
   EXTERNAL FF3
!
   INTEGER SSN,SM,NP2,MP,COUNT,I,J,N,M,II,IIP, OPDCNT
   INTEGER IWIW,NUMTOT,IW
   COMMON/IWIWIW/IWIW,NUMTOT,IW
!
   LOGICAL OPMAP,OPEN64
!
   COMMON/OPOPMP/OPMAP
!
   COMMON/PRSIZE/COUNT
!
!       THIS PASSES THE SOLUTION OF THE LEAST SQUARES PROBLEM
   COMMON/SOLU/X
!
   REAL*8 ACCUM(1:96,1:96),REFHT,&
   &CCOL(1:96),&
   &X(1:96)
!
   COMMON/ACDATA/ACCUM,CCOL
!
   INTEGER III,JJ,KK,ALLOERR
   integer :: rec64
!
   REAL*8 DWW1,DWW2,DWW3,DWW4,&
   &TERM,FF3,RHO,THETA
!
!
   REAL*8 W,V,U,&
   &B,XXX
!
   DIMENSION W(:),V(:,:),U(:,:),&
   &B(:),XXX(:)
!
   ALLOCATABLE :: W,V,U,B,XXX
   ALLOCATE (W(1:96),V(1:96,1:96),U(1:96,1:96),B(1:96),XXX(1:96)&
   &,STAT=ALLOERR)
!
!       DWW1=REF SURF Y-COORDINATE
!       DWW2=REF SURF X-COORDINATE
!       DWW3=OPD VALUE
!       DWW4=INTENSITY VALUE
!
   IF(SQ.EQ.1.OR.SST.EQ.1) THEN
      OUTLYNE=&
      &'"FITZERN" TAKES NO QUALIFIER OR ALPHANUMERIC INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      DEALLOCATE(U,W,V,XXX,B,STAT=ALLOERR)
      RETURN
   END IF
!
!
   IF(S3.EQ.1.OR.S2.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      OUTLYNE=&
      &'"FITZERN" ONLY TAKES NUMERIC WORD #1 INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      DEALLOCATE(U,W,V,XXX,B,STAT=ALLOERR)
      RETURN
   END IF
!
!     DEFAULT WAVELENGTH IS CONTROL WAVELENGTH
   IF(DF1.EQ.1) W1=sys_wl_ref()
   IF(INT(W1).LT.1.OR.INT(W1).GT.10) THEN
      OUTLYNE=&
      &'NUMERIC WORD #1 MUST BE 1, 2, 3, 4, 5, 6, 7, 8, 9 OR 10'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      DEALLOCATE(U,W,V,XXX,B,STAT=ALLOERR)
      RETURN
   END IF
   IF(.NOT.CPFNEXT) THEN
      OUTLYNE=&
      &'NO CAPFN EXISTS'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      DEALLOCATE(U,W,V,XXX,B,STAT=ALLOERR)
      RETURN
   END IF
   OUTLYNE=&
   &'FITTING THE WAVEFRONT TO A 37 TERM FRINGE ZERNIKE'
   CALL SHOWIT(1)
   CCOL(1:96)=0.0D0
   CFTYPE(1:96)=0.0D0
   X(1:96)=0.0D0
   XXX(1:96)=0.0D0
   ACCUM(1:96,1:96)=0.0D0
!
!     DETERMINE THE REFERNCE APERTURE HEIGHT
!     OF THE REF SURFACE COORDINATES
   IF(surf_clap_type(NEWREF) >= 1.AND.surf_clap_type(NEWREF) <= 5.AND.surf_array_parity(NEWREF) == 0) THEN
      IF(surf_clap_type(NEWREF) == 1) THEN
         IF(surf_clap_dim(NEWREF, 1).LE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RECT CLAP
!
      IF(surf_clap_type(NEWREF) == 2) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        ELIP CLAP
!
      IF(surf_clap_type(NEWREF) == 3) THEN
         IF(surf_clap_dim(NEWREF, 1).GE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RCTK CLAP
!
      IF(surf_clap_type(NEWREF) == 4) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        POLY CLAP
!
      IF(surf_clap_type(NEWREF) == 5) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 1))
      END IF
!        IPOLY CLAP
!
      IF(surf_clap_type(NEWREF) == 6) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 5))
      END IF
!
   ELSE
!       NO CLAP ON REF SURF.
      IF(PXTRAY(1,NEWREF).GE.PXTRAX(1,NEWREF)) THEN
         REFHT=PXTRAY(1,NEWREF)
      ELSE
         REFHT=PXTRAX(1,NEWREF)
      END IF
   END IF
!
   !      OPEN(UNIT=64,ACCESS='DIRECT',FILE=LIBSPO//'OPDDAT.DAT',
   !   1  FORM='UNFORMATTED',RECL=(10*NRECL),STATUS='UNKNOWN')
   !    CALL CLOSE_FILE(64,0)
   call clear_file(trim(LIBSPO)//'OPDDAT.DAT')
   inquire(iolength=rec64) DWW1,DWW2,DWW3,DWW4
!
!     OPEN OPDDAT.DAT
!
   OPEN(UNIT=64,ACCESS='DIRECT',FILE=trim(LIBSPO)//'OPDDAT.DAT',&
   &FORM='UNFORMATTED',RECL=rec64,STATUS='UNKNOWN')
   KK=1
   PRINT *, "ITOT is ", ITOT
   DO IIP=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=IIP-1
      CALL SPOTIT(4)
!
      IF(DSPOT(16).EQ.W1.AND.DSPOT(12).NE.0.0D0.OR.&
      &DSPOT(16).EQ.W1.AND.DSPOT(12).EQ.0.0D0.AND.&
      &DSPOT(7).EQ.7.0D0) KK=KK+1
   END DO
   IF(KK.LT.37.0D0) THEN
!     NOT ENOUGH DATA FOR A FIT
      OUTLYNE=&
      &'NOT ENOUGH DATA POINTS EXIST FOR A RELIABLE FIT'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'OR NO DATA WAS AVAILABLE AT THE SPECIFIED WAVELENGTH'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'TRY TRACING A DENSER GRID OF RAYS'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      DEALLOCATE(U,W,V,XXX,B,STAT=ALLOERR)
      RETURN
   END IF
!
   KK=1
   if (allocated(curr_opd%X)) then
      deallocate(curr_opd%X)
      deallocate(curr_opd%Y)
      deallocate(curr_opd%Z)


   end if
   allocate(curr_opd%X(IWIW))
   allocate(curr_opd%Y(IWIW))
   allocate(curr_opd%Z(IWIW))
   curr_opd%numPts = IWIW
   curr_opd%numx = INT(sqrt(real(curr_opd%numPts)))
   curr_opd%numy = INT(sqrt(real(curr_opd%numPts)))

   PRINT *, "OPDLOD numPts is ", curr_opd%numPts
   PRINT *, "IWIW is ", IWIW



   DO IIP=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=IIP-1
      CALL SPOTIT(4)

!


!
      IF(DSPOT(16).EQ.W1) THEN
         !PRINT *, "W1 for ID ", KK
         DWW1=DSPOT(6)/REFHT
         DWW2=DSPOT(5)/REFHT
         DWW3=DSPOT(4)/(TWOPII)
         DWW4=DSPOT(12)

         curr_opd%X(KK) = DWW1
         curr_opd%Y(KK) = DWW2
         curr_opd%Z(KK) = DWW3

!
!     DATA FOR DESIRED WAVELENGTH, PROCEED
!
!       PROCEED WITH FITTING A TYPE 3 TYPE/SURFACE
         RHO=DSQRT((DWW1**2)+(DWW2**2))
         IF(DABS(DWW1).GE.DABS(((1.0D35)*DWW2))) THEN
            IF(DWW1.GE.0.0D0) THETA=PII/2.0D0
            IF(DWW1.LT.0.0D0) THETA=(3.0D0*PII)/2.0D0
         ELSE
            IF(DABS(DWW1).EQ.0.0D0.AND.DABS(DWW2).EQ.0.0D0) THEN
               THETA=0.0D0
            ELSE
               THETA=DATAN2(DWW1,DWW2)
            END IF
            IF(THETA.LT.0.0D0) THETA=THETA+(TWOPII)
         END IF
!
         III=0
         DO I=1,37
!       FILL THE COLLUMN ARRAY
            III=III+1
!       CALCULATE COLUMN VECTOR
!       FUNCTION FF3 RETURNS THE CORRECT VALUE
!       FOR THE ITH ENTRY IN THE COLUMN VECTOR
!       WITHOUT THE GIVEN DEPENDENT VARIABLE VALUE
!       OF THE WEIGHT FUNCTION FACTORED IN. THIS IS
!       FOR THE STANDARD ZERNIKE. I RANGES FROM 1 TO 37
            TERM= FF3(RHO,THETA,I)
            TERM=TERM*DWW3*DWW4
            CCOL(III)=CCOL(III)+TERM
            JJ=0
            DO J=1,37
!       DO THE APPROPRIATE ROW FOR COLUMN I
               JJ=JJ+1
               TERM= FF3(RHO,THETA,I)*FF3(RHO,THETA,J)
               ACCUM(III,JJ)=ACCUM(III,JJ)+(DWW4*TERM)
            END DO
         END DO
         COUNT=III
!
!       ALL VALUES CALCULATED FOR THE CURRENT "DATA"
!       STATEMENT.
!
         KK=KK+1
         WRITE(UNIT=64,REC=KK) DWW1,DWW2,DWW3,DWW4
      END IF
   END DO
!     KK IS THE NUMBER OF FITTED DATA ITEMS
   WRITE(UNIT=64,REC=1) KK
!
!       THE LARGE ARRAY WITH ACCUMULATED DATA IS
!       ACCUM. THE COLUMN VECTOR WITH FUNCTIONAL DATA
!       IS CCOL.
   MP=96
   NP2=96
   N=COUNT
   M=COUNT
   I=COUNT
   B(1:I)=CCOL(1:I)
   J=COUNT
   U(1:I,1:J)=ACCUM(1:I,1:J)
!       DO SINGULAR VALUE DECOMPOSITION
!
   SM=M
   SSN=N
   CALL SVDCMP(U,SM,SSN,MP,NP2,W,V)
   M=SM
   N=SSN
!
!       SOLVE LINEAR EQUATION
!
   SM=M
   SSN=N
   CALL SVBKSB(U,W,V,SM,SSN,MP,NP2,B,XXX)
   M=SM
   N=SSN
!
!       SIMPLE DATA FIT
   II=0
   DO I=1,37
      II=II+1
      CFTYPE(I)=XXX(II)
      X(I)=CFTYPE(I)
   END DO
   DO I=38,96
      II=II+1
      CFTYPE(I)=0.0D0
      X(I)=CFTYPE(I)
   END DO
   OPMAP=.TRUE.
   OUTLYNE=&
   &'FITTING COMPLETED'
   CALL SHOWIT(1)
   DEALLOCATE(U,W,V,XXX,B,STAT=ALLOERR)
   RETURN
END
! SUB WAVESLP1.FOR
SUBROUTINE WAVESLP1(DSPOTT,IITOT,JTYPE)
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_clap_type, surf_clap_dim, surf_array_parity
   use mod_system, only: sys_units, sys_wavelength, sys_wl_weight
   IMPLICIT NONE
!
   EXTERNAL FF3
!
   INTEGER SSN,SM,NP2,MP,JTYPE,IITOT,COUNT,I,J,N,M,II,IIP,IWK,JJJ &
   &,ISS
!
   COMMON/PRSIZE/COUNT
!
!       THIS PASSES THE SOLUTION OF THE LEAST SQUARES PROBLEM
   COMMON/SOLU/X
   LOGICAL ERRR
!
   DOUBLE PRECISION ACCUM(1:96,1:96),REFHT,WW,TERM1,TERM2,&
   &WAVEX,CCOL(1:96),DSPOTT(35,IITOT),X(1:96),SUML2,SUML4,WEIS &
   &,DENOM,DZ1,DZ2,SS1,SS2,VALL,VALX,VALY,WEI(1:10),LAM(1:10)&
   &,PHI,PHIX,PHIY,SSS,COSX,COSY,SINX,SINY,SSSO,DLLZX,DLLZY,DLLZ0 &
   &,PHIO,NRR,ORR,TERM3
!
   COMMON/ACDATA/ACCUM,CCOL
!
   INTEGER III,JJ,ALLOERR
!
   DOUBLE PRECISION DWW1,DWW2,DWW3,DWW4,&
   &TERM,FF3,RHO,THETA
!
!
   DOUBLE PRECISION W,V,U,&
   &B,XXX,WV
!
   DIMENSION W(:),V(:,:),U(:,:),&
   &B(:),XXX(:)
!
   ALLOCATABLE :: W,V,U,B,XXX
   DEALLOCATE (W,V,U,B,XXX &
   &,STAT=ALLOERR)
   ALLOCATE (W(1:96),V(1:96,1:96),U(1:96,1:96),B(1:96),XXX(1:96)&
   &,STAT=ALLOERR)
!
!       DWW1=REF SURF Y-COORDINATE
!       DWW2=REF SURF X-COORDINATE
!       DWW3=OPD VALUE
!       DWW4=INTENSITY VALUE
!
   WAVEX=0.0D0
   DLLX=0.0D0
   DLLY=0.0D0
   DLLZ=0.0D0
   CCOL(1:96)=0.0D0
   CFTYPE(1:96)=0.0D0
   X(1:96)=0.0D0
   XXX(1:96)=0.0D0
   ACCUM(1:96,1:96)=0.0D0
!
!     DETERMINE THE REFERNCE APERTURE HEIGHT
!     OF THE REF SURFACE COORDINATES
   IF(surf_clap_type(NEWREF) >= 1.AND.surf_clap_type(NEWREF) <= 5.AND.surf_array_parity(NEWREF) == 0) THEN
      IF(surf_clap_type(NEWREF) == 1) THEN
         IF(surf_clap_dim(NEWREF, 1).LE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RECT CLAP
!
      IF(surf_clap_type(NEWREF) == 2) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        ELIP CLAP
!
      IF(surf_clap_type(NEWREF) == 3) THEN
         IF(surf_clap_dim(NEWREF, 1).GE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RCTK CLAP
!
      IF(surf_clap_type(NEWREF) == 4) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        POLY CLAP
!
      IF(surf_clap_type(NEWREF) == 5) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 1))
      END IF
!        IPOLY CLAP
!
      IF(surf_clap_type(NEWREF) == 6) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 5))
      END IF
!
   ELSE
!       NO CLAP ON REF SURF.
      IF(PXTRAY(1,NEWREF).GE.PXTRAX(1,NEWREF)) THEN
         REFHT=PXTRAY(1,NEWREF)
      ELSE
         REFHT=PXTRAX(1,NEWREF)
      END IF
   END IF
!
!     COMPUTE THE EFFECTIVE WAVELENGTH
   SUML2=0.0D0
   SUML4=0.0D0
   LAMAVE=0.0D0
   WEI(1)=sys_wl_weight(1)
   WEI(2)=sys_wl_weight(2)
   WEI(3)=sys_wl_weight(3)
   WEI(4)=sys_wl_weight(4)
   WEI(5)=sys_wl_weight(5)
   WEI(6)=sys_wl_weight(6)
   WEI(7)=sys_wl_weight(7)
   WEI(8)=sys_wl_weight(8)
   WEI(9)=sys_wl_weight(9)
   WEI(10)=sys_wl_weight(10)
   LAM(1)=sys_wavelength(1)
   LAM(2)=sys_wavelength(2)
   LAM(3)=sys_wavelength(3)
   LAM(4)=sys_wavelength(4)
   LAM(5)=sys_wavelength(5)
   LAM(6)=sys_wavelength(6)
   LAM(7)=sys_wavelength(7)
   LAM(8)=sys_wavelength(8)
   LAM(9)=sys_wavelength(9)
   LAM(10)=sys_wavelength(10)
   WEIS=0.0D0
   DO ISS=1,10
      WEIS=WEIS+WEI(ISS)
   END DO
   IF(WEIS.EQ.0.0D0) WEIS=1.0D0
   DO ISS=1,10
      WEI(ISS)=WEI(ISS)/WEIS
   END DO
   DO ISS=1,10
      IF(LAM(ISS).NE.0.0D0.AND.WEI(ISS).NE.0.0D0) THEN
         SUML2=SUML2+(WEI(ISS)/(LAM(ISS)**2))
         SUML4=SUML4+(WEI(ISS)/(LAM(ISS)**4))
      END IF
   END DO
   LAMAVE=DSQRT(SUML2/SUML4)
   IF(sys_units().EQ.1.0D0) THEN
      LAMAVE=LAMAVE*3.93700787402D-5
   END IF
   IF(sys_units().EQ.2.0D0) THEN
      LAMAVE=LAMAVE*1.0D-4
   END IF
   IF(sys_units().EQ.3.0D0) THEN
      LAMAVE=LAMAVE*1.0D-3
   END IF
   IF(sys_units().EQ.4.0D0) THEN
      LAMAVE=LAMAVE*1.0D-6
   END IF
   DO IIP=1,IITOT
      WV=sys_wavelength(INT(DSPOTT(16,IIP)))
      IF(sys_units().EQ.1.0D0) THEN
         WV=WV*3.93700787402D-5
      END IF
      IF(sys_units().EQ.2.0D0) THEN
         WV=WV*1.0D-4
      END IF
      IF(sys_units().EQ.3.0D0) THEN
         WV=WV*1.0D-3
      END IF
      IF(sys_units().EQ.4.0D0) THEN
         WV=WV*1.0D-6
      END IF
      IF(DSPOTT(17,IIP).NE.0.0D0 &
      &.AND.DSPOTT(7,IIP).EQ.0.0D0.AND.DSPOTT(12,IIP).NE.0.0D0) THEN
         DWW1=DSPOTT(6,IIP)/REFHT
         DWW2=DSPOTT(5,IIP)/REFHT
         DWW3=((DSPOTT(33,IIP)/(TWOPII)))*WV
         DWW4=DSPOTT(12,IIP)
         WAVEX=1
!
!       PROCEED WITH FITTING A TYPE 3 TYPE/SURFACE
         RHO=DSQRT((DWW1**2)+(DWW2**2))
         IF(DABS(DWW1).GE.DABS(((1.0D35)*DWW2))) THEN
            IF(DWW1.GE.0.0D0) THETA=PII/2.0D0
            IF(DWW1.LT.0.0D0) THETA=(3.0D0*PII)/2.0D0
         ELSE
            IF(DABS(DWW1).EQ.0.0D0.AND.DABS(DWW2).EQ.0.0D0) THEN
               THETA=0.0D0
            ELSE
               THETA=DATAN2(DWW1,DWW2)
            END IF
            IF(THETA.LT.0.0D0) THETA=THETA+(TWOPII)
         END IF
!
         III=0
         DO I=1,4
!       FILL THE COLLUMN ARRAY
            III=III+1
!       CALCULATE COLUMN VECTOR
!       FUNCTION FF3 RETURNS THE CORRECT VALUE
!       FOR THE ITH ENTRY IN THE COLUMN VECTOR
!       WITHOUT THE GIVEN DEPENDENT VARIABLE VALUE
!       OF THE WEIGHT FUNCTION FACTORED IN. THIS IS
!       FOR THE STANDARD ZERNIKE. I RANGES FROM 1 TO 4
            TERM= FF3(RHO,THETA,I)
            TERM=TERM*DWW3*DWW4
            CCOL(III)=CCOL(III)+TERM
            JJ=0
            DO J=1,4
!       DO THE APPROPRIATE ROW FOR COLUMN I
               JJ=JJ+1
               TERM= FF3(RHO,THETA,I)*FF3(RHO,THETA,J)
               ACCUM(III,JJ)=ACCUM(III,JJ)+(DWW4*TERM)
            END DO
         END DO
         COUNT=III
!
!       ALL VALUES CALCULATED FOR THE CURRENT "DATA"
!       STATEMENT.
!                     ELSE
!     POINT DOSE NOT CONTRIBUTE THIS TIME
      END IF
   END DO
!       THE LARGE ARRAY WITH ACCUMULATED DATA IS
!       ACCUM. THE COLUMN VECTOR WITH FUNCTIONAL DATA
!       IS CCOL.
   MP=96
   NP2=96
   N=COUNT
   M=COUNT
   DO I=1,COUNT
      B(I)=CCOL(I)
      DO J=1,COUNT
         U(I,J)=ACCUM(I,J)
      END DO
   END DO
!       DO SINGULAR VALUE DECOMPOSITION
!
   SM=M
   SSN=N
   CALL SVDCMP(U,SM,SSN,MP,NP2,W,V)
   M=SM
   N=SSN
!
!       SOLVE LINEAR EQUATION
!
   SM=M
   SSN=N
   CALL SVBKSB(U,W,V,SM,SSN,MP,NP2,B,XXX)
   M=SM
   N=SSN
   II=0
   DO I=1,4
      II=II+1
      CFTYPE(I)=XXX(II)
      X(I)=CFTYPE(I)
   END DO
!     NOW COMPUTE THE TILTED PART AND SUBTRACT IT OFF
   DO IIP=1,IITOT
      WV=sys_wavelength(INT(DSPOTT(16,IIP)))
      IF(sys_units().EQ.1.0D0) THEN
         WV=WV*3.93700787402D-5
      END IF
      IF(sys_units().EQ.2.0D0) THEN
         WV=WV*1.0D-4
      END IF
      IF(sys_units().EQ.3.0D0) THEN
         WV=WV*1.0D-3
      END IF
      IF(sys_units().EQ.4.0D0) THEN
         WV=WV*1.0D-6
      END IF
      DWW1=DSPOTT(6,IIP)/REFHT
      DWW2=DSPOTT(5,IIP)/REFHT
      DWW3=((DSPOTT(33,IIP)/(TWOPII)))*WV
      DWW4=DSPOTT(12,IIP)
      RHO=DSQRT((DWW1**2)+(DWW2**2))
      IF(DABS(DWW1).GE.DABS(((1.0D35)*DWW2))) THEN
         IF(DWW1.GE.0.0D0) THETA=PII/2.0D0
         IF(DWW1.LT.0.0D0) THETA=(3.0D0*PII)/2.0D0
      ELSE
         IF(DABS(DWW1).EQ.0.0D0.AND.DABS(DWW2).EQ.0.0D0) THEN
            THETA=0.0D0
         ELSE
            THETA=DATAN2(DWW1,DWW2)
         END IF
         IF(THETA.LT.0.0D0) THETA=THETA+(TWOPII)
      END IF
      TERM=0.0D0
      IF(JTYPE.EQ.3) THEN
         TERM1=(X(2)*FF3(RHO,THETA,2))&
         &+(X(3)*FF3(RHO,THETA,3))
         TERM2=0.0D0
      END IF
      IF(JTYPE.EQ.4) THEN
         TERM1=(X(2)*FF3(RHO,THETA,2))&
         &+(X(3)*FF3(RHO,THETA,3))
         TERM2=(X(1)*FF3(RHO,THETA,1))&
         &+(X(4)*FF3(RHO,THETA,4))
      END IF
      TERM3=TERM1+TERM2
      DWW3=DWW3-TERM3
      IF(DSPOTT(12,IIP).NE.0.0D0)&
      &DSPOTT(4,IIP)=(DWW3*(TWOPII))/WV
      IF(DSPOTT(12,IIP).EQ.0.0D0) DSPOTT(4,IIP)=0.0D0
   END DO
   IF(WAVEX.EQ.1) THEN
      DLLX=((X(2)*FF3(1.0D0,0.0D0,2))&
      &-(X(2)*FF3(1.0D0,(PII),2)))
      DLLY=((X(3)*FF3(1.0D0,(PII/2.0D0),3))&
      &-(X(3)*FF3(1.0D0,(3.0D0*PII/2.0D0),3)))
      IF(JTYPE.EQ.3)  DLLZ=0.0D0
      IF(JTYPE.EQ.4)  DLLZ=((X(1)*FF3(1.0D0,0.0D0,1))&
      &+(X(4)*FF3(1.0D0,0.0D0,4)))
      ERRR=.FALSE.
      MSG=.FALSE.
      CALL EXPDIAX(VALL,ERRR)
      IF(.NOT.ERRR) VALX=VALL
      IF(ERRR) VALX=EXDIAX
      ERRR=.FALSE.
      MSG=.FALSE.
      CALL EXPDIAY(VALL,ERRR)
      IF(.NOT.ERRR) VALY=VALL
      IF(ERRR) VALY=EXDIAY
      DLLX=-((DLLX/(2.0D0*VALX))*RREF)*DCOS(REFRY(11,NEWIMG))
      DLLY=-((DLLY/(2.0D0*VALY))*RREF)*DCOS(REFRY(12,NEWIMG))
      DLLZX=(DLLZ*2.0D0)/(DSIN(DATAN(1.0D0/(2.0D0*RBFNY)))**2)
      DLLZY=(DLLZ*2.0D0)/(DSIN(DATAN(1.0D0/(2.0D0*RBFNX)))**2)
      DLLZ=(DLLZX+DLLZY)/2.0D0
   END IF
!
   DEALLOCATE(U,W,V,XXX,B,STAT=ALLOERR)
   RETURN
END
! SUB OPDLIS.FOR
SUBROUTINE OPDLIS
   use zoa_file_handler, only: isSPOFileOpen
!
   use DATSP1
   use DATLEN
   use DATMAI
   use mod_surface, only: surf_clap_type, surf_clap_dim, surf_array_parity
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE OPDLIS. THIS IS THE SUBROUTINE WHICH
!       HANDLES THE "OPDLIST" COMMAND FROM THE CMD LEVEL
   integer :: rec64
!
   EXTERNAL FF3
!
   INTEGER DATCNT,TYPE,COUNT,INUMBER,&
   &IDATA,I,II,III,IIII,IIIII
!
   LOGICAL OPMAP,OPEN64
!
   COMMON/OPOPMP/OPMAP
!
   COMMON/PRSIZE/COUNT
!
   COMMON/NUMDAT/DATCNT
!
   REAL*8 TERM,X(1:96),RHO,FF3,DDDATA(1:4),REFHT
!
   COMMON/SPIDAT/IDATA
!
   COMMON/SOLU/X
!
   REAL*8 THETA
!
!
   IF(SST.EQ.1.OR.SQ.EQ.1.OR.SN.EQ.1) THEN
      OUTLYNE=&
      &'"OPDLIST" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
   IF(.NOT.OPMAP.OR..NOT.CPFNEXT) THEN
      OUTLYNE=&
      &'NO OPD MAP FIT COEFFICIENTS EXIST'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
!
!     DETERMINE THE REFERNCE APERTURE HEIGHT
!     OF THE REF SURFACE COORDINATES
   IF(surf_clap_type(NEWREF) >= 1.AND.surf_clap_type(NEWREF) <= 5.AND.surf_array_parity(NEWREF) == 0) THEN
      IF(surf_clap_type(NEWREF) == 1) THEN
         IF(surf_clap_dim(NEWREF, 1).LE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RECT CLAP
!
      IF(surf_clap_type(NEWREF) == 2) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        ELIP CLAP
!
      IF(surf_clap_type(NEWREF) == 3) THEN
         IF(surf_clap_dim(NEWREF, 1).GE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RCTK CLAP
!
      IF(surf_clap_type(NEWREF) == 4) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        POLY CLAP
!
      IF(surf_clap_type(NEWREF) == 5) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 1))
      END IF
!        IPOLY CLAP
!
      IF(surf_clap_type(NEWREF) == 6) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 5))
      END IF
   ELSE
!       NO CLAP ON REF SURF.
      IF(PXTRAY(1,NEWREF).GE.PXTRAX(1,NEWREF)) THEN
         REFHT=PXTRAY(1,NEWREF)
      ELSE
         REFHT=PXTRAX(1,NEWREF)
      END IF
   END IF
!
!       PROCEED WITH LISTING
!
!       WRITE THE HEADING THEN THE DATA
   WRITE(OUTLYNE,1106)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1105)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1106)
   CALL SHOWIT(0)
!

   OPEN64 = isSPOFileOpen('OPDDAT.DAT')
   inquire(iolength=rec64) DDDATA(1),DDDATA(2),DDDATA(3),DDDATA(4)
   !INQUIRE(FILE=trim(LIBSPO)//'OPDDAT.DAT',OPENED=OPEN64)
   IF(.NOT.OPEN64)&
   &OPEN(UNIT=64,ACCESS='DIRECT',FILE=trim(LIBSPO)//'OPDDAT.DAT',&
   &FORM='UNFORMATTED',RECL=rec64,STATUS='UNKNOWN')
   READ(UNIT=64,REC=1) INUMBER
!
   DO IIIII=1,INUMBER-1
      READ(UNIT=64,REC=IIIII+1)&
      &DDDATA(1),DDDATA(2),DDDATA(3),DDDATA(4)
!       PROCEED WITH EVALUATION
      II=0
      TERM=0.0D0
      RHO=DSQRT((DDDATA(1)**2)+(DDDATA(2)**2))
      IF(DABS(DDDATA(1)).GE.&
      &DABS(((1.0D35)*DDDATA(2)))) THEN
         IF(DDDATA(1).GE.0.0D0) THETA=PII/2.0D0
         IF(DDDATA(1).LT.0.0D0) THETA=(3.0D0*PII)/2.0D0
      ELSE
         IF(DABS(DDDATA(1)).EQ.0.0D0.AND.DABS(DDDATA(2)).EQ.0.0D0)&
         &THEN
            THETA=0.0D0
         ELSE
            THETA=DATAN2(DDDATA(1),DDDATA(2))
         END IF
         IF(THETA.LT.0.0D0) THETA=THETA+(TWOPII)
      END IF
      DO I=1,37
         TERM=TERM+(X(I)*FF3(RHO,THETA,I))
      END DO
!       DO A LINE OF OUTPUT
      DDDATA(1)=DDDATA(1)*REFHT
      DDDATA(2)=DDDATA(2)*REFHT
      WRITE(OUTLYNE,1110) DDDATA(1),DDDATA(2),&
      &DDDATA(3),TERM,(DDDATA(3)-TERM)
      CALL SHOWIT(0)
   END DO
   CALL CLOSE_FILE(64,1)
   RETURN
!
1110 FORMAT(D15.8,1X,D15.8,1X,D15.8,1X,D15.8,1X,D15.8)
1106 FORMAT(1X)
1105 FORMAT('   Y-COORD     ',1X,'   X-COORD     ',&
   &1X,' INPUT  (OPD)  ',1X,&
   &' FITTED  (OPD) ',1X,'FITTING ERROR')
!
END
! SUB WRTCOEFS.FOR
SUBROUTINE WRTCOEFS
!
   use DATSP1
   use DATLEN
   use DATMAI
   IMPLICIT NONE
!
!       THIS IS THE SUBROUTINE WHICH
!       HANDLES THE "LISTZERN" COMMAND FROM THE CMD LEVEL
!
   EXTERNAL FF3
!
   INTEGER DATCNT,TYPE,COUNT,INUMBER,&
   &IDATA,I,II,III,IIII,IIIII
!
   LOGICAL OPMAP,OPEN64
!
   COMMON/OPOPMP/OPMAP
!
   COMMON/PRSIZE/COUNT
!
   COMMON/NUMDAT/DATCNT
!
   REAL*8 TERM,X(1:96),RHO,FF3,DDDATA(1:4),REFHT
!
   COMMON/SPIDAT/IDATA
!
   COMMON/SOLU/X
!
   REAL*8 THETA
!
!
   IF(SST.EQ.1.OR.SQ.EQ.1.OR.SN.EQ.1) THEN
      OUTLYNE=&
      &'"LISTZERN" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
   IF(.NOT.OPMAP.OR..NOT.CPFNEXT) THEN
      OUTLYNE=&
      &'NO OPD MAP FIT COEFFICIENTS EXIST'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
!
!
!       PROCEED WITH LISTING
!
!       WRITE THE HEADING THEN THE DATA
   WRITE(OUTLYNE,1101)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1106)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1105)
   CALL SHOWIT(0)
   WRITE(OUTLYNE,1106)
   CALL SHOWIT(0)
!
   DO I=1,37
      WRITE(OUTLYNE,1110) I,X(I)
      CALL SHOWIT(0)
   END DO
   RETURN
!
1110 FORMAT(6X,I2,7X,1X,D15.8)
1106 FORMAT(1X)
1101 FORMAT(' ZERNIKE COEFFICIENT LIST FROM LAST WAVEFRONT FIT')
1105 FORMAT(' COEF. NUMBER  ',1X,'  COEF. VALUE  ')
END
! SUB WRTREPORT.FOR
SUBROUTINE WRTREPORT
!
   use DATLEN
   use DATMAI
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
!       THIS DOES THE LISTREPT COMMAND
!
   REAL*8 HIGHORD,VCF(1:37),EMN,NV &
   &,VC1,VC2,VC3,VC4,VC5,VC6,VC7,VC8,VC9,X(1:96)
!
   LOGICAL OPMAP
!
   COMMON/OPOPMP/OPMAP
!
!
   COMMON/SOLU/X
!
   INTEGER I
!
!
!
!               THIS IS A CMD LEVEL COMMAND ONLY
!
!               CHECK FOR ADDITIONAL INPUT AND
!               PRINT ERROR AND RETURN IF DISCOVERED.
!
   IF(is_command_query()) THEN
      WRITE(OUTLYNE,*)&
      &'"LISTREPT" GENERATES A REPORT FOR 37-TERM FRINGE ZERNIKE'
      CALL SHOWIT(1)
      WRITE(OUTLYNE,*)&
      &'WAVEFRONT FITTING RESULTS)'
      CALL SHOWIT(1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.SQ.EQ.1.OR.SN.EQ.1) THEN
      OUTLYNE=&
      &'"LISTREPT" TAKES NO EXPLICIT INPUT'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
   IF(.NOT.OPMAP.OR..NOT.CPFNEXT) THEN
      OUTLYNE=&
      &'NO OPD MAP FIT COEFFICIENTS EXIST'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
   WRITE(OUTLYNE,6)
6  FORMAT('  ')
   CALL SHOWIT(0)
   WRITE(OUTLYNE,5)
   CALL SHOWIT(0)
5  FORMAT('37-TERN FRINGE ZERNIKE REPORT')
   WRITE(OUTLYNE,40)
40 FORMAT &
   &('RMS WAVEFRONT ERROR IN WAVES (FROM THE LAST WAVEFRONT MAP FIT)')
   CALL SHOWIT(0)
   NV=0.0D0
   EMN=2.0D0
   VCF(1)=(EMN/(2.0D0*(NV+1.0D0)))*(X(1)**2)
   NV=1.0D0
   EMN=1.0D0
   VCF(2)=(EMN/(2.0D0*(NV+1.0D0)))*(X(2)**2)
   NV=1.0D0
   EMN=1.0D0
   VCF(3)=(EMN/(2.0D0*(NV+1.0D0)))*(X(3)**2)
   NV=2.0D0
   EMN=2.0D0
   VCF(4)=(EMN/(2.0D0*(NV+1.0D0)))*(X(4)**2)
   NV=2.0D0
   EMN=1.0D0
   VCF(5)=(EMN/(2.0D0*(NV+1.0D0)))*(X(5)**2)
   NV=2.0D0
   EMN=1.0D0
   VCF(6)=(EMN/(2.0D0*(NV+1.0D0)))*(X(6)**2)
   NV=3.0D0
   EMN=1.0D0
   VCF(7)=(EMN/(2.0D0*(NV+1.0D0)))*(X(7)**2)
   NV=3.0D0
   EMN=1.0D0
   VCF(8)=(EMN/(2.0D0*(NV+1.0D0)))*(X(8)**2)
   NV=4.0D0
   EMN=2.0D0
   VCF(9)=(EMN/(2.0D0*(NV+1.0D0)))*(X(9)**2)
   NV=3.0D0
   EMN=1.0D0
   VCF(10)=(EMN/(2.0D0*(NV+1.0D0)))*(X(10)**2)
   NV=3.0D0
   EMN=1.0D0
   VCF(11)=(EMN/(2.0D0*(NV+1.0D0)))*(X(11)**2)
   NV=4.0D0
   EMN=1.0D0
   VCF(12)=(EMN/(2.0D0*(NV+1.0D0)))*(X(12)**2)
   NV=4.0D0
   EMN=1.0D0
   VCF(13)=(EMN/(2.0D0*(NV+1.0D0)))*(X(13)**2)
   NV=5.0D0
   EMN=1.0D0
   VCF(14)=(EMN/(2.0D0*(NV+1.0D0)))*(X(14)**2)
   NV=5.0D0
   EMN=1.0D0
   VCF(15)=(EMN/(2.0D0*(NV+1.0D0)))*(X(15)**2)
   NV=6.0D0
   EMN=2.0D0
   VCF(16)=(EMN/(2.0D0*(NV+1.0D0)))*(X(16)**2)
   NV=4.0D0
   EMN=1.0D0
   VCF(17)=(EMN/(2.0D0*(NV+1.0D0)))*(X(17)**2)
   NV=4.0D0
   EMN=1.0D0
   VCF(18)=(EMN/(2.0D0*(NV+1.0D0)))*(X(18)**2)
   NV=5.0D0
   EMN=1.0D0
   VCF(19)=(EMN/(2.0D0*(NV+1.0D0)))*(X(19)**2)
   NV=5.0D0
   EMN=1.0D0
   VCF(20)=(EMN/(2.0D0*(NV+1.0D0)))*(X(20)**2)
   NV=6.0D0
   EMN=1.0D0
   VCF(21)=(EMN/(2.0D0*(NV+1.0D0)))*(X(21)**2)
   NV=6.0D0
   EMN=1.0D0
   VCF(22)=(EMN/(2.0D0*(NV+1.0D0)))*(X(22)**2)
   NV=7.0D0
   EMN=1.0D0
   VCF(23)=(EMN/(2.0D0*(NV+1.0D0)))*(X(23)**2)
   NV=7.0D0
   EMN=1.0D0
   VCF(24)=(EMN/(2.0D0*(NV+1.0D0)))*(X(24)**2)
   NV=8.0D0
   EMN=1.0D0
   VCF(25)=(EMN/(2.0D0*(NV+1.0D0)))*(X(25)**2)
   NV=5.0D0
   EMN=1.0D0
   VCF(26)=(EMN/(2.0D0*(NV+1.0D0)))*(X(26)**2)
   NV=5.0D0
   EMN=1.0D0
   VCF(27)=(EMN/(2.0D0*(NV+1.0D0)))*(X(27)**2)
   NV=6.0D0
   EMN=1.0D0
   VCF(28)=(EMN/(2.0D0*(NV+1.0D0)))*(X(28)**2)
   NV=6.0D0
   EMN=1.0D0
   VCF(29)=(EMN/(2.0D0*(NV+1.0D0)))*(X(29)**2)
   NV=7.0D0
   EMN=1.0D0
   VCF(30)=(EMN/(2.0D0*(NV+1.0D0)))*(X(30)**2)
   NV=7.0D0
   EMN=1.0D0
   VCF(31)=(EMN/(2.0D0*(NV+1.0D0)))*(X(31)**2)
   NV=8.0D0
   EMN=1.0D0
   VCF(32)=(EMN/(2.0D0*(NV+1.0D0)))*(X(32)**2)
   NV=8.0D0
   EMN=1.0D0
   VCF(33)=(EMN/(2.0D0*(NV+1.0D0)))*(X(33)**2)
   NV=9.0D0
   EMN=1.0D0
   VCF(34)=(EMN/(2.0D0*(NV+1.0D0)))*(X(34)**2)
   NV=9.0D0
   EMN=1.0D0
   VCF(35)=(EMN/(2.0D0*(NV+1.0D0)))*(X(35)**2)
   NV=10.0D0
   EMN=2.0D0
   VCF(36)=(EMN/(2.0D0*(NV+1.0D0)))*(X(36)**2)
   NV=12.0D0
   EMN=2.0D0
   VCF(37)=(EMN/(2.0D0*(NV+1.0D0)))*(X(37)**2)
   VC1=DSQRT(VCF(1))
   VC2=DSQRT(VCF(2))
   VC3=DSQRT(VCF(3))
   VC4=DSQRT(VCF(4))
   VC5=DSQRT(VCF(5))
   VC6=DSQRT(VCF(6))
   VC7=DSQRT(VCF(7))
   VC8=DSQRT(VCF(8))
   VC9=DSQRT(VCF(9))
   WRITE(OUTLYNE,100) VC1
   CALL SHOWIT(0)
100 FORMAT('                   CONSTANT TERM = ',G20.12)
   WRITE(OUTLYNE,200) VC2
   CALL SHOWIT(0)
200 FORMAT('                X-AXIS TILT TERM = ',G20.12)
   WRITE(OUTLYNE,300) VC3
   CALL SHOWIT(0)
300 FORMAT('                Y-AXIS TILT TERM = ',G20.12)
   WRITE(OUTLYNE,400) VC4
   CALL SHOWIT(0)
400 FORMAT('                      FOCUS TERM = ',G20.12)
   WRITE(OUTLYNE,500) VC5
   CALL SHOWIT(0)
500 FORMAT('         0 OR 90 DEG ASTIG. TERM = ',G20.12)
   WRITE(OUTLYNE,600) VC6
   CALL SHOWIT(0)
600 FORMAT('           +/-45 DEG ASTIG. TERM = ',G20.12)
   WRITE(OUTLYNE,700) VC9
   CALL SHOWIT(0)
700 FORMAT('        3RD ORDER SPHERICAL TERM = ',G20.12)
   WRITE(OUTLYNE,800) VC8
   CALL SHOWIT(0)
800 FORMAT('      3RD ORDER X-AXIS COMA TERM = ',G20.12)
   WRITE(OUTLYNE,900) VC7
   CALL SHOWIT(0)
900 FORMAT('      3RD ORDER Y-AXIS COMA TERM = ',G20.12)
   HIGHORD=0.0D0
   DO I=10,37
      HIGHORD=HIGHORD+VCF(I)
   END DO
   WRITE(OUTLYNE,1000) DSQRT(HIGHORD)
   CALL SHOWIT(0)
1000 FORMAT('              HIGHER ORDER TERMS = ',G20.12)
   HIGHORD=0.0D0
   DO I=1,37
      HIGHORD=HIGHORD+VCF(I)
   END DO
   WRITE(OUTLYNE,1100) DSQRT(HIGHORD)
   CALL SHOWIT(0)
1100 FORMAT('      (TOTAL) ALL TERMS INCLUDED = ',G20.12)
   HIGHORD=0.0D0
   DO I=2,37
      HIGHORD=HIGHORD+VCF(I)
   END DO
   WRITE(OUTLYNE,1201) DSQRT(HIGHORD)
   CALL SHOWIT(0)
1201 FORMAT('             (TOTAL) MINUS CONST = ',G20.12)
   HIGHORD=0.0D0
   DO I=4,37
      HIGHORD=HIGHORD+VCF(I)
   END DO
   WRITE(OUTLYNE,1200) DSQRT(HIGHORD)
   CALL SHOWIT(0)
1200 FORMAT('      (TOTAL) MINUS CONST & TILT = ',G20.12)
   HIGHORD=0.0D0
   DO I=5,37
      HIGHORD=HIGHORD+VCF(I)
   END DO
   WRITE(OUTLYNE,1300) DSQRT(HIGHORD)
   CALL SHOWIT(0)
1300 FORMAT('(TOTAL) MINUS CONST,TILT & FOCUS = ',G20.12)
!
   RETURN
END
! SUB AWRTSUM.FOR
SUBROUTINE AWRTSUM
   use zoa_file_handler, only: doesFileExist
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
!     THIS IS SUBROUTINE AWRTSUM.FOR.
!     THIS WRITES A SUMMED SPOT DIAGRAM TO THE FILE WHOSE
!     NAME IS THE QUALIFIER WORD AND WHOSE EXT IS JUST (ASC)
!     (ASCII VERSION)
!
   LOGICAL OPEN65,EXIS65,EXIS32,OPEN32
!
   INTEGER I,JKNN,FJKNN
!
   CHARACTER NAMER*8,FNAMER*8
!
!
   IF(is_command_query()) THEN
      OUTLYNE=&
      &'"AWRTSUM" WRITES A SUMMED SPOT DIAGRAM TO AN ASCII FILE'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & '"AWRTSUM" REQUIRES EXPLICIT QUALIFIER INPUT'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(SN.EQ.1) THEN
      CALL REPORT_ERROR_AND_FAIL('"AWRTSUM" TAKES NO NUMERIC INPUT'//'\n'//'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   NAMER=WQ
   IF(SST.EQ.0) WS(1:8)='SPOTS   '
   JKNN=8
   DO I=8,1,-1
      IF(NAMER(I:I).NE.' ') THEN
         JKNN=I
         GO TO 20
      END IF
   END DO
20 CONTINUE
   FNAMER=WS(1:8)
   FJKNN=8
   DO I=8,1,-1
      IF(FNAMER(I:I).NE.' ') THEN
         FJKNN=I
         GO TO 30
      END IF
   END DO
30 CONTINUE
   EXIS32=doesFileExist(trim(LIBSPO)//FNAMER(1:FJKNN)//'.DAT')
   IF(.NOT.EXIS32) THEN
      OUTLYNE=&
      &'SUMMED SPOT DIAGRAM DOES NOT EXIST TO WRITE TO DISK'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
!     SAVE THE SUMMED DIAGRAM TO THE NAMED FILE. IF THE NAME EXISTS,
!     OVERWRITE THE FILE
   EXIS65=doesFileExist(NAMER(1:JKNN)//'.ASC')
   IF(EXIS65) THEN
      OPEN(UNIT=65,ACCESS='SEQUENTIAL',BLANK='NULL'&
      &,FORM='FORMATTED',FILE=NAMER(1:JKNN)//'.ASC'&
      &,STATUS='UNKNOWN')
      CALL CLOSE_FILE(65,0)
   END IF
!     NOW OPEN FOR READING AND WRITING
   OPEN(UNIT=32,ACCESS='DIRECT',FILE=trim(LIBSPO)//&
   &FNAMER(1:FJKNN)//'.DAT',&
   &FORM='UNFORMATTED',RECL=(110*NRECL),STATUS='UNKNOWN')
!
   OPEN(UNIT=65,ACCESS='SEQUENTIAL',BLANK='NULL'&
   &,FORM='FORMATTED',FILE=NAMER(1:JKNN)//'.ASC'&
   &,STATUS='UNKNOWN')
!
!     READ FROM FILE THEN WRITE TO NAMER.ASC
!
   READ(UNIT=32,REC=1) ITOT
   WRITE(UNIT=65,FMT=200) ITOT
!
   DO I=2,ITOT
      READ(UNIT=32,REC=I) DSPOT(1),DSPOT(2),DSPOT(3),DSPOT(4)&
      &,DSPOT(5),DSPOT(6),DSPOT(7),DSPOT(8),DSPOT(9),DSPOT(10),&
      &DSPOT(11),DSPOT(12),DSPOT(13),DSPOT(14),DSPOT(15),DSPOT(16)&
      &,DSPOT(17)&
      &,DSPOT(18),DSPOT(19),DSPOT(20),DSPOT(21),DSPOT(22),DSPOT(23)&
      &,DSPOT(24)&
      &,DSPOT(25),DSPOT(26),DSPOT(27),DSPOT(28),DSPOT(29)&
      &,DSPOT(30),DSPOT(31),DSPOT(32),DSPOT(33),DSPOT(34),DSPOT(35)&
      &,DSPOT(36),DSPOT(37),DSPOT(38),DSPOT(39),DSPOT(40),DSPOT(41)&
      &,DSPOT(42),DSPOT(43),DSPOT(44),DSPOT(45),DSPOT(46),DSPOT(47)&
      &,DSPOT(48),DSPOT(49),DSPOT(50)
      WRITE(UNIT=65,FMT=100) DSPOT(1),DSPOT(2)
      WRITE(UNIT=65,FMT=100) DSPOT(3),DSPOT(4)
      WRITE(UNIT=65,FMT=100) DSPOT(5),DSPOT(6)
      WRITE(UNIT=65,FMT=100) DSPOT(7),DSPOT(8)
      WRITE(UNIT=65,FMT=100) DSPOT(9),DSPOT(10)
      WRITE(UNIT=65,FMT=100) DSPOT(11),DSPOT(12)
      WRITE(UNIT=65,FMT=100) DSPOT(13),DSPOT(14)
      WRITE(UNIT=65,FMT=100) DSPOT(15),DSPOT(16)
      WRITE(UNIT=65,FMT=100) DSPOT(17),DSPOT(18)
      WRITE(UNIT=65,FMT=100) DSPOT(19),DSPOT(20)
      WRITE(UNIT=65,FMT=100) DSPOT(21),DSPOT(22)
      WRITE(UNIT=65,FMT=100) DSPOT(23),DSPOT(24)
      WRITE(UNIT=65,FMT=100) DSPOT(25),DSPOT(26)
      WRITE(UNIT=65,FMT=100) DSPOT(27),DSPOT(28)
      WRITE(UNIT=65,FMT=100) DSPOT(29),DSPOT(30)
      WRITE(UNIT=65,FMT=100) DSPOT(31),DSPOT(32)
      WRITE(UNIT=65,FMT=100) DSPOT(33),DSPOT(34)
      WRITE(UNIT=65,FMT=100) DSPOT(35),DSPOT(36)
      WRITE(UNIT=65,FMT=100) DSPOT(37),DSPOT(38)
      WRITE(UNIT=65,FMT=100) DSPOT(39),DSPOT(40)
      WRITE(UNIT=65,FMT=100) DSPOT(41),DSPOT(42)
      WRITE(UNIT=65,FMT=100) DSPOT(43),DSPOT(44)
      WRITE(UNIT=65,FMT=100) DSPOT(45),DSPOT(46)
      WRITE(UNIT=65,FMT=100) DSPOT(47),DSPOT(48)
      WRITE(UNIT=65,FMT=100) DSPOT(49),DSPOT(50)
   END DO
100 FORMAT(D23.15,1X,D23.15)
200 FORMAT(I10)
!     FINISHED WRITING, CLOSE THE FILE NAMER.ASC
   CALL CLOSE_FILE(65,1)
   RETURN
END
! SUB BWRTSUM.FOR
SUBROUTINE BWRTSUM
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
!     THIS IS SUBROUTINE BWRTSUM.FOR.
!     THIS WRITES A SUMMED SPOT DIAGRAM TO THE FILE WHOSE
!     NAME IS THE QUALIFIER WORD AND WHOSE EXT IS JUST (SPD)
!     (BINARY VERSION)
!
   LOGICAL OPEN64,EXIS64,EXIS32,OPEN32
!
   INTEGER I,JKNN,FJKNN
!
   CHARACTER NAMER*8,FNAMER*8
!
!
   IF(is_command_query()) THEN
      OUTLYNE=&
      &'"BWRTSUM" WRITES A SUMMED SPOT DIAGRAM TO A BINARY FILE'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & '"BWRTSUM" REQUIRES EXPLICIT QUALIFIER INPUT'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(SN.EQ.1) THEN
      CALL REPORT_ERROR_AND_FAIL('"BWRTSUM" TAKES NO NUMERIC INPUT'//'\n'//'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   NAMER=WQ
   IF(SST.EQ.0) WS(1:8)='SPOTS   '
   JKNN=8
   DO I=8,1,-1
      IF(NAMER(I:I).NE.' ') THEN
         JKNN=I
         GO TO 20
      END IF
   END DO
20 CONTINUE
   FNAMER=WS(1:8)
   FJKNN=8
   DO I=8,1,-1
      IF(FNAMER(I:I).NE.' ') THEN
         FJKNN=I
         GO TO 30
      END IF
   END DO
30 CONTINUE
   OPEN(UNIT=32,ACCESS='DIRECT',FILE=trim(LIBSPO)//&
   &FNAMER(1:FJKNN)//'.DAT',&
   &FORM='UNFORMATTED',RECL=(110*NRECL),STATUS='UNKNOWN')
   EXIS32=.FALSE.
   INQUIRE(FILE=trim(LIBSPO)//FNAMER(1:FJKNN)//'.DAT',EXIST=EXIS32)
   IF(.NOT.EXIS32) THEN
      OUTLYNE=&
      &'SUMMED SPOT DIAGRAM DOES NOT EXISTS TO WRITE TO DISK'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
!     SAVE THE SPOT DIAGRAM TO THE NAMED FILE. IF THE NAME EXISTS,
!     OVERWRITE THE FILE
   OPEN64=.FALSE.
   INQUIRE(FILE=NAMER(1:JKNN)//'.SPD',EXIST=EXIS64)
   IF(EXIS64) THEN
      OPEN(UNIT=64,ACCESS='DIRECT',FILE=NAMER(1:JKNN)//'.SPD',&
      &FORM='UNFORMATTED',RECL=(110*NRECL),STATUS='UNKNOWN')
      CALL CLOSE_FILE(64,0)
   END IF
!     NOW OPEN FOR WRITING
   OPEN(UNIT=64,ACCESS='DIRECT',FILE=NAMER(1:JKNN)//'.SPD',&
   &FORM='UNFORMATTED',RECL=(110*NRECL),STATUS='UNKNOWN')
!
   OPEN(UNIT=32,ACCESS='DIRECT',FILE=trim(LIBSPO)//&
   &FNAMER(1:FJKNN)//'.DAT',&
   &FORM='UNFORMATTED',RECL=(110*NRECL),STATUS='UNKNOWN')
!
!     READ FROM FILE THEN WRITE TO NAMER.SPD
!
   READ(UNIT=32,REC=1) ITOT
   WRITE(UNIT=64,REC=1) ITOT
!
   DO I=2,ITOT
      READ(UNIT=32,REC=I) DSPOT(1),DSPOT(2),DSPOT(3),DSPOT(4)&
      &,DSPOT(5),DSPOT(6),DSPOT(7),DSPOT(8),DSPOT(9),DSPOT(10),&
      &DSPOT(11),DSPOT(12),DSPOT(13),DSPOT(14),DSPOT(15),DSPOT(16)&
      &,DSPOT(17)&
      &,DSPOT(18),DSPOT(19),DSPOT(20),DSPOT(21),DSPOT(22),DSPOT(23)&
      &,DSPOT(24)&
      &,DSPOT(25),DSPOT(26),DSPOT(27),DSPOT(28),DSPOT(29)&
      &,DSPOT(30),DSPOT(31),DSPOT(32),DSPOT(33),DSPOT(34),DSPOT(35)&
      &,DSPOT(36),DSPOT(37),DSPOT(38),DSPOT(39),DSPOT(40),DSPOT(41)&
      &,DSPOT(42),DSPOT(43),DSPOT(44),DSPOT(45),DSPOT(46),DSPOT(47)&
      &,DSPOT(48),DSPOT(49),DSPOT(50)
      WRITE(UNIT=64,REC=I) DSPOT(1),DSPOT(2),DSPOT(3),DSPOT(4)&
      &,DSPOT(5),DSPOT(6),DSPOT(7),DSPOT(8),DSPOT(9),DSPOT(10),&
      &DSPOT(11),DSPOT(12),DSPOT(13),DSPOT(14),DSPOT(15),DSPOT(16)&
      &,DSPOT(17)&
      &,DSPOT(18),DSPOT(19),DSPOT(20),DSPOT(21),DSPOT(22),DSPOT(23)&
      &,DSPOT(24)&
      &,DSPOT(25),DSPOT(26),DSPOT(27),DSPOT(28),DSPOT(29)&
      &,DSPOT(30),DSPOT(31),DSPOT(32),DSPOT(33),DSPOT(34),DSPOT(35)&
      &,DSPOT(36),DSPOT(37),DSPOT(38),DSPOT(39),DSPOT(40),DSPOT(41)&
      &,DSPOT(42),DSPOT(43),DSPOT(44),DSPOT(45),DSPOT(46),DSPOT(47)&
      &,DSPOT(48),DSPOT(49),DSPOT(50)
   END DO
!     FINISHED WRITING, CLOSE THE FILE NAMER.SPD
   CALL CLOSE_FILE(64,1)
!
   RETURN
END
!
! SUB AWRTSPOT.FOR
SUBROUTINE AWRTSPOT
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
!     THIS IS SUBROUTINE AWRTSPOT.FOR.
!     THIS WRITES THE CURRENT SPOT DIAGRAM TO THE FILE WHOSE
!     NAME IS THE QUALIFIER WORD AND WHOSE EXT IS JUST (ASC)
!     (ASCII VERSION)
!
   LOGICAL OPEN65,EXIS65
!
   INTEGER I,JKNN
!
   CHARACTER NAMER*8
!
!
   IF(is_command_query()) THEN
      OUTLYNE=&
      &'"AWRTSPOT" WRITES THE CURRENT SPOT DIAGRAM TO AN ASCII FILE'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & '"AWRTSPOT" REQUIRES EXPLICIT QUALIFIER INPUT'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.SN.EQ.1) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & '"AWRTSPOT" TAKES NO STRING OR NUMERIC INPUT'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(.NOT.SPDEXT) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & 'NO SPOT DIAGRAM EXISTS TO WRITE TO DISK'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   NAMER=WQ
   JKNN=8
   DO I=8,1,-1
      IF(NAMER(I:I).NE.' ') THEN
         JKNN=I
         GO TO 20
      END IF
   END DO
20 CONTINUE
!
!     SAVE THE SPOT DIAGRAM TO THE NAMED FILE. IF THE NAME EXISTS,
!     OVERWRITE THE FILE
   OPEN65=.FALSE.
   INQUIRE(FILE=NAMER(1:JKNN)//'.ASC',EXIST=EXIS65)
   IF(EXIS65) THEN
      OPEN(UNIT=65,ACCESS='SEQUENTIAL',BLANK='NULL'&
      &,FORM='FORMATTED',FILE=NAMER(1:JKNN)//'.ASC'&
      &,STATUS='UNKNOWN')
      CALL CLOSE_FILE(65,0)
   END IF
!     NOW OPEN FOR WRITING
   OPEN(UNIT=65,ACCESS='SEQUENTIAL',BLANK='NULL'&
   &,FORM='FORMATTED',FILE=NAMER(1:JKNN)//'.ASC'&
   &,STATUS='UNKNOWN')
!     READ FROM FILE THEN WRITE TO NAMER.ASC
!
   WRITE(UNIT=65,FMT=200) ITOT
!
   DO I=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=I-1
      CALL SPOTIT(4)
      WRITE(UNIT=65,FMT=100) DSPOT(1),DSPOT(2)
      WRITE(UNIT=65,FMT=100) DSPOT(3),DSPOT(4)
      WRITE(UNIT=65,FMT=100) DSPOT(5),DSPOT(6)
      WRITE(UNIT=65,FMT=100) DSPOT(7),DSPOT(8)
      WRITE(UNIT=65,FMT=100) DSPOT(9),DSPOT(10)
      WRITE(UNIT=65,FMT=100) DSPOT(11),DSPOT(12)
      WRITE(UNIT=65,FMT=100) DSPOT(13),DSPOT(14)
      WRITE(UNIT=65,FMT=100) DSPOT(15),DSPOT(16)
      WRITE(UNIT=65,FMT=100) DSPOT(17),DSPOT(18)
      WRITE(UNIT=65,FMT=100) DSPOT(19),DSPOT(20)
      WRITE(UNIT=65,FMT=100) DSPOT(21),DSPOT(22)
      WRITE(UNIT=65,FMT=100) DSPOT(23),DSPOT(24)
      WRITE(UNIT=65,FMT=100) DSPOT(25),DSPOT(26)
      WRITE(UNIT=65,FMT=100) DSPOT(27),DSPOT(28)
      WRITE(UNIT=65,FMT=100) DSPOT(29),DSPOT(30)
      WRITE(UNIT=65,FMT=100) DSPOT(31),DSPOT(32)
      WRITE(UNIT=65,FMT=100) DSPOT(33),DSPOT(34)
      WRITE(UNIT=65,FMT=100) DSPOT(35),DSPOT(36)
      WRITE(UNIT=65,FMT=100) DSPOT(37),DSPOT(38)
      WRITE(UNIT=65,FMT=100) DSPOT(39),DSPOT(40)
      WRITE(UNIT=65,FMT=100) DSPOT(41),DSPOT(42)
      WRITE(UNIT=65,FMT=100) DSPOT(43),DSPOT(44)
      WRITE(UNIT=65,FMT=100) DSPOT(45),DSPOT(46)
      WRITE(UNIT=65,FMT=100) DSPOT(47),DSPOT(48)
      WRITE(UNIT=65,FMT=100) DSPOT(49),DSPOT(50)
   END DO
   WRITE(UNIT=65,FMT=101) REFRY(1,NEWOBJ)
   WRITE(UNIT=65,FMT=101) REFRY(2,NEWOBJ)
   WRITE(UNIT=65,FMT=101) REFRY(3,NEWOBJ)
   WRITE(UNIT=65,FMT=101) REFRY(4,NEWOBJ)
   WRITE(UNIT=65,FMT=101) REFRY(5,NEWOBJ)
   WRITE(UNIT=65,FMT=101) REFRY(6,NEWOBJ)
   WRITE(UNIT=65,FMT=101) REFRY(32,NEWOBJ)
100 FORMAT(D23.15,1X,D23.15)
101 FORMAT(D23.15)
200 FORMAT(I5)
!     FINISHED WRITING, CLOSE THE FILE NAMER.ASC
   CALL CLOSE_FILE(65,1)
   RETURN
END
! SUB BWRTSPOT.FOR
SUBROUTINE BWRTSPOT
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
!     THIS IS SUBROUTINE BWRTSPOT.FOR.
!     THIS WRITES THE CURRENT SPOT DIAGRAM TO THE FILE WHOSE
!     NAME IS THE QUALIFIER WORD AND WHOSE EXT IS JUST (SPD)
!     (BINARY VERSION)
!
   LOGICAL OPEN64,EXIS64
!
   INTEGER I,JKNN
!
   CHARACTER NAMER*8
!
!
   IF(is_command_query()) THEN
      OUTLYNE=&
      &'"BWRTSPOT" WRITES THE CURRENT SPOT DIAGRAM TO A BINARY FILE'
      CALL SHOWIT(1)
      CALL REPORT_ERROR_AND_FAIL('NO ACTION TAKEN', 1)
      RETURN
   END IF
   IF(SQ.EQ.0) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & '"BWRTSPOT" REQUIRES EXPLICIT QUALIFIER INPUT'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(SST.EQ.1.OR.SN.EQ.1) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & '"BWRTSPOT" TAKES NO STRING OR NUMERIC INPUT'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   IF(.NOT.SPDEXT) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & 'NO SPOT DIAGRAM EXISTS TO WRITE TO DISK'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
   NAMER=WQ
   JKNN=8
   DO I=8,1,-1
      IF(NAMER(I:I).NE.' ') THEN
         JKNN=I
         GO TO 20
      END IF
   END DO
20 CONTINUE
!
!     SAVE THE SPOT DIAGRAM TO THE NAMED FILE. IF THE NAME EXISTS,
!     OVERWRITE THE FILE
   OPEN64=.FALSE.
   INQUIRE(FILE=NAMER(1:JKNN)//'.SPD',EXIST=EXIS64)
   IF(EXIS64) THEN
      OPEN(UNIT=64,ACCESS='DIRECT',FILE=NAMER(1:JKNN)//'.SPD',&
      &FORM='UNFORMATTED',RECL=(110*NRECL),STATUS='UNKNOWN')
      CALL CLOSE_FILE(64,0)
   END IF
!     NOW OPEN FOR WRITING
   OPEN(UNIT=64,ACCESS='DIRECT',FILE=NAMER(1:JKNN)//'.SPD',&
   &FORM='UNFORMATTED',RECL=(110*NRECL),STATUS='UNKNOWN')
!     READ FROM FILE THEN WRITE TO NAMER.SPD
!
   WRITE(UNIT=64,REC=1) ITOT
!
   DO I=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=I-1
      CALL SPOTIT(4)
      WRITE(UNIT=64,REC=I) DSPOT(1),DSPOT(2),DSPOT(3),DSPOT(4)&
      &,DSPOT(5),DSPOT(6),DSPOT(7),DSPOT(8),DSPOT(9),DSPOT(10),&
      &DSPOT(11),DSPOT(12),DSPOT(13),DSPOT(14),DSPOT(15),DSPOT(16)&
      &,DSPOT(17)&
      &,DSPOT(18),DSPOT(19),DSPOT(20),DSPOT(21),DSPOT(22),DSPOT(23)&
      &,DSPOT(24)&
      &,DSPOT(25),DSPOT(26),DSPOT(27),DSPOT(28),DSPOT(29)&
      &,DSPOT(30),DSPOT(31),DSPOT(32),DSPOT(33),DSPOT(34),DSPOT(35)&
      &,DSPOT(36),DSPOT(37),DSPOT(38),DSPOT(39),DSPOT(40),DSPOT(41)&
      &,DSPOT(42),DSPOT(43),DSPOT(44),DSPOT(45),DSPOT(46),DSPOT(47)&
      &,DSPOT(48),DSPOT(49),DSPOT(50)
   END DO
   WRITE(UNIT=64,REC=ITOT+1)&
   &REFRY(1,NEWOBJ),REFRY(2,NEWOBJ),REFRY(3,NEWOBJ),REFRY(4,NEWOBJ),&
   &REFRY(5,NEWOBJ),REFRY(6,NEWOBJ),REFRY(32,NEWOBJ)
!     FINISHED WRITING, CLOSE THE FILE NAMER.SPD
   CALL CLOSE_FILE(64,1)
   RETURN
END
! SUB STATT.FOR

SUBROUTINE STATT
!
   use DATSP1
   use DATMAI
   use command_utils, only: is_command_query
   IMPLICIT NONE
!
!       THIS IS SUBROUTINE STATT.FOR.
!
!
   IF(SST.EQ.1.OR.SN.EQ.1) THEN
      OUTLYNE=&
      &'"STATS" TAKES NO STRING OR NUMERIC INPUT'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(SQ.EQ.0.OR.is_command_query()) THEN
      IF(STATSP)       WRITE(OUTLYNE,100)
      IF(.NOT. STATSP) WRITE(OUTLYNE,200)
      CALL SHOWIT(0)
      RETURN
   ELSE
   END IF
   IF(WQ.NE.'FULL'.AND.WQ.NE.'MIN') THEN
      OUTLYNE=&
      &'INVALID QUALIFIER USED WITH "STATS"'
      CALL SHOWIT(1)
      OUTLYNE=&
      &'RE-ENTER COMMAND'
      CALL SHOWIT(1)
      CALL MACFAL
      RETURN
   END IF
   IF(WQ.EQ.'FULL') STATSP=.TRUE.
   IF(WQ.EQ.'MIN') STATSP=.FALSE.
100 FORMAT('SPOT DIAGRAM STATISTICS ARE CURRENTLY SET TO "FULL"')
200 FORMAT('SPOT DIAGRAM STATISTICS ARE CURRENTLY SET TO "MIN"')
!
   RETURN
END
! SUB SPSAVE.FOR
SUBROUTINE SPSAVE
   use zoa_file_handler, only: clear_file, doesFileExist,&
   &isSPOFileOpen, clear_file
!
   use DATSP1
   use DATSPD
   use DATLEN
   use DATMAI
   IMPLICIT NONE
!
   LOGICAL EXIS32,OPEN32
!
   INTEGER I,J,K,N
!
   REAL*8 SPT1,SPT2,SPT3,SPT4,SPT5,SPT6,SPT7,SPT8 &
   &,SPT9,SPT10
!
   COMMON/SPTWTS/SPT1,SPT2,SPT3,SPT4,SPT5 &
   &,SPT6,SPT7,SPT8,SPT9,SPT10
!
!
   IF(SST.EQ.1.OR.S2.EQ.1.OR.S3.EQ.1.OR.S4.EQ.1.OR.S5.EQ.1) THEN
      CALL REPORT_ERROR_AND_FAIL(&
      & '"SPDSAVE" OR "SPDADD" TAKE NO'//'\n'//&
      & 'STRING OR NUMERIC WORD #2 THROUGH #5 INPUT'//'\n'//&
      & 'RE-ENTER COMMAND', 1)
      RETURN
   END IF
!
   IF(DF1.EQ.1) W1=1.0D0
   IF(SQ.EQ.0)  WQ='SPOTS'
!
   DO I=8,1,-1
      IF(WQ(I:I).NE.' ') THEN
         N=I
         GO TO 10
      END IF
   END DO
10 CONTINUE
!
!       SAVE
   IF(WC.EQ.'SPDSAVE') THEN
      EXIS32=doesFileExist(trim(LIBSPO)//WQ(1:N)//'.DAT')
      IF(EXIS32) THEN
!       DELETE IT
         call clear_file(trim(LIBSPO)//WQ(1:N)//'.DAT')
      END IF
      OPEN(UNIT=32,ACCESS='DIRECT',FILE=trim(LIBSPO)//WQ(1:N)//'.DAT',&
      &FORM='UNFORMATTED',RECL=(110*NRECL),STATUS='UNKNOWN')
!
      K=2
      IF(.NOT.SPDEXT) THEN
         CALL REPORT_ERROR_AND_FAIL(&
         & 'NO SPOT DIAGRAM EXISTS TO SAVE OR ADD'//'\n'//&
         & 'RE-ENTER COMMAND', 1)
         RETURN
      END IF
      IF(SPDEXT) THEN
         DO I=2,ITOT+1
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
            ID=I-1
            CALL SPOTIT(4)
            DSPOT(12)=DSPOT(12)*W1
            DSPOT(37)=DSPOT(12)*RAYRAY(9,NEWIMG)
            IF(DSPOT(12).NE.0.0D0) THEN
               WRITE(UNIT=32,REC=K)&
               &DSPOT(1),DSPOT(2),DSPOT(3),DSPOT(4),&
               &DSPOT(5),DSPOT(6),DSPOT(7),DSPOT(8),&
               &DSPOT(9),DSPOT(10),DSPOT(11),DSPOT(12),&
               &DSPOT(13),DSPOT(14),DSPOT(15),DSPOT(16),&
               &DSPOT(13),DSPOT(14),DSPOT(15),DSPOT(16),&
               &DSPOT(17),DSPOT(18),DSPOT(19),DSPOT(20),&
               &DSPOT(21),DSPOT(22),DSPOT(23),DSPOT(24)&
               &,DSPOT(25),DSPOT(26),DSPOT(27),DSPOT(28),DSPOT(29)&
               &,DSPOT(30),DSPOT(31),DSPOT(32),DSPOT(33),DSPOT(34),DSPOT(35)&
               &,DSPOT(36),DSPOT(37),DSPOT(38),DSPOT(39),DSPOT(40),DSPOT(41)&
               &,DSPOT(42),DSPOT(43),DSPOT(44),DSPOT(45),DSPOT(46),DSPOT(47)&
               &,DSPOT(48),DSPOT(49),DSPOT(50)
!       COMPUT THE RECORD NUMBER OF THE NEXT RECORD TO BE WRITTEN
               K=K+1
            END IF
         END DO
!       WRITE THE RECORD NUMBER OF THE LAST RECORD
         WRITE(UNIT=32,REC=1) K-1
         CALL CLOSE_FILE(32,1)
         RETURN
      ELSE
      END IF
      IF(.NOT.SPDEXT) THEN
         CALL REPORT_ERROR_AND_FAIL(&
         & 'NO SPOT DIAGRAM EXISTS TO SAVE OR ADD'//'\n'//&
         & 'RE-ENTER COMMAND', 1)
         RETURN
      END IF
   ELSE
!       NOT SPDSAVE
   END IF
!       SPDADD
   IF(WC.EQ.'SPDADD') THEN
!
      EXIS32=doesFileExist(trim(LIBSPO)//WQ(1:N)//'.DAT')
      IF(.NOT.EXIS32) THEN
!       NO FILE EXISTS, ERROR AND STOP
         CALL REPORT_ERROR_AND_FAIL(&
         & 'NO '//WQ(1:N)//'.DAT FILE EXISTS TO ADD ON TO'//'\n'//&
         & 'NO ACTION TAKEN', 1)
         RETURN
      ELSE
!       PROCEED
      END IF
!       SPOTS.DAT EXISTS, IF NOT OPEN, OPEN IT
      OPEN32=isSPOFileOpen(WQ(1:N)//'.DAT')
      IF(.NOT.OPEN32) THEN
         OPEN(UNIT=32,ACCESS='DIRECT',FILE=trim(LIBSPO)//WQ(1:N)//'.DAT',&
         &FORM='UNFORMATTED',RECL=(110*NRECL),STATUS='UNKNOWN')
      ELSE
!       IT WAS OPENED, PROCEED
      END IF
!
!       READ THE RECORD NUMBER OF THE LAST RECORD IN THE FILE
      READ(UNIT=32,REC=1) K
!       CREATE THE NEXT RECORD NUMBER TO WRITE
      K=K+1
!       ADD THE CURRENT SPOT DIAGRAM
      IF(.NOT.SPDEXT) THEN
         CALL REPORT_ERROR_AND_FAIL(&
         & 'NO SPOT DIAGRAM EXISTS TO SAVE OR ADD'//'\n'//&
         & 'RE-ENTER COMMAND', 1)
         RETURN
      END IF
      IF(SPDEXT) THEN
         DO I=2,ITOT+1
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
            ID=I-1
            CALL SPOTIT(4)
            DSPOT(12)=DSPOT(12)*W1
            DSPOT(37)=DSPOT(12)*RAYRAY(9,NEWIMG)
            IF(DSPOT(12).NE.0.0D0) THEN
               WRITE(UNIT=32,REC=K)&
               &DSPOT(1),DSPOT(2),DSPOT(3),DSPOT(4),&
               &DSPOT(5),DSPOT(6),DSPOT(7),DSPOT(8),&
               &DSPOT(9),DSPOT(10),DSPOT(11),DSPOT(12),&
               &DSPOT(13),DSPOT(14),DSPOT(15),DSPOT(16),&
               &DSPOT(13),DSPOT(14),DSPOT(15),DSPOT(16),&
               &DSPOT(17),DSPOT(18),DSPOT(19),DSPOT(20),&
               &DSPOT(21),DSPOT(22),DSPOT(23),DSPOT(24)&
               &,DSPOT(25),DSPOT(26),DSPOT(27),DSPOT(28),DSPOT(29)&
               &,DSPOT(30),DSPOT(31),DSPOT(32),DSPOT(33),DSPOT(34),DSPOT(35)&
               &,DSPOT(36),DSPOT(37),DSPOT(38),DSPOT(39),DSPOT(40),DSPOT(41)&
               &,DSPOT(42),DSPOT(43),DSPOT(44),DSPOT(45),DSPOT(46),DSPOT(47)&
               &,DSPOT(48),DSPOT(49),DSPOT(50)
               K=K+1
            END IF
         END DO
!       WRITE THE TOTAL NUMBER OF RECORD WRITTEN
         WRITE(UNIT=32,REC=1) K-1
         CALL CLOSE_FILE(32,1)
         RETURN
      END IF
      IF(.NOT.SPDEXT) THEN
         CALL REPORT_ERROR_AND_FAIL(&
         & 'NO SPOT DIAGRAM EXISTS TO SAVE OR ADD'//'\n'//&
         & 'RE-ENTER COMMAND', 1)
         RETURN
      END IF
   ELSE
!       NOT SPDADD
   END IF
   RETURN
END
! SUB OPDLOD2.FOR
SUBROUTINE OPDLOD2
   use zoa_file_handler, only: clear_file
!
   use DATSP1
   use DATLEN
   use DATMAI
   use mod_surface
   IMPLICIT NONE
!
   EXTERNAL FF3
!
   INTEGER SSN,SM,NP2,MP,COUNT,I,J,N,M,II,IIP
!
   LOGICAL OPMAP,OPEN64,ERROP
!
   COMMON/OPOPMP/OPMAP
!
   COMMON/PRSIZE/COUNT
!
!       THIS PASSES THE SOLUTION OF THE LEAST SQUARES PROBLEM
   COMMON/SOLU/X
!
   REAL*8 ACCUM(1:96,1:96),REFHT,&
   &CCOL(1:96),&
   &X(1:96)
!
   COMMON/ACDATA/ACCUM,CCOL
!
   INTEGER III,JJ,KK,ALLOERR,WVNUMOP


!
   REAL*8 DWW1,DWW2,DWW3,DWW4,&
   &TERM,FF3,RHO,THETA
!
   COMMON/OPDFIT1/ERROP
   COMMON/OPDFIT2/WVNUMOP
!
!
   REAL*8 W,V,U,&
   &B,XXX
!
   DIMENSION W(:),V(:,:),U(:,:),&
   &B(:),XXX(:)
!
   ALLOCATABLE :: W,V,U,B,XXX
   ALLOCATE (W(1:96),V(1:96,1:96),U(1:96,1:96),B(1:96),XXX(1:96)&
   &,STAT=ALLOERR)
!
!       DWW1=REF SURF Y-COORDINATE
!       DWW2=REF SURF X-COORDINATE
!       DWW3=OPD VALUE
!       DWW4=INTENSITY VALUE
!
!
   IF(.NOT.CPFNEXT) THEN
      CALL MACFAL
      DEALLOCATE(U,W,V,XXX,B,STAT=ALLOERR)
      ERROP=.TRUE.
      RETURN
   END IF
   CCOL(1:96)=0.0D0
   CFTYPE(1:96)=0.0D0
   X(1:96)=0.0D0
   XXX(1:96)=0.0D0
   ACCUM(1:96,1:96)=0.0D0
!
!     DETERMINE THE REFERNCE APERTURE HEIGHT
!     OF THE REF SURFACE COORDINATES
   IF(surf_clap_type(NEWREF) >= 1.AND.surf_clap_type(NEWREF) <= 5.AND.surf_array_parity(NEWREF) == 0) THEN
      IF(surf_clap_type(NEWREF) == 1) THEN
         IF(surf_clap_dim(NEWREF, 1).LE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RECT CLAP
!
      IF(surf_clap_type(NEWREF) == 2) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        ELIP CLAP
!
      IF(surf_clap_type(NEWREF) == 3) THEN
         IF(surf_clap_dim(NEWREF, 1).GE.surf_clap_dim(NEWREF, 2)) THEN
            REFHT=surf_clap_dim(NEWREF, 1)
         ELSE
            REFHT=surf_clap_dim(NEWREF, 2)
         END IF
      END IF
!        RCTK CLAP
!
      IF(surf_clap_type(NEWREF) == 4) THEN
         REFHT=DSQRT((surf_clap_dim(NEWREF, 1)**2)+(surf_clap_dim(NEWREF, 2)**2))
      END IF
!        POLY CLAP
!
      IF(surf_clap_type(NEWREF) == 5) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 1))
      END IF
!        IPOLY CLAP
!
      IF(surf_clap_type(NEWREF) == 6) THEN
         REFHT=DABS(surf_clap_dim(NEWREF, 5))
      END IF
!
   ELSE
!       NO CLAP ON REF SURF.
      IF(PXTRAY(1,NEWREF).GE.PXTRAX(1,NEWREF)) THEN
         REFHT=PXTRAY(1,NEWREF)
      ELSE
         REFHT=PXTRAX(1,NEWREF)
      END IF
   END IF
!
   call clear_file(trim(LIBSPO)//'OPDDAT.DAT')
!
!     OPEN OPDDAT.DAT
!
   OPEN(UNIT=64,ACCESS='DIRECT',FILE=trim(LIBSPO)//'OPDDAT.DAT',&
   &FORM='UNFORMATTED',RECL=(10*NRECL),STATUS='UNKNOWN')
   KK=1
   DO IIP=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=IIP-1
      CALL SPOTIT(4)
!
      IF(DSPOT(16).EQ.WVNUMOP.AND.DSPOT(12).NE.0.0D0.OR.&
      &DSPOT(16).EQ.WVNUMOP.AND.DSPOT(12).EQ.0.0D0.AND.&
      &DSPOT(7).EQ.7.0D0) KK=KK+1
   END DO
   IF(KK.LT.37.0D0) THEN
!     NOT ENOUGH DATA FOR A FIT
      CALL MACFAL
      DEALLOCATE(U,W,V,XXX,B,STAT=ALLOERR)
      ERROP=.TRUE.
      RETURN
   END IF
!
   KK=1
   DO IIP=2,ITOT
!     LOAD DSPOT(*) WITH DSPOTT(*,ID)
      ID=IIP-1
      CALL SPOTIT(4)
!
      DWW1=DSPOT(6)/REFHT
      DWW2=DSPOT(5)/REFHT
      DWW3=DSPOT(4)/(TWOPII)
      DWW4=DSPOT(12)
!
      IF(DSPOT(16).EQ.WVNUMOP) THEN
!
!     DATA FOR DESIRED WAVELENGTH, PROCEED
!
!       PROCEED WITH FITTING A TYPE 3 TYPE/SURFACE
         RHO=DSQRT((DWW1**2)+(DWW2**2))
         IF(DABS(DWW1).GE.DABS(((1.0D35)*DWW2))) THEN
            IF(DWW1.GE.0.0D0) THETA=PII/2.0D0
            IF(DWW1.LT.0.0D0) THETA=(3.0D0*PII)/2.0D0
         ELSE
            IF(DABS(DWW1).EQ.0.0D0.AND.DABS(DWW2).EQ.0.0D0) THEN
               THETA=0.0D0
            ELSE
               THETA=DATAN2(DWW1,DWW2)
            END IF
            IF(THETA.LT.0.0D0) THETA=THETA+(TWOPII)
         END IF
!
         III=0
         DO I=1,37
!       FILL THE COLLUMN ARRAY
            III=III+1
!       CALCULATE COLUMN VECTOR
!       FUNCTION FF3 RETURNS THE CORRECT VALUE
!       FOR THE ITH ENTRY IN THE COLUMN VECTOR
!       WITHOUT THE GIVEN DEPENDENT VARIABLE VALUE
!       OF THE WEIGHT FUNCTION FACTORED IN. THIS IS
!       FOR THE STANDARD ZERNIKE. I RANGES FROM 1 TO 37
            TERM= FF3(RHO,THETA,I)
            TERM=TERM*DWW3*DWW4
            CCOL(III)=CCOL(III)+TERM
            JJ=0
            DO J=1,37
!       DO THE APPROPRIATE ROW FOR COLUMN I
               JJ=JJ+1
               TERM= FF3(RHO,THETA,I)*FF3(RHO,THETA,J)
               ACCUM(III,JJ)=ACCUM(III,JJ)+(DWW4*TERM)
            END DO
         END DO
         COUNT=III
!
!       ALL VALUES CALCULATED FOR THE CURRENT "DATA"
!       STATEMENT.
!
         KK=KK+1
         WRITE(UNIT=64,REC=KK) DWW1,DWW2,DWW3,DWW4
      END IF
   END DO
!     KK IS THE NUMBER OF FITTED DATA ITEMS
   WRITE(UNIT=64,REC=1) KK
!
!       THE LARGE ARRAY WITH ACCUMULATED DATA IS
!       ACCUM. THE COLUMN VECTOR WITH FUNCTIONAL DATA
!       IS CCOL.
   MP=96
   NP2=96
   N=COUNT
   M=COUNT
   I=COUNT
   B(1:I)=CCOL(1:I)
   J=COUNT
   U(1:I,1:J)=ACCUM(1:I,1:J)
!       DO SINGULAR VALUE DECOMPOSITION
!
   SM=M
   SSN=N
   CALL SVDCMP(U,SM,SSN,MP,NP2,W,V)
   M=SM
   N=SSN
!
!       SOLVE LINEAR EQUATION
!
   SM=M
   SSN=N
   CALL SVBKSB(U,W,V,SM,SSN,MP,NP2,B,XXX)
   M=SM
   N=SSN
!
!       SIMPLE DATA FIT
   II=0
   DO I=1,37
      II=II+1
      CFTYPE(I)=XXX(II)
      X(I)=CFTYPE(I)
   END DO
   DO I=38,96
      II=II+1
      CFTYPE(I)=0.0D0
      X(I)=CFTYPE(I)
   END DO
   OPMAP=.TRUE.
   DEALLOCATE(U,W,V,XXX,B,STAT=ALLOERR)
   ERROP=.FALSE.
   RETURN
END
